### ISSUE TITLE
RChain platform core dev work for Oct

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#1000]
### Benefit to RChain

address [core dev team bounty tickets](https://rchain.atlassian.net/wiki/spaces/CORE/pages/105938971/Bounties+for+Development+work) (in Jira)

### Budget and Objective

Worker | Work | Story Points | Rate | Reward | Reward %
-- | -- | -- | -- | -- | --
zsluedem | OPS-358 | 13 | $150 | $1,950 | 45%
xiphiness | RHOL-725 - 726 | 8 | $150 | $1,200 | 28%
glenbraun | CORE-1337 | 8 | $150 | $1,200 | 28%
  |   |   |   |   | 100%
  |   |   | Budget: | $4,350 |  

ref google sheet: [core-dev 201810](https://docs.google.com/spreadsheets/d/1cIarjRAZbMMSA3r07tLx2E6YAsmb_lzSJ6sGkUvXaCc/edit#gid=0)

_Estimated Budget of Task:_ **$6,000?**  N story points @ $150/story point (per #273)

_Estimated Timeline Required to Complete the Task:_ Oct 2018
_How will we measure completion?_ **[core PR request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
@AbnerZheng how many story points did you contribute to this month?

@Medha were there other contributors to bounty issues this month?

**Comment by KellyatPyrofex** [comment]
@zsluedem completed 13 story points in Oct. for his work on https://rchain.atlassian.net/browse/OPS-358

**Comment by dckc** [comment]
@KellyAtPyrofex tells me @zsluedem did https://rchain.atlassian.net/browse/OPS-358 ; that's 13 story points x $150 is $1950.

In [budget votes for this bounty][1] I just voted as such.

[1]: https://rewards.rchain.coop/index.php?-action=related_records_list&num=%3D1000&-relationship=BudgetVotes&-table=issue&--msg=Record+successfully+added+to+%22BudgetVotes%22+relationship.

**Comment by zsluedem** [comment]
@dckc @KellyatPyrofex Thanks. I voted myself.

**Comment by zsluedem** [comment]
Does this issue still need on budget vote?

**Comment by dckc** [comment]
Yes, it still needs a budget vote from someone such as @deannald .

**Comment by KellyatPyrofex** [comment]
@xiphiness completed https://github.com/rchain/rchain/pull/1578 that resolved https://rchain.atlassian.net/projects/RHOL/issues/RHOL-724
https://rchain.atlassian.net/projects/RHOL/issues/RHOL-725
https://rchain.atlassian.net/projects/RHOL/issues/RHOL-726

That's 8 points x $150 = $1200

@dckc FYI

**Comment by dckc** [comment]
@glenbraun points out he did 
https://rchain.atlassian.net/browse/CORE-1337 : 8 story points.

Darn... gotta adjust the numbers again.

**Comment by deannald** [comment]
I voted, but it doesn't look like it affected anything. Also, how does one go back and adjust the numbers for a budget that's been voted on already?

**Comment by KellyatPyrofex** [comment]
@glenbraun completed 
https://rchain.atlassian.net/browse/CORE-1337

That's 8 points x $150 = $1200

**Comment by golovach-ivan** [comment]
I did Rholang Lexer/Parser = https://github.com/golovach-ivan/RhoLP/
Lexer part done, it can check RhoLang sources and detect a lot of errors.
https://github.com/rchain/bounties/issues/1015
https://rchain.atlassian.net/browse/RHOL-1027
https://rchain.atlassian.net/browse/RHOL-1029
https://rchain.atlassian.net/browse/RHOL-1030
https://rchain.atlassian.net/browse/RHOL-1031

JoshyOrndorff checked my tool and liked it.

command-line tool in /bin folder
https://github.com/golovach-ivan/RhoLP/tree/master/bin

**Comment by dckc** [comment]
@golovach-ivan that's very promising work, but as far as I can tell, that code hasn't been merged into https://github.com/rchain/rchain . As I explained in https://github.com/rchain/bounties/issues/1015#issuecomment-436805224 , getting your work reviewed and accepted by the core dev team is the measure of completion for **core-dev** bounties.

**Comment by glenbraun** [comment]
I think it is interesting to write a parser. It is certainly useful to have a way to get the RhoTypes protobufs for any given Rholang code (assuming that's the data model this parser would use.

I would like to point out a way that you can use RChain itself to get the protobufs for any valid Rholang.

@"parser"!(
{
    new c, stdout(`rho:io:stdout`) in {
        contract c(x) = {
            stdout!(*x)
        }
    }
})

Using a client we can listenForDataAtName "parser" and receive the protobufs for the Rholang in the curly brackets. That is, just wrap any valid Rholang in curly brackets, send it on a name and then listen for that using a client, you'll get the protobufs graph of the Rholang. For example, the code above looks like this:

{ "news": [ { "bindCount": 2, "p": { "receives": [ { "binds": [ { "patterns": [ { "exprs": [ { "eVarBody": { "v": { "freeVar": 0 } } } ], "connectiveUsed": true } ], "source": { "exprs": [ { "eVarBody": { "v": { "boundVar": 1 } } } ], "locallyFree": "Ag==" }, "freeCount": 1 } ], "body": { "sends": [ { "chan": { "exprs": [ { "eVarBody": { "v": { "boundVar": 1 } } } ], "locallyFree": "Ag==" }, "data": [ { "exprs": [ { "eVarBody": { "v": { "boundVar": 0 } } } ], "locallyFree": "AQ==" } ], "locallyFree": "Aw==" } ], "locallyFree": "Aw==" }, "persistent": true, "bindCount": 1, "locallyFree": "Aw==" } ], "locallyFree": "Aw==" }, "uri": [ "rho:io:stdout" ] } ] }

I know we won't be able to send on public names in the future and will have to use a private name, but the concept is the same.

**Comment by dckc** [comment]
Interesting, but let's please discuss that work in #1015.

**Comment by glenbraun** [comment]
Sorry. Posted in #1015
