### ISSUE TITLE
RChain Blog Article: CoLab October Summary

### ISSUE THREAD

**Issue by owans** [rchain/bounties#1014]
Benefit to RChain:
Create further exposure of Cooperation Laboratory (CoLab) activities.
Encourage interested members and non-members to join the CoLab.

Budget and Objective:
Article size: No preference so long as the article clearly communicates the instructions accurately.
Links to resources: Only if applicable (Use REF: best practices)
Imagery: Only use Royalty-Free imagery sourced from the list below unless you are the owner of the photograph is screencapture. Here are some great links to thousands of free images:
https://pixabay.com/
https://www.pexels.com/
https://www.canva.com/photos/free/
http://photos.polarfox.com/
https://skitterphoto.com/photos/
Keywords?
Use any appropriate key words from this list, but sparingly or naturally.  
RChain Keywords.xlsx 

Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.

Estimated Budget of Task: $[200]
Approved By: Leah @planteater#9554 
Estimated Timeline Required to Complete the Task: [ 1 Month]
How will we measure completion? [Article is written, edited, reviewed, approved by RChain Blog team, and approved for publication]

*See CONTRIBUTING.md for details on budget and reward process.*

Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by plantether** [comment]
This has been approved for publication. @patrick727 @kitblake could you vote on this, please?

**Comment by kitblake** [comment]
Done, I'll see if I can marshal another budget vote..

**Comment by kitblake** [comment]
This issue is provisioned. 

Can we close these blog issues now? I'll do so, reopen if needed, and commenting can always happen.

**Comment by owans** [comment]
See post link;
https://www.rchain.coop/blog/colab-update-11-08-18/?utm_source=Social&utm_medium=LinkedIn&utm_campaign=CoLab%20Update%2011/07/18
