### ISSUE TITLE
RChain platform core dev work for Nov for (dev1)

### ISSUE THREAD

**Issue by KellyatPyrofex** [rchain/bounties#1016]
### Benefit to RChain
address core dev team bounty tickets (in Jira)

### Budget and Objective

Estimated Budget of Task: $6,000? N story points @ $150/story point (per #273)

_Separate issues per dev simplify reward accounting._

Estimated Timeline Required to Complete the Task: Oct 2018
How will we measure completion? [core PR request merged]

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by zsluedem** [comment]
pr for Nov I made.
https://github.com/rchain/rchain/pull/1924   5 story points
https://github.com/rchain/rchain/pull/1929   3 story points
https://github.com/rchain/rchain/pull/1894   Not configured story point

https://rchain.atlassian.net/browse/OPS-347 5 story points(not merged and canceled but discussed with Kelly)

**Comment by dckc** [comment]
@kellyatpyrofex how many story points total for @zsluedem?

Once we have that on record, I suggest we skip rewards.rchain.coop and let these github comments serve as votes. Then you should just send an invoice, @zsluedem

**Comment by KellyatPyrofex** [comment]
Apologies for the delay. I confirm this work.

- rchain/rchain#19245 story points
- rchain/rchain#1929 3 story points
- rchain/rchain#1894 5 story points
- https://rchain.atlassian.net/browse/OPS-347 5 story points

This is a total of 18 story points @ $150/story point for a grand total of $2,700.

**Comment by dckc** [comment]
@zsluedem please send an invoice for $2,700 for 18 story points of core dev work in Nov.

Unless that process is a problem, please close this issue.

**Comment by dckc** [comment]
Please make a new issue, @zsluedem
