### ISSUE TITLE
RChain platform core Jan 2019 work for Dec for (dev1)

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#1021]
### Benefit to RChain
address core dev team bounty tickets (in Jira)

### Budget and Objective

Estimated Budget of Task: **25** story points @ $150/story point (per #273) total = 3750$

_Separate issues per dev simplify reward accounting._

Estimated Timeline Required to Complete the Task: Jan 2019

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by zsluedem** [comment]
jira ticket for the dev in Jan 2019.

* https://rchain.atlassian.net/browse/RCHAIN-2211  8 story points
* https://rchain.atlassian.net/browse/RCHAIN-2841  3 story points
* https://rchain.atlassian.net/browse/RCHAIN-2842  3 story points
* https://rchain.atlassian.net/browse/RCHAIN-2878   8 story points
* https://rchain.atlassian.net/browse/RCHAIN-2843  3 story points

total ： **25** story ponits.

**Comment by zsluedem** [comment]
@dckc @KellyatPyrofex

**Comment by KellyatPyrofex** [comment]
I confirm Will's completion of the stated work representing 25 story points @$150/story point = $3750.00

**Comment by dckc** [comment]
This all looks good.
