### ISSUE TITLE
telegram subscribers

### ISSUE THREAD

**Issue by Abdurrehman1** [rchain/bounties#1022]
Measure of Completion: 1500 Telegram Members in the RChain Official Telegram Chat Group: @rchain_coop Telegram Chat Invite Link: https://t.me/joinchat/AAAAAEM1_8pWfDST60gjcg
Suggested Budget: $7,500

**Comment by zsluedem** [comment]
I don't think we have bounties for non-development activities.

**Comment by zsluedem** [comment]
And you post a non-relevant link.
