### ISSUE TITLE
M> Wrong reference to slack in Architecture Doc

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#128]
In Architecture Document [Rate limiting mechanism](http://rchain-architecture.readthedocs.io/en/latest/execution_model/rhovm.html#rate-limiting-mechanism) is a reference to Slack #rhovm.

I think it has to be replaced by a channel in Discord #development 

Citation:
*For more details join the #rhovm channel on the RChain Slack here. Compiler work can be seen on GitHub.*

**Comment by lapin7** [comment]
@JosDenmark please change this Slack link into something more actual

**Comment by dckc** [comment]
looks like this was fixed Jan 31.
https://github.com/rchain/architecture-docs/commit/392535fe1355ecfe36851943c66cd1667f560852
