### ISSUE TITLE
O> Map Teams/Roles to Social Circles

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#131]
[ Team/Role Spreadsheet](https://docs.google.com/spreadsheets/d/1i548cX214_gxgZ1IPOKc7PSk1fUO8MVbIe6pesgZiZo/edit#gid=0)

1. Fill out team/roles spreadsheet as best as possible (minimum 5 - maximum 11)
2. Get consensus from team and roles
3. Map team/roles as circles within social ledger

**Comment by dckc** [comment]
@patrick727 is this still relevant to life as we know it? Or is it overtaken by events?
