### ISSUE TITLE
O> Attack Governance Model

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#135]
Phil's POV "a critical part of the security of the whole platform. one has to avoid that the coop ends up being a SPOF due to political centralization & centralization of development decisions as well as centralization of staking coins. after all the coop has a jurisdiction and that might be an SPOF as well.  I know it sounds weird at this point but maybe more restrictions of the coop's power might be better for the overall platform security. also it is much harder to restrict the power of the coop later on."

1. Define Governance Process' 
2. Postulate attack vectors
3. Test through small scale experiments within a Circle
4. Review the results

**Comment by Ojimadu** [comment]
https://docs.google.com/document/d/1EW0H833BsBZV9hWQC7cl3_KucMbckQfPpVQtEK3JOuQ/edit?usp=sharing

This a first draft i wrote, we would be need some volunteers to test these postulations.

**Comment by Keaycee** [comment]
This is also a [document](https://docs.google.com/document/d/1U3elyL4y-H8Z6uBU61tiO0sRTWu7DeRmPjfdYgpUOKY/edit?usp=sharing) on Governance process for your review. Make suggestions and correction if needed.

**Comment by dckc** [comment]
@pmoorman see? We've been talking about this openly for some time. This might be an even better place for your analysis than #261.

**Comment by TrenchFloat** [comment]
I'm assuming this has been solved by the web app in #260 and the trust metric in #375.

**Comment by dckc** [comment]
@Phistr90 be sure to explain why when you reopen an issue.
