### ISSUE TITLE
M> Curate Content for platform cooperativsm and goverance

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#137]
What we are doing is very much on the cutting edge so we should capture and present it in a way to the internet at large that works to establish RChain Cooperative as thought leaders in the space. Patrick will be the link for this between Governance and Marketing

**Comment by lapin7** [comment]
I made a movie about how to fill out the decentralized budget/spending 
  https://youtu.be/m6xiTWbEdpA?t=55

**Comment by patrick727** [comment]
@lapin7 I love it and we could use it, already shared through twitter, etc

**Comment by dckc** [comment]
@9rb do you still expect to work on this? What next step(s) do you have in mind?

@patrick727 is this still worth tracking? What would completion look like?

**Comment by pmoorman** [comment]
Closing this issue, in an effort to keep Github organised. 

(feel free to reopen, if still relevant!)
