### ISSUE TITLE
M> KY - Campaign Outline

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#138]
Outline the purpose of the campaign in a document. 

Outline the overview of the message we are getting across

[see notes document](https://docs.google.com/document/d/1Mi1JXoYu6zqQlsm12tIktSKA6FVe9mgpDnrCd-sMY_g/edit#)

[see campaign spreadsheet](https://docs.google.com/spreadsheets/u/2/d/1mKHdWF6-UhYqQ8J-Nk7QxgQuIvE5F1aY6AxSQpfaSrs/edit#gid=0)

**Comment by Ojimadu** [comment]
I thought there is still an open issue for this? Issue 98 precisely.

**Comment by patrick727** [comment]
yes and I will close that out.

**Comment by lapin7** [comment]
See the notes of the retreat
[Go+to+Market+breakout+notes]https://rchain.atlassian.net/wiki/spaces/DOC/pages/93552934/Go+to+Market+breakout+notes)

**Comment by Ken-dahl** [comment]
How are we handling invoices on this KY project now? What is the correct issue # to use in the Invoice. Do we have ledger to enter our hours in? Thank you

**Comment by lapin7** [comment]
Create a budget for #138 through [Pub Member Allocating Budget - Spending](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=634479823)
Here's a [webinar](https://www.youtube.com/watch?v=m6xiTWbEdpA&feature=youtu.be&t=57) that explains how to do it
Or have a [brief overview ](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md)

**Comment by plantether** [comment]
@patrick727 @lapin7 We don't have access to either of these documents: 
https://docs.google.com/document/d/1ZXy-7_lEzuPp0ptoO92CT3hz-fTXQF6RC0GNmGkzz3A
https://docs.google.com/spreadsheets/u/2/d/1mKHdWF6-UhYqQ8J-Nk7QxgQuIvE5F1aY6AxSQpfaSrs

We also need edit access to this doc, which is View Only for us:
https://docs.google.com/document/d/1Mi1JXoYu6zqQlsm12tIktSKA6FVe9mgpDnrCd-sMY_g

**Comment by pmoorman** [comment]
closing this issue because it seems the time for this has come and past. 

_Feel free to reopen if you still deem it relevant!_
