### ISSUE TITLE
M> KY - Identity ebook

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#139]
See the links below for drafted table of contents 

 - [EBook - Know Yourself](https://docs.google.com/document/d/1rePsjOK6pIfLe_5q6vfr62gkTgkG54TtHaLj0EJZ2g8/edit#heading=h.a02o7owja9e1)

- [Notes doc](https://docs.google.com/document/d/1Mi1JXoYu6zqQlsm12tIktSKA6FVe9mgpDnrCd-sMY_g)

 - [Own Yourself](https://docs.google.com/document/d/1ZXy-7_lEzuPp0ptoO92CT3hz-fTXQF6RC0GNmGkzz3A/edit#heading=h.ik5zjgxbaydk)

- Own Your Organization. 

[Taxonomy Document](https://docs.google.com/document/u/2/d/1PX17preGPNrQy9C6_YgNnPIoD1I6EdjKwQP_2uR4Ywc/edit#heading=h.st5rqoc1ayw0)

**Comment by Ojimadu** [comment]
"know yourself" link requires permission.

**Comment by plantether** [comment]
@patrick727 @lapin7 We don't have access to the directory that is supposed to contain these docs

**Comment by lapin7** [comment]
@patrick727 please add Access: rchain@googlegroups.com to each folder or document that you create for collaboration ;-)

**Comment by Keaycee** [comment]
@patrick727 Is there a link for "Own your organization"?

**Comment by lapin7** [comment]
Ideally those docs should be in a sub folder of [RChain (Greg Meredith) \ Members](https://drive.google.com/drive/folders/0Bx1gRG7UuoiJZ1lpSnZzenNzY00)

**Comment by plantether** [comment]
@patrick727 @lapin7 I have appropriate access to all docs now, Thanks. 

@jimscarver @9rb @jhngrant @kitblake @gsj5 @Ken-dahl , are you able to access all the docs now?

**Comment by jimscarver** [comment]
Yes. The Members gdoc folder is back. the google gfroup has permission. thanks @lapin7

**Comment by 9rb** [comment]
There's a budget issue on this item that needs to be fixed.  I will open BYOID as a separate development task, so that budgets are not commingled.

**Comment by plantether** [comment]
@jimscarver @9rb @jhngrant @kitblake @gsj5 @Ken-dahl @patrick727 @Ojimadu,

Jim and I created a new working document for the identity ebook:

[Working copy of Identity - "Know Thyself" - identity ebook](https://docs.google.com/document/d/1VCAsWgMrWX55eRHFkE7OCsqWvaHKjJrQezWEMZxQ9vM)

It's in a new [Identity e-book folder](https://drive.google.com/open?id=1-2Uguame7UjUOaPbmK4eXK2qjSyWQnFl) in the  Projects folder. please let us know if you are unable to access or edit it. 

It is created from the EBook document we've been working with and Ken's Taxonomy document. We left the other two documents as they were.

Please add comments, additions, objections now if you want. Otherwise we can go through it together in the meeting on Saturday.

**Comment by plantether** [comment]
Ia Amaka on github?

**Comment by makys** [comment]
Yep as @makys. I didn't get your email the last time.

**Comment by plantether** [comment]
@makys @jimscarver @9rb @jhngrant @kitblake @gsj5 @Ken-dahl @patrick727 @Ojimadu,

The next meeting is scheduled for 2018-02-24 at 10:00 AM EST, but we can change the time or date if necessary so Patrick and Kit can attend. 

Should we change the name of this issue to "Sovereign Identity Awareness Project"? Or create a new one?

Action items before next meeting on 2018-02-24 at 10:00 AM EST:

1. Jim(?) and Rao will begin discussions with LifeId
2. Leah will prepare presentations on a broad overview of the decentralized space in general 
3. Amaka will prepare a more focused review of identity issues 

Could anyone work on guiding the implementation of anonymous member voting? This was Ed's most urgent request in the previous meeting. Jim, could you do this while Rao (and Gurinder?) begin discussions with Chris from LifeId?

[BYOID project log](https://docs.google.com/document/d/1OVUGmxv4q1ywcxDG-V926lrXpkQNDs7n2eO2R5OJdOk)

**Comment by pmoorman** [comment]
@PatrickM727 @jimscarver @plantether @makys what's the status with this issue? Can we close it? Should we keep it?

Is there still any active work being done here?

**Comment by jimscarver** [comment]
This started with great enthusiasm but energy for this has gone to almost zero. and our weekly meeting has been repurposed so I'll take the liberty of closing this. The documents developed could be a bases for restarting this in the future if there is any renewed interest.
