### ISSUE TITLE
M> KY - Build List - PR Opportunities

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#141]
Build out a list of things that we can do in order to position this campaign as a through leadership campaign for the identity space. 

Example: 

Having representation in the Decentralized Identity Foundation
Attending large conferences
Presenting at smaller conferences
Newsjacking privacy related convo

etc.

**Comment by 8lcarte** [comment]
I know the folks at http://melrosepr.com/ I know they recently left another protocol level project and may be interested in working with RChain.

**Comment by llerner** [comment]
Cool. Look forward to introductions



========================
Lawrence I Lerner
o/m: 630.248.0663
lawrencelerner@gmail.com

Blog: lawrenceilerner.com
 <http://www.lawrenceilerner.com/>twitter: RevInnovator <https://twitter.com/#!/RevInnovator> 



On Jan 12, 2018, at 10:24 , Lee Carter <notifications@github.com> wrote:

I know the folks at http://melrosepr.com/ <http://melrosepr.com/> I know they recently left another protocol level project and may be interested in working with RChain.

**Comment by pmoorman** [comment]
closing this issue because it seems the time for this has come and past. 

_Feel free to reopen if you still deem it relevant!_
