### ISSUE TITLE
M> (G) "RChain" Style Guide

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#147]
Work on brand book and style guide for RChain

**Comment by drbloom** [comment]
[![Foo](http://www.coop/wp-content/uploads/2017/05/coop_blk-300x126.png)]

.COOP Global Cooperative Marque branding was discussed and **agreed upon** during the Co-op's January 26 staff meeting (no minutes taken). Full adoption of the Marque was applied for and granted to the Cooperative to use under these [Terms & Conditions](http://www.domains.coop/support/terms-conditions/). Executive Committee action is pending regarding the adoption or "full adoption" of the Marque.

### coop Marque

[Coop_marque.zip](http://www.coop/wp-content/uploads/2017/08/Coop_marque.zip) (2.31 MB)

### coop Marque with slogan

[English_slogan.zip](http://www.coop/wp-content/uploads/2017/08/English_slogan.zip) (2.66 MB)

### coop Marque with key messages

[English\_key\_messages.zip](http://www.coop/wp-content/uploads/2017/08/English_key_messages.zip) (19.21 MB)

### coop Marque Custom

[English_custom.zip](http://www.coop/wp-content/uploads/2017/08/English_custom.zip) (5.07 MB)

### Signature images – large

[jpg\_hr\_1.zip](http://www.coop/wp-content/uploads/2017/08/jpg_hr_1.zip) (16.05 MB)[jpg\_hr\_2.zip](http://www.coop/wp-content/uploads/2017/08/jpg_hr_2.zip) (22.96 MB)

### Signature images – medium

[jpg_mr.zip](http://www.coop/wp-content/uploads/2017/08/jpg_mr.zip) (29.61 MB)

### Signature images – small

[jpg_lr.zip](http://www.coop/wp-content/uploads/2017/08/jpg_lr.zip) (7.39 MB)

**Comment by dckc** [comment]
What would full adoption look like? How would  we know when we're done?
