### ISSUE TITLE
M> (G) Social media profile designs

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#151]
More social media profile images for 
- Medium
- Reddit

**Comment by nikhil9865** [comment]
We can scale this to reddit and medium
![Uploading IMG_0314 (1).jpg…]()

**Comment by ValeBF** [comment]
Would you like me to scale this design to the mentioned social media or you want to keep the new look I proposed ?

**Comment by patrick727** [comment]
@nikhil9865, @ValeBF  Id like to see some variations based on the proposed profile images in here 

For reddit specifically it'd be really cool to play of the aliens like how most people customize their subreddit. think of a cooperative of aliens building a decentralized teleportation network lol

[Members Google Drive](https://drive.google.com/drive/u/0/folders/0B1YxVxO-qg0CQlpHWElvTVo1cTQ)

**Comment by Ojimadu** [comment]
@nikhil9865 The colour composition of the picture above seem to need more contrast like an a dark outline for the text to increase readability and some the background image need to be consistent with the ones being created by @ValeBF

**Comment by ValeBF** [comment]
I am working in this I will show you soon

**Comment by ValeBF** [comment]
I would like to hear what you think of my construction of @patrick727  idea for the Reddit page.

<img width="216" alt="rai" src="https://user-images.githubusercontent.com/33433916/33350689-86a8736a-d476-11e7-87b7-3930137e3b73.png">

And in order to follow the style I am proposing the whole cover could look like this
![reddit-banner](https://user-images.githubusercontent.com/33433916/33350803-1ff8eb08-d477-11e7-82a5-2a5a9bcf30cf.jpg)

Please let me know what you think and also I would like to confirm the copy that should be on the social media images. Tx

**Comment by patrick727** [comment]
@ValeBF thank you,

so with reddit there is the background image and the subreddit profile image. The profile image should be the logo as you have it ant thats where I would put those three aliens, not the middle structure, just have them around the logo. 

as for the background it could be the rest of the image as is, id make the meshnet a bit lighter so it blends into the background more. 

thank you

**Comment by ValeBF** [comment]
Do you think work better like this ?

![rp](https://user-images.githubusercontent.com/33433916/33398214-95be5bd6-d524-11e7-8668-b7f4d78dffb1.jpg)

![reddit-banner](https://user-images.githubusercontent.com/33433916/33398233-a4bbea9a-d524-11e7-8bc7-eb804aa0bb36.jpg)

The graphics on the background are a little different to the previous, because I as long as I have been knowing more about the brand I understood the esthetic and the possibility to build a more solid graphics with meaning fore the same proposes that we have now.
[Graphic construction .pdf](https://github.com/rchain/Members/files/1515552/Graphic.construction.pdf)

Let me know what you thing and if I should procede to update the graphics I created previously. Thanks. VBF

**Comment by patrick727** [comment]
@ValeBF thank you

see https://www.reddit.com/r/eos/ and see hwo there are too images? 

One is the background and one is the profile image "eos"

For the profile image I like what you did with the aliens surrounding the logo, but would prefer that the logo with the text "rchain cooperative" remain unaltered and the aliens worked around the words too. 

For the background image(header) please just make that the the background image you have, no logo, no words, just hte color gradient and the meshnet.

please remove the "building scalability, etc..." entirely

also please design in a way that can be edited quickly if the logo changes. 

Thank you again

**Comment by ValeBF** [comment]
Yes I know that is going to be 2 images... It was just for visualization proposes let me fix that right now.

**Comment by patrick727** [comment]
@ValeBF sorry i didnt realize

thank you

**Comment by ValeBF** [comment]
I think i miss understood the propose of the images
First here is the cover image
![cover](https://user-images.githubusercontent.com/33433916/33402680-b630c520-d533-11e7-820c-5c2741848932.png)
Here you have the profile picture

**Comment by ValeBF** [comment]
For the medium profile here is the profile image
![rcs--p_medium](https://user-images.githubusercontent.com/33433916/33403634-85432684-d537-11e7-87a8-4776d6bf610a.png)

There is no cover for the profile. just cover for the posts  you tell me if it anyone needed right now

**Comment by patrick727** [comment]
those look good @ValeBF thank you!

**Comment by kitblake** [comment]
Those look **really** good :)

**Comment by fiebsy** [comment]
Probably a dumb question, but any reason why the Rchain sub says "(Unofficial)" on the search queue?

<img width="773" alt="screen shot 2017-11-30 at 8 34 56 pm" src="https://user-images.githubusercontent.com/34101760/33465527-f8e8e85e-d60d-11e7-84f5-ee03ff9ea73a.png">

**Comment by Ojimadu** [comment]
Those are really good images. Great work @ValeBF

**Comment by patrick727** [comment]
@fiebsy because we hadnt confirmed between r/rchain and r/rchain_offical

I think because /rchain is now completely under our ownership and that it has more subs, we can drop the other and make r/rchain the official

Cheers

**Comment by ResonanceXX** [comment]
Can the reddit sub be up and running. And what contents would be put on there to excite interested community members. The images are outstanding by the way.

**Comment by patrick727** [comment]
@ResonanceXX yes its up and running with all new content https://www.reddit.com/r/RChain/

@momchilov is working on getting the images up there ASAp but he has some work obligations. 

I think we should close down RChain_Offical asap, @Mervyn853 arent you the lead on that one?

**Comment by Mervyn853** [comment]
@patrick727  I believe @derek7272 is the original creator of the /r/RChain_Official subreddit. 

If i recall,  you can't delete a subreddit. The closest you can come is making it private and not letting anybody in, essentially parking in which is good for security reasons.

**Comment by patrick727** [comment]
thanks @Mervyn853, @derek7272 will you go ahead and privatize that subreddit so that we can promote the r/RChain as the official channel. 

Cheers

**Comment by derek7272** [comment]
sure. Done.

**Comment by Keaycee** [comment]
Job well done @ValeBF great work and collaborative effort.

**Comment by lapin7** [comment]
@fiebsy please send a msg to ops@rchain.coop

**Comment by pmoorman** [comment]
closing this, since Branding WG / Girvin would take care of this
