### ISSUE TITLE
M> (G) EBook covers and Brand Marks

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#153]
Cover and Brand Marks for
- Rholang Specs
- E Plurubis Unum 2.0 
- Platform Cooperatives with Blockchain
- "Know Yourself" Identity EBook
- "Own Yourself" Identity EBook

**Comment by ValeBF** [comment]
I have this preliminary version, the file still needs to be completed and I am attentive any comments you have
[EP2 1.0.pdf](https://github.com/rchain/Members/files/1703951/EP2.1.0.pdf)

**Comment by ValeBF** [comment]
this is a proposal of style for the  Know-Yourself Ebook, I still need the content to refine or complete this.
[Know-Yourself.pdf](https://github.com/rchain/Members/files/1704007/Know-Yourself.pdf)

**Comment by pmoorman** [comment]
Closing this because Branding WG & Girvin engagement will take care of this as relevant
