### ISSUE TITLE
O> Github, Mattermost, Discord, Telegram data feed into Google sheet

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#157]
The API's of Github, Mattermost, Discord, Telegram provide maybe a way to get a data feed into a Google sheet:
It would be great if I could get this data into [Pub](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=634479823):

Application | Issue Nr | Participant | Gsheet cel
-- | -- | -- | --
Github | 001 | Github ID 1| Budget 201711!R3
Github | 002 | Github ID 2| Budget 201711!U5

@Ryanmtate, @Jake-Gillberg any suggestions?

**Comment by lapin7** [comment]
@jimscarver Please don't add members to an issue. They prefer to do that themselves. Only assign yourself as you see a fit. :-)

**Comment by aviationhacker** [comment]
@lapin7 Jim & I have just been fiddling with the Zapier integration, and the Budgetbot is now back online on Mattermost. :)

**Comment by kitblake** [comment]
@aviationhacker Great, I really missed that notification. It was truly informative @jimscarver.

**Comment by lapin7** [comment]
@aviationhacker Wonderful!!

Please join rchain@googlegroups.com in order to get access to RChain Google documents.  https://groups.google.com/forum/#!managemembers/rchain/members/join

**Comment by jimscarver** [comment]
BugetBot was great for monitoring the reward system but now that we are off google sheets we need something similar to log events from the new reward system. Should we repurpose this issue or create a new one?

**Comment by lapin7** [comment]
@jimscarver you're right.
Maybe we can do something with the [Bounty App](https://rewards.rchain.coop/)

@dckc 
Suggested output to BudgetBot:

- date
- github_name
- new_budget_vote
- new_budget_voter
- new_reward_vote
- new_reward_voter
- budget
- reward
- provisional_budget
_ provisional_reward

**Comment by kdvalentine** [comment]
Nh.h.

**Comment by kdvalentine** [comment]
mL
mLl

**Comment by dckc** [comment]
I'm reviewing my assignments... the webhook idea here is somewhat buried. I did some technical exploration, but I'm not sure where this fits in my priorities, so rather than a new bounties issue I put it in https://github.com/dckc/rchain-dbr/issues/6
