### ISSUE TITLE
M> Policy - Official vs. Community - Assets

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#158]
M> Indicates that this task is in the "Marketing" Category 

Goal:

We will need to figure out a policy for the cooperative community channels. meaning how they can represent themselves and use the RChain assets. 

The draft should be reviewed by the Governance & Executive committee and then approved by the Board of Directors.

**Comment by patrick727** [comment]
@drbloom just linked this too me, important.
 
[.coop terms](http://www.coop/wp-content/uploads/2017/05/terms_of_use_for_the_global_coop_marque.pdf)

**Comment by dckc** [comment]
There was a trademark session at the Governance Forum; I'd appreciate it if somebody would cite the records from this issue, highlighting any follow-up items.
