### ISSUE TITLE
O> Define "Officers" and "Important Roles"

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#162]
The compensation committee needs to work with the governance and executive committee, and the financial team in order to define what Officer and other Important Co-op roles need to be filled in order to propose a compensation package for them.

**Comment by patrick727** [comment]
So in regards to Compensation Packages

9 Board of Directors

4 Officers
- President
- VP
- Secretary
- Treasurer 

"Important Roles" - ???
- Community Manager
- Director of Markeing
- COO
- CFO
- VP of HR
- Director of Development
- Developer Teams
 - comms
 - storage
 - VM
 - language
 - devops
 - mathematics

What do you all think about this? 

And then based on [financial forecast](https://docs.google.com/spreadsheets/d/1vGmDSpdYWsXjsFSI3ByH5j_Y1QpdPwnOyzt3bLBOwxA/edit#gid=1872922692)

1. is it only the Board who really needs a package determined
2. If all "important roles" receive a package, then how is that calculated within the forecast

**Comment by kennyrowe** [comment]
@patrick727 how many of the suggested important roles are currently filled?

**Comment by patrick727** [comment]
So i'm not sure about the "Director of Development" or "Director of Marketing" or "Community Manager" yes but aside from that I believe all the rest are.

**Comment by lapin7** [comment]
**Draft**
Channel  | Moderator |   |   |   |  
-- | -- | -- | -- | -- | --
[Official Website RChain](https://www.rchain.coop/) | @patrick727   | @branko  |   |   |  
[Member registration](https://member.rchain.coop/) | @leithaus | @n10n  |  |  |
[Newsletter](https://docs.google.com/document/d/1sRez-kki99HWwP6XhoumYAko9U5QS79Brfp2PNYSkGY/edit#) | @patrick727   |   |   |   |  
[Chinese RChain](https://rchain.site) | @Mervyn853   | @sportshark   |   |   |  
[Draft new RChain](https://rchain.site) | @Rafkraft   |   |   |   |  
[Discord (Private)](https://discord.gg) | [Requires Membership](https://member.rchain.coop/)   | @drbloom   |   |   |  
[Discord (Public)](https://discord.gg/fvY8qhx) |   |   |   |   |  
[Slack](https://ourchain.slack.com/)  | (To be phased out and replaced by Private Discord)  |   |   |   | 
[Github/members](https://github.com/rchain/Members/) | @lapin7 |   |   |   |  
[Google groups](https://groups.google.com/forum/#!forum/rchain) | @lapin7 | @jimscarver |   |   | 
[Telegram RChain Coop Chat Group](https://t.me/RChain_Official_Chat) | @kitblake |   |   |   |  
[Telegram RChain Coop Announcements](https://t.me/RChain_Official) | @Mervyn853 |   |   |   |  
[Telegram](@rchain_coop) | not moderated  |   |   |   |  
[Telegram Invite Link](https://t.me/rchain_coop) | @Mervyn853  |   |   |   |  
[Reddit](https://www.reddit.com/r/RChain_Official/ ) | @derek7272 | @entropee | @ojimadu | @Mervyn853 |  
[Reddit Old](https://www.reddit.com/r/RChain/) |   |   |   | 
[Bitcointalk](https://bitcointalk.org/index.php?topic=1747033.0) |   |   |   |   |  
[Facebook Page](https://www.facebook.com/rchaincooperative/)| @derek7272  |   |   |   |  
[Twitter](https://twitter.com/rchain_coop) |   |   |   |   |  
[RChain Architecture Doc](http://rchain-architecture.readthedocs.io/) | @JosDenmark   |   |   |   |  
[Comparison of Blockchains](http://rchain-architecture.readthedocs.io/en/latest/introduction/comparison-of-blockchains.html) |   |   |   |   |  
[Youtube](https://www.youtube.com/channel/UCSS3jCffMiz574_q64Ukj_w) | PearsonMedia  |   |   |   |  
[Medium](https://medium.com/rchain-cooperative) |   |   |   |   |  
Finance |  @lisa  |   |   |   | 
Development  |  @MParlikar  | @pyrocto   |   |   |  
Marketing  | @patrick727   |   |   |   |  
Organisation  | @kennyrowe   | @lapin7  |   |   |

**Comment by jbassiri** [comment]
I would do nothing - 0 - on compensation. People are working because they believe in the mission. If their work is valued they have a coop SOW or get paid through activist rewards. 

We dont have to give more coins to the few people who are already committed. 

If anyone has an issue and feels their time isnt being compensated they should speak up! We should make this part of our open transparent culture!

Define the roles on an as needed basis. Not roles and compensation for the sake of having them. 


-- 
Jacob Bassiri-Tehrani
(516) 458-7439

**Comment by lapin7** [comment]
I don't understand why the post "Cell phone expenses" has to be specified. Maybe it comes from the template for expenses.

_I would do nothing - 0 - on compensation. People are working because they believe in the mission. If their work is valued they have a coop SOW or get paid through activist rewards.
We dont have to give more coins to the few people who are already committed._

Does "Compensation packages" refer to normal salary based on SoW and Activist rewards?

_Define the roles on an as needed basis. Not roles and compensation for the sake of having them._
We could leave those positions just open.

**Comment by lisa** [comment]
@lapin7, I think you mean another Lisa for the project. :)

**Comment by patrick727** [comment]
@lapin7 yes i believe "cell phone expenses" was from another template

it is totally possible that the answer to "proposing compensation packages for Officers and other Important Roles" is "They get nothing outside of their SOW's" 

I have to take myself out of direct proposals for that because I fit into one of those categories. But i will say that options and other packages are great for getting people to commit longer term.

**Comment by derek7272** [comment]
I think the value we get from officers and people in other important roles
right now is quite important, and we should be compensating them
accordingly ... :)

**Comment by patrick727** [comment]
How can we formalize this vote? 

The task for this committee is

1. Confirm a compensation package for Board of Directors
2. Propose compensation packages for Officers and "Other Important Roles"
3. Self Govern

**Comment by patrick727** [comment]
p.s @lapin7 I am the owner of the facebook account not derek7272

**Comment by kennyrowe** [comment]
I think we get more information regarding the first item. As far as the second is concerned I don't think there are any "Officers or Other Important Roles" that require immediate attention. I suggest the committee define compensation for important roles as they come up. Last I think we well on our way to self-governance, but we do need to set a meeting to formalize our process.

**Comment by dckc** [comment]
I copied the table above to https://github.com/rchain/Members/wiki/Channel-Moderators since it seems like it should outlive this issue.

**Comment by patrick727** [comment]
There is also this sheet that we will want to keep updated ["teams/roles"](https://docs.google.com/spreadsheets/d/1i548cX214_gxgZ1IPOKc7PSk1fUO8MVbIe6pesgZiZo/edit#gid=589522231)

**Comment by dckc** [comment]
I didn't realize there was already a spreadsheet. No need for a wiki page then... Except... The spreadsheet doesn't seem to be public. These moderator roles should be publicly accountable, no?

**Comment by drbloom** [comment]
@patrick727 - Please mark your spreadsheet as DRAFT.
Committees are not fully seated.

**Comment by kitblake** [comment]
@patrick727 Also permissions have changed for the spreadsheet, I don't have access now.

**Comment by lapin7** [comment]
I've added the group rchain@googlegroups.com
It's a good idea to add this group to all documents that you create. Access is then restricted to people who log on. Then you can also see who has been updating the doc. Anonymous editors are then not possible.

**Comment by dckc** [comment]
That spreadsheet has an awfully large scope. Are the compensation, governance, and executive committees adequately represented in this github issue process? Is there some other process by which they review the **teams/roles** spreadsheet?

I'm interested to focus on social media channel moderators and maintaining a positive environment and consistent message as the community grows. _Perhaps I should make a separate issue._

**Comment by dckc** [comment]
I see no misunderstanding. Board officers Meredith and Rowe, if not others, were present at the community debrief 40 on Aug 30, 2017 where HJ explained the process. That looks like due process to me.

**Comment by drbloom** [comment]
@dckc - You are referring to HJ's description of a "budget allocation process" and **not editorial review**.

**Comment by dckc** [comment]
Yes, I guess I misunderstood what you were referring to.

On Jan 15, 2018 8:01 PM, "drbloom" <notifications@github.com> wrote:

@dckc <https://github.com/dckc> - You are referring to HJ's description of
a "budget allocation process" and *not editorial review*.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rchain/Members/issues/162#issuecomment-357832020>, or mute
the thread

**Comment by lapin7** [comment]
Whatever the misunderstanding is, it's of no use anymore.
This [Invite Activists to become Member.md](https://github.com/rchain/Members/blob/dea290fc000ea221c4e3337374eb828680abf5ff/Invite%20Activists%20to%20become%20Member.md) is obsolete and can be archived. It's **not** used anymore.

**Comment by Keaycee** [comment]
Can one apply for this base on his or her specialty? I would like to know because i believe in this mission and i'm willing to support collaboratively.

**Comment by dckc** [comment]
I think this issue is overtaken; i.e. I don't think the committee is doing its business here.
