### ISSUE TITLE
F> Compensation Committee: Propose Board of Director packages

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#163]
This is the one true deliverable accountable to this committee. 

Some helpful points to know would be. 

Was there a pre-determined package already proposed for the Board? If yes then we can simply approve or disapprove. 

Where in the financial forecast is the room for the compensation packages for the Board, Officers and Important Roles so that we know the parameters.

**Comment by kennyrowe** [comment]
I will ask Lisa to do this since it would not be appropriate for me to offer suggestions

**Comment by lapin7** [comment]
Rewards for board members can be based on:

- the number of expected regular meetings annually and expected length of regular meetings
- regular materials that will be sent out to the board for their review and benefit
- requirements to attend or not attend the annual member meeting in person
- frequency of President communication and performance review
- a reasonable solution based on the open market compensation
- a compensation comparative analysis of the similar work being done in similar capacity elsewhere
- Board members have to provide a reasonable explanation of our actions (to our members) and document it.

**Comment by Tonyprisca13** [comment]
@lapin7 ur reward proposal is good.

**Comment by dckc** [comment]
I just (re)discovered:
> Member Committees are a volunteer position. -- https://github.com/rchain/Members/issues/118#issuecomment-338691846

So we don't reward committee work and the budget for this issue is zero, right @lapin7 ?

**Comment by kennyrowe** [comment]
correct - participation in committee's is a volunteer position.

However - participation on the cooperative board is compensated, and this compensation will be determined by the compensation committee.

**Comment by kennyrowe** [comment]
also further discussion happening here https://discordapp.com/channels/375365542359465989/398198181881577473

**Comment by dckc** [comment]
This was decided in the [2018-02-12 meeting](https://drive.google.com/file/d/1WUTofLikchxUxNHbn27LXOj1EuGaWufI/view).
