### ISSUE TITLE
review of core dev team's Rholang Tutorial

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#169]
Alex of Coinfund is working on this.

**Comment by lapin7** [comment]
We need probably a Graphical User Interface (GUI) contract constructor, containing templates of contracts and typical actions. The GUI will provide ability to create smart contracts without special technical skills.

**Comment by dckc** [comment]
@alex-coinfund care to share a pointer to your work in progress?

**Comment by patrick727** [comment]
yes please, 

this is something that @Jake-Gillberg would also like to help out with

**Comment by alex-coinfund** [comment]
Well, I am not working on a tutorial per se, just a series of articles. Will work on the next one shortly, it will focus on the Cell contract.

**Comment by dckc** [comment]
So is this a duplicate of #51?

**Comment by lapin7** [comment]
@dckc I close #169 and leave #51 open.

**Comment by 9rb** [comment]
what happened to the Udemy Rholang course idea?  Is that a separate topic?

**Comment by dckc** [comment]
I did some relevant work by reviewing Mike Stay's...

 - [Add Rholang-Mercury tutorial doc](https://github.com/rchain/rchain/pull/159)

**Comment by Keaycee** [comment]
This is an introduction and a tutorial to [smart contract language Rholang](https://www.youtube.com/watch?v=7tW1fAWg6s8).

**Comment by dckc** [comment]
@AbnerZheng @tgrospic I would appreciate your input on the budget / reward for this issue.

See https://github.com/rchain/Members/issues/169#issuecomment-358858461

**Comment by tgrospic** [comment]
I'm looking forward to read Mike's tutorial.

**Comment by dckc** [comment]
I edited the scope w.r.t. what actually happened here.
