### ISSUE TITLE
D> RChain Development for Bounties: VM primitives, CI integration

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#176]
**[Jira Bounties](https://rchain.atlassian.net/browse/ROS-271?jql=labels%20%3D%20bounty)**

- Story ROS-271 | Integrate into CI Pipeline
- Bug ROS-270 | Fix C++ Rosette builds
- Story ROS-266 | Make C++ Rosette VM read in an RBL file in addition to boot.rbl
- Story ROS-253 | Create primitive definitions located in RBLString.cc
- Story ROS-251 | Create primitive definitions located in RblStack.cc
- Story ROS-250 | Create primitive definitions located in RblAtom.cc
- Story ROS-247 | Create primitive definitions located in Queue.cc
- Story ROS-246 | Create primitive definitions

The work on these issues requires that the community engage with the core development team. @dckc has experience with this engagement. So you can ask him how that goes.
Please, ask @MParlikar how to engage and how to become assigned to a ROS.
Please put regular comments hereunder, so that it's visible for the other members that you're working.

**Comment by MParlikar** [comment]
Please advise which ticket you wish to work on, and your Discord handle will be added to the ticket - so no one else will work on the ticket.

**Comment by lapin7** [comment]
Wow,
You're fast as light. I didn't even finish my intro email to you ;-)

--
Cheers,
HJ

**Comment by dckc** [comment]
I spent a little time orienting myself to work on ROS-271 but eventually discovered @KentShikama has done the bulk of it: [PR 52]( https://github.com/rchain/rchain/pull/52/)

For reference: https://travis-ci.org/rchain/rchain build logs

**Comment by dckc** [comment]
After discussion with @KentShikama, I put some more time in: https://github.com/rchain/rchain/pull/54

time log: about 3 or 4 hrs tonight.

**Comment by rchain-travis** [comment]
Here is the wiki page for the Bounty tickets:
https://rchain.atlassian.net/wiki/spaces/CORE/pages/105938971/Bounties+for+Development+work

**Comment by lapin7** [comment]
@rchain-travis are you the same person as @travismorehead ??

**Comment by pyrocto** [comment]
No, it's the build system.  https://travis-ci.org/

**Comment by dckc** [comment]
the build system made https://github.com/rchain/Members/issues/176#issuecomment-348283808 ???

**Comment by pyrocto** [comment]
Oh, must have been Alex or Medha while logged into that account.

**Comment by MParlikar** [comment]
It was my bad.  I was logged in there and didn't realize it until after I
made the comment.

**Comment by BelovedAquila** [comment]
@dckc how does it go please, want to see what contributions I can make to help resolve this issue

**Comment by BelovedAquila** [comment]
@MParlikar please would likewise want to know how to engage and be assigned to a ROS please .

**Comment by dckc** [comment]
@BelovedAquila which of the Jira bounties most interests you?

Before you start making any changes, have you checked out the code and gotten the tests running in your development environment?

**Comment by BelovedAquila** [comment]
@dckc no I haven't how do I do that

**Comment by dckc** [comment]
@BelovedAquila this issue is about collaborative software development in scala (or perhaps C++). Do you have experience with that? I can't tell from your github profile whether you do.

You check out the code like any other github project; see [Propose changes to someone else's project](https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project). Then use [sbt test](http://www.scala-sbt.org/1.0/docs/Testing.html) in any of the subprojects under https://github.com/rchain/rchain.

**Comment by MParlikar** [comment]
@BelovedAquila Select a ROS ticket from the list of bounty tickets and advise in Discord (DM) or you may advise here.  I will assign a label to your username (hopefully your Git and Discord handles are the same) on the ticket, so others will see that you are on it.  You can also look at ROS-197, which was recently completed by a member also.

**Comment by MParlikar** [comment]
ROS-243 completed by @AbnerZheng, ROS-197 completed by @AbnerZheng.  RHOL-44 and RHOL-45 in flight with @AbnerZheng.

**Comment by lapin7** [comment]
@dckc worked on issues below


Date | role | Summary | stat | Core Jira issue | PR | commit
-- | -- | -- | -- | -- | -- | --
Jan-24 19:29 | reviewed | Add port argument to rholang-web. |   |   | 189 |  
Jan-19 22:08 | analyzed | risky I/O calls in rosette |   | RHOL-78 |   |  
Jan-18 19:55 | reviewed | Create environment variables for rholang web initialization. |   |   | 173 |  
Jan-16 20:43 | edited | rholangweb: stronger security warning RHOL-77 | 1 file changed, 5 insertions(+), 2 deletions(-) | RHOL-77 | 166 | b0622cb
Jan-15 19:05 | merged | Merge pull request #164 from dckc/verbose-RHOL-66 |   | RHOL-66 | 164 | 8df735f
Jan-15 18:24 | coded | rholangweb: expose verbose flag RHOL-66 | 3 files changed, 11 insertions(+), 5 deletions(-) | RHOL-66 |   | fc427a0
Jan-15 17:52 | reviewed | Fix up installation of libraries and the deb package. |   |   | 163 |  
Jan-15 17:20 | reviewed | Modify space.rbl debug output to obey rosette --verbose and --quiet |   |   | 160 |  
Jan-15 17:05 | tweaked | rholangweb: "fork me on github" | 1 file changed, 7 insertions(+) |   |   | 3f43994
Jan-15 17:05 | tweaked | rholangweb: PRE-ALPHA status | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | e50765c
Jan-14 20:32 | reviewed | Use new --boot-dir cmd line option |   |   | 154 |  
Jan-11 13:23 | merged | Merge pull request #143 from dckc/rholangweb |   |   |   | 16f84b7
Jan-11 00:37 | merged | Merge dev into rholangweb |   |   |   | 92765dd
Jan-11 00:24 | wrote | rholangweb: promote security considerations to README | 2 files changed, 27 insertions(+), 23 deletions(-) |   |   | 150880b
Jan-11 00:02 | coded | rholangweb: access control, docs, type hints | 4 files changed, 192 insertions(+), 77 deletions(-) |   |   | e7ab27b
Jan-11 00:01 | coded | rholangweb: logging config | 1 file changed, 34 insertions(+), 1 deletion(-) |   |   | 811004e
Jan-10 23:58 | tweaked | rholangweb RBL code: wrap display | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | 433b087
Jan-9 01:56 | coded | select examples from menu | 2 files changed, 27 insertions(+), 2 deletions(-) |   |   | 9255d0d
Jan-9 01:10 | coded | views: handle compiler errors | 3 files changed, 63 insertions(+), 69 deletions(-) |   |   | 0fc809a
Jan-9 00:24 | coded | runner.VM: check errors when running VM | 3 files changed, 82 insertions(+), 34 deletions(-) |   |   | 70629ed
Jan-8 23:27 | coded | handle compiler errors | 3 files changed, 159 insertions(+), 26 deletions(-) |   |   | d1c042c
Jan-8 23:26 | tweaked | use rholang syntax for input placeholder | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | ea4d757
Jan-8 23:25 | coded | run rosette without docker | 2 files changed, 5 insertions(+), 1 deletion(-) |   |   | 109556d
Jan-7 21:04 | coded | compiler: run assembly jar | 3 files changed, 12 insertions(+), 18 deletions(-) |   |   | 240a147
Jan-7 21:03 | tweaked | views.py: newline at end of file | 1 file changed, 1 insertion(+), 1 deletion(-) |   |   | 21aed87
Jan-6 09:47 | wrote | Getting Started docs, fix missing requirement | 2 files changed, 40 insertions(+) |   |   | acad17e
Nov-3 20:36 | tweaked | rosette/Compiler: avoid converting args toList | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | 301303f
Nov-3 20:34 | coded | rho2rbl shell script | 2 files changed, 22 insertions(+) |   |   | 7f3b81a
Nov-2 22:24 | coded | rholang: build stand-alone .jar compiler app | 2 files changed, 19 insertions(+), 9 deletions(-) |   |   | 6455a5b
Nov-2 22:24 | coded | Rholang2RosetteCompiler.main: compile .rho to .rbl | 2 files changed, 19 insertions(+), 2 deletions(-) |   |   | 4758195

**Comment by dckc** [comment]
@lapin7 let's keep this issue focussed on  VM primitives, CI integration and use #185 for Compiler-Web stuff. I created #255 for the example contracts (RHOL-44, RHOL-45).

@AbnerZheng 's work on VM primitives is in scope here:
 - **ROS-243**: 8 story points; [PR121](https://github.com/rchain/rchain/pull/121) merged 8 Jan
 - **ROS-197**: 8 story points; merged Dec 20

Next I'll add numbers in the budget / reward spreadsheet...

**Comment by AbnerZheng** [comment]
Just a short comment to become a participant on this issue. Aha

**Comment by AbnerZheng** [comment]
@lapin7 @dckc @MParlikar 
There must be something  wrong for the budget and reward for this issue. @dckc vote 640$ for this issue, I guess he must want apply all budget for work done for this month, because if the total budget for this issue is 640$, and then the percentage of my work is 5%, then my reward is 32$. So I vote 25000$ for this budget so that, my reward is about 16*40 = 640$.

**Comment by dckc** [comment]
Yes, $640 is good.

There was a large budget left over from previous months at the time I
entered what I did.

**Comment by MParlikar** [comment]
What needs to be done in order to fix this?  @dckc @lapin7 How does the budget roll over from last month?

**Comment by dckc** [comment]
@MParlikar I'm inclined to see the big spreadsheet as a useful prototype and retire it. See #260 for a next prototype.

**Comment by lapin7** [comment]
"budget 201801" & "rewards 201801" are frozen and can only be changed be me
at the moment.

Please check and eventually enter correct entries for #176
I've changed the entries manually to

3,072.00 Member
0.00 lapin7
0.00 MParlikar
2,432.00 dckc
0.00 rchain-travis
0.00 pyrocto
0.00 BelovedAquila
640.00 AbnerZheng
0.00 kaka56
0.00
0.00
0.00
​The roll over is like: "budget rollover" = "budget 201801" - "rewards
201801"
The new budget is like: "new budget" = "budget rollover" +  "budget 201802"​

--
Cheers,
HJ

**Comment by AbnerZheng** [comment]
@lapin7 The reward for my work is right. Thanks.

**Comment by dckc** [comment]
@lapin7 in the scope of this ticket, my only contributions in January were coordination, onboarding, and guiding.

My coding work was mostly in #185.

**Comment by linsheng9731** [comment]
I have made a PR for ROS-247 and ROS-314. @lapin7 @MParlikar Please assign someone to review it, thank you.
https://github.com/rchain/rchain/pull/218

**Comment by lapin7** [comment]
Soon I will produce a total list of payments per person.
Before actual payments start, I can receive feedback and make adjustments
if it's needed.

The attention for the payment system has increased enormously. :-)
And I'm happy to improve the system with all your insights and suggestions.

--
Cheers,
HJ

**Comment by linsheng9731** [comment]
After i rebased dev branch, there was something wrong with this pull-request #218. So i made a new pull-request here. #296..

**Comment by dckc** [comment]
Medha is making new issues for more recent contributions to the core development work.
