### ISSUE TITLE
D> Rholang play web site like rust playground, crystal playground, etc.

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#185]
The core team tracks this as [RHOL-35](https://rchain.atlassian.net/projects/RHOL/issues/RHOL-35) and [Compiler-Web](https://rchain.atlassian.net/browse/RHOL-103?jql=project%20%3D%20RHOL%20AND%20component%20%3D%20Compiler-Web).

suggested budget: $1500 (for 31 story points, plus reviews of related PRs)

escalated from https://github.com/rchain/rchain/pull/40#issuecomment-341991949

**Comment by dckc** [comment]
I got started with some research and a trivial HTTP server in scala: https://github.com/dckc/rholang-playground e86af15

I got as far as building a single-jar assembly, only to realize the machine I had in mind for initial deployment doesn't have java installed. :-/

Maybe I'll just use python...

**Comment by dckc** [comment]
ok... I've got a possible deployment path using codenvy: http://node13.codenvy.io:54968/index.html

**Comment by dckc** [comment]
Ah... this is also tracked as [RHOL-35](https://rchain.atlassian.net/projects/RHOL/issues/RHOL-35).

**Comment by dckc** [comment]
@KentShikama tells me there's already a start: https://github.com/KentShikama/RholangWeb

**Comment by dckc** [comment]
another deployment path for testing: [ngrok](https://ngrok.com/).

**Comment by dckc** [comment]
I'm kinda happy with https://da6247d5.ngrok.io/ now.

I found a full 5 hr chunk to work on it. Results: 54ddeda https://github.com/KentShikama/RholangWeb/pull/10

**Comment by KentShikama** [comment]
I'm really liking what I see so far :+1: I'll take a look at the PR now.

**Comment by dckc** [comment]
@MParlikar and I talked last Thu about some todos:

* capture what people are entering
* security boundary
* turn off debug output in the VM / REPL
* line numbers

**Comment by dckc** [comment]
For end-of-the-month accounting purposes, here's my work on this issue to date:

I have a few more tickets to work on this weekend, so I'll tweak this as I go:

Date | role | Summary | stat | Core Jira issue | PR | commit
-- | -- | -- | -- | -- | -- | --
Jan-24 19:29 | reviewed | Add port argument to rholang-web. |   |   | 189 |  
Jan-19 22:08 | analyzed | risky I/O calls in rosette |   | RHOL-78 |   |  
Jan-18 19:55 | reviewed | Create environment variables for rholang web initialization. |   |   | 173 |  
Jan-16 20:43 | edited | rholangweb: stronger security warning RHOL-77 | 1 file changed, 5 insertions(+), 2 deletions(-) | RHOL-77 | 166 | b0622cb
Jan-15 19:05 | merged | Merge pull request #164 from dckc/verbose-RHOL-66 |   | RHOL-66 | 164 | 8df735f
Jan-15 18:24 | coded | rholangweb: expose verbose flag RHOL-66 | 3 files changed, 11 insertions(+), 5 deletions(-) | RHOL-66 |   | fc427a0
Jan-15 17:52 | reviewed | Fix up installation of libraries and the deb package. |   |   | 163 |  
Jan-15 17:20 | reviewed | Modify space.rbl debug output to obey rosette --verbose and --quiet |   |   | 160 |  
Jan-15 17:05 | tweaked | rholangweb: "fork me on github" | 1 file changed, 7 insertions(+) |   |   | 3f43994
Jan-15 17:05 | tweaked | rholangweb: PRE-ALPHA status | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | e50765c
Jan-14 20:32 | reviewed | Use new --boot-dir cmd line option |   |   | 154 |  
Jan-11 13:23 | merged | Merge pull request #143 from dckc/rholangweb |   |   |   | 16f84b7
Jan-11 00:37 | merged | Merge dev into rholangweb |   |   |   | 92765dd
Jan-11 00:24 | wrote | rholangweb: promote security considerations to README | 2 files changed, 27 insertions(+), 23 deletions(-) |   |   | 150880b
Jan-11 00:02 | coded | rholangweb: access control, docs, type hints | 4 files changed, 192 insertions(+), 77 deletions(-) |   |   | e7ab27b
Jan-11 00:01 | coded | rholangweb: logging config | 1 file changed, 34 insertions(+), 1 deletion(-) |   |   | 811004e
Jan-10 23:58 | tweaked | rholangweb RBL code: wrap display | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | 433b087
Jan-9 01:56 | coded | select examples from menu | 2 files changed, 27 insertions(+), 2 deletions(-) |   |   | 9255d0d
Jan-9 01:10 | coded | views: handle compiler errors | 3 files changed, 63 insertions(+), 69 deletions(-) |   |   | 0fc809a
Jan-9 00:24 | coded | runner.VM: check errors when running VM | 3 files changed, 82 insertions(+), 34 deletions(-) |   |   | 70629ed
Jan-8 23:27 | coded | handle compiler errors | 3 files changed, 159 insertions(+), 26 deletions(-) |   |   | d1c042c
Jan-8 23:26 | tweaked | use rholang syntax for input placeholder | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | ea4d757
Jan-8 23:25 | coded | run rosette without docker | 2 files changed, 5 insertions(+), 1 deletion(-) |   |   | 109556d
Jan-7 21:04 | coded | compiler: run assembly jar | 3 files changed, 12 insertions(+), 18 deletions(-) |   |   | 240a147
Jan-7 21:03 | tweaked | views.py: newline at end of file | 1 file changed, 1 insertion(+), 1 deletion(-) |   |   | 21aed87
Jan-6 09:47 | wrote | Getting Started docs, fix missing requirement | 2 files changed, 40 insertions(+) |   |   | acad17e
Nov-3 20:36 | tweaked | rosette/Compiler: avoid converting args toList | 1 file changed, 2 insertions(+), 2 deletions(-) |   |   | 301303f
Nov-3 20:34 | coded | rho2rbl shell script | 2 files changed, 22 insertions(+) |   |   | 7f3b81a
Nov-2 22:24 | coded | rholang: build stand-alone .jar compiler app | 2 files changed, 19 insertions(+), 9 deletions(-) |   |   | 6455a5b
Nov-2 22:24 | coded | Rholang2RosetteCompiler.main: compile .rho to .rbl | 2 files changed, 19 insertions(+), 2 deletions(-) |   |   | 4758195

**Comment by dckc** [comment]
@MParlikar I wish I could get a table of story points for each ticket in the Compiler-Web component (I just made sure all the relevant tickets I've worked on are there). I spent a few minutes looking into it without luck. Does JIRA support that sort of thing straightforwardly?

**Comment by zsluedem** [comment]
Wow!~that's really nice .

**Comment by dckc** [comment]
cool... Medha showed me how: [story points in Compiler-Web](https://rchain.atlassian.net/issues/?jql=component%20%3D%20Compiler-Web%20ORDER%20BY%20assignee%20ASC%2C%20status%20DESC). I'm not sure who has access to that, but I can export and share as appropriate.

**Comment by dckc** [comment]
@AbnerZheng @tgrospic I would appreciate your input on the budget and reward for this issue.

**Comment by AbnerZheng** [comment]
Yes, I will.

**Comment by tgrospic** [comment]
@dckc I was not involved in this issue so I'm not sure on which basis should I fill out the budget document.

But, I exchanged few emails with @AbnerZheng about adding code editor to rholang-web, like Ace. Should I create a new issue for that feature?

I'm not sure if this is _long running issue_ which tracks montly updates? I'm also asking because of [Idea plugin](https://github.com/rchain/Members/issues/127) issue which has similar situation. What should be the workflow for developing additional features? Or for example to create Atom plugin.

**Comment by dckc** [comment]
@tgrospic I am asking you to _get_ involved.  :) If noone else takes a look at this work, I get no reward.

 :) Assuming you agree that such a playground is good for RChain... In [my Jan 27 comment above][3] I claim to have made a bunch of commits, PRs, etc.; you can spot-check and verify those claims, yes? And you can look at a little bit of the code. I claim to have done 90% of the work on this issue this month. Does that seem reasonable? If so, fill in that number in the [rewards sheet][1]. I suggested a budget in the summary; does it seem reasonable? If so, fill in that number in the [budget sheet][2]. If you think it should be higher or lower, that input is welcome as well.
 
[1]: https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=950224463
[2]: https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=468279933
[3]: https://github.com/rchain/Members/issues/185#issuecomment-360983331

**Comment by tgrospic** [comment]
@dckc thanks for the invite and for clarification. I appreciate you work for RChain. :)

I will take a look at your work summary for January. Do you know how can I add my name to the list of members for this issue on rewards sheet?

**Comment by dckc** [comment]
Making a comment here is supposed to get your name into that list, @tgrospic .

@lapin7 any suggestions?

**Comment by dckc** [comment]
And yes, @tgrospic, please make a new issue for the Ace editor enhancement. Managing long-running issues is not smooth yet; it's not clear if it ever will be.

**Comment by lapin7** [comment]
I've added manually @tgrospic to #185
Now @tgrospic can add a budget and rewards
https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=468279933&range=AF98

--
Cheers,
HJ

**Comment by dckc** [comment]
@MParlikar @KentShikama would you please weigh in on the bounty for this issue?

@tgrospic @AbnerZheng today is the last day to vote for January rewards, @lapin7 said in a couple other issues.

@lapin7 irony: currently I'm set up to get zero reward for this issue, and it's the one I put the most work in on.

**Comment by lapin7** [comment]
The distribution of rewards is now like this.

Please reply if it's not OK.

2,066.67 Member 100.00% 8 Voted percentages
1,798.00 dckc 87.00% 3 dckc 0.89 AbnerZheng 0.87 MParlikar 0.85
144.67 KentShikama 7.00% 2 dckc 0.07 AbnerZheng 0.07
62.00 AbnerZheng 3.00% 1 AbnerZheng 0.03
62.00 tgrospic 3.00% 2 dckc 0.03 AbnerZheng 0.03
0.00 lapin7 0.00% 0
0.00 MParlikar 0.00% 0
0.00 tgrospic 0.00% 0
@KentShikama doesn't get his reward, because it's covered by an SoW.


--
Cheers,
HJ

**Comment by dckc** [comment]
moving this off my front burner pending updates on [RHOL-78][]

[RHOL-78]: https://rchain.atlassian.net/browse/RHOL-78

**Comment by dckc** [comment]
Looks like somebody else (@tschoffelen) picked up the ball: http://rchain.cloud/

**Comment by tschoffelen** [comment]
I did indeed, thanks for the ping @dckc. Totally new to the bounty program, so please let me know what I need to do to progress with this.

**Comment by dckc** [comment]
Take a look at README.md and CONTRIBUTING.md (and the explainer video) and let me / us know if it's clear.

Things are in a bit of flux, though; for example, see #375 .

More later, I hope...

**Comment by tschoffelen** [comment]
Cool, thanks for the great overview @lapin7. I've completed most of the steps. Also, I had a good look a t Rholangweb and didn't realise you made so much progress with this already @dckc! Hope I didn't step on your toes by building rchain.cloud, not my intention in any way.

Also, what do you think is the best course of action? I was planning to bring the feature set of rchain.cloud on par with what has already been built (see the [rchain.cloud issues](https://github.com/th3build/rchain.cloud/issues)). Any other suggestions?

**Comment by dckc** [comment]
The fact that rchain.cloud runs as a public service makes it much more interesting than the rholang-web work that I did (along with Kent and others). The rholang-web stuff doesn't run as a public service due to lack of available effort to secure it [RHOL-78][]. I asked the core team:

> Does http://rchain.cloud/ render this issue moot? Maybe just punt RholangWeb to the community?

[RHOL-78]: https://rchain.atlassian.net/browse/RHOL-78?jql=project%20%3D%20RHOL%20AND%20component%20%3D%20Compiler-Web

**Comment by tschoffelen** [comment]
I saw that, cool! I think that the fact that it runs the interpreter within a docker container should resolve most of the security concerns, although there are still some efforts that can be taken to fortify the service.

**Comment by zsluedem** [comment]
@tschoffelen That's what I was thinking ,too.(running inside the docker) 
I have discussed this with @dckc .
But now http://rchain.cloud/ is released. I don't know if the Rholangweb project should continue(actually it stuck because of the security issue for quite long time).
I think we should make this project forward something like http://rchain.cloud/ is really helping spread the Rholang not just the plain Rholang tutorials and the hard-to-understand spec docs.

**Comment by dckc** [comment]
@tschoffelen I just added a budget vote in https://rewards.rchain.coop/ and voted to reward the bulk of it to you. Be sure you vote for your work!

@zsluedem I talked with Medha, and she agrees: rchain.cloud should obsolete rholangweb. Here's hoping for time to submit a PR to remove it. Feel free to beat me to it.

**Comment by tschoffelen** [comment]
Thanks @dckc! Would someone else (@zsluedem?) mind voting for the budget/reward for April to reach the 3 vote minimum?

**Comment by dckc** [comment]
I made https://github.com/rchain/rchain/pull/659 to remove rholangweb from the core source tree, after discussion with @MParlikar .

**Comment by dckc** [comment]
The PR to remove rholangweb from core was merged and rchain.cloud is on developer.rchain.coop.

Well done, all!
