### ISSUE TITLE
F> Communication on New Email for Invoices

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#186]
Our CFO, Lisa, has set up the procedure around [invoicing and payments.](https://docs.google.com/document/d/11Wh0i8ysRvnzAdYk5e985I3OX9lRffV036JqLmQC764/edit) . The new email for invoicing is invoices@rchain.coop
Feel free to add suggestions, comments, etc.

**Comment by Ojimadu** [comment]
The new invoicing requires a tax form to be filled before rewards can be sent. For US residents and aliens that might not be a problem but for Non-US residents how do they go about that? Also, is there a way to auto-generate invoices based on the usernames on the spreadsheet so it would be faster and easier to submit the invoices?

**Comment by lapin7** [comment]
For non-us-residents it depends per country i think 🤔. It depends whether there exists a tax treaty between the USA and the country of the non-us-resident. 

With concern to auto generate an invoice all manual work has to be programmed with a script. Who could do such a thing?

Best,
HJ

**Comment by Ojimadu** [comment]
@lapin7 I just did some reading on that and it depends whether tax treaty between the USA and the country of the non-us-resident. The W-8 form seem like the most appropriate for non-US-resident. Please add the instructions on how to fill both the W-9 and W-8 form for ease of use.
[Instructions for Form W-8BEN](https://www.irs.gov/instructions/iw8ben/index.html)
[Instructions for Form W-8BEN](https://www.irs.gov/instructions/iw9/index.html)

**Comment by lapin7** [comment]
@Ojimadu could you add a simple instruction for W8 and W9 to contributing.md for example?

**Comment by Ojimadu** [comment]
@lapin7 Would write down a draft and update it.

**Comment by Ojimadu** [comment]
@lapin7 On a second thought, it would be better to just add a link to the instructions on how to fill the tax forms on the contributing.md files but there is a problem, the contributing.md document says Fw9 and Fw4 tax form which is different from the W8 and W9 tax forms which is sent in the invoice. Please clarify this.

**Comment by Keaycee** [comment]
@lapin7 There need to be a clear instruction stating how W9 and W8 form should be filled out correctly. There is a need to translate the invoice and also the "W9 and W8 HOW TO" in other engaging languages so engaging cooperative member can understand this instructions. This instruction should clearly state "HOW TO" for the U.S citizens, Countries with Tax treaty between the U.S, And countries that does not. This information can be stated on a single document so member can understand the difference between the Taxes. But there is a need to translate it to the major engaging languages. @Ojimadu What do you suggest?

**Comment by Ojimadu** [comment]
Let's get the instructions done first, before we can know what to translate. For now am waiting for @lapin7 to clarify the forms as what's stated on Contributing.md is different from what's on the invoice.

**Comment by lapin7** [comment]
w4 is not needed. it can be deleted
clear instruction for w8 an and w9 would help :-)

--
Cheers,
HJ

**Comment by Mervyn853** [comment]
Updated the tracking sheet to close out the Influencer connections with Blockchain Brad that concluded with this great interview : https://www.youtube.com/watch?v=PwuV7ryhaXw&t=1s and a connection to Jackson Palmer. Have a few other Influencers that have reached out to me expressing further interest in more interviews.

**Comment by Ojimadu** [comment]
Alright, am working on it.

**Comment by BelovedAquila** [comment]
>  @lapin7 There is a need for clear instruction stating how W9 and W8 form should be filled out correctly. 

@Keaycee your suggestion on clear instruction on how to fill the Tax forms, is being rectified on #360

**Comment by jimscarver** [comment]
The declaration form has replaced the email no? This issue need to be modified or closed.

**Comment by lapin7** [comment]
Use form [Declaration](https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform) to send your invoice and if you haven't done so already, your tax form W8 or W9.
