### ISSUE TITLE
D> Rho-calc/Rholang programming on Holochain

### ISSUE THREAD

**Issue by jimscarver** [rchain/bounties#188]
Holochain has many of the same design objectives as RChain. Like Rosette, Holochain is based on an actor model. The aim is to generate Holochain apps from the rosette output of the Rholang compiler.

To this end we have engaged in a cooperation with DigLife.com and Holochain.org in the [Social Ledger trial](https://docs.google.com/document/d/1v7JaVwJUhWix52y7piNqlpAYiVCtNhim2I0KvJyE16M/edit#).

**Comment by dckc** [comment]
Holochain is based on an actor model? Help me find any documentation about that? I looked for a few minutes without luck.

**Comment by Ojimadu** [comment]
The white paper [here](https://github.com/metacurrency/holochain/blob/whitepaper/holochain.pdf) can be  a good resource. Quite technical for me yet. Also the FAQ might help. I think it has element of concurrency (actor model) as RChain.

**Comment by patrick727** [comment]
@jimscarver i see a reminder for the meeting but how can one join?

**Comment by jimscarver** [comment]
raymond will be in brooksville around jan 20th and we hope to have a meetup in the tampa bay area while he is here @patrick727 

activity is in the [holochain mattermst](https://chat.holochain.net/signup_user_complete/?id=uc7j4tp8jbga78nw363gbgqdxc) w.r.t. our collaboration.

**Comment by kitblake** [comment]
@jimscarver @patrick727 When the meetup date gets nailed down please post it.

**Comment by jimscarver** [comment]
Today diglife/rchain folks are meeting with @rayzer at 1pm EST in  https://zoom.us/j/6853551826  This is the warm up... getting people up to speed with Holochain app development while we wait for the meeting with Eric to really dig into a plan to roll out DPKI,-Identity

**Comment by dckc** [comment]
I see no movement in over six months.

**Comment by jimscarver** [comment]
I do not think this issue is closed. It is an issue looking for a team to embrace. It is an activity encouraged by Greg in a debrief/standup. Only interest has been express from both holochain and rchain but noone has stepped forward yet to take action. The issue is very open.

**Comment by dckc** [comment]
Open issues represent plans to complete work. I see no plan here. Monitoring issues takes time and effort. With no indication that anyone intends to make progress, this issue isn't worth tracking as open.

**Comment by jimscarver** [comment]
If we intend to scale and offer opportunity to participate we want to list issues that have been staffed as well as those that have not.  If managing stale issues is the issue, I think that should be delt with separately.

We can ask if rholang support on every platform is an objective of the coop. Or if interoperation with holochain is desired. If ether answer is yes the issue should remain open if we intend that someday it will be completed.

**Comment by dckc** [comment]
I read the whitepaper and watched a couple of the short videos. I see lots of stuff about agents, but nothing about the actor model.

Having this issue around hasn't catalyzed any momentum in just about a year.

And I don't see a separate plan emerging for dealing with stale issues. So I'm continuing with my "open issues represent plans to complete work" process.
