### ISSUE TITLE
M> (B) RChain Developer Retreat Summary

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#191]
M> Indicates that this is a project within the "Marketing" category
(B) Indicates that this is a Blog post

Goal:

Blog post with paragraphish long descriptions of sessions with a link to the corresponding video

**Comment by Jake-Gillberg** [comment]
Target publication by 2017-12-31

**Comment by dckc** [comment]
Here's hoping I find a moment to write one up, now that the videos are out.

**Comment by patrick727** [comment]
thankyou @Jake-Gillberg and yes please @dckc !

**Comment by dckc** [comment]
I just ran across "Greg summarizes the developer retreat" in the [Nov 21 community debrief](https://github.com/rchain/Members/wiki/Weekly-Debrief-Index#november-22nd---community-debrief-52).

**Comment by Jake-Gillberg** [comment]
Feedback welcome!

Here is a preview for a summary of Day 1 of the retreat. https://medium.com/@jake.gillberg/rchain-developer-retreat-roundup-day-1-759091f53795

**Comment by n10n** [comment]
@Jake-Gillberg Good work! Looking forward to talking to you.

**Comment by ResonanceXX** [comment]
Good work Jill!  Still some typo's to weed out. But great thinking. 

Sent from Yahoo Mail on Android 
 
  On Sat, 30 Dec 2017 at 20:33, n10n<notifications@github.com> wrote:   
@Jake-Gillberg Good work! Looking forward to talking to you.

**Comment by Jake-Gillberg** [comment]
@ResonanceXX Gave it another pass and caught a few typos. Let me know specifics if you find any more; thanks!

**Comment by Jake-Gillberg** [comment]
Published here: https://medium.com/@jake.gillberg/rchain-developer-retreat-roundup-day-1-759091f53795

**Comment by Jake-Gillberg** [comment]
Oops, nvm. Reopening because we still have days 2 and 3 to summarize and those don't have separate issues.

**Comment by dckc** [comment]
My write-up might not be exactly on target, but... FWIW:

 - [Smart Contracts and Capabilities Up Close](http://www.madmode.com/2017/rchain-dev-retreat.html)

**Comment by patrick727** [comment]
@Jake-Gillberg please submit the post to the RChain Cooperative medium account

In the future can you submit the draft to the publication as well. we want the content to be scheduled...

Thanks

**Comment by pmoorman** [comment]
@patrick727 @Jake-Gillberg I guess we can close this?  Will close it now, feel free to reopen.
