### ISSUE TITLE
C> RHOCs on Exchanges

### ISSUE THREAD

**Issue by kitblake** [rchain/bounties#192]
This issue tracks the everchanging scenario of RHOCs on exchanges and provides current answers to common questions that come up in chat channels. The issue includes How-Tos, listing statuses, and discussion. It supersedes #29 which became outdated and bloated.

**Comment by kitblake** [comment]
How to Trade RHOCs on OasisDex, EtherDelta, and 0x:
https://github.com/rchain/Members/issues/29#issuecomment-324218666

**Comment by kitblake** [comment]
CoinMarketCap info:
https://github.com/rchain/Members/issues/29#issuecomment-342401211

**Comment by kitblake** [comment]
List of exchanges and statuses:
https://github.com/rchain/Members/issues/29#issue-226203655

**Comment by kitblake** [comment]
Starting Dec 12th, RHOCs start trading on [Kucoin](https://www.kucoin.com/). It's a new up and coming exchange with simple email signup, 2fa, friendly UI.

**Comment by ResonanceXX** [comment]
Cheers!  Great work team.

**Comment by Mervyn853** [comment]
RHOCs can now be purchased at https://www.kucoin.com/

​https://www.kucoin.com/#/trade/RHOC-BTC
https://www.kucoin.com/#/trade/RHOC-ETH

**Comment by sportshark** [comment]
RHOC listed at https://decentrex.com/#RHOC-ETH

**Comment by kitblake** [comment]
From @isepick:
looks like it went up on IDEX as well
https://idex.market/eth/rhoc

**Comment by kitblake** [comment]
RHOCs are now listed on https://token.store/trade/RHOC

**Comment by kitblake** [comment]
Current listings:
https://token.store/trade/RHOC
https://www.kucoin.com/#/trade/RHOC-BTC / ETH
https://idex.market/eth/rhoc
https://decentrex.com/#RHOC-ETH
https://etherdelta.com/#RHOC-ETH
https://oasisdex.com/#trade/W-ETH/RHOC
https://ex.singularx.com/exchange/RHOC/ETH

**Comment by Mervyn853** [comment]
New exchange for RHOC! chaoex.com! @kitblake I believe @sportshark got us listed on CHAOEX.COM https://coinmarketcap.com/currencies/rchain/#markets

**Comment by sportshark** [comment]
Yes，chaoex.com has listed RHOC,
One of the managers is my friend
Thank you @Mervyn853

**Comment by Keaycee** [comment]
This is really a step forward for RChain having part of the Chinese market.  Well done @sportshark

**Comment by lapin7** [comment]
It's a controversial issue for the coop. Therefor it cannot get a budget. I've removed the entry of @ResonanceXX from the Budget spreadsheet.

**Comment by kitblake** [comment]
https://app.radarrelay.com/ZRX/WETH (beta, requires Metamask)

**Comment by kitblake** [comment]
https://app.radarrelay.com/RHOC/WETH (beta, requires Metamask)

**Comment by cenyuhai** [comment]
Huobi.pro will open a new exchange called HADAX. Huobi is very popular in China. Should we submit a request?
We can submit request in this url: https://docs.google.com/forms/d/1Cxn6kM3tJIOty0jBU0XbzmY9doxVHi4zVvTB4b8l8Hs/viewform?edit_requested=true
If we win in the vote, we can listed rhoc in HADAX.

**Comment by kitblake** [comment]
@cenyuhai I looked at the form and I think yes, but I don't read Chinese, so let's ping @Mervyn853

**Comment by dckc** [comment]
see https://github.com/rchain/reference/commit/3efdc256dfc6a7bcf7d381f3fa0c0d7b88cd15e3#diff-4a1318da06786ac52626178ca960109e
