### ISSUE TITLE
M> Research Group Review: CHAINROCK

### ISSUE THREAD

**Issue by Mervyn853** [rchain/bounties#193]
I've been contacted by CHAINROCK which is a digital asset research and investment group, focused on blockchain technology and cryptoassets. They've released an analysis of our project cited here : https://chainrock.io/rchain/

I believe this is our first research group review and I find the analysis fair and valid with criticisms similar to those that have been conveyed to me in other social channels. 

I also believe there is opportunity for us to clear the air with regards to some of the concerns addressed in the report. This could also help instill further confidence in our project within the larger Crypto community which could drive membership and future platform adoption.

With another ICO planned after the Mercury platform release, I believe we could set up an issue with rewards for Research groups to give a fair and objective review to build the RChain brand and get our name out there.

Chainrock is interested in setting up an interview with a member of the team to address some concerns. Would anyone be interested in taking this on?

**Comment by patrick727** [comment]
@Mervyn853 this is great!

It would need to be someone who could address the token supply terms directly.

**Comment by llerner** [comment]
@Mervyn853 hi, please direct these to me. I'll find someone or answer it myself. Let's connect offline to follow up. Thank you!

**Comment by lapin7** [comment]
I think it deserves to be open.

**Comment by Ojimadu** [comment]
@Mervyn853 Has anyone been able to talk to chainrock? When I last read the review I couldn't find any definitive concern about the technology except a subjective one. If there are concerns concerning the tech we can get to set up an interview with Nash foster.

**Comment by Mervyn853** [comment]
Yes. Me and Lawrence are in contact with Don. Will work to schedule something since Nash has volunteered to take on interviews.

**Comment by Ojimadu** [comment]
Is Don from chainrock?

**Comment by Mervyn853** [comment]
Yes @Ojimadu . Also, I might have more reviews coming in, will update again.

**Comment by pmoorman** [comment]
@Mervyn853 I'll close this issue for the sake of trimming our marketing issue list, and because it seems like the time has come and past for this (right?).

_Feel free to reopen if you still deem it relevant!_
