### ISSUE TITLE
O> Gov Conference Travel expenses

### ISSUE THREAD

**Issue by jimscarver** [rchain/bounties#194]
Travel expenses for committee members and invited guests need to be budgeted and approved.

**Comment by ResonanceXX** [comment]
I'm willing to assist in doing this.

**Comment by lapin7** [comment]
Just create an Issue "Travel Expenses"
Set a budget for example $10.000
Find 3 members to set this budget in Budget 201712
Travellers write in the comment of the issue for what reason they travel,
when, and the amount. And they add an invoice with copy/paste (see #171)
Ask your friends if they agree with your expenses and ask them to fill out
a percentage in Rewards 201712

For example:
If you go on holiday to Zambia and you organize a Meetup about RChain
there. Then you report in the comment how it went and you declare your cost.

Clear? OK. Go for it :-)




--
Cheers,
HJ

**Comment by ResonanceXX** [comment]
@lapin7 I would need authorization access for the budget sheet document. I await your response to begin work.

**Comment by lapin7** [comment]
Please send me your email and then I can add you to the Google group RChain


--
Cheers,
HJ

**Comment by ResonanceXX** [comment]
Kenechukwuoliaku@yahoo.com

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Dec 2017 at 14:46, HJ Hilbolling<notifications@github.com> wrote:   Please send me your email and then I can add you to the Google group RChain


--
Cheers,
HJ

**Comment by ResonanceXX** [comment]
Take a look at this dear Mr. HJ

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Dec 2017 at 15:11, Kenechukwu Oliaku<kenechukwuoliaku@yahoo.com> wrote:   Kenechukwuoliaku@yahoo.com

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Dec 2017 at 14:46, HJ Hilbolling<notifications@github.com> wrote:   Please send me your email and then I can add you to the Google group RChain


--
Cheers,
HJ

**Comment by ResonanceXX** [comment]
@ #

**Comment by ResonanceXX** [comment]
How much money will you need in Seattle? $149 is the average daily price for traveling in Seattle. The average price of food for one day is $37. The average price of a hotel for a couple 

![screenshot_20171205-002313](https://user-images.githubusercontent.com/34219332/33581792-9353ca5c-d952-11e7-8ecd-0c3f634ab811.png)

**Comment by ResonanceXX** [comment]
![screenshot_20171205-002307](https://user-images.githubusercontent.com/34219332/33583931-2faf9264-d95d-11e7-9506-90b5848c7c91.png)

**Comment by Phistr90** [comment]
@ResonanceXX The current discussed options on discord are: 

Proposed Dates
Thursday 2/15 - Sunday 2/18
(Valentines day is Feb 14, 2018)(edited)
Location:
St. Petersburg FL (TPA)
Denver, CO (DEN)

**Comment by lapin7** [comment]
@ResonanceXX sorry for the mis-communication. But it seems to be good now. You're set up for google groups and github. So please go ahead.

**Comment by ResonanceXX** [comment]
Thank you. I will research some more with the updated info. 

Sent from Yahoo Mail on Android 
 
  On Tue, 5 Dec 2017 at 10:57, HJ Hilbolling<notifications@github.com> wrote:   
@ResonanceXX sorry for the mis-communication. But it seems to be good now. You're set up for google groups and github. So please go ahead.

**Comment by ResonanceXX** [comment]
Hello HJ
A little clarity on the exact amount of attendees. I can compute a final figure. But check this out meanwhile. 



https://docs.google.com/document/d/10nsH-bE0De1cqaaYQg4woi1QHMcYXds5RaOVVy1RkCE/edit?usp=drivesdk

**Comment by ResonanceXX** [comment]
HJ I suppose this could work. 

https://docs.google.com/document/d/1JZR5t88dtdcMtn5ICoeQxkK6imLh-iSVS1O8yS9As6w/edit?usp=drivesdk

**Comment by Phistr90** [comment]
@ResonanceXX Did you intentionally leave out flight expenses as they vary a lot and have to be set on case by case basis?

**Comment by ResonanceXX** [comment]
Yeah. There would have to be a list of  location guide. Because naturally do not suppose all attendees are from same state. I'll check the average costs of travel to both probable host cities.  Thank you. 
- ResonanceXX



Sent from Yahoo Mail on Android 
 
  On Wed, 6 Dec 2017 at 17:10, Phistr90<notifications@github.com> wrote:   
@ResonanceXX Did you intentionally leave out flight expenses as they vary a lot and have to be set on case by case basis?

**Comment by ResonanceXX** [comment]
@Phistr90  Here are some prices for a round trip ticket to Denver, CO. 

Pending the final  collective choice location. This only just guessing. 
https://docs.google.com/document/d/1fnEZO5rMC5AMDRBvy1mXZzGYhjVY6LPr_JuV3c-4GQE/edit?usp=drivesdk

**Comment by Phistr90** [comment]
@ResonanceXX I brought up this issue due to the fact that I am from Germany and travel costs will be higher for me. So I guess flight expenses have to be set on case by case basis.

**Comment by ResonanceXX** [comment]
@Phistr90 Yeah. That would be carefully done. 

Although the vote for final location is ongoing. 
I do hope you have voted.

**Comment by lapin7** [comment]
@Phistr90 Please raise the budget for #194 in Gsheet "Pub...." https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=176786742

**Comment by Keaycee** [comment]
The major issue about the governance conference travel budget is mainly on the members not residing in the United States (North America). There is a huge difference in the ticket reservation fares especially outside the United States. An average ticket fare on economy class within United States ranges from $179 - $250 but for members outside the United States, it ranges from $650-$1,050 on average. I did a budgeting estimate per individual outside the United States due to higher expense incurred. However the Budgeting Estimate can also be used by members within the United State for their travel budget expenses.

Below is an open budget estimate link.

https://docs.google.com/spreadsheets/d/1LygsKXohwez6u0V3aYeWmrtFcYMryqqwCbQR2VS8pAA/edit?usp=sharing

I suggest that members of the governance Committee should come along with a receipt proving the cost of ticket fare (Economy Class Flight) in order to be reimbursed by the cooperative.

**Comment by dckc** [comment]
I would appreciate support to travel to the governance conference to share my [15 years of consensus building in the World Wide Web Consortium](https://www.w3.org/blog/2010/06/thanks-for-a-great-15-years-at/).

I would be travelling from Kansas City airport (MCI). Flights seem to be priced around $375. $100/day * 5 = $500 should suffice for food, lodging, and ground transportation.

**Comment by patrick727** [comment]
@dckc yes!

**Comment by lapin7** [comment]
Let's just say that RChain reimburses travel and lodging cost at a fair rate. The only thing a visitor has to do is to send in proves of expenses.
BTW There's no upfront payment. The budget of this issue should be used for "organizing" the reimbursement. Not for actual reimbursements. Therefore I've changed the suggested rewards for December in TAB: Rewards 201712

**Comment by lapin7** [comment]
I've made a [proposal](https://github.com/rchain/Members/issues/194) that has to be approved by the COO and/or CEO.

Feel free to edit in suggestion mode.

**Comment by dckc** [comment]
Is encouraging international participation a goal? The financial burden would be higher for those further from the venue. I'm still learning what RChain's goals are w.r.t. international collaboration.

That's the most substantial of my comments; I annotated the proposal with that and other comments.

**Comment by Keaycee** [comment]
@lapin7  In line with the proposal on governance conference,  I created this form with the characteristics stated on the proposal. Members of the RChain cooperative who would like to attend the Governance Conference are expected to fill in the form below. 

https://docs.google.com/forms/d/e/1FAIpQLSc7PSiN8D0Af60Wbaz-sMnt0jMcFjO5EZMxjHYuGFiU7y1DDQ/viewform

This form would be a placeholder form pending approval by the Board on the proposal

**Comment by dckc** [comment]
@Keaycee would you please mark that form "draft" or something?

**Comment by lapin7** [comment]
Make it a draft and editable for rchain@googlegroups.com

Maybe it's nice to integrate these forms:

https://docs.google.com/forms/d/e/1FAIpQLSc7PSiN8D0Af60Wbaz-
sMnt0jMcFjO5EZMxjHYuGFiU7y1DDQ/viewform
https://docs.google.com/forms/d/171oKtb6Y7h3ICeoVkUoWQeSTc8vD2bU8YHns9tRd3os/edit


I like sections and before a section begins you can add a way out to
submit. When you get bored of the form you can submit at any moment.

--
Cheers,
HJ

**Comment by Keaycee** [comment]
@lapin7 it's open for rchain@googlegroups.com to make any necessary update or edit.

**Comment by dckc** [comment]
This is done to my satisfaction.
