### ISSUE TITLE
M> Influencer Outreach / Research Groups/ Directories tracking sheet 

### ISSUE THREAD

**Issue by traviagio** [rchain/bounties#198]
As a background: I asked earlier in the general channel that I want to start outreaching to podcasts/blogs/influencers/directories but I wanted to make sure that it's coordinated effort and that I don't reach out to people you may have already contacted. For example @Mervyn853 did Chainrock and few others did CryptoCompare etc.) 

After discussing it over with the marketing group we decided to 1) Make this a group effort and get more people involved 2) Use the spreadsheet to as a base to track our efforts 3) Include issue #193 in the sheet for tracking as suggested by @Mervyn853 

Here is the spreadheet link: https://docs.google.com/spreadsheets/d/1M9kqbnYxotaOLtWOj7MWquE41KADZJLtwFdgDqtoEck/edit?usp=sharing 

Already done tasks must post a link in 'RChain submission link' and add your name to 'assigned to.' For example I just addded @Mervyn853#1350 to 'Rockchain' 

Huge thanks @lapin7 for helping out with this process earlier.

**Comment by llerner** [comment]
All, this is great work and much appreciated.

As @leithaus mentioned in the Dev and Community hangouts, I am driving some of our Marketing efforts with @patrick727. I've implemented a CRM to collect and manage communication Partner, investors, media (influencers, bloggers, press, etc.). We'll have one source of truth and this becomes a company asset for contacting third parties.

Fill in what information you can collect. Company, URL and other contact info at a minimum. 

Could I ask whoever is maintaining the spreadsheet link to replace it with this one for the CRM we're using? I will upload the contacts and use it as part of awareness building. I also need to be careful about sending too many unsolicited emails. Media people are generally ok with those.

I am getting a lot of good requests and feedback for RChain from the speaking events I've delivered. We'll be soliciting more content from the community as part of our awareness building. 

Onward.

Lawrence


[RChain Media Contacts 12-2017.xlsx](https://github.com/rchain/Members/files/1543519/RChain.Media.Contacts.12-2017.xlsx)

**Comment by lapin7** [comment]
@llerner Is it possible to get access to your CRM?
Which application are you using?

**Comment by llerner** [comment]
I’ve taken two licenses for FreshSales. it’s a subscription model, we’re paying for it from Holdings. @edeykholt and I have licenses. I can do exports as needed.

**Comment by lapin7** [comment]
In the coop we do some email things with ZoHo.
I suggest to use [HubSpot](https://www.hubspot.com/crm/e010a?utm_content=e010a&utm_term=crm&utm_campaign=Capterra-AllCountries-AllSegs&utm_medium=paid&utm_id=e548a&utm_source=capterra) for the Coop.
It's free and it has more features then FreshSales.
We could now and then do a sync between the two apps

**Comment by llerner** [comment]
That would have been good to know. I think we should settle on one product and create two instances if necessary. Can we touch base offline and discuss on the needs of the team? Since I am supporting both I'd like to have one way for us to message the community. 

I'll ping you on Discord.

**Comment by patrick727** [comment]
For an immediate solution bridging organizations I like @llerner 's suggestion of

Have the existing CRM
Update xl file ongoing

**Comment by lapin7** [comment]
Let's talk Monday on a zoom.

**Comment by Ojimadu** [comment]
@lapin7 what time is the meeting today?

**Comment by ResonanceXX** [comment]
I saw somewhere 7am PDT. Which is about +8 Hours on the GMT.


 
 
  On Mon, 18 Dec 2017 at 7:20, Ojimadu<notifications@github.com> wrote:   
@lapin7 what time is the meeting today?

**Comment by Ojimadu** [comment]
That's for a different meeting.

**Comment by ResonanceXX** [comment]
Okay. I understand. 

Sent from Yahoo Mail on Android 
 
  On Mon, 18 Dec 2017 at 7:32, Ojimadu<notifications@github.com> wrote:   
That's for a different meeting.

**Comment by traviagio** [comment]
@llerner the excel sheet you shared only contains one entry. Is this correct or did you mean to send another one?

**Comment by llerner** [comment]
It’s for others to fill in the contacts they’ve received. It’s there as an example.

Sorry for some reason notifications are coming late to me. 



========================
Lawrence I Lerner
o/m: 630.248.0663
lawrencelerner@gmail.com

Blog: lawrenceilerner.com
 <http://www.lawrenceilerner.com/>twitter: RevInnovator <https://twitter.com/#!/RevInnovator> 



On Dec 17, 2017, at 23:42 , Georgi Georgiev <notifications@github.com> wrote:

@llerner <https://github.com/llerner> the excel sheet you shared only contains one entry. Is this correct or did you mean to send another one?

**Comment by traviagio** [comment]
@llerner can you add it to Google Docs then rather than excel file? That way I can just point the e-mails section from this the current list to your sheet.

**Comment by Ojimadu** [comment]
@traviagio You can update the file with the xls sheet with the one posted by llerner above. He requested that to be done by the person managing the first sheet we were using.

**Comment by traviagio** [comment]
@Ojimadu  @llerner to keep things simple, we haven't yet and won't be collecting influencer/media contact details in this sheet. For now we will just limit this project to Directories list and Research Groups.

**Comment by kitblake** [comment]
Fyi, I've appended an "Address Roster" sheet to track all the RChain Internet addresses and their attributes (as discussed with @patrick727) for all the comm channels:
https://docs.google.com/spreadsheets/d/1M9kqbnYxotaOLtWOj7MWquE41KADZJLtwFdgDqtoEck/edit?usp=sharing

It also lists addresses that are parked, or not in use, so scammers can't create them in the future. Not complete yet..

**Comment by patrick727** [comment]
thanks @kitblake I added linked in

**Comment by patrick727** [comment]
@decentralizebanksy went ahead and added a bunch of "infleuncers" and "followers"

Alberto maybe you can coordinate with @llerner to continually update the exel sheet so we can update CRM

**Comment by decentralizebanksy** [comment]
Hey all, 

I added a bunch of my twitter network to the influencer section. I'll make sure to add more as I come across more influential people in the space. 

I think it would be a great idea to add a section dedicated to FB groups, google + communities, meetups, and other forums with hyperlinks directing to those respective locations. 

Sincerely,

Alberto

**Comment by patrick727** [comment]
I added a permissed section to the spreadsheet titled "CRM" with the .xml format that will make it easy to import into the CRM. 

It might be best to seperate this initiative into two distinct operations. 

1. CRM (ACtualy management of contact relations)
2. Market Resources ( location where we input groups, channels, competitions)

**Comment by lapin7** [comment]
Could we add also "investors with interest in RChain"?

--
Cheers,
HJ

**Comment by Mervyn853** [comment]
Updated the sheet to reflect the status of connecting RChain with influencers like Jackson Palmer and Blockchain Brad which concluded in this wonderful interview.  https://www.youtube.com/watch?v=PwuV7ryhaXw

Have a few more influencers who have reached out to me expressing interest in conducting interview. Will update the progress in the influencer tab.

**Comment by kitblake** [comment]
@Mervyn853 I notice there's no budget set on this issue. I added one.

**Comment by traviagio** [comment]
@Mervyn853 please update the sheet if there are any new Research Reviews in the pipeline. I just updated all the progress in the marketing directories part.

**Comment by Mervyn853** [comment]
Updated the sheet with latest review by :
**Cryptosyndicate** https://thecryptosyndicate.com/rchain-multi-threading-blockchain/
**Coin Central** https://coincentral.com/rchain-beginner-guide/

Also updated The Crypto Lark interview with Lawrence Lerner and Nash Foster here https://www.youtube.com/watch?v=2SiEBpSI6Uo

Will update again with a few more interviews scheduled @traviagio

**Comment by AyAyRon-P** [comment]
@traviagio are there any updates to this project? Do we need to add anything or can we close this out and archive the links in the issue?
