### ISSUE TITLE
From Pi Calc to Rholang

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#199]
M> Indicates that this is a project within the "Marketing" category
(B) Indicates that this is a Blog post

Goal:

Create a 2-5 blog post educational series taking people from pi calculus > rho calculus > rholang

**Comment by lapin7** [comment]
Please add links to the sections of the blog post.

**Comment by dckc** [comment]
progress: http://www.madmode.com/togl/picalc2
source: https://github.com/dckc/togl/blob/master/picalc2.lidr 348340d

@Jake-Gillberg maybe re-purpose this issue for the stuff we talked about? Or we could close this and make a new one.

**Comment by dckc** [comment]
See also: https://github.com/RChain-Collaborative-Learning/PiCalculus

**Comment by dckc** [comment]
This seems to be subsumed by #755.

**Comment by dckc** [comment]
nearby: [RHOL-331 Come up with a formulae for describing all possible blockDAGs in Greg's graph algebra](https://rchain.atlassian.net/browse/RHOL-331)
