### ISSUE TITLE
M> Create Assign Other Social Media Channels

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#200]
M> Indicates that this is a task within the "Marketing Category"

Goal: 

Because of membership activism is the one of the top in the space we can differentiate by hitting the long tail of social media and forums.

Where can we go that others are not? 

RChain leeroy?
RChain steemit profile? 

hackernews? 
others youtube livestreams?

If you frequent random channels let me know, or we can add these to another sheet such as the one that georgio was creating.

**Comment by ResonanceXX** [comment]
@patrick727  Very eager to work on this issues with guidance from yourself. 
.Leeroy  and steemit.. Are good platforms to brighten the Rchain brand light. 
I'm off to create accounts.

**Comment by ResonanceXX** [comment]
While my applications for a profile is processed on steam. 

Steemit is a wonderful platform where curated contents can also earn money. Owners describe it as a decentralized social network similar to twitter. Cryptocurrency issues, especially of bitcoin was abundant. Now would be a good time for the rhoc to get some "game time"

The only limitation was the coop official email address. Needed to reply an activation link. Time is always of the essence to ensure the unique "rchain'username was not claimed by spammers who have been known the prowl recently.

**Comment by ResonanceXX** [comment]
The leeroy Setup requires installing a MetaMask plugin to complete. 
Was doing that with my Android device. Would complete with a PC.

**Comment by ResonanceXX** [comment]
Hurray!
Steemit approval has been granted after a somewhat agonising wait. 

Profile link was sent. Right now. 


https://steemit.com/start/35b1456e47d6c95e54fda40fde
 I'll go ahead to make changes.

**Comment by patrick727** [comment]
@ResonanceXX thanks Chris! 

This looks good, feel free to take the lead with this. 

It also be awesome if we had a category in steemit, like a subreddit.

**Comment by ResonanceXX** [comment]
@patrick727 need a password for that. Do you have that?

**Comment by pmoorman** [comment]
I guess this issue can be closed? It's getting dated. @patrick727
