### ISSUE TITLE
M> Thoughts on "Blockchain Governance"

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#205]
Let's reach out to industry professionals and get their thoughts on blockchain governance. 

It could be a paragraph or it could be an in depth article. 

We will use this to build buzz for the blockchain governance conference

**Comment by patrick727** [comment]
Joe Blankenship will be doing a guest post with his thoughts on blockchain governance

His work can be found here https://github.com/joeblankenship1

**Comment by ResonanceXX** [comment]
[Block.docx](https://github.com/rchain/Members/files/1579964/Block.docx)
  

This is a little summary of Fred Ehrsam's views.

**Comment by patrick727** [comment]
@ResonanceXX is this original content? 

Would be cool if you reached to him and got permission to post this, or asked him to expand his thoughts on this summary for a guest post on our medium. 

good work!

**Comment by patrick727** [comment]
An adviser from the World Economic Forum will be sharing a post as well!

Anyone else have updates?

**Comment by patrick727** [comment]
Anthony the founder of Raincube will be creating a post as well.

**Comment by patrick727** [comment]
Alex Landry of earth.nation and earth democracy will also be creating a post

**Comment by Ojimadu** [comment]
I don't really know these guys but it feels nice seeing the steam build up for the governance conference.n good work @patrick727

**Comment by ResonanceXX** [comment]
Patrick you done it yet again. Well done!!

Sent from Yahoo Mail on Android 
 
  On Sat, 6 Jan 2018 at 19:10, Ojimadu<notifications@github.com> wrote:   
I don't really know these guys but it feels nice seeing the steam build up for the governance conference.n good work @patrick727

**Comment by patrick727** [comment]
some individuals from the blockchain education network will be creating posts as well. 

yes this space is so big that its hard to keep track of everyone, but so long as there posts are thoughtful we will use them and give them our platform. 

we cherish the ideas and the actions more then the names and the labels

keep em coming!

**Comment by Viraculous** [comment]
This a marketing strategy using opinion leaders in the blockchain technology. In issue  #221 I sent a request to Trebor Scholz but still felt that to getting the contacts of a range of top influencers in the blockchain community. Here is link with the 50 top influencer in blockchain systems: https://www.rise.global/top-fintech-people we could reach them out.

**Comment by Keaycee** [comment]
Good idea @Viraculous , let's reach them and get a feedback

**Comment by pmoorman** [comment]
closing this, since we're past the "blockchain governance conference" and this issues has run it's course.
