### ISSUE TITLE
O> Chantal as host of member debrief meeting

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#206]
@dcpnlau is invited to host the weekly member debrief meeting
She will:
- act as the chairman
- host the meeting
- make summaries
- prepare newsletter updates
- and more

**Comment by ResonanceXX** [comment]
Best of luck to her. Well done.

**Comment by kaka56** [comment]
That's a very good effort. All the best.

**Comment by dcpnlau** [comment]
Hi Everyone,

Nice to meet you and thanks for the introduction.

I will kick off hosting the weekly meeting in January. I am based in Sydney
so time difference can make meetings slightly challenging. Can you
therefore let me know which of the below works best for you - day and time
with most votes win:

Tuesday 8:30am CET
Tuesday 9:30am CET
Wednesday 8:30am CET
Wednesday 9:30am CET

I understand that you are still in the process of assigning roles and
responsibilities within Rchain.

With that in mind, can you please answer the questions below (can be reply
all or to myself only) so I understand what you'd like to contribute and
how the meetings will be most effective for you. I will then use that to
make sure everyone can work on their preferred subject matters, best use
their skills and make the meetings as useful as possible.

1) What role would you like to fulfil within Rchain?
2) What are your main skills that you can apply to Rchain?
3) What would you like to take out of the weekly meetings?

I look forward to hearing from everyone.

Thanks,
Chantal

**Comment by vishyim** [comment]
Hi Chantal

Nice to meet you :)

I could help with digital marketing and white hat Seo (area of expertise)
and am also very proficient in WordPress development and setup.

Happy to help as needed

Best
Vishal
YetiYogi.com

**Comment by lapin7** [comment]
For your questions I could make a google form.

**Comment by patrick727** [comment]
Hey @dcpnlau nice to have you on Board!

I currently help with a lot of the digital marketing and community building activities. 

Cheers

**Comment by patrick727** [comment]
hey @dcpnlau can ypou put your availability into this?

https://meeting.freecodecamp.org/event/5a43e8221f9aac1956bb5fe0

**Comment by Ojimadu** [comment]
A google form would make it easier to collate and analyse data. Welcome aboard @dcpnlau

**Comment by dcpnlau** [comment]
Thanks to those who replied.

I had a look at the calendar and realised that my time zone and
availability isn't ideal - most of the suggested times are during the night
time for me. If there are weeks where more people can make it and I can't,
I'm more than happy to have someone else facilitate the meeting, but we can
play it by ear.

Who manages the calendar? Is there a new calendar for the next few weeks?
Might be good to set availability for a few weeks out so everyone can
manage their diaries better.

I also created a Google form to answer my questions (thanks for the
suggestion), which you can find here
<https://docs.google.com/spreadsheets/d/1YbmexWhD8MYXGT5NYoUqwSN3wKQ98avh_7U45kBN_g8/edit?usp=sharing>
.

Let me know your thoughts.
Thanks!

**Comment by Ojimadu** [comment]
@dcpnlau The link you sent is a spreadsheet and not a google form. Please recheck the link.

**Comment by kitblake** [comment]
Hi @dcpnlau, 
Setting a time for the meeting that works across the world is going to be tricky. Currently, the Member activist meeting is Wednesdays at 19:00 CET (UTC +1). This works nicely because it's followed by the Weekly Debrief (with a much larger group) at 20:00 CET. Often we plug in some points from the Member meeting into the Debrief. 

If you're in Sydney that's UTC +11 so I presume the current Member meeting takes place at 5:00 in the morning for you. Are you a very early bird? ;)

**Comment by lapin7** [comment]
Hi @dcpnlau,

Below you find a shortened time table that defines the ideal time for you
and the rest of the world.
Wednesday is a great day because it's after Weekly Debrief of Greg is also
around that time.
Instead of doing it before Greg's meeting, we're going to do after that
meeting.
So the next meeting is at: 10th of January, at 21:00 GMT (UTC)
We will see who is going to join.

GPS -41,174 -33,151 52,4 51,0 42,-78 47,-122
Delta Hours GMT 13 11 1 0 -5 -7
Time Code NZDT AEDT CET GMT EST PST
Country Wellington Sydney Amsterdam London New York Seattle
Meet 10 8 22 21 16 14

​If you want to find another time slot, please look at this time table:

https://docs.google.com/spreadsheets/d/1L48czfHqeCrZHbZL3COtDnl9BZ0DQywxhC64pTVPomU/edit#gid=0
​

--
Cheers,
HJ

**Comment by lapin7** [comment]
GPS | -41,174 | -33,151 | 39,116 | 52,4 | 51,0 | 42,-78 | 47,-122
-- | -- | -- | -- | -- | -- | -- | --
Delta Hours GMT | 13 | 11 | 8 | 1 | 0 | -5 | -7
Time Code | NZDT | AEDT | CST | CET | GMT | EST | PST
Country | Wellington | Sydney | Beijng | Amsterdam | London | New York | Seattle
Meet | 10 | 8 | 5 | 22 | 21 | 16 | 14

**Comment by Ojimadu** [comment]
@lapin7 The meeting on 10th of January, at 21:00 GMT (UTC). That would make it difficult for me to attend. I usually catch up with the debriefs but can't find anywhere the members meeting is uploaded on youtube for persons that missed out and would like to catch up.

**Comment by lapin7** [comment]
@Ojimadu 
Oh that's a pity. What's your time difference with GMT/UTC?
We will do it anyway on 21:00 GMT (UTC).
The recordings can be seen at https://www.youtube.com/user/lapinutube

**Comment by Ojimadu** [comment]
@lapin7 My time is UTC +1. It's not a big problem as I can always catch up. Thanks for the YouTube link.

**Comment by lapin7** [comment]
OK,
Please get in touch with ResonanceXX ( Kenechukwu Oliaku )
for setting up a Telegram group for Nigeria or Africa.
Maybe you have some ideas about that ;-)
--
Cheers,
HJ

**Comment by Keaycee** [comment]
@lapin7  It's nice creating a Telegram group for Africa rather than Nigeria alone.  It's a very good idea as it educate individuals about the future crypto coin. I will support in doing the marketing aspect in Africa, precisely Nigeria.  Nice work.

**Comment by lapin7** [comment]
Please create an issue: >M Telegram Africa
Discuss about a name, something like: RChain_Africa
Add a budget of for example $1000

--
Cheers,
HJ

**Comment by ResonanceXX** [comment]
@lapin7 Did a little digging around. 
Chanced to discover the Dutch (Netherlands)  community Telegram name - "RChain_nl"

1) For the purpose of consistency should the nomenclature for the proposed new telegram group name be similar I. E RChain_(NG)  An abbreviation for Nigeria. 
2) Also helps clarify above. I believe that dealing with the Nigerian community alone could be premature. So "RChain_Africa" or "RChain Africa" seems more compliant. 
The latter could aid better intersection of interested potential members. 
*Including the underscore symbol may prove too novel for some potential members.(No offences meant to Africans)
Additionally Telegram's word search auto complete may solve this. But there seems to be a growing list of branching RChain groups. 
Let me know your thoughts on this also.

**Comment by lapin7** [comment]
Yes in fact I'm also against - and _ 
If a space works then that's fine as well
@kitblake and I were discussing this naming also. RChainNL was also an option.

And by the way: Announcement:


Zoom Meeting ID:Date, time | https://zoom.us/j/197490909 (webinar)2018-January-17, 20:00 UTCSydney +11, Beijing +8, Lagos +1, Amsterdam +1, New York -5, Seattle -8
-- | --
Agenda + Minutes: | https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64/edit#heading=h.whshgyg00kl0
Youtube recording: | https://www.youtube.com/user/lapinutube

**Comment by ResonanceXX** [comment]
I concur with the both of you. I have a personal bias against the extra symbols. 

Sent from Yahoo Mail on Android 
 
  On Thu, 11 Jan 2018 at 18:11, HJ Hilbolling<notifications@github.com> wrote:   
Yes in fact I'm also against - and _
If a space works then that's fine as well
@kitblake and I were discussing this naming also. RChainNL was also an option.

And by the way: Announcement:

| Zoom Meeting ID:Date, time | https://zoom.us/j/197490909 (webinar)2018-January-17, 20:00 UTCSydney +11, Beijing +8, Lagos +1, Amsterdam +1, New York -5, Seattle -8 |
| Agenda + Minutes: | https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64/edit#heading=h.whshgyg00kl0 |
| Youtube recording: | https://www.youtube.com/user/lapinutube |

**Comment by Tonyprisca13** [comment]
@dcpnlau Impressive work well done.

**Comment by tcezi** [comment]
All the best to her.

**Comment by dckc** [comment]
This appears to be done.
