### ISSUE TITLE
Explore solutions for member voting

### ISSUE THREAD

**Issue by jimscarver** [rchain/bounties#209]
https://www.coindesk.com/voting-scheme-ethereum-doesnt-give-away-vote/

**Comment by dckc** [comment]
I read the article and browsed the code... it looks plausible, especially since our membership isn't yet so large that we need a mechanism that is robust in the face of concerted attack. We trust each other, mostly, and if something goes wrong, we can just talk it over.

The code is 1300 lines of solidity, and it would take a long time for me to convince myself it has no bugs.

**Comment by patrick727** [comment]
@dckc good points
@jimscarver thanks

@Jake-Gillberg is also considering voting mechanisms for a while and has some ideas worth sharing soon

**Comment by barneycinnamon** [comment]
@jimscarver Looking at this issue and thinking about our discussions about Loomio, ConsiderIt, Discord emoji polls, etc. It seems like various tools have been explored and used at different times with varying levels of success. I think @Jake-Gillberg has the more consequential votes covered in issue #399, so I am wondering if this issue has ongoing import as a marker for revisiting the polling debates, or if we should close it and figure that members will use a mix of Loomio and Discord emoji polls depending on context.

**Comment by jimscarver** [comment]
@barneycinnamon Loomio and considerit are decision aids, not proven official vote. Making decisions is about developing consensus, not voting so much. As Vlad says, the vote just confirms what has already been decided. Voting helps get the sense of group sentiment but the results need not make any final decision.

I suggest as a governance working group activity we experiment and evaluate decision processes that might enhance our collective intelligence. I think we can close this issue and add one on decision process research and experimentation perhaps.
