### ISSUE TITLE
RHOC Missing In Wikipedia's Official List Of Cryptocurrency. 

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#212]
I came by this problem about two weeks ago. Since that time, howbeit painstakingly, I have applied to Wikipedia for Editor powers. Seemed my Regional location was not eligible. 

The good news however is this: I have gotten provisional authority to edit the page, include the RHOC and give it plenty of exposure. 
All of this would not have been possible if I had not searched for such a vague information. This adds to the authenticity and desirability of the RHOC.

**Comment by n10n** [comment]
Can you please add wiki link also?

**Comment by dckc** [comment]
applied to Wikipedia for Editor powers? I'm not familiar with that process. Anyone can edit any wikipedia page, no?

I see a https://en.wikipedia.org/wiki/List_of_cryptocurrencies page. I don't see RHOC there. I wonder if it's sufficiently [noteable](https://en.wikipedia.org/wiki/Wikipedia:Notability). Ah... "The notability guidelines do not apply to contents of articles or lists". So I started to add it. But on the Talk page, I see "Having mainstream media 'specifically' mentioning it." among criteria the editors are using for inclusion. I don't think RHOC nor RChain has been mentioned in mainstream media yet. So far, it's one of many ERC20 tokens. I'm not inclined to say much about RChain in wikipedia until RChain is closer to 1.0.

Since the markup took me a few minutes, I suppose I'll save my edit here:

```
| <!--Year Est.      --> 2017
| <!--Active/Inactive--> {{no|Development}}
| <!--Currency       --> RHOC, Rev
| <!--Code           --> RHOC
| <!--Founder        --> Greg Meredith
| <!--Hash algorithm -->
| <!--Timestamping   --> [[Proof-of-stake|PoS]]
| <!--Notes          --> RChain is rooted in a formal model of concurrent and decentralized computation. The RChain Cooperative is leveraging that model through correct-by-construction software development to produce a concurrent, compositional, and scalable blockchain.<ref>{{cite web|title=RChain FAQ|url=https://github.com/rchain/reference/blob/master/faq.md|website=Github|accessdate=27 Dec 2017}}</ref>
|-
```

**Comment by ResonanceXX** [comment]
Exactly. I was on the exact same level of work. Was unable to add update(recently fell ill) "We can push for RHOC publication by drawing attention to some of our "good media"
Media marketing can help us with articles from just about any competent blog, website, Cryptocurrency expert around. 
Nice work Dan, All. Myself too. Quick recovery to me too. 

Sent from Yahoo Mail on Android 
 
  On Thu, 28 Dec 2017 at 0:51, Dan Connolly<notifications@github.com> wrote:   
applied to Wikipedia for Editor powers? I'm not familiar with that process. Anyone can edit any wikipedia page, no?

I see a https://en.wikipedia.org/wiki/List_of_cryptocurrencies page. I don't see RHOC there. I wonder if it's sufficiently noteable. Ah... "The notability guidelines do not apply to contents of articles or lists". So I started to add it. But on the Talk page, I see "Having mainstream media 'specifically' mentioning it." among criteria the editors are using for inclusion. I don't think RHOC nor RChain has been mentioned in mainstream media yet. So far, it's one of many ERC20 tokens. I'm not inclined to say much about RChain in wikipedia until RChain is closer to 1.0.

Since the markup took me a few minutes, I suppose I'll save my edit here:
|  2017
|  {{no|Development}}
|  RHOC, Rev
|  RHOC
|  Greg Meredith
| 
|  [[Proof-of-stake|PoS]]
|  RChain is rooted in a formal model of concurrent and decentralized computation. The RChain Cooperative is leveraging that model through correct-by-construction software development to produce a concurrent, compositional, and scalable blockchain.<ref>{{cite web|title=RChain FAQ|url=https://github.com/rchain/reference/blob/master/faq.md|website=Github|accessdate=27 Dec 2017}}</ref>
|-

**Comment by ResonanceXX** [comment]
Also Dan. You're able to Edit liberally because of the location of your IP. Where I am, this powers so not exist so liberally. We have to apply for them.

**Comment by dckc** [comment]
Wikipedia's stated [editing policy][1] is:
> ... anyone can edit any unprotected page and improve articles immediately for all readers. You do not need to register to do this.

So you don't need to apply to them. Is there some other party between you and Wikipedia that you need to apply to? Would you care to share a pointer to this application process?

Have you tried [creating a wikipedia account][2]? (for reference, the user page for my account is https://en.wikipedia.org/wiki/User:DanConnolly ) 

[1]: https://en.wikipedia.org/wiki/Help:Editing
[2]: https://en.wikipedia.org/wiki/Wikipedia:Why_create_an_account%3F

**Comment by ResonanceXX** [comment]
![screenshot_20171228-014844](https://user-images.githubusercontent.com/34219332/34396922-732db662-eb71-11e7-97dd-a374a0406401.png)
@dckc 
![screenshot_20171228-014829](https://user-images.githubusercontent.com/34219332/34396921-6b30758a-eb71-11e7-9dff-d9dd6c6caeb0.png)

**Comment by ResonanceXX** [comment]
![img_20171228_015322_191](https://user-images.githubusercontent.com/34219332/34396985-ed777fe8-eb71-11e7-99cd-0b3685e40f0c.jpg)
![screenshot_20171228-014844](https://user-images.githubusercontent.com/34219332/34396990-f552b8e0-eb71-11e7-820b-278270114f9f.png)

**Comment by ResonanceXX** [comment]
@dckc This was the reason! Deleting your previous comment was unintentional. Did I have it mixed up? Was there an easier way to go about things that I didn't?

**Comment by dckc** [comment]
OK... the [blocking policy](https://en.wikipedia.org/wiki/Wikipedia:Blocking_policy) is new to me. I wrote a [request to reconsider blocking those IP addresses](https://en.wikipedia.org/wiki/User_talk:Primefac#Reconsider_indefinite_block_of_197.210.0.0/16?).

**Comment by ResonanceXX** [comment]
Abundantly helpful Dan. Wikipedia is an amazing place to be locked out from. 

Sent from Yahoo Mail on Android 
 
  On Thu, 28 Dec 2017 at 17:47, Dan Connolly<notifications@github.com> wrote:   
OK... the blocking policy is new to me. I wrote a request to reconsider blocking those IP addresses.

**Comment by ResonanceXX** [comment]
@dckc I revisited the page, and those changes to not seem to have reflected. Are you aware?

**Comment by dckc** [comment]
@ResonanceXX I don't understand your questions. You revisited which page? And which changes are not reflected?

**Comment by ResonanceXX** [comment]
The rhoc is still not listed on the Wikipedia page. That contains the list of cryptocurrency.

Sent from Yahoo Mail on Android 
 
  On Wed, 3 Jan 2018 at 19:43, Dan Connolly<notifications@github.com> wrote:   
@ResonanceXX I don't understand your questions. You revisited which page? And which changes are not reflected?

**Comment by dckc** [comment]
Why would you expect RHOC to appear on https://en.wikipedia.org/wiki/List_of_cryptocurrencies ? Did you address your blocking issue and make an edit there? As I explained [above](https://github.com/rchain/Members/issues/212#issuecomment-354197347), I did not.

**Comment by ResonanceXX** [comment]
I assumed you handled it because you put the picture. Honestly, that made me feel it had resolved. I revisited that just as a spare time. Unknown to me it was still unchanged.  

Sent from Yahoo Mail on Android 
 
  On Wed, 3 Jan 2018 at 19:49, Dan Connolly<notifications@github.com> wrote:   
Why would you expect RHOC to appear on https://en.wikipedia.org/wiki/List_of_cryptocurrencies ? Did you address your blocking issue and make an edit there? As I explained above, I did not.

**Comment by dckc** [comment]
@ResonanceXX the response I got from Wikipedia was:
> you may use the Unblock Ticket Request System at http://utrs.wmflabs.org/ and an administrator will look into your request.

I tried using that ticket system, but it is asking questions that only make sense when answered by you, the person being blocked.

**Comment by ResonanceXX** [comment]
Okay. Wikipedia. 

Sent from Yahoo Mail on Android 
 
  On Thu, 18 Jan 2018 at 0:49, Dan Connolly<notifications@github.com> wrote:   
@ResonanceXX the response I got from Wikipedia was:


you may use the Unblock Ticket Request System at http://utrs.wmflabs.org/ and an administrator will look into your request.


I tried using that ticket system, but it is asking questions that only make sense when answered by you, the person being blocked.

**Comment by dckc** [comment]
Until RHOC or RChain is mentioned in mainstream media, the fact that it's not in wikipedia is as-designed.
