### ISSUE TITLE
M>RChain; Why Cooperative?

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#213]
Hello good day all. I was introduced to the RChain cooperative by @Ojimadu  and have had quite a thrilling experience exploring through the global economy of blockchain technology. That of the Rchain cooperative particularly caught my interest more for using a cooperative model because I have had an academic background on Cooperative Economics and Management and currently on Economics. I wish to promote the interest of this community and its members as a cooperator by starting first with this article.  Please I would like to post this article in other social platforms but needs your assistance of reviewing it to check for mechanical and other errors before posting. Thanks.

https://drive.google.com/open?id=1EaisxJo7Id1xCkZ_OkAqMH3g20VCgjw5r2kuwdk3RIs

**Comment by llerner** [comment]
@Viraculous thanks for taking time to write this piece. I'll review it from a Marketing perspective and help circulate as appropriate.
Please ping me off list. I'd like to understand your background a bit better and see if there is other collaboration we can work on.

**Comment by Viraculous** [comment]
OK. @llerner

**Comment by n10n** [comment]
Interesting article if they are same https://drive.google.com/open?id=15bSRb-38TtMU5o47eqZ0ihKK8QGbpTun. Sent you access request for the original article.

**Comment by patrick727** [comment]
cool stuff @Viraculous ! will review.

are you looking to publish this as a contributor to RChain medium or through your own independant source?

**Comment by BelovedAquila** [comment]
Fabulous piece by @viraculous very insightful and as well understandable, goes a long way in helping newbies understand Rchain better, Nice!

**Comment by Viraculous** [comment]
Thanks @patrick727. am looking towards being a contributor in the RChain medium.

**Comment by patrick727** [comment]
sweet whats your medium username? @Viraculous 

Once we do our round of feedback, we can have @plantether review it for grammar etc. and then we can schedule it out. 

Is there any way you can do another one about cooperative structures and how they can fit into blockchain governance? 


p.s dont forget to propose a budget for this. 


Cheers!

**Comment by Viraculous** [comment]
Thank you sir. My user name is Victor Ojimadu. Concerning your question, I will in much that is in me.

**Comment by Viraculous** [comment]
Please @patrick727, how do i propose a budget when the issue has not been uploaded to the public member budget-allocation spending?

**Comment by patrick727** [comment]
@lapin7 may be able to answer that better, But I believe that you can simply input the issue into the sheet

Will look more into things this week if it has not been solved.

happy new year!

**Comment by Viraculous** [comment]
Thanks a lot @patrick727 , a Happy and a prosperous new year to you all. Congrats!!!

**Comment by patrick727** [comment]
Happy New year!
@Viraculous are you vimirimious34 on medium? I added you as a writer please accept

**Comment by Viraculous** [comment]
yes @patrick727 thanks a lot man and a prosperous new year to you too.

**Comment by patrick727** [comment]
cheers!
@plantether when you have a moment can you review this article for grammar and spelling?

**Comment by Viraculous** [comment]
yes @plantether, It will be great to have the post on medium, that calls on
the need of proofreading the article. Meaning while am doing a research
more on cooperative organizing and how it suits the blockchain governance.
Thanks @plantether as you cooperate, to @patrick727 and other esteemed
cooperators.

**Comment by BelovedAquila** [comment]
@patrick727 can someone else review the documents for grammatical and spellings error or its just opened to @plantether?, because am open to helping on that.

**Comment by BelovedAquila** [comment]
@patrick727 while reviewing, there were some corrections that needs to me made in the doc, so I requested an edit permission from @Viraculous and he gave the access to comment on the mistakes, so am commenting on them,so he could make the necessary corrections. what do you think please?

**Comment by BelovedAquila** [comment]
@patrick727  i just finished reviewing the article,after @Viraculous makes the necessary corrections that needs be made,then i think the article is good to go.

**Comment by Viraculous** [comment]
Nice review @BelovedAquila. Thanks for your collaboration. Here is the link for the edited text https://docs.google.com/document/d/1EaisxJo7Id1xCkZ_OkAqMH3g20VCgjw5r2kuwdk3RIs/edit

**Comment by dckc** [comment]
Please add a byline to the document and clarify whether it's endorsed by the board of directors.

**Comment by plantether** [comment]
@Viraculous @BelovedAquila @patrick727 Sorry to be so late in replying. Is this still the current version? https://drive.google.com/open?id=15bSRb-38TtMU5o47eqZ0ihKK8QGbpTun 
I do have some suggestions and I want to make sure I'm working in the correct document.

**Comment by Viraculous** [comment]
yea but i would that you review the from the edited document https://drive.google.com/open?id=1EaisxJo7Id1xCkZ_OkAqMH3g20VCgjw5r2kuwdk3RIs

**Comment by dckc** [comment]
Turn on comments, perhaps?

**Comment by lapin7** [comment]
@Viraculous please make a Google Doc of it. Then we can make comments, edit in suggestion mode etc.

**Comment by Viraculous** [comment]
I have done just that.  comments acess is open, thanks/

**Comment by patrick727** [comment]
Great work all, sorry for my late response. 

In the future, no it doesn't need to be only @plantether that does the review. But she is our resident "editor" so that Is why I specifically tagged her. 

But if enough(3+) people review it and sign off, then we should be good to go. 

Cheers

**Comment by Viraculous** [comment]
My vote of thanks to all collaborators for contributions and edit work, you all are Great.

**Comment by patrick727** [comment]
@Viraculous and thank you!

@BelovedAquila @plantether @dckc do you all check off on this?

If yes then we can que it up in medium

**Comment by dckc** [comment]
I have not reviewed more than the first paragraph or so.

**Comment by Viraculous** [comment]
@plantether did the last edit work but dckc can still review but for me I think its set.

**Comment by plantether** [comment]
I think it would be good to have a fresh pair of eyes look at it. Maybe @kitblake has some time. If not, I can go over it another time after @dckc makes comments.

**Comment by Viraculous** [comment]
Ok@plantether

**Comment by Keaycee** [comment]
Great job @Viraculous this is such a very nice piece and it does has an impact in members of RChain cooperative.

**Comment by Keaycee** [comment]
The article is good and it's ready to be que on medium @patrick727 . We can also make a last review before putting it up on medium.

**Comment by dckc** [comment]
I haven't managed time to review this. Don't wait for me.

I hope @llerner finds time.

**Comment by drbloom** [comment]
@patrick727 - Please be sure that any publication or endorsement going out under "RChain Cooperative" has first been reviewed and approved by an authorized representative of the Cooperative.

Getting three up-votes by participants on GitHub may be a high enough bar to prompt further *participation*, but is not sufficient to represent the Co-op of over 720 members.
