### ISSUE TITLE
M> Consolidating channel (social) media links

### ISSUE THREAD

**Issue by n10n** [rchain/bounties#214]
https://github.com/rchain/Members/blob/master/projects/LinksToOfficialChannels.md
and 
https://github.com/rchain/reference

Can we consolidate list in one place? and reference on page everywhere. We have these links in many places and some of them are old/outdated. Please send a pull request for "reference" repo.

**Comment by kitblake** [comment]
If you're suggesting merging this with the FAQ, I/we don't think that's a good idea. Because:
- Updating the FAQ requires a pull request and it is often out of date, easily for hours and sometimes for many days.
- Usually the channel operators want to send someone to this list only, and not the entire FAQ.
- When a critical issue arises (like EtherDelta getting its DNS hacked) the operators need to respond immediately.

For these reasons we like keeping it in /Members, where the operators have checkin rights and can edit at will. Btw, we also have the Telegram channel rules stored in:
https://github.com/rchain/Members/blob/master/projects/bots/groupbutler/rules.md

As for keeping it synced with the FAQ, that's something I handle personally (but anyone else is welcome to jump in!).

**Comment by n10n** [comment]
@kitblake, I hear your concerns. Lately, I've been paying more attention to Github updates. Going forward will merge pull request quickly and @patrick727 also has access. You will not have issues merging items anymore. Keeping the documents in one place is better than syncing. Let me know what you think.

**Comment by kitblake** [comment]
@n10n Great to hear that pull requests and merges will happen quickly! That's a definite friction point in the FAQ workflow and if we can reduce it to hours that would be agile.

The channel list is used in multiple channels. It works like an abridged FAQ and is really handy. Of course when questions arise that aren't answered in the list, then we link directly to the entire FAQ.

When things are quiet the Telegram group operators use the channel list as the Pinned Message. Then when new users inevitably ask a typical question we say "See the pinned message". It's easy group management and the Github file provides up-to-date content.

However when a burning issue is current, like the ED hack or the scam form, we pin a different message and then, when a typical question comes up, we link to the list.

So we don't want this list to be merged with the FAQ as it fulfills a different function. Of course, I understand your wishes and in the interest of non-duplication we could merge it. But then the operators will end up editing the Pinned Message manually, it'll get out of sync, and avoiding that is why we collaboratively maintain this list. Any changes in the list get immediately fed into the FAQ, if they apply. But the FAQ has a different channel list for a different purpose. 

But most important is this allows us to respond instantly which is a requirement in the crypto environment. We can't wait a few hours to update info about scams and hacks. We have to respond in seconds.

**Comment by kitblake** [comment]
Just to be clear @n10n, your input is appreciated. It helped us to evolve.

**Comment by n10n** [comment]
@kitblake I believe I'm missing something from this discussion. Let's have a quick hangout session. Similarly, I see fragmentation in how RChain communicates with the community and similarly, the documentation we need to support it. Let me know the best time, I'm on Seattle, PST.

There can be many channels where the community can interact with each other but we shouldn't have so many official channels. I'm on the Telegram web. I don't see any pinned message and welcome message is pointing toward a pinned message, for example, "Welcome xxx, Please be aware that a scammer has published a Google form about a fictitious sale/airdrop. See the pinned message.". When people are coming into these channels, we should direct them in some meaningful way i.e. some documentation and the role they would like to play, could be a developer etc.. Public Discord seems to be the most official channel at this moment and we have bots doing some message exchange.

**Comment by kitblake** [comment]
Quick detail: are you using Telegram on (Mac) desktop? If so, the pinned message doesn't automatically appear. To see it, click on the group header (where it says "580 members"). Then click "< BACK". Then the pinned message will appear. Not sure if this is a feature or a bug..

Most Tg users are on mobile where the pinned message is always visible. Or you can tap it away to conserve space.

In Telegram we're trying to funnel people to become RChain Members, and it seems to be working. Most of the new Members have onboarded via Telegram. :)

The Tg operators try to minimize support. New users come in and inevitably ask the same questions: "Cool project, is there a whitepaper somewhere?", "Where's the roadmap?", "I can't see my RHOC in MyEtherWallet".... to which we reply, "See the pinned message".

The welcome message from the Butler bot is a dynamic thing. When there's an alarm, like the EtherDelta hack or the current scam form for a fictitious sale/airdrop, then it must warn new users. In quiet times we just link to the pinned message. This keeps them in Telegram, as opposed to sending them out of the group (that they just joined) to an external link. We hope that most new users read the pinned message, remember its content, and proceed to interact with the group to get acquainted.

**Comment by patrick727** [comment]
I have update the reference with all major links. 

I now have edit access so please ping me with any updates you'd like to see to that

**Comment by kitblake** [comment]
@patrick727 Is a rename of the Facebook id possible? Changing it to rchain_coop for consistency would be ideal.

**Comment by ResonanceXX** [comment]
I totally agree with consistent nomenclature. Also the pinned message appears repeatedly on Telegram. 
Happy New Year to  the team.  
 
  On Tue, 2 Jan 2018 at 18:19, kitblake<notifications@github.com> wrote:   @patrick727 Is a rename of the Facebook id possible? Changing it to rchain_coop for consistency would be ideal.

**Comment by patrick727** [comment]
@kitblake @ResonanceXX i totally agree. so facebook doesnt allow  the underscore in the username and @rchaincoop (no underscore) is taken. 

We should most definitely strive towards consistent language. If it helps though we have the check mark on facebook that lets people know we are official ;)

**Comment by ResonanceXX** [comment]
Yes. The check mark is authentic. Correct. 

Sent from Yahoo Mail on Android 
 
  On Tue, 2 Jan 2018 at 19:54, patrick727<notifications@github.com> wrote:   
@kitblake @ResonanceXX i totally agree. so facebook doesnt allow the underscore in the username and @rchaincoop (no underscore) is taken.

We should most definitely strive towards consistent language. If it helps though we have the check mark on facebook that lets people know we are official ;)

**Comment by Keaycee** [comment]
@patrick727 i think the check mark is more important rather than the consistent nomenclature. The check mark will proof our authenticity and also differentiate between official page and the ordinary or fake page. 
This could help to combat scam on crowdsale and airdrop for RChain.

**Comment by kitblake** [comment]
As part of the "Consolidating channel (social) media links" effort we want to start linking to:
https://github.com/rchain/reference
or:
https://github.com/rchain/reference/...

/reference is a memorable URL that can be easily passed on or typed. When a user asks about info, answers, links, or whatever, the first place to send the user is /reference. Of course, if you know they need something deeper, like the FAQ, then you send them directly to the FAQ.

For links to communication channels I've created "RChain Cooperative Communication Channels":
https://github.com/rchain/reference/blob/master/communication_channels.md
If a user asks about channel links, you can send them directly here.

Unless anybody has any critique (no need to cheer me on :) I think this issue can be closed, but I'll leave that up to @n10n.

**Comment by dckc** [comment]
I tidied up the links: https://github.com/rchain/reference/pull/33
