### ISSUE TITLE
M> The future of Blockchain, Identity and Governance - Tampa Bay

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#216]
I put this issue here as a reminder for myself and @jimscarver , but anyones invited to contribute. 

Blockspaces.io is the tampa bay blockchain innovation center and we are now going to be running local meetups in st pete as well. 

the first one will Tuesday January 23rd. so @jimscarver I believe that fits into your collegues schedule. 

We want to create an agenda for the night. 

Because its the first in St. Pete we will need to start off with a small primer, we are thinking a Q&A panel
and then we can dive into some Blockchain 3.0, and Governance conversations. 

What do you think?

**Comment by BelovedAquila** [comment]
Questions and Answers panel?, of course it's an interesting agenda. it's likewise a lift to marketing Rchain . but please @patrick727, would there be a kind of video coverage on that?maybe on YouTube, to carry along those not present at the St Pete meet ups, perhaps reason being that they are not residing around the locals. 
 Secondly  @patrick727 if there would be,would there be a need of creating a summary on the meet ups essential or vital points made in the course of each meetings?, if yes, I think I can collaborate in doing the summaries. 
 Thirdly after the meet ups and answering of the questions as related to Rchain during the meetings, what about i updating the  https://github.com/rchain/reference/blob/master/faq.md     with Q&A's that are vital but not there?

**Comment by Keaycee** [comment]
Is this part of the governance conference meeting?

**Comment by patrick727** [comment]
@Keaycee no, if you read the top descriptions, its essentially a placeholder for myself and @jimscarver to coordinate over

**Comment by patrick727** [comment]
@jimscarver this is great thank you. 

I look forward to the meetup link so I can get people in attendance. 

Cheers

**Comment by jimscarver** [comment]
https://www.meetup.com/Ethereum-Tampa/events/247023719/
Details
A panel including leaders from RChain.coop, Holochain.org and DigLife.com will introduce what you need to know about the scalable green technologies becoming part of Blockchain 3.0 and answer your questions.

The potential impact of decentralization enabled on your identity and reputation, monetary freedom, and the future of work, education and governance will be introduced and breakout sessions organized in the last half.

Refreshments will be served.

Remote participants can join at https://zoom.us/j/6853551826

**Comment by dckc** [comment]
Given that the event was Jan 23, I suppose this is as done as it's going to get.
