### ISSUE TITLE
M > Need help to consolidate media coverage and article written 

### ISSUE THREAD

**Issue by n10n** [rchain/bounties#220]
https://github.com/rchain/reference/blob/master/mediacoverage.md

**Comment by kaka56** [comment]
The Merkle(September 4 2017 by JP Bontinx )https://themerkle.com/what-is-rchain/

**Comment by n10n** [comment]
Added.

**Comment by ResonanceXX** [comment]
@n10n Shingai Thornton wrote what could be a good piece here. You should check it out. 
https://blog.coinfund.io/an-introduction-to-rchain-d5fe303e9fe1

Cheers.

**Comment by Keaycee** [comment]
Here is also an article written by **Aleksandr Bulkin** on Rchain. It was written (August 4, 2017) 
https://blog.coinfund.io/rchain-series-introduction-985a05804ab

**Comment by kitblake** [comment]
One of our members, @Viva La Crypto:, created this video which takes the viewer on a tour of RChain info: https://youtu.be/MCCXzvO0Hhk Technical or marketing feedback welcome.

**Comment by BelovedAquila** [comment]
Actually likewise stumbled upon this while, doing some research and study, I hope it helps in more enlightenment on the Rchain, here please : https://mobile-process-calculi-for-programming-the-new-blockchain.readthedocs.io/en/latest/

**Comment by Mervyn853** [comment]
https://medium.com/@reinman/adventures-in-the-rho-calculus-672b72ef16c4?source=linkShare-81617e5a81cb-1515859215 Superb article on the benefits of Rho

**Comment by Mervyn853** [comment]
https://youtu.be/OLQ4LVmCIh4 Ashton from the crypto coin show also recently did a coverage on RChain

**Comment by Keaycee** [comment]
I find this article (project) very important to RChain. 
http://www.meti.go.jp/english/press/2016/pdf/0531_01f.pdf

**Comment by dckc** [comment]
I tidied up the links: https://github.com/rchain/reference/pull/33

**Comment by Ojimadu** [comment]
A Look at Seattle-based RChain's Plans to Build a Scalable & Safe Blockchain.
https://cryptoslate.com/look-seattle-based-rchains-plans-build-scalable-safe-blockchain/

**Comment by Ojimadu** [comment]
https://medium.com/@Ojimadu/ethereum-researcher-vlad-zamfir-joins-rchain-co-op-board-of-directors-6d70a035d0d8

**Comment by dckc** [comment]
Any particular reason folks aren't submitting pull requests?

Would a wiki page be easier?

Or a google doc, for that matter?

**Comment by Ojimadu** [comment]
Not everyone knows how to do that. Most are new to github. But would do that on my next link.

**Comment by TrenchFloat** [comment]
I started adding articles suggested above into the file.
https://github.com/rchain/reference/pull/36

**Comment by dckc** [comment]
If there is more to do, somebody can refine the issue summary / description or open a new one.

**Comment by dckc** [comment]
The README should definitely link to the list of articles. We could keep the most important two or three articles in both places.

**Comment by dckc** [comment]
I just ran across 
https://www.geekwire.com/2018/cryptocurrency-may-ups-downs-blockchains-stock-rise/
 in discord. @n10n does that sort of thing belong in the list?

cc @TrenchFloat

**Comment by n10n** [comment]
@dckc We should cover this one but once we have enough of them then I would want to split into focused articles vs coverage. Any other suggestion?

**Comment by dckc** [comment]
@TrenchFloat , Gary Coulter dropped this pointer in discord; RChain, Pyrofex and Mike Stay are mentioed in the article.

https://johncarlosbaez.wordpress.com/2018/01/22/statebox-a-universal-language-of-distributed-systems/
