### ISSUE TITLE
O> RGov log

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#229]
I ran across [RGov log](https://docs.google.com/document/d/1PwLD4eQV-w42iY2oKuBHV-PItQ40dv_Qq_6L1IDLK0k/edit#heading=h.kfy2ytg8gfzx) while reviewing [projects](https://github.com/rchain/Members/projects). I think rewarding whoever keeps such notes is reasonable.

Anybody know who wrote it? @lapin7 @patrick727 @kitblake @jimscarver ?

**Comment by dckc** [comment]
In fact, I wonder about a wiki page with short summaries and pointers to records for all the committees.

**Comment by patrick727** [comment]
that was a joint effort that @jimscarver initiated. myself and others(who I don't know of exactly) have contributed to it

**Comment by Keaycee** [comment]
Well, the [RGov log](https://docs.google.com/document/d/1PwLD4eQV-w42iY2oKuBHV-PItQ40dv_Qq_6L1IDLK0k/edit#heading=h.kfy2ytg8gfzx) is been updated time after time by @jimscarver . I would like to know if the Governance Conference has been decided?

**Comment by dckc** [comment]
@Keaycee see #189 for details on the Governance Forum.

**Comment by dckc** [comment]
I started organizing a [Coop Committees](https://github.com/rchain/Members/wiki/Coop-Committees) wiki page.

Like any other wiki page, all are welcome to edit it, but...

Let's **keep it brief**; it should mostly be pointers to other things.

I would like help finding records of where / when committee chairs were decided.

**Comment by dckc** [comment]
Thanks, @patrick727 .

@jimscarver I'm now trying to figure out how, if at all, **RGov** log relates to the RChain Nomination and Governance Committee. I don't see the committee chair, Evan, involved in the meetings. Help?

**Comment by dckc** [comment]
@9rb it's not clear to me why you assigned yourself to this issue. If you want to be assigned, please clarify what you intend to do.

**Comment by jimscarver** [comment]
We we given a mandate to self organize. Even directed us to determine the committee membership and said he would be taking a back seat. We help weekly meeting open to all memvers and have notes in the [RGov log](https://docs.google.com/document/d/1PwLD4eQV-w42iY2oKuBHV-PItQ40dv_Qq_6L1IDLK0k/edit) and other documents linked there.

**Comment by dckc** [comment]
I just (re)discovered:
> Member Committees are a volunteer position. -- https://github.com/rchain/Members/issues/118#issuecomment-338691846

and "Nominating and Governance Committee" is actually a bit of a misnomer. Its mandate is:
> Identification and selection of directors, officers, and other important roles in the Cooperative, subject to Board approval. Oversee selection of Executive Committee general membership.

Nothing about broader governance issues in there.

So while **RGov log** still looks like interesting work, it's not something we can reward as work of that committee.
