### ISSUE TITLE
M> Translate CONTRIBUTE in FR

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#231]
Translate [CONTRIBUTE](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md) into French.
For each language create a different issue.
Name the file CONTRIBUTE_FR.md

**Comment by ResonanceXX** [comment]
Members/projects/bots/groupbutler/pinnedmessage_fr.md
@kitblake this is through with.

**Comment by kitblake** [comment]
Excellent, merci @ResonanceXX

**Comment by lapin7** [comment]
Voilà un video sur YouTube traduit en Francais, par Gael . Click sur CC et les sous titres aparessent.
https://www.youtube.com/watch?v=VhgY1Hu31C4
Génial !!

**Comment by truffard** [comment]
Hi,this is Gael @truffard  I translated the video and I'm available for any videos you wish to be translated into french!

**Comment by lapin7** [comment]
Maybe it's even better to create video's in French about RChain. :-)

**Comment by truffard** [comment]
oui c est vrai,mais je dois maitriser le concept pour cela .au fait tu penses quoi de TRON la crypto chinoise?


________________________________
De : HJ Hilbolling <notifications@github.com>
Envoyé : mardi 16 janvier 2018 19:27
À : rchain/Members
Cc : truffard; Mention
Objet : Re: [rchain/Members] M> Translate CONTRIBUTE in FR (#231)


Maybe it's even better to create video's in French about RChain. :-)

**Comment by lapin7** [comment]
TRON c'est la merde.

**Comment by truffard** [comment]
nouvelle vidéo sous titrée en français
 https://www.youtube.com/watch?v=iP6Ws6G598k
elles sont sur la chaine youtube Rchain Coop France

**Comment by Keaycee** [comment]
@truffard  Ce fil n'est pas sur TRON, c'est sur la façon de traduire le doc de contribution en langue française. il y a un endroit pour discuter de votre type de problème. ce sont des fils de coopération RChain où l'on discute de la contribution pour avancer dans RChain. Je vous remercie.

**Comment by lapin7** [comment]
@patrick727 please change [the trailer video](https://www.youtube.com/watch?v=iP6Ws6G598k) on the main web site https://rchain.coop
Because it has subtitles in French.
If you press CC then you could change also to other languages.
Ask @truffard how he did that. Any language could be done this way. :-)

**Comment by truffard** [comment]
Nouvelle vidéo sous titrée
 https://www.youtube.com/watch?v=N0x1BmwNdbM&feature=youtu.be

**Comment by Ojimadu** [comment]
J'ai traduit la vidéo Vision de RChain de l'anglais vers le français. Voici le lien vers la vidéo téléchargée sur ma chaîne YouTube
https://www.youtube.com/watch?v=JyI9XvObRCc

Je travaille actuellement pour faire traduire Contributing.MD en français et en allemand.

**Comment by rjl493456442** [comment]
@lapin7 I'd like to translate this to chinese version :)

**Comment by lapin7** [comment]
@rjl493456442 
That's fine with me. See for yourself if others are working on it or they did it. Please coordinate yourselves on an issue

**Comment by Ojimadu** [comment]
Je viens de créer la copie traduite de [CONTRIBUTING.md](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md) de l'anglais vers le français. Voici le lien:
[CONTRIBUTING_FR.md](https://github.com/rchain/Members/blob/master/CONTRIBUTING_FR.md)

**Comment by ICA3DaR5** [comment]
@lapin7 Is this issue still relative?

**Comment by ICA3DaR5** [comment]
Closing this since it seems complete!
