### ISSUE TITLE
M> Create Marketing Assets/Templates

### ISSUE THREAD

**Issue by 8lcarte** [rchain/bounties#232]
It would be great if the community had standard templates for documents for any type of presentation, proposal, submission they might need to do. Specifically I would like to propose we create:

1. Word template for long-form proposals & papers
2. Word template for 1-pagers
3. PPT template

I have a great graphic designer I can use to complete this task if we deem it appropriate. It may also be done I just don't know where to find it. #

**Comment by lapin7** [comment]
@8lcarte Good idea. Plz send your email to ops@rchain.coop.
And it's a good idea to read https://github.com/rchain/Members/blob/master/CONTRIBUTING.md

**Comment by AyAyRon-P** [comment]
I've created three (3) PowerPoint Templates: https://github.com/rchain/Members/tree/master/style_guide_assets/presentations

Was there still a need for the WordDoc Templates as well?

**Comment by 8lcarte** [comment]
I think a word doc would be helpful for longer form proposals but not required for the governance forum.

**Comment by lapin7** [comment]
Please make it a google doc instead of word. It's better for collaboration.

--
Cheers,
HJ

**Comment by pmoorman** [comment]
closing this since the Branding WG / Girvin engagement will take care of this scope
