### ISSUE TITLE
M>  Full Marketing Audit, incl. Recommendations 

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#234]
Hey all, first issue here!

I'm Pieter, and @traviagio asked me to get involved with RChain. He asked if I could do a high-level marketing audit for RChain, to help RChain get the marketing strategy more in-line.

I've been lurking around the channels for the last ~2 weeks, and it seems like RChain is 1) doing great, but 2) marketing is very one-off and driven by all kind of separate initiatives. 
I hope we can — besides keeping that energy up  — also work on a cohesive strategy, so everyone can execute better, faster, and more efficiently.

**About the audit format:** 
I'll compile high-level findings into a slidedeck + video critique, so everyone can contribute and comment on it. Also, it'll be full of specific recommendations that we can work on.

–Pieter

**P.S.** if you think anything could be improved about this issue, please let me know! (Looking at you, @traviagio , @patrick727 , @Mervyn853 )

**P.P.S.** I'll try get the audit ready tomorrow or the day after. I did most of the analysis already, but need to write it down properly, so everyone can understand.

**Comment by dckc** [comment]
Welcome. This looks like a great idea.

I'm interested to know a bit more about your experience. Your github profile doesn't say much about you.

You could try this [introductions survey](https://docs.google.com/forms/d/e/1FAIpQLSdP42ZJ-UQ8HU1QkO_lywWbfAqxTJWYG2TWRgbQon6h5BeuKw/viewform) if you like.

**Comment by lapin7** [comment]
I prefer to have this link 
https://groups.google.com/forum/#!forum/rchain/join
instead of email to ops@rchain.coop

**Comment by lapin7** [comment]
Please give a link to the result spreadsheet.

**Comment by dckc** [comment]
@lapin7 ok, I can tweak the survey (or you can, I think).

But please use #222 for further comments on the survey. (It has a link to the results, too.) Let's keep our discussions focused.

**Comment by Mervyn853** [comment]
Interested to have a look at the marketing audit too. I believe one issue we have to work on is the communication of official statements or releases from the Coop whether its about governance, development updates etc. 

We need to find a way of communicating the same messaging across the multiple channels we have through Discord, Telegram, Reddit, Bitcointalk Forum, Medium, Twitter, Facebook and Linkedin especially the public facing ones.

**Comment by pmoorman** [comment]
_// To address the first few comments: I've heard you, and I'll try give a bit of an introduction using those forms and other processes. For the sake of focus (like @dckc said), let's keep this treat only about the topic of the marketing audit, rather than my personal credentials._

++++++++++++

Hey all, 

great to get so many responses already. 
Seems like it's an issue that more people care about.

It seems to me that really there are 4 BIG strategic marketing themes that need to be addresses. 
Here's how I see that:

### Theme 1  ::  Communicating core value props

**Problem:** RChain is technically complicated, and does a bad job communicating _why all that technology matters._ 

We could work on how we translate abstract concepts such as "concurrency" and "correct by construction" (all technical terms), and show how that translates into a different kind of platform/product and then show how that — in turn — leads to desirable outcomes such as _"content at the scale of Facebook, and payments at the scale of VISA"_

An example would be:
1. Rholang is a completely different programming language, unique to RChain
2. Due to how the Rholang works, code can be formally validated (= "correct by construction")
3. Because of this, RChain can be more secure (example: the DAO attack could have been avoided)
4. Because it's more secure... we can trust it to run mission-critical applications.

Similar 'pathways' can connect other abstract choices with tangible benefits and USPs. Obviously writing this in a compelling way is hard work, and requires quite a deep understanding on what's actually going on in the product. 


### Theme 2  ::  Branding & consistency

**Problem:** We are not consistent in our communications. This makes us look unprofessional, and it also makes us execute slower than needed.

I think this is something that many are already aware of, in different kind of environments. The comments by @Mervyn853 and @Ojimadu are driving at a similar point.

Similarly, we should have a unified brand guidelines that everyone can pull from (see issue #147), as well as a consolidated place to find previous external sources where we talk about RChain (see issue #220 for instance).

Obviously I have many more ideas here... but this is a theme we should work on (and to some extend, we already are).

BONUS points: website design. We shall I even begin. It's a mess, and we should do better. 


### Theme 3  ::  Content strategy & SEO

**Problem:** There's not enough content about RChain.

Almost all the publications we're featured in are 'news articles' that only scratch the basics. Our blog is semi-active, but really should have a much more ambitious editorial calendar. 

We could push topics such as the technical areas as discussed under theme 1, but also give more info about the team, more info about our governance model, more info about the technical roadmap, and generally just more info about pretty much everything.


### Theme 4  ::  Social channels

**Problem:** We're not really represented on many social channels. We let too many opportunities for discussion & dialogue slip.

As an example: I found it really odd that RChain — which brings such massive innovation with the Rholang language — is nowhere to be found on Hacker News.... What better place to ask developers what they think about such a fundamentally different approach to distributed programming, than in their virtual living room?

We could do much better, if we'd be more active in more social channels. Already somewhat in the works, but a lot could be improved on.


++++++++++

*Conclusion (for now):* 

1. I will compile my thoughts into a document that we can share everyone who takes an interest in marketing for RChain.

2. I hope it can serve as a starting point towards a more unified / consolidated marketing effort for RChain (where many focused efforts can magnify each other, rather than the "one-off approach" that we have now, and where people can tackle the BIG problems also (such as theme 1, in my opinion)).  

3. Obviously I'd love to hear from everyone anytime during the process. 

Best for now,

–Pieter

**Comment by dckc** [comment]
@pmoorman writes:
> As an example: I found it really odd that RChain — which brings such massive innovation with the Rholang language — is nowhere to be found on Hacker News....

It would have been premature to bring Rholang to Hacker News up to this point; it barely exists yet. Somebody would have a field day ridiculing us with stuff like the [Programming Language Checklist](http://colinm.org/language_checklist.html).

And [SDK 0.1 release](https://rchain.atlassian.net/wiki/spaces/RHOL/pages/103546887/Rholang+SDK+0.1) is in the works; @MParlikar has said in one or two [weekly debriefs](https://github.com/rchain/Members/wiki/Weekly-Debrief-Index) that it's planned for early February. At that point, we should definitely hit Hacker News.

**Comment by kitblake** [comment]
@pmoorman Thanks for your observations! Critique is welcome. 

Imho a helicopter overview of the RChain marketing and communication is sorely needed. You're right about the one-off aspects. While the internal discussion is aligned pretty well, a global approach is required.

**Comment by ResonanceXX** [comment]
RChain needs a general direction that sells it to the world. 
If there could be a brainstorming to decide that. Fine. 
All the activities online, in the social media groups should always aim to sell. What's the attraction to this. How enjoyable is this. 
Crystallize all efforts and make this happen. 
Marketing is a good place to start. Let's  sell some stuff!

**Comment by traviagio** [comment]
Great points @pmoorman. I personally think #1 and #2 are definitely challenging as those require consistency and agreement by all COOP members which sometimes seems hard to accomplish with the current setup. The current setup is not perfect but does bring results. Excited to see what you will come up with.

**Comment by Viraculous** [comment]
I personally think that for effective decision to be taken on the issue of full marketing audit and integrating the formalities of the different RChain communication and marketing channels, there is need for internal evaluation of member thoughts of the RChain coops particular on  their view about the structural oddity and discrepancies of the different marketing channels. Am suggesting a kind of interactive questionnaire where views are aired based on critical questions on the operations of the community and its marketing channels.

**Comment by lapin7** [comment]
The mission of RChain has to be very clear and shared by each of us!!!

But the message of each person can be different. A lot of people have different views on how to reach the mission. The group, that coordinates, organizes and promotes itself in the most efficient and effective way, will have the most influence.

So, I'm looking forward to the full marketing audit. The target group of RChain's marketing if for me the whole set of stakeholders in and around RChain.

**Comment by Keaycee** [comment]
Marketing is one key we need to gain potential part of the crypto market system. @lapin7 we've got up coming events  February, aside from the RChain promotional ether card and RChain embedded T-shirts. There is more to be done to project RChain to the world. I suggest outlets, handbills, souvenir, flyers and more to printed and distributed. We need more channels and also online marketing.

**Comment by pmoorman** [comment]
Hey, Pieter here...

It's time for an update! 

I have the basic version of the marketing audit done. I've spend way more time than I initially had in mind digging through RChain as a project (all the way to the technical docs, consulting with 2 developer friends, etc. etc.), and then back to marketing again.

I also realised that I should keep the spirit of a cooperative alive, and find a way to seek out much more feedback & suggestions from everyone else (rather than just presenting solely _my_ opinion). 

So let me explain how this is set up...

###Here's how the audit is structured

1. I wrote a 3-page PDF document giving you a high-level overview. This compliments what you've already see me ramble about in the comments above, and a few more ideas.  => [(RChain) Marketing Audit  __  Outline.pdf](https://github.com/rchain/Members/files/1659832/RChain.Marketing.Audit.__.Outline.pdf)

2. I recorded [a short video (3:32min)](https://www.useloom.com/share/c6a47fd108b74495a22bf3c7c7f1a98c) so it's easy for everyone to understand what's going on. 

3. There's a Google Docs ([click here](https://docs.google.com/document/d/1CGJoCGbReJry06Wfb-EA_sk_92ga16ejuK7BY5MLye8/edit?usp=sharing)) where I hope everyone can contribute with specific suggestions on how these main areas can be approached & solved. See video with further instructions.

I will make sure I moderate the document, to make sure things stay structured and sane. After 1-2 weeks of collaboration, we can close the document and spin out all action into corresponding Github issues. That way Github stays the singular place that actions get coordinated. 
Hope that's cool.

### Here's how you can help, right now

You can help me improve this audit, by just pitching in with your thoughts. There are a few ways you could do this, but I think any of the below would help:

- Read the document, and let me know what you think of the _high-level analysis_. Is anything significantly wrong? Please let me know, so we can consider it. Pushback is welcome.

- Add actions that would specifically help address one of the 5 topics in the Google Doc.

- Interact here on the Github issue, or reach me on Discord (@pmoorman) with any sort of feedback or thoughts.

- Invite others in the community to have a look, too.

++++

My hope is that this document can act as a starting point to get everyone to think not only on the _tactical_ level, but also on the _strategic_ level about our marketing & positioning. 

Cheers for now,

–Pieter

**P.S.** Not sure if I should tag people here, but I guess that @lapin7 @dckc @traviagio @Ojimadu @Mervyn853 @kitblake @Viraculous @Keaycee should definitely take a look...

**Comment by Ojimadu** [comment]
I like the way the document is structured. Much work went into the formulation of the  document. For 
 Branding & consistency I think work is already going on on that with @patrick727 and @ValeBF working on that I'd like them to pitch in so we can know the state of things. 
I would like to see this issue divided into respective issues when we are set based on the points raised so it can be easier and faster to tackle and track progress of the respective issue.
Overall, I pretty much agree to the points and strategy outlined in the document.

**Comment by pmoorman** [comment]
Thanks @Ojimadu. Agree with what you're saying about spinning tasks out into their respective Github issues.

I spoke with a couple different people about the document (mostly privately through Discord), and I think it was generally well-received, and that the next thing to do is to spin out the actions like you also suggest. 

Hearing the thoughs of @patrick727 and @ValeBF would be valuable, indeed.

**Comment by ValeBF** [comment]
Hello! @pmoorman I am Valeria I am the designer in charge of the rebranding of the project, as it was mentioned I have been working on the definition of the brand image, from the new coop logo to the brand style guide and also working on the web remake. As you have seen all this work is not implemented yet we are defining the elements to be ready for the possible rebrand launch.

I read all the document and I think there is a lot of my responsibility to help the brand to have a cohesive image in order to be recognizable and identifiable in the market and the communications. I am attentive to work on anything we could need

**Comment by dckc** [comment]
@pmoorman I just discovered https://www.rchain.io/purpose-and-principles/ ; have you seen that?

**Comment by pmoorman** [comment]
@dckc Hm, interesting. Based on that, I've doodled a little on a document to help new members better understand what we're all about. Could be "purpose & principles" but from the RChain **Coop** perspective, rather than Holdings.

Love to hear your thoughts => 

https://docs.google.com/document/d/1rfpwP3PBVx429ulwxl0ZgalVknV4KIf5sWTdGBXltJQ/edit?usp=sharing

_P.S. this should maybe be escalated into a separate issue? It's off-topic from the scope of this issue...   (something with world hunger and Bob's sandwich. I'm learning... :+1: )_

**Comment by dckc** [comment]
Nifty writing. One of my favorite parts is:

>  - **Be a self-starter**  ::  because there is no boss, nobody is going to tell you what to do. Being a RAM is much more like being an _entrepreneur_ than it is like being a _employee_.

I can think of a few times people wrote "Here I am. Please tell me what to do." where it would have been useful to respond by citing that.

I think what you wrote is even more narrow than coop purpose and principles; it looks more like RAM purpose and principles. I'd like to see it merged/meshed with CONTRIBUTING and/or README.

CONTRIBUTING has gotten a little off course; the first screen-full is a pile of pointers to social media channels. That seems like a bit of a distraction from "How to contribute."

And yes, we've wandered off the scope of a marketing audit and we should make a new issue. I almost put this response in the onboarding issue (#253) but I'm not sure that's quite on target either.

**Comment by patrick727** [comment]
My 2 Cents

So the high level stuff is and has been in consideration for a long time. 
Your unique perspective on it is very much appreciated

The more research you do the more you'll see on branding, content, with the primary focus on developer advocacy. Including branding docs, website mockups, content sheets/calendars, etc. 

My attempt was to do it as much with the community as possible, still while driving it with the leaders. 

People come in at different times and with limited attention and it seems mixed. 

I take responsibility for anything that feels "chaotic"

To a respectable leaders point though "We shouldn't except people to get completely up to speed in 1 week, 2 weeks, are organization is growing to fast and complex for that to be the case." 

The jam. (hopefully) a focal point of the governance conference. 
It's about decision making, editorial process, and budgeting. 

If/once there's consensus on that, i'll bet that the marketing becomes world-class. 
In fact, world-class developer marketers have been engaged for some time now helping to refine plans. 
 
@pmoorman when those plans are drafted, we can share with you and see if your points have been address adequately. 

The real trick is figuring out how to involve the community in a way that keeps the co-op focused on stewarding the platform. 

I've been thinking that much like there is holdings and ventures and pyrofex to execute on certain strategies, there could be a research-group/incubator for community building, market research and content creation.

**Comment by AyAyRon-P** [comment]
I had an opportunity to reach out to Pieter after a discussion with Kit about this project, Pieter and I will be working together to generate a draft proposal to establish a solid document with clean content and purposeful graphics that will help drive the project.

**Comment by lapin7** [comment]
@dckc please set the budget as you think it's good.

**Comment by dckc** [comment]
I suggest $400 for Feb.

In fact, I already suggested it in [Budget Votes for 234][1] in the new system.
