### ISSUE TITLE
M> Translate CONTRIBUTING.md to Chinese version

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#239]

**Comment by rjl493456442** [comment]
I have submitted the #240 of this issue. Need some time to review :)

**Comment by Whisker17** [comment]
Whats ur plan？Maybe I can cooperate with u

**Comment by rjl493456442** [comment]
@Whisker17 Of course. I have submitted the PR and you can help me to review the modification.

**Comment by kitblake** [comment]
The PR is merged.  @rjl493456442 Gary, you should be able to just checkin now, no need to do a PR. @Whisker17 please review and improve the content.

**Comment by lapin7** [comment]
Where is the link to the Chinese version of contributing.md

**Comment by rjl493456442** [comment]
@lapin7 The Chinese version translation has been merged by @kitblake. And here is the  [link](https://github.com/rchain/Members/blob/master/CONTRIBUTING_CN.md).
Besides, i have not allocated the budget yet. Could you please do me a favor to create a budget?

**Comment by Whisker17** [comment]
@rjl493456442  the budget has been allocated,u can check it now
