### ISSUE TITLE
M> Sponsorship of Blockchain Africa Conference 2018

### ISSUE THREAD

**Issue by Ojimadu** [rchain/bounties#241]
Hello everyone, I would like the co-op to be a part of the sponsors of [Blockchain Africa Conference 2018](http://blockchainafrica.co) in South Africa. I think this would be a good way to create awareness of RChain in Africa and globally, on-board new co-op members and network with key people in the blockchain space.
The main plan here would be to on-board key people in the blockchain space in Africa and globally on to RChain.

The conference is scheduled for 8 & 9 March 2018 in Johannesburg, South Africa. There are three categories of sponsorship but I wanted the coop to sponsor the cheapest category (Gold) which cost $5,500 as I believe that offers the best value for money but unfortunately after an inquiry with the organizers I found out the slots for gold category was already filled and there are only two slot for Platinum which cost $11,500 per slot and Diamond sponsorship (which one slot has already been filled by Microsoft) has one slot left and it cost $20,000. 
Also, there are other sponsorship opportunities that the coop might consider like sponsoring a 30 minute session where we can give talk on what RChain is, the vision and advantages of RChain and also host a small Q&A session. This would put us in the minds of the participants of the conference and if we interest people enough, they will sign up as members of the coop.

After the conference, members/representative of the coop can look out for local tech meet-ups within Johannesburg (if time and budget permits) to onboard new members.

I have opened correspondence with the sponsors of the event to get more information on the various sponsorship packages.

Would like to get everyone's thought on this.
Measure of Completion:  Attending the Conference.
Suggested budget:
 ```
$11,500 for Platinum sponsorship
```
``` 
Travel Expenses for two persons (Platinum sponsorship offers two conference tickets to sponsors) or more.
 $1,500 per head * 2 (This is a rough estimate and can vary depending on the location of the participants.)
```
```
Total estimated budget: $14,500
```                              
Sponsorship Prospectus: http://blockchainafrica.co/pdfs/Bitcoin%20Events-Blockchain%20Africa%20Conference%202018%20Sponsorship%20Prospectus.pdf

**Comment by Viraculous** [comment]
The Conference covers Blockchain issues of performance, scalability and infrastructure. Its a fertile platform to for the co-op to propose its vision of speed and scalability to Blockchain and its road map to this end. I think its going to go a long way in marketing the coop and bringing it to the limelight. Better still, officials of the coop and some of the coops members from Africa due to proximity should be present at the conference to for education and training on blockchain technology as in line with the 5th ICA  principle.

**Comment by Viraculous** [comment]
#225

**Comment by BelovedAquila** [comment]
@ojimadu the idea of  "Blockchain Africa conference“ is a welcomed development, but I was made to  wonder  why South Africa? Would the conference be of a greater and wide impart there? What about Egypt,  Nigeria? I think holding a conference in one of the countries mentioned  would cut cost down sponsorship cost and yield greatly too,considering their GDP too as regards to The African Economies. What's the peculiarity to holding the conference at South Africa? Just wondering...

**Comment by pmoorman** [comment]
Frankly, I think this is a bad idea unless we can get a clear sense of what audience we'd reach (both quantity and quality), and how that $15k worth will be produce an ROI

Basically, I second @Mervyn853 's comment above. 

@Ojimadu what specific ROI do you expect this to yield?

**Comment by traviagio** [comment]
I agree with @Mervyn853 and @pmoorman here. I have attended a few blockchain conferences myself and it's full of people selling their own ICO. This is often not the right target audience.

**Comment by Ojimadu** [comment]
The issue is a suggestion by myself for coop to be a part of the sponsor of the conference. This issue was part of the agenda that was supposed to be discussed on last week's membership meeting but there wasn't enough time to discuss this and some other points on the agenda. 

The conference is coming up in early March and I proposed a budget for it this January in the case that the sponsorship is agreed upon by the members and there is a need for funds to be used especially to pay the sponsorship fee as if the budget is not set now, no funds would be released till March when the conference is supposed to be held. 
The slot I had in mind for the coop to sponsor was for the cheapest available sponsorship available (it doesn't come with a speaking opportunity) as a I think that has the most value for money based on what is obtainable on the sponsorship prospectus but on inquiry with the organizers of the conference, the gold slot (Cheapest option) was fully booked and none was available. The only slot left as at when they replied my mail was 1 Diamond sponsorship and 2 platinum sponsorship. I queried that there wasn't a difference between the Platinum sponsorship and Gold sponsorships and also inquired about the advertised "sponsored session" then it was made clear that the sponsored session is for platinum and Diamond sponsors - this wasn't stated in the prospectus -. 
So if the coop acquires any of the sponsorship slots left we'll have to arrange for a speaker. The plan is for the main speaker to be a marketing person (@llerner comes to my mind) and a second person would be a developer sent by Pyrofex to cover the technical aspects. Also RChain branded souvenirs like T-shirts, pins and tags would be printed and distributed at the conference at the stand designated for the coop. 
The coop representative can use the Networking sessions to network with key players in the blockchain industries from across the world that would be attending the conference. 
Finally, if time permits or based on prior arrangements, the team would meet with a developer community, Crypto community or start-up hub around Johannesburg to explore options for on boarding. 

None of these is set in stone (most things actually aren't), not even the budget. As I mentioned on the pub sheet that the budget is a "placeholder" just in case there is a need for funds in February. The reward was initially set to HJ as he disburses the funds and I believe should be in custody of the funds but he said that the rewards should be set to myself. I did that but I don't feel comfortable about it.

**Comment by makys** [comment]
Thanks @Ojimadu for the additional clarification.

**Comment by makys** [comment]
@Mervyn853 good point you raised. In addition, I would say that there should be a standard custom presentation slide for active members to use for introducing Rchain to prospectus coop members esp in their local meetup. For conference engagement we should have marketers do this so we ensure there is a consistent message being put out there.
Another idea is to set up a training for active members interested in speaking engagements and we can have a 'Certified Rchain Speaker' after formally completing the training. This way we can grow the number of speakers in a structured way and have them reach more audience.

**Comment by pmoorman** [comment]
@Ojimadu I appreciate the clarification. 

I'm still not really convinced about the ROI we'd get from spending on events like this (see @traviagio comment above, basically), but if other people think it's a good idea, then let's go with it.

My thought would be that it's probably money "mostly wasted", but that's only one guy's unfounded opinion.

**Comment by kitblake** [comment]
Personally I haven't investigated this conference so I can't comment on its potential ROI. But sponsoring is something the Coop needs to decide about, based on an appraisal. Imho the three Member budget only applies to the work done to investigate and coordinate RChain's potential sponsorship.

**Comment by Ojimadu** [comment]
@kitblake I agree with what you said "Imho the three Member budget only applies to the work done to investigate and coordinate RChain's potential sponsorship." and the budget has been adjusted to reflect that. @viraculous and @belovedAquila please review your budgets to reflect the above. @all other participants, [please fill out the budget sheet](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=468279933) based on your perception as the sheet works based on averages. Don't forget to set reward percentages for yourselves and everyone else.


Proposals like this (not just this one) requires some form of deliberation, approval and planning but the question here is, who approves what? I've been reluctant to contact more board members on this as I don't see these things as things that the board needs to spend time deliberating on as I believe they have more work on their hand than to sit approving/disapproving proposals from members however there is still a need to sanction proposals like this. Probably a committee like the compensation committee approves it then it gets signed off by the board if necessary.  
What do we think?

**Comment by lapin7** [comment]
@Ojimadu The board should handle only strategic issues. Operational issues should be handled by "The Organization". At the moment we have a CEO, CFO and COO. So I would say arrange these things with the COO, @kennyrowe .
If the COO thinks it's worth the attention of the CEO or CFO then he can escalate to that level.

For the rest it's more or less up to us, what we think is good for RChain. And us is then most active members, like @patrick727 @llerner @jimscarver @dckc @kitblake @Ojimadu @Mervyn853 @sportshark @pmoorman @dcpnlau (and who did I forget)

**Comment by kennyrowe** [comment]
I take a look but I'd say it's unlikely we could sponsor this conference at the moment.

**Comment by pmoorman** [comment]
Great to see some more discussion about the cooperative governance in the last few days (and thanks @lapin7 for leading that!). 

In this case I'd say the comment of Kenny above here should carry some real weight.
Once the budget is adjusted downwards (it's still averaged out of $7000 right now) we can set a reward for the explorations that mostly @Ojimadu did.

**Comment by 9rb** [comment]
Looks like one or more members from the Marketing Committee should be looking at proposals like this one and perhaps also develop 'conference proposal guidelines' for one to review and assess if some suggestion meets guidelines (may be the folks commenting here already are on that committee?, I'm not sure).  Kenney can of course substitute for them.

**Comment by 9rb** [comment]
Is it possible to come up with a proposal to engage the African Developer community on a sustained basis, without forking out a bag of money to a third party for a one-shot exposure?  Can we identify and engage channels of communication where such developers congregate?

**Comment by jimscarver** [comment]
There is a concern that "sponsorship" does not mean exposure of rchain at the conference.  Will there be an rchain presentation?

**Comment by pmoorman** [comment]
@ojimadu I think we can close this issue, yes? I'll close i (in an effort to clean up old issues), but feel free to reopen if anything needs to be discussed still.
