### ISSUE TITLE
M>Finish translating RChain Architecture documents into Chinese

### ISSUE THREAD

**Issue by AbnerZheng** [rchain/bounties#242]
I have create a PR(https://github.com/rchain/architecture-docs/pull/12) to architecture-docs(https://github.com/rchain/architecture-docs) .

In this PR, there are contributors:

@AbnerZheng add the sphinx international support for this doc, in this way, multi-language could be easily supported, and easy for team collaborating.
@linsheng9731 translated 'motivation', 'approach' and 'execution_model/consensus_protocol' page into Chinese.
@RowlandZhou translated 'introduction' page into Chinese.
@yyh1102 translated 'index' and page into Chinese.
@rjl493456442 translated ' architecture-overview' and 'storage and query' page into Chinese.
@yuhuanmocmoc translated 'application' and 'contract-design' page into Chinese.
@AbnerZheng translated "namespace" page into Chinese.

And in this PR, @RowlandZhou and @yuhuanmocmoc are not familiar with Sphinx, so I help them commit the translating contents. And others are committing by creating PR to my repo.
Finally，@AbnerZheng review the style problem and assemble these commit, then create this PR.

You can preview these translated doc in http://architecture-docs.readthedocs.io/zh_CN/latest/

**Comment by Ojimadu** [comment]
Awesome, @AbnerZheng I like the way you have partitioned the documents to different collaborators so everyone gets up to speed quickly. We;ll need to translate to more languages as well.

**Comment by Ojimadu** [comment]
@AbnerZheng good because am working a few languages translated and this would be of help.

**Comment by Whisker17** [comment]
@AbnerZheng I have translate some RChain Arc(include Contract Design),may I join u?

**Comment by BelovedAquila** [comment]
@AbnerZheng very impressive collaboration, division of Labour (cooperative).

**Comment by AbnerZheng** [comment]
@Whisker17 Yeah. After this PR has been merged. Anyone who wanna to translate the doc could find a easy way.

**Comment by AbnerZheng** [comment]
@Whisker17 You can do the translate as README.md said.

**Comment by sportshark** [comment]
hi Every one ,After a period of work and repeated proofreading, the Chinese version of FAQ which I translated is formally incorporated into the official document library you can see it here. https://github.com/rchain/reference/blob/master/faq_cn.md

**Comment by AllCombo** [comment]
I am also preparing to translate some parts of this document. May i join u?

**Comment by lapin7** [comment]
@AllCombo please be very explicit in what you want to do. That helps @sportshark and others enormously in the coordination. ;-)

**Comment by llerner** [comment]
Please do keep me on copy with the Chinese translations with a specific set of docs. Also we’re working on getting someone else to produce content. Once identified they’ll be put into this process.

I met with some investors from China and they’ve pledged assistance as we deliver materials and will help with local PR. There is tremendous interest but we need more native language materials. 

Thank you


========================
Lawrence I Lerner
o/m: 630.248.0663
lawrencelerner@gmail.com

Blog: lawrenceilerner.com
 <http://www.lawrenceilerner.com/>twitter: RevInnovator <https://twitter.com/#!/RevInnovator> 



On Jan 26, 2018, at 05:46 , HJ Hilbolling <notifications@github.com> wrote:

@AllCombo <https://github.com/allcombo> please be very explicit in what you want to do. That helps @sportshark <https://github.com/sportshark> and others enormously in the coordination. ;-)

**Comment by AbnerZheng** [comment]
@llerner Thans a lot.  You can send me email or contact me in discord(same name with 'AbnerZheng') if you have others work.

**Comment by lapin7** [comment]
@AbnerZheng @llerner please create Github issues for any work that has to be done. And specify it in a SMART way.
The progress of each issue can then be followed by all collaborators through the comment sections

**Comment by AbnerZheng** [comment]
@lapin7 I will assign the percentage of contribution for the contributors.

**Comment by RowlandZhou** [comment]
good job

**Comment by yuhuanmocmoc** [comment]
Thanks a lot. You did a really good job

**Comment by linsheng9731** [comment]
Thanks @AbnerZheng ! You did a really good job!

**Comment by yyh1102** [comment]
Very nice job!

**Comment by dckc** [comment]
@AbnerZheng I can add  architecture-docs.readthedocs.io as a translation of http://arch-doc.rchain.coop/en/latest/ but it looks like you need to make me (dckc) an administrator of architecture-docs.readthedocs.io first.

**Comment by AbnerZheng** [comment]
We have finished reviewing the translation and I have publish the latest content in  http://arch-doc.rchain.coop/en/latest/. 
@dckc I have add you as the maintainer of the site, thanks for your help. 
I closed this issue, since all work has been done in my opinion.

**Comment by dckc** [comment]
Oh... I see that architecture-docs-ZH-cn is the actual translation. That's the one I need access to. architecture-docs is your fork of the English document.

**Comment by AbnerZheng** [comment]
Oh, sorry. I have fixed it.  Try again.

**Comment by dckc** [comment]
tada! http://arch-doc.rchain.coop/zh_CN/latest/

One odd thing: there's a link from http://arch-doc.rchain.coop/zh_CN/latest/ to http://arch-doc.rchain.coop/en/latest/ but not the other way around. I don't understand. oh well.
