### ISSUE TITLE
M> Finish Translating RChain "mobile-process-calculi-for-blockchain" into Chinese

### ISSUE THREAD

**Issue by AbnerZheng** [rchain/bounties#246]
I have create a new PR(), which has finished translating all of the pages of "mobile-process-calculi-for-blockchain".
In the PR, there are contributors:
@AbnerZheng add the sphinx international support for this doc, in this way, multi-language could be easily supported, and easy for team collaborating.
@rjl493456442 translate 'introduction' and 'conclusion' page into Chinese.
@yuhuanmocmoc translate 'actors tuples and pi' page into Chinese.
@yyh1102 translate 'enter-the-blockchain' page into Chinese.
Finally，@AbnerZheng assemble these commit, then create this PR.
You can preview these translated doc in http://mytestdocforrchain.readthedocs.io/zh_CN/latest/

**Comment by yyh1102** [comment]
Nice!

**Comment by linsheng9731** [comment]
Awesome! This PR allows more Chinese developers to understand rchain!

**Comment by yuhuanmocmoc** [comment]
You did a really good job! It is favorable for RChain to be promoted and applied in China.

**Comment by rjl493456442** [comment]
Fantastic.

**Comment by RowlandZhou** [comment]
good job

**Comment by AbnerZheng** [comment]
@lapin7 @BelovedAquila 
I don't think just comment or adding label has any contribution to the work. So I set negative percentage  to adjust your vote.

**Comment by dckc** [comment]
Very nice. I did a small check: I let Google translate a page back to English and checked that it made sense.

Please add "translated by ..." either on the title page or in an appendix.

**Comment by dckc** [comment]
@AbnerZheng did you assign @yuhuanmocmoc a negative reward on purpose? Or did something get corrupted? I'm surprised by what I see.

**Comment by AbnerZheng** [comment]
Aha，@yuhuanmocmoc is my girl friend. She is not familiar with these process. So I helped her to get the reward.

**Comment by yuhuanmocmoc** [comment]
@dckc My reply is too late, so I can't get the reward. I ask Abner to help me to get the reward.

**Comment by rjl493456442** [comment]
@dckc Hey dan, thanks for the rechecking! The correctness and translation quality is the most important thing.

**Comment by yuhuanmocmoc** [comment]
@dckc I‘m not familiar with the process, so I ask AbnerZheng to help me to get the reward. I'am so sorry for that.

**Comment by BelovedAquila** [comment]
@AbnerZheng this is a cooperative platform. And a cooperative is of the believe that  no matter how little ones participation might seemly be, it still counts to certain percentage of total contribution done. Every participate counts, a participation being little doesn't void it from being a participation.
Secondly, about getting a reward for a friend, I just wonder?everyone is seen  to be responsible for any changes made on the budget sheet as it partains to its  username, If we go ahead in helping friends and enemies in doing that, when the need arise for one to be responsible as it partains to a misplacement or other contingencies, who then would the board hold responsible?. I don't think an Avenue for such is excusable in cooperative. So what has been done was meant to be solely an individual responsibility or let's say the  individual's responsibility. 
Yet, Do justice to the budget, and to this issue as it may seem right to you.its welcomed 
Cheers!

**Comment by rjl493456442** [comment]
@BelovedAquila I think add a label and require 10% work percentage is totally bull shit. Me and my teammate put a lot of energy to translate the document. Every one in our team can only get a little percentage. But you just do nothing can require 10%?

Please go away! Show me your work :)

**Comment by BelovedAquila** [comment]
@rjl493456442 please there isn't any cause to be vulgar friend, this isn't a battle field please. I respect your say and actions as it partains to setting a budget on issues, much as I endeavor too to create something cooperatively fair. To emphasize "Yet, Do justice to the budget, and to this issue as it may seem right to you. its welcomed“ please.

**Comment by rjl493456442** [comment]
> Yet, Do justice to the budget
Sure, we always do that things. I make the apologize for my team's wrong operation since they don't know the rule very well. But we are always improving and try to correct the wrong behavior.

> much as I endeavor too to create something cooperatively fair
Do you think it is fair to plunder other people's work results. Don't You will feel nauseated about requiring 10 percentage and do nothing totally?

**Comment by yuhuanmocmoc** [comment]
@BelovedAquila I think you are a little mean. Anyway, it is unfair to steal other peoples' work results.

**Comment by BelovedAquila** [comment]
@rjl493456442 and @yuhuanmocmoc it was a suggestive vote, which each participant has the right to accept or refuse, we just took the whole process personally without understanding it. Am sorry for being unfair as it seems (before two or more witnesses a case is justified), I rest my case on this. But yet, to have erred in some ways, please accept my apologies friends. 
Disagreements are things which must be, but yet we are to carry ourselves along, to see that our aims are  achieved (to collaborate cooperatively to get job done ), and not let misunderstandings  hinder our cooperation please .
Cheers friends, please do well as it fits.

**Comment by yuhuanmocmoc** [comment]
@BelovedAquila All right, that is it! We all want RChain to be good, and we need work together to move it forward.

**Comment by lapin7** [comment]
@dckc Your rewards are above 100%. Please change to make it =< 100%
https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=950224463&range=AI1982:AJ1991

**Comment by dckc** [comment]
I was pretty careful about that. I wonder if someone else changed them.

Will fix, in any case...

**Comment by ICA3DaR5** [comment]
@AbnerZheng Should this issue be closed by now?

**Comment by AbnerZheng** [comment]
@ICA3DaR5 The work for translation and review is done. But I think this should be deployed on the official site of RChain readthedocs. So I leave this open.

**Comment by ICA3DaR5** [comment]
@AbnerZheng mobile-process-calculi-for-blockchain is obsolete, so that may never happen.

**Comment by dckc** [comment]
Obsolete? What takes its place? What did I miss?

**Comment by ICA3DaR5** [comment]
@dckc It's more than a year old. I don't know what takes it's place. Should this be translated?

**Comment by dckc** [comment]
Doesn't we recently rediscover rules on what to tanalate in ISSUE_TEMPLATE.md?

Please don't ask me without making it clear that you tried hard to find the info yourself. I'm no authority on what to translate. I can only help find records of discussion.

**Comment by ICA3DaR5** [comment]
I am closing this one since it has been done and paid.
