### ISSUE TITLE
O> 20180124 RChain Active Members

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#249]
# goal: Organize the meeting [RAM 20180124](https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64/edit#heading=h.u4pck0fugly0)

- [x] set agenda before 2018-01-24
- [ ] scan issues in Github and Discord to talk about
- [x] publish meeting announcement in media channels
- [x] participate in the meeting
- [x] make minutes and report
- [x] prepare report for Greg's Debrief 2018-01-31

# budget: $2000 
# time: 2 weeks

**Comment by lapin7** [comment]
@dcpnlau You did a wonderful job during the meeting and the report in the Debrief of @leithaus

**Comment by Tonyprisca13** [comment]
"This is a nice way of organizing members to participate in the formulation of the agenda for the member's meeting and to increase the level of member participation in meeting"

**Comment by Ojimadu** [comment]
I think all the goals for this issue has been achieved @lapin7

**Comment by dckc** [comment]
I don't see the debrief of @leithaus in the [outline of debrief 61](https://github.com/rchain/Members/wiki/Weekly-Debrief-Index#january-24th---community-debrief-61). Was the report given somewhere else? I would appreciate a pointer.

**Comment by dckc** [comment]
I don't expect we want to discuss this in a future meeting, so I'm removing **RAM-weekly-agenda.**

And this is as done as it's going to get, so I'm closing it.
