### ISSUE TITLE
O> 20180131 RChain Active Members

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#250]
# goal: Organize the meeting [RAM 20180131](https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64/edit#heading=h.rtk357c1r43i)

- [ ] set agenda before 2018-01-31
- [ ] scan issues in Github and Discord to talk about
- [ ] publish meeting announcement in media channels
- [ ] participate in the meeting
- [ ] make minutes and report
- [ ] prepare report for Greg's Debrief 2018-02-07

# budget: $2000 
# time: 2 weeks

**Comment by lapin7** [comment]
I will get a paid account for Zoom. The account will be open for sharing by all members. Like that we have a fixed zoom id.

**Comment by Tonyprisca13** [comment]
creating a committee to handle d meetings planning and preparation help in making the meeting more organize.

**Comment by makys** [comment]
@Tonyprisca13 I am interested in being part of the committee. I was part of the last debrief live and buy the idea of organizing the meeting.

**Comment by Viraculous** [comment]
Please, whats it going to be like using the paid account of zoom?@lapin7

**Comment by David405** [comment]
@laplin,  on rchain coop introductions (Draft with sections), is it necessary to fill out ALL the sections?

**Comment by lapin7** [comment]
All sections are optional.
And it's a draft for the moment

--
Cheers,
HJ

**Comment by lapin7** [comment]
[Zoom Account](https://zoom.us) To be used by all members
I have to find out how to arrange it best

**Comment by optictopic** [comment]
I received messages from Zoom that were meant for someone else.
"Hi RAM,
We have received your request to change your email address from
lapin7@gmail.com to rchain@googlegroups.com."
Not sure who to pass this on to so I picked you.   I hope nothing has gone
awry.
Rich

**Comment by Viraculous** [comment]
I also recieved the same message @lapin7 , that seem to be the paid account for all member.

**Comment by lapin7** [comment]
@optictopic thx for mentioning. I'm fiddling around with this account. So expect some erroneous messages.

**Comment by lapin7** [comment]
There's one day left to edit the agenda of our Wednesday meeting [RAM 20180131](https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64/edit#heading=h.rtk357c1r43i)

**Comment by Ojimadu** [comment]
@dcpnlau Isn't the Agenda for the meeting too much? Considering that the meeting is usually only an hour long.

**Comment by Tonyprisca13** [comment]
I think the agenda is much for a meeting considering the time frame for the meeting.

**Comment by Tonyprisca13** [comment]
I suggest we attend to two-third of the agenda so that it can be handled comprehensively.

**Comment by dcpnlau** [comment]
I’ll update it before the meeting tomorrow. 

Sent on the go

**Comment by dckc** [comment]
Saying "the agenda is too full" is less useful than saying which items should stay and which should go. The order naturally prioritizes too: things at the end are at risk of being postponed.

**Comment by Ojimadu** [comment]
I did not want to be like "remove this, add that, remove this" as I felt @dcpnlau wrote it and would be in a better position to review as I just skimmed through the document.
Yes, the order priorities too, I think missed that. :)
