### ISSUE TITLE
M> RChain & Me video productions

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#252]
# goal: show what the folks understand of RChain in their own words

- [x] example of @truffard [rchaincoop en francais](https://www.youtube.com/watch?v=Ev5GeLDBZJk&feature=youtu.be)
- [x] setup campaign before 2018-02-02
- [x] make a page with collected video's
- [x] decide about reward for a submitted video
- [x] create a rating mechanism and price winner
- [ ] what else ....

# budget: $500 
# time: 1 week

**Comment by Viraculous** [comment]
Thanks @lapin7 for this issue.  I think this would go a long way in clearing the ambiguities and misconception in their thoughts concerning the coop. Moreover, its an internal regulatory measure tool for organizational survey through its members. see #243

**Comment by David405** [comment]
This is cool, is it open to all contributors on the coop?

**Comment by lapin7** [comment]
Of course it's open to all contributors. Please go ahead and paste the link of your video here under.

**Comment by truffard** [comment]
https://www.youtube.com/watch?v=viubRlqm634

**Comment by truffard** [comment]
https://www.youtube.com/channel/UCi_FAJP556JHoXIvQCoeftw

**Comment by lapin7** [comment]
@truffard 
Dans [Pub Bounties](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=60903965&range=A163:W163) tu peux définir le budget pour ce issue. Tu peux mettre un montant avec lequel tu te sens comfortable.

Pendant Février tu peut mettre un [bounty](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=294454559&range=M2216:AA2220) pour toi et les autres collaborateur.

**Il faut minimum 3 entries, si non le moyen ne sera pas accepté!!!!!**

**Comment by lover33** [comment]
this is wonderful! I will post my reviews and updates for Rchain!

https://youtu.be/XFvHqYg5K5Y

I can also be a point person on social media for milestone releases and updates whenever Rchain announces!

**Comment by lapin7** [comment]
@lover33 
Pease create a new issue for your video and take this issue description as an example plus fill out the questions in the new issue template.

**Comment by lapin7** [comment]
Also interesting https://www.youtube.com/watch?v=_QvmCQm2OD0

**Comment by lapin7** [comment]
And a second video of @lover33 
https://www.youtube.com/watch?v=vxJLwvFizw0

**Comment by truffard** [comment]
pour traduire? oui il n y a pas de souci si c'est le cas....


________________________________
De : HJ Hilbolling <notifications@github.com>
Envoyé : samedi 21 avril 2018 09:53
À : rchain/bounties
Cc : truffard; Mention
Objet : Re: [rchain/bounties] M> RChain & Me video productions (#252)


Also interesting https://www.youtube.com/watch?v=_QvmCQm2OD0

[https://www.bing.com/th?id=OVP.ac2oLbseUmTRrIfu01itIwJYE3&pid=Api]<https://www.youtube.com/watch?v=_QvmCQm2OD0>

WTF is RChain? Rchain Review [My attempt to breakdown the Rchain Blockchain Project]<https://www.youtube.com/watch?v=_QvmCQm2OD0>
www.youtube.com
So What is Rchain? Well that is what we cover in tonight video. Bear with me on this Rchain Review, this was one the the tougher videos I have shot and one of the ...

**Comment by lover33** [comment]
wow cool! I will check this out!

**Comment by CryptoBr0s** [comment]
Hi @lapin7 

Just submitting my video on R-chain- I am fairly unfamiliar with the process here, but the video is complete and on YT.

If there is anything else I need to do I will be more than happy to follow through. Also I am a very big fan of this project so I would LOVE to collaborate/help out in any way possible! 

Rodney

https://youtu.be/_QvmCQm2OD0

**Comment by lapin7** [comment]
Hi @CryptoBr0s 

_**Just tell what your video is worth.**_

Cheers,
HJ, @lapin7, ops

## To contribute to RChain:
 
- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
- [ ] Join rchain@googlegroups.com to get access to documents of RChain https://groups.google.com/forum/#!forum/rchain/join
- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [ ] Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
- [ ] Bounty App https://rewards.rchain.coop/
- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- [ ] or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit
- [ ] with concern to the "become a collaborator process": get in touch with for example: @lover33 @Cryptovideos @truffard

**Comment by Cryptovideos** [comment]
Fantastic work @cryptobros

**Comment by kitblake** [comment]
Yes, excellent work @CryptoBr0s!

**Comment by lover33** [comment]
Great stuff! @CryptoBr0s Yes, this checklist is a great start!

Join the CoOP discord, Join the membership and so on

**Comment by CryptoBr0s** [comment]
Thanks Everyone! Very Much appreciated.

I hope everyone is having a great Sunday. Just to follow up here

I worked my way through the check list, signed up for the membership, got
set up on the discord, submitted the deceleration etc.

I did struggle to access the Gsheet for the invoice, and it would not let
me copy the format out. So I put the information in the comments section of
the deceleration instead. ( I hope that was ok)

If I need to correct anything I certainly will do that, was just a little
confused on how to navigate everything, but there should be enough
information to get us started!

Thank you again for the kind words! I am a big fan & happy to contribute.

-Rodney

**Comment by lover33** [comment]
Welcome to the CoOp!

**Comment by lapin7** [comment]
There's a lot of video impressions of RChain. [This one](https://www.youtube.com/watch?v=ci-a0L4gDEc) I liked a lot. A presentation in Russian.
Maybe it could get English subtitles. ;-)

**Comment by lover33** [comment]
wow! cool!

Great stuff! A mashup would be fun & exciting for people to watch!

**Comment by lapin7** [comment]
@Cryptovideos It would be awesome if you could make a mashup of many Rchain Reviews. 
You could start with a listing in these comments of the video's that you want to integrate in your mashup. And you can leave a message under each video in order to interest the creator in becoming a RAM. And placing a link to this #252 issue.
