### ISSUE TITLE
O> Community efforts related to Identity & Privacy

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#254]
Continuation of [#41](https://github.com/rchain/Members/issues/41) Identity

# goal: self sovereign cooperative identity and reputation
- [x] @jimscarver update [byoid meeting log](https://docs.google.com/document/d/1OVUGmxv4q1ywcxDG-V926lrXpkQNDs7n2eO2R5OJdOk/edit#heading=h.e98xkt7b85fy), 
- [x] @jimscarver announce video's in comments [video](https://youtu.be/GQnLPE_Y_JM)
- [ ] enablement of privacy respecting community applications (#830) enabling agency across discord, the bounty system, google, ethereum, and the social ledger to be integrated with rchain
- [ ] @kitblake report about progress with [Decentralized Identity Foundation](https://decentralized-identity.github.io/) project/consortium
- [ ] @kitblake report about progress with [Consent](http://www.consent.global/) team, interesting work being done.
- [ ] @kitblake improve [user story](https://github.com/rchain/Members/blob/master/projects/identity/userstory.md)
- [x] @jimscarver provide link to "noob log"
- [ ] @9rb report about "social ledger"
- [ ] announce issue in Discord
- [ ] what else....

# budget: $2000 
# time: ongoing

**Comment by dckc** [comment]
Is this only about identity? I would be more comfortable with "identity and privacy". I hope there is as much effort put into *avoiding* surveillance as supporting surveillance.

The RChain architecture includes capability security; with capabilities, it doesn't matter who you are, only that you have authorization.

**Comment by makys** [comment]
I am new to this space. I have got privacy background and I am interested in working on this. How is the group task being co-ordinated.

**Comment by jimscarver** [comment]
Welcome @makys (Amaka)!
Here is the video from yesterday's meeting https://youtu.be/xG81K3JbsEM
@edeykholt joined at 42:20. He suggested an identity channel be created in discord. @drbloom ?

**Comment by 9rb** [comment]
Adding Privacy to the title is a good add.  Yes,we're looking into privacy also, not only because we philosophically support it, it is also a legal requirement in Eu.  RChain has to meet that requirement since some of our membership is in Eu.

**Comment by David405** [comment]
@jimscarver I believe BYOID log and Noob log is up to date

**Comment by dckc** [comment]
Is there a concise report other than the rough meeting notes? A budget of $2K or $3K would make more sense for a concise report.

Why claim the whole budget if not all the checkboxes are checked?

**Comment by ResonanceXX** [comment]
I honestly would preach that privacy be treated with great severity

Identity and security without any laxity. These are some of the most important aspects of proper decentralization.

**Comment by azazime** [comment]
Identity and security

**Comment by dckc** [comment]
this was rewarded in 201803

Please make a new, more focused issue for any follow-on work.
