### ISSUE TITLE
Example Rholang contracts: RHOL-44 Voting etc.

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#255]
- **RHOL-44 Example contract: Voting**: 3 story points
 - **RHOL-45 Example contract: Safe Remote Purchase**

 On Jan 8 in #176, @MParlikar  said "in flight" but I can't find the work-in-progress. @AbnerZheng, pointer please?

ref: [Jira Bounties](https://rchain.atlassian.net/browse/ROS-271?jql=labels%20%3D%20bounty)

**Comment by AbnerZheng** [comment]
Yeah, there is some problem, I need wait for rholang 0.2 specification released.  Sorry for that.

**Comment by AbnerZheng** [comment]
I need rholang supporting for array etc which is released in 0.2 specification.

**Comment by dckc** [comment]
Thank you for the update.

**Comment by flowpoint** [comment]
i started on RHOL-45, [https://github.com/flowpoint/rholang_playaround/blob/master/safe_r_p.rho](url)

**Comment by flowpoint** [comment]
busy week, have the safe remote purchase working for the rholang erc20 [here](https://github.com/flowpoint/rholang_playaround/blob/master/safe_r_p_erc20), it needs review.
i hope good enough. cleanup + documentation will come.
