### ISSUE TITLE
M> Serbo Croat version

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#262]
**Goal:** a [. srt file](https://drive.google.com/open?id=1OQkfiCpQvyPxINZ_RXZzFwpIpzWfbYPEYSCXcce-lOA) 
stored in  [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii) 
with a translated transcript in Serbo Croat of the file  
[[TRANSCRIPT][.srt][English] "Rchain Exclusive chat Lawrence Lerner & Nash Foster"](https://docs.google.com/document/d/1oTZVkYEhhnZtyU4DmNiiT3N39R0IVpHI92vP8kaltFs/edit)
**Progress indicator**: see the evolvement of the doc
**TIme**: 3 weeks
**Budget**: $5000
**Collaborator:** @noordaa

**Comment by BelovedAquila** [comment]
Portugese should be added to the list of languages transcripts for the Lerner & Nash Foster interview. I have assigned myself into working on it.

**Comment by lapin7** [comment]
@BelovedAquila Please create a new issue and use #262 as an example

**Comment by ICA3DaR5** [comment]
@lapin7 @noordaa Should I close this issue?

**Comment by noordaa** [comment]
Hang on I will ask Svetlana once again and will let you know next week

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by noordaa** [comment]
Svetlana will pick it up

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by ICA3DaR5** [comment]
@noordaa @lapin7 What is the status of this issue? It's open since Jan 30.
