### ISSUE TITLE
M> Mandarin Version of Lerner & Foster interview transcript

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#264]
**Goal:** a [. srt file](https://docs.google.com/document/d/1nxkJw2Pu1YdeAdWCJz11pVrRKibqnk3NoIZRSO7KxvQ/edit) 
stored in  [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii) 
with a translated transcript in Mandarin of the file 
[[TRANSCRIPT][.srt][English] "Rchain Exclusive chat Lawrence Lerner & Nash Foster"](https://docs.google.com/document/d/1oTZVkYEhhnZtyU4DmNiiT3N39R0IVpHI92vP8kaltFs/edit)
**Progress indicator**: see the evolvement of the doc
**TIme**: 3 weeks
**Budget**: $2000
**Collaborator:** @zsluedem @Whisker17

**Comment by Whisker17** [comment]
I and @zsluedem will finish this issue today,we have cooperate for this.

**Comment by zsluedem** [comment]
It's almost done~!

**Comment by lapin7** [comment]
@zsluedem please add a reviewer that confirms correct translation.
Great work :-)

**Comment by lapin7** [comment]
@zluedem please check "word count" of the doc and find out if figures like 123 or other things that don't need translation are counted as words

**Comment by zsluedem** [comment]
@lapin7 you mean English "word count" or Mandarin "word count"?

@Whisker17 and I translate the different part. So we are going to review each other's translation~
We still need a third reviewer.

**Comment by lapin7** [comment]
@zsluedem English word count please

**Comment by zsluedem** [comment]
@lapin7 I wrote a Python script to count the words. It is about *10954* words in the English transcript regardless the figures or other things.

(The first draft Mandarin transcript)[https://docs.google.com/document/d/1nxkJw2Pu1YdeAdWCJz11pVrRKibqnk3NoIZRSO7KxvQ/edit] is done! We are going to review each other's translation now~!

**Comment by zsluedem** [comment]
@lapin7 I don't know what is going on right now . I lost the permissions to edit the doc right now

**Comment by lapin7** [comment]
The Folder got moved somehow and permissions were gone.

--
Cheers,
HJ

**Comment by zsluedem** [comment]
@Whisker17  and I have reviewed each others' transcript already.
 It's done now.@lapin7 . feel free to upload the transcript now

**Comment by lapin7** [comment]
@Whisker17 I'm not able to upload the transcript to the official video of Blockchain Brad.
Maybe @Mervyn853 can arrange that for all the languages.
Nice job #289

**Comment by zsluedem** [comment]
This one has done already~! According to #318 #401, I am going to close this issue. Feel free to reopen it.
