### ISSUE TITLE
D> Ace editor enhancement for Rholang-web. 

### ISSUE THREAD

**Issue by AbnerZheng** [rchain/bounties#268]
As https://github.com/rchain/Members/issues/185 said,  I create a new issue to follow the progress of work. 
@tgrospic has finished the tmLanguage for grammer. 
And I will integrate the grammer to Ace editor and add  some other features to make it works.

**Comment by AbnerZheng** [comment]
I have just finished the formatter for rholang-idea, and now I can start working on this issue.

**Comment by zsluedem** [comment]
#514 the ace editor is finish ~! I am going to help abnerzheng with the enhancement

**Comment by AbnerZheng** [comment]
Great works.Now  I closed this issue.

**Comment by zsluedem** [comment]
make the first pr on the enhancement https://github.com/rchain/rchain/pull/420

**Comment by dckc** [comment]
This is good work!

I'm interested to know why there are no [budget / reward votes on this issue][1] from anybody else.

[1]: https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=268&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D268&-ui-root=main-content&-relationship=BudgetVotes

**Comment by zsluedem** [comment]
@dckc forgot to do that.....
