### ISSUE TITLE
M> Translate White Paper to Chinese #100

### ISSUE THREAD

**Issue by JieL314** [rchain/bounties#270]
Excuse me, @lapin7 .
We have completed the translation work for whitepaper Chinese version. Which format will be better when I upload to Github, PDF or docs or Markdown?
The tencent QQ is not the unique useful channel in China. The Wechat group, Wechat public account, weibo(similiar to Twitter) are also useful channels. By which are easy to spread rchain cultural and update the latest news to Chinese people. Some projects have already done, such as Wanchain. This is my second suggestion. Thank you.

**Comment by jiyuxuan1944** [comment]
Sounds great！

**Comment by Whisker17** [comment]
we have upload it into [this](http://www.rchain.site/wp-content/uploads/2018/01/Rchain%E7%99%BD%E7%9A%AE%E4%B9%A6%E8%AF%91%E7%A8%BF.pdf).
should we upload this pdf into the Google Disk or other? @lapin7

**Comment by AbnerZheng** [comment]
I’m a Chinese native speaker and has solid background of CS. You can invited me to review the whitepaper so that the content will be more consistent with other two translated document.

**Comment by linsheng9731** [comment]
Awesome! I am also a chinese developer and want to participate in review.

**Comment by rjl493456442** [comment]
Chinese Team is getting stronger

**Comment by Whisker17** [comment]
welcome to review it!That's our aim to upload it to the cyberspace.
we can learn from the Ethereum's whitepaper translation.work together to make it more precise.
u can download this pdf [there](http://www.rchain.site/wp-content/uploads/2018/01/Rchain%E7%99%BD%E7%9A%AE%E4%B9%A6%E8%AF%91%E7%A8%BF.pdf) @AbnerZheng @linsheng9731

**Comment by JieL314** [comment]
Welcome all of you. The Chinese version whitepaper need to be review by all of us, and get to be a formal one.

**Comment by ICA3DaR5** [comment]
What's the status of this?

**Comment by zsluedem** [comment]
I have seen the CHinese white paper in Chinese QQ group. And this one should be closed now.

**Comment by jiyuxuan1944** [comment]
http://www.rchain.site/wp-content/uploads/2018/01/Rchain%E7%99%BD%E7%9A%AE%E4%B9%A6%E8%AF%91%E7%A8%BF.pdf

**Comment by ICA3DaR5** [comment]
Okay so, closing this!
