### ISSUE TITLE
M> Translate White Paper into Chinese

### ISSUE THREAD

**Issue by JieL314** [rchain/bounties#271]
I am sorry about the issue submitted before.
The issue #100 contain many language versions, and I am not familiar with all users typed in spreadsheet. So it is too difficult to decide percentages distribution. I want to submit a new issue only for translate White Paper into Chinese. The work already finished. I will inform the partners type their name in the new issue spreadsheet. Hope the issue can pass through as soon as possible. 
Sorry for the trouble again. @lapin7

**Comment by Whisker17** [comment]
good job!

**Comment by jiyuxuan1944** [comment]
I participated in the translation.

**Comment by lapin7** [comment]
@Whisker17 
@zsluedem wrote a Python script to count the words of an English document to be translated. 
It's an indicator for setting the budget. And then another indicator is $0.20 per word.
Please check this with your document and put a budget proposal in the comment here under.

**Comment by JieL314** [comment]
@lapin7 
The word of the English document is about 6000. But the finished Chinese one is about 9792. We can't translate the word by simple stitching. We try to perfectly interpret the meaning of the original in native Chinese. So the budget I think is suitable and worthful.
Another question is we've typed it in sheetspread Budget201801 and need me to type it in again in Budget201802?

**Comment by lapin7** [comment]
OK for the count.
The calculation is based on English words: So 6000 x $0.20 = $1200
Budget201801 is $3000
Rewards201801 is:
3,000.00 Member
1,500.00 JieL314
750.00 Whisker17
750.00 jiyuxuan1944
0.00 Keaycee
​So Budget201802 for #271 should be $0 I think and no more rewards spend on
this issue.

Please tell me what you think​

--
Cheers,
HJ

**Comment by JieL314** [comment]
I'm sorry to make you angry.
I've clear the Budget201802 for issue#271.
The translation work is not rely on addition and splicing of words. We use idioms to make sentences easier to understand. And scripts do not translate well, and typesetting is no exception
English words are only as a reference, There are about 10k Chinese words.
Compare to issue#278, $400 for translation and other related work with about 1100 English words, I think the budget of Whitepaper translation is worth it.

**Comment by ICA3DaR5** [comment]
@JieL314 Hello there, what's the status of this issue?

Is there any reason for it to be still open after all this time?

**Comment by zsluedem** [comment]
I have seen the CHinese white paper in Chinese QQ group. And this one should be closed now.
