### ISSUE TITLE
M> French Version of Lerner & Nash Foster interview transcript 

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#272]
**Goal:** a [. srt file](https://docs.google.com/document/d/1en8ewGh88ItE-1UKMYA0wZwz5Elwch0ESfWwD_AiYoo/edit) 
stored in  [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii) 
with a translated transcript in French of the file 
[[TRANSCRIPT][.srt][English] "Rchain Exclusive chat Lawrence Lerner & Nash Foster"](https://docs.google.com/document/d/1oTZVkYEhhnZtyU4DmNiiT3N39R0IVpHI92vP8kaltFs/edit)
**Progress indicator**: see the evolvement of the doc
**TIme**: 1 week
**Budget**: $5000
**Collaborator:** @niwaa @truffard .....

**Comment by truffard** [comment]
@niwaa hi!please let me know how i can help with the translation in french

**Comment by niwaa** [comment]
Hey guys here is the collaborative file : https://docs.google.com/document/d/1en8ewGh88ItE-1UKMYA0wZwz5Elwch0ESfWwD_AiYoo/edit

I've got it done until chunk #400, will update the doc (I use Pages for spellcheck).

@truffard would you like to start maybe at the middle so we don't collide ? Like from #1000 till the end. Or let me know what blocks you are doing. I will be on #400-600 for today i think.

**Comment by truffard** [comment]
@niwaa sounds great but first i need to be granted access to the doc, thanks again

**Comment by niwaa** [comment]
@truffard it should be public but I just gave you access.

**Comment by truffard** [comment]
@niwaa Ill start translating tonight,thanks!

**Comment by lapin7** [comment]
@truffard
I see that you've worked on this doc. So it's fine I guess.

--
Cheers,
HJ

**Comment by truffard** [comment]
@lapin7 yes im translating from line 1000 till the end and its a lot of fun

**Comment by lapin7** [comment]
@truffard @niwaa 
Please take a look at the beginning of the doc. I made a relation with the payment system Pub.
Please propagate this to the other languages. It's a nice way of peer control and peer help.

**Comment by kaka56** [comment]
@lapin7 your third comment is about Spanish. please change that.

> with a translated transcript in Spanish of the file

**Comment by niwaa** [comment]
@truffard great you want to do 800-1000 too? So it will be 50%. I should be done with 500-800 today or tomorrow.

**Comment by truffard** [comment]
@niwaa  ill start from 802

**Comment by truffard** [comment]
@niwaa that's it we're even.. It's your turn to play.

**Comment by niwaa** [comment]
@truffard great thank you I should be done by the end of the weekend.

**Comment by truffard** [comment]
@niwaa are you ok?

**Comment by niwaa** [comment]
@truffard yes something came up but I will be done today for sure. I just have 202 lines left now. Then I will review your section and you can do the same for me!

**Comment by niwaa** [comment]
@truffard Completely done with my part too now.

**Comment by truffard** [comment]
@niwaa is french your mother tongue?

**Comment by niwaa** [comment]
@truffard Yes I am french. Why?

**Comment by truffard** [comment]
@niwaa oui car franchement et désolé pour dire ça, ta traduction , c'est la cata.... J'ai changé beaucoup de choses mais applique toi s'il te plait.

**Comment by truffard** [comment]
@niwaa can you review line 774 through to line 777? I think you missed something....

**Comment by niwaa** [comment]
@truffard Ok je prends note, je suis en train de relire le transcript et les changements faits.
Par contre je vois des corrections comme:

```
229
00:08:29,870 --> 00:08:32,150 
serveur virtuel pour accomplir cela alors
```

machine virtuelle >> serveur virtuel 

La traduction du terme "virtual machine" est bien "machine virtuelle" et non "serveur virtuel" en français...

https://fr.wikipedia.org/wiki/Machine_virtuelle

**Comment by niwaa** [comment]
@truffard Yes I am going over lines 774 to 802 now.

**Comment by truffard** [comment]
@niwaa ok cool merci

**Comment by niwaa** [comment]
@truffard J'ai revu ta partie et corrigé les fautes d'orthographe, ponctuations et de formatage qui étaient évidents.  Pour les autres de grammaire / syntaxe j'ai laissé des commentaires sur google docs. 

En parlant de traduction littérale, tu en as fait aussi:

#1280
je me sens un peu toujours un réluctant à
-> je suis toujours un peu réticent

#1301
ma passion pour tout cela transpire un peu!
-> transparait un peu (?)

#1538
pour décrire ce mode de computation 
-> modèle de calcul

Bref pas de soucis, collaborons pour finaliser ce document rapidement afin de promouvoir RChain.

**Comment by truffard** [comment]
@niwaa oui j'avais volontairement laissé tel quel ces mots, mais pour quand va t on finaliser ce document? Disons que Vendredi ça devrait etre bon.... enfin je pense, dis moi ce que tu en penses

**Comment by niwaa** [comment]
@truffard oui Vendredi max.

**Comment by niwaa** [comment]
@truffard J'ai relu 0-802 et ça me semble personnellement OK... Mais dis moi si ça ne va pas. 

As tu aussi eu le temps de revoir les commentaires que j'ai laissé sur ta partie?

**Comment by truffard** [comment]
@niwaa oui mais je reviens sur le texte un peu plus tard aujourd'hui pour finir tout ça,j'aurais plus de temps

**Comment by truffard** [comment]
@niwaa merci ça a l'air ok j'ai regardé encore merci @lapin7 seems good to me

**Comment by lapin7** [comment]
peux tu prendre contact avec @Mervyn853 pour ajouter le transcript Francais au video?

**Comment by truffard** [comment]
@Mervyn853 no problem

**Comment by truffard** [comment]
@niwaa c'est bon pour toi?

**Comment by niwaa** [comment]
@truffard @lapin7 Good with me. Here is the final .srt file, ready for upload: 
[French_subtitle_youtube_chat_Lawrence_Lerner_Nash_Foster.srt](https://drive.google.com/open?id=1um7HwGa06JexK5MrQ7V-gHVq_A0qEcCV)

**Comment by lapin7** [comment]
@niwaa plz make sure that @Mervyn853 get's the French .srt uploaded!!

**Comment by niwaa** [comment]
Sure.

**Comment by truffard** [comment]
@lapin7 @niwaa everything is all set?

**Comment by niwaa** [comment]
@truffard Yes I think so,  Mervyn853 said in the other thread that he is aggregating all the .srt for the upload. Can you vote on the work percentages on the [reward spreadsheet](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=294454559)?

**Comment by truffard** [comment]
salut @niwaa , aucune nouvelle de personne.. lol

**Comment by niwaa** [comment]
salut @truffard, Mervyn853 a dit dans l'autre fil qu'il avait déjà envoyé les .srt pour la vidéo, donc il n'y a plus qu'a attendre je pense!

**Comment by ICA3DaR5** [comment]
@lapin7 I am closing this since it seems to be completed.
