### ISSUE TITLE
M > Translate Rholangtut-mercury document into Chinese

### ISSUE THREAD

**Issue by HaizhenZhuo** [rchain/bounties#274]
I'am a front-line blockchain developer and working for a big financing institution in China now. I have a great interest in RChain and want to do something. Rholangtut-mercury（https://github.com/rchain/rchain/blob/dev/rholang/doc/rholangtut-mercury.md） is a core part of the Rchain architecture,so I want to translate this document into Chinese.I really wish more and more people can join us, so I will invite other developers who have experience in the development of blockchain to assist me.

**Time:** 1-2 weeks
**Collaboator:**  @yuhuanmocmoc (and others?)

**Comment by HaizhenZhuo** [comment]
I have translated most of the chapters and are verifying now.

**Comment by linsheng9731** [comment]
@HaizhenZhuo I am very interested in this , i can join you.

**Comment by RowlandZhou** [comment]
@HaizhenZhuo I want to join

**Comment by lapin7** [comment]
@HaizhenZhuo 
Please become member of this [group](https://groups.google.com/forum/#!forum/rchain/join) to get access to documents
Please accept [Github Repository Invite](https://github.com/rchain/Members/invitations)

**Comment by David405** [comment]
Hello guys, I would love to join this issue....how far have the translation gone?

**Comment by yyh1102** [comment]
Please let me join in !

**Comment by rjl493456442** [comment]
@David405 Welcome! Almost the translation has been done. But you can review the translation carefully to make sure the translation is make sense.
Once the translation been submitted, we will mention you to review :)

**Comment by AbnerZheng** [comment]
@HaizhenZhuo Thanks for your contributing. I have help commit the document you translate into the https://github.com/rchain/reference repo. You can view the translated document in https://github.com/AbnerZheng/reference/blob/master/docs/rholangtut-mercury_cn.md

**Comment by AbnerZheng** [comment]
And I will help to merge the PR into the repo.

**Comment by BelovedAquila** [comment]
@yyh1102 nice you want to contribute to issues,to join in, 
Please friend, 
- Join https://groups.google.com/forum/#!managemembers/rchain/join
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by David405** [comment]
@Haizhenzhou, I have seen and reviewed the issue (with the help of a Chinese friend of course since I am not a native speaker of the language.. Lol)

**Comment by AbnerZheng** [comment]
As @kelly said, I have reviewed the translation and and update the translation towards the updating of original document after the creating of the https://github.com/rchain/reference/pull/40 and then create a new PR(https://github.com/rchain/rchain/pull/324) to `rchain/rchain` repo.

**Comment by AbnerZheng** [comment]
@lapin7 I don't find table entry for this issue on `budget Feb`, is there anything wrong?

**Comment by lapin7** [comment]
Plz try  again
https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=60903965&range=A184:I184

--
Cheers,
HJ

**Comment by AbnerZheng** [comment]
@lapin7 Thank you. It works now.

**Comment by AbnerZheng** [comment]
Since the PR(https://github.com/rchain/rchain/pull/324) has been merge into the dev branch, every can view the translation in https://github.com/rchain/rchain/blob/dev/rholang/doc/rholangtut-mercury_CN.md, means this work has been done. 
@HaizhenZhuo Please apply for the budget.

**Comment by ICA3DaR5** [comment]
@HaizhenZhuo Since all of the languages have also translated the 0.1 version of this file, I guess you could translate that too.

Question: These documents are subject to change, especially the Mercury one, are you willing to keep them up to date?

**Comment by AbnerZheng** [comment]
@ICA3DaR5 Thank you. We have create a new issue for 0.1 version of that file.
And I will keep these rholang translation up to date. 
I close this issue, seems all of work has been done.

**Comment by RowlandZhou** [comment]
@AberZheng
 I create the new issue #473 for 0.1 version
