### ISSUE TITLE
M>Translate RChain Blockchain multithreading mechanism into Chinese

### ISSUE THREAD

**Issue by JieL314** [rchain/bounties#278]
I want to launch a translation project to explain the blockchain multithreading mechanism to Chiinese people, aim at attach more prople who are interested in RChain. The source url is link to https://thecryptosyndicate.com/rchain-multi-threading-blockchain/. 
The budget is $400(ten hours). I'already done it. And will published in a day.
@lapin7

**Comment by Whisker17** [comment]
cool

**Comment by jiyuxuan1944** [comment]
That‘s great

**Comment by hcl3** [comment]
very good

**Comment by Whisker17** [comment]
@lapin7 
I have joined this translation,but I can't add my name to the Budget table

**Comment by lapin7** [comment]
If you're a participant, then with the next refresh of issues and
participants, you will be on the list (tomorrow)
I've learned my lesson in January. Folks destroy the gsheet with manual
entries. So I've put some restrictions.

--
Cheers,
HJ

**Comment by rjl493456442** [comment]
I'd like to review the translation

**Comment by JieL314** [comment]
@rjl493456442 That is great. The translation were upload to official RChain Wechat public account. You can leave your email address. I will send the doc to you.

**Comment by rjl493456442** [comment]
@JieL314 Why not upload the translation to the repository in markdown format? I think it is more proper.

**Comment by JieL314** [comment]
@lapin7 Where is the issue in Budget201801 or Budget201802? I remembered that I set the budget and percentages, but now I can't find it.

**Comment by lapin7** [comment]
Please have a look again and reset it if necessary

--
Cheers,
HJ

**Comment by ICA3DaR5** [comment]
What's the status of this issue? I don't see any work done here and it has been probably payed since it's voted February.

**Comment by ICA3DaR5** [comment]
Closing this since no one has responded for weeks.
