### ISSUE TITLE
M> Translate 20180131 Rchain Weekly Community Debrief 62 into Portugese 

### ISSUE THREAD

**Issue by David405** [rchain/bounties#280]
Goal: a .srt file for Portugese for 20180131 Weekly Member Debriefing. 

Collaborator: @Ojimadu

Tasks:
- [ ] Get an English transcript of the video
Measure of Completion:  50%
- [ ] Translate the English transcript into Portugese
- [ ] Crosscheck grammar, spelling
- [ ] Review the Portugese transcript
- [ ] Upload the Portugese transcript

Time: 1 week

Suggested Budget: $1000

**Comment by Whisker17** [comment]
if u get an English transcript,I can translate it into Chinese

**Comment by David405** [comment]
@Whisker17 I am working on the English transcript

**Comment by Whisker17** [comment]
@David405 cool

**Comment by dckc** [comment]
Somebody elaborate a bit on how a .srt file is useful? How do audience members consume them?

**Comment by David405** [comment]
@dckc, a .srt file is a subtitle file. When you download a video file, you can also download a .srt file in your language of choice(if available) and save both in the same folder and same name. This enables you get the written translation of any video in your chosen language

**Comment by David405** [comment]
In the case of this issue, a Portuguese member can follow up with the meeting with ease. I hope this is helpful

**Comment by Ojimadu** [comment]
@David405 Can you help remove my name? As am yet to sign up for this.

**Comment by ICA3DaR5** [comment]
Abandoned as well.
