### ISSUE TITLE
O>Coop Information page: Newsletter link is broken, minor content fixes

### ISSUE THREAD

**Issue by kitblake** [rchain/bounties#281]
The page at: https://www.rchain.coop/coop-information-1/ has a newsletter subscribe button that doesn't respond. This seems to be the same problem as on the main page a few days back. 

@patrick727 Is this page linked from somewhere? It's slightly out of date as the Activist Meeting is now after the Weekly Debrief. Also the main title is funky: the word devel-opment is broken into two lines (on my screen) and it's hard to read. 

Measure of Completion:  the newsletter button and content items are fixed. 
Suggested Budget: $250

**Comment by David405** [comment]
@kitblake that's true, I tried signing up for newsletter but it isn't going through.

**Comment by kitblake** [comment]
@David405 When you signed up, was that on the main page or the Information page? I believe the main page is fixed, I just tested it and the button seemed to send, which is what is what not doing a few days ago.

**Comment by AyAyRon-P** [comment]
@kitblake did you fix this and can we close this out?

**Comment by kitblake** [comment]
Yes, closing.
