### ISSUE TITLE
M>Portugese Version of Lerner & Nash Foster interview transcript 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/bounties#282]
**Goal:**  [PORTUGESE .SRT](https://docs.google.com/document/d/1eUz9yjd6QtiyCyVLUYqFQqoOZLrahpCokXI0OU8Nm6k/edit)
**Stored in:**  https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii

**Collaborator:** @BelovedAquila 

- [x] Download the English (original) transcript
- [x] Translate the content: 10%
- [x] Check the spelling
- [x] View and review the Portuguese transcript
- [ ] Have it reviewed by others with deeper  understanding of Portuguese  and English 
- [x] @eedsilva 
- [x] @David405 

**Time:** 3 weeks maximum.

**Comment by David405** [comment]
@BelovedAquila, I would love to collaborate with you on this

**Comment by David405** [comment]
I can see you have already started, where can I join in?

**Comment by lapin7** [comment]
@BelovedAquila in the first comment there's a link to the serbo-croat version. Please change that

**Goal:** a [. srt file](https://drive.google.com/open?id=1OQkfiCpQvyPxINZ_RXZzFwpIpzWfbYPEYSCXcce-lOA)

**Comment by BelovedAquila** [comment]
@david for now would love handling it alone maybe you did be assisting in the review, reason because want to take responsibility for any errors that might be seen, though ain't hoping for one. @lapin7 alright, got it.

**Comment by lapin7** [comment]
@BelovedAquila @David405 
I would like to see a portugese version like hereunder
![image](https://user-images.githubusercontent.com/1913335/35749821-2b3b30ce-0853-11e8-9455-39fcfaea9e38.png)

**Comment by wordsandstuff** [comment]
@BelovedAquila is Portuguese your native language ?

**Comment by eedsilva** [comment]
Native portuguese speaker here. Let me know if I can help.

**Comment by lapin7** [comment]
See first comment. Change of Document to work on.

Status:	DRAFT (RAM's edit this to FINAL when done)
Language:	FRENCH
Integration done with:	@entropee work YES/NO
Doc link:	[/RChain/Members/Marketing-Community Dev/YouTube](https://docs.google.com/document/d/1t4M7SJ_JAypxzPMl39CUIXQGG8WMIhVsOgWANCtw780/edit#heading=h.c22lt3pgxzd3)
Participation:	Pub ...

**Comment by eedsilva** [comment]
I can definitely help with it, I just need access to the file

**Comment by BelovedAquila** [comment]
@wordsandstuff No it's not, working on it with natives.
@David405 and @eedsilva you can start up with the reviews.

**Comment by eedsilva** [comment]
@BelovedAquila Could you give me access to the files?

**Comment by BelovedAquila** [comment]
@eedsilva become a collaborator, so I could assign you into collaborating on this issue. You can do that by sending collaboration request email to @lapin7 via lapin7@gmail.com.

**Comment by BelovedAquila** [comment]
@eedsilva do you happen to be in discord or telegram so we could collaborate?

**Comment by eedsilva** [comment]
@BelovedAquila I am in discord. I am "Ed Silva"

**Comment by BelovedAquila** [comment]
@lapin7 please I  can't  access the transcript file anymore, been having some ups and down with my system while working on this issue, things got mixed up, so I want to make a fresh concise transcript and need access it.

**Comment by patrick727** [comment]
Analytics shows 889 brazilian unique from past 3 months
11 hit the developer site.

**Comment by Keaycee** [comment]
@BelovedAquila I still have the transcript as i'm helping out with the spanish work. We could work this together.

**Comment by eedsilva** [comment]
@lapin7 did you receive my email?

**Comment by BelovedAquila** [comment]
@wordsandstuff why not become a collaborator to assist in resolving issues for better job well done?to do that, 
Please friend, 
- Join https://groups.google.com/forum/#!managemembers/rchain/join
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by BelovedAquila** [comment]
@eedsilva yes you are, started a fresh work on another doc which I plan replacing with the current transcript, as for the one above its invalid, you are now a collaborator, so am assigning you to collaborate on the Portuguese transcript.

**Comment by eedsilva** [comment]
@BelovedAquila great. I'll keep you updated with my changes.

**Comment by BelovedAquila** [comment]
@eedsilva alright, thank you.

**Comment by BelovedAquila** [comment]
@eedsilva the file has been uploaded,please go on with the review.
