### ISSUE TITLE
Q> Establish norms for financial reward for comments

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#284]
### Outline
I think we need to have a discussion about how we — as a group — value comments on Github. In the last month many people spoke about about this, in various ways. For instance: 

@dckc wrote in #261:

> @zsluedem has left several "drive-by" comments that I consider counter-productive. For example: #259 (comment)

@viraculous said in the same issue:

> **The question is , what are the parameters of identifying solid contributions? @AbnerZheng sometimes solid contributions maybe passive and unrecognized.** I personally think that all newbees should be on boarded in a nursery group where they are educated on ethical values of the cooperative and also the criteriology of liquid democracy on budgeting and participation. They should be made aware of the implications of being unethical in budgeting and rewards. This is because a lot of more bad actors are yet to come.

@AbnerZheng writes in #246:

> **I don't think just comment or adding label has any contribution to the work.** So I set negative percentage to adjust @blovedaquila vote.

To which @BelovedAquila responded:

> @AbnerZheng this is a cooperative platform. And a cooperative is of the believe that no matter how little ones participation might seemly be, it still counts to certain percentage of total contribution done. Every participate counts, a participation being little doesn't void it from being a participation.

Besides this, countless other frustrated discussions can be found. 

### Goal
We should define a standard for how much weight (in terms of rewards) comments should carry. 

### Execution
Once we agree on the standard or guideline or rule of thumb, we can integrate this into the RAM (RChain Active Member) onboarding process, like many people have suggested.  

cc @Mervyn853 @traviagio @lapin7 (and many more!)

**Comment by pmoorman** [comment]
### My personal take on this...

Personally, I think too much weight is currently put on comments. This incentivises everyone to just "chip in their 2 cents" which is often well-intended but not necessarily helpful. 

The standard should be:

    **Comments are worthless unless they comprise delivered work**

Or something similar to that. 

### Why?

The reason for this, is that **doing the primary work is much harder than it seems to as an outsider.** We should lean towards over-valuing the primary contributor, rather than leaning towards under-valuing his work (by bleeding much of his credit/rewards away to bystanders).

The time it costs to do the primary work in most cases is measured in _hours_, whereas writing comments is a matter of _minutes_. Also, doing the primary work requires much more energy and 

In practice this could mean:

- Between 85-90% of the reward goes to whoever did the 'real work'... which is probably in most cases only 1 or 2 people per issue

- The standard is that good, thoughtful comments are worth something in the tune of 1%-of-total, as opposed to 5% or 10% of total, as is now quite often the case.

- Other "secondary contributions" such as reviewing things, commenting in a document or proof-reading should also carry less weight, and fit within the "10-15% of budget" space.

- A thoughtful compromise needs to be found for people that (for instance) do editing work on a document, or otherwise provide a "second pair of eyes" service to the primary contributor(s).


Anyway... those are just my thoughts. Happy to hear what everyone thinks!

**Comment by zsluedem** [comment]
At first I don't know too much about reward thing so I put comments everywhere(It's not because I want the reward, but I just want to get involved with the issue I am interested~!

Back here, I think for the "Advice type" issue , we should reward the one who give the advice we take.Sometimes we take two or three persons's advice ,then we vote for the percentage of the reward.
For the "Need to Do " issue, reward the persons who actually do it and finish it .

That's two types of issues I come across.

**Comment by kaka56** [comment]
@pmoorman am glad such issue is been brought up and i agree with you this

> Personally, I think too much weight is currently put on comments. This incentives everyone to just "chip in their 2 cents" which is often well-intended but not necessarily helpful.
**For me** I think there should be some percentage of rewards for helpful comments ,and it should be within "10-15% of budget'' space just as you said.

## why:
**.** comments add value to the work that is been done.
### how: some one with a better understanding,or idea of the issue can make a helpful comment that will improve the performance,quality or standard of work been done

**.**comments aids in  good management of the work.
### how: advice's from different collaborators are been given through comment.

**.**comment helps the project or work that is been done to meet up to standard.

**.**there are some issues that only needs helpful comments for it to be solved just like this.

these are my points why comments should have some percentages of budget space.

**Comment by pythonical** [comment]
maybe 'comments' is too broad and should have categories that are weighted
as to the nature of them?

**Comment by BelovedAquila** [comment]
**Comments are vital**
some comments are boosters,
 some are idea creators, 
some are insightful, 
Some are problem solving, 
some are helpful and 
_**some!_ Are 

> `_Not.**_`

So measures need be created as regards to each comments to know where it falls and how it would or should be rewarded.
Though I count every participation useful

**Comment by dckc** [comment]
Comments are neither worthless nor vital.

Getting feedback on work is valuable, but work can get done with no comments.

The point about hours vs. minutes is perhaps the most relevant. A comment that represents hours of review or years of experience is perhaps something I would vote to reward financially, but in other cases I expect collaboration is its own reward.

**Comment by Viraculous** [comment]
Am truly impressed about this issue. Many school of thought about comment valuation, hope we arrive at a consensus. I agree with @dckc "comments are neither worthless or vital". I think that worth of comments can be estimated from a normative view that is comments valued through a proportional voting system by participants, based on perceived value of a comment in getting work done with a statutory percentage to the person who raised the issue. e.g, I raise an issue, a mandatory percentage of the to total budget lets say 20% and a redistribution of 80% to all now based on votes per participants. and then from a positive view, where comments are hierarchically categorized and defined as @pythonical , @BelovedAquila  and valued by member through a consensus with also a mandatory % for the person who raised the issue. @pmoorman, I dont think 85-90% is fair enough and further more is likely to reduce member participation and the spirit of Cooperativism. 70-75% on average is fair. this is because, there are some other measures of participation not taken into account but still may have been helpful. This is what i think.

**Comment by flowpoint** [comment]
imo, until we have to get robust tracking for impact of small stuff like comments, question answering, fixing minor errata, ..., first,
we could say, everyone has to donate x< amount, every y, distributed to z< people he found helpful, and track that

**Comment by dckc** [comment]
@Viraculous writes
> a statutory percentage to the person who raised the issue ... 20% goes to me for raising the issue

Careful! That's likely to move us out of the frying pan of frivolous comments and into the fire of frivolous issues.

It hardly takes hours to raise an issue. Work worth rewarding financially takes hours, usually.

**Comment by Viraculous** [comment]
@dckc I get your point but I was just citing example. The percentage could be far less than 20% maybe  5% or less to be fair. They could be checks to reward on issue raised. The issue can be ranked in other of perceived relevance maybe rewarded according within a statutory range 1-5%. 95% now goes for redistribution.

**Comment by dckc** [comment]
I was just about to change the title of this issue to "Establish norms for financial reward for comments" but the description says:

> I consider implementation to be outside the scope of this issue. This is just the discussion.

_throws up hands in frustration_

The goal stated one paragraph period is "We should define a standard for how much weight (in terms of rewards) comments should carry." Our standard is CONTRIBUTING.md, no? The goal is reached when that document is edited to reflect the outcome of this discussion, no? You want a separate issue for that? That doesn't seem [SMART](https://en.wikipedia.org/wiki/SMART_criteria) to me.

**Comment by pmoorman** [comment]
@dckc this whole "setting a scope" thing is a lot harder than I thought!  I've just updated the headline & description in line with your comment above. 

With "execution" I was more thinking about concerns such as _"how do we make sure all (new) members see & understand this message"_.

_That_ should be, in my opinion, another thing. The goal for this discussion should be — taking Dan's suggestion here:

> **The goal is reached when the CONTRIBUTE.md document is edited to reflect the outcome of this discussion**

**Comment by dckc** [comment]
Ah. I read too much into what you wrote. Thanks for clarifying.

**Comment by dckc** [comment]
I suggest this discussion has reached a point of diminishing returns.
