### ISSUE TITLE
M> Russian Version of Lerner & Nash Foster interview transcript

### ISSUE THREAD

**Issue by kaka56** [rchain/bounties#285]
Goal: a .[srt file](https://docs.google.com/document/d/1yQNO3ihaBBy0bo1xC0mkTuyVWslM0kKIeXwGdWYmBqE/edit?usp=sharing)
stored in [ /RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)
with a translated transcript in RUSSIAN of the file
[[TRANSCRIPT][.srt][English] "Rchain Exclusive chat Lawrence Lerner & Nash Foster"](https://docs.google.com/document/d/1jTP6uuX4tuQpPREHlSniqYVxnzXev95gjm7fMwJG_UE/edit)
Progress indicator: see the evolvement of the doc
TIme: 2 weekS
Budget: $5000
Collaborator: @kaka56 @Keaycee @Barkov-F

**Comment by lapin7** [comment]
Bon chance @Barkov-F with the translation :-)

**Comment by Barkov-F** [comment]
https://docs.google.com/document/d/1yQNO3ihaBBy0bo1xC0mkTuyVWslM0kKIeXwGdWYmBqE/edit?usp=sharing

Here is the link to the draft. I have done the first five minutes and I welcome any reviews

**Comment by lapin7** [comment]
Great!!!
Contact @Mervyn853 to upload it to the original video

**Comment by kaka56** [comment]
Great work@Barkov-f in helping out with the Russian version. While reviewing, I noticed the sentence from line 17-19 is empty but will help to refill them so they can be translated

**Comment by kaka56** [comment]
I have also fix the proper link to  goal .srt

**Comment by Keaycee** [comment]
@Barkov-F check paragraph 342 on the transcript, there is words in English. Still reviewing the doc.

**Comment by Barkov-F** [comment]
I left the english wording so I would be easier to google the techical term
"scope extrusion". I am still working on the doc.

пн, 19 февр. 2018 г., 13:06 Keaycee <notifications@github.com>:

**Comment by Barkov-F** [comment]
I've done the first [draft](https://docs.google.com/document/d/1yQNO3ihaBBy0bo1xC0mkTuyVWslM0kKIeXwGdWYmBqE/edit). Reviews and comments are welcome.

**Comment by Barkov-F** [comment]
I've proofread the [transcript](https://docs.google.com/document/d/1yQNO3ihaBBy0bo1xC0mkTuyVWslM0kKIeXwGdWYmBqE/edit). I think it's ok to publish. @Mervyn853

**Comment by Viraculous** [comment]
great job work done @kaka @barkov and @keaycee

**Comment by ICA3DaR5** [comment]
@kaka56 Please create an .srt file as well. See: https://drive.google.com/open?id=1nl5ctTmA9FNK_uS6K2nN2m3gyzZJCIgY

**Comment by Barkov-F** [comment]
Here is the .srt
<https://drive.google.com/open?id=10pELesAm0g8Y-55dX8TjV_wIwdzvP7eW>

**Comment by Barkov-F** [comment]
Here is the [.srt](https://drive.google.com/open?id=10pELesAm0g8Y-55dX8TjV_wIwdzvP7eW) @kaka56 @ICA3DaR5 @Keaycee @lapin7
