### ISSUE TITLE
M > Upload Youtube video to China online video website 

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#289]
Because of GFW in China , people in China is difficult to watch the video on Youtube.So I have create accounts in China video website to upload the videos on Youtube.

I have remaked the [video Exclusive chat Lawrence Lerner & Nash Foster](https://www.youtube.com/watch?v=PwuV7ryhaXw&t=2388s)video based on #251 #264 with the Chinese subtitle by a video software and upload it to Chinese main video website like:

优酷 Youku: [video](http://v.youku.com/v_show/id_XMzM3ODE5NDM2OA==.html?spm=a2hzp.8244740.0.0)
爱奇艺 Iqiyi: [video](http://www.iqiyi.com/w_19rvxctbll.html)
Bilibili : [video](https://www.bilibili.com/video/av19118757/)

People now in China can watch the videos from Youtube.I think in this way Rchain would be spread out easier.

Next, I will download the videos from [Youtube Rchain channel](https://www.youtube.com/channel/UCSS3jCffMiz574_q64Ukj_w/videos) and upload it to those Chinese website (but without the subtitles).It needs time to bake to subtitle into the video.

If the video has the subtitle, I will remake the video with the subtitle(I found most of them don't have any Chinese subtitle).

Time:long term work

BUDGET: $500

**Comment by zsluedem** [comment]
Yeah~! I have remake [RChain Vision video](https://www.youtube.com/watch?v=Qftq9S34xgg) with the Chinese subtitle based on @Mervyn853 translations, too. I think it is a good introduction video for Rchain.

**Comment by Mervyn853** [comment]
Wow great work @zsluedem , im glad my chinese translations of the RChain vision transcript #215  is finally put to good use. @sportshark Could we get these videos on the Chinese fan site?  #173

**Comment by Mervyn853** [comment]
@zsluedem If its possible, you could find a few native mandarin speakers who could do this in Chinese voiceover which will be better for the general Chinese population to understand. Also agree on getting them on youku and 171 for greater exposure due to the great firewall of china.

**Comment by Whisker17** [comment]
cool，we can do it together

**Comment by zsluedem** [comment]
Done with the upload of [RChain Developer Retreat](https://www.youtube.com/watch?v=Fs38s7nI3Uk&list=PLf2bbiic5ZjCPzin3gCSMGiBtbT8UO5o2) to [Youku](http://list.youku.com/albumlist/show/id_51501850) and [Bilibili](https://space.bilibili.com/286283912/#/)

**Comment by zsluedem** [comment]
This one has done already~! According to #318 #401, I am going to close this issue. Feel free to reopen it.
