### ISSUE TITLE
on-board @dckc, advocate of open web, open source, and capability security

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#293]
As [suggested in 253][1], let's retrospectively document the work folks did to get me on board. One version of the story is in [my blog item][2]. _I wonder if "welcome" is a better way to start the title than "on-board"._

brain dump: https://github.com/rchain/Members/wiki/Weekly-Debrief-Index , README and CONTRIBUTIONG ...

[1]: https://github.com/rchain/Members/issues/253#issuecomment-362917062
[2]: http://www.madmode.com/2017/rchain-dev-retreat.html

cc @Ojimadu @lapin7 @jimscarver @kitblake @pmoorman

**Comment by kitblake** [comment]
+1 for 'Welcome'

**Comment by dckc** [comment]
I'm pruning my todo list... this is done to my satisfaction, until I think of something else worth documenting.

**Comment by dckc** [comment]
Everywhere I look I see RChain apps now:
  - tripit - why don't I get paid for contributing my data? Why do I have to look at ads?
  - google maps - again, why don't I get paid for contributing my driving data?

  - [finquick](https://github.com/dckc/finquick) - the personal finance system I've been building for years
    - Discover shut down their OFX server, so I tried using plaid
      - I have a screenshot of an error message from the plaid API
      - Why should I have to give my bank password to plaid anyway?!?!?!

  - The other night I fronted @TrechFloat money to buy a clarinet
    - The purchase price was higher than the ATM limit
    - The seller offered to take venmo; after re-installing it...
      - setting up my bank account ran into errors several times in a row
      - using a credit card worked, but with a hefty fee
   - it looks like the easiest way for him to repay me is with crpytocurrency

 - as I wrote in my blog item: gmail
   - I hope the mailbox@domain name structure fades slowly if at all, but can't we set up the economics so that SPAM isn't cost-effective? (the discussions around SPF and DKIM showed there are lots of tricky issues, esp. mailing lists)
  - on the flip side, getting sub-second search of 15GB of mail in an RChain app is an interesting challenge

 - twitter. Here's hoping the #BuyTwitter movement turns into a coop
   - perhaps STEEM points a way forward, on the other hand

 - github? I've never seen a reason to believe that decentralized issue tracking should work, but perhaps the whole thing can be packaged up as a smart contract that can be deployed separately for each community. Economies of scale benefit the github community for now, but it's quite likely to scale only so far, as most online communities (see c2.com / CommunityLifeCycle or thereabouts)

**Comment by dckc** [comment]
so many business relationships I'd rather replace with coops and smart contracts:
 - streaming music (roll on resonate.is!)
 - credit cards
 - cell carrier (found one, but it's in the UK)
 - ISP
 - hardware vendors?
