### ISSUE TITLE
Translate README.md into Chinese

### ISSUE THREAD

**Issue by Whisker17** [rchain/bounties#296]
I've translated README.md into Chinese.It is about 157 words in the English,so I think the budget should be $32

**Comment by kitblake** [comment]
Looks good! But I can't read Chinese. The translation needs to be peer reviewed by other native speakers. @sportshark translated the FAQ, maybe he or other Chinese speakers could review.

**Comment by zsluedem** [comment]
I can help review it

**Comment by n10n** [comment]
Can anybody review this? https://github.com/rchain/reference/pull/40
