### ISSUE TITLE
Translation quality assurance and issue template 

### ISSUE THREAD

**Issue by wordsandstuff** [rchain/bounties#302]
Native speakers need to have priority over the translations.  I dont think that some one who doesn't speak German or Spanish or what ever language should be able to be the main translator . Google translate should NOT be the first method of translation. QUALITY should always be the TOP priority.  Yes I would like to translate something with google translate and make money, but I know a native speaker can do it better.

**Comment by flowpoint** [comment]
to make this issue smart, we maybe could streamline translation with a short translation_guide and find a way to find native speakers of the languages
also how schould we reference this with the many current translation issues?

**Comment by dckc** [comment]
Which translation used Google translate with poor quality results? Pointer, please?

@lapin7 invited work on a [translation policy][1] in an [Oct 11 comment][2] Unfortunately, aside from my suggestion to take inspiration from [W3C Translations][3], it's empty.

[1]: https://docs.google.com/document/d/1xSXK4DAVwcc-OnrvRm4KP-LOSwWKnAxVOWIpFcCAYaw/edit
[2]: https://github.com/rchain/Members/issues/100#issuecomment-335711243
[3]: https://www.w3.org/Consortium/Translation/

**Comment by jimscarver** [comment]
someone must take the responsibility for development of the translation policy.

I believe no transaction can be considered good until several speakers of the language have reviewed and improved it. There is a work flow process  If no one is willing to review/correct it given reasonable bounties it can be considered worthless. reviewers budget/claim/award a percent of the bounty commensurate with the amount of work toward a finished product needed and delivered..

**Comment by llerner** [comment]
Review by consensus. Three native speakers should agree upon the translation. Split the bounty accordingly (E.g., translator gets 70%, validators get 15%)

**Comment by dckc** [comment]
Yes, my impression is that we are doing just that: review by several native speakers.

At some point, it becomes cost-effective to lay down rules explicitly, but it's not much fun. Just trusting each other is more fun. So I'd like to see evidence that just trusting each other isn't working. Pointer, please?

**Comment by Viraculous** [comment]
I agree with @dckc and @llerner . Your idea is splendid @wordsandstuff. In a cooperative and decentralized Community as the RChain, what we market is solidarity in trust to achieve precision on work done.

**Comment by Keaycee** [comment]
I agree with @dckc & @llerner .  You have a point @wordsandstuff , The google translation API is very poor and it's translation are not accurate, and i do not advice or support any work done with google translation. But you must also know that there are native speakers who are not member of our cooperative but get paid to get most translation work done. There are native speaker who's job is to translate documents or assist in business interaction. Anyone who is willing to take up the cost to contract a native speaker to get a work done is good enough. What we should consider, is the quality and accuracy of the translation work been done.

**Comment by flowpoint** [comment]
> Pointer, please?

not suspecting/blaming anyone but in:
#266 this [document](https://docs.google.com/document/d/1oTZVkYEhhnZtyU4DmNiiT3N39R0IVpHI92vP8kaltFs/edit)
example, line 789:
> [...] wissen, dass die dag-Operationen, die Haschisch [...]

in the english transcript:
> 'know, to the DAG operations that Hashgraph'

'Haschisch' is a german word for marihuana, which doesnt fit at all,
and i doubt, that a human, would translate english "hash" into german "Haschisch"

**Comment by dckc** [comment]
I guess I don't see a problem in the case of #266. It's still clearly on their TODO list to "Have it reviewed by others with deeper understanding of German and English". They don't claim to be done.

My experience with translation is all 2nd hand, but I don't see any reason to rule out Google translate as a way to start. As long as the end product is good quality and people treat each other with respect along the way, I don't much care how it gets done.

**Comment by dckc** [comment]
oh! @flowpoint you're the one doing the reviewing. If you see a problem, then there is a problem.

**Comment by n10n** [comment]
Food for thought: https://www.quora.com/How-effective-is-Google-translate... varies between 58 to 88 % and this number is language dependent. If you like the real numbers then use this: http://mt-quality.multilizer.com/machine-translation-quality-statistics/. Question - Do you want to use this tool for the translation?

**Comment by flowpoint** [comment]
### my gripe is:
1. if the result matters, then the goal and budget should be fixed. however someone got there isnt important. 
2. or, if the amount of effort matters, reward is proportional, then whether google translate was used impacts alot.

without clear decisions about that, it will lead to:
someone claiming reward for his effort (2.) , without having done work himself, towards the result (1.)
### here:
someone using google translate, getting 80% accuracy, claiming its his work and he cant do better.
-> little work done, big reward

p.s. google translate from a cleaned englisch transcript to german is very good. how to decide which translation was done by software or badly done by a human?

**Comment by Keaycee** [comment]
@flowpoint How the work is been done does not really matter. What matters is the quality and accuracy of the work been done. We need the works to be reviewed and proofread to check further errors and corrections. This work maybe translated by a native speaker who are been paid by a coop members or  probably by a translator.  Which ever way the work is done, what's important is a work well done.  It's a decentralized cooperative, we all can contribute to any particular issue base on specialty or knowledge.

**Comment by dcpnlau** [comment]
I agree with @Keaycee: quality over quantity/how work has been done. If Google Translate was 100% accurate, it would be fine to use and we could have perfect translations at lower cost as it would be easier to do. Unfortunately, this is not the case, so a suggestion I'd like to propose:

Can we create a list of native speakers by language who are willing to proofread translated transcripts or translate projects altogether? That way we can easily notify and assign issues to native speakers who can then decide if they want to work on it. 

Is there any way we can use the KYC process to confirm nationality and if someone is a native speaker, as it will inform us with great accuracy of someone's background? Or is this too private information? Though I understand that e.g. someone who has a Spanish passport, may have grown up in the UK and not be fluent, but I think this number of people will be minimal and we'll be able to pick up on these people quickly.

**Comment by dckc** [comment]
@dcpnlau writes:
> Can we create a list of native speakers by language who are willing to proofread translated transcripts or translate projects altogether?

That's a fine idea. Would you please do so?

I think it's worth putting some more quality control measures in place.

In #100 I requested that translation issues be specific to a source document and a language. These are not specific to a document:

 - #329 Requesting to translate to Filipino
 - #328 request to translate into Indonesian
 - #320 M>Requesting for Cebuano Translation
 - #317 M>Request for Spanish translation
 - #312 M> Documentation: Translation into Spanish Language
 - #303 M> Filipino Translation for the Project

#317 is a dup of #312.

#317 and several others also shows a lack of familiarity with the [self-starter](https://github.com/rchain/Members/wiki/Welcome-To-RAM) aspect of bounty work. Work in other languages is significantly less transparent -- many of us cannot evaluate the quality of the work.

**Comment by Ojimadu** [comment]
While we give Native speakers preference in translation, we need to also note that a good number of native speakers are also not fluent in English. Some might use some computer aided translation to convert these text into English all this can affect how the translation work turn out to be overall.

**Comment by dckc** [comment]
In cleaning up some goofy git commits (#319) I just realized that many of the translations are for administrative files in this repository. Compared to translating the architecture document or some such, these have little value in telling the RChain story.

Also, I expect README and CONTRIBUTING to change significantly as a result of our onboarding discussion, so I would only want those translated in the case where a commitment to maintain them over time is arranged.

I wonder about [Setting up a Proper Multilingual Site with GitHub Pages and Jekyll](http://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/).

**Comment by dckc** [comment]
@patrick727 which lanuages show up high in web site analytics?

**Comment by dckc** [comment]
Perhaps an issue template for translations:

  - Why this document? (mark all that apply)
    - [ ] it's one of the /rchain/reference documents
    - [ ] I contacted the author, who agreed it's important to translate
    - [ ] I know a person or audience who would benefit from it: _____
    - [ ] other: ___
  - How can people who do not speak this language be assured of the quality of the translation?
    - [ ] several reviewers are involved
    - [ ] at least two of them have high proficiency in (the target language)
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have significant reputation at stake or have a track record of quality work on rchain bounties

**Comment by Ojimadu** [comment]
@dckc A good template up there. IMO, the most important documents that should be translated are
1. [How to contribute](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md) 
2. White paper and architecture documents 

Translation of any other document should meet a quorum set by the community through a proposal, and the languages to be translated into should be among the top 10 spoken languages (except English)  by number of speakers. Except in cases where the translation has a clear value and and audience for it.

**Comment by dckc** [comment]
@ICA3DaR5 would you please help shepherd translations for a while? I would much rather focus on other things, and @dcpnlau isn't available -- at least not today (cf. #381).

Perhaps you could recruit @AbnerZheng to help you?

I think I read that github supports multiple issue templates. Would you please start by installing the checklist in my comment above?

**Comment by ICA3DaR5** [comment]
@dckc Sure thing.

**Comment by ICA3DaR5** [comment]
@dckc We can do the same thing we did on #398 for Pull Requests too.

**Comment by dckc** [comment]
This is done to my satisfaction.

@wordsandstuff and others, feel free to re-open it if you see more to do that shouldn't go in a separate issue.

**Comment by dckc** [comment]
#483 shows the approach here isn't working well enough.

**Comment by Barkov-F** [comment]
The usage of machine translation is [detectable](https://www.researchgate.net/publication/228353067_Detecting_inappropriate_use_of_free_online_machine_translation_by_language_students-A_special_case_of_plagiarism_detection). But I have no idea how to implement such a system here

**Comment by ICA3DaR5** [comment]
@Barkov-F I think colleges use something like this to avoid machine translation and copying from other students.

**Comment by dckc** [comment]
#483 seems like a dup of this one, but I guess the action is over there...
