### ISSUE TITLE
M> Filipino Translation for the Project

### ISSUE THREAD

**Issue by caratzky** [rchain/bounties#303]
Good Day!

I have been a contributor of Filipino Translations for open-source projects for the sake of Filipino developers, and I am being rewarded by Utopian.io. May I know if you need this kind of translation for your project? It would be my pleasure to help you. Thank you.

Have a nice day!

**Comment by BelovedAquila** [comment]
@caratzky interesting, that's impressive. Your collaboration here is greatly needed,why not create an issue on what you did would like to work on. Do you mind starting a Filipino transcript on this #251 or #292 ?

**Comment by caratzky** [comment]
Isn't there an already-made English Transcript? I would love to start the translation now

**Comment by BelovedAquila** [comment]
@caratzky there is or there are. Please follow up the issues on #251 you would get the link to the English transcript there. @ICA3DaR5 is still working on a more concised error free version of it though in #292, wonder if he is done yet with it, that would have been the best transcript to work on to reduce the work load of trying to rightly correct errors in the early English transcript.

**Comment by BelovedAquila** [comment]
@caratzky 
[Here's the link](https://docs.google.com/document/d/1cq8hWLLrdlT6W_t07sFqYanXEwwbjBSvcJv92aoKO5s/edit) again.

**Comment by ICA3DaR5** [comment]
@BelovedAquila I'll watch the video with the English transcript one more time tomorrow, and I'll call it a day!

**Comment by Keaycee** [comment]
There are still corrections to be done on the current transcript. I've watched the video and followed word after words. It's 80% good. Just few more corrections to be done.

**Comment by kaka56** [comment]
Welcome @caratzky . Please specify  the Source  of documents   you want to translate  on the issue  you created

**Comment by caratzky** [comment]
Actually I already translated almost all translatable files in this project @kaka56

**Comment by caratzky** [comment]
For 1 language only

**Comment by kaka56** [comment]
Edit your issue and make mention  of the project  you translated on the issue. Here is an example 
### M> Translate /rchain/rholang/doc/* to Italian#367

**Comment by kaka56** [comment]
@ also paste the link of the project  you translated .

**Comment by zero-andreou** [comment]
ok, I see no comment has been made since feb 16 so I assume this is abandoned.
