### ISSUE TITLE
Translate <Categorical foundations, RChain, Mike Stay, Pyrofex, cool contd> into Chinese

### ISSUE THREAD

**Issue by jiyuxuan1944** [rchain/bounties#304]
We think it is necessary to translate this interesting story, which will make Chinese fans better understand Rchain.
word count:2545
budget:$500
time：5 days

**Comment by zsluedem** [comment]
Can you provide a link or something which article you refered? @jiyuxuan1944

**Comment by Viraculous** [comment]
Please do mind writing the budget in $dollar equivalent for clarity.@jiyuxuan1944

**Comment by jiyuxuan1944** [comment]
@Viraculous Okay, I did not notice the problem.

**Comment by jiyuxuan1944** [comment]
@zsluedem I found it here.
https://johncarlosbaez.wordpress.com/2018/02/04/pyrofex/

**Comment by JieL314** [comment]
I have reviewed it.

**Comment by jiyuxuan1944** [comment]
@hcl3 We have finished the translation,you can upload to the WeChat Official Account.

**Comment by hcl3** [comment]
@jiyuxuan1944 ok, I've uploaded it to the WeChat Official Account.

**Comment by zsluedem** [comment]
this one has been done on Feb. Closing it now .

**Comment by jiyuxuan1944** [comment]
https://mp.weixin.qq.com/s/r0OjJhqXKV0n8O2Tjr3VmA

**Comment by ICA3DaR5** [comment]
Closing this as it seems completed!
