### ISSUE TITLE
G> Prezi "Decentralized ..."

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#307]
## Goal: create Prezi for 17 Feb, Governance Meeting
**"Decentralized setting of budgets and rewards for solving self defined issues on Github" is the key for building a 10.000+ swarmwise organisation that helps RChain getting on the rails.**

Send email addresses to ops@rchain.coop for collaboration on [Prezi](https://prezi.com/view/gOEfKm6SgClJkigEeZET/)

This is the very very beginning of a draft

**Comment by n10n** [comment]
What is RAM or SMART?

**Comment by lapin7** [comment]
You can help me creating this presentation by logging in to https://prezi.com
as rchain@googlegroups.com
pw: Decentralize

**Comment by zsluedem** [comment]
@lapin7 requirements for the presentation? Where can I find the topics ? Or I have to come up with one by myself.

**Comment by lapin7** [comment]
@zsluedem To be clear. I'm going to give a presentation on the Governance Meeting 17, February.
The subject is: 

**"Decentralized setting of budgets and rewards for solving self defined issues on Github" is the key for building a 10.000+ swarmwise organisation that helps RChain getting on the rails.**

I want to cover the [spreadsheet system](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=60903965)

Use #251 "M> Translate video Exclusive chat Lawrence Lerner & Nash Foster" as an example of great collaboration.

Use #261 "O>	slashing conditions in the RAM budgeting and reward system?" as input

Use #260 "O> Usable Web app for RAM distributed budgeting and reward system" as our future system

Set up a form for making decisions about:
- high level budget for decentralized work (10,000,000 RHOC)
- goal: 10,000 RAM's before 10-10-2018
- approval of the whole system
- .... what else

**Comment by jimscarver** [comment]
I added a few topics including objectives and oversight and then leah and I did an overall edit for clearity and language.

It may be better to set up loomio for voting rather than a form @lapin7 ?

**Comment by plantether** [comment]
@jimscarver The slide title is spelled "Oversite" but it should be "Oversight"

**Comment by dckc** [comment]
@lapin7 delivered the presentation at the [RChain Governance Forum 2018](https://www.gov.rchain.coop/2018-gov-forum)
