### ISSUE TITLE
M> Documentation: Translation into Spanish Language

### ISSUE THREAD

**Issue by michaelizer** [rchain/bounties#312]
Greetings, I would like to contribute to the project by translating it into Spanish. Spanish is my native language so don't panic (I was reading the Issues), but a lot of Spanish speakers are still limited by the language so this is primarily to help them. At Utopian we love contributing to open source projects. 

Thanks in advance and for your time. Keep up the great work.

**Comment by lapin7** [comment]
Hi @michaelizer 
Please accept https://github.com/rchain/Members/invitations
and https://groups.google.com/forum/#!pendingmember/rchain/join

**Comment by michaelizer** [comment]
Done

**Comment by BelovedAquila** [comment]
@michaelizer sorry about that,use this
 https://groups.google.com/forum/#!forum/rchain

**Comment by kaka56** [comment]
@michaelizer good to have you here. While you accept  the invitation been sent to you, please  specify  the source  of documents you  want  to translate . Example 
#367 M> Translate /rchain/rholang/doc/* to Italian
#368   M> Translate architecture-docs/*.rst files to Italian

**Comment by lapin7** [comment]
Nothing has been done in Feb. So I downgraded the budget for Feb.

**Comment by michaelizer** [comment]
https://github.com/rchain/bounties/pull/341 
https://github.com/rchain/bounties/pull/340
