### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by nanik94** [rchain/bounties#317]
Hi!, can I translate this project into spanish ?

**Comment by Viraculous** [comment]
@nanik94  I edited this issue to make it more organised. Also which project do you mean?

**Comment by BelovedAquila** [comment]
@mrinalmanohar of course you can work on it, there are various translation projects you can work on and various collaborators you can align with for effective output if you don't mind. But Dear friend start up the process, become a collaborator, 
plz join https://groups.google.com/forum/#!managemembers/rchain/join
and accept https://github.com/rchain/Members/invitations
and send your email to ops@rchain.coop

**Comment by kaka56** [comment]
@nanik94 you  are welcome. What  project  do you want to translate ?. Please specify  the source  of documents  you are interested  in translating. #367

**Comment by nanik94** [comment]
i was interested in translating the project RChain for sec compliance, i saw you have a book there called Rchainwhitepaper.pdf, i could work on that and on any other project you could use the help, thanks and let me know, i am at your disposal

**Comment by kaka56** [comment]
@nanik94  edit  the issue by mentioning  the specific  doc you want to work  on. example you can edit it to
**M>Translate White Paper to Spanish**
