### ISSUE TITLE
O>Require review of file repository changes

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#319]
We have too many people with too little experience with git to let everyone commit without review. 

For example, the [blame view of CONTRIBUTING.md][1] got corrupted in the process of a a recent tagalog translation 5e795fb.

[1]: https://github.com/rchain/Members/blame/master/CONTRIBUTING.md

 - [X] change the repository settings to require review of pull requests.
 - [x] update `CONTRIBUTING.md` to document the requirement

**Comment by lapin7** [comment]
@dckc I don't know how to manage this Github Rep. I leave it up to you to make all the necessary changes/restrictions.
I've made you admin of rchain/members

**Comment by rjl493456442** [comment]
Strongly agree with this. Pull request is the recommended way instead of pushing commit directly.

**Comment by ICA3DaR5** [comment]
Git and GitHub knowledge should be a requirement. Pull Requests is a nice wall between people who know what they are doing and people who don't.

**Comment by rjl493456442** [comment]
Hey @dckc . I have pushed a [PR](#355) adding the git workflow chapter in CONTRIBUTION.md.
PTAL.

**Comment by ICA3DaR5** [comment]
@dckc There's a lot of stuff [here](https://guides.github.com/) and [here](https://git-scm.com/doc)

**Comment by rjl493456442** [comment]
@ICA3DaR5 Hey, i push a PR which mentioned above. I add a workflow example in the contributing file just like the most opensource project. Do you think which way is better:

1. Add a simple workflow example
2. Add a tutorial link

We should choose one so that newbie can learn how to use git.

**Comment by dckc** [comment]
Since CONTRIBUTING.md is the authoritative record on what the bounty contract is, its history needs to remain in-tact. So that we can once again see [who wrote which parts of CONTRIBUTING.md][1] and when, I reverted the master branch to Feb 7, before it was clobbered in some translation work:

To github.com:rchain/Members.git
 + 8f687b3...a517753 master -> master (forced update)

What was previously the master branch is now a [needs-cleanup](https://github.com/rchain/Members/tree/needs-cleanup) branch.

[1]: https://github.com/rchain/Members/blame/master/CONTRIBUTING.md

**Comment by michaelizer** [comment]
@dckc where is going to be the place for translations now? (after the clean up)

**Comment by dckc** [comment]
I made a suggestion about directory organization in #351.

But this issue is not about changing file locations; it's about cleaning up the git version control history.
