### ISSUE TITLE
 Cebuano Translation

### ISSUE THREAD

**Issue by iam-strings** [rchain/bounties#320]
Hi,

I would like to contribute on this project through translation. I would to translate the necessary files to my native language, Cebuano.

Thanks....

**Comment by caratzky** [comment]
@iam-strings  somebody has already been assigned for Cebuano Translations. .

**Comment by caratzky** [comment]
@iam-strings actually you can help in doing the translations for Cebuano along with @josephace135. 

Am I right @BelovedAquila ?

**Comment by josephace135** [comment]
Hi Mr. @caratzky,

I can pair with @iam-strings  if given the chance to translate it into Cebuano.

**Comment by caratzky** [comment]
Yes, much better. Thank you.

**Comment by Viraculous** [comment]
@iam-strings , i edited this issue to make it more organised.

**Comment by BelovedAquila** [comment]
@caratzky you are not far from right friend.
@josephace135 glad you are interested in working on the translation projects, just like @caratzky said, you can work along with @iam-strings not because you can't work alone, but because the cooperation could create an effective job well done. You can work alone too, but two heads are better than one. Why not start by becoming a collaborator friend?

**Comment by BelovedAquila** [comment]
@caratzky you are not far from right friend.
@josephace135 glad you are interested in working on the translation projects, just like @caratzky said, you can work along with @iam-strings not because you can't work alone, but because the cooperation could create an effective job well done. You can work alone too, but two heads are better than one. Why not start by becoming a collaborator friend?

**Comment by iam-strings** [comment]
@BelovedAquila Yes sir. I would be glad if I can contribute with @josephace135. Thanks a lot sir.

**Comment by iam-strings** [comment]
@Viraculous okays sir. Thanks

**Comment by josephace135** [comment]
Okay. I like that idea. I will collaborate with.

Sorry can’t tagged. Was using cp for now.

**Comment by iam-strings** [comment]
@BelovedAquila @josephace135 and I wanted to be become certified collaborators for this project. How are we going to achieve that? Thanks...

**Comment by BelovedAquila** [comment]
Ok friends, glad there is a mutual agreement @iam-strings and @josephace135, to become a collaborator
plz join https://groups.google.com/forum/#!managemembers/rchain/join
and accept https://github.com/rchain/Members/invitations
and send your email to ops@rchain.coop

**Comment by josephace135** [comment]
@BelovedAquila I have apply for membership in the Google group of RChain.

**Comment by BelovedAquila** [comment]
@josephace135 great, you will get a feedback soon please.

**Comment by lapin7** [comment]
@BelovedAquila I've made you admin on Github https://github.com/rchain/Members/ and manager on rchain@googlegroups.com. You will also get forwards of ops@rchain.coop to your personal email address.
The goal is that you scan for new collaborators and ask them to register on:

- join https://groups.google.com/forum/#!managemembers/rchain/join
- accept https://github.com/rchain/Members/invitations
- send your emailaddress + github name to ops@rchain.coop

You can enter the incoming requests in this sheet. [RAC register](https://docs.google.com/spreadsheets/d/1E25ruhIawKtJekK26pVU0s9kl4T6z4MrQ2FGIQYXQPM/edit#gid=0)

**Comment by kaka56** [comment]
@lapin7  I will like to assist @BelovedAquila  on this.

**Comment by lapin7** [comment]
@kaka56 
That's great. Scan all comments on new collaborators and ask them to register with previous message.

**Comment by BelovedAquila** [comment]
@lapin7 gladly, thank you for this privileged to help out.

**Comment by josephace135** [comment]
@BelovedAquila  ahh i can collaborate with both @iam-strings and @vinzruzell . He would be a great addition to the team.

**Comment by BelovedAquila** [comment]
@vinzruzell and @josephace135 sure!,more effective work is done when done in cooperation, so why not?.
@vinzruzell become a collaborator, follow the directions on your recent issue #358

**Comment by kaka56** [comment]
@josephace135 @iam-strings @vinzruzell  is great you want  to collaborate  on Cebuano  translation. Please while you are still following  the steps  to become  a collaborator, specify the source  of documents  you want to  work  on the issue. That is Cebuano translation of which  doc?.

**Comment by vinzruzell** [comment]
Hi. Thank you for the info. I would to translate dictionary.md into
cebuanoo. If still available.

**Comment by ICA3DaR5** [comment]
This is ghost city. Closing.
