### ISSUE TITLE
Filipino Translation

### ISSUE THREAD

**Issue by agentzero1** [rchain/bounties#329]

**Comment by BelovedAquila** [comment]
@agentzero1 good knowing you are interested in working on the translation projects friend, let's start it up with you becoming a collaborator?
Please friend 
- Join https://groups.google.com/forum/#!managemembers/rchain/join
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by agentzero1** [comment]
How many days is the approval of membership ?

**Comment by caratzky** [comment]
@BelovedAquila we have almost finished translating the project files into Filipino/Tagalog. @agentzero1 you may help in the other untranslated files.

**Comment by agentzero1** [comment]
what about Cebuano dialect ?

**Comment by caratzky** [comment]
@josephace135  is working on it. You may help.

**Comment by agentzero1** [comment]
okay thanks

**Comment by agentzero1** [comment]
who will review my  translation you or @BelovedAquila ?

**Comment by BelovedAquila** [comment]
@agentzero1 I suppose one with a deep knowledge of your dialect transcript would do the review. It won't be a bad idea working with @caratzky on that.

**Comment by caratzky** [comment]
Yes, I will gladly, properly and accurately do it @BelovedAquila . @agentzero1 I have made a file in the master folder containing the english transcript. I suggest you divide it into six parts, coz there are about 7000 words in it.

**Comment by kaka56** [comment]
@agentzero1  Please specify  the document of the project  you worked  on. 
 You can  start by pasting a link.

**Comment by agentzero1** [comment]
@BelovedAquila  why I cant open your invitation ?

**Comment by agentzero1** [comment]
Thanks for kindness

**Comment by BelovedAquila** [comment]
@agentzero1 so sorry about the inconvenience, please kindly send your complaint to @lapin7 via lapin7@gmail.com. Thank you

**Comment by ICA3DaR5** [comment]
This seems abandoned!
