### ISSUE TITLE
M> List 60 Medium Info-Sources

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#332]
I created a tab in the [research spreadsheet](https://docs.google.com/spreadsheets/d/1M9kqbnYxotaOLtWOj7MWquE41KADZJLtwFdgDqtoEck/edit#gid=520219094)

Lets list out the medium writers/publications that our target audiences will go for information. 

Target Segments: 

"Mavens" - highly experienced programmers that tinkerer with new toys
"New Blockchain Developers" - less experienced devs(could be students) who want to learn blockchain programmer for their career

**Comment by patrick727** [comment]
Added the first 10 to kick it off!!!

**Comment by ResonanceXX** [comment]
Fred Erhsam's articles are insightful. A lot of knowledge could be passed from him to both Mavens and N.B-C.D. He will be added.

**Comment by Tonyprisca13** [comment]
Added 13-18

**Comment by Tonyprisca13** [comment]
Fine! lets do what will be best.

**Comment by Tonyprisca13** [comment]
i added 19 and 20

**Comment by ResonanceXX** [comment]
21-27. Cheers

**Comment by ResonanceXX** [comment]
**28**

**Comment by Tonyprisca13** [comment]
43

**Comment by ResonanceXX** [comment]
44. cheers

**Comment by ResonanceXX** [comment]
Lets keep this ball rolling peeps. Cheers.

**Comment by ResonanceXX** [comment]
I just added a 55. A very interesting content writer.

**Comment by ResonanceXX** [comment]
@Patrick727 I still am interested in getting this done fully. But very skeptical of contributing redundantly.

**Comment by Tonyprisca13** [comment]
same here @patrick

**Comment by Tonyprisca13** [comment]
@Resonancexx do suggest a budget

**Comment by AyAyRon-P** [comment]
Closed
