### ISSUE TITLE
Filipino Localization/Translation

### ISSUE THREAD

**Issue by vinzruzell** [rchain/bounties#358]
Hi. I would like to contribute filipino translation in your community.

**Comment by vinzruzell** [comment]
Also I would like to contribute cebuano translation. Thank you.

**Comment by BelovedAquila** [comment]
@vinzruzell you are welcome to contribute in the translation projects of your stated languages, to start it up,
Please friend, 
- Join https://groups.google.com/forum/#!forum/rchain
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by dckc** [comment]
Which document would you like to translate?

See [my comment on translation requirements](https://github.com/rchain/Members/issues/302#issuecomment-365101015)
and [Welcome to the Bounty Program](https://github.com/rchain/Members/wiki/Welcome-to-the-Bounty-Program).

**Comment by vinzruzell** [comment]
Hi I want to translate dictionary.md into Cebuano if still available.

**Comment by dckc** [comment]
I recommend against translating `dictionary.md`. See #88

**Comment by vinzruzell** [comment]
Thank you sir

**Comment by zero-andreou** [comment]
closing.
