### ISSUE TITLE
O> Filling out tax Form W8 BEN and W9

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#360]
GOAL: Create manual for filling out tax form W8 and W9

[W8 BEN](https://www.irs.gov/pub/irs-pdf/fw8ben.pdf)

**Comment by TrenchFloat** [comment]
[This link](https://www.irs.gov/pub/irs-pdf/fw9.pdf) has a W9 form with instructions. Crude, but effective.

**Comment by Tonyprisca13** [comment]
I have compiled an easy to use and concise instruction manual on W-8BEN form which can be found [here](https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing).
I am also working on a concise manual for W-9 form.

**Comment by lapin7** [comment]
@Tonyprisca13 please make the access to "WRITE" for rchain@googlegroups.com
[W8 instructions](https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing).
And add a link to the actual W8 form

**Comment by Tonyprisca13** [comment]
I have made the access and added the link.

**Comment by Tonyprisca13** [comment]
The link for W9 form can be found[here](https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit?usp=sharing)

**Comment by makys** [comment]
Reviewed W9 form manual prepared by @Tonyprisca13 . It looks good. However anyone who need additional information should spend time going through the General instruction on the form. If not clear on any section, can ask and we will try to guide.

**Comment by tcezi** [comment]
@tonyprisca13 Nice work  it's simple and clear

**Comment by BelovedAquila** [comment]
I reviewed the W8 form manual. @Tonyprisca13 you did a nice work on that, it's actually very concise and straightforward. 
@lapin7 the manual for filling out tax forms W8 and W9 created by @Tonyprisca13 are they good to go?

**Comment by Biseny** [comment]
@lapin7 request a Github collaborator role . My email ：Biseny@qq.com

**Comment by lapin7** [comment]
@BelovedAquila please link to the manual W8/W9 when you've scanned a new collaborator.
