### ISSUE TITLE
Translate CONTRIBUTING.md to Croatian

### ISSUE THREAD

**Issue by InternautNeven** [rchain/bounties#382]
Measure of Completion: 
- [x] Create CONTRIBUTING_HR.md file translated to Croatian language.

Suggested Budget: $250

Collaborators Work:
- @InternautNeven
- @MarioPolo
- @tgrospic

**Comment by MarioPolo** [comment]
Great ! 🎉

**Comment by tgrospic** [comment]
:+1:

**Comment by tgrospic** [comment]
@lapin7 can you check why @MarioPolo and I are not listed for voting in the bounties document on this issue? Also there is a vote for an empty name and from an empty name.

Should commenting on the issue fill the required fields in the bounties document?

**Comment by lapin7** [comment]
​They can add B&R again
https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=60903965&range=A246:Z246
https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=294454559&range=C3378:P3390
​

--
Cheers,
HJ
