### ISSUE TITLE
Argument: Markdown as a small barrier of entry or suggestion

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#383]
**Argument**: Make Markdown a barrier of entry or at least a suggestion (to learn) for the rchain/bounties members.
**Why**: It's **very** easy to learn and it will show **will** for learning, which to me show's a lot in a person. Education is a big part of RChain.

**Suggestion**:
- **Markdown Spec(ed)**: http://commonmark.org/
- **Tutorial**: http://commonmark.org/help/tutorial/

**Comment by pmoorman** [comment]
I'm not sure, but isn't just even using the buttons on the interface here enough?

**Suggestion:** 
We should phrase this issue positively:

"Encourage people to format their comments, so it's easier to digest for others"  or something like that

**Comment by ICA3DaR5** [comment]
@pmoorman This ^^
