### ISSUE TITLE
Create working group for "ideas and tools for governance processes"

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#385]
The purpose of the yet-to-be-named working group fronted by Cathy Henderson is separate from the "welcoming new members" working group. 

It's purpose (afaik, and this is still being formed) seems to be to develop proposals (directed towards [TBD]) for governance processes. An example would be evaluating potential tools and processes the coop could use to generate and vote on a ballot at the annual members meeting.

Cathy has started to organize us over email, we are planning our first meeting currently over [this doodle poll](https://doodle.com/poll/3t3idctvg883cztq).

The hope would be that the work that we do may be applicable not only at the "annual members meeting" level, but that we would be able to present ideas of organization for other committees or working groups to use.

**edit** (@dckc): Cathy writes:
> This group would help set up governance systems for the co-op (which would include the requirements for proposals, voting, requirements for tools, and ultimately how to implement (short and long term), in addition to help clarify the principles/culture of the co-op).

**Comment by iamnathanwindsor** [comment]
Great, I'm glad to help with this. I'll be posting as many notes as I can over the next couple of days.

**Comment by dckc** [comment]
@drbloom did you expect the "welcoming new members" group to be separate from the group Cathy H. is forming? That's a bit of a surprise, to me.

**Comment by dckc** [comment]
Since the proposed WG scope includes setting coop-wide policies, be sure to add

  - [ ] coordinate with officers

to the issue description.

**Comment by Jake-Gillberg** [comment]
I'm not sure that the scope includes setting coop-wide policies, but developing suggestions

**Comment by dckc** [comment]
OK; being explicit that the WG will be developing proposals is good. Even better if it's clear where the proposals will be directed. (e.g. "to the officers" or "to the board" or "to the board and/or officers" or "to the executive committee" or whatever)

**Comment by tcezi** [comment]
@bloom this is a good progress. I would like to assist.

**Comment by pmoorman** [comment]
@Jake-Gillberg @drbloom @dckc Do we really need more processes and tools for governance?

In my opinion, **the main thing we need is more transparency / clarity,** so people can work with what's already there.

I think adding more processes, layers & tools will make things only harder, not easier.

**Comment by dckc** [comment]
I think some more tools are likely to help; in particular, a petition system (#380) and a trust metric (#375). And the introductions survey (#222) seems to be a useful tool.

But most importantly, I think we need to collect experience from actually bringing on new members (#294, #295). I just chatted with @drbloom and it seems likely that one of this new group's first agenda items will be identifying people to help him with the new member KYC process.

**Comment by Jake-Gillberg** [comment]
@pmoorman To add to dckc's points: It is currently unclear how items make it to the ballot for the annual members meeting, and how members express their votes on the ballot. Last year the vote was conducted via survey monkey. I imagine that as we grow and more contentious issues make the ballot, we will want to add vote privacy and verifiability to our solution.

**Comment by jimscarver** [comment]
Loomio has rich decision making tools and I think we can use it to bootstrap our future decision processes. It is certainly worth experimenting with it.

The consider.it tool that was used quite successfully for The DAO is worth experimenting with. I've put considerable effort in seeding https://diglife.consider.it with principles and possibilities. It is said that when people share common principles and rally behind a possibility effective self-organization happens.
Please give it a try. Your input will be valuable to the experiment.

**Comment by dckc** [comment]
@Jake-Gillberg I see you added this to a github project; that suggests some notion of project completion. Do you have a sense of what that looks like?

In this repo there has been some mis-use of projects as buckets / categories, with no clear completion target, which I am [deprecating in favor of labels](https://github.com/rchain/bounties/issues/105#issuecomment-357788709).

**Comment by Jake-Gillberg** [comment]
@dckc Jim has been leading a group that has been organizing itself using the "O> Governance Working Group" project. I placed this issue on the project to notify anyone who may be monitoring that project that we are re-grouping and redefining what such a working (or interest) group may look like.

I agree with the preference to move away from "projects as buckets" to labels. I will remove this issue from the project once we meet and sync up this week.

**Comment by Jake-Gillberg** [comment]
Closing, as this group seems to have cemented.

**Comment by dckc** [comment]
For reference, the [#working-groups](https://discordapp.com/channels/375365542359465989/416248459503468544) channel shows:
 - **Governance WG** - Contact: @jimscarver: & @catH:  
   RGov Log GDoc - https://goo.gl/aWPFMs
