### ISSUE TITLE
guide lightning talk session at RChain Governance Forum

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#386]
- [x] solicit lightning talks
 - [x] emcee the talks
 - [ ] gather and publish / index presentation materials

## Speaker List
 1. Jim Whitescarver (@jimscarver) [collective intelligence best practices](https://docs.google.com/presentation/d/1qFK10rFcCiBO72aeSFIfII0e1TeIXDKgZqwVlP-wREk/edit) 
 2. Kenny Rowe
 3. Kit Blake
 4. Jake Gillberg [Properties of Secure Voting Systems](https://docs.google.com/presentation/d/1rhD1tp9Zem6CEuD-Nbi1V2Urv5mF1qzKyl-A1QkjyuU/edit#slide=id.g30ca358298_0_852)
 5. Jonathan Kochmer
 6. Tim Bansemer [Successful governance through strong cultivated values and open processes](https://docs.google.com/presentation/d/1m9OTcUiVhOFAMq2TbB1K_SsJg_VNqF1PukLPD85SzlM/edit#slide=id.p)
 7. Dan Connolly - Trust Metric
 8. Jim Whitescarver (2)
 9. Dan Connolly - RChain Life

----

I hope to work toward a record of the whole meeting more in the style of W3C or Apache or ECMA-262.
(_also: I want the governance forum to have its own page; the current /events URL suggests that when the next event comes along, all the stuff about this event is going to get deleted_). I [pinged vlad](https://twitter.com/dckc/status/965342007664062464), who, at the closing brunch, encouraged scribes to share. But he didn't know of a point person.

FYI: Tai Chi instructor from Saturday, Viola Brumbaugh, referred us to videos from https://wise-orchid.com/ for follow-up (thanks to Tamara Rogers for the pointer.)

**Comment by dckc** [comment]
video:

 - [Rchain Governance Conference Day 2 Session 1](https://www.youtube.com/watch?v=Mmkae9E93tk&feature=youtu.be&t=6393)

ack: allanc

**Comment by dckc** [comment]
@jimscarver point me to your slides, please? especially that list of best practices.

**Comment by dckc** [comment]
@ian-bloom how about a new page / folder under https://www.gov.rchain.coop/co-op-governance for documents from the Feb Gov Forum?

**Comment by ian-bloom** [comment]
gov.rchain.coop is just a Co-op GSuite account for hosting mailing lists and shared GDocs.
I'm working w/ Jeremy Busk on using member.rchain.coop as a general document store.

How about a member.rchain.coop/2018-Gov-Forum WP page for:
1. Initially listing the Gov-Forum documents hosted in the doc-store (docs.rchain.coop)
2. Later curating the list as a nicely edited page

**Comment by dckc** [comment]
I think most forum scribes used gdocs; integrating them into a gsuite site (as you/we did for the executive committee) seems a lot easier than porting them to wordpress. But I suppose a wordpress page could point to them.

I think the cat is out of the bag w.r.t. a "general document store". The community is already using both gdocs and github. And lots of other stuff.

**Comment by dckc** [comment]
The lightning talk presentation materials that I have are now in a folder under [2018-gov-forum](https://www.gov.rchain.coop/2018-gov-forum).

I also added [RChain Governance Forum](https://drive.google.com/drive/folders/1on-U4ZEy1Sc155bDYNazTXLcYowlXnRR) notes by Nathan Windsor.
