### ISSUE TITLE
How to do CRUD apps (e.g. budget / rewards) on RChain

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#387]
I'm used to building CRUD apps using SQL (e.g. #260). SQL records can be seen as tuples. I hope to find out how to use the rchain tuplespace or other parts of the storage layer  for this sort of thing.

**Comment by zsluedem** [comment]
I am kind of confused about what you are looking for here.What do you mean about "rchain tuplespace"?

**Comment by dckc** [comment]
I'm not exactly sure either. ;-)

But see things such as https://github.com/rchain/mobile-process-calculi-for-blockchain/blob/master/actors-tuples-and-pi.rst

**Comment by David405** [comment]
@dckc, please can make it a little clearer what you intend to here, I am more drawn towards development issues.

**Comment by David405** [comment]
@dckc, please make it a little clearer what is intended to do here as I am sort of interested in this since I am naturally drawn to development issues

**Comment by dckc** [comment]
I took the business rules from CONTRIBUTING.md and the spreadsheet and implemented them in SQL; much of it is views, which is a form of functional programming:

```
create or replace view issue_budget as
select issue_num, title
    , case when voter_qty >= 3 then budget_provisional else null end budget_usd
    , budget_provisional, voter_qty, voters, pay_period
from (
	select bv.issue_num, i.title
	     , count(distinct bv.voter) voter_qty
	     , group_concat(bv.voter separator ', ') voters
	     , round(avg(bv.amount), 2) budget_provisional
             , bv.pay_period
	from issue i
	    join budget_vote bv on bv.issue_num = i.num
            join admin_settings s on s.current_pay_period = bv.pay_period
	group by i.num, i.title
) ea
;
```
-- https://github.com/dckc/rchain-dbr/blob/master/bees_ants_schema.sql

I'm interested to learn what this would look like in Rholang.

**Comment by lapin7** [comment]
Me too.

**Comment by David405** [comment]
what is the possibility of creating a CRUD App using rholang as at the moment?

**Comment by zsluedem** [comment]
I am still not really confused about the thing you want to do.

SQL is a language to integrate with the database; They are `string`.

If you want to build an app with the Rholang. I think you should use a database like Mysql and you should use Rholang to implement the driver(like [this](https://github.com/mysql/mysql-connector-python)) to integrate with the database and then wrap it like a tool(package).

There is another way to do .It is to implement a database by Rholang inside the CRUD App you said.

**Comment by dckc** [comment]
I want to use the RChain storage layer rather than Mysql. In particular, I want to find out if the [storage and query][1] layer serves a similar role as mysql.

[1]: http://rchain-architecture.readthedocs.io/en/latest/execution_model/storage_and_query.html

**Comment by dckc** [comment]
moved to the forum
