### ISSUE TITLE
Blog post summarizing Governance Forum

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#394]
For someone who attended the Forum, it would be nice to summarize the conference into a blog post including links to the videos. 

The sooner the better as we are planning some press releases 

ETI - 1 Week

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

Measure of Completion:  
Suggested Budget:

_See CONTRIBUTING.md for details on budget and reward process._

**Comment by dckc** [comment]
This has been percolating since the event; it might have too much stuff packed into one item, but that's how my head feels too:

 - [MadMode: dreaming big at the RChain Governance Forum](http://www.madmode.com/2018/rchain-gov-forum-SEA.html)

**Comment by derek7272** [comment]
Blog post is here, sorry I guess I didn't do a good job in updating the reward or this github  https://docs.google.com/document/d/18Nw9Mb_YsmNeEw6BOiy8wnl11PSYy0gAltP37CKAXYU/edit

**Comment by dckc** [comment]
Derek that's an interesting article, but it doesn't look like it's prart of a blog. Do you keep a blog?

**Comment by derek7272** [comment]
I do, but not an active one. I think there was a bit of confusion about this item ... my understanding is @patrick727 added this as a github item so he could get a blog post he could eventually publish elsewhere? Perhaps I'm mistaken but I don't think it was meant to be, "write a blog post about RChain and the cooperative will pay you for it." This post was eventually used in the RChain member email list of March 6.

**Comment by dckc** [comment]
Ah. I see. Thanks.

**Comment by barneycinnamon** [comment]
I see this is still open. @patrick727, did you have a budget in mind for this? @derek7272, did you have a budget suggestion? I can't imagine we are going to solicit new accounts of the Governance Forum now unless they are more retrospective pieces situating the Governance Forum in a larger context, so let's get any relevant rewards into the bounty system and close this issue.

**Comment by derek7272** [comment]
maybe like $300? $200 for the author (me) and $100 for editors?

**Comment by Viraculous** [comment]
@patrick727 I think this issue is past date. I am closing it but reopen if you have any thought around it.
