### ISSUE TITLE
Share Discord community building expertise with RChain

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#404]
For example: what does granting a friend request do?

cc @bconnolly

**Comment by David405** [comment]
Granting a friend request allows you chat with a person even when he is not a member of any of the servers you belong to. See http://www.forums.mkboards.com/threads/discord-what-is-it-and-how-do-i-use-it.26051/ for a detailed documentation on discord and you can check out discord developer documentation for a greater level of details

**Comment by dckc** [comment]
@David405 thanks. How much experience do you have with discord? What communities? If you have done community building on discord, perhaps you would like to share your experience? See also #403.

**Comment by dckc** [comment]
How do I prune the list of channels on the left to just the ones I want to track?

I'm used to IRC, where you `/join` the channels you want to. Just because somebody creates a channel doesn't mean it shows up on my screen.

**Comment by drbloom** [comment]
Channels can be nested into "Categories", but unfortunately, users have little control over which channels are displayed. I suggest we archive many of the channels, change channel names, and streamline.
There is just not enough space in Discord's channel listings.

**Comment by AyAyRon-P** [comment]
@dckc Here is what I found out with the help of someone at Discord....

After you MUTE a channel, right click a channel and select MUTE, you can go up to the top drop down arrow, click it, and then select HIDE MUTED CHANNELS

This will clean up your list. 
![hide_muted_channels](https://user-images.githubusercontent.com/35570702/36648896-767624c8-1a5e-11e8-9bb7-fde2fe7b4897.PNG)
![drop_down_hide_muted_channels](https://user-images.githubusercontent.com/35570702/36648897-7689219a-1a5e-11e8-9bf2-d98ff78cea6c.PNG)

**Comment by AyAyRon-P** [comment]
@dckc 
For the sake of the Pub Bounty/Budget and completion are you looking for a more formal guide or were there any FAQs you need answered?

**Comment by dckc** [comment]
I'm looking for guidance from someone who has done community building using discord.

In particular:
> [FlashingFire][] is the creator and administrator of the PM Snake Discord.

cc @bconnolly

[FlashingFire]: https://www.ssbwiki.com/Smasher:FlashingFire

**Comment by AyAyRon-P** [comment]
Took a look at that server and have a much better example for you:

**Comment by AyAyRon-P** [comment]
Ah okay - that helped! I took at look at the example you sent, and that's a basic gaming server. I'm part of a large gaming community known as PixelPub: http://www.pixelpubgaming.com/

Here is their discord server: https://discord.gg/uw3PMqV

This server utilizes multiple bots that can be incredibly helpful: https://botlist.co/platforms/discord
Probably one of the best is Dyno Bot for moderation of the server but there are also ones for "fun" if we want to include that. 

If you want I can reach out to the owner of the community and see if he's willing/able to help share his knowledge.

**Comment by pmoorman** [comment]
**this issue could do with a more S.M.A.R.T. scope!** 

As a suggestion:

- Maybe we could use "how Discord works" entry in either the wiki or some other place
- Another issue I can anticipate is figuring out which channels can be removed / replaced, to keep Discord organized
- ... not to even get started on the fact that we have a 2nd, not-known-to-most Discord "Use Cases" server

@dckc
