### ISSUE TITLE
M> RChain Jingle

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#408]
The goal of this is to come up with a simple jingle like

"nationwide is on your side"

but for RChain, and then we could use it as what offically starts the debriefs. 
we have so many awesome musicians in teh community this should be a fun one.

Proposed bounty 1500 USD in RHOCs

**Comment by ResonanceXX** [comment]
The jingle could be played against a backdrop of an animated manipulation of the RChain Logo. Effected to maybe dart across, shimmer or bounce around. Even twist.

This definitely should be fun. (clears throat!)

**Comment by jiyuxuan1944** [comment]
We can make this kind of tone with a synthesizer.

**Comment by lapin7** [comment]
@jiyuxuan1944 please add here a link to a draft synthesizer tone

**Comment by OPNO** [comment]
Hi Patrick, I'd love to take a crack at this. How long should it be? Should it be more of a stinger than a jingle?

**Comment by dckc** [comment]
@TrenchFloat for some words, check out the branding ideas in #371.

**Comment by jiyuxuan1944** [comment]
@lapin7 I use my Korg synthesizer and SONAR, made a few melodies.Tell me more details.
[jingles.zip](https://github.com/rchain/bounties/files/1754373/jingles.zip)

**Comment by patrick727** [comment]
Im a fan of the tune @dckc just intro'd our meeting with this morning. 

Not sure if it was original but it was catchy.

**Comment by ResonanceXX** [comment]
A lot of copy right issues could be mopped up by seeking appropriate approval for use. 
Catchy is very good. Something that lingers in the mind, and resonates in the heart. The tune could be altered to prevent copy right issues. 
We want a blind person to know "This is RChain!"

Sent from Yahoo Mail on Android 
 
  On Sat, 24 Feb 2018 at 17:29, patrick727<notifications@github.com> wrote:   
Im a fan of the tune @dckc just intro'd our meeting with this morning.

Not sure if it was original but it was catchy.

**Comment by ottermagically** [comment]
I might submit some ideas in coming week.

**Comment by AyAyRon-P** [comment]
@TrenchFloat I like the intro/outro. Remind me of a Radio/Pod cast jingle.

**Comment by ResonanceXX** [comment]
https://drive.google.com/file/d/1sJy8Qr1J14vURib2Ki_3hWrX6ldTZCjh/view?usp=drivesdk


This has a slight jingle opening. 
But all tunes are primal property. So no legal "wahala"
Also tunes can get better, with adjustment to the #keys.

**Comment by dckc** [comment]
@TrenchFloat @mjreitz we forgot to add the vroom rev sound. Go ahead and
add it?

**Comment by ResonanceXX** [comment]
Like a reving car?  @dckc? 

I did this before seeing this message. 

Improvement on the others. 

https://drive.google.com/file/d/1VEdvgFtXCDsMcEdp78A4o3snAAOxNba9/view?usp=drivesdk

**Comment by OPNO** [comment]
Hey all, just wondering whether submissions are still being accepted? (BTW, Dan and Patrick, this is Darryl - we met in Seattle).

**Comment by dckc** [comment]
As far as I know, yes, @OPNO . Join the fun!

**Comment by Ojimadu** [comment]
@ResonanceXX Your links requires access permissions

**Comment by ResonanceXX** [comment]
Hi @Ojimadu I always grant access to coop members that request access to the file. Only because I am not clear on how to remove the restrictions on google drive.
--------------------------------------------
On Sat, 3/10/18, Ojimadu <notifications@github.com> wrote:

 Subject: Re: [rchain/bounties] M> RChain Jingle (#408)
 To: "rchain/bounties" <bounties@noreply.github.com>
 Cc: "Chris Ken" <kenechukwuoliaku@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Saturday, March 10, 2018, 10:34 AM
 
 @ResonanceXX Your
 links requires access permissions
 
 —
 You are receiving this because you were
 mentioned.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Ojimadu** [comment]
Grant access to rchain@googlegroups.com so all members can access it.

**Comment by ResonanceXX** [comment]
Okay. I have created a folder with all pitches. And have added The Coop to access freely. Thank you. Feel free to modify. Cheers!
--------------------------------------------
On Sat, 3/10/18, Ojimadu <notifications@github.com> wrote:

 Subject: Re: [rchain/bounties] M> RChain Jingle (#408)
 To: "rchain/bounties" <bounties@noreply.github.com>
 Cc: "Chris Ken" <kenechukwuoliaku@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Saturday, March 10, 2018, 10:59 AM
 
 Grant access to rchain@googlegroups.com
 so all members can access it.
 
 —
 You are receiving this because you were
 mentioned.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by OPNO** [comment]
Hello all,

Here's a stinger as well as a version with the stinger going into a groove that could work under dialog.
I can change any elements if need be and my partner Tracy can sing any proposed new words etc.
Hopefully it works to attach the zipped file here: 
Cheers!
Darryl
[RChain Stinger - Darryl Neudorf.zip](https://github.com/rchain/bounties/files/1799797/RChain.Stinger.-.Darryl.Neudorf.zip)

**Comment by Ojimadu** [comment]
@OPNO Great stinger you've got. Good quality. My favorite so far.

**Comment by leithaus** [comment]
i've been planning on doing a version of Rawhide, but with Rholang substituted for "rollin'".

rholang, rholang, rholang -- keep those contracts rholang - RChain!

https://www.youtube.com/watch?v=qCRae5mRoRE

**Comment by leithaus** [comment]
Anyone want to help me rewrite the lyrics?

**Comment by ResonanceXX** [comment]
@Leithaus I can give it a try. 

Sent from Yahoo Mail on Android 
 
  On Sun, 11 Mar 2018 at 22:06, leithaus<notifications@github.com> wrote:   
Anyone want to help me rewrite the lyrics?

**Comment by OPNO** [comment]
Thanks @Ojimadu . I can change any elements at any point to get it closer to the target. Here's a password protected link: https://we.tl/xpd807lL54 password: rholang       @Leithaus - love the rawhide angle - just so wacky it works!

**Comment by pmoorman** [comment]
so.... do we have a jingle that we all like?  

Is this issue still relevant? Can it be closed off?  Do we need more _me_  to pick up the guitar (I hope not!)?

**Comment by dckc** [comment]
My impression was that the goal was to use the jingle in the weekly updates. I haven't seen that happen, so I don't think we're done.

@Ojimadu endorsed the March 10 submission from @OPNO.

The Feb 25 submission from @TrenchFloat and company got support from @patrick727 (@PatrickM727 ) and @AyAyRon-P . That's two of the Marketing guides; is that critical mass? @leithaus didn't concur; rather, he wished for rholang-Rawhide. I hope the guides will sync up and give us some direction.

**Comment by pmoorman** [comment]
Looking at this issue again.

@dckc you said 

> I hope the guides will sync up and give us some direction.

I don't think our guiding role should be to make decisions on jingles. If anyone wants to push this jingle, maybe let's do a vote/contest somewhere?

I'll slap on the `Needs SMART-objectives` label for now, because clear next actions are missing

**Comment by dckc** [comment]
We did a vote. I enumerated the results above.

And I think it *is* up to the guides to clarify whether RChain wants a jingle for the weekly updates or not. At least @Patrick727 who opened the issue should say whether he still wants it.

**Comment by TrenchFloat** [comment]
I asked Patrick on discord if he's still interested in a jingle.
DM from Patrick:
"Let it die.
But it would be nice"

:(
