### ISSUE TITLE
O> Checkmating multiple accounts by coop members

### ISSUE THREAD

**Issue by Keaycee** [rchain/bounties#409]
There have been dialogues about coop members having multiple membership account to enable their malicious act other than a helpful contribution to RChain cooperative. I think we can come up with an effective  measures to combat double membership account by coop members. 

**How do we checkmate accounts?**

**TIPS**
- 1. Reviewing all coop members accounts that signed up

- 2. Reviewing each accounts and it's means of identification (I.D cards)

- 3. Verification of coop members every month before getting a reward. Members can be group batch after batch for a video verification with a corresponding means of identification (I.D cards)

- 4. Checking accounts with same Eth addresses

- 5. KYC form.

The above tips is only a suggestion, perhaps there maybe a better ideas.

**Comment by BelovedAquila** [comment]
@Keaycee that's a nice suggestive  tactics to check mate bad actors of multiple accounts and I think it would go a long way in achieving this #391 more effectively.

**Comment by Biseny** [comment]
@lapin7 request a Github collaborator role . My email ：Biseny@qq.com

**Comment by kaka56** [comment]
@Biseny Great you want  to collaborate.
  please friend ,
- Join https://groups.google.com/forum/#!forum/rchain
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by dckc** [comment]
If you start doing this and have any experience to share, @Keaycee , please do.

It's interesting to think through these scenarios, but I doubt the suggested process is cost-effective. If you think through a budget for this, you may well agree.

I chatted with @kennyrowe about KYC and learned that the requirement is not 100% prevention of fraud, but just a reasonable due-diligence, sufficient to keep fraud from being _cost effective_.

I don't think it's important to prevent multiple github accounts for the same person. I do think it's important to prevent multiple coop memberships for the same person. I believe that's in the membership agreement, so the courts would back us if necessary. Meanwhile, discord OAuth seems a cost-effective solution (see #279, #260).

**Comment by dckc** [comment]
With no movement toward a SMART objective in a week, I'm closing this.

**Comment by Keaycee** [comment]
@dckc The objective of this thread is not preventing multi account on github, but preventing multi coop membership. 

Why was the comments of @Biseny and @kaka56 deleted?? @dckc

**Comment by dckc** [comment]
I still see no movement toward a Measurable, Achievable, Realistic, Timely objective.

Again, feel free to re-open this issue **if you have experience to share**.

As I already explained, the comments were deleted because they were not relevant to this issue; they were discussion of getting access to the repo and the google drive folder.
