### ISSUE TITLE
RChain vs. Ethereum vs. Cardano

### ISSUE THREAD

**Issue by iamnathanwindsor** [rchain/bounties#412]
Hi All-

Can someone explain the differences between RChain, Ethereum and Cardano?

Specifically:

1.) What advantages does a correct by construction language like Rholang have over others like Cardano's [Plutus](https://whycardano.com/#scalability)?

2.) I've heard Greg say multiple times that Rholang has concurrency "built into it", but why does it matter if Ethereum is "bolting on" plasma or polkadot in its effort to scale? What could specifically occur in both systems?

3.) The DAO hack would be caught with Rholang due to its behavioral type system and formal verification. How is RChain's "Correctness" feature different from Cardano's [Plutus](https://whycardano.com/#scalability)?

Thank you~
N

**Comment by kirkwood** [comment]
Thanks for the question. See https://forum.rchain.coop/developer/rholang/rchain-vs-ethereum-vs-cardano/

**Comment by iamnathanwindsor** [comment]
@kirkwood Thanks for the feedbac, though that is my own post I made today that I'm trying to move things over to the forum. 

Does anyone have an answer to this?

**Comment by dckc** [comment]
Kent's answer looks pretty good.
