### ISSUE TITLE
Authenticate bounty Collaborators using Github OAuth

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#414]
part of #260

see also #413 discord oauth for verifying members

related work: Google OAuth with xataface: https://github.com/dckc/hh-office/tree/master/Auth/gapp

cc @hyperevo

**Comment by dckc** [comment]
Whatever version the service providers (github, discord) use. I haven't checked. OAuth 2, I suppose.

**Comment by BelovedAquila** [comment]
Alright, please is the Github OAuth aimed at authenticating  or authorizing, because I use to know OAuth to be a kind of pseudo authenticator not basically for authentication, though an exception if a new version which does that is actually onboard

**Comment by hyperevo** [comment]
I have implemented a bare bones github oauth. Progress is moving ahead nicely. I forked the original bounty website code here that includes xataface and github oauth: https://github.com/hyperevo/rchain-dbr

**Comment by hyperevo** [comment]
I updated the repo. Did a lot more testing and updating to improve security. Github Oauth integration is fully functional now. The xataface use menu system has been updated to allow login, logout, and coop member verification via discord oauth.

**Comment by dckc** [comment]
@hyperevo writes:
> Ian thinks we need to get email addresses. -- [March 4][1]

I'm pretty sure we don't. @ian-bloom would you please clarify?

Even if we need email addresses, I doubt we should get them from github.

[1]: https://github.com/hyperevo/rchain-dbr/commit/c29f464c5e4c96d5967e091826a1594e5c7cd57c#diff-9269a89183e54685b10d200d96377227R17

**Comment by dckc** [comment]
@hyperevo the login workflow does a lot of what I expect, but when it gets back to `.../github_auth_callback.php?code=...` I get **could not write to database**.

The new code is deployed at http://rchain-dbr.nfshost.com/rchain-dbr-beta/

**Comment by dckc** [comment]
We're just about ready to claim victory on this one.

The `session_token` column is too visible; that seems like the one remaining **critical** issue.

I re-worked the way the SQL query is built:

 - use bind_param to avoid SQL injection https://github.com/dckc/rchain-dbr/commit/57c9728f0a89a93f0fc5527baea087fa0b0c79c9

I don't have the discord part wired up yet, though.

**Comment by dckc** [comment]
The `session_token` is hidden now.

https://github.com/dckc/rchain-dbr/commit/6ee5030156ea05ee6ede3bc6bd0fb685b77c53e1
