### ISSUE TITLE
Sync bounty repo users, issues with Web app

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#416]
part of the app designed in #260 

prototyped in [dbr_norm.py](https://github.com/dckc/rchain-dbr/blob/master/dbr_norm.py) Feb 2 fc16119

## Use case: Sync users, issues tables with github repo

  - [x] ops manager or any other user can sync on demand by pushing a button
  - [x] noone can edit users; sync from github is the only way to update
  - [x] noone can edit issues

postponed:
  - [ ] _system automatically syncs periodically_

**Comment by dckc** [comment]
I'm close to done on this; just need to tidy up deployment.

[social_coding_sync.py](https://github.com/dckc/rchain-dbr/blob/master/social_coding_sync.py) e99389c

**Comment by dckc** [comment]
The sync mechanism is now incremental (thanks to a technique I picked up from @hyperevo ).

I did a manual sync just recently. I don't plan to blow away all the data any more.

**Comment by Ojimadu** [comment]
@dckc  @hyperevo Would it be possible to add a form of sorting on issues on the web app? Like newest first, oldest first or highest budget etc.?

**Comment by kitblake** [comment]
Last time I looked it was laborious to get to the recent issues, so yes, +1 on sorting and why not make newest first the default?

**Comment by dckc** [comment]
All these sorting features come with xataface out of the box. Just click on the column heading, as is conventional on many web sites.

I'm not sure how to make newest the default, but there is a "recent issues" link on the homepage that goes to the list sorted newest first.

**Comment by dckc** [comment]
We now have **ops manager or any other user can sync on demand by pushing a button**.

https://github.com/dckc/rchain-dbr/commit/d0e4e028a3191402e20fb21e3f226727adffb477

I think _system automatically syncs periodically_ is not critical.

**Comment by dckc** [comment]
oops; I don't think the current design revokes privilege when appropriate
