### ISSUE TITLE
Use Github labels rather than title prefixes O> M> etc.

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#417]
I'm still not clear on why we have these **O>** prefixes. Whatever system uses them, let's get it to use labels instead so we can quit cluttering up the issue titles.

@lapin7 wrote [Feb 2][]:
> A cell calcs M> to Marketing
> And it's used for bookaccounting purpose

The convention dates back as far as [Dec 8][].

[Feb 2]: https://github.com/rchain/Members/issues/279#issuecomment-362682280
[Dec 8]: https://github.com/rchain/Members/issues/165#issuecomment-350388332

cc @kaka56 @lapin7

**Comment by AyAyRon-P** [comment]
@dckc I took a look at this and it's an easy fix, but it's a manual task. Let me know if you want me to make the changes.

**Comment by dckc** [comment]
You took a look where? What would you change? Did you find the system that consumes the prefixes?

**Comment by AyAyRon-P** [comment]
It's done manually when a person enters in the ISSUE name.

**Comment by dckc** [comment]
That's the (manual) system that **produces** the prefixes. The fix has to go in the system that **consumes** the information.

**Comment by dckc** [comment]
@lapin7 what is the system that consumes these prefixes?

**Comment by lapin7** [comment]
It’s self invented. In the spreadsheet there was a formula that converted M> into Marketing. 
Nothing special.

**Comment by dckc** [comment]
So there's no need for these prefixes any more? yay!

**Comment by dckc** [comment]
I'm sort of experimenting with **duplicate** to mean "not worth any reward".
