### ISSUE TITLE
Onboard @theneverafter, product manager, ethereum miner, and front end developer

### ISSUE THREAD

**Issue by theneverafter** [rchain/bounties#420]
*Inspired by #293 and #294*

### How I got involved
I did some LinkedIn stalking and saw that my friend and ex-colleague @kirkwood was working on RChain, so I decided to check it out. I first got into crypto when I did some casual mining of Bitcoin/Litecoin/Dogecoin with my gaming PC back in 2013. More recently, I build a dedicated mining rig for Ethereum. This led me further down the rabbit hole, and I've been spending more and more of my free time learning everything I can. I'm looking for a way to get more deeply involved and start contributing to a project, and after all I've learned about RChain, I believe this is the best place for me to do that. If we can deliver on the vision as described, I think it will have a massive impact on the world.

### What I've done so far
- [x] Filled out the [skills inventory](https://goo.gl/ffWXzD)
- [x] Read Contributing.md (and made a PR to improve it slightly)
- [x] Signed up for membership, paid the $20, and was verified by Ian
- [x] Joined the Google Group
- [x] Became a Github collaborator
- [x] Watched the budget allocation video

### What I still need help with
- [x] Finding/creating a first issue to contribute to (like @pmoorman and his marketing audit)
- [x] Understanding how issues are "approved" by the community for work
- [x] Understanding the big picture / roadmap / major milestones on the way to RChain launch

**Comment by dckc** [comment]
There's no approval step before starting work. You just start and take the risk that you'll be rewarded when you're done. Does that make sense?

> **Be a self-starter** :: because there is no boss, nobody is going to tell you what to do. Being a RAM is much more like being an _entrepreneur_ than it is like being a _employee_. -- [Welcome to the Bounty Program](https://github.com/rchain/bounties/wiki/Welcome-to-the-Bounty-Program)

**Comment by dckc** [comment]
Oh... for working on [core rchain/rchain bounties from Jira](https://rchain.atlassian.net/browse/ROS-271?jql=labels%20%3D%20bounty), it's best to coordinate with @MParlikar (cf. #184).

**Comment by BelovedAquila** [comment]
@theneverafter Welcome friend, for further information,don't know if you had come across  [CONTRIBUTING.MD]  (https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md) it would go a long way in helping you understand better.

**Comment by theneverafter** [comment]
@dckc What about closing work though? Who can review and merge pull requests?

**Comment by dckc** [comment]
Anyone with contributor status (which is pretty much everyone) _may_ review and merge pull requests.

Lack of experience with git, however, means that the number of people who _can_ review and merge pull requests is fairly small. :)
