### ISSUE TITLE
Add a working Formatter for Rholang-idea

### ISSUE THREAD

**Issue by AbnerZheng** [rchain/bounties#422]
Since @dckc suggests, I create this issue for apply for budget for `Add a working Formatter for Rholang-idea`. 

The function preview:
![image](http://g.recordit.co/aaqkN11t6W.gif)

The PR is https://github.com/tgrospic/rholang-idea/pull/2.
Measure of Completion:  
Suggested Budget:

**Comment by lapin7** [comment]
I think this is awesome and deserves a budget and reward
https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=60903965&range=A273:Q273

422 |   | Add a working Formatter for Rholang-idea |   | $ - | $ - | $ - | ⍴ - | $ - | OPEN | 0 |   |   | AbnerZheng | 0 |   | tgrospic
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by dckc** [comment]
Yes, this looks like good work. I wonder if we could get some time in Greg's weekly update for a demo. (See also #380)

**Comment by lapin7** [comment]
I will try to get some demo time from Greg

**Comment by David405** [comment]
@AbnerZheng, kindly comment your discord username, I would like to have a chat with you

**Comment by dckc** [comment]
@David405 a good place to connect github names to discord names is the Introduction survey results in #222. I guess I should make them easier to find...

**Comment by AbnerZheng** [comment]
@David405 I have the same name with discord.

**Comment by AbnerZheng** [comment]
@tgrospic @lapin7 @dckc 
It is a big PR, you can view the commits in https://github.com/tgrospic/rholang-idea/pull/2/commits. It takes me about 12 days to finish the job. The tuning of formatter style take a amount of time. 
So I apply for 3800$. 
Can I have your vote?

**Comment by tcsiwula** [comment]
What is the Budget for this issue?

**Comment by dckc** [comment]
yes, you have my vote, @AbnerZheng ; however, presuming this gets some time on the weekly update, I voted to reward myself and @lapin7 a small part of the reward for getting it appreciated by a wider audience.

**Comment by AbnerZheng** [comment]
@dckc
Sure
