### ISSUE TITLE
M> Add git workflow section to chinese version CONTRIBUTING

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#423]
git workflow section has been added to the english version CONTRIBUTING file, and chinese version should also up to date.

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

Measure of Completion:  
Suggested Budget: $50(1 hour)

**Comment by yyh1102** [comment]
That's good! This will make contributing flow very convenient~

**Comment by AbnerZheng** [comment]
I have review the PR and help to merge it.

**Comment by yuhuanmocmoc** [comment]
good job!

**Comment by ICA3DaR5** [comment]
Could you please post the PR here so it's in a public view? Thanks.
