### ISSUE TITLE
M> 10-15 Media Outlets w/ Author Contacts

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#426]
Input 10-15 media outlets in which our targets would frequent. 

See ["Media Outlets" ](https://docs.google.com/spreadsheets/d/1M9kqbnYxotaOLtWOj7MWquE41KADZJLtwFdgDqtoEck/edit#gid=1863564439)in infleuncer spreadsheet

Target Audiences

#1 Mavens: Anarchist/Libertarians that are very well practices in multiple programming modalities, motivated by a systemic shift. 

Possible outlets: Hackernews, libertarian news, lambda-the-ultimate, and wherever @dckc frequents. 

#2 New Blockchain Devs: Inspired by the possibilities of smart contracts, mix of change-the-system motivations and money motivations, not as indepth in there knowledge. 

Possible outlets: subreddits, hackernoon, etc.

**Comment by decentralizebanksy** [comment]
Updated with 22 inputs. Includes publication, author's name, author's email, and author's twitter handle. Some email fields are n/a. 

https://docs.google.com/spreadsheets/d/1M9kqbnYxotaOLtWOj7MWquE41KADZJLtwFdgDqtoEck/edit#gid=1863564439

**Comment by dckc** [comment]
I can refine #238 for this purpose.

I'm unsubscribing from this broader issue.
