### ISSUE TITLE
What IT infrastructure for Co-op to expand operations?

### ISSUE THREAD

**Issue by ian-bloom** [rchain/bounties#428]
#### (Self-Hosted, and Open Source wherever feasible)

- [ ] Membership Database Credential Sharing
  - [ ] LDAP
  - [ ] OAuth2
- [ ] Multisig Management Tools, Procedures, & Training for Officers & Directors
- [ ] Hosting Infrastructure
  - [ ] IP block
  - [ ] Physical Server(s)
  - [ ] Container Architecture (LXD, Docker)
  - [ ] DNS
  - [ ] Backup
- [ ] Monitoring & Auditing
  - [ ] Crypto & Fiat accounts.
  - [ ] Servers & Services
- [ ] RChain.coop Site (https://rchain.coop)
- [ ] Membership Site (https://member.rchain.coop) - I favor Multi-language WordPress
  - [ ] Announcements
  - [ ] Account Management
    - [ ] Registration, Payment, & ID Verification
    - [ ] Payment Gateway for Credit Card & Crypto (replace current)
  - [ ] Blog
  - [ ] Bounty Budgeting & Reward System (See Issue #260)
  - [ ] Governance
    - [ ] Member Voting and Petitioning
    - [ ] Board, Committees, Working Groups
- [ ] Developer Site (https://developer.rchain.coop)
    - [ ] Developer Forum (https://forum.rchain.coop) _dev-forum_ might be better
- [ ] Email
  - [ ] @rchain.coop, @gov.rchain.coop, etc.
  - [ ] for Officers, Committee Chairs, and staff (at a minimum)
  - [ ] Newsletters (Self hosted MailTrain or use WP Plugin)
- [ ] Notarization (DocuSign or Blockchain based)
- [ ] GSuite
  - [ ] Shared Document storage
  - [ ] Collaborative editing

**Comment by dckc** [comment]
re newsletter, see #219

**Comment by dckc** [comment]
gsuite sites could be good for #418

**Comment by dckc** [comment]
re GSuite for collaborative editing: their tools are hard to beat for the real-time aspects, but we should publish any useful results under our own domain name (#418).

For real-time work, the best tool I know to avoid using Google altogether is [etherpad on sandstorm][1].

[1]: https://apps.sandstorm.io/app/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60

**Comment by Viraculous** [comment]
@ian-bloom and @kitblake, Please whats the progress on this issue? I am persuaded to close it because it doesn't have a smart objective.

**Comment by dckc** [comment]
I'm reasonably confident @ian-bloom doesn't intend to track this issue here any longer.
