### ISSUE TITLE
M> Check rholang 101 syntax and semantics video subtitle and translate it to chinese

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#430]
Check rholang 101 syntax and semantics video's subtitle which offered in #347 by @zsluedem and translate it to chinese version after the correctness checking. 

Measure of Completion:  
Suggested Budget:  3200$ (0.4$ each word for both review and translation)

**Comment by Whisker17** [comment]
cool,and I think u should tick it in #347 to avoid duplicated work

**Comment by rjl493456442** [comment]
@Whisker17 Thanks for remind!

**Comment by rjl493456442** [comment]
@Whisker17 No worry, i already reference the #347. Anyway thanks for the remind!

**Comment by rjl493456442** [comment]
The reviewed and translated subtitles are all uploaded to [google drive](https://drive.google.com/drive/u/0/folders/1aHKERuxccZ1rd-da97mq916zO09UTx01). Welcome for double check.
