### ISSUE TITLE
Translate 'LADL Algorithm and Type Theory' into Chinese

### ISSUE THREAD

**Issue by AbnerZheng** [rchain/bounties#431]
We wanna to translate this subtitle(LADL Algorithm and Type Theory #347 ) into Chinese. 

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved （I will assign them later)
    - [x] at least two of them have high proficiency in Chinese
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation at stake: we all have  master degree of CS, and almost of us is doing the work of blockchain. 
       - [x] a track record of quality work on rchain bounties: #176 #242 #246 etc.
  - What about maintenance? 
    - [x] the source document is stable; further translation work is not expected

**Comment by ICA3DaR5** [comment]
@AbnerZheng This issue seems to have been payed for March. Is there any link you should post for the final work?

**Comment by ICA3DaR5** [comment]
No work has been uploaded here, and I haven't received a reply for 3 weeks. The translation guides are slashing all the voters.
