### ISSUE TITLE
M> Review English subtitle of 'Rholang Smart Contracts Lab'(part 1 and 2) and translate it into chinese

### ISSUE THREAD

**Issue by yyh1102** [rchain/bounties#432]
I wanna review and translate 'Rholang Smart Contracts Lab' referenced in #347 , including **part1** and **part2**

Total English words: 9297 (part 1: 6162  part 2: 3135)
Measure of Completion:  
Suggested Budget:  $2760 
(translation: $1860 ($0.2 per word)  review origin subtitle: $900 ($0.1 per word))

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation at stake: we all have master degree of CS, and almost of us is doing the work of blockchain
       - [x] a track record of quality work on rchain bounties: #242 #246 etc.
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected

**Comment by yyh1102** [comment]
Have completed translation work and upload the result subtitle to [here].(https://drive.google.com/drive/u/0/folders/1Ay8Fdmh9uvjnvDuhBW3gD2Y588BBRV-D). You can review them across. @AbnerZheng @rjl493456442 @yuhuanmocmoc @HaizhenZhuo

**Comment by yyh1102** [comment]
@lapin7 
I found out that this issue is not added to the budget in new bounty system. Does this issue not match or something else goes wrong?

**Comment by lapin7** [comment]
@yyh1102 this issue is available in "rewards"
https://rewards.rchain.coop/index.php?-table=issue&-limit=100&-action=browse&-cursor=365&-skip=300&-mode=list&-recordid=issue%3Fnum%3D432

**Comment by yyh1102** [comment]
@lapin7 OK,i see it. Thanks~
