### ISSUE TITLE
Translate this project into Portuguese from Portugal ptpt.

### ISSUE THREAD

**Issue by nunojesus** [rchain/bounties#433]
Hello,
If you are interested I can translate this project into Portuguese from Portugal ptpt.
If yes, is there any folder for translations?
Greetings!

**Comment by zsluedem** [comment]
You have to become a collaborator first. 
@BelovedAquila I think you are the one who manage the github collaborator, right?

**Comment by BelovedAquila** [comment]
you are welcome @nunojesus  to contribute in the translation projects of your stated languages, please start it up by following the details below. 
Please friend, 
- Join https://groups.google.com/forum/#!forum/rchain
- Accept https://github.com/rchain/Members/invitations
- Send your emailaddress + github name to ops@rchain.coop

**Comment by nunojesus** [comment]
Hello,
I made a request to join the https://groups.google.com/forum/#!forum/rchain

And I try to accept https://github.com/rchain/Members/invitations, but it shows something like this:  "Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account."

What should I do?
Greetings!

**Comment by lapin7** [comment]
Hi Nuno,

I've approved your request for joining googlegroups.
Yes the name of the rep has changed to https://github.com/rchain/bounties/invitations

Plz try again the github link

**Comment by lapin7** [comment]
It should be https://github.com/rchain/bounties/invitations
And you're already a member

--
Cheers,
HJ
