### ISSUE TITLE
Nominate a Treasurer

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#434]
The nominating committee has been instructed to nominate a candidate for Treasurer of the Coop in replacement of Lisa Rice, who has accepted a position elsewhere (still within the RChain ecosystem!).

The duties of the Treasurer as stated in [the bylaws](https://github.com/rchain/board/blob/master/Revised%20Bylaws%20(8-28-17).docx.pdf):

> The Treasurer shall be responsible for the keeping and distributing of all monies of the association, and shall keep accurate books of accounts of all transactions of the association. The Treasurer shall perform all such duties with respect to the finances of the association as may be prescribed by the RChain Board. Upon the election of a successor, the Treasurer shall promptly turn over to his successor all monies, property, books, records, and documents pertaining to his or her office or belonging to the association.

From Lisa, current holder of the position:
> A good candidate would be someone who is proactive, has enough financial and accounting knowledge to do the basics and run a effective monthly accounting process and to know when they need to reach out to an expert.  There is very little guidance on GAAP or IRS accounting for crypto currency so the person needs to be keeping in touch with experts who will hear what is coming out first.

Qualities that the committee is looking for in an ideal candidate:
- 6+ years of experience in public accounting
- CPA
- Experience closing financial books
- Experience managing excess cash
- Experience adding new employees / managing payroll
- Experience preparing and reviewing budgets
- Located in Seattle
- Entrepreneurial spirit
- Experience with cryptocurrency

We are currently scheduling interviews with candidates. The candidates that have been brought to the committee's attention are:

1. [Kate Gonsalves](https://www.linkedin.com/in/kate-gonsalves-3a804238/)
2. [Zeev Kirsh](https://www.linkedin.com/in/zeevkirsh/)

Interview questions live [here](https://docs.google.com/document/d/1CnBi4CCr83i0G4cD8JtpFA7t7vm4uBLwiyORfeXWu_0).

**Comment by Jake-Gillberg** [comment]
Some good marketing stuff for the position from Jacob:
> Seeking Responsible CPA for an Ambitious Global Blockchain Technology with $500M AUM

**Comment by Jake-Gillberg** [comment]
There is a discussion about compensation happening in discord's comp-committee

**Comment by Jake-Gillberg** [comment]
A good question that was raised: "how many years of experience are we looking for?"

**Comment by Jake-Gillberg** [comment]
It sounds like "Min 5-7 years experience in public accounting" landed well

**Comment by jbassiri** [comment]
LinkedIns:
https://www.linkedin.com/in/kate-gonsalves-3a804238/
https://www.linkedin.com/in/zeevkirsh/

**Comment by Dessertowl** [comment]
I dont think  Kate has the experience needed to manage the funds of a billion dollar company. The 4 jobs she has had that have lasted longer than a year are literally  working for David Otto. She  worked with Otto law from 2005 till May 2011. Otto law was essentially renamed to Martin Davis since in April 2011 when the SEC fined Otto for penny stock pump and dumps.  She was a treasurer for him during that example of Ottos below board actions.  Her experience  and company she keeps leads me to not trust her.
Otto Law       2005  >>2011
Otto Capital 2008 >> 2015
Otto law II    2011 >> 2015 
Beleza Cap   2011 >> 2018  Otto is her council 

Please prove me wrong.

**Comment by Jake-Gillberg** [comment]
comments from discord:
> kirkwood:: have we engaged a national search agency for it?
> kirkwood:: I'm having trouble telling if the Treasurer is just an oddly named CFO position or if it's simply the "bookkeeper" position.
> gigi:: This is a traditional controller role

**Comment by kirkwood** [comment]
Is there a reason we're not filling the CFO role instead? Any candidate will end up doing those duties anyway, since they must be done, and it seems reasonable to recognize that fact.
