### ISSUE TITLE
M>  Translate 'Go-To-Market Strateg' into Chinese

### ISSUE THREAD

**Issue by yuhuanmocmoc** [rchain/bounties#437]
We want to translate this subtitle(Go-To-Market Strategy #347 ) into Chinese.

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected

Suggested Budget: $900 (2969 English words and $300 for review, $600 for translation)

**Comment by ICA3DaR5** [comment]
Please post a link to the work done here!

**Comment by yuhuanmocmoc** [comment]
@ICA3DaR5  sorry, In two days, I will uplaod the subtitle after reviewing.

**Comment by yuhuanmocmoc** [comment]
Have completed the work of reviewing original subtitle and translation, and upload the result subtitle to [the google doc](https://drive.google.com/open?id=1MrARXFYUlFaIc0At-PmmRE-61LTRZdKK)
You can review them across. @AbnerZheng @rjl493456442 @HaizhenZhuo

**Comment by ICA3DaR5** [comment]
Could you please also upload it in an .SRT format so it can be used directly on the YouTube video?

**Comment by yuhuanmocmoc** [comment]
@ICA3DaR5 it's ok.

**Comment by ICA3DaR5** [comment]
Work seems to have been done here, although and .SRT file has been uploaded. Voters of this issue have been slashed on issue #453
