### ISSUE TITLE
Translate "Compiler Design, Cryptoeconomics" into Chinese

### ISSUE THREAD

**Issue by han014** [rchain/bounties#439]
Check "Compiler Design, Cryptoeconomics" video's subtitle  offered in #347 by @zsluedem and translate it to chinese version after English subtitle review.

I will complete it with @Whisker17 

Suggested Budget: 2000$ (0.2$ for each word)
Time: #about a week

**Comment by Whisker17** [comment]
We've finished translation and upload [here](https://drive.google.com/drive/u/0/folders/12Ffx1vjYo9XsYBllfNHci9xETlpG2KxD)

**Comment by Whisker17** [comment]
So this issue will be closed
