### ISSUE TITLE
Translate "Blockchain Business Requirements" into Chinese

### ISSUE THREAD

**Issue by Whisker17** [rchain/bounties#440]
I and @han014 have reviewed the crude subtitle and translated the "Blockchain Business Requirements" into Chinese #347 
Since the total word is 3166,I think the budget should be $634.
We will upload the reviewed subtitle and its Chinese version [there](https://drive.google.com/drive/u/0/folders/1TYCHiaqfPjixlxT_2dgWZWeKSdVRe5rK)

**Comment by han014** [comment]
That's good.

**Comment by ICA3DaR5** [comment]
Is this finished?

**Comment by Whisker17** [comment]
@ICA3DaR5  yes,we have uploaded [there](https://drive.google.com/drive/u/0/folders/1TYCHiaqfPjixlxT_2dgWZWeKSdVRe5rK),and I will close this issue later

**Comment by Whisker17** [comment]
Done
