### ISSUE TITLE
pro/con list on RChain vs. DAT vs IPFS

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#442]
context: https://twitter.com/nevali/status/968951172412444672

I want to know more about DAT. Maybe @MostAwesomeDude will teach me...

fielding 18 Dec is relevant re IPFS:
> Replacing resource addresses (URL) with content hashes, because you think they are more "decentralized", would be a great (old) idea if the only thing people wanted to link to were documents that never change. No, you can't rewrite the links.
https://twitter.com/fielding/status/942852215496105984

but see also [videos of collaborative editing with IPFS using CRDTs][1]

[1]: https://github.com/ipfs/research-CRDT/issues/7

**Comment by nevali** [comment]
for more context on DAT (I've played with a bit, but I'm not involved in the project):

https://datproject.org
https://beakerbrowser.com

and most interestingly…

https://beakerbrowser.com/docs/inside-beaker/other-technologies.html

**Comment by dckc** [comment]
lots of synergy with other-technologies:

> - Proof-of-work and global ledger distribution are inefficient.

check... RChain architecture is proof of stake

> - The requirement to use global consensus on all transactions results in a direct costs for operations in the form of transaction fees.

check... see RChain namespaces etc.

> - We believe Proof-of-work is wasteful, and we have ethical reservations about the expenditure of resources to sustain PoW.

check... "scalable; secure; sustainable" is one of RChain's mottos

> - We have concerns over governance models.

check: One of Greg's answers to "Why RChain?" was "Governance and blockchain can't be separated; I felt compelled to connect them." -- https://platform.coop/2017/schedule/breakout-panels-next-money-new-tech-for-new-finance

**Comment by flowpoint** [comment]
on ipfs from [rchain architecture docs](https://rchain-architecture.readthedocs.io/en/latest/execution_model/storage_and_query.html?highlight=ipfs):
>Why did RChain not select IPFS (InterPlanetary File System) for distributed memory? In addition to carrying centralization risks, IPFS uses a path to get to content, whereas SpecialK uses entire trees (and trees with holes in them) to get to content. IPFS has an intuitive path model, but that design begs the question on how to do queries. SpecialK started from the query side of addressing. Now, the RChain project can benefit from the IPFS work, including their hashing for addressing content, once the SpecialK query semantics are in place. SpecialK can also utilize a randomly generated flat key that has no correlation to the data.

**Comment by dckc** [comment]
Nether IPFS nor DAT seems to address the issue of economic incentives.

**Comment by dckc** [comment]
I'm unlikely to continue to pursue this.
