### ISSUE TITLE
O> Gov conf SWAG

### ISSUE THREAD

**Issue by wordsandstuff** [rchain/bounties#444]
# All
Every person who attends the governance meeting should revive moral boosting merchandise  . People will fly form all over and should receive some swag that they can take back with them to show off to their local blockchain communities . 

Measure of Completion: DONE  
Suggested Budget: 1650

**Comment by LiliNL** [comment]
Great. I will work on it.

**Comment by LiliNL** [comment]
@kitblake please add a comment.

**Comment by Keaycee** [comment]
@wordsandstuff please be clear about this

**Comment by wordsandstuff** [comment]
This is already done. The shirts have been created and distributed. :)

**Comment by kitblake** [comment]
We could change the title to "Gov conf SWAG"

**Comment by lapin7** [comment]
Changed Title to @kitblake 's suggestion

**Comment by ResonanceXX** [comment]
Swagger = Alternate Marketing! = You should all have a great time. Cheers

**Comment by pmoorman** [comment]
@wordsandstuff In an effort to keep Github issue list groomed: I'll close this issue, because it has already been completed!
