### ISSUE TITLE
FFI from Rholang to Apache Spark dataframes

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#445]
> Big data, financial analytics contracts gotta scream -- Greg at the Nov 2017 Developer Retreat

That boggled my mind, at the time, so I jotted it down to ask around about it.

The other day in #rholang, @birchmd wrote:
> Rholang will have a foreign function interface (FFI) which will allow lower level (and thus possibly faster) implementations of specific compute heavy functions. An obvious example for the blockchain use case being crypto functions like hashing and signatures. And similar core functionalities for AI applications, like matrix algebra and numerical derivatives, would be good FFI candidates as well.

This makes total sense.

It mostly answers my question about porting SQL business rules (#387) as well.

**Comment by Viraculous** [comment]
@dckc what's the progress on this issue? I am persuaded to close it since it requires a smart objective. Feel free to open it to get your thought around it.
