### ISSUE TITLE
Clean up rchain/board

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#448]
[https://github.com/rchain/board](https://github.com/rchain/board) is hard to navigate.

- Text cutoff of filenames in the github viewer makes it hard to know what each document contains.
- Changes between versions of the bylaws are hard to see.
- There is no file structure hierarchy, which will probably be un-maintainable in the long run.
- All files are unsearchable PDFs

- [ ] Convert all documents to markdown
- [x] Create one file for the bylaws, use commits to update them
- [x] Create a year/[MM]-[D]/ structure
- [ ] Collect agreements that aren't present in this repository (Pithia Nee Holdings)
- [x] Update titles of agreements to reflect entity name changes (Pithia, Reflective Ventures)
- [x] Fancy README.md pointing to important / most recent version of things

**Comment by dckc** [comment]
This sounds great!

Make sure to coordinate with @n10n ; he seems to have handled that repo to date.

Here's hoping we can publish the results somewhere under the **rchain.coop** domain; cf. #411 .

cc @ian-bloom @jeremybusk

**Comment by dckc** [comment]
p.s. consider folders organized by time (year and/or month) rather than by type of document.

**Comment by ICA3DaR5** [comment]
@Jake-Gillberg Could you convert them to Markdown text?

I was thinking all those PDF's need to be in Markdown IMO. You can easily export them to PDF anyway, anytime.

**Comment by Jake-Gillberg** [comment]
@dckc good suggestion. I was coming to that conclusion as I started parsing through things yesterday.

I am thinking something like this:
```
├── 2017/
│   ├── 10-4/
│   |   ├── Minutes.pdf
|   |   ├── Revised Bylaws.pdf
│   ├── 12-5/
|   |   ├── Minutes.pdf
├── 2018/
│   ├── 01-22/
|   |   ├── Pyrofex Agreement.pdf
└── 
```
@ICA3DaR5 Yeah, having these in Markdown would be awesome. Do you know of a good way to do the conversion? I am concerned that the Markdown conversion and the review of that conversion would be  a tedious manual process. If there isn't a good way to automate, at minimum I would like to manually create a markdown document of the current bylaws (would probably live at the top level of the above directory structure).

**Comment by dckc** [comment]
Surely a softcopy of the text documents in PDF or Word format or whatever is around somewhere. Ask @edeykholt maybe?

**Comment by kitblake** [comment]
This tool does a decent job converting: http://markitdown.medusis.com/ especially from Google doc html. Just copy and paste.
But as @dckc pointed out, you'd need the 'original' docs from which the PDFs were made.

**Comment by makys** [comment]
@Jake-Gillberg This is a true pain point especially with ability to search the minutes. 

> Changes between versions of the bylaws are hard to see.> 

For versioning of the Bylaws, we should consider a version control procedure so it can applicable across board for similar type document. "In short, usability and learnability improve when similar elements have consistent look and function in similar way." - Design Principle - Consistency.

**Comment by Jake-Gillberg** [comment]
Opened a pull request with some changes here: https://github.com/rchain/board/pull/1

Any feedback is welcome!

I only translated the the bylaws to markdown, because this was a tedious manual process.
I also didn't collect the agreements that are missing from the current document store.

**Comment by ian-bloom** [comment]
Bylaws & minutes are generated by the Co-op's Secretary, Evan Jensen (@evanjensen) on RChain Discord. Please coordinate with him to obtain text versions. Manual transcription should not be necessary.

**Comment by Jake-Gillberg** [comment]
@ian-bloom Thanks, I sent an email to Evan on Monday the 12th.

**Comment by dckc** [comment]
@Jake-Gillberg I'd love to see the results published under the **rchain.coop** domain so that we could change back-ends later if we want. Do you think it's worthwhile? At least for the documents you / we convert to markdown?

cf. #411

**Comment by Jake-Gillberg** [comment]
@dckc. Sure, I think the Bylaws especially would be important to have published under the rchain.coop domain. You thinking that we would have github continue to host the content for now though? I'm worried about having to maintain the updated Bylaws in two separate places. I am currently planning to maintain (with cooperation from @ian-bloom or someone who has commit access to /board) [https://raw.githubusercontent.com/rchain/board/master/Bylaws.md](https://raw.githubusercontent.com/rchain/board/master/Bylaws.md)

**Comment by dckc** [comment]
yes, hosted by github -- using github pages and a custom domain. see #411

**Comment by dckc** [comment]
ironic: I just realized that the board PDF documents aren't scanned images as I had imagined. Or did that change recently? Were they unsearchable? Docs such as https://github.com/rchain/board/blob/9f063a4b7c05d40d09ce63f23d60869ab000dffc/20180125BOD-Meeting%20Minutes.pdf seem searchable.

**Comment by Jake-Gillberg** [comment]
@dckc Only a few documents are scanned images. I meant unsearchable from the github viewer (at least in my browser).

**Comment by Jake-Gillberg** [comment]
[https://github.com/rchain/board/pull/1](https://github.com/rchain/board/pull/1) was merged and this done to my satisfaction for now. If someone wants to reopen or open up another issue for translating more documents to markdown or finding the missing agreements, please do.

For bounty voters: herding cats and doing pull request review stuff took some time. So all in all, I'd say I have about 7 hours of "billable" time for this.

**Comment by ICA3DaR5** [comment]
> @ICA3DaR5 Yeah, having these in Markdown would be awesome. Do you know of a good way to do the conversion? I am concerned that the Markdown conversion and the review of that conversion would be a tedious manual process. If there isn't a good way to automate, at minimum I would like to manually create a markdown document of the current bylaws (would probably live at the top level of the above directory structure).

@Jake-Gillberg There are ways to auto-magically convert PDF and doc's into Markdown, but there is definitely going to need manual oversight and fixes. I can take up on that task and create a separate issue.
