### ISSUE TITLE
M>Translate Rchain Whitepaper.pdf into Croatian

### ISSUE THREAD

**Issue by InternautNeven** [rchain/bounties#449]
## Original (English) Content
- [RChainWhitepaper](https://github.com/rchain/reference/blob/master/docs/RChainWhitepaper.pdf)

## Translated (Croatian) Content
- [RChainWhitepaper_HR](https://drive.google.com/open?id=1Pr1OAuhp36qKL-JpLxccwXQrJOkiIGH1)

To attract people from different cultures and with different languages. This is easiest when the English version is translated into local spoken languages. Whitepaper is basic guide that informs readers concisely about a Rchain project and present the matter. 
We will translate it in a 30 days.
Why: interest in telling the story of RChain in another language.
 
Collaborators:
* @InternautNeven
* @MarioPolo 

 Reviewers:
* @tgrospic 
* @Howsoonisnow 

Tasks:

- [x] Translate the content
- [x] Check the spelling
- [x]  Review each other's work
- [x]  Have it reviewed by others with knowledge of English and Croatian
- [x]  Create the .pdf file

* @InternautNeven: 50 %
* @MarioPolo : 20%
* @Howsoonisnow 25%
* @tgrospic 5%

### Other Information

Completed: 100%

Suggested Budget: $3333

Why this/these document(s)? (mark all that apply)

- [x]  It's one/some of the /rchain/reference document(s).
- [x] I know a person or audience who would benefit from it: The Croatian developers community.
-  [x] Several reviewers are involved. (assign the ticket to them)
-  [x] At least two of them have high proficiency in English.
-  [x] At least two of them have high proficiency in Croatian.
-  [x] At least two of them have either:
-  [x] Significant reputation Diploma- InternautNeven: (MS) IT Management, Howsoonisnow: (MS) Professor
-  [x] A track record of quality work on rchain bounties: #382, #125 

What about maintenance? (choose one)

 *  [ ]  The source document(s) is/are stable; further translation work is not expected.
*  [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by ICA3DaR5** [comment]
@InternautNeven Could you please, base tour issue post on this template? https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md

**Comment by InternautNeven** [comment]
@ICA3DaR5     If you could tell me is it better to made it in pdf format or a Markdown.  Can you dirrect me to source document of Italian version- i saw it as Issu-e,  it would help us. And if  you have some suggestion for reviewer, if no we will find one more in a couple of days. Thank you

**Comment by ICA3DaR5** [comment]
@InternautNeven I am all in favor of Markdown, but since it's a PDF I leave it up to you to decide.

I found the Italian version [here](https://github.com/rchain/reference/blob/master/docs/RChainWhitepaper_IT.pdf).

**Comment by InternautNeven** [comment]
Ok, it is [translated](https://drive.google.com/open?id=1pCAzi9drOcTW8eP_TUZ3XRHlkv9LLpk2). Is there anywhere else that i need to upload it.

**Comment by ICA3DaR5** [comment]
@InternautNeven Please create a Pull Request for the reference/docs repository.

**Comment by InternautNeven** [comment]
Yes, @ICA3DaR5  it was created https://github.com/rchain/reference/tree/master/docs 18 days ago https://github.com/rchain/reference/pull/51/commits and it was merged 10 days ago

**Comment by ICA3DaR5** [comment]
@InternautNeven Great!
