### ISSUE TITLE
Coop2Board --> Collect Member Questions that Deserve Answers

### ISSUE THREAD

**Issue by barneycinnamon** [rchain/bounties#450]
Let’s work together to enumerate questions about the Co-op, get those questions in front of the right people, and generate well-documented answers. The focus on resolving questions about decision making processes and power in the Co-op itself. 

I have put together a document containing some of the questions that I have, but I want to give other members an opportunity to review and edit the document to make sure that we have a comprehensive list of areas of concern. Please edit!

 - [RChain Cooperative Governance Questions](https://docs.google.com/document/d/1DDBnJwHe4RhrAeE8IRUEPa9srG8tikRDibydnvvv8y0/edit)

Once some time has passed, I'd like to interface with the various working groups and the board to make sure that all of the fundamental questions related to governance and how the Co-op functions get answered or get assigned to the right set of people to work through them.

 - [x] Generate a Google Doc seeded with some questions
 - [ ] Reach out to governance working groups and executive committee to see what is already on their radars
 - [ ] Collect some additions / revisions from other interested members
 - [ ] Generate some specific Issues separating out components where action is possible
 - [ ] Build a mechanism for members to submit polls of some sort to the Board
 - [ ] Submit the questions to the members of the Board (as individuals if possible)
 - [ ] Have member-wide polling or voting on the issues that garner sufficient attention

**Comment by pmoorman** [comment]
@barneycinnamon well done for posting your first Github issue 💯 !!

I've added the label "Governance" and assigned you and me. You can do that on the right. Can you see it?

**Comment by barneycinnamon** [comment]
I see it, but it doesn't appear clickable. Your handle and my handle both show up as links, but the word "Assignees" and the word "Labels" both do not appear as links. The GitHub help entry on Labels suggested going to the main page of the repository, clicking the checkbox next to the issue I wanted to label, and then selecting the label to add. But I didn't see any checkbox next to the issue on the main page, just a circle with an exclamation point in the middle where I expected to checkbox to be.

**Comment by pmoorman** [comment]
Don't you see next to "assignee" the little gear icon?  That's what you need. 

If you don't see it, then maybe you somehow don't have equal editing rights, but I doubt that to be the case...

**Comment by barneycinnamon** [comment]
No gear.  ¯\_(ツ)_/¯  Maybe that's why, even though I commented on an issue by @dckc, I didn't end up in the bounties spreadsheet and couldn't vote on it.

**Comment by dckc** [comment]
The questions in the doc are useful, but you wrapped them in a "solve all the world's problems" issue or "how long is a piece of string?" issue.

The first couple questions look like they would make good issues on their own:
  - **What is the mission of the Co-op?**
  - **What are the business goals of the Co-op?**
  - ...

Oh... another thought: you seem to be seeking answers not just from any three people who might choose to collaborate but answers on behalf of the whole coop. The bounty system is an awkward place for them. I suggest you either
  - take them to the existing committees or the board
    - this dovetails nicely with making separate issues for each question.
  - get involved in building the petition system (#380)
    - you could even use github issues as prototype petitions... say... if you get 20+ people to +1 an issue, it's a pretty compelling case for the leadership to put it on their agenda

**Comment by dckc** [comment]
The questions about the board of directors have answers in the form of readily available facts; no need to ask anybody about those, I hope.
> How is it written in our bylaws?

like this: [RChain Cooperative Bylaws](https://github.com/rchain/board/blob/master/Revised%20Bylaws%20(8-28-17).docx.pdf)

**Comment by barneycinnamon** [comment]
_ Searches sent email to find the one to ops@rchain.coop. Wonders if he needs to click through the link in the You've been invited email. Clicks link. Clicks big green button. Gears! _

**Comment by barneycinnamon** [comment]
Reading bylaws now. Will add to the original document answers as I find them.

**Comment by makys** [comment]
It appears you are providing a frame for which these questions should be answered considering your sub-questions. I would suggest if some of these sub questions stand alone. We should also be mindful that the answers to these questions may vary depending on who you talk with and in my opinion some of these questions do not have conclusive answers just because a lot is evolving in the space.

If we get enough consensus on this issue, we may well tag this as FAQ 2.

Nice work @barneycinnamon

**Comment by dckc** [comment]
I don't suppose you consider this done.

**Comment by barneycinnamon** [comment]
I think issues #380 and #564 might better positioned to accomplish the objectives that motivated this issue.
