### ISSUE TITLE
DNS name, SSL cert for bounty budget voting system

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#451]
for production deployment:
  - **bounty-system**.rchain.coop ?
  - **bounty-budgets**.rchain.coop?

cc @kitblake @lapin7 @ian-bloom @jeremybusk @hyperevo @patrick727 

see also #260

**Comment by makys** [comment]
@dckc What is the timeline for the bounty web app to be completed?

**Comment by dckc** [comment]
This is assigned to [milestone/3](https://github.com/rchain/bounties/milestone/3); my best guess at a launch date is kept there.

**Comment by ICA3DaR5** [comment]
**bounties**.rchain.coop?

**Comment by dckc** [comment]
I didn't want to give the impression that it was the whole bounty system, since so much of the action is here in github. But it (**bounties**.rchain.coop) is worth considering.

**Comment by zsluedem** [comment]
some suggestions
* system.rchain.coop
* cooperate.rchain.coop

**Comment by ICA3DaR5** [comment]
I am inclined towards **bounty-system**.rchain.coop or **bounties**.rchain.coop

**Comment by ResonanceXX** [comment]
Bounties.rchain.coop is less cumbersome. Because the - may give some problems. 

Sent from Yahoo Mail on Android 
 
  On Sun, 4 Mar 2018 at 17:17, Donald A. Iljazi<notifications@github.com> wrote:   
I am inclined towards bounty-system.rchain.coop or bounties.rchain.coop

**Comment by Keaycee** [comment]
Is there  a  web application prototype for RAM distributed budgeting and bounty? @dckc 
How about this DNS names
bounty.rchain.coop
bountybudget.rchain.coop
rewards.rchain.coop
budgets.rchain.coop

**Comment by makys** [comment]
I really like rewards.rchain.coop suggested by @Keaycee 
Rewards and RChain both starts with "R".

I tried to look up the difference between Reward and Bounty online even though we use the term bounty often.

"Bounty is a synonym of reward.
As nouns the difference between bounty and reward is that bounty is generosity while reward is something of value given in return for an act." (Source: https://wikidiff.com/bounty/reward)

"A bounty (from Latin bonitās, goodness) is a payment or reward often offered by a group as an incentive for the accomplishment of a task by someone **usually not associated with the group**. "(source Wikipedia). We have established that we want **only** member to be part of the bounty (or better put rewards) program.

**Comment by dckc** [comment]
I'm hesitant to go with rewards.rchain.coop; I lean toward something more obscure: maybe **dbr.rchain.coop** (distributed budgeting and rewards).

**Comment by dckc** [comment]
@jeremybusk I need your help with the SSL cert.

@ian-bloom did the CNAME, so we have https://rewards.rchain.coop/ , but with scary SSL warnings.

**Comment by dckc** [comment]
@jeremybusk took care of the SSL cert.

**Comment by dckc** [comment]
I'm folding the $200 budget for this into #477 .
