### ISSUE TITLE
M> Review and translate Codebase document video subtitle to chinese

### ISSUE THREAD

**Issue by watermelonZJ** [rchain/bounties#453]
Review the correctness of the codebase document video subtitle and translate it to chinese.
As #347 said, the subtitle obtained by machine is not accurate so that the checking is necessary.

Tasks:

- [x] Review the subtitle generated automatically
- [x] Translate to chinese version
- [ ] Download the video, add the chinese subtitle and upload to rchain wechat official account

Measure of Completion:  
Suggested Budget: 600$ (0.1$ per word for the subtitle review, 0.2$ per word for the translation and 50$ total for the promoting)

_See CONTRIBUTING.md for details on budget and reward process._

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
    - [x] I contacted the author, who agreed it's important to translate
    - [x] I know a person or audience who would benefit from it: _____
    - [x] other: ___
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: ____

**Comment by ICA3DaR5** [comment]
Please post the work done here.

**Comment by michaelizer** [comment]
Due to lack of response, I'm adding a slashing vote on this issue.
