### ISSUE TITLE
Web site analytics on language demographics

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#454]
@patrick727 which languages show up high in web site analytics?

This is follow-up from our discussion in Seattle, originally posted in https://github.com/rchain/bounties/issues/302#issuecomment-367168156

**Comment by patrick727** [comment]
This is from September 2017, I chose that date range because it was around the time of the annual meeting.

[Analytics All Web Site Data Language 20170901-20180304.pdf](https://github.com/rchain/bounties/files/1783048/Analytics.All.Web.Site.Data.Language.20170901-20180304.pdf)

**Comment by dckc** [comment]
Thanks!

cc @pmoorman @ICA3DaR5

**Comment by ICA3DaR5** [comment]
I don't think the current web analytics say anything. We should choose the languages that we need to expand to.

Hence #579
