### ISSUE TITLE
Medium Post: Pythia and RChain: Transmitting Blockchain Oracles.

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#455]
Just getting thoughts out an interesting analogy of pythia/pithia. Both mediums of futuristic divinations. 

![screenshot-2018-3-6 pithia and rchain transmitting blockchain oracles](https://user-images.githubusercontent.com/34219332/37014146-ee9ddcd8-20fe-11e8-97ac-fd4e1ebb0144.png)
Thanks for your interest in telling the story of RChain in another language.

  - Why this document? (mark all that apply)
  
    - [ ] several reviewers are involved
    - [ ] at least two of them have high proficiency in English
       - [ ] a track record of quality work on rchain bounties: 
        A clear measure to determine when the issue is completed: **Completed**
        Scope  - **Creating informed topics about RChain and associated venture.**
        Suggested budget: **$300 - 500**
   

PITHIA AND RCHAIN: TRANSMITTING BLOCKCHAIN ORACLES
https://medium.com/@kenechukwuoliaku/pythia-and-rchain-transmitting-blockchain-oracles-e50f83c84bf3

**Comment by Pionelle** [comment]
Well written
Have upclapped!
But is Pithia inc. making contributions to the RChain coop and bounty programme. Directly or not?

**Comment by ResonanceXX** [comment]
@Pionelle I do not speak at that level of affairs. But I would consider Pythia's involvement as an extension of RChain ventures. Whether they contribute in an form, more clarifications are needed.

I had just written this to draw both analogies. Get word out. You can however, visit the  - Oracle's  - website @ www.pithia.com I should also add that it is at its infancy. Dont expect too much information.

You could check the Discord channel for more information. 
Cheers!

**Comment by ResonanceXX** [comment]
To add that you can follow on Twitter also @Pionelle

**Comment by Pionelle** [comment]
@ResonanceXX Thank you very much. 
i WOULD try on twitter and the other app you mentioned also.

**Comment by pmoorman** [comment]
@ResonanceXX I'm going through the list of (marketing) issues in an effort to make all issues clearer and more S.M.A.R.T.

**Could you update the description, to more specifically outline what this issue is about?**

Stuff like this:
- Scope = ...to write & publish a blog post on personal Medium about Pithia (??)
- You might need some help with editorial review, if I get it correctly.
- Suggested budget

Maybe the title can also be updated to more clearly reflect that this concerns the publishing of a blog post?

Thanks!!

**Comment by ResonanceXX** [comment]
@pmoorman Thank you for calling my attention. Allow me rectify this as I was unaware. I shall take into full consideration your opinion. Cheers!

**Comment by ResonanceXX** [comment]
@pionelle, just to add to our previous discussion. www.pithia.com has now  been comprehensively updated. There has also been added a Profile of the board and the CEO  @Lawrence Lerner. 
You should visit her for any additional information you may be seeking to access. Cheers.

**Comment by Pionelle** [comment]
Visited the website. 




Thank you

**Comment by ResonanceXX** [comment]
And also allow yourselves liberty to contribute on issue #603. Cheers

**Comment by pmoorman** [comment]
closing this issue because it seems it's completed.
