### ISSUE TITLE
Board Of Directors Profile on Coop Website - Attention.

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#456]
# All

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

Measure of Completion:  

Hello, Devs/Builders.
 
Caught my eye

1). Mr. Ian Blooms profile.
Minor text ammendment - Ian *is a* Open-source, linux, and DAO enthusiast. Worked as a Microsoft Software Engineer for AEGON, Computer Security Specialist for Fortress Technologies & Kroll.

Could read *is an* since this is a vowel coming after the noun. https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwjkxe-w8dbZAhUCRhQKHXPnBy8QFggqMAE&url=http%3A%2F%2Fwww.writersdigest.com%2Fonline-editor%2Fa-before-consonants-and-an-before-vowels-is-not-the-rule&usg=AOvVaw0oRck0W7NU9cFBU_tb9fQY

2). The direct speeches of our Directors should be relayed in inverted commas. '' 0 '' Minor adjustment.
This would separate the direct and the reported speeches for better comprehension.
a).  Hendrick J. Hillbolling
Working since 1989 in the IT business with a degree in Business Management in 1990 from the University of Groningen, The Netherlands. HJ started in 1995 to introduce email in the Ministry of Education and created their first website. **With friends I raised the Association NetYes that made the digital city of The Hague**. **In 1997 I joined AtosOrigin as a CRM consultan**t. Currently HJ is in the position of blockchain consultant with focus on social communities, attention economy and remuneration of creators instead of third parties. Markers **

b).  David Currin

A strong believer that the future of the internet must be and will be decentralized. David also works with dapphub and makerdao. David stood as a candidate for the Internet Party at the last general election in his home of New Zealand for the principles on which the internet was founded, principles of freedom, fairness, openness for all - advocating transparent governance, data-driven policy, a surveillance-free society and much WOW which decentralised tech will enable. **We need better tools for communication and co-ordination, tools which can’t be manipulated or subverted by the interests of the few. Tools like RChain.**

Is this David Currin's closing thoughts or a part of the description? If its a direct speech by David, shouldn't it be made known these are his thoughts and not the RChain websites'.

3. Evan Jensen's profile isn't finished with a (full stop). Minor**
4. There isn't any picture of Navneet Suman. I suggest an RChain logo could be used in the absence of any.

**Comment by David405** [comment]
Nice  job making all these observation @ResonanceXX. Your observations actually made go back and look closely at these profiles. I believe only developers with access to the website can make necessary corrections @laplin @dckc others?

**Comment by lapin7** [comment]
@ResonanceXX Thanks for your review. I will propose another text. However I don't have write access to change things on the website.

**Comment by makys** [comment]
Good catch @ResonanceXX .

**Comment by dckc** [comment]
I don't have write access to https://www.rchain.coop/

My impression is that @patrick727 and perhaps @n10n do.

**Comment by dckc** [comment]
Someone called Chiamaka Igweka in gdocs added this to this week's agenda (#469). I'm interested to know why. Just FYI? Or is this issue stuck? What's the goal of the agenda item?

@Tonyprisca13 do you know that person?

**Comment by ResonanceXX** [comment]
Hello, @dckc. I dont have that sort of information. 
Resolving these errors are important to me above all. Tells on us to ''Dot our I's and cross our T's''. 

The website is the embassy of our total makeup as an organization. Cheers!

**Comment by Keaycee** [comment]
@ResonanceXX This issue will be addressed on the weekly agenda #469 today, stay tuned.

**Comment by pmoorman** [comment]
Hey guys, 

I'll try address all these points in the next couple days in Github Issue #538.
I have write access to Squarespace now, so this shouldn't be a problem.

Cheers,

–Pieter

**Comment by ResonanceXX** [comment]
@pmoorman Hello, I see actionable movements about this issue. This is positive and gladdening as well. Feel free to connect for a better review too. Cheers.

**Comment by ResonanceXX** [comment]
@pmoorman Word of encouragement for the team. It is my hope that the end result makes you happy.

**Comment by ResonanceXX** [comment]
@pmoorman Shout out to a job well done. Just to call your attention that @lapin7's picture on the website is a bit too informal. The uniformity of the other pictures is lost with, @lapin7 's sitting on a park bench. Could you request a better image file from him. Thanks.

**Comment by lapin7** [comment]
![image](https://user-images.githubusercontent.com/1913335/39407561-eb172c9c-4bc7-11e8-8577-87b112225d39.png)

Would this work??

**Comment by Tonyprisca13** [comment]
Nice
