### ISSUE TITLE
Operate account for spread RChain on bihu.com

### ISSUE THREAD

**Issue by JieL314** [rchain/bounties#457]
Description: [Bihu](https://bihu.com/) is a newly launched social platform. To be exactly, Bihu is a vertical community platform for cryptocurrency. I saw several blockchain(like EOS or SKYcoin) already has their account in Bihu, I am prepare to operate a account to spread RChain. The difference with other channels is that users of Bihu is more likely to invest in cryptocurrency field. 

Work: The current work is to post all documents which were been published about RChain. The next work is update the latest news about RChain.

Budget: The current work is miscellaneous because there are nearly 30 docs need to be upload. So I set the budget for this March is $3000. I will decrease the budget according to the workload next month.

**Comment by dckc** [comment]
I'm interested to see the list of 30 documents. I suggested someone do a documentation inventory in #298 but I haven't seen any results.

A $3000 budget suggests dozens of hours of work. Does it really take that long to post pointers to 30 documents? Perhaps I don't understand what you mean by "upload"?

Also, thanks for filling out the introduction survey (#222); please consider sharing some of that info in your github profile, which is much easier to find.

**Comment by JieL314** [comment]
Thanks for your suggestion. I will give the detail list to show you all the documents. 

The work is not post the hyperlink of documents, but post the content of it in Chinese, so we should re-edit the format. Besides, we will write some non-technical articles to make more investor know RChain. 

My introduction can be find in [column52](https://docs.google.com/spreadsheets/d/1yvhJUJo8goo14exir6U0FDibUlP7aWIv_CSk4_hnOFM/edit#gid=1739308456).

**Comment by AbnerZheng** [comment]
@JieL314 @dckc @lapin7 
I had actually created a bihu account of rchain for Bihu about two week ago, and I have migrated some of translating document to Bihu. Bihu already paid for the document, and these document translation already paid in other issue in rchian. So I don't think it is good way to apply the budget. 
What do you think about it?

**Comment by yyh1102** [comment]
Yeap, the public channel of RChain in Bihu will be published soon~ @AbnerZheng @JieL314  Hopefully more and more collaborator can join and post their works on it.

**Comment by JieL314** [comment]
Ok, I will do other job to help to spread RChain. Hopeful to do it better. @AbnerZheng

**Comment by dckc** [comment]
Someone called Chiamaka Igweka in gdocs added this to this week's agenda (#469). I'm interested to know why. Just FYI? Or is this issue stuck? What's the goal of the agenda item?

@Tonyprisca13 do you know that person?

**Comment by Tonyprisca13** [comment]
This issue is added to the [RAM weekly agenda](https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64/edit#heading=h.vnl7pexus3jjurl)@AbnerZheng would like anyone participating in the isssue to give us an update in the meeting

**Comment by AbnerZheng** [comment]
@Tonyprisca13 Sorry, I have not added this to the agenda.  And @JieL314 has agreed my suggestion. Can I remove this agenda item?

**Comment by zsluedem** [comment]
I have asked @JieL314 and this task has been done by someone else.
