### ISSUE TITLE
M> Branding Platform Document

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#461]
Draft 1 of branding platform document complete

**Comment by dckc** [comment]
How is this different from #371?

And I'm curious why a branding label in addition to Marketing.

**Comment by makys** [comment]
@dckc I am wondering same thing too with regards #371 
@patrick727 can you share the Draft 1 of branding platform document  here.

**Comment by patrick727** [comment]
its not different, i didnt see that issue in thie project branding working group, thats it
