### ISSUE TITLE
M> Translate Video Exclusive Chat Jake Brukhman man & Kenny Rowe (Crypto Talk on Rise)

### ISSUE THREAD

**Issue by Keaycee** [rchain/bounties#462]
# Goal:  Translate Video [Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://www.youtube.com/watch?time_continue=17&v=cjHooZc0JNM)

The file name is: [[TRANSCRIPT][.srt][English] "Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://docs.google.com/document/d/1-SsnE2rHlULBK5CR41re0OW_pxf4ubpwySTfqiuKjZM/edit?usp=sharing)"
It's in Folder: [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)
 
- [x] create a complete transcript in English with timed links to subjects before 2018-03-30
- [x] Correction of transcript errors
- [ ] Mandarin 
- [ ] French, 
- [ ] Greek, 
- [ ] German 
- [ ] Spanish 
- [ ] Portugese 
- [ ] Dutch, 
- [ ] Serbo-Croat, 
- [x] Italian, 
- [ ] Russian, 
- [ ] (or add other languages)
- [ ] promote video on all channels and other outlets

## Time: 2weeks

**Comment by dckc** [comment]
Please move the budget to the individual per-language issues and take it off this one.

I suppose a budget for cleaning up the English translation could stay here.

**Comment by BelovedAquila** [comment]
@Keaycee I will be working to review the English transcript, hope you don't mind?

**Comment by Whisker17** [comment]
Cool,I'm looking forward to contributing myself to it.

**Comment by Keaycee** [comment]
You're welcome @BelovedAquila 
The English transcript corrections will completed in a few @Whisker17

**Comment by Keaycee** [comment]
I'm done with the English transcript. Now completed

**Comment by ResonanceXX** [comment]
@Keaycee  Hello. Minor text issue. Telegram text shows **Jake Brukhman** but that was in @lapin7 translated version to groups. Is it then fair to suggest Jake/James Brookman is the English form of the name. Otherwise everything is fine. 


I have only assisted in changing the srt. file's heading to **Jake**. You can then follow through on the surname. Cheers!

**Comment by BelovedAquila** [comment]
@ResonanceXX you are right I just observed that too,

**Comment by Keaycee** [comment]
Thank you for your observation. noted and corrected on the new threads and srt file.

**Comment by BelovedAquila** [comment]
Actually made the adjustment in the transcript file name, other language transcript should follow suit

**Comment by Whisker17** [comment]
I don't think this transcript works since it doesn't a time axis (xx:xx:xx,xxx --> yy:yy:yy,yyy) like other worked transcript, is that right? @Keaycee

**Comment by ResonanceXX** [comment]
@Keaycee @BelovedAquila Very up to date. cheers.

**Comment by Keaycee** [comment]
It does has a timestamps @Whisker17

**Comment by Whisker17** [comment]
@Keaycee Have you ever a try?It doesn't work if you change the .txt to .srt

**Comment by zsluedem** [comment]
@Keaycee It is not a norlmal .srt format. What that means is it doesn't fit into the youtube subtitle.

**Comment by Keaycee** [comment]
I'm going to get that fixed today @zsluedem @Whisker17

**Comment by dckc** [comment]
I removed the misleading budget.

**Comment by Keaycee** [comment]
@lapin7 @Whisker17 @zsluedem @ResonanceXX @BelovedAquila see issue #251 and suggest a budget for this thread.

**Comment by dckc** [comment]
#251 is an example of what _not_ to do. It has caused a great deal of concern, including suggestions to stop the bounty program altogether. (cf [executive committee March 2](https://docs.google.com/document/d/1MeYZFva1U-5Faf7NZmOrd0KeJ1CAc293sExC7Lxa4Ec/edit))

**Comment by ResonanceXX** [comment]
@Keaycee  Hello. The source file being changed, does it render our previous work on the document irrelevant?

**Comment by Keaycee** [comment]
It was hard for me to do it. @Whisker17 and @zsluedem tried to convert the transcript back to srt but it failed, probably because it was not in the right format. Now i've got it back to a right format. So i'm still reviewing the document.

**Comment by ResonanceXX** [comment]
@Keaycee okay. Lets get on with it. Cheers.

**Comment by Keaycee** [comment]
No need for that, I'm still doing some correction on the transcript. @Whisker17

**Comment by Keaycee** [comment]
The transcript review has been completed today. But still open for further correction. You may start your translation @Whisker17

**Comment by Whisker17** [comment]
@Keaycee Good job

**Comment by BelovedAquila** [comment]
#488

**Comment by BelovedAquila** [comment]
#488

**Comment by Whisker17** [comment]
still have so many problem,I'll upload a new reviewed doc in two days. @Keaycee

**Comment by Keaycee** [comment]
What problems @Whisker17 , There won't be need for that on this transcript. Other translators are working with this document. Try and fix your problem on your part. I've done the corrections and reviewed the document severally with the video.

**Comment by Whisker17** [comment]
But I've found many problem with your version,and if I do with your transcript,I think it will take me more time,so I think I should correct this first. @Keaycee

**Comment by Keaycee** [comment]
Well, It's take a pretty good time to do a good translation job. You seem to be the only one complaining. I suggest you. I found no problems with the transcript because it has been reviewed. Perhaps you need to see the video chat and do your translation. @Whisker17

**Comment by BelovedAquila** [comment]
@Whisker17 should I suppose you made an exaggeration. Presently working with the transcript made by @Keaycee and have attain some certain level of progress on it, so you waking up to drop a new version is what I can't fathom, if there are issues there comment on them on the main transcript already in use, so you don't end up raising a misunderstanding as that found in #266

**Comment by Whisker17** [comment]
@BelovedAquila  cool,it's OK,I'll do my translation,thanks for your advise.

**Comment by ResonanceXX** [comment]
@whisker17 Be informed, extensive work done on the document precedes the error you have pointed out. 

Except a newer document was created, which would be needless. 

Secondly, with my experience in the work, we generally make the edits on the document, leaving behind edit marks for the correcting contributor to make amends.

That is done there. And the corrections are made more genuinely.

**Comment by irynapopova61** [comment]
Hello, can i translate it to Ukrainian ? @Jake-Gillberg

**Comment by Jake-Gillberg** [comment]
@irynapopova61 I do not think that this is a good target. If you would like to summarize the content into a blog post and translate it, I would support that effort.

**Comment by Whisker17** [comment]
@ResonanceXX  I see,and all I want to do is to make this transcripts more precise,and you are right,I totally agree,thanks for your advice

**Comment by Staff91** [comment]
Issue #488 is Done.

**Comment by Whisker17** [comment]
This transcript‘s word account is 8897,since the price of a word is $0.2,so I think the total budget should be $1800.

**Comment by BelovedAquila** [comment]
Issue #464 is Done.

**Comment by Jake-Gillberg** [comment]
I believe that subtitle translations are worth much less than video translations. I appreciate your work, but I am currently valuing video subtitle translations at .05/word, not .20/word.

**Comment by Keaycee** [comment]
@Jake-Gillberg The proposed budget for this work is $1800. However, I suggest every participant of this thread should review their budget on this issue.

**Comment by Jake-Gillberg** [comment]
@Keaycee, @Viraculous. I see that you changed your vote from $5,000 to $1,800. Please tell me why you initially voted $5,000, otherwise I must assume that your intent was to defraud the bounty program.

Also, you have not offered an explanation for the $1,800 budget for this issue. Please explain what value was derived from this issue.

**Comment by Keaycee** [comment]
@Jake-Gillberg I asked everyone who participated on this issue to review their votes to be matched the proposed budget. There was no intent to defraud the system, I commented on this issues 24 days ago, asking the participants to come up with a budget for the issue.  @Whisker17 came up with the proposed budget for the issue, which was $1800. I must say people vote as a result of example of the budget seen in the budgetvote especially when we were still using the spreadsheet. Please @Jake-Gillberg , @dckc  @BelovedAquila review your vote on this issue.

**Comment by Jake-Gillberg** [comment]
@Keaycee You voted too. Please explain your reasoning for this amount. There are logs of $5000 votes on this issue. 

Just had a conversation with @Keaycee in which he claimed that generating the original English subtitle file would "3-4 days". I was able to download the youtube auto-generated subtitle file within minutes. From here I would guess all it would take is a scan to clean up anything the machine missed. 2 hours worth of work TOPS. This in now way justifies a bounty of $5000. Due to my judgement that the work done and budget proposed for this issue was not in good faith, I am modifying my vote from $100 to a large negative number.

**Comment by Keaycee** [comment]
@Jake-Gillberg The amount of time i spent doing my job does not matter, What matters is the quality of work done. To download an auto generated subtitle file only takes minutes. What consumes more time is the reviewing and correction on the script. @Jake-Gillberg Kindly put up the whole conversation i had with you on discord on here for everyone to see.
@Jake-Gillberg I understand you have personal problem about translation jobs, but it think it's more personal voting -99999 and @dckc voting -5000. I made reference to issue #251 . You can take a look at the budgetvote on issue #251 on the spreadsheet in january.
12,000 @Whisker17 
14,000 @Tonyprisca13 
10,000 @LiliNL 
10,000 @kaka56 
10,000 @Viraculous 
10,000 @Mervyn853 
11,500 @noordaa 
12,000 @ICA3DaR5 
12,000 @BelovedAquila 
10,000 @lapin7 
10,000 @Ojimadu  
All this votes was as a result of the misleading vote made by one person and was seconded by other participant. However, the budget was corrected $1,000 by @lapin7 regardless of the vote of outrageous votes of the participants.  Again, sometimes members vote outrageously because of the misleading votes placed by others. Looking at the votes above, the intent was never to defraud the system, but rather vote seconded to backup the first example of vote placed. 

The spreadsheet is no longer in use and some coop members do not know how to use the  webApp effectively.


Now @Jake-Gillberg and @dckc  voting an outrageous negative vote on issues created by me. I must say, if issue 462 was created by @lapin7 you both will have that decency not to behave or act like this. But because it was created by @keaycee .  

What justifies your act of negatives vote, was it the conversation on discord or comments on github or the quality of work done? @Jake-Gillberg 

@dckc and @Jake-Gillberg I think you guys are trying to centralize this system and also discourage coop members. We don't have a lot of participating coop members on github and many of them aren't active members. 

I understand that @dckc @Jake-Gillberg do not support my work, thereby calling other friends to downvote my budget. This is no longer official, rather a personal decision of loathing and resentment.

The system is decentralized and collaborative, we're here to collaborate with other coop members for the best interest of RChain, and not to discourage coop members from participating. 
Example: If Mr A spot an error where Mr B doesn't see it, as a coop, It's up for Mr A to address or correct such errors rather than leaving it for Mr B to spot it out. 
As we collaborate together, correct errors together, we learn and don't make same mistakes tomorrow.

**Comment by Keaycee** [comment]
![screenshot 113](https://user-images.githubusercontent.com/34557673/38243165-f0a00288-3736-11e8-8902-d3ff8a2d8731.png)

![screenshot 114](https://user-images.githubusercontent.com/34557673/38243177-f90ba026-3736-11e8-9364-b03219a340f1.png)

**Comment by Jake-Gillberg** [comment]
@Keaycee you are welcome to share the whole conversation if you like.

I compared your corrected script with the auto-generated. I removed the punctuation and capitalization in your work for easier comparison. See the results [here](https://www.diffchecker.com/QJ4e2Lfz). I agree that you did a good job reviewing the auto-generated transcript, but fail to see how these changes constitute more than 2 hours of work, let alone 3-4 days and ~$1,800. I also spot-checked the timestamps in your file vs the auto-generated time stamps and couldn't find any major differences (<1/20 second difference).

It seems like you maybe used an inefficient process to create the English reviewed transcript (hence the different timestamps), and that might be where our misunderstanding is coming from. Is this the first reviewed English transcript you have compiled?

@zsluedem, it looks like you have experience getting and reviewing the youtube auto-generated transcripts. Can you comment on the amount of time this takes?

**Comment by zsluedem** [comment]
@Jake-Gillberg For a one-hour videos , it would take about 1.5-2 hours to review the English transcripts.(For me ,it would take a little longer because I am not an English native speaker)

**Comment by Ojimadu** [comment]
I agree with much of what Jake Gillberg has said but I don't think the negative budget given to this issue is equitable. The participants might have erred but clearly work was done and should be rewarded based on the result. Giving a large negative reward seem to me like a disincentive. I don't know how the Negative budget works, if it affect the participants rewards on other issue or not. 
@Keaycee thinks it's more of personal sentiment that @Jake-Gillberg and @dckc voted a negative budget on this issue. We shouldn't create/imply a situation that anyone feels he/she is being targeted or anyone is on a vendetta. I see that among issue #462, #463, #464, #465, #488 and #500 only #462 and #463 has a negative budget while all of the issues mentioned above stemmed from this issue. 

@Jake-Gillberg and @dckc I would suggest that the negative votes on #462 and #463 be reviewed based on the results of work done.

**Comment by Keaycee** [comment]
@dckc I answered that seven days ago. Can you check the history of the budgetvote on #462 on the webApp. The budgetvote was placed firstly by a participant. I was the third person seconding the budgetvote when it was $5,000 on the webApp. There was no intent to defraud the system as most voting actions are base on my explanation seven days ago. 
@dckc, I replied earlier the basis for the calculation at $1800. @JakeGillberg says he values transcript at $0.05 (around $400 based on his calculations) but voted $100 because he opines that the work would be done on two hours for a person with skill. Only to vote a largely negative budget later on.
About the $5000 vote, I sent a reply four days ago. I admit I made a mistake there but you subjectively decided that the downward budget review was an intent to defraud of which there was no such intent.
I understand that @dckc and @Jake voted on this issue based on their personal assumptions but I don't understand the rationale behind the negative votes given on #463 as well.

**Comment by dckc** [comment]
At [@lapin7's request][1], the current pay period in the web app is now **201804** and we can no longer edit **201803** votes. I suppose we are now into the **Centralized Payment process** part of [the program][2] for March. I get the impression @lapin7 is reviewing invoices with translation work, so he can take your responses into account.

[1]: https://github.com/rchain/bounties/issues/563#issuecomment-379461106
[2]: https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md

**Comment by lapin7** [comment]
@dckc 
> I suppose we are now into the Centralized Payment process part of the program for March.

Technically we're in the Centralized state, but the rest is pretty decentralized. I only check if invoices are technically speaking OK. I don't check the arguments for entries. So generally I won't take any responses into account. Too time consuming.

Everybody can discuss votes, but that does not change the rewards or budgets. **Only the figures** entered in the [Bounty App](https://rewards.rchain.coop/) change the averages.

## It's about the numbers not the text.
Explanation of numbers comes later, if needed.
