### ISSUE TITLE
M> Translate Exclusive Chat Jake  Brukhman  & Kenny Rowe (Crypto Talk on Rise) Transcript to Spanish

### ISSUE THREAD

**Issue by Keaycee** [rchain/bounties#463]
## Goal:  Translate Video [Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) to Spanish

**The file name is**: [[TRANSCRIPT][.srt][English] "Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://docs.google.com/document/d/1-SsnE2rHlULBK5CR41re0OW_pxf4ubpwySTfqiuKjZM/edit?usp=sharing)"

**Save translated transcript in**: [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)

- [x] Translate to Spanish
- [x] Check for correction errors
- [x] Reviewing and proofreading
- [x] Upload Transcript 
- [x] Translate transcript within 3 weeks

## Time: 3weeks

**Comment by dckc** [comment]
Please pay careful attention to the revised ISSUE_TEMPLATE for translation issues that from @ICA3DaR5 and others?

  - Why this document? (mark all that apply)
    - [ ] it's one of the /rchain/reference documents
    - [ ] I contacted the author, who agreed it's important to translate
    - [ ] I know a person or audience who would benefit from it: _____
    - [ ] other: ___
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in (the target language)
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Jake-Gillberg** [comment]
@Keaycee, why didn't you respond to @dckc? If you are going to do work in the bounty system, please follow the requested format.

Also @Keaycee, @BelovedAquila, @kaka56, @Viraculous, please explain the $2000 budget when .20/word would put this translation issue at $1862.60

**Comment by Jake-Gillberg** [comment]
I believe that subtitle translations are worth much less than video translations. I appreciate your work, but I am currently valuing video subtitle translations at .05/word, not .20/word.

**Comment by Keaycee** [comment]
@Jake-Gillberg Thank you very much for reviewing it. I used the microsoft office word count. i guess it includes the timestamp. But i have reviewed it on a plain text. The budget on this issue has been reviewed also as suggested above.

**Comment by Jake-Gillberg** [comment]
@Keaycee, My suggested budget for this issue is $0.00 because you have failed to follow the standard protocol of the translation issue template set up to ensure quality translation work, and did not correct this or respond when asked by dckc.

**Comment by Keaycee** [comment]
@Jake-Gillberg I did follow instructions of @ICA3DaR5 . However, i was unable to put in the template. This is system is decentralize and collaborative. dckc posted the template, but it would be more better if he had edited my comment and make the corrections. But i'm very certain to have followed every instructions and my work is good. Please @Jake-Gillberg and @dckc Review your vote on this issue.

**Comment by Jake-Gillberg** [comment]
>  our plan to keep the translation up to date is: ____
> significant reputation (e.g. a diploma) at stake; source: ____
> a track record of quality work on rchain bounties: #nn, #nn, ...

@Keaycee These blanks are here for you to fill out. Please fill them out in addition to just checking the box.

**Comment by Jake-Gillberg** [comment]
See above comments and comments in #462 for the reasoning behind changing my vote to a large negative number.

**Comment by Keaycee** [comment]
@Jake-Gillberg The amount of time i spent doing my job does not matter, What matters is the quality of work done. To download an auto generated subtitle file only takes minutes. What consumes more time is the reviewing and correction on the script. @Jake-Gillberg Kindly put up the whole conversation i had with you on discord on here for everyone to see.
@Jake-Gillberg I understand you have personal problem about translation jobs, but it think it's more personal voting -99999 and @dckc voting -5000. I made reference to issue #251 . You can take a look at the budgetvote on issue #251 on the spreadsheet in january.
12,000 @Whisker17 
14,000 @Tonyprisca13 
10,000 @LiliNL 
10,000 @kaka56 
10,000 @Viraculous 
10,000 @Mervyn853 
11,500 @noordaa 
12,000 @ICA3DaR5 
12,000 @BelovedAquila 
10,000 @lapin7 
10,000 @Ojimadu  
All this votes was as a result of the misleading vote made by one person and was seconded by other participant. However, the budget was corrected $1,000 by @lapin7 regardless of the vote of outrageous votes of the participants.  Again, sometimes members vote outrageously because of the misleading votes placed by others. Looking at the votes above, the intent was never to defraud the system, but rather vote seconded to backup the first example of vote placed. 

The spreadsheet is no longer in use and some coop members do not know how to use the  webApp effectively.


Now @Jake-Gillberg and @dckc  voting an outrageous negative vote on issues created by me. I must say, if issue 462 was created by @lapin7 you both will have that decency not to behave or act like this. But because it was created by @keaycee .  

What justifies your act of negatives vote, was it the conversation on discord or comments on github or the quality of work done? @Jake-Gillberg 

@dckc and @Jake-Gillberg I think you guys are trying to centralize this system and also discourage coop members. We don't have a lot of participating coop members on github and many of them aren't active members. 

I understand that @dckc @Jake-Gillberg do not support my work, thereby calling other friends to downvote my budget. This is no longer official, rather a personal decision of loathing and resentment.

The system is decentralized and collaborative, we're here to collaborate with other coop members for the best interest of RChain, and not to discourage coop members from participating. 
Example: If Mr A spot an error where Mr B doesn't see it, as a coop, It's up for Mr A to address or correct such errors rather than leaving it for Mr B to spot it out. 
As we collaborate together, correct errors together, we learn and don't make same mistakes tomorrow.

**Comment by Keaycee** [comment]
![screenshot 114](https://user-images.githubusercontent.com/34557673/38243094-c213af00-3736-11e8-80ad-01080c3481c3.png)

![screenshot 113](https://user-images.githubusercontent.com/34557673/38243118-ce2515cc-3736-11e8-85ed-507274c5f3fa.png)
