### ISSUE TITLE
M> Translate Exclusive Chat Jake  Brukhman & Kenny Rowe (Crypto Talk on Rise) Transcript to French 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/bounties#464]
## Goal:  Translate Video [Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) to French 

**The file name is**: [[TRANSCRIPT][.srt][English] "Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://docs.google.com/document/d/1-SsnE2rHlULBK5CR41re0OW_pxf4ubpwySTfqiuKjZM/edit?usp=sharing)"

**Save translated transcript in**: [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)

- [x] Translate to French 
- [x] Check for correction errors
- [x] Reviewing and proofreading
- [x] Upload Transcript 

## Time: 3weeks

**Comment by ResonanceXX** [comment]
00:13 reads **Jake Brookman** Title page reads **James Brookman**

Minor adjustment. Cheers.

**Comment by BelovedAquila** [comment]
@ResonanceXX yes thanks its actually Jake Brukhman not Brookman though

**Comment by BelovedAquila** [comment]
Work completed!

**Comment by BelovedAquila** [comment]
Uploaded and done.

**Comment by BelovedAquila** [comment]
Uploaded and done.

**Comment by Jake-Gillberg** [comment]
@Tonyprisca13, @Viraculous Please justify the $3000 budget.

@kaka56 Please justify the $2500 budget.

 At .20/word this issue is would be worth $1862.60

**Comment by Jake-Gillberg** [comment]
I believe that subtitle translations are worth much less than video translations. I appreciate your work, but I am currently valuing video subtitle translations at .05/word, not .20/word.

**Comment by BelovedAquila** [comment]
@Jake-Gillberg Thank you, but actually we didn't just work on transcripts with just subtitles, we had to also watch the video over and over again to bring about a precised translation, it's doesn't just takes a kind of copy and paste swift to compile it, it also takes time and other vital factors which I think you haven't considered.

**Comment by Tonyprisca13** [comment]
@Jake-Gillberg the word count i got was around  20000 plus, i made an estimate based on that.

**Comment by Jake-Gillberg** [comment]
@BelovedAquila please be honest here. Issue #462 provides an original English subtitle file from which you can translate. Why would you need to "watch the video over and over again" in order to translate that text file?

Also, this is not a technical document, so the ["standard" translation price of $.20/word is DOUBLE the industry standard](https://www.google.com/search?q=translation+price+per+word&rlz=1C1CHBF_enUS732US732&oq=translation+price+per+word). Please don't claim "other vital factors" without further substantiation for your vote of $2,000, or I will have to assume your intent is to defraud the bounty program.

@Tonyprisca13. Please explain how you get a number **>2x** the number that I got. Doing a word count of the original English subtitles found in #462 gives me 9,314 words. Please explain or I will have to assume your intent is to defraud the bounty program.

**Comment by Tonyprisca13** [comment]
@Jake When the document is open via google doc click on tool then the word count you will see description under words to 20482

**Comment by Jake-Gillberg** [comment]
@Tonyprisca13 That document has timestamp information which is included in the word count.

```
1
00:00:03,600 --> 00:00:07,069
Let's do this guys. Hi everybody welcome.
```
^ google docs counts these 7 words as 16 words. This more than doubles your estimate. Why would you include timestamps into the word count?

**Comment by Tonyprisca13** [comment]
@Jake-Gillberg thought those where the word alone not knowing it included timestamps

**Comment by BelovedAquila** [comment]
@Jake-Gillberg you don't have to plea for honesty friend, it's deserving. 
 yes issue #462  provides for an original English subtitle file, but doesn't mean one needs rely solely on its accuracy that would be a cheap assumption which might be a jeopardy to the sole aim of making a professional concised  and precised transcript I believe you understand what it means to " review " and I believe you understand that consecutive reviews results in less chances of inaccuracies or errors? I believe that answers the first question friend.

About your second proposition, your inference made on assumption is an ad hominem  drawn  on bases of  ignorantio elenchi one doesn't just make assumptions as costly as that on another on no vital basis,but it's fine. Actually me relating to other factors is in relation to the fact that job done on each language differs in its uniqueness,that is quite indisputable no matter how we try to create a balance. Yet I think I understand the point here à bit clearer, we are dealing on " a word count " and not just what we find appropriate to the job and efforts made,well then, would like to understand what gives you your word count figures? Need understand the reasons for the discrepancies please.

**Comment by kaka56** [comment]
@Jake-Gillberg my error was that I included timestamp. And I still tried to reduce the budget to what I think is fair.

**Comment by Jake-Gillberg** [comment]
@BelovedAquila If this translation required more work than the translation to Chinese or another language for some reason, then please tell me that reason.

Remove the timestamps and re-count the words. I get ~9312.

**Comment by kaka56** [comment]
Alright

**Comment by BelovedAquila** [comment]
@Jake-Gillberg ok, I see. There would be a readjustment of the budget. 
But as suggestion please, I think it's worth it for the prices of each translation to be made know on time, so one don't get to fall into cheap assumptions like this. I mean, if as it looks, you are handling  translation supervision, please on the creation of the issue, please try drop an estimate of an appropriate price there, perhaps one could be sure ahead of time on what is attainable from a good source. If there is a need for questioning or commenting on the price, it did would have been done and settled before hand, because somehow this our late procedures affects the overall bounty timing. And you know what? It becomes  easier to ascertain when one willfully insisted on a budget (inappropriate budget)Please I hope you get a bit of my point?
But, there would be an adjustment of this issues budget

**Comment by BelovedAquila** [comment]
@Jake-Gillberg I realized there have been a negative budget place, please if you don't mind, there is a need for it all to be readjusted, as we have come to an understanding and I believe our deliberations on this issue has been resolved? Right?
So please, I appeal to you, @dckc and as well @kaka56 to please adjust the budget please. Thank you for your supervision @Jake-Gillberg

**Comment by dckc** [comment]
Your original budget votes remain. You have neither changed them nor justified them. I see no information about credentials of translators, for example. I don't see any resolution.

**Comment by Jake-Gillberg** [comment]
My estimate of worth seems to be $465, backed up by Kenny in the #bounties discord channel.

**Comment by BelovedAquila** [comment]
@Jake-Gillberg ok I think I understand, your worth on the translation issue. At $465?,may I ask on what basis and who are this OTHERS on whose backing you came across such unfair estimate please?we don't tend to put into consideration people's time and noble efforts, do we?

**Comment by dckc** [comment]
@BelovedAquila writes:
> I adjusted the budget and I checked, other voters did.

Ah. so you did. My mistake. I adjusted mine now. (_Darn! Editing a vote doesn't update the vote time. I had to delete it and add it again to make the vote time right._)

about credentials of translators... this comes from [ISSUE_TEMPLATE][IT]:

>  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
>    - [ ] several reviewers are involved (_assign the ticket to them_)
>    - [ ] at least two of them have high proficiency in (the target language)
>    - [ ] at least two of them have high proficiency in English
>    - [ ] at least two of them have either
>       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
>       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...

[IT]: https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md

So who are the several reviewers and what do we know about their proficiency in English and French?

**Comment by Jake-Gillberg** [comment]
@BelovedAquila tagging others who I believe support my position that:
 1) Video transcript translation should not be valued as high as written document translation,
 2) $.05/word seems like a reasonable start, putting an hour long video at about ~$500 (this one at $465).

Tagged people below, if you do not support the above position, please let me know or edit this comment to remove your name for the list. Also, if anyone else supports this, feel free to chime in.

@dckc 
@kennyrowe 
@Staff91 
@ian-bloom 
@klysford 
@ICA3DaR5 
@kdvalentine 
@RollandWaters 
@kitblake 
@jplepel 
@Barkov-F

**Comment by BelovedAquila** [comment]
@dckc thank you, it's now clear. But where should I fix that?
@Jake-Gillberg you seem not to be even sure of the OTHERS referred to,

> if you do not support the above position, please let me know or edit this comment to remove your name

and this already sounds like an ad Baculum , so Logically we can't be expecting a feedback as against it.

**Comment by Jake-Gillberg** [comment]
@BelovedAquila I have evidence to believe the support of these people, but I do not like speaking for others without at least giving them a chance to reject or respond.

dckc - has made votes of ~465 on similar issues (check rewards.rchain.coop)
kennyrowe - expressed this opinion on discord in the #bounties channel
staff91 - "liked" the comment about $.05/word in #488 
ian-bloom - through many private conversations
kdvalentine, RollandWaters, kitblake - We met last Saturday to discuss these issues, there were no dissenting opinions expressed of the above claims expressed
jplepel, barkov-F - responded positively to the messages about these issues in #bounties channel of discord

**Comment by Barkov-F** [comment]
I have concerns about the localization efforts in general. As I see it, the
coop doesn't have a pipeline for these kind of activities. For example, the
translation that I've made (issue 285
<https://github.com/rchain/bounties/issues/285>) is still unpublished and
the value of unpublished work is exactly zero. My impression is that that
we should attract new developers to the project. In this case translators
should concentrate on the rholang tutorial and other documents that will
help to on-board new coders.  These docs are highly technical and in my
view high rates of $0.2-0.3/word are justified. I can make a poll on Loomio
to help us to figure out the list of the artifacts that require translation
first.

**Comment by klysford** [comment]
@Barkov-F - I agree that the value of untranslated work is zero :)  I like the idea of first using the translations to bring in new developers (so translating the tutorials and coding documents).  Could you send me a list of the artifacts that require translation once you do that?  I would love to try to incorporate in anything I attempt going forward :)

@Jake-Gillberg - I agree that video translations aren't as necessary - most of what is talked about (correct me if I'm wrong) is something that would be mentioned in a tutorial, in blog posts, or is just filler interview information that doesn't really add much.  

As mentioned, if you don't have the English transcript I think it takes more effort than it's worth to type it out and then translate it - if it WAS needed it would be better (in my opinion) to have native speakers then transcribe it for a set cost and then post it for the translators of all languages to look through instead of paying multiple people to write down the English and have a larger room for error.

**Comment by Jake-Gillberg** [comment]
@klysford The standard way for getting the transcript is to download the youtube auto-generated transcript and clean it up. This takes on average about 1.5 - 2x the length of the video. The English transcript for this issue was provided in #462

**Comment by jplepel** [comment]
I am with @Jake-Gillberg on his position. Sure some documents garner higher rates (ie. Technical, Official coop documents), a Loomio poll would be appreciated. 

My main concern is individuals potentially taking advantage of the bounty program by translating any Rchain related content for a high bounty. This talk with Kenny is one of them, while it was a great chat, there were only 400 views the past month. Coop funds can be better spent to spread awareness across different cultures and languages. 

In my eyes, before deciding weather non-critical documents should be translated, we should look at the following factors...

1. Content Reach 
   -ROI, Have a significant # of people viewed content?
Ex. Two similar interviews 
   -Epicenter W/Greg&Nash 28k views
   -Rize Crypto Talk W/Kenny 400 views

2. Translation Demand
   -Are there people asking for translation?
   -Does this market understand English/Native content language?

3. Method of Distribution
   -Where will the content be posted?

**Comment by tcezi** [comment]
@Jake-Gillberg  there are lots other translation with high budget: 
[480](https://github.com/rchain/bounties/issues/480) -$3000 
[482](https://github.com/rchain/bounties/issues/482) -$4000 
[498](https://github.com/rchain/bounties/issues/498) -$5000
[527](https://github.com/rchain/bounties/issues/572) -$3000
[528](https://github.com/rchain/bounties/issues/528) -$4000
why are they not mention in your documents of thought on translation? and also nothing is been said on these issue about there translation budget
@dckc  do other translation have translator credentials? 
This seem like an Ad Hominem and has some sentiment attached this is my opinion

**Comment by dckc** [comment]
> @dckc did other translator provide translator credentials?

Yes.

**Comment by Ojimadu** [comment]
@tcezi writes:
> @Jake-Gillberg there are lots other translation with high budget:
480 -$3000 instead of $1658
482 -$4000 instead of $1130
498 -$5000 instead of $2162
497 -$2500 instead of $1252
499 -$2300 instead of $565
502 -$3200 instead of $1252
528 -$4000 instead of $1252
why are they not mention in your documents of thought on translation? and also nothing is been said on these issue about there translation budget, would like you to have a look on this issues as well.
@dckc did other translator provide translator credentials?
>
@klysford Perhaps you may want to look at the issues raised by @tcezi. Jake probably has lots already except he is looking at them too.

**Comment by tcezi** [comment]
Personally i think this has some element of Ad Homen which isn't good for the coop

**Comment by dckc** [comment]
Still no response to "How can people who do not speak this language be assured of the quality of the translation?"
