### ISSUE TITLE
M> Translate Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) Transcript to Chinese

### ISSUE THREAD

**Issue by Whisker17** [rchain/bounties#465]
## Goal:  Translate Video [Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) to Chinese

**The file name is**: [[TRANSCRIPT][.srt][English] "Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://docs.google.com/document/d/1-SsnE2rHlULBK5CR41re0OW_pxf4ubpwySTfqiuKjZM/edit?usp=sharing)"

**Save translated transcript in**: [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)

I'll finish it with @han014

**Comment by Whisker17** [comment]
when the English transcript finished,this translation will start

**Comment by Keaycee** [comment]
I will be done with the English transcript in a few

**Comment by han014** [comment]
Good.

**Comment by Keaycee** [comment]
I'm done with the corrections on the English transcript. You may start @Whisker17

**Comment by Whisker17** [comment]
@Keaycee  Fine,I'll finished translation in a week with @han014

**Comment by ResonanceXX** [comment]
@Whisker17 @han014 Check out **Jake Brukhman**

Minor adjustment to the name already on the srt. file. To avoid delegation of duty Ive went ahead to make the little adjustment. 

![screenshot-2018-3-7 jake brukhman - google search](https://user-images.githubusercontent.com/34219332/37074893-52a48058-21cf-11e8-8692-5680a32a54c6.png)

**Comment by Keaycee** [comment]
@Whisker17  I have included the timestamps

**Comment by Whisker17** [comment]
@Keaycee  Good job!
I'll start translation now.

**Comment by ICA3DaR5** [comment]
@Whisker17 Please assign the contributors.

**Comment by Whisker17** [comment]
@ICA3DaR5  @han014 will work with me,but I can't assign him,I don't know why

**Comment by lvsik** [comment]
good jop

**Comment by lvsik** [comment]
good job!

**Comment by lapin7** [comment]
@han014 cannot be assigned until he accepts the collaborator invitation
https://github.com/rchain/bounties/invitations

**Comment by han014** [comment]
I have accepted the invatation. Thanks for your help.

________________________________
发件人: HJ Hilbolling <notifications@github.com>
发送时间: 2018年3月21日 16:47:18
收件人: rchain/bounties
抄送: #LU; Mention
主题: Re: [rchain/bounties] M> Translate Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) Transcript to Chinese (#465)


@han014<https://github.com/han014> cannot be assigned until he accepts the collaborator invitation
https://github.com/rchain/bounties/invitations

―

**Comment by lvsik** [comment]
WOW

**Comment by lvsik** [comment]
I have accepted the invatation. Thanks for your help.

**Comment by lvsik** [comment]
@lapin7 ,Hi,HJ,I wanna contribute to RChain,and I've pay the $20,but I can't enter the Discord,it says "the email is invalid",so what should I do next?

**Comment by kitblake** [comment]
@lvsik Join via https://discord.gg/fvY8qhx then ask admin about verification..

**Comment by Keaycee** [comment]
@Whisker17 Please what's your name on Discord?

**Comment by Whisker17** [comment]
@Keaycee my discord name is whisker，anything happened？

**Comment by Whisker17** [comment]
@lapin7  This transcript‘s word account is 8897,since the price of a word is $0.2,so I think the total budget should be $1800,but I've set the budget for $1200,how can I alter the budget in [here](https://rewards.rchain.coop)

**Comment by Whisker17** [comment]
done

**Comment by Jake-Gillberg** [comment]
I believe that subtitle translations are worth much less than video translations. I appreciate your work, but I am currently valuing video subtitle translations at .05/word, not .20/word.

**Comment by Jake-Gillberg** [comment]
@han014, @lvsik, @Whisker17. I know that the standard in the past has been $.20/word for translations, but please re-evaulate your budget votes given that:

1) The market rate for non-technical document translation seems to be at $.10/word (not $.20/word) and
2) Video translations are not worth as much as written document translations, so somewhere around $.05/word would be a good start. This would put an hour long video translation at about ~$500. (see conversation in #bounties channel on discord where some support was given from Kenny around this price)

I suggest $465.65 for this issue.

I appreciate the translation work and the professionalism of the Chinese RChain community that is interacting with the bounty program. I hope I am not insulting with this lower valuation of work. My wish is to direct you towards work that both the community and yourselves as translators will receive more profit from 😄.

**Comment by Whisker17** [comment]
@Jake-Gillberg  That's not a problem,I think this is a great try to approve the Community.
