### ISSUE TITLE
RChain Netherland Group. Is No SCAM ALERTE ON?

### ISSUE THREAD

**Issue by Pionelle** [rchain/bounties#466]
# A Goede dag. The Telegram group is there no SCAM ALERT. This is problematic as Dutch members will not know about the issue circulating. Also not every member of Dutch RChain is on the English Channel. The Pinned message on Dutch channel reads - Direction to English chanel.

I propose to translate the other versions into Dutch of this Scam Alerte to notify the Dutch Members as well.

Measure of Completion:  A few days
Suggested Budget:

**Comment by Pionelle** [comment]
Whoever is willing to help me with the source document as well. Is good too.

**Comment by kitblake** [comment]
Hi @Pionelle, the Dutch users are also in the @rchain_coop Telegram group and at ease with English so there's no need to translate the pinned message to Dutch. But thanks for your concern. I put a wontfix label on this issue and, unless other Dutch users disagree, we can close it.

**Comment by Keaycee** [comment]
@Pionelle  you are welcome to contribute in the translation projects of your stated languages.

Please Signup 
- Join https://groups.google.com/forum/#!forum/rchain
- Accept https://github.com/rchain/Members/invitations
- Send your email address + github name to ops@rchain.coop

**Comment by Pionelle** [comment]
@kitblake That is okay. That is fine too,will the users other ones be around here.

**Comment by Pionelle** [comment]
@Keaycee Thank you so much, I have followed the links, 


Thanks.

**Comment by kitblake** [comment]
Welcome onboard @Pionelle. Let's close this.
