### ISSUE TITLE
Newsletter - March 7th, 2018

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/bounties#467]
Anyone who had a part in this newsletter can say so here. Here is the [google doc](https://docs.google.com/document/d/1Va_u-I_IWCvpWVgQXNKsFuhpaH-enouhPotJMTGoiRM/edit) with the notes for all the hangouts.

**Comment by Tonyprisca13** [comment]
Did some editing and correction

**Comment by ResonanceXX** [comment]
Hello Devs. Hello @Tonyprisca13 
 Made minor changes.
 **Pythia** was a greek biologist. 
The venture website reads www.pithia.com. 
 Should every sentence end in a full stop.  Some do
I could change that?

**Comment by ResonanceXX** [comment]
changed those! Cheers!

**Comment by TrenchFloat** [comment]
Oops. The Pithia/Pythia mixup was my bad. Thanks @ResonanceXX
