### ISSUE TITLE
WikiHow: How To Join The RChain Cooperative Community.

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#468]
#  Basically, trying to describe the process of joining the Cooperative. More Importantly, by utilizing WikiHow's excellent Point layout system (and maybe effective imagery).
The WikiHow search results would come up especially when searches are inquisitive.
And in combination with excellent materials detailing this same process, provides a varied source of information to potential members.
It is advantageous to have info about **RChain's membership** process available to prospective members who may engage Google in that regards.

**Wikihow in 2005, had about 35 Million unique website visitors.**

Measure of Completion: **Done** Progressing.
Suggested Budget: $400 - 1800

  - Why this document? (mark all that apply)
    - [ ] it's one of the /rchain/reference documents
    - [ ] I know a person or audience who would benefit from it: _____

    - [ ] several reviewers are involved (_assign the ticket to them_)
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...

**Comment by ResonanceXX** [comment]
https://www.wikihow.com/Join-the-Rchain-Cooperative-Community?new=1

This is the Link to RChain's descriptive process of joining the Cooperative.
I would admire a critical evaluation of the processes, especially if there were inconsistent flow in the hierarchy.
Editorial guidance where necessary.
**Pending approval**

**Comment by ResonanceXX** [comment]
**Already Published**

 Cheers.

**Comment by ResonanceXX** [comment]
![screenshot-2018-3-8 welcome to rchain - membership](https://user-images.githubusercontent.com/34219332/37186508-27d7940a-2346-11e8-96e5-3cc3edbaab92.png)

**Comment by ResonanceXX** [comment]
![screenshot-2018-3-9 how to join the rchain cooperative community](https://user-images.githubusercontent.com/34219332/37186522-3b4b52a6-2346-11e8-8aec-83741c85d999.png)

**Comment by Keaycee** [comment]
## on-boarding for newbies

- Join https://groups.google.com/forum/#!forum/rchain
- Accept https://github.com/rchain/Members/invitations
- Send your email address + github name to ops@rchain.coop

**Comment by makys** [comment]
@ResonanceXX Can you put this process in a googledoc for community review before this is approved. The process you outlined doesn't seem right, at least that is not how the process should flow. We want to encourage new members to start by signing up for membership and be on-boarded which appears to be the step 4 in your process. Also we should be consistent in the way we spell RChain ("RC" is in uppercase and "hain" in lower case.

**Comment by ResonanceXX** [comment]
Hello @makys, Yeah. Since its domiciled with Wikihow, you'd know that the website exhibits control over the text character and fonts.

Especially for the header, where each word starts with a Capital letter. In a situation where R-C is spelt in Capital letters and kept together, the codes written by Wikihow, forcefully modifies the text to suits its content descriptions (maybe for better viewing).

I have scanned the text, and that seems to be the only instance of a deviated spelling for RChain.

About  step 4. The process of onboarding was preceded by the Github member registration and a Google account setup. (Maybe such a person lacks a functional email.) These other processes allows, for a primal knowledge of how the Coop works.
There is also a motivation to part with that sum, in the instance where the potential member has seen the validity (manifestation) of our claims as a cooperative here on Github.
Our membership fee may not be a lot of money. 
But for people, especially from developing countries, it could be quite substantial.
 I've made an effort to not scare away potential members from such Countries by providing a subtle approach to the paid membership phase of joining.

Cheers!

**Comment by BelovedAquila** [comment]
@ResonanceXX Actually you are putting up a good proposition,but i suppose its not functional yet right?Because i tried checking it out on google but no headline as that.

**Comment by ResonanceXX** [comment]
@BelovedAquila yes. In fact I'm patiently waiting for more edits to be made. Pictorial supplementation of the current information. I have to give more time for better informed coop members to criticize and make amendments where necessary. 

Sent from Yahoo Mail on Android 
 
  On Tue, 27 Mar 2018 at 6:21, BelovedAquila<notifications@github.com> wrote:   
@ResonanceXX Actually you are putting up a good proposition,but i suppose its not functional yet right?Because i tried checking it out on google but no headline as that.

**Comment by BelovedAquila** [comment]
Alright, nice one friend. @ResonanceXX

**Comment by ResonanceXX** [comment]
I have received an email that conveyed congratulations on my article helping **72 persons** learn something new in this few weeks alone. This further propped my investigation, which revealed that although not - Search engine accessible - This article can be found from a search on WikiHow's website. 
I had previously assumed that pending varied edits and/or contributions (from esteemed Coop members), the article could be domiciled just for 'my view'. 

And so I wish to announce that this article is 'live' for now. The information contained therein being accurate, but lacking consensual ratification.
Anna from Wikihow, has however invited me to return and contribute some more. 

Cheers!
![screenshot-2018-4-1 kudos for your hard work - inbox - yahoo mail](https://user-images.githubusercontent.com/34219332/38172708-40a5787e-35a9-11e8-8471-cc17cafb42ee.png)

**Comment by ResonanceXX** [comment]
But then I have a personal obligation to work towards further completion of the whole article. Given that above, plenty of thoughtful opinions had been laid down. 
Presently looking to bolster the quality with some crucial imagery.

**Comment by BelovedAquila** [comment]
@ResonanceXX that's progressive, I believe by virtue of this, they would be more questions popping out from it, which I know wiki created an avenue for, am suggesting you see to it that  appropriate answers are been given, so as for any not to be misled. Nice one

**Comment by ResonanceXX** [comment]
This is always certainly a good one. The moratorium for other inputs on this issue is thinning down. And plenty more people are landing on the page for information. So this is going to be the resurrection of more work on this.

**Comment by ResonanceXX** [comment]
Wikihow.com recommends dutiful patience because editing and approving Articles for SEO and regulated status by Wikihow depends on volunteers.
According to Wikihow, these volunteers are not online 24/7 and as such this could take a bit of time.

**Comment by ResonanceXX** [comment]
**Be patient. Our volunteers are not on wikiHow 24/7, and getting your article approved takes time.

    If you want to work on the article while you wait, it can help to check out the Writer's Guide and formatting guidelines to get a better idea of all of the requirements for a wikiHow article. wikiHow's Boosters are often happy to help with those details, but if you want a quick promotion, it doesn't hurt to get everything ready to go.**

**Comment by TrenchFloat** [comment]
I'm going through and cleaning up parts of the issues list; this looks like it's done.
