### ISSUE TITLE
M> Review `Introducing Rholang` video's subtitle and translate to chinese

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#470]
It is a [video on ethereum devcon3](https://www.youtube.com/watch?v=7tW1fAWg6s8) which introduces **Rholang** in detail. I'll review the correctness of the subtitle and make a translation.

Since `youtube` is not available in china, so i'll download the video, add the translated subtitle and upload the video the rchain chinese wechat official account to let more chinese know it.

Task:
- [x] Upload and Review the subtitle (I have uploaded the original subtitle with review [here](https://drive.google.com/drive/folders/1Gd8g398lNoxZRXLCGGI2fmbMhQuIIx41))
- [ ] Translate the subtitle
- [ ] Upload translated video to wechat official account

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

Measure of Completion:  
Suggested Budget:

_See CONTRIBUTING.md for details on budget and reward process._

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
    - [x] I contacted the author, who agreed it's important to translate
    - [x] I know a person or audience who would benefit from it: _____
    - [x] other: ___
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: ____

**Comment by zhanghebei** [comment]
Why not upload to youku or bilibili?  You can go to QQ group to find youku account or bilibili account
