### ISSUE TITLE
Working group to define our values and principles

### ISSUE THREAD

**Issue by jimscarver** [rchain/bounties#471]
Development of the values and principles sub-group created from the governance working group shepherding the process of determining the official rchain values and principles.
[working document](https://docs.google.com/document/d/1Sv0iPxufWezcKsQKrIoI3EXMEgvvAzXQN2Pjsn3jIcI/edit#)

Measure of Completion:  
Executive committee and marketing WG approve publication of the RChain principles and values

Suggested Budget:
The level of effort and number of people engaged in this process is variable but we hope to maximize it. Assuming 10 people contributing an average of 3 hours each, 30 hours at $50 we get a budget of $1500.
The working group will suggest an actual budget at a later date.

_See CONTRIBUTING.md for details on budget and reward process._

**Comment by llerner** [comment]
Love it! Looking forward to seeing the rest. 

1. SIgn me up!
2. For those of us who don't care to receive the bounty, can we identify a series of charitable contributions from the Co-op? 
3. Per our Abundance mentality, can we take the wealth we are sharing and distribute it to others? Perhaps as identified as part of this group's charter?

Comments?

**Comment by ResonanceXX** [comment]
@llerner  Your suggestion is wonderful to note. This is an important part of many a Blockchain organization's operations globally. 
**For instance**
 1). Dogecoin in 2014, raised about 26 Million in Dogecoin currency. ($25,000). This was raised for the **Jamaican bobsleigh team** competing in that year's winter Olympics.
https://www.theguardian.com/technology/2014/jan/20/jamaican-bobsled-team-raises-dogecoin-winter-olympics.

2). **GiveDirect a notable charity organization in Kenya received some form of assistance/funding from the **Pineapple Fund.**
The charity  provides unconditional cash transfers to people living in extremely poor communities
http://www.independent.co.uk/news/business/news/bitcoin-universal-basic-income-donate-millions-crytocurrency-pineapple-fund-givedirectly-digital-a8132731.html
3). There other examples of charitable acts by Blockchain companies either willingly or as CSR (Corporate Social Responsibility).

**Comment by AyAyRon-P** [comment]
If we move forward with the CO-OP as a full adoption, we could leverage the CO-OP identity as our principles which would be a great addition to RCHAIN's own principles. These principles are:  

- Voluntary and open membership
- Democratic member control
- Economic participation by members
- Autonomy and independence
- Education, training and information
- Cooperation among cooperatives
- Concern for community

By fully adopting this ICA brand we can also use their values:

- Self-help
- Self-responsibility
- Democracy
- Equality
- Equity
- Solidarity

From a brand identity perspective, graphically speaking, by adding CO-OP to RCHAIN we could use this as another opportunity to update current logo(R cattle brand). With this new logo consensus, we could also update our website to reflect our CO-OP brand alliance. 

Reference: https://ica.coop/en/whats-co-op/co-operative-identity-values-principles

**Comment by dckc** [comment]
Great to see this. Note some more or less relevant work: #370, #234, #371, #460.

I see you put it on the [Governance WG project](https://github.com/rchain/bounties/projects/7). I just moved the cards on that project around a bit to reflect what I see as the current status.

**Comment by dckc** [comment]
@jimscarver what does "marketing WG" refer to?

A Feb 27 message from Henderson refers to a "Branding" group led by @pmoorman ; The discord `#working-groups` channel also lists a **Branding WG** lde b @pmoorman and refers to #371. Is "marketing WG" just another name for that? (works for me)

**Comment by dckc** [comment]
@llerner donating bounty rewards was raised in #46. It got closed for lack of movement or something back in January, but anybody who wants to move it forward is welcome to reopen it.

**Comment by pmoorman** [comment]
As far as WGs go, there are 2 onboarding groups ("greeters" and "member portal"). Then there's the branding/website WG that I'm leading.  

I think at the very least the "greeters" group would like to know about the outcomes of the values & principles, so they can integrate it with onboarding.

I would also be interested, as they can further inform branding. 

In my opinion **principles must preceed branding (and marketing). The branding WG should not be required to approve of it.** 
Branding should align with values, rather than the other way around.

**Comment by AyAyRon-P** [comment]
I agree that we need to determine both of those items before we can move forward with flushing out the rest of the brand identity. I think that our values should reflect the principles and that both should be part of the brand when we move forward with the mission and vision statement.

UPDATE: I just saw the diagram in the document 👍

**Comment by Ojimadu** [comment]
@pmoorman Very correct. The greeter group would likely be the first point of call for new members orientation and the part of the orientation would be "Values and principles of the coop".
Since we are a coop, we should align our values with that of a cooperative, from there we can brainstorm on "Purpose, Mission and Vision". 
There has been this question about why RChain is structured as a coop? We need to clearly answer that.

**Comment by jimscarver** [comment]
Yesterday's [meeting notes](https://docs.google.com/document/d/1j3qq3o2FjyjNjMdrmCGnsKqE3bkJPJoPBlQY9o40hdk/edit), video https://youtu.be/tjxhLVXNFYM
weekly meetings are planned for now: [calendar event](https://calendar.google.com/event?action=TEMPLATE&tmeid=N2FlaG9lYjd0NTUyN3I4ZWhxaXFyaWlkaGtfMjAxODAzMDlUMjIwMDAwWiAyY2oxNTJjOW5pZGg2Z2xwcjFkNWc0ZXEyOEBn&tmsrc=2cj152c9nidh6glpr1d5g4eq28%40group.calendar.google.com&scp=ALL)

**Comment by makys** [comment]
I agree with @pmoorman , its a cyclical process where we ("New Member WG" or "greeters") get input from other WG and provide input to the WG based on our interactions with New Members.

**Comment by dckc** [comment]
Someone called Chiamaka Igweka in gdocs added this to this week's agenda (#469). I'm interested to know why. Just FYI? Or is this issue stuck? What's the goal of the agenda item?

@Tonyprisca13 do you know that person?

**Comment by kmoskowitz** [comment]
Hi all- Excited to be working on this!
I am new to Github, was told I needed to comment on this thread to be added/invited.
Please let me know if there is any other action I must take.

**Comment by lapin7** [comment]
@kmoskowitz please accept https://github.com/rchain/bounties/invitations

**Comment by dckc** [comment]
@jimscarver defined the measure of completion as:
> Executive committee and marketing WG approve publication of the RChain principles and values

We're not there yet.

**Comment by AyAyRon-P** [comment]
Is it possible to change the time of this meeting from 2pm PST to something earlier like 11am PST? I'd like to be involved more than just commenting on the document.

**Comment by kitblake** [comment]
+1 on an earlier timeslot, 2pm PST is 11pm in Europe (normally).

**Comment by kmoskowitz** [comment]
I have set up a Doodle poll on some earlier time slots for meeting on Fridays.  Please submit your time choice: https://doodle.com/poll/netezhmeb3gb4it8
This weeks meeting will stay at 2:00 PM PST Friday:  https://zoom.us/j/6853551826
If enough people are up for a change we will move to new time the following week.

**Comment by kmoskowitz** [comment]
After doodle poll we are changing Principles and Values WG meeting time to:
11:00 AM PST on Fridays:   https://zoom.us/j/6853551826
So all upcoming meetings will be at new time.

**Comment by pmoorman** [comment]
Since the branding WG is making good progress on engaging a branding firm to help RChain with revamping it's branding, I'm wondering how much progress this "values & purpose" project has made.

Can someone provide an up-to-date update or overview of the current best state? Then we can take this along in the branding efforts.  (Not sure who to tag. Maybe @jimscarver ?)

**Comment by jimscarver** [comment]
We collected values from members and made a consolidated list
[Values Master List.docx](https://docs.google.com/document/d/1sGh8CRGcbXretGFlNonal59meOQwnLO5yhMRcUcGR9Q/edit#)
Lower in the doc we are adding and reviewing short descriptions of what we mean by each value.
I believe jonathan is coordinating with branding

meetings friday 2pm PST in https://zoom.us/j/6853551826
video of last meeting https://youtu.be/QOekEnXV4yU

**Comment by pmoorman** [comment]
ah, that's perfect.  If Jonathan is already synced, then I'm not worried about it (Jonathan, Patrick and I work on branding together). 

Thanks for the update!

**Comment by barneycinnamon** [comment]
The values poll concluded on May 29 at the end of two weeks live on Discord. The working group will move on to working on principles based on the top values.
Top three values: Collective Intelligence (26), Transparency (25), Sustainability (22)
Next three values: Integrity (16), Decentralization (15), Respect (14)

**Comment by kmoskowitz** [comment]
Just want to add that values derived from the poll were additional values to those already agreed upon as Coop Values:

Democracy
Equality
Equity
Solidarity
Self-Help
Self-Responsibilty

This link contains the most current list and definitions of values used in our Discord poll: https://docs.google.com/document/d/1QjWxmTrR_Qx2s_x5IKMSyruQDZCw_1-VCD2o58w_Icc/edit <https://docs.google.com/document/d/1QjWxmTrR_Qx2s_x5IKMSyruQDZCw_1-VCD2o58w_Icc/edit>

**Comment by allancto** [comment]
Yes, i believe those six, 3 and 3, will be off enormous value to our cooperative. Thanks @kmoskowirz

**Comment by kmoskowitz** [comment]
No they are Values we already ascribe to from the ICA Coop Values and Principles:https://ica.coop/en/whats-co-op/co-operative-identity-values-principles

The reason I brought that up is that the Discord poll lists our Coop Values:

Democracy
Equality
Equity
Solidarity
Self-Help 
Self-Responsibility 

and asks: What ADDITIONAL values do you personally feel Chain Coop should ascribe to and apply in the operation of the Coop?

**Comment by jimscarver** [comment]
It is time for a final review of [Results of Members Discord poll ending 5/29/2018](https://docs.google.com/document/d/1XZFEcURYVLjDHMVqlbULxhq8UqGzml5lns7W-xr4VOU/edit) document.

Outstanding are how many of the values do we propose to be coop values and how do we derive principles from these values. https://diglife.com/principles/ is a result of a similar process we did in the digital life collective.

Meeting attendance has dwindled. Is friday 2pm PST not good for people?

**Comment by barneycinnamon** [comment]
@ian-bloom @dckc I am ready to declare mission accomplished and close this issue, but I wanted to check on the final resolution. Did the executive committee or board review the submission from the working group?

**Comment by dckc** [comment]
> ... Did the executive committee or board review the submission from the working group?

No, I don't think so. I don't recall review by the EC and I didn't see any mention of it in board minutes.

**Comment by kmoskowitz** [comment]
FWIW  I did speak to Ian Kendrick at RCon3.  I sent him the final P/V doc which he received and said was valuable in his recent work with the Coop.  He did an H3Uni workshop in Seattle last month.
