### ISSUE TITLE
Translate rholang 0.1 version to Chinese

### ISSUE THREAD

**Issue by RowlandZhou** [rchain/bounties#473]
We wanna to translate rholang 0.1 versionto Chinese.
the link https://github.com/rchain/rchain/blob/master/rholang/doc/rholangtut-0.1.md

Why this document? (mark all that apply)
 it's one of the /rchain/reference documents
How can people who do not speak this language be assured of the quality of the translation? (all are required)
 several reviewers are involved （I will assign them later)
 at least two of them have high proficiency in Chinese
 at least two of them have high proficiency in English
 at least two of them have either
 significant reputation at stake: we all have master degree of CS, and almost of us is doing the work of blockchain.
 a track record of quality work on rchain bounties: # #242 #246 #274etc.
What about maintenance?
 the source document is stable; further translation work is not expected

**Comment by rjl493456442** [comment]
Maintain the dapp development language documents is a long term mission.

**Comment by AbnerZheng** [comment]
I will help translating these documents.

**Comment by yuhuanmocmoc** [comment]
I help review this  document.

**Comment by Jake-Gillberg** [comment]
Probably not necessary to translate both the .1 specs when .2 is already out, right?

Looks like .2 translation work is happening in #474

**Comment by Jake-Gillberg** [comment]
@kitblake, @ian-bloom, @yuhuanmocmoc I request that you modify your budget votes for this issue to $0 given the above comment.

**Comment by kitblake** [comment]
Done. Note that no rewards were assigned so it wouldn't have payed out.
