### ISSUE TITLE
M> Translate rholang-spec-0.2 to chinese

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#474]
Rholang sepc 0.2 version has already be published on the [rchain official website](https://developer.rchain.coop/rholang-spec-0.2.pdf). So i'd like to translate it to chinese and spread it by our wechat official account to the rchain fans in china.

Tasks:

- [x] Translate
- [x] Review the translation crosswise 
- [x] Put it to wechat official account 

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

Measure of Completion:  
Suggested Budget: 1580$(0.2$ per word for translation, 0.1$ per word for review, 50$ for promoting)

Note, this document is 5103 word totally calculated by the online [tool](http://countwordsfree.com/) 

_See CONTRIBUTING.md for details on budget and reward process._

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
    - [x] I contacted the author, who agreed it's important to translate
    - [x] I know a person or audience who would benefit from it: _____
    - [x] other: ___
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: ____

**Comment by RowlandZhou** [comment]
i want to join

**Comment by AbnerZheng** [comment]
I want to join too.

**Comment by yyh1102** [comment]
Please let me join in~

**Comment by yuhuanmocmoc** [comment]
cool! rholang is very important.

**Comment by linsheng9731** [comment]
I will help you to translate it.

**Comment by AbnerZheng** [comment]
Finally we have finished the translation. 
The link of this translated document is https://drive.google.com/open?id=1jRUHXvJITmB414Ing6eGcgyY_Kld9nkE. 
Comments and review are welcome!

**Comment by rjl493456442** [comment]
Translation finished
