### ISSUE TITLE
M> Translate `RChain Developer Retreat Roundup (Part 1 of 4)` to chinese

### ISSUE THREAD

**Issue by watermelonZJ** [rchain/bounties#476]
RChain team post a lot of articles in the medium, [RChain Developer Retreat Roundup (Part 1 of 4)](https://medium.com/rchain-cooperative/rchain-developer-retreat-roundup-day-1-759091f53795) is one of them which post recently. I'd love to make a translation.

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

Measure of Completion:  

- [x] Review the original post and correct the typos error if have
- [x] Translation to chinese version
- [x] Ask chinese fans to review my work
- [x] Post the translation to chinese wechat official account for promoting

The translated file has been uploaded to wechat offical account, checkout [here](https://mp.weixin.qq.com/s?__biz=MzAxNjAzMTYwNw==&mid=2247483765&idx=1&sn=06e65009ade67e763700f75c62d8ba09&chksm=9bfa4b6dac8dc27b3fca54186c2e46ba6d44d86ebc099ae0018c3d2035f078a556e1a7d7c278&scene=0&key=da75b846f73de59a6f54a473202affeeb0f8c8c721c89f360d8e04ba582efaef9ab8dca7f6e5733ae594eb5c7e209b65929d2deda457eb25ddb0f3c6575eb0c3e9bd9cdaa256e4d75b93fc51ebb2092d&ascene=0&uin=MjgyOTg2Njg0MA%3D%3D&devicetype=iMac+MacBookPro12%2C1+OSX+OSX+10.12.1+build(16B2555)&version=12020010&nettype=WIFI&lang=zh_CN&fontScale=100&pass_ticket=ZwczBOxjZ%2Bk4LRs%2BcHGYr%2BSuvQXmRDUWDLGrx6iNxTE%2Fn9oGnn9%2BHIg1ZfxfG%2BVP)

Suggested Budget: 351.2$ (0.2$ per word for translation, $0.1$ per word for original checking and translation review and $50 for promoting)

The post contains 1004 word totally.

_See CONTRIBUTING.md for details on budget and reward process._

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document? (mark all that apply)
    - [x] it's one of the /rchain/reference documents
    - [x] I contacted the author, who agreed it's important to translate
    - [x] I know a person or audience who would benefit from it: _Chinese rchain fans____
    - [x] other: ___
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: _Author by @Jake-Gillberg ___
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: __3/25__

**Comment by Jake-Gillberg** [comment]
Hey, I wrote that! Let me know if you find any typos or have any edits to suggest to the source document!. Or if you have any questions.

**Comment by Jake-Gillberg** [comment]
Also, could you fill out the :____'s for the boxes you have checked please?

**Comment by watermelonZJ** [comment]
@Jake-Gillberg Hey jake, i'll let you know if any typos error i find in the translation and review! 
I just read the post and i think it is a really good translation target. Do you think so :) Amazing post.

**Comment by watermelonZJ** [comment]
All tasks have been done! Checkout the translation in chinese wechat official account!

**Comment by rjl493456442** [comment]
Good job 💯

**Comment by Jake-Gillberg** [comment]
@watermelonZJ I'm not in the wechat official account, so I haven't seen it. Have you linked back to the original document / made sure that I am still attributed? :)

**Comment by watermelonZJ** [comment]
@Jake-Gillberg Of course. I add the original medium link under the chinese post.  Respecting authors is the most basic criterion.
If you have the time, could you please add a budget vote for me? Thanks a lot!
