### ISSUE TITLE
Use web app for 201803 pay period

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#477]
Goal: obsolete the spreadsheets in favor of the web app (#260).

 - [x] remove **WARNING**: Any data you enter may be deleted without notice.
   - initialize the database one last time
 - [x] move from https://rewards.rchain.coop/rchain-dbr-beta/ to https://rewards.rchain.coop/
 - [x] update CONTRIBUTING.md (#506)
 - [x] provide [How-To documentation](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App)
 - [x] get domain name set up (#451)
 - [x] fix permissions for deleting votes
   - _usability isn't great, but it does work._
 - [x] _fix bug: voter hidden in summary listing_

The web app was not intended to change the **bounty-contract** but it's likely that we're dropping the budget carry-over aspect: https://github.com/rchain/bounties/issues/415#issuecomment-369817670

postponed to #491: _fix filtering_

cc @jeremybusk @hyperevo @makys

**Comment by lapin7** [comment]
It's a difficult subject: budget carry-over. In one way it makes sense because when the budget is not used or partly used, then it can be spend in the next month. On the other side. When there's not enough budget, the budget can be augmented.

**Comment by dckc** [comment]
grr... adding new votes triggers an error:

```
ParseError: syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /var/www/html/xataface-2.1.3/Dataface/LanguageTool.php(223) : eval()'d code:2
```

It's somewhat harmless: the vote gets counted. But it's a pain.

I'm not the first to report these symptoms with xataface: https://groups.google.com/forum/#!topic/xataface/YlW6NZe5y8A

**Comment by lapin7** [comment]
Is this bug harmful?
I will  announce the system anyway. Let's see if there are more bug coming up. Reality testing is the best ;-)

**Comment by Ojimadu** [comment]
While we should actively encourage participants to use the web app there should be a corresponding fill out in the spreadsheet as the app is still new and many would not know how to use it at a first glance also we have the issue of bugs in codes. We would not like a situation where we a bug ruins the entire budget and rewards for march right?

**Comment by dckc** [comment]
I don't see how that would work, @Ojimadu . The web app assumes it has all the votes; so if there are two votes in the web app and one in the spreadsheet, the web app will count the budget as $0 since there are <3 votes.

Maybe the systems could be reconciled after the voting period ends, but (a) that's a bunch of coding work that I'm not volunteering to do, and (b) it affects the results in a way that the voters don't have a chance to react to. Maybe the systems could be reconciled every night or something... but I don't see a technical design for doing that.

mysql is pretty reliable. xataface is quite reliable, in my experience. It supports history logging, and that's turned on. The other xataface app I built (https://bitbucket.org/DanC/hh-office/ ) has been running since about 2011 with no data loss. I won't claim there are no bugs, but we saw plenty of actual data loss in the gsheets approach and I'm willing to bet that data loss on this platform is significantly less.

**Comment by Ojimadu** [comment]
That's good. Since Xataface supports history logging, we can easily reverse to a previous version if anything goes wrong.

**Comment by dckc** [comment]
excerpt from today's meeting (#469): 
> Rao: we’re doing some testing; maybe we should continue in that mode?
> **JW: to really test it we should treat it as the real thing**
> **HJ: yes.**

**Comment by TrenchFloat** [comment]
Is this the place to post bugs/usability fixes? Here's one anyway: I did a demo budget vote and took screenshots for the sake of updating CONTRIBUTING.md and found that once I put in a budget vote I couldn't delete it later on, just change the amount.

@lapin7 my demo vote was on #449.

**Comment by dckc** [comment]
Yes, @TrenchFloat , this is a reasonable place for usability feedback. As noted above, _usability isn't great, but it [deleting votes] does work._ You have to use the "Open this record in the Budget Vote table" link at the bottom. Then you should see a **Delete** button.

**Comment by dckc** [comment]
Oh... as to updating CONTRIBUTING.md, I'd like to keep it limited to just the rules. I'd rather use links to wiki pages or something for tutorial aspects.

**Comment by makys** [comment]
Error while voting for rewards:

```
Uncaught exception was thrown while processing this request. Troubleshooting steps:

Refresh the APC Cache. - This may help in cases where you have changed a table column definition and your server has the APC opcode cache installed.
Clear Cache Views - This may also help in cases where you have changed a table column definition and some tables include __sql__ definitions.
Check your PHP error log for a description of the error and go from there. See this page for troubleshooting tips.
Oops. Technical difficulties. This might be harmless, or you may have hit a bug. If your vote / edit didn't get recorded, report the problem in #477 and we'll check the logs.
```

**Comment by makys** [comment]
Yes, I figured what went wrong. It threw an error because rewards vote was going to exceed a 100%. 
We can work on our error handling to be more user friendly. Thanks @dckc for your response. I have been working through the system to better understand it.

**Comment by dckc** [comment]
OK, so the problem you hit isn't critical. Good.

> We can work on our error handling to be more user friendly.

Right. Since this is closed, I opened #491 for non-critical usability issues.

**Comment by dckc** [comment]
@lapin7 I just noticed from **20180328 RChain Active Member Meeting**:
> HJ: March might be a lost month, we’ll catch up in April. We can have some slack on the rewards.

That effectively re-opens this issue. I hope you didn't really mean that. Please confirm that March won't be a lost month and close this issue again. As you observe, "the new system follows the rules exactly"; I don't know how to get it to handle a lost month.

> Amaka: Whoever opens an issue should assign bounty to every member. Is that the process?

I recommend:
  - each person claim a reward on work they did: add a budget vote and a reward vote for each issue where you made a substantial contribution
    - When you log in, you'll see a "Rewards for (me)" page linked from https://rewards.rchain.coop/ . Add budget votes and reward votes until the provisional rewards there look about right.
    - Add reward votes for other contributors while you're at it, if they come to mind.
  - Then review the [Reward][r] tab to see what rewards others are claiming. Add supporting (or counter-acting) votes as appropriate.

That's what I did.

[r]: https://rewards.rchain.coop/index.php?-table=reward

**Comment by kitblake** [comment]
+1 to all the above checkboxes. 

For anybody's information, I successfully copied the InvoiceTemplate into my personal invoice spreadsheet, corrected the username, and it automagically updates!

**Comment by makys** [comment]
@dckc : 

> Amaka: Whoever opens an issue should assign bounty to every member. Is that the process?

> 
This was a recommendation, based on a pattern observed, some folks don't get around to understanding how the system works esp in their first month. That way if they get a vote it is typically very low. This is just a way to ensure fair play. 

Short answer to your question: This is not the process, it is a recommendation.

**Comment by dckc** [comment]
That wasn't my question; I was quoting you, @makys .  :)

**Comment by dckc** [comment]
> March is going fine.

Ok... so I'll set this back to closed...

> Is there a way to "Freeze March" after let's say the 7th of the April?

Yes (modulo a bug: I need to constrain vote editing to not only the logged in user but the current pay period)

> Does the new period start automatically at the 1st of the Month?

No; it starts when I do a sql `update admin_settings set current_pay_period=...`.

IOU a web UI for that. Note a few un-checked boxes under **Ops Manager initiates the next pay period** in the [Feb 2 use cases / design notes][22].

[22]: https://github.com/rchain/bounties/issues/260#issuecomment-362630020

> Could we say that budgets & rewards can be set from the 1st to the 7th of the next month?

Yes. Just don't change the current pay period until the 8th.

(you don't mean that voting should _not_ be allowed until the 1st of the month, I assume.)

**Comment by dckc** [comment]
Right. March is frozen.

**Comment by makys** [comment]
@dckc , how about customizing this error handler so members get meaningful messages if they attempt to execute operations outside of the business logic. That could be an issue on its own but it sure will help with navigating the system.

**Comment by dckc** [comment]
Good idea, @makys , please do customize the error message. The code is https://github.com/dckc/rchain-dbr

**Comment by lapin7** [comment]
I've updated the CONTRIBUTING.md
RChain Decentralized Bounty Program https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md

Links to spreadsheets have gone and links to forms have been added.

**Comment by truffard** [comment]
@ICA3DaR5  there's a slight bug regarding the reward system of issue 671

**Comment by MarioPolo** [comment]
Same here, I also have a problem with #449, we've been voting but the votes are not counting.

**Comment by jeremybeal11** [comment]
i am unable to submit a reward. i have an error screen stating: "uncaught exception was thrown" 

![rewards error screen](https://user-images.githubusercontent.com/23203842/41205640-3aff4168-6cc5-11e8-81a7-77f0dfcef84e.png)

**Comment by deannald** [comment]
When I click on an issue in rewards.rchain.coop, I get the following error message: 
Oops. Technical difficulties. This might be harmless, or you may have hit a bug. If your vote / edit didn't get recorded, report the problem in #477 and we'll check the logs.

**Comment by dckc** [comment]
Which vote didn't get recorded? Or what other task were you trying to perform?

I agree the usability is poor, and fixes in that area (and alternative user interfaces such as #789 and #792 ) are more than welcome, but as I have mentioned, I find it hard to justify further development work on the bounty system that isn't (a) a critical functionality problem or (b) a contribution toward migrating it to RChain.

**Comment by dckc** [comment]
Oh shoot... that "please report the problem in #477" diagnostic should be updated to refer to #491 now that this one is closed.

**Comment by deannald** [comment]
I was just poking around trying to figure out how to vote on issues and when I clicked anywhere in the issue, I got the message above.

**Comment by ICA3DaR5** [comment]
@deannald Try logging in again.

**Comment by deannald** [comment]
I will, thanks @ICA3DaR5 and @kitblake

**Comment by Cryptovideos** [comment]
Hi guys - any way i can remedy the folowing error : Uncaught exception was thrown while processing this request. Troubleshooting steps:

    Refresh the APC Cache. - This may help in cases where you have changed a table column definition and your server has the APC opcode cache installed.
    Clear Cache Views - This may also help in cases where you have changed a table column definition and some tables include __sql__ definitions.
    Check your PHP error log for a description of the error and go from there. See this page for troubleshooting tips.

Oops. Technical difficulties. This might be harmless, or you may have hit a bug. If your vote / edit didn't get recorded, report the problem in #477 and we'll check the logs.?

**Comment by dckc** [comment]
I just created https://github.com/rchain/bounties/wiki/VotingTrouble and pointed the oops message there.

* 2f43fc9       2018-08-02 20:54:59 +0000       change oops pointer from #477 to wiki page
