### ISSUE TITLE
delegate / proxy voting for bounties

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#484]
> If I could delegate my vote to someone who I trusted to keep the concerns proposed above in mind, I totally would. -- @Jake-Gillberg in #483

I already did some proxy voting last month: I would contact people by text or the like and fill in values in the spreadsheet on their behalf.

The new web app (#260) brings higher integrity, but it pretty much prevents this sort of proxy voting.

**Comment by Ojimadu** [comment]
Adding proxy voting now might complicate issues since we have not used the web app and see how it works. Am interested to see how the proxy voting would work out as the time used to authorize a proxy would also be the same effort used in doing the actual voting.

**Comment by dckc** [comment]
I don't have a design for doing this, so it's not likely to happen soon.

But it _is_ a regression, so I thought it important to document.

**Comment by Jake-Gillberg** [comment]
To give more color to my comment / a little user story: I would like to be able to delegate my budget votes on all issues tagged `translation` to someone like @ICA3DaR5, who has taken an expressed interest in protecting the bounty program and ensuring quality translation work.

**Comment by dckc** [comment]
@Jake-Gillberg and I sketched a design:

Bob gives his proxy to Jane for the month of May. Jane votes for budgets on issues 3, 5, and 9. Bob expresses his own opinion by voting on issue 3; on issue 5 and 9, the system copies Jane's vote for Bob.

Implementation:
   - add a proxy table: voter, proxy, pay_period, proxy_time
   - add reward_vote_proxy and budget_vote_proxy views

Ideally, Bob could delegate just **Translation** issues to Jane, but we don't see an easy implementation.

**Comment by dckc** [comment]
I don't see myself getting to this any time soon.

Anybody else who wants to work on it is free to re-open it.
