### ISSUE TITLE
O> RChain Developer's Retreat By Pyrofex

### ISSUE THREAD

**Issue by Keaycee** [rchain/bounties#485]
## DESCRIPTION
You’re invited to attend the RChain Developer’s Retreat to be held in beautiful Boulder, CO on April 17-18, 2018. A final itinerary will be sent to you closer to the retreat.

Please register to reserve your seat. You may also e-mail us at events@pyrofex.net with any questions or comments. We look forward to seeing you in Boulder!

If you're interested in speaking at the event, there are still spots available! [Sign up here](https://goo.gl/forms/7Ew66r5qz6f6kH313): 

Hotel rooms will be available, please email events@pyrofex.net to get on the rooming list.

### DATE AND TIME
Tuesday, April 17th, 2018, 9:00AM
Wednesday, April 18th, 2018, 7:00 PM MDT

### LOCATION
Millenium Harvest House Hotel
1345 28th St, Boulder, CO
Boulder, CO 80302
United States

**Comment by Jake-Gillberg** [comment]
What is the goal of this issue? The github issues aren't an announcement board.
