### ISSUE TITLE
E> Github documentation for RAM

### ISSUE THREAD

**Issue by David405** [rchain/bounties#487]
A lot of RChain Active Members especially new members are not yet so proficient in their use of github and I believe a document in effect to this will go a long way in solving this problem.

**Measure of Completion:** 100% ( Open to reviews and comments though)

**Suggested Budget: $1000**

The pdf file has being published to https://rchain.tech/2018/03/14/github-documentation-for-rchain-active-members/

**Comment by Keaycee** [comment]
[Github Documentation for Ram](https://rchain.tech/wp-content/uploads/2018/03/Github-for-RAM-main.pdf)

**Comment by Valentine-Mario** [comment]
This documentation covers from the very basic to the more complex part of using git hub. It explains how to make commit, branch, merge, pull request, merge request, etc

**Comment by dckc** [comment]
github is well documented already; I'm all for pointers to existing documentation, but I don't see why we should maintain our own.

If you can get experience github users to review and help maintain it, I suppose it does little harm.

But @David405, your github profile shows only 13 contributions in the last year. @Keaycee and @Valentine-Mario  likewise less than 20.

**Comment by dckc** [comment]
Ah... I see this is a blog article... so it can be more of a one-time sharing of experience than something with a maintenance burden. If you change the title of this issue to "blog item on using github for RChain" I would be more supportive.

**Comment by dckc** [comment]
but it needs a real byline, not "Posted by RChain.tech"

**Comment by David405** [comment]
@dckc you can make review and make amendments to https://docs.google.com/document/d/1TB5eu8IrhP9jiwzmxz6IoLZlIvBLlCLhPaA-ioV4kC0/edit# to improve it, remember, this is not a general documentation for github but I just believe we should have a tailored document to improve RAM understanding of github, I am hoping more experienced persons like yourself would welcome this and make contributions.

**Comment by David405** [comment]
@dckc I am currently working on a very basic document for rholang developers and I would be very glad if you will share your experience on how to get started as a beginner in rholang.

**Comment by TrenchFloat** [comment]
I'm going through and cleaning up parts of the issues list; this looks like it's done.
