### ISSUE TITLE
M> Translate Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) Transcript to Italian

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#488]
## Goal:  Translate Video [Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) to Italian

**The file name is**: [[TRANSCRIPT][.srt][English] "Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://docs.google.com/document/d/1-SsnE2rHlULBK5CR41re0OW_pxf4ubpwySTfqiuKjZM/edit?usp=sharing)"

**Save translated transcript in**: [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)

- [x] Translate to Italian
- [x] Check for correction errors
- [x] Reviewing and proofreading
- [x] Upload Transcript 
- [x] Translate transcript with in 10 days.

## Collaborators
- @Staff91 (Translator): 90%
- @akhs13 (Reviewer): 5%
- @Chris-Arv (Reviewer): 5%

## Budget: $1200

**Comment by Jake-Gillberg** [comment]
Hey, how would you feel about crafting a blog post in both English and Italian summarizing this content instead of translating the subtitles? @patrick727 is this something we could get featured on the RChain Coop Medium?

**Comment by Staff91** [comment]
Finished.

**Comment by Jake-Gillberg** [comment]
@Staff91, @akhs13, @Chris-Arv please explain why you supplied a $2000 budget in the bounty voting system, when you are claiming the work is worth $1800 above.

**Comment by Jake-Gillberg** [comment]
I believe that subtitle translations are worth much less than video translations. I appreciate your work, but I am currently valuing video subtitle translations at .05/word, not .20/word.

**Comment by Staff91** [comment]
Hello @Jake-Gillberg  i understand what happen , from now on when i want to open one issue i will speak too you @Jake-Gillberg  and with @dckc  about what i have to translate and budget, thank you!
@ian-bloom @lapin7

**Comment by Jake-Gillberg** [comment]
@Staff91, you haven't answered my question.

**Comment by Staff91** [comment]
@Jake-Gillberg   Because you've lowered the budget enough already, and any lower than this, and it's not worth my time anymore. Your idea about a blog post is very good, but since I already had done half the work I decided to finish it. I will also do your suggestion (the blog post), with no change to the budget. @dckc @ian-bloom

**Comment by Jake-Gillberg** [comment]
@Staff91 My intention wasn't for you to feel guilty or to say that I don't value your time. I would just like to direct you to efforts that I believe are more valuable, so that we both can be happier! I see that you 👍 my comment about valuing video translations at $.05/word. This seems to be in line with Kenny's valuation in the #bounties discord channel, and others as well. How about you change your vote for this issue to $465, and then claim a rightfully-due bounty for the blog post effort!
