### ISSUE TITLE
Pick Brand Names for RChain Node and Storage 

### ISSUE THREAD

**Issue by barneycinnamon** [rchain/bounties#490]
Medha has requested - "I'm looking for a name for 2 of our products - the Node, and the Storage layer. I'm calling on the membership to submit names for each. Then we will run an INFORMAL poll here."

 - [x] Elicit names in the Discord
 - [x] Set up the poll in the Discord polling-station channel
 - [x] Choose names and announce them

Suggested reward: $25

**Comment by ResonanceXX** [comment]
**Medha-Nodes**     

I'm just saying! :-)

**Comment by barneycinnamon** [comment]
Medha is one of the options for the node name.  :-)

**Comment by ResonanceXX** [comment]
@barneycinnamon Okay, good to know.

**Comment by barneycinnamon** [comment]
https://discordapp.com/channels/375365542359465989/422221952984416256

**Comment by qelentium** [comment]
For Storage i suggest name RCloset :)))

**Comment by Barkov-F** [comment]
How about ![thesun](https://user-images.githubusercontent.com/18509341/37456423-6139225e-2850-11e8-9b3b-ab4f54d15fa4.png) the **Sun**, or **Sol** for the node?

 **Security, Sustainability, Scalability .... _Sol_ (Sun)**

`sol-mercury-0.2`

**Comment by Keaycee** [comment]
RCovery-Nodes
Rchain-Nodes
RCooperative-Nodes

**Comment by AyAyRon-P** [comment]
@ian-bloom will there be an iconography requirement for these layers?

**Comment by barneycinnamon** [comment]
We did it! The names RNode and RSpace were chosen to identify the node and storage layer. Thank you to everybody who contributed a name and everybody who voted in the poll.
