### ISSUE TITLE
bounty voting app usability paper-cuts

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#491]
[The bounty web app](https://github.com/dckc/rchain-dbr) pretty much works, but there are various usability "paper cuts"

 - [ ] anywhere you see an issue or a user (e.g. on a budget vote or a reward vote) it should be a link to the issue or user page
 - [ ] search for issue by number doesn't work
 - [ ] filtering got messed up by the dashboard

grr... adding new votes triggers an error:

```
ParseError: syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /var/www/html/xataface-2.1.3/Dataface/LanguageTool.php(223) : eval()'d code:2
```

It's somewhat harmless: the vote gets counted. But it's a pain.

I'm not the first to report these symptoms with xataface: [PHP errors when adding relationship from existing data.](https://groups.google.com/forum/#!topic/xataface/YlW6NZe5y8A)

Looks like there's a [Sep 16, 2016 fix](https://github.com/shannah/xataface/commit/a39267928750f8d66b6d8451f8eec9653f92ebee) but no release has been cut since then. :-/

In fact there have been 103 commits since Xataface v2.1.3 released Aug 31, 2016. I made a [request for a release](https://github.com/shannah/xataface/issues/96).

Diagnosing this probably involves setting up a test instance of the app and exploring either PHP versions or, more likely, unreleased versions of xataface.

_originally [reported March 13](https://github.com/rchain/bounties/issues/477#issuecomment-372580819)_

cc @hyperevo @petereitz

**Comment by David405** [comment]
Are you certain this error is caused by version conflicts? I think perhaps something was omitted in the code, maybe debugging could solve the problem( my suggestion though), can you share a link to file where this is occurring?

**Comment by David405** [comment]
The app refuses to run on my local server, I can't seem to trace the problem, it throws a 500 internal server error but a clone of the xataface repo runs fine.

**Comment by David405** [comment]
One last thing, when logging into rewards.rchain.coop, the authorize button in the github oauth page doesn't work, is this intentional or a bug?

**Comment by dckc** [comment]
"doesn't work" is [not helpful](http://www.catb.org/esr/faqs/smart-questions.html#idm46060474008752).

**Comment by Valentine-Mario** [comment]
I tried to log in to the Web app @http://rewards.rchain.coop but I couldn't. How do I resolve this?

**Comment by dckc** [comment]
If you want help, @Valentine-Mario, you should [be precise and informative about your problem](http://www.catb.org/esr/faqs/smart-questions.html#beprecise).

Did you get an error including "unexpected T_ENCAPSED_AND_WHITESPACE"? If not, perhaps your problem is not relevant to this issue.

**Comment by dckc** [comment]
I suppose I'll widen the scope of this to include other usability issues.

**Comment by TrenchFloat** [comment]
Under the "budget" tab and "reward" tab, I couldn't find any issues that were closed in GitHub. The one I was looking for, #467, was both opened and closed in March, but should we also consider budget carry-over on closed issues before we omit them from the list?

Anyway, I found it under the "Issues" tab and voted on it from there.

**Comment by dckc** [comment]
In the "budget" tab and "reward" tab, you should only expect to find issues where somebody has voted. The "Issues" tab is usually the place to start.

**Comment by dckc** [comment]
woot!

With help from @petereitz, I upgraded xataface, and now rather than "technical difficulties" we get:
> Record successfully added to "BudgetVotes" relationship.

https://github.com/dckc/rchain-dbr/commit/a1791e51ef301c5fd632b74e71815d48149cef3a

**Comment by dckc** [comment]
With @petereitz , I fixed a couple missing-link papercuts.

https://github.com/dckc/rchain-dbr/commit/74d8c8a48c3c289b9094dc291bd47eab369a5978

**Comment by dckc** [comment]
Oops! The Xataface upgrade broke login. I know why... Need to put the custom login module in place

**Comment by dckc** [comment]
Login restored.

@petereitz , we forgot about this part:
```
    - name: install XDB module
      synchronize:
        src: "{{ install_dir }}/xataface_template/modules/"
        dest: "{{ xf_dir }}/modules/"
```
-- https://github.com/dckc/rchain-dbr/blob/master/playbook.yml#L18-L21

**Comment by lapin7** [comment]
Anyone: 
Please enter one more reward-vote for #529 
Then I can try out the invoice part of the bounty-system

**Comment by pythonical** [comment]
Added.

**Comment by dckc** [comment]
The [invoice info](https://rewards.rchain.coop/index.php?-table=invoice_info) tab already has 7 entries, @lapin7 .

**Comment by dckc** [comment]
The **Verify Coop Membership** link is in the upper right menu under your login (after you log in).

A detail: un-verified users are allowed to _enter_ votes; they just get ignored in the budget/reward calculations until the user is verified.

**Comment by Tonyprisca13** [comment]
I am a verified coop why cant i vote or budget?

**Comment by dckc** [comment]
Are you sure you cannot? What happens when you try?

**Comment by kitblake** [comment]
Fwiw, I just verified and I think it worked. Then I did it again. 

But I'm not sure it has any effect. I was trying to add a budget for "RChain Coop Membership Benefit #520" but the issue is not showing up in the listing: 
Budget tab > Click "Issue Num" heading > Click reverse order triangle > See issues in reverse order

**Comment by dckc** [comment]
Use the issue tab. It has all the issues. (If it doesn't, use the sync link
on the left)

The budget tab only shows issues where a budget vote has been entered.

**Comment by pythonical** [comment]
i used the 'verify' but have no idea if it worked.

**Comment by dckc** [comment]
It worked. Look at the "Verified coop" field in [your user record][1]. Also note that your votes are getting counted, for example in the [rewards for lapin7 on issue 529][2].

[1]: https://rewards.rchain.coop/index.php?-table=github_users&-search=python&-action=view&-submit=Search+Users&-cursor=0&-skip=0&-limit=30&-mode=list&-recordid=github_users%3Flogin%3Dpythonical&-ui-root=main-content
[2]: https://rewards.rchain.coop/index.php?-action=view_related_record&-related-record-id=issue%2FRewards%3Fnum%3D529%26Rewards%253A%253Apay_period%3D2018-03-01%26Rewards%253A%253Aissue_num%3D529%26Rewards%253A%253Aworker%3Dlapin7&-table=issue&num=%3D529&-ui-root=main-content&-cursor=0&-skip=0&-limit=30&-mode=list

**Comment by dckc** [comment]
@kitblake I don't see any budget votes from you on #520. Describe the exact steps you took to vote?

Everybody, for 4th time: take care with your problem reports. "It doesn't work" is no help in diagnosing problems. It's important to to say
  1. _exactly_ what you did
  2. _exactly_ what you expected, and
  3. _exactly_ what you experienced instead.

**Comment by lapin7** [comment]
@pythonical since you managed to become a "verified member" please add a budget vote to #529

**Comment by kitblake** [comment]
@dckc I didn't get that far, after posting the problem I called it a night. Doing it now..

**Comment by lapin7** [comment]
@kitblake since you managed to become a "verified member" please add a [budget vote](https://rewards.rchain.coop/index.php?-table=issue_budget&-action=list&-cursor=0&-skip=0&-limit=30&-mode=list&-sort=issue_num+desc#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-table%3Dissue_budget%26-action%3Drelated_records_list%26-cursor%3D6%26-skip%3D0%26-limit%3D30%26-mode%3Dlist%26-sort%3Dissue_num%2Bdesc%26-recordid%3Dissue_budget%253Fpay_period%253D2018-03-01%2526issue_num%253D529%26-ui-root%3Dmain-content%26-relationship%3DBudgetVotes) to #529

**Comment by kmoskowitz** [comment]
I am trying to vote for rewards on issue #471  I already made budget vote, but when i pull up the window for rewards vote, no button shows up to allow me to vote. Not sure how to proceed.

**Comment by dckc** [comment]
I can't reproduce the problem, @kmoskowitz; when I start at the Issue tab, bring up 471, and follow the link to [RewardVotes on 471][1], I see a **New RewardVote** button. I made an [annotated screenshot][2].

[1]: https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=471&title=&updatedAt=&state=#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-table%3Dissue%26-limit%3D30%26num%3D471%26title%3D%26updatedAt%3D%26state%3D%26-action%3Drelated_records_list%26-cursor%3D0%26-skip%3D0%26-mode%3Dlist%26-recordid%3Dissue%253Fnum%253D471%26-relationship%3DRewardVotes%26-ui-root%3Dmain-content
[2]: https://www.diigo.com/item/image/1464w/dwrb

**Comment by kmoskowitz** [comment]
Thanks!  I used your link in a different browser and it came up fine (Safari) and able to use, for some reason not working in Chrome.

**Comment by lapin7** [comment]
Thanks to @dckc 's ImportHTML we have a data connection between Gsheet and the Bounty App.

I'm now busy with a spreadsheet that can create your personal invoices. It has all the personal data and it's usable starting from March onwards. You just have to create an "invoice overview" in the bounty app and fill out the period in the spreadsheet and your github name.

Tomorrow I will copy this template to your personal invoices spreadsheet.

You can have a look at it in [Pub Bounties](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=1560696085&range=G1:H1)

**Comment by dckc** [comment]
> You just have to create an "invoice overview" in the bounty app

I don't think so. As I noted in #548, the InvoiceInfo tab is gone from rewards.rchain.coop. The IMPORTHTML in the invoice spreadsheet template just uses the Rewards tab and filters on worker and pay period.

**Comment by kmoskowitz** [comment]
I voted placed my rewards vote on issue #471, but when I check rewards vote is not showing up.

**Comment by kitblake** [comment]
@kmoskowitz First make sure you're logged in, then click the disclosure triangle next to your name and choose "Verify Co-op Membership". You should be redirected to Discord and see a "Verify" overlay. Click "Authorize" and you'll be returned to the BudgetRewards app. Now you should be able to vote.

**Comment by kmoskowitz** [comment]
Hmmm... I thought my Co-op membership was already verified. I don't see the disclosure triangle.  To be clear, I was able to vote, and it shows that I voted under the RewardsVote tab.  When I click on the Rewards tab to the left, and look under Voters, my name does not show up. Issue #471

**Comment by kitblake** [comment]
@kmoskowitz I see what you see, namely votes that are listed in the RewardVotes tab are missing in the Rewards tab. 
Escalating to @dckc..

**Comment by kmoskowitz** [comment]
Found the fab to Verify Coop Membership. Clicked "authorize"e to access Discord.  The page won't load.  Tried with different browsers.

**Comment by dckc** [comment]
Your user record shows your discord member profile has been verified. Your votes count now.

**Comment by dckc** [comment]
- [ca19b85][1] dbr_triggers: only current vote changes allowed

I only put database constraints (triggers) in place. Ideally the constraints would be clear in the web app too, but for now, you'll just get an error if you try to make an edit outside the current pay period.

[1]: https://github.com/dckc/rchain-dbr/commit/ca19b855cdf018c6ec854161e698aeaa7fd80e5a

**Comment by kitblake** [comment]
In the Budget/Rewards app I'm getting no visible reaction when trying to access issue details (which normally appear in the lower frame after locating an issue). Steps:
1. Search for an issue by number.
1. Click on the found issue link. There is a request but nothing happens on the page. The lower frame remains empty. 

The workaround is to copy the link, then paste & go in the location bar. Then the details load and budgets/rewards can be edited. 
(So @dckc and/or @TrenchFloat should relax and enjoy the Dev conf.)

**Comment by kitblake** [comment]
Btw, I miss the Status page with the handy links, such as:
My budget votes: https://rewards.rchain.coop/index.php?-action=related_records_list&-relationship=BudgetVotes&-table=github_users&login=%3Dkitblake
My reward votes: https://rewards.rchain.coop/index.php?-action=related_records_list&-relationship=RewardVotes&-table=github_users&login=%3Dkitblake

**Comment by kitblake** [comment]
Hey, nice latent filter: 'Showing matches for query Search: "2018-04-01"'

**Comment by kitblake** [comment]
I'm getting a traceback when updating issues from Github:
pymysql.err.InternalError: (1366, "Incorrect string value: '\\xE2\\x80\\x8A - ...' for column 'title' at row 607")

**Comment by dckc** [comment]
long overdue: link from an issue page in the web app to the github issue:

 - `5bb48e5c6a14`  papercuts: link to issue

I fixed the `Incorrect string value` bug in 3efc87c, too, @kitblake .

**Comment by kitblake** [comment]
Can we increase the session length on the rewards server? I think it's default 20 minutes, and people at the end of the month are often busy for an hour or two.

**Comment by dckc** [comment]
I don't remember seeing where the session duration is set, but it must be
in there somewhere...

**Comment by dckc** [comment]
Thanks to @David405 and @jimscarver for helping me make time to fix a couple:

* [ea8e069][]     2018-08-09      paper cut: display exception message
* 7eaeb06     2018-08-09      make link_markup available to issue.php

[ea8e069]: https://github.com/dckc/rchain-dbr/commit/ea8e069

I have no particular plans to work on this further. I'm closing this until something specific comes up.
