### ISSUE TITLE
Governance Policy: Disclosure of Affiliations

### ISSUE THREAD

**Issue by barneycinnamon** [rchain/bounties#492]
There are a handful of bodies within the Co-op that are handed high authority by the Co-op bylaws.

#### _Co-op Compensation Committee_

It might be beneficial to adopt a policy that includes disclosure of related affiliations by members elected or appointed to fill key roles.

Beyond a disclosure policy, we might consider a limit on the ratio of seats in a given committee that can be filled by members with overlapping external affiliations to limit the potential for bias to creep into the decision making of the committees.

**Comment by evanjensen** [comment]
I have no interest in or connection with Reflective.

**Comment by barneycinnamon** [comment]
Thanks for the feedback! I'll update that now.

**Comment by kennyrowe** [comment]
@barneycinnamon perhaps a wiki for this information would be better than an issue as the information is likely to change.

**Comment by barneycinnamon** [comment]
Kenny -- Thanks a bunch for clarifying your affiliations and adding in the compensation committee members. I need to find the nominating committee members next. Regarding belonging in a wiki, that actually makes a great deal of sense to me. Can that allow vintages? I thought it might be good to have a history over time, but it might be more important to have a current version. I guess it depends on the purpose. We should think about that.

**Comment by kdvalentine** [comment]
@barneycinnamon Why would disclosures be subset of 'conflict of interest' and not 'corporate (co-op) governance'?

**Comment by barneycinnamon** [comment]
@kdvalentine That's a good question. I thought of it as the first step in the direction of a conflict of interest policy. If you have a responsibility to do your best for each of two entities, the conflict of interest comes when your ability to do the right thing for one is impacted by a desire to do right by the other or even just due to a bias that makes it hard to see the situation clearly as an outsider. The same insider information that can bias your judgment is also _valuable_ context, so it is actually a good thing to have Reflective and Pithia folks integrated into the Co-op and doing their best to advance both entities, but it's important for there to be a core of Co-op focused representatives who do not see direct benefit from any related entity and instead benefit from the success of those related entities in the same indirect way that all RChain stakeholders and Co-op members hope to. Does that make sense?

**Comment by kdvalentine** [comment]
@barneycinnamon Furthermore, this is a public document that lists a group of people under the subject "conflict of interest". It's misleading on several fronts. There could be several ways where what you intend can be expressed in a way that leave less room for misinterpretation.

**Comment by mrinalmanohar** [comment]
Everyone is incetivized to see the platform succeed , this seems pointless and a huge violation of privacy. All you seem to be asking is how much RHOC each person has; given it's the same access token to a utility I don't see the point of this exercise. This is equivalent to asking everyone to disclose their bank accounts

**Comment by barneycinnamon** [comment]
@kdvalentine I see your point. My first instinct is to try to change something here to make you feel better. Bear with me for a minute though before I make some revision along those lines. I just typed "conflict of interest" into Google and was provided with this helpful definition from Wikipedia:

_A conflict of interest is a situation in which a person or organization is involved in multiple interests, financial or otherwise, one of which could possibly corrupt the motivation or decision-making of that individual or organization._

All of the people on that list have an interest in the Co-op. All of the people with an additional affiliation are associated with another related entity. The definition does not say that those people are corrupt or that their intent is malicious. Nor am I making any such claim. Rather, the definition merely states that the multiple interest _could possibly_ influence the decision-making of those people.

If you feel uncomfortable about having a conflict of interest, you can step down from one of those positions, but please understand I am not suggesting that you ought to do that. The conflict of interest issue is not really at the individual level as much as it is on the organizational level--that is, as long as there are enough other competing interests to balance those of the conflicted parties, then the individual conflict of interest will not corrupt the decision made at the group level. My interest is in exposing potential conflicts at the individual level so that the members of the Co-op can better understand whether or not the committees representing their interests have a weakness at the group level as a result of too many conflicts at the individual level.

**Comment by barneycinnamon** [comment]
@mrinalmanohar It is not my intention to violate your privacy, and I apologize sincerely if you feel I have done so here. Maybe this list should sit in a place where only Co-op members can view it, like the member dashboard for example. I don't understand how this connects to anybody's holdings of RHOC tokens, but maybe you can explain.

**Comment by mrinalmanohar** [comment]
I do not accept your apology,  unless  you can prove malintent, this is an immature and incendiary attack that is not in good faith. We work hard to build something good here

**Comment by barneycinnamon** [comment]
@mrinalmanohar I am not claiming malintent. There is nothing for me to prove. I don't think you've done anything wrong. I am also hard at work trying to build something good. That's why I am doing this. It troubles me that this is causing you to feel hurt, but I hope that you can see it isn't about you. It's about how many people in the Co-op leadership have a responsibility to more than one entity. If that's true for a couple people it is fine, but if it's true of too many then the system is not sufficiently robust.

**Comment by mrinalmanohar** [comment]
Then bring this up when you see malintent or suspect it

**Comment by barneycinnamon** [comment]
I think if you consider that comment when you're less agitated you'll realize it isn't a sensible suggestion.

**Comment by mrinalmanohar** [comment]
I'm not agitated , just disappointed

**Comment by barneycinnamon** [comment]
You have no reason to be disappointed though. You are doing such great work for the Co-op you got asked to serve on the executive committee _and_ asked to work for Reflective. Those are both testaments to the esteem in which your fellow Co-op members hold you. So far so good. But something like 6/10 of the people on the executive committee work for either Pithia or Reflective. That might not be so good. It's also not about you personally. It's about the ratio on the committee.

**Comment by deannaduke** [comment]
You might also want to edit "Let's start by simply establishing a list of the financial interests of holders of all key co-op positions" to "Let's start by simply establishing a list of the affiliations of holders of all key co-op positions". Keep the financial aspect out of it.

**Comment by mrinalmanohar** [comment]
Then name this "committee ratio" Or propose a ratio that works for you. You started with alleging there was a conflict of interest and asked for disclosure of all our financial interests within the rchain system.  I don't know if this comes from a place of inexperience or self importance. If you're trying to throw grenades, good job. But I don't see what constructive outcome you see from pulling stunts like this

**Comment by barneycinnamon** [comment]
Mrinal -- I see it now. It was a stupid error. I wrote "financial interests," and that wasn't really what I meant. It's a stupid mistake and re-reading it now it is glaring. I am going to do some surgery on this...

**Comment by barneycinnamon** [comment]
Thank you to @kennyrowe, @deannald, @evanjensen, @mrinalmanohar, and @kdvalentine for feedback on this issue that made its intent more clear.

**Comment by mrinalmanohar** [comment]
If that's the amount of thought you put into these things before making such extreme demands and accusations  (conflict of interest) , makes me question your credibility and qualifications.  On that topic could we please have a summary of your background and expertise here, while I've tried to be nice and given you benefit of the.doubt these frequent revisions within minutes make me question your credibility

**Comment by mrinalmanohar** [comment]
If that's the amount of thought you put into these things before making such extreme demands and accusations  (conflict of interest) , makes me question your credibility and qualifications.  On that topic could we please have a summary of your background and expertise here, while I've tried to be nice and given you benefit of the.doubt these frequent revisions within minutes make me question your credibility
