### ISSUE TITLE
Co-op Operations and Budgeting Disclosure

### ISSUE THREAD

**Issue by barneycinnamon** [rchain/bounties#494]
Weekly updates contain lots of current information but lack an overarching context that would be present in a roadmap. These would be useful things to bring new members up to speed on where we're going.

When the co-op treasurer gives an update on the Co-op's finances, there must be a written counterpart to whatever is shared verbally. Do we have anything like an income statement stored somewhere that is viewable? Do we have an operational roadmap for the Co-op, and if so where does that reside?

I propose to ask the executive committee to request that the Co-op Officers release, on a regular basis (quarterly?), a written report detailing their plan for Co-op operations (objectives and budget), including a brief retrospective of the previous reporting period.

Dan points out that there are some existing updates. I'd like to see something in writing, like accounting statements. If those are already posted, it would be nice to find where they are.

Kenny points out that the plans are present in the minutes published by the committees. I am thinking in conventional terms that there might be a plan that contains some key objectives for the Co-op that would help align the activist members and the committees as they each execute their parts.

**Comment by dckc** [comment]
I think some budget numbers and projections were presented as part of the annual meeting... ah yes: the [weekly update index](https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index) shows a [Financial Summary by Lisa Rice](https://youtu.be/CXA_LqsJaks?t=2m40s).

See also [RHOC Distribution](https://github.com/rchain/reference/blob/master/finance/rhoc.md) in the `rchain/reference` repo.

**Comment by kennyrowe** [comment]
@barneycinnamon Coop executives do not plan in private. Information is generally shared every week at the community hangouts. Furthermore, plans are created collaboratively with members. Nearly all documents and minutes can be found someplace here on github. If there is a specific lack here I suggest forming a group to address the issue.

**Comment by dckc** [comment]
@barneycinnamon I'm reviewing the issues assigned to me; I need clarification on what I am supposed to do. If I ever knew, I forgot.

**Comment by barneycinnamon** [comment]
@dckc Removed your assignment. I think I originally assigned you because you were on the executive committee, and this was an attempt to express to the co-op executive committee that members would benefit from insight into the Co-op's financial and operational outlook. Since the financial information is centralized under the supervision of the Co-op treasurer, the authorization to share the information really needs to be approved or rejected by a governing body like the executive committee. With the authorization in place, generating a canned QuickBooks report should require little more than pressing a button and having a suitable place to post the output.

**Comment by barneycinnamon** [comment]
Issue #637 looks like it will cover this ground, so I'll close this issue.

**Comment by dckc** [comment]
My impression is that #637 is a report about the bounty system. Regular reports about the finances of the coop as a whole would still be nice. But I suppose I'm content with reports in annual meetings, so I don't mind if this is closed.

**Comment by barneycinnamon** [comment]
@dckc The Co-op treasurer, Kate, would be the person in a position to produce and post a report like this. I don't know who is in a position to advocate for such a report to be produced. Several members, including me, you, and Medha have said they'd like to see something like this. Is this something you can put on the agenda for the next Executive Committee meeting? If so, this issue will have accomplished it's very limited scope.

**Comment by dckc** [comment]
I could, but I am already juggling as much as I can; I don't see anything that this should preempt.

**Comment by dckc** [comment]
@kennyrowe mentioned something about a regular "chat with members of the board" thing that seems responsive to this issue.

**Comment by kennyrowe** [comment]
@barneycinnamon I'll look into this and get back to you

**Comment by barneycinnamon** [comment]
@dckc @kennyrowe @ian-bloom I think this issue could use a different name or some amendment of scope, and I am hoping for your constructive input. There have been lively conversations about the bounty system and what kind of coop the RChain coop is. Here we have an issue inquiring originally about the operational roadmap and financial plans/budget of the coop. What this issue is about is the coop business model. I think it would be useful to have an open discussion about the coop business model, because that interacts with the bounty system (what do we want it for? how do we know if it's working? which tasks should get budgets and how much?) and with the type of coop that the coop is (Ian and Kenny have both said "Consumer, not worker!" lately. I've been curious about the "investor coop" concept that was mentioned once or twice and how that might provide useful precedents as well). Finally, there was a motion to burn RHOCs in 2018 passed at the 2017 member meeting. @leithaus said earlier this year that the motion was not actionable, but it was passed for a reason, and the underlying issue is what to with excess coop resources. There is a dispute on the one hand about how many REV there should be (hence 10:1 or 100:1 split discussion to have a distribution-preserving-quantity-expanding event) and on the other hand about what the coop needs (the RHOC reserve is not enough or the wrong way to support coop operations versus the project is way over-funded to serve its purpose of paying to develop the code). All of these questions intersect at the "what's the business model" nexus, and it seems particularly thorny, because it's unclear who should answer that question. The obvious candidate answers are: Greg; the officers (Greg and Kenny); the board (Greg, Kenny, et al.); the members (working group? executive committee? annual meeting?). If the answer is "We already have this all worked out," I'd say it would be worth expending some resources to elucidate the existing plan for the members. If this hasn't been worked out, I think it's only fair to the members (and to the benefit of the coop itself as well as the RChain ecosystem) to determine how this will be considered and decided now and moving forward (since these things are necessarily iterative).

**Comment by dckc** [comment]
My impression is that "consumer coop" is a very short summary of the bylaws, and that's what we are unless and until we change the bylaws.

I don't know what the coop business model is. It's not even clear to me that we must have one. Maybe each of us has our own idea of what the coop business model is. That seems kinda silly, but for all I know, that's an acceptable state of affairs.

I suggest you chat up @ottermagically about it.

**Comment by ian-bloom** [comment]
@dckc 

> My impression is that "consumer coop" is a very short summary of the bylaws, and that's what we are unless and until we change the bylaws.
> 
> I don't know what the coop business model is. It's not even clear to me that we must have one. Maybe each of us has our own idea of what the coop business model is. That seems kinda silly, but for all I know, that's an acceptable state of affairs.

RChain Cooperative is a _Consumer-Cooperative_, much like REI or many Electric Cooperatives. The primary benefit of being a member is that you receive discounted use of the RChain Platform. The discount takes the form of a yearly rebate on the usage fees (phlogiston) that you expend.

Changing or re-interpreting the business model could jeopardize the sustainability of the Co-op itself, as could preferentially serving stakeholders other than the **users** of the platform.

**Comment by barneycinnamon** [comment]
@ian-bloom 

Thank you for your response. I am going to try to push the conversation forward a little bit, and I hope you and otters will find it worthwhile to participate.

RChain Cooperative is a consumer-cooperative. The purpose of the RChain Cooperative is primarily to get the platform launched and then to maintain it. The consumer focus means that, to the extent the Cooperative represents the interests of a particular stakeholder group, it's the users. I presume that means the Cooperative would like to see the lowest possible prices for network services. 

Question 1: Does the objective of low user costs put the RChain Cooperative at odds with RHOC/REV holders?

That objective does not necessarily put the Cooperative at odds with speculative holders of RHOC/REV, because low costs in USD and a high USD value of REV can be reconciled by a high REV to phlogiston exchange rate. If I grok the economics, the idea would be that it's valuable to stake REV to offer services, and that offering those services at a small margin (the "low costs" relevant to _users_) at a high volume generates a substantial net income available only to somebody with the REV necessary to stake. The reason people associate high coin price with high transaction costs is that existing precedent blockchains (Bitcoin and Ethereum) don't scale. There is no "make it up on volume" avenue. Higher demand has to mean higher price, because supply is inelastic. On RChain, if everything works as advertised, higher demand (for network services) will mean higher supply (of network services) and not higher prices (USD rate of network services). Shifting out the supply curve of network services with a fixed supply of the staking token means increasing the value of the staking token even without increasing the cost of the services.

Question 2: Does the RChain Cooperative run nodes?

The RChain Cooperative has a big decision to make with respect to operating nodes. Since it is sitting on a boatload of RHOC and wants to see the network flourish, it could just launch a bunch of nodes to bootstrap the network. But this is the cryptocurrency space, so users care about decentralization. It's even one of our values, according to the work of the Principles and Values working group (see issue #471). I believe that, if you could wave a magic wand and have everybody feel great about the RChain Cooperative running nodes _because coop!_ then this would be by far the most efficient way to build the network. I also have the sense that people would not be satisfied by that and want to see as much decentralization as possible. So, maybe the RChain Cooperative runs _some_ nodes? Maybe it participates in validating _some_ namespaces? But presumably tries to do so in a way that does not scare people, which means having other, independent validators in meaningful proportion. Still, that would be a way for the Coop to actually generate income in REV...

Question 3: Whence the RChain Cooperative derive income?

In order to rebate phlogiston, which really means REV, the RChain Cooperative needs a source of REV. One option is running nodes, and this is probably a good idea within reason and with utmost care vis a vis centralization concerns. Another source of income could be running DApps. Maybe the RChain Cooperative (a locus of Rholang programming talent and RChain platform knowledge) could build its own DApps. Greg M talks about an App Store in what seems like a reference to the Apple App Store. But nobody ever mentions IOS Apps. Maybe in between the OS (RChain) and the App Store (the DApps built by users) there are the RChain Coop DApps -- by analogy to the built-in stuff like Clock that comes on your iPhone.

Question 4: Will investments in third-party DApps be the primary source of income for the RChain Cooperative?

RChain Cooperative supports the ecosystem and generates an asset on its balance sheet when it invests in companies through Pithia and Reflective or directly. To the extent that those investments appreciate, the RChain Cooperative receives income in the form of unrealized or realized capital gains.

Question 5: Will RHOC/REV appreciation be a source of income for the RChain Cooperative?

You cannot mention assets and capital gains without mentioning the RHOC/REV treasury. That's there too.

Some of these questions verge on rhetorical, while others invite reflection and discussion. I think it is strange for @ian-bloom to say:

> Changing or re-interpreting the business model could jeopardize the sustainability of the Co-op itself, as could preferentially serving stakeholders other than the users of the platform.

...because I am pretty sure I am coming in and saying "Hey, what is our business model?" _not_ "Hey, let's change to this other business model."

>

**Comment by barneycinnamon** [comment]
A few additional thoughts on rebates:

1.  There are going to be multiple RChain Coop entities. Which one will be offering rebates? Seems minor until you remember the rebates have to be funded from revenue. Which one receives which revenue might get more complicated depending on how they pursue revenue and whether there is some kind of sharing model across them.

2.  You could imagine each transaction including a small fee that goes to the RChain Coop. @ian-bloom has mentioned this possibility a couple times. It seems reasonable. One concern is that blockchain forks to delete the transaction fee. That risk is always present, so I'd just say be the best chain all things considered _including_ any fee you want to levy, and you will be fine. If that's easier said than done, then don't levy the fee.

3.  When @ian-bloom says RChain Cooperative is a consumer coop, he seems to have DApp deployers in mind as the consumers. If RChain deploys validator nodes or levies a transaction fee, it will have revenue tied to network use and can offer rebates proportionally. An alternative view would have users of DApps as the consumers. If RChain Cooperative holds equity or token stakes in DApps the Coop itself has deployed, or in DApp deployers supported by the Coop directly, or in DApp deploying portfolio companies of Pithia and Reflective, the Coop could think about ways to embed a rebate for RChain Coop members directly into each or many of those DApps. I don't know exactly how that would work, but it could generate some virtuous network effects if membership in any of the coops (e.g. Resonate, SHOP, etc.) somehow reduced barrier to entry or increased appeal of all the others.

**Comment by barneycinnamon** [comment]
As far as charging transaction fees and wondering if the network would be forked, one option would be to have a value-add service of operating machines for lazy validators. If you stake your REV on your own system, running the node software implementation of your choice, you keep the fees/rewards. If you stake your REV on a Coop system, you pay a cut to the Coop.

> The one major difference between WordPress.com and WordPress.org is who's actually hosting your website. ... WordPress.org is where you'll find the free WordPress software that you can download and install on your own web server. WordPress.com, on the other hand, takes care of all of the hosting for you.

**Comment by barneycinnamon** [comment]
@kennyrowe Last I checked the status of this was that Bill and Kate were working on business model and periodic financial statement disclosures. What kind of outcome should members anticipate coming from the existing process? Not sure if I should close this issue, pester people, or what.

**Comment by kennyrowe** [comment]
Feel free to keep pestering. The documents I've seen aren't ready for
general consumption yet, but I don't think it would be hard to get them in
shape.

**Comment by barneycinnamon** [comment]
When Evan provides guidance on the submission of initiatives for the annual meeting, I will submit a formal proposal for regular disclosures from the Coop. In the meantime, I don't see this going anywhere, so I will close it.
