### ISSUE TITLE
atom rholang 0.1 package

### ISSUE THREAD

**Issue by flowpoint** [rchain/bounties#495]
i started an atom rholang package:
rholang basics are working, 
this is a WIP:
https://github.com/flowpoint/atom_language_rholang

**Comment by zsluedem** [comment]
@tgrospic is using the tmlanguage to generate the formatter for other ide. I don't know if it works for the atom.

**Comment by flowpoint** [comment]
yes, i used his json grammar.
is released now
https://atom.io/packages/language-rholang
https://github.com/flowpoint/atom_language_rholang

**Comment by tgrospic** [comment]
I like the gif, but snippets even more. :+1:

**Comment by dckc** [comment]
I just tried out this package. Works pretty good!

Here's hoping for 0.2 support... especially coloring names and processes differently.

**Comment by dckc** [comment]
Let's reduce the scope of this and call it done. When you're ready to do more work in this area, feel free to create a new issue or re-open this one.
