### ISSUE TITLE
M> Translate Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) Transcript to Polish

### ISSUE THREAD

**Issue by pavlos1851** [rchain/bounties#500]
## Goal:  Translate Video [Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) to Polish

**The file name is**: [[TRANSCRIPT][.srt][English] "Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://docs.google.com/document/d/1-SsnE2rHlULBK5CR41re0OW_pxf4ubpwySTfqiuKjZM/edit?usp=sharing)"

**Save translated transcript in**: [/RChain/Members/Marketing-Community Dev/YouTube](https://drive.google.com/drive/folders/1zBZXvPMIC9yBneYI2c4x-xGwr-D1X1Ii)

- [ ] Translate to Polish
- [ ] Check for correction errors
- [ ] Reviewing and proofreading
- [ ] Upload Transcript 
- [ ] Translate transcript with in 10 days.

## Collaborators
- @pavlos1851 (Translator): 10%
- @qelentium  (Reviewer): 0%
- @jkost401 (Reviewer): 0%

## Budget: $2000

**Comment by Jake-Gillberg** [comment]
Hey, how would you feel about crafting a blog post in both English and Polish summarizing this content instead of translating the subtitles? I believe this is this something we could get featured on the RChain Coop Medium, with you as the author.

**Comment by Jake-Gillberg** [comment]
This issue was closed, and I remember talking with @ICA3DaR5 who said that you would not translate this document, but I still see a budget assigned. @jkost401 @pavlos1851 @qelentium please correct this.

**Comment by Jake-Gillberg** [comment]
I believe that subtitle translations are worth much less than video translations. I appreciate your work, but I am currently valuing video subtitle translations at .05/word, not .20/word.

**Comment by qelentium** [comment]
Ok i will tell @pavlos1851 to close it

**Comment by pavlos1851** [comment]
I'm sorry for the delay, I thought since the issue was labeled "Do not translate" and closed, that no further action was necessary.  Now I know better :)
