### ISSUE TITLE
Share news on performance monitoring in Node Release

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#504]
Hey guys,

we just announced the new node release

https://medium.com/rchain-cooperative/rchain-node-version-0-1-3-released-ede6cb2d57f7

please share it far and wide, and link to your shares here in this issue. 

feel free to use the resources in this [research sheet ](https://docs.google.com/spreadsheets/d/1M9kqbnYxotaOLtWOj7MWquE41KADZJLtwFdgDqtoEck/edit#gid=520219094)

**Comment by dckc** [comment]
Don't bury the lede!

"RChain node version 0.1.3 released" says only "there are new bits on the Internet."

the interesting bits are in the next line, but that line doesn't get nearly as much exposure as the title:
> The RChain node now has more installation options and production engineering features, including built-in telemetry for monitoring node performance.

I suggest changing the title to: **RChain node adds performance monitoring in 0.1.3 release**.

cc @pmoorman 

ref:
 - [Microcontent: A Few Small Words Have a Mega Impact on Business](https://www.nngroup.com/articles/microcontent-how-to-write-headlines-page-titles-and-subject-lines/)

**Comment by David405** [comment]
Shared on rchain.tech https://rchain.tech/2018/03/17/rchain-node-version-0-1-3-release/

**Comment by dckc** [comment]
I suggest we've reached a point of diminishing returns.
