### ISSUE TITLE
Nominate a Director

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#505]
Fill the spot left by Alex Bulkin.

> Dear members of the RChain coop and the broader community of supporters! 
>
>It is after no small amount of hesitation that I have announced to the Board of Directors of the Coop of my resignation from the Board. 
>
>The reasons behind this decision are simple: while I remain an ardent supporter of innovation brought about by the RChain cooperative, I recognize that over the last 6 months the project has grown to significant complexity: complex technology, complex community, complex governance, and complex relationships with other related efforts. As my own efforts at CoinFund have also ramped up to demand most of my time, I can’t help but recognize that I will be unable to contribute to the functioning of the RChain project as much effort and attention as it deserves on part of someone in a position of responsibility. Simultaneously, I watch others in the organization step up to take effective leadership roles, and take on increasing responsibility for the community and the growth of the RChain ecosystem. It is then the most ethical course of action for me to offer the seat on the RChain board to someone who can be more present and effective with the project than I am able to. 
>
>I am certainly going to continue to watch the effort and participate when able. I believe RChain technology represents an incredible level of innovation in the blockchain space and I support it wholeheartedly. 
>
>Alex Bulkin

**Comment by kitblake** [comment]
+1 on another outsider with reputation, as opposed to an insider.

**Comment by Valentine-Mario** [comment]
Do you have any suggestions or we just pick randomly?
