### ISSUE TITLE
Translate the video ''Roscala Interpretation for VM'' into Chinese 

### ISSUE THREAD

**Issue by han014** [rchain/bounties#508]
Check "Roscala Interpretation for VM" video's subtitle offered in #347 by @zsluedem and translate it to chinese version after English subtitle review.  

I will complete it with @Whisker17

Suggested Budget: 220$ (0.2$ for each word)
Time: #about 3 days

**Comment by han014** [comment]
Have uploaded the reviewed and translated files in [](https://drive.google.com/drive/u/0/folders/1-zU302BURFk0RhK1UXor_1kmTMFWQggm).

**Comment by han014** [comment]
Have uploaded the reviewed and translated files [here](https://drive.google.com/drive/u/0/folders/1-zU302BURFk0RhK1UXor_1kmTMFWQggm).

**Comment by han014** [comment]
Close this issue.

**Comment by zsluedem** [comment]
well done!!

**Comment by lapin7** [comment]
And is the SRT attached to the video?

**Comment by han014** [comment]
Yes

________________________________
发件人: HJ Hilbolling <notifications@github.com>
发送时间: 2018年3月19日 14:30:13
收件人: rchain/bounties
抄送: #LU; State change
主题: Re: [rchain/bounties] Translate the video ''Roscala Interpretation for VM'' into Chinese (#508)


And is the SRT attached to the video?

―
