### ISSUE TITLE
Outreach - "Rholang Tutorial" videos

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#51]
This is a big one guys! Alex Bulkin of Coinfund, Joe Denman, Greg and others are going to spend some time at the end of this month hammering out "Rholang Tutorial" videos. 

As a community we can assure that it reaches the largest possible crowd of interested developers.

We are talking about creating a Udemy course series for Rholang and a Consultancy program for early Rholang certified developers. 

We also have the noob-study group that takes place thursdays at 2Pm, is there a way that we can synergize and formalize that so that it creates more Rholang developers? 

What other types of content and outreach can be done around learning Rholang? 

Let's start now!

**Comment by pythonical** [comment]
How are the videos coming along?

**Comment by lapin7** [comment]
Good question!!!!
Who knows the answer?

--
Cheers,
HJ

**Comment by lapin7** [comment]
@dckc I close #169 and leave #51 open.

**Comment by dckc** [comment]
I did some relevant work by reviewing Mike Stay's...

 - [Add Rholang-Mercury tutorial doc](https://github.com/rchain/rchain/pull/159)

**Comment by dckc** [comment]
since this one is not currently in the Jan budget sheet, and it's really about videos, I'm going to close this and re-open #169.

**Comment by lover33** [comment]
I would love to create videos to spread awareness and show how to operate simply in the Rchain system

**Comment by dckc** [comment]
Go for it, lover33!

**Comment by dckc** [comment]
I think @lover33 is using other issues to track his work.
