### ISSUE TITLE
M> make chinese contributing && readme file up to date

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#510]
### For all issues

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

Currently our bounties system update a lot, so the chinese version should also up to date.

_Estimated Budget of Task:_ **$[300]**  \
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**  \
_Measure of Completion:_ **100%**

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #570 #474 #470
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by rjl493456442** [comment]
@zsluedem I have created the budget allocation in the https://rewards.rchain.coop/. Please type in the reasonable budget amount and your percentage! Thanks.

**Comment by ICA3DaR5** [comment]
I am opening this again to ask @rjl493456442 for a link to the final work.

**Comment by rjl493456442** [comment]
@ICA3DaR5  [Contributing](https://github.com/rchain/bounties/blob/master/CONTRIBUTING/CONTRIBUTING_CN.md) && [Readme](https://github.com/rchain/bounties/blob/master/README/README_CN.md)

**Comment by ICA3DaR5** [comment]
@rjl493456442 Could you please fill correctly the **For Translators** section.
