### ISSUE TITLE
Rholang ace editor grammar rules

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#514]
@tgrospic and I was working on the ace editor rholang rules. We have made the first version ace editor  rules now and had make a pr to the ace editor.(It seemed a little bit late, sorry for the delay)

[Here](https://github.com/ajaxorg/ace/pull/3614) is the commits we make.

@tgrospic said "we can improve tmLanguage version and just generate it for multiple editors without modification so we can easily automate things."

**Comment by dckc** [comment]
so this is part of #268 ?

**Comment by dckc** [comment]
oh... I see... this would do syntax coloring of rholang for all of github

**Comment by dckc** [comment]
ah... no, that would be https://github.com/github/linguist 

Any chance these rules work with linguist?

**Comment by dckc** [comment]
Ah! yes... linguist uses ace: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L6

**Comment by tgrospic** [comment]
I think it uses Ace and CodeMirror only for editing. For source grammar it recognizes TextMate format (tmLanguage).

I will make PR to linguist, for now you can see demo [Rholang lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftgrospic%2Frholang-sublime%2Fmaster%2FSyntaxes%2FRholang.YAML-tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Frchain%2Frchain%2Fmaster%2Frholang%2Fexamples%2Ftoken.rho&code=).

**Comment by tgrospic** [comment]
PR to make Rholang syntax highlighted on GitHub. :smiley: https://github.com/github/linguist/pull/4071
