### ISSUE TITLE
O> 20180321 RChain Active Members Meeting 

### ISSUE THREAD

**Issue by Tonyprisca13** [rchain/bounties#518]
****ZOOM LINK FOR RAM MEETING 21 MAR:****
[**https://zoom.us/j/197490909**](https://zoom.us/j/197490909)
2018-March-21, 19:00 UTC (after Greg's Debrief)
Sydney +11, Beijing +8, Greece+2, Lagos +1, Amsterdam +1,
New York -5, Seattle -8

- [x] Prepare report for Greg's Debrief

- [x] Prepare [RAM meeting agenda](https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64/edit?ts=5aa05d54#heading=h.qqz7b4owu041)

- [x] Any key discussion points anyone wants to address should be added to the agenda and we can
allocate time accordingly

@makys @raob @dcplnau @Ojimadu @kitblake @lapin7 happy for additional agenda items to be added by any of the members. Please add to agenda

**Comment by kitblake** [comment]
@Tonyprisca13 Thanks, I made a slight adjustment to the UTC + times for the States (New York -4, Seattle -7) as DST has kicked in there but not in other parts of the world. 
Unfortunately I inhabit one of the regions still observing this irrelevant artifact, so I always check: https://www.timeanddate.com/worldclock/converter.html?iso=20180321T190000&p1=234&p2=179&p3=16&p4=33

**Comment by dckc** [comment]
I'll make my pitch for using the **RAM-weekly-agenda** label one more time.

For example, it clarifies who requested the agenda item.

Who requested these?

 - Update on concern surrounding translation issue@dckc@raob@Jake Gillberg
 - Operate Account For Spread Rchain On Bibu(Issue 457 @Jiel314@Abnerzheng)
 - 2 Week Ui/Ux Mock Ups (Issue 446 @Patrick@Ayayron@Kitblake@Makys)

I'll also repeat my request for clarity on what is the goal of each agenda item, noting that "an update on issue X" is unlikely to be a good use of time, given that we can all read issue X. If the discussion in issue X is too long and rambling, ask someone to do some summarizing / gardening in issue X.

**Comment by dckc** [comment]
@Tonyprisca13 you're claiming 70% of the budget for this meeting? I can't imagine any one person contributed more than 25% of the value of the meeting.

**Comment by Tonyprisca13** [comment]
@dckc  i did not vote myself on did issue

**Comment by Tonyprisca13** [comment]
@dckc u have no part in these issue let those involved in this vote.

**Comment by Tonyprisca13** [comment]
@kitblake i think i have done that

**Comment by kitblake** [comment]
Thanks. 
@Keaycee, adjusting your budget is kinda hidden. You have to click on your budget number (in the Amount column of the table), then click "Open this record in the Budget Vote table". Then at the top will be a Delete button. Click the Delete button and then re-add your new vote.
