### ISSUE TITLE
On-board @klysford, Translation and QA specialist

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#519]
[Kelsey Lysford](https://www.linkedin.com/in/kelsey-lysford-b004a821/) has expressed interest in helping out with translation organization and any QA that might be needed.

Not all these steps are required, but here are some things you might want to do:

- To participate in bounty program / get paid:
  - [x] register on https://member.rchain.coop/#/sign-up
  - [x] become a verified member on discord
  - [x] become a collaborator on rchain/bounties
  - [ ] Send your name, email, github name to ops@rchain.coop.
- Other suggestions
  - [ ] become a member of the [google group](https://groups.google.com/forum/#!forum/rchain)
  - [ ] take note of the events in #member-calendar (especially the weekly Wednesday sessions)

**Comment by klysford** [comment]
Hi everyone, I'm Kelsey!

I've been in QA for around the last three years; two at a large healthcare company and now I'm currently at a web based startup.  At my first job I was also one of three British English translators, as well as a backup Danish and mobile localization lead.  I love localization and making things accessible to larger audiences, and I view it as a vital part of the QA sphere.

I'll be coming into quite a bit of free time in the next few weeks, and Jake has offered to help me get up to speed.  He's given me some background on the current state and I think I could be of some help.

Pleasure to meet everyone!

**Comment by makys** [comment]
Welcome @klysford . Nice to have you on-board. I am interested in finding out how you'd perform QA on languages your are not conversant with. Maybe there is a skill to this, idk. Or maybe we need different QA like yourself to cover the languages we decide to explore.

**Comment by lapin7** [comment]
Hi @klysford 
Please become member through https://member.rchain.coop/#/sign-up

And then become a member of group https://groups.google.com/forum/#!forum/rchain to get access to documents of RChain

And send your name, email, github name to ops@rchain.coop.

**Comment by Ojimadu** [comment]
Welcome @klysford, Nice to have you here.

**Comment by Keaycee** [comment]
Welcome @klysford , Nice to have you On-board. I'm incline to collaborate with you.

**Comment by Jake-Gillberg** [comment]
> And send your name, email, github name to ops@rchain.coop.
What is this for?

**Comment by ICA3DaR5** [comment]
@Jake-Gillberg Probably for the Invoices.

**Comment by Tonyprisca13** [comment]
Nice to have you on-board klyford

**Comment by BelovedAquila** [comment]
@klysford warmly welcomed onboard kelsey

**Comment by klysford** [comment]
Thanks for the welcome everyone!

@lapin7 I completed all of the steps - let me know if anything is missing!

@makys - The main QA part re: localization would be mostly aesthetics - verifying the documents/transcriptions all appear without common issues (going off the screen or behind images, characters not appearing correctly, chunks missing, etc).  For most Indo-European languages the patterns can be easy to pick up on and once you know a few key words you're able to at least check if anything is missing :)  This allows translators to focus their time on providing a better text without having to worry about all the steps that come after (and honestly, I find it easier to look for visual issues in how the text is displayed when I can put all the focus on that, and not on reading what's on the page).

Having people to actually verify the translations is a whole sphere I can't do directly (unless you want some hilariously off the mark Dutch sentences), but I can help standardize and streamline the process.  I'm hoping to go through what's already out there in the next week or so and get some insight in what's happening already before I start offering any ideas on what might help in this situation :)

**Comment by lapin7** [comment]
@klysford Thanks.
The rest of the details, like (address, ETH-address, Tax Form) comes at the beginning of April, when you claim your rewards. During March: Be sure to set budgets and rewards for the issues that you participate in. You can do that through in our [Bounty system](https://rewards.rchain.coop)
