### ISSUE TITLE
Write up for Namespace discussion

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#524]
Write up of the namespaces discussion that just got published to be published on medium.

https://www.youtube.com/watch?v=EHUteN2Aw5Y&feature=youtu.be

This would include a summary of the main points with links to the developer wiki, website as well as RChain github repo and references made.

**Comment by David405** [comment]
@patrick727 you first sentence isnt all that clear, a little clarity would help.

**Comment by Valentine-Mario** [comment]
I don't grasp at all

**Comment by dckc** [comment]
from a Development perspective, I think the time for this has come and gone.
Perhaps it's still useful for Marketing... @pmoorman ? @patrick727 ?

**Comment by pmoorman** [comment]
yeah, I would suggest we roll it into the website update.  It'll serve as input there.

**I'll close this issue for now.**
