### ISSUE TITLE
O> Preparation of invoices 201802

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#529]
Prepare invoices for RAM's (RChain Active Members) for work done in February

Measure of Completion:  Gsheet-invoices for 201802 in personal spreadsheet of RAM's
Date of Completion: 04-01-2018
Suggested Budget: $500

- [x] Create TAB "Rewards 201802" [Declaration](https://docs.google.com/spreadsheets/d/19Y5aEZelHa2JISCXB6jViTiRx9H0cCmha8arYz7vbg0/edit#gid=46872367&range=A1:G4) _Access is only for RChainFin_
- [x] Create personal TABs (201802-githubname) in [Declaration](https://docs.google.com/spreadsheets/d/19Y5aEZelHa2JISCXB6jViTiRx9H0cCmha8arYz7vbg0/edit#gid=1690363621&range=A2:C3) 
- [x] Copy personal TABs to personal invoice Gsheet
- [x] Send personalized email to RAM's with Gsheet
- [x] ops@rchain.coop receives and checks PDF-invoices
- [ ] invoices@rchain.coop receives PDF-invoices and creates payment register
- [ ] Ops enters payments in Gnosis-Multisig
- [ ] COO confirms payments

**Comment by David405** [comment]
@lapin7 I would like to know, for 201803 using the xataface web app, does reward vote also requires a minimum of 3 entries to be valid?

**Comment by lapin7** [comment]
@David405 For 201803 budgets and rewards:

- A valid budget contains at least 3 votes
- A valid reward has a valid budget and contains at least 3 votes.
- A valid budget/reward vote can only be done by "verified members"
- Voting on budgets and rewards is open to anyone, but only the votes of "verified members" are able to influence the amount/percentages.

**Comment by ian-bloom** [comment]
@lapin7 - The email address invoices@rchain.coop is receiving many invoices directly from members who are seeking bounties. Perhaps you should forward all approved invoices _from your own email_, so that recipients at invoices@rchain.coop can be sure that they are legitimate and have been approved by you.

**Comment by lapin7** [comment]
@ian-bloom I had a discussion with the CFO about this. She wanted to be sure that the invoices are send by email by the members themselves. I've no insight in what invoices@rchain.coop is receiving. Maybe you have. And please give a list of invoices that claim bounties and are directly send. However I have no problem with forwarding invoices to invoices@rchain.coop.

It's also a question of ownership of the invoice. My stand was that the member could own the invoice. And that the member could store it in it's personal folder: Invoices. Whereas the CFO said that RChain has to be rightful owner of the invoice and that RChain had to be sure that the invoice had to be send by the member.

**Comment by dckc** [comment]
rewarded 201803
