### ISSUE TITLE
 March Seattle rchain coop meetup

### ISSUE THREAD

**Issue by wordsandstuff** [rchain/bounties#534]
On march 6th I hosted this event in seattle https://www.meetup.com/Seattle-RChain-Meetup/events/247667491/

We had about 70 people show up of the 120+ that rsvp ed
 
I paid out of pocket . Cost was 507.04 . There was food and beer and wine and a single bottle of whisky. All the food and most of the drink was gone by the end.

Lawrence of pithea and chris boscalo of life id spoke. 
![20180320_143342](https://user-images.githubusercontent.com/31779766/37732652-f08fc96a-2d02-11e8-96a7-41d0690cb0d5.jpg)

**Comment by BelovedAquila** [comment]
Interesting, it was a productive effort @wordsandstuff 
cheers!

**Comment by ResonanceXX** [comment]
@llerner of Pithia is a warehouse of information.

Good looking out to him and other RChain experts. Cheers!

**Comment by Ojimadu** [comment]
This seems to be done and paid for. Am closing this off.
