### ISSUE TITLE
Newsletter - March 21st, 2018

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/bounties#535]
Thanks for the help last week (#467). I would appreciate reviewing from anybody present for the 3/14 and 3/21 debriefs on the [google doc](https://docs.google.com/document/d/1Va_u-I_IWCvpWVgQXNKsFuhpaH-enouhPotJMTGoiRM/edit) for this next newsletter.

**Comment by BelovedAquila** [comment]
@TrenchFloat I will with the review
