### ISSUE TITLE
O> Video Tutorial for Bounty Budget/Rewards Web App

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/bounties#536]
I will be making a short video tutorial for the [budget/rewards web app](https://rewards.rchain.coop/) in #506 to go with the [tutorial page in the wiki](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App) per @lapin7 's email earlier this month: "The payment process will start at the end of the month. It would be great if somebody creates a new attractive video." I plan to finish this by Friday. Any suggestions to include apart from walking through the existing wiki page are welcome!

Measure of Completion:  Video is uploaded to the [wiki page](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App)
Suggested Budget: $800

**Comment by dckc** [comment]
The **bounty-contract** label is intended for _changes_ to the bounty contract.

**Comment by dckc** [comment]
@TrenchFloat the [user cases](https://github.com/rchain/bounties/issues/260#issuecomment-362630020) from the prototype should make for a good script. "permission-less access" is perhaps not all that relevant, but the rest do look relevant.

Note the [invoice preparation use case](https://github.com/rchain/bounties/issues/260#issuecomment-362683050) later in the issue; we probably don't have enough data in the system to record that stuff yet, though.

**Comment by lapin7** [comment]
@dckc how can I create an example invoice? I guess I need some data with at least 3 confirmed budgets and 3 confirmed rewards.

**Comment by David405** [comment]
@TrenchFloat  @lapin7 seems <a href="https://github.com/Valentine-Mario/vid"> This </a> might be interesting to see

**Comment by dckc** [comment]
exactly, @lapin7 

I / we can insert some test /demo data into the database if you think it's worthwhile. I hope we have sufficient real data sufficiently soon that it's not worth the bother, though.

**Comment by TrenchFloat** [comment]
@David405 This video might work, but it was pretty hard for me to watch and understand. The audio was jumping and an error screen came up and stopped playback whenever I got to a certain point in the video, like 2:49 for example. The latter might be client side; would @dckc, @lapin7 or anyone care to see if the video plays differently for them?
If there is a motion to use @Valentine-Mario's video for the wiki page, that is an option. Until then, though I will keep working on a video myself for the wiki page.

**Comment by TrenchFloat** [comment]
https://drive.google.com/file/d/12aOF6uV3lEnYBFtqV9KHllw-Xi-BB1Ux/view?usp=sharing Here's what I came up with. If no one objects, I'll put it on the wiki page tonight (7 or 8 hours from now).

**Comment by Keaycee** [comment]
@TrenchFloat Good job. The video was pretty easy to comprehend.
