### ISSUE TITLE
Website patch #2 :: Update team/about section 

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#538]
### Context
Messaging & communications on the rchain.coop main website could be improved. The 'Branding WG' (working group) will engage an external Seattle-based firm for a full branding overhaul, but in the meantime I plan to release "patches" (for lack of a better name) to the current website on a weekly basis. 

### Scope  ::   _update 'about' part of the website_
I try to keep the scope of each patch as small as possible, aiming for _incremental improvements._ Shipping it is better than perfect.

The scope of this patch will be to...  **update the 'about' part of the website.** 
This includes rethinking the sections "officers & team", "board of directors" and "partners"

- We will stay on Squarespace
- We won't rework visuals (but we'll update the images of team members)
- We might consider to move the 'about' stuff into a separate page, and give background on governance-related stuff there. For instance: we might want to add something about "why we are a coop", etc.

### Small things to take care of

- [ ] Reconsider who's names need to be mentioned at which places (given that the role of the website is to sell RChain to Maven's and other early adopters) 
- [ ] Make sure all people that are mentioned have an actual image (Navneet, for instance)
- [ ] Put logo's of partners with each partner (per request of Nash Foster)
- [ ] Incorporate fixes as outlined in Github issue #456 

### Info for collaboration
- If you have team-related fixes that you'd like to see incorporated, comment below!
- I plan to roll out this release next week
- @ddayan will help me with this release
- If you want to collaborate on this, please contact me directly to coordinate (because I'm the person with Squarespace write access)

Suggested budget: $2.000

**Comment by ResonanceXX** [comment]
@pmoorman The possibility of making the few adjustments from #456 is a mood lifting event. 

I also would encourage improvement on the thorough and uniform assembling of both texts and visual elements of the website. 
Ours' is an amazing website, that I relish visiting even for no urgent reason.

This is the first ''embassy'' of our enterprise. It would greatly benefit both our ventures, the Coop and our objectives if the website regularly makes important updates.
Cheers!

**Comment by ddayan** [comment]
I agree the whole look & feel of the website needs to be changed.

In regards to this patch I have most of the code ready. I’m waiting for the pyrofex assets which Nash said he will deliver tomorrow and I still need to write some info about the board. Will try to have a staging environment for people to review before pushing it to the live site.

**Comment by ResonanceXX** [comment]
@ddayan Hello, I definitely would concur with you again.

Rest assured that any review activity would be delightfully carried out. Especially by a host of Coop members to ensure a satisfactory output.
When that is ready. Please notify (You definitely should).
Good luck while you're at it.

Cheers!

**Comment by ddayan** [comment]
**Board of Directors**
Here's my redesign of the board of directors.
Which fixes (in my opinion) the following:

1. Reduces the scroll size of the page. That makes the tech and mission info the main section of the website. It also helps the smaller sections like partnerships and communication channels to be more reachable.
2. Social media links. At the moment some board members are linked to a linked-in account, there's no visual indication for that behavior and no option for multi-social media links.
3. Consistent behavior. At the current site clicking on some board members redirects to linked-in, and for others it opens an overlay with the same information.


Desktop view:
<img width="1433" alt="screen shot 2018-04-05 at 10 29 46 pm" src="https://user-images.githubusercontent.com/285560/38387986-82e62ebe-3922-11e8-97e0-1c1ba286fffe.png">

Mobile view:
![board mobile view](https://user-images.githubusercontent.com/285560/38388617-6d78c238-3924-11e8-87cc-3a6a03418117.jpg)


**Partnerships section**
Desktop:
<img width="1430" alt="screen shot 2018-04-05 at 10 39 24 pm" src="https://user-images.githubusercontent.com/285560/38388642-80d7eb2e-3924-11e8-9d39-2a9de279b15a.png">

Mobile:
<img width="400" alt="screen shot 2018-04-05 at 10 57 16 pm" src="https://user-images.githubusercontent.com/285560/38388734-bed8a332-3924-11e8-8b94-f5f3f3abd159.png">


**OFFICERS & TEAM**

This section seems to be redundant at the moment. Most of the team is listed in the board section and the info can be combined. There are other people in the community that have an active role (eg. dckc), imho either we have a longer list of the active members or we remove this part for now.

**Research & Development**

I want to suggest that we will have a section that lists the research & development team. I think it will be useful for the following reasons:

1. Clarifies Greg's role as the chief architect of the platform.
2. Links to social media & github, Nash regularly posts about rchain on medium and twitter. Michael posts on medium too.
3. Transparency about the dev team shows competence and can persuade dapp developers to develop on rchain (testnet release is not far away).
4. Shows more details about the pyrofex-rchain partnership.

* this will need to be approved by the pyrofex team and Michael B. 

mockup:
<img width="1430" alt="screen shot 2018-04-06 at 12 42 13 am" src="https://user-images.githubusercontent.com/285560/38393417-69ece55e-3933-11e8-9909-cfa1e9fc8e21.png">

I don't have access to the Squarespace account, but I made sure it can be added to Squarespace templates easily via dev mode.

**Comment by kitblake** [comment]
Looks great @ddayan 👍

**Comment by lapin7** [comment]
Please change my pic

![image](https://user-images.githubusercontent.com/1913335/38452243-7233f140-3a40-11e8-969f-f5d862436597.png)

**Comment by ResonanceXX** [comment]
I always thought @Lapin7's picture identity was very informal IN comparison to the obvious standard. This could be corrected. 

Sent from Yahoo Mail on Android 
 
  On Sat, 7 Apr 2018 at 7:48, HJ Hilbolling<notifications@github.com> wrote:   
Please change my pic

**Comment by Ojimadu** [comment]
Great work @ddayan. Greg Meredith's appears twice, one of which I assume should be Kenny Rowe's who is a board member, COO of RChain and Co-founder of MakerDAO.

**Comment by ddayan** [comment]
@lapin7 can you upload a square profile pic? There's no enough space to crop this one.

**Comment by lapin7** [comment]
![image](https://user-images.githubusercontent.com/1913335/38466952-7aab5f56-3b31-11e8-8450-47f015756739.png)

**Comment by ddayan** [comment]
Thanks for picking that up @Ojimadu . I'm waiting for input from the patch moderators (I'm assuming it's @ian-bloom, @pmoorman, @patrick727, @dckc)  before I fix things.

**Comment by ddayan** [comment]
@dckc Sorry I saw you approved patch#1 so I thought you might be involved.
