### ISSUE TITLE
blog in the rchain.coop domain with multi-language support

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#539]
In these other issues, I propose keeping the collaboration mechanism as-is but publishing the result under the rchain.coop domain:
 - #418 google docs
 - #411 github pages
 - #458 readthedocs

But Medium no longer offers that choice.

@ICA3DaR5 offered to look into it.
https://github.com/rchain/bounties/issues/483#issuecomment-375679771

Note:
> I [@ian-bloom] favor Multi-language WordPress -- #428

**Comment by ian-bloom** [comment]
(post moved from #483 2018/03/24)

@ICA3DaR5 Sometime around last Saturday #403 meeting you expressed your preference for WP [Polylang](https://wordpress.org/plugins/polylang/) over [WPML](https://wpml.org/), and showed me the open source translation platform [Weblate](https://weblate.org/en/).

Since we are looking at tools that play nice with WordPress, how about [GlotPress](https://wordpress.org/plugins/glotpress/)? That is the tool being used by the large volunteer project to [translate WordPress](https://translate.wordpress.org/).

I also like the way their volunteer translation project is structured. Here is their [HANDBOOK](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/).

WordPress polyglots community even has a [process](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/#become-a-translation-editor) for screening translators:

> Before your translations become part of WordPress, they will need to be approved by a translation editor – a trusted member of the polyglots community who can also appoint new translation editors.

**Comment by kitblake** [comment]
@dckc said: "But Medium no longer offers that choice." 

Does this mean that Medium no longer allows parties to have their own URLs?

Here's an example:
![kybernetworkblog](https://user-images.githubusercontent.com/912545/37877508-a12f7f3e-305c-11e8-96ea-6ba9eca38e14.png)

This is the Kyber Network blog, at https://blog.kyber.network/, with English, Korean, and Chinese versions. Plus a blog Intro and a link to the main website.

**Comment by dckc** [comment]
"Medium is no longer offering new custom domains as a feature. " --
https://help.medium.com/hc/en-us/articles/115003053487-Custom-Domain-FAQ

**Comment by kitblake** [comment]
Thanks. That'll be their loss.

**Comment by dckc** [comment]
The [RNode v0.3.1 blog item][1] by @nashef is really nice... so nice that it makes me sad, again, that we're sharecropping on medium.

Looking around a bit, I found...

> Luckily, one place where you can syndicate your content without this penalty is Medium. Medium tells Google, “Hey, this is syndicated content and the original version exists elsewhere.” -- [Tchiki D. July 21st, 2017](https://contentwriters.com/blog/syndicate-content-medium/)

[1]: https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82

**Comment by ICA3DaR5** [comment]
I found out that [Ghost](https://ghost.org/) supports multiple languages.

Ghost is also very minimal and the blog posts are written in Markdown (with a Markdown toolbar available and live preview).

Also, we can host it on our own servers. What do you guys think?

**Comment by dckc** [comment]
I don't see any advantages of Ghost over wordpress.

**Comment by ICA3DaR5** [comment]
@dckc Let me sum-up a few of the advantages of Ghost:

- Simple to use and easier to set up
- Easy-to-use built-in SEO and Social Media
- Built-in email subscription
- Independent tests have found Ghost to be up to 1,900% faster than WordPress

Read more about it [here](https://ghost.org/vs/wordpress/)

**Comment by dckc** [comment]
Easy to use is mostly a function of what people around you know. @kitblake , @ian-bloom , @jeremybusk , etc. know wordpress. We'd have to learn ghost. (I've kicked the tires on ghost; I found it acceptable but unremarkable). A typical RChain community member is much more likely to have experience with WP than Ghost.

Setup cost for WP is not an issue. I'm not aware that the folks who have ongoing operational responsibility for rchain services have experience setting up Ghost. They're the ones who have long-term responsibility, even if you set it up initially.

WP does email just fine.

Speed is a possible advantage for Ghost. But in the article you cite, they tout simplicity of setting up Ghost by comparing their hosted solution with self-hosted WP, which is ridiculous when wordpress.com has been around for ages. So I'm highly skeptical about their performance claims. In any case, I expect WP performance is going to be acceptable.

**Comment by ICA3DaR5** [comment]
@dckc Alright then!

**Comment by Barkov-F** [comment]
@ICA3DaR5 Did you set up a budget for running a Ghost-node? I guess, if you take the content from the local language medium pages and host in on a single coop-run domain it would generate some traffic. I have registered "rchain.world" and can sell it back to the Coop for 1 RHOC.

**Comment by ICA3DaR5** [comment]
@Barkov-F I didn't set up a budget. I can't speak in behalf of the Coop for the offer you made.

**Comment by dckc** [comment]
Do I really have to contact them individually to track this work? Can't we continue to coordinate via this issue, or at least some other shared web page?

**Comment by dckc** [comment]
I guess I'm willing to keep in touch with them and update this on their behalf.

**Comment by dckc** [comment]
TODO: syndicate from http://www.madmode.com/

cc @ottermagically @kitblake

**Comment by dckc** [comment]
This seems to be subsumed by https://rchaincommunity.xyz/ (#588 ) and https://blog.rchain.coop/
