### ISSUE TITLE
Translate the Medium blog posts to Chinese part 1

### ISSUE THREAD

**Issue by HaizhenZhuo** [rchain/bounties#541]
Tasks:

- [x] Copy the posts to text files.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Italian.
- [ ] Post them to the Italian [Medium]() account.

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #242 #246 ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

I have translated four Medium blogs into Chinese.
1. [RChain node version 0.1.3 released](https://medium.com/rchain-cooperative/rchain-node-version-0-1-3-released-ede6cb2d57f7) [367words]
2. [RChain Ecosystem Update 2018](https://medium.com/rchain-cooperative/rchain-ecosystem-update-2018-6ae475bcb7b8) [1209words]
3. [RChain Node.Hello (v0.1) Released](https://medium.com/rchain-cooperative/rchain-node-hello-v0-1-released-98d255a9567d) [227 words]
4. [RChain Rholang SDK (v0.1) Released](https://medium.com/rchain-cooperative/sdk-v0-1-5f6bc35bf3e9) [317words]
5. [RCHAIN: WITH CONCURRENCY AND DIVERSITY.](https://medium.com/@kenechukwuoliaku/rchain-with-concurrency-and-diversity-114926d0e046) [920 words]
6.[Resonate and lifeID collaborate](https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6) [991 words]

Suggested Budget: $810 (for 4031 English words)

**Comment by tigermumu** [comment]
May I join this issue ?

**Comment by lapin7** [comment]
To contribute to RChain:

   - Join RChain Coop by signing up for membership
   <http://member.rchain.coop/>
   - Join https://groups.google.com/forum/#!forum/rchain/join to get access
   to documents of RChain. rchain@googlegroups.com
   - Join github/rchain/bounties
   <https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md> in
   order to contribute
   - Send your discord name, github name and real name to ops@rchain.coop.
   - Read about our decentralized bounty system.
   <https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App>



--
Cheers,
HJ

**Comment by tigermumu** [comment]
Hello Sir:

My Discord ID is tigermumu#3910, GitHub name is tigermumu, real name is 刘国威

Mr Ian has already interviewed me and passed.

Thank you ~

Best Regards


> 在 2018年3月26日，下午7:59，HJ Hilbolling <notifications@github.com> 写道：
> 
> To contribute to RChain:
> 
> - Join RChain Coop by signing up for membership
> <http://member.rchain.coop/>
> - Join https://groups.google.com/forum/#!forum/rchain/join to get access
> to documents of RChain. rchain@googlegroups.com
> - Join github/rchain/bounties
> <https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md> in
> order to contribute
> - Send your discord name, github name and real name to ops@rchain.coop.
> - Read about our decentralized bounty system.
> <https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App>
> 
> 
> 
> --
> Cheers,
> HJ
>

**Comment by linsheng9731** [comment]
Great! i will translate those documents into chinese with @RowlandZhou @yyh1102 .
https://medium.com/rchain-cooperative/a-visualization-for-the-future-of-blockchain-consensus-b6710b2f50d6 [8756]
https://medium.com/rchain-cooperative/annual-meeting-summary-3827a82a2e33 [5391 words]
https://medium.com/rchain-cooperative/the-first-membership-meeting-will-be-held-on-october-24th-6f2d13fdf4cc [3266 words]
https://medium.com/rchain-cooperative/vlad-zamfir-joins-the-rchain-cooperative-a05f8e32c110 [2509 words]

**Comment by yuhuanmocmoc** [comment]
@linsheng9731 Well done

**Comment by linsheng9731** [comment]
@yuhuanmocmoc I have finished the document "a-visualization-for-the-future-of-blockchain-consensus", and i uploaded it to[ google doc](https://docs.google.com/document/d/1PtkzlQruW3CswAOce1XhgHdmyE1dxVUrl4Q6zCDAxeI/edit?usp=sharing)c.

**Comment by linsheng9731** [comment]
In order to facilitate the calculation of budget，i made another issue #625 .

**Comment by yuhuanmocmoc** [comment]
@linsheng9731 It's nice.

**Comment by yyh1102** [comment]
Have done the translation work and upload it to [google doc](https://docs.google.com/document/d/1eluC3q8BljOVyXN0aRBIqzEg_1ZOZOA7D5T4qY4wrEo/edit)

**Comment by yuhuanmocmoc** [comment]
all the translation Medium blogs have uploaded to [google doc](https://drive.google.com/open?id=1SoO3bcXzJt3rO1me-Kr9a-P_Kb7iD_6A).

**Comment by ICA3DaR5** [comment]
Please post these on a blog post, a google docs document doesn't bring any benefit to the RChain Cooperative.

**Comment by yuhuanmocmoc** [comment]
@ICA3DaR5 we have posted all of them to the Wechat official account of China.

**Comment by ICA3DaR5** [comment]
This seems to have been completed, closing it.

**Comment by yuhuanmocmoc** [comment]
all the translation work have been uploaded to [google doc](https://drive.google.com/open?id=1UfGOJ6ox67zw3WBTxTKuBZ-6jBOkQyqt)
