### ISSUE TITLE
Translate "Blockchain Use Case: Supply Chain" into Chinese

### ISSUE THREAD

**Issue by han014** [rchain/bounties#542]
Check "Blockchain Use Case: Supply Chain" video's subtitle offered in #347 by @zsluedem and translate it to chinese version after English subtitle review.

I will complete it with @Whisker17

Suggested Budget: 1000$ (0.2$ for each word)
Time: #about a week

**Comment by lvsik** [comment]
@lapin7 , I want to cooperate with @Whisker17 and @han014 , but no invitation.

**Comment by han014** [comment]
Have finished this work and uploaded file [here](https://drive.google.com/drive/u/0/folders/1tY8W5qWfe7EA1-K7LlkjGCOJhMiaychS).

**Comment by han014** [comment]
Close this issue.

**Comment by dckc** [comment]
What word count are you using? In #347, a word count of 3900 is given; 3900 * .2 = $780. And yet the current budget votes are $1200. Why is that?

**Comment by han014** [comment]
I am so sorry that I mistaken the budget vote as 1200. The actual budget is $1000 including the English subtitle review and translation. Also, after reviewing, there is more word count.  I will revise the budget vote.

**Comment by ICA3DaR5** [comment]
From now on please use the [ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)
