### ISSUE TITLE
Translate "Block formats, Types, and Messaging" into Chinese

### ISSUE THREAD

**Issue by han014** [rchain/bounties#543]
Check "Block formats, Types, and Messaging" video's subtitle offered in #347 by @zsluedem and translate it to chinese version after English subtitle review.

I will complete it with @Whisker17

Suggested Budget: 800$ (0.2$ for each word)
Time: #about a week

**Comment by lvsik** [comment]
@lapin7 , I want to cooperate with @Whisker17 and @han014 , but no invitation.

**Comment by lapin7** [comment]
@Ivsik


To contribute to RChain:

   - Join RChain Coop by signing up for membership
   <http://member.rchain.coop/>
   - Join https://groups.google.com/forum/#!forum/rchain/join to get access
   to documents of RChain. rchain@googlegroups.com
   - Join github/rchain/bounties
   <https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md> in
   order to contribute
   - Send your discord name, github name and real name to ops@rchain.coop.
   - Read about our decentralized bounty system.
   <https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App>




--
Cheers,
HJ

**Comment by han014** [comment]
Have finished this work and uploaded files  [here](https://drive.google.com/drive/u/0/folders/1Dvy7V4LkmbrUUQE8Pacq3UJ9r18XYz5i)

**Comment by han014** [comment]
Close this issue.
