### ISSUE TITLE
Translate and Compile for Meetup- RChain Intro -Presentation

### ISSUE THREAD

**Issue by InternautNeven** [rchain/bounties#544]
## Issue
Translate original RChain Presentation #102 and compile for Meetup 
I contacted author Mr. J.Bassiri and he gave me permision 
also compiling Presentation will be made with his approval.
It is for Meetup in Zagreb  #125 , 
also translation of Contributing document #382
that we will share at presentation, with copy of Rholang spec 2.0  croatian translation #546
 
 Topics:
-Technical Team
-Problem - scalability
-The challenges
-Current solutions (serialized chains, non-concurrent)
-Governance - Cooperative slide
-Impact on Business and Society

_____

## Original
Presentation: [RChain Intro Deck for the Web.pdf](https://drive.google.com/open?id=1MbeNPF72KV3GhQ4VY4EGdpuvdRBTO8Za)

Translated (Croatian) Content and (English)- [new Presentation](https://drive.google.com/open?id=1_VsBOKXtp9bxYlRZVPi55NDBjwxD8tB5)
Tasks
  *   [x]  Download the original (English) file.
  *   [x]  Translate the content.
  *   [x]  Check the spelling.
  *   [x]  Review each other's work.
  *   [x] Have them reviewed by others with knowledge of English and Croatian.
 Upload it [here](https://drive.google.com/open?id=1_VsBOKXtp9bxYlRZVPi55NDBjwxD8tB5) .

Collaborators
* @InternautNeven
* @Howsoonisnow
* @MarioPolo

 Reviewers:
* @tgrospic 
* @jbassiri  

_____

Translators Q&A
Why this/these document(s)? (mark all that apply)

  *   [ ]  It's one/some of the /rchain/reference document(s).
  *   [x] I contacted the author, who agreed it's important to translate.
  *   [x] I know a person or audience who would benefit from it: The Croatian developers community.
 Other: ...
How can people who do not speak this language be assured of the quality of the translation? (all are required)

 Several reviewers are involved. (assign the ticket to them)
  *   [x] At least two of them have high proficiency in English.
  *   [x] At least two of them have high proficiency in Croatian.
 At least two of them have either:
 Significant reputation Diploma- InternautNeven: (MS) IT Management, Howsoonisnow: (MS) Professor 
 A track record of quality work on rchain bounties: #382, #125, #449 #546
What about maintenance? (choose one)

 *   [x]  The source document(s) is/are stable; further translation work is not expected.
 *   [ ] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by ICA3DaR5** [comment]
Can you please add the estimated price and timeline?

**Comment by ICA3DaR5** [comment]
This seems abandoned, closing this.

**Comment by InternautNeven** [comment]
Yes, it is finished, i`ll put it here in a few days.

**Comment by ICA3DaR5** [comment]
@InternautNeven Please don't close issues that are not finished, meaning that you should always post the final work.

**Comment by InternautNeven** [comment]
This was only addition,for that i will not request reward.- Presentation that helped us, is intelectual property from mr. Bassiry i just made some minimal changes and updates that i will put here in few days- may help someone in future.

**Comment by ICA3DaR5** [comment]
@InternautNeven Okay then. :)

**Comment by InternautNeven** [comment]
Since the presentation is in the form of insights, I will add just a couple of sentences.
The goal was to explain the time and conceptual framework from where the blockchain technology has emerged. Blockchain tehology emerged from cryptography (solution of Byzantine Generals' Problem) as a discipline of Cybernetic (greek word meaning "art of steering"). Cybernetic was defined by Norman Wiener (mathematics professor at the Massachusetts Institute of Technology (MIT) 1948. as a transdisciplinary approach for exploring regulatory systems. It has enormous influence on science and a whole series of discoveries and can be said to have shaped the Information Age that followed. Not all of it was idyllic, automation and robotization of certain jobs, sometimes lead to the high level of unemployment, but all in all, it can be said that it led to positive displacements and humanization of working environment .
Blockchain technology comes in 2008, and one of its definitions is the "global public notary system". We still reveal all it˙s applications, but automatization of workplaces, that play the role of "third party services" in the relationship of exchange goods, information, services are definitely the area that blockchain technology has his future in. And again, jobs will be at steak but all that intermediated services, is better to be automated, and put people on different other positions to gather new knowledges and skills. Blockchain technology today is not without problems, and some of them are related with an old approach and way of thinking. In Cybernetics and system theory all organizations and systems, in order to survive, has to use and share informations (energy) whithout any omit.
And one more important change related with blockchain technology today is that it giving us back possibility to manage our personal data and informations. [Systems thinking](https://www.youtube.com/watch?v=Miy9uQcwo3U) , [Cybernetic definition](http://www.pangaro.com/definition-cybernetics.html) , [Living or dead systems](https://www.youtube.com/watch?v=4eIR1iUw9r4) Thank you all. Issue closed.
