### ISSUE TITLE
Propose and rank taglines for Mavens

### ISSUE THREAD

**Issue by patrick727** [rchain/bounties#545]
- [Determine the communities favorite Taglines for "The RChain Technology" that targets the segment "Mavens"](https://www.loomio.org/p/695jphDR/determine-the-communities-favorite-taglines-for-the-rchain-technology-that-targets-the-segment-mavens-) ranked choice 

I created a rank-choice poll in which you can explore community input on taglines for the "Maven" audience. 

The Mavens are the primary audience for Mercury and the messaging will blend with the secondary audiences of new blockchain devs and hunters because new blockchain devs learn from mavens, and hunters may also be mavens in there own right. 

In this poll you can rank the taglines as well as propose new ones. and comment in the discussion

**Comment by Valentine-Mario** [comment]
Interesting voting system.

**Comment by dckc** [comment]
Note the **M>** prefix is obsolete now: #417

**Comment by patrick727** [comment]
@dckc noted!

@Valentine-Mario yes its loomio!

**Comment by pmoorman** [comment]
@patrick727 I guess this issue can be closed, right?

_(I'm going through the "marketing" issue list, tidying things up)_
