### ISSUE TITLE
Nominations Protocol - Governance

### ISSUE THREAD

**Issue by Eblu2** [rchain/bounties#547]
Gather nominations protocol from bylaws and address any missing protocol items for voting for a new board member.  Pull in the past procedure Ian B. mentioned during the Governance meeting on 3/18.

In order to accomplish this, post nomination draft protocol after information is gathered for co-op members to add to. after two weeks of review by co-op members, open any items that need to be voted on to everyone, then finalize the document and post the protocol. 

-Posted by catH

**Comment by dckc** [comment]
This is pretty similar to #505 ... but I guess it's not quite the same.

**Comment by barneycinnamon** [comment]
@Jake-Gillberg @deannald I think this is under control. If you disagree, please re-open this issue.
