### ISSUE TITLE
Translate "RChain: The real scalable blockchain" to Chinese

### ISSUE THREAD

**Issue by tigermumu** [rchain/bounties#549]
Issue

Original (English) Content

`https://medium.com/@giottodf/rchain-the-real-scalable-blockchain-4be5a43b722b`

Translate to Chinese 

Translated revision
[Link:]( https://pan.baidu.com/s/1rNqWPI41z1rNnX8A122Y_w )
Password: eb44

Completed: 100%
Suggested Budget: $50 ($0.1/word) , 519 words

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because _**This article can be better understood scalable of Rchain**___
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [v] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in (the target language)
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [v] our plan to keep the translation up to date is: 2018/03/30

**Comment by ICA3DaR5** [comment]
What is the status of this issue?

**Comment by ICA3DaR5** [comment]
Closing this. Feel free to re-open if you need to.
