### ISSUE TITLE
Finalise marketing plan for board approval

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#550]
### Context

Amir et al. created a [high-level marketing plan](https://docs.google.com/document/d/1tfoZMB7tedcsqZG6enGsCN4qR6l6AZSCUNrdMUs_0c4/edit) that has been hotly debated in the #marketing-plan-proposal channel in Discord. Right now, the plan is (almost) ready to be submitted for board approval, hopefully due in the 1st week of April.

A few things need to be finalised in the plan, before it can be sent over. This issue will track those activities, and also serve as a gateway to get all people involved in the marketing debate on Github, where collaboration can happen in the open.

### Goal

Finalise the plan and submit for board approval by the end of the week

### Action items

The following updates need to be executed before the document is ready for submission (assignee for each task in brackets):

- [ ] Add section on process (@amir)
- [x] Write short paragraph on branding (@pmoorman)
- [ ] Include results from the Loomio poll of @patrick727 about which strategies should be executed first (@amir)
- [ ] OPTIONAL: Fix title of the document to say "marketing" instead of "maketing". Also remove "draft" status.

- [ ] Submission to the board (@amir)

---

_**P.S.** I'm creating this issue to move discussion about it to Github (because we want more discussion to take place on Github), but for coordination please contact @amir or @ank316 on Discord because they're in charge of the effort!_

**Comment by patrick727** [comment]
thanks for this. I think the biggest sticking point was actually brought up by Jon West and thats the governance around implementation. 

Ultimately its for the board to decide but I propose this. 

1. Keyholder group consisting of myself, Kenny, Reflective rep, Pythia rep, and Pyrofex rep. 
- these people literally just have the keys to a multi-sig and finalize spends based on strategy not tactic. 

2. Implementation group consisting of 5-7 individuals who will direct implementation, hire, report on progress and adaptations. Ideally 1 or 2 keyholders act as bridges. and Ideally Ankur and Amir are in charge of this group. 

3. Hires - specific individuals hired to execute portions of the plan

4. Formal working groups - member WG's chartered by the authority of the implementation group to own portions of the plan

5. Informal working groups - operate in the gray space between Phenomena and KPI's. Rewarded through reward programs or small proposals.  

thoughts?

**Comment by pmoorman** [comment]
### Snippet for branding:

@amir @ank316 (argh, neither are on Github yet!) here's a suggested snippet for integration into the marketing plan regarding branding. My suggestion is to add it at the top of section 8, after "messaging & value props":

> **Clear, unique branding and visual identity to complement messaging & value props ($75k):** 
> The crypto market is in a state of maturity where the most dominant brands can quickly land grab both market share and brand recognition in the customer’s mind. Because crypto is both new but also mission-critical for many implementations, many early adopters will look for a brand that they perceive as trustworthy and reliable. All branding efforts should be coordinated to reinforce the message and positioning in the market. RChain branding should roll out in three stages: a 1st stage tailored to “mavens” and early adopters, followed by a 2nd stage focused on the wider development community, and a 3rd stage (probably in 2019) oriented also towards end-users and the general public. 

I will be out-of-office in the next few days, so I depend on someone else to integrate this.

_**P.S.** To make sure that this reaches Amir in time, I'll also post it to him in 1-on-1 in Discord. Here's hoping more marketing discussions will happen transparently on Github in the future!_

**Comment by Murphy6** [comment]
Can come up with a solution

**Comment by dckc** [comment]
Is this done? @TrenchFloat ?

**Comment by pmoorman** [comment]
Yes, it is.  Let me close this.
