### ISSUE TITLE
Translate the " RChain series: Introduction"

### ISSUE THREAD

**Issue by tigermumu** [rchain/bounties#554]
**Issue**
Original (English) Content
"RChain series: Introduction"
https://blog.coinfund.io/rchain-series-introduction-985a05804ab

**Task**
Translated (Chinese) Content
Reviewed by others with Chinese and English reading skills

**Co-worker**
To be determined

**Suggested Budget**
 $190 ($0.1/word) , 1900 words

**Why this document?**
This article writed by the third party which has neutral view on Rchain and It will helps Chinese community readers understand Rchain more  objectively.

**Due time**
2018/04/07

**Comment by tigermumu** [comment]
The translation has been finished. 
Reviewed in this link: https://zine.la/article/1cff1170359311e8a6c100163e0c1eb6/

**Comment by wiki-yu** [comment]
Great job! Is the website your own blog?

**Comment by tigermumu** [comment]
Yes~Thank you.
Do you like this blog? Here is the link: http://zine.la/

**Comment by tigermumu** [comment]
@lapin7 I am sorry, I am a new member, I haven't experienced the whole process and get the reward yet. So I am not very familiar with this bounty system.
I will do this job once i figure out this.
By the way, Could you provide me the budget standard for reference ? These is a new issue from me without budget which is #578 
Thank you very much!!!

**Comment by ICA3DaR5** [comment]
@tigermumu What's the status of this issue?

**Comment by ICA3DaR5** [comment]
Closing this, but feel free to re-open if you need to!
