### ISSUE TITLE
Website ::  Update Information Architecture, add product pages

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#555]
### Context
Messaging & communications on the rchain.coop main website could be improved. The 'Branding WG' (working group) will engage an external Seattle-based firm for a full branding overhaul, but in the meantime I plan to release "patches" (for lack of a better name) to the current website on a weekly basis. 

### Scope  ::   _expand the website with product pages_
I try to keep the scope of each patch as small as possible, aiming for _incremental improvements._ Shipping it is better than perfect.

The scope of this patch will be to...  **update information architecture and add product pages to the website** 

- We will stay on Squarespace
- We will create a set of product pages on the most interesting aspects of the technology
- I won't update any of the other pages
- Doing this might lead to small overlaps, but we can fix that later. Better too much info than too little.

### Sub-deliverables

- [ ] Update information architecture to allow exploration and understanding of the RChain platform/tech without leaving the website. (IA needs to be viable and practical on Squarespace). Will post here in the comments below.
- [ ] Create a layout or 'template' for the product pages, so we know roughly how to structure the information.
- [ ] Create page on Concurrency & scalability
- [ ] Create page on Correct-by-construction & reliability
- [ ] Create page on Casper POS
- [ ] Create page on Namespaces
- [ ] Create page on (product) roadmap
- [ ] Have dev team edit / review all copy for correctness
- [ ] Update homepage to make these pages discoverable
- [ ] Create events page + separate sub-pages for each event (suggested by @dckc)

### Info for collaboration
- If you have fixes related to the scope that you'd like to see incorporated, comment below!
- My aim is to roll out this release before the 15th of April
- @cryptomillenial wants to help with crafting copy for the Caspar POS page. If you'd like to help with any of the other pages, let me know!
- If you want to collaborate on this, please contact me directly to coordinate (because I'm the person with Squarespace write access)

This is a bigger update, where a lot of copy needs to be crafted, reviewed & implemented. ~$1,000 per product page seems reasonable considering the work.

**Suggested budget:** ~$5,000  (depending on how many pages we ultimately need)

**Comment by pmoorman** [comment]
### Information architecture

The current website sitemap is basically:

- Home
- Events (= registration developer retreat)
- [external links to blog, Github FAQ, developer site, etc.]

I would like to restructure the website to become the primary hub for information regarding RChain. It should more fully serve the role of supporting, educating and selling developers & early adopters every step of the way.

**Suggested new sitemap:**

```
- Home
- Product pages
     - Rhocalc / Rholang
     - Concurrency (scalability)
     - Namespaces
     - Correct-by-construction (reliability / security)
     - Caspar POS
- Governance & team
     - RChain Coop
     - Team / about
     - Board of Directors
     - How to get involved
     - Partners
- Events  (index page)
     - Developer retreat
     - Governance forum
     - {separate page for each other event}

- Unrelated pages such as the "become a member" page (see issue #520)
```

A few practical notes on how to integrate this in the Squarespace site:

- I wouldn't include everything in the navbar. That won't work due to how Squarespace works.

- Instead, all product pages only get linked from the "technology" section of the homepage, and they link to each other (to create a 'product tour' together)

- Events index page gets linked from navbar, all individual event pages get linked only from that hub page

- In this update, I wouldn't update the team/about/governance section of the website. That is the scope of another patch. This one only to focus on product pages (to keep it small & lean)

- **Navbar should still link to blog, developer site, etc.**

### What's next?

1. Please, let me all know what you think of a sitemap like this! 

2. Assuming it's more or less oke, the rest of this particular 'website patch' is about creating the product pages and linking them into the rest of the site structure. 

3. The events section restructuring is so straightforward that we might even release that before the rest is done, as a sort of separate patch.

**Comment by dckc** [comment]
Correct-by-construction is a product? Concurrency? 

One could argue that Rholang and Casper are products, but I don't see how the others are.

**Comment by dckc** [comment]
Also, "Rethink information architecture that is viable and practical on Squarespace. Decide which pages are needed." is an endless scope. Which visitor tasks do you think most motivate a re-think of the information architecture?

**Comment by pmoorman** [comment]
Eh, let's see....

### RE: endless scope
I updated the scope to reflect your comment above. I think it's merely a requirement to establish an updated sitemap... and if we're doing that might as well solicit feedback from others if they think anything else should be added.

My main line of thinking is summed up in the first comment:

> I would like to restructure the website to become the primary hub for information regarding RChain. It should more fully serve the role of supporting, educating and selling developers & early adopters every step of the way.

### RE: product pages

I don't really know how to call them otherwise, but my aim is to deliver on the ambition as stated in the quote above. I want to allow people to explore the coolest features of the RChain platform/tech/product. We'd dedicate one page to the promise of scalability and how that works, one page to how we deliver on our security/reliability-related claims, one page to tell people all they ever wanted to know about Rhocalc/Rholang, etc. etc.

Does that make sense?

I call them "product pages" but _that name wouldn't show up anywhere_. If we're on the same page here, that's good enough.  

If anyone has a suggestion for a more descriptive name for those pages, I'm happy to switch it around.

**Comment by dckc** [comment]
Suppose I said it already fully serves the role of supporting, educating and selling developers & early adopters every step of the way. Not that I believe that, but in what _specific_ ways would you disagree? What _specific_ tasks are not currently well served?

I don't think "find a page about namespaces" is a task many of our readers have in mind when they arrive.

I don't think "update information architecture" is an end in and of itself; that doesn't differentiate information architectures that are better from those that are worse; it only argues for newer designs. It's an argument for change for the sake of change.

I don't _need_ this information; if you come up with better web pages, then we'll probably all know it. But good engineering documentation starts with _why_ just like good marketing copy :)

**Comment by lopezi** [comment]
I can help with this, let's make a brief if you find it a good idea

**Comment by lopezi** [comment]
Why was patrick727 unassigned automatically when i posted?

**Comment by dckc** [comment]
Is this done? Or wontfix?

**Comment by pmoorman** [comment]
wontfix (unfortunately).

I forgot to add the label. Good catch
