### ISSUE TITLE
Translate [RChain Ecosystem Update 2018] into Chinese

### ISSUE THREAD

**Issue by jiyuxuan1944** [rchain/bounties#558]
**Issue**
Original (English) Content
"RChain Ecosystem Update 2018"
https://medium.com/rchain-cooperative/rchain-ecosystem-update-2018-6ae475bcb7b8

**Task**
Translated (Chinese) Content
Reviewed by others with Chinese and English reading skills

**Suggested Budget**
$205.76 ($0.16/word) , 1286 words

**Why this document?**
It's important to translate because  it's an [RChain blog] item,and this will help Chinese fans know better about RChain Ecosystem.

**Due time**
2018/04/10

**Comment by han014** [comment]
Good.

**Comment by Jake-Gillberg** [comment]
This isn't a technical document, I recommend a budget closer to $.10/word

**Comment by jiyuxuan1944** [comment]
I have done the work.The translated article was published on the Rchain Chinese website, and the WeChat Offical Account.
[http://www.rchain.site/?p=506](url)
[https://mp.weixin.qq.com/s?__biz=MzU0MzY4NDQ4MQ==&mid=2247483758&idx=1&sn=da1cf5d2820f28d1416d0100801cc00d&chksm=fb06e380cc716a9619ebaac610bf8a445ee25070ccc970aa7a94000421a8a16901f6a0932423&mpshare=1&scene=23&srcid=0417TWs5PtlpylU01xFzFhUr#rd](url)

**Comment by zsluedem** [comment]
I have asked @jiyuxuan1944 and this work has been finished. I'm going to close it.
