### ISSUE TITLE
Copy InvoiceTemplate to Personal Gsheet

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#563]
Goal: RAM can create an invoice by changing the month of payment
Action: get invoice data from [Bounty App](https://rewards.rchain.coop/) to Personal Gsheet.
Budget: $1000
Deadline: 4/1/2018
Restriction: trustable person because of access to private data

Repeated action for 75 collaborators with [RAMmain registration](https://docs.google.com/spreadsheets/d/1rV6Qga-JJpcx-O2I352kHNabIZAXFa46zAl8rHXqYxE/edit#gid=363550433&range=B1:B680)
- [ ] copy mail address from TAB [Form Responses 2](https://docs.google.com/spreadsheets/d/1rV6Qga-JJpcx-O2I352kHNabIZAXFa46zAl8rHXqYxE/edit#gid=363550433&range=B1:B680) to cell [c7](https://docs.google.com/spreadsheets/d/1rV6Qga-JJpcx-O2I352kHNabIZAXFa46zAl8rHXqYxE/edit#gid=133909296&range=C7)
- [ ] duplicate TAB "Temp", rename "Copy of Temp" to "T"
- [ ] in TAB "T" copy rows [2 to 18](https://docs.google.com/spreadsheets/d/1rV6Qga-JJpcx-O2I352kHNabIZAXFa46zAl8rHXqYxE/edit#gid=239080108&range=2:18) and paste as values 
- [ ] copy cel c15 [TempInvoice](https://docs.google.com/spreadsheets/d/1rV6Qga-JJpcx-O2I352kHNabIZAXFa46zAl8rHXqYxE/edit#gid=133909296&range=C15:G15)
- [ ] TAB "Copy to" and paste it in "Or paste a web address here"
- [ ] Press OK and go to next email address
- [ ] Can this be programmed in a Macro, Script ??

**Comment by dckc** [comment]
Is there any reason for Operations to do all this make-work for the RAMs at all? Why not just say to RAMs: "grab the [template][1] and make a copy; fill in the green parts: name, ETH and postal address; when you fill in your github name, watch your rewards flow in from rewards.rchain.coop automatically; save as PDF and submit it."

[1]: https://docs.google.com/spreadsheets/d/1OvUkkYb-haFow8Xx4ax7fT_UFq2JBejGUhT_6HUJ-z8/edit?ts=5abc1ffc#gid=1491215041

**Comment by lapin7** [comment]
Because these fields have also to be on the invoice:

Pers Folder
TempInvoice
Tax form
SoW

And an already filled out form with name, postal address, ETH-address gives less errors.
Probably you don't know how **bad** people are by filling out forms on their own. Wrong cells, Forgotten cells, Wrong input, etc. That gives me much more work.

So I've chosen to do it like this.

**Comment by lapin7** [comment]
But let's try your suggestion as well.

- [ ] Go to your personal temporary invoice
- [ ] Copy the url link to your personal temporary invoice
- [ ] Go to [Pub Bounties / TAB Temp](https://docs.google.com/spreadsheets/d/1uxuxx8YN17KCIWcH1cUoGuSm2hAnIya2iAc6wxoaq1o/edit#gid=1560696085&range=D1)
- [ ] Click on the TAB Temp and select "_Copy to_" and paste the url in "_Or paste a web address here_"
- [ ] in your own spreadsheet rename the copied sheet from "Copy Temp" to "Temp"
- [ ] **fill out the green parts**
- [ ] enter: your Name, Postal Address, Country, GithubName, Email-address, ETH-address
- [ ] copy from previous invoices the cells below and paste them in:
- url link to personal folder
- url link to temporary invoice
- url link to tax form
- url link to statement of work
- [ ] now you can see your rewards flow in from rewards.rchain.coop automatically
- [ ] download as PDF
- [ ] mail it to ops@rchain.coop for verification

**Comment by dckc** [comment]
I can't figure out why you're doing anything related to the monster **Pub Bounties** at all any more. I guess I don't know why Pers Folder nor TempInvoice belongs on the invoice.

Part of me says: it doesn't bother me if you want to do a bunch of extra work. But it does bother me. It means I get paid slower. (We all do.) But I guess I'll let it go, for now.

**Comment by lapin7** [comment]
You’re right I’m in a kind of tunnel view. We’ve to rethink the payment process. The biggest bottleneck is elsewhere.

**Comment by lapin7** [comment]
The links don’t point to pub bounty anymore BTW

**Comment by makys** [comment]
Hi @lapin7 , I just requested access so I can help with this.

**Comment by jasoncruzzy** [comment]
Hello @lapin7 i would like to be a collaborator on RChain

**Comment by lapin7** [comment]
@dckc please freeze March now. And begin new period April

**Comment by ChloeCoul** [comment]
Je dois faire quelque chose ?

**Comment by dckc** [comment]
> @dckc please freeze March now.

OK; I updated the current pay period.

I haven't finished with the bug where you can still edit votes from pay periods that are not current.

**Comment by dckc** [comment]
oops... that didn't work well... now the budget and reward views are empty... let me roll back until I fix those views.

**Comment by dckc** [comment]
ok... "Current pay period: 2018-04-01" but the reward and budget tabs still show March as well.

  - bdd8a60 issue_budget: don't constrain to current pay period

**Comment by dckc** [comment]
OK, March is really locked:

 - [ca19b85][1] dbr_triggers: only current vote changes allowed

[1]: https://github.com/dckc/rchain-dbr/commit/ca19b855cdf018c6ec854161e698aeaa7fd80e5a

**Comment by michaelizer** [comment]
My lack of experience is bringing me some difficulties when making the invoice (mostly the part of taxes), could somebody take some minutes to guide me through this process? my discord user is michaelizer#2321 and my email is medinamiguel5991@gmail.com. Thank you very much

**Comment by Ojimadu** [comment]
Send me message on discord or Telegram @OjimaduChidindu

**Comment by lapin7** [comment]
@michaelizer 

- I've created template invoice "Temp"  in your spreadsheet https://docs.google.com/spreadsheets/d/1UoiyExSW7V4tAFwvIAsml1hWfz_fXZEiWvwNr3ZN1hw/edit#gid=393433963&range=D1
- a TempPD is meant for updates of the template
https://docs.google.com/spreadsheets/d/1UoiyExSW7V4tAFwvIAsml1hWfz_fXZEiWvwNr3ZN1hw/edit#gid=820941464&range=A1:G17
- and a PD is As Value-copy/paste of your TempPD for personal data https://docs.google.com/spreadsheets/d/1UoiyExSW7V4tAFwvIAsml1hWfz_fXZEiWvwNr3ZN1hw/edit#gid=241191986&range=A1
- the Temp copies data from PD
- each month the invoice is automatically filled out through a connection with our bounty app https://rewards.rchain.coop/
- the current month is frozen and a new month starts at the 7th of the month
- after the 8 of the month you can transmit the invoice through form Declaration https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
- For your invoice of Feb, please send your ETH address, discord name to ops@rchain.coop.
- Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
- Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- fill out a w8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
- w8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
- or w9 https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit
- w9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by lapin7** [comment]
@dckc 
If possible, I would like a query that delivers this result (in a temporary table):
- [ ] Period
- [ ] Worker
- [ ] Issues (all issues that the worker worked on)
- [ ] USD (total of the rewards of issues)
- [ ] RHOC (USD converted to RHOC, default is 1:1)

A table that contains the rhoc_price of the month

pay_period	month	rate
20170801	August	 $ 0.100 
20170901	September	 $ 0.200 
20171001	October	 $ 0.200 
20171101	November	 $ 0.200 
20171201	December	 $ 0.200 
20180101	January	 $ 0.200 
20180201	February	 $ 1.170 
20180301	March	 $ 1.250 
20180401	April	 $ 1.138 
20180501	May	 $ -  .0 
20180601	June	 $ -  .0 
20180701	July	 $ -  .0 
20180801	August	 $ -  .0 
20180901	September	 $ -  .0 
20181001	October	 $ -  .0 
20181101	November	 $ -  .0 
20181201	December	 $ -  .0

**Comment by dckc** [comment]
like this?

 - [invoice_summary tab](https://rewards.rchain.coop/index.php?-table=invoice_summary)
    - [CSV export](https://rewards.rchain.coop/index.php?-table=invoice_summary&-action=export_csv&-cursor=0&-skip=0&-limit=999999&-mode=list)

**Comment by lapin7** [comment]
Exactly :-)
That replaces my tedious spreadsheet for a part.
What's the query?
I know some sql but have to get it up to date again.

**Comment by lapin7** [comment]
@dckc 
Exactly. :-)
You've made my work with spreadsheets a ton lighter.
I have to catch up with sql.
How did the query look like?

**Comment by dckc** [comment]
I haven't checked this in yet, but the code is:

```sql
create or replace view invoice_summary as
  select pay_period, worker, group_concat(issue_num separator ', ') as issues
, sum(reward_usd) USD
, sum(reward_usd) * rate RHOC
from reward r
join pay_period pp on pp.start_date = r.pay_period
where r.reward_usd > 0
group by r.pay_period, r.worker;
```

**Comment by dckc** [comment]
I fixed the computation of `RHOC` to use `usd / rate` rather than `usd * rate` and checked it in:

 - `d731413` invoice_summary - reward by worker, pay period

**Comment by dckc** [comment]
reward was paid in 201804

**Comment by allancto** [comment]
@dckc thanks for your work/ contribution on this. I've had the pleasure of working with your tools and you did an awesome job. -@allancto
