### ISSUE TITLE
upload videos to Chinese website on March

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#565]
upload the videos from Youtube to Chinese video website

The videos below only moves from Youtube.The budget on these videos is 20$ one video.

1. [Rchain Governance Forum Thursday PM Session Final](https://www.bilibili.com/video/av21359263)
2. [Rchain Governance Conference Saturday Session](https://www.bilibili.com/video/av21333994)
3. [Rchain Governance Conference Guitar Circle Performance](https://www.bilibili.com/video/av21334097)
4. [Govenrance Forum Friday PM Session Final](https://www.bilibili.com/video/av21332549)
5. [Rchain Governance Forum Thursday AM Session Final](https://www.bilibili.com/video/av21327634)
6. [Rchain Governance Forum Friday AM Session Final](https://www.bilibili.com/video/av21325561)

The videos below put a little bit subtitle on the videos.Because of the subtitle, the budget on these videos is 40$ per video.
1. [架构和Rholang预览](https://www.bilibili.com/video/av19238263)
2. [Compiler Design, Cryptoeconomics](https://www.bilibili.com/video/av19240878)
3. [Blockchain Business Requirements](https://www.bilibili.com/video/av19238514)
4. [Rholang Smart Contracts Lab](https://www.bilibili.com/video/av19242329)
5. [Rholang Smart Contracts Lab part 2](https://www.bilibili.com/video/av19242399)
6. [Roscala Interpretation for VM](https://www.bilibili.com/video/av19242436)
7. [Release Management](https://www.bilibili.com/video/av19241860)
8. [Codebase Documentation](https://www.bilibili.com/video/av19240564)
9. [Blockchain Use Case - Supply Chain](https://www.bilibili.com/video/av19238647/)

Measure of Completion:  completed already
Suggested Budget: 6 * 20$+9 * 40$=480$

**Comment by tigermumu** [comment]
In my opinion, the budget of the first part issue is more, I think download and upload should not take much time. But the second part of the budget is low, translation and subtitles need more time.
