### ISSUE TITLE
Medium post translation: The RChain Cooperative & Pyrofex Corporation ink Strategic Partnership

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#570]
Translate medium post: The RChain Cooperative & Pyrofex Corporation ink Strategic Partnership to chinese.

Measure of Completion:  
Suggested Budget:

_See CONTRIBUTING.md for details on budget and reward process._

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: ____

**Comment by v56700** [comment]
This article has been translated by others.
Check here http://www.rchain.site/?p=236

**Comment by rjl493456442** [comment]
@v56700 Thanks for your remind
