### ISSUE TITLE
Goal: Summarize  Video into blog post & translate [Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise) to Italian

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#572]
**The file name is**: [[TRANSCRIPT][.srt][English] "Exclusive Chat Jake Brukhman & Kenny Rowe (Crypto Talk on Rise)](https://docs.google.com/document/d/1-SsnE2rHlULBK5CR41re0OW_pxf4ubpwySTfqiuKjZM/edit?usp=sharing)"

## Collaborators
- @Staff91 (Translator): 10%
- @akhs13 (Reviewer): 0%
- @Chris-Arv (Reviewer): 0%

## Deadline: 2 Weeks

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: 
       - [x] a track record of quality work on rchain bounties: #488 
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Staff91** [comment]
Ok, I will do this.

**Comment by Jake-Gillberg** [comment]
@Staff91, No need to close this issue, just turn it into the "Summarize Video" portion of the work
