### ISSUE TITLE
Creation of Italian website and social media

### ISSUE THREAD

**Issue by Staff91** [rchain/bounties#573]
# All  100%

## Collaborators
- @Staff91 (Developer): 75%
- @ICA3DaR5 (Developer for check) 5%
- @akhs13 (Beta tester): 10%
- @Chris-Arv (Social media management): 10%

## Creation: 100% complete

- [x] [Folder](https://drive.google.com/open?id=1v4KCd-br_Kiwa4W-ZKdT-IMMf7cQL_OO)

## Website requirements

- [x] [Buy Domain](https://drive.google.com/open?id=1gzgQnx2XMX6_aRjOmTxlhPoGexVCfhF0) rchaincoop.it for a year

- [x] [Secure Hosting](https://drive.google.com/open?id=1ys9sKutQOg78dJBoQVwkJduWuXt6SkfF) for a year

- [x] [Theme Avada](https://drive.google.com/open?id=18WNM8eW167nLLhFsxTw7qahrM10gyojN)

- [x] [Yoast SEO](https://drive.google.com/open?id=1HVPSXxgMkQayTW2hnWwceXQu9dOE2PTa)

## Website

- [x] [rchaincoop.it](https://rchaincoop.it/)

- [x] [forum](https://rchaincoop.it/forum/)

- [x] [Blog](https://rchaincoop.it/category/rchain-blog/)

## Social Media 

- [x] [facebook page](https://www.facebook.com/rchaincoop.it/) 

- [x] [twitter account](https://twitter.com/rchain_it) 

- [x] [Telegram channel](https://t.me/rchaincoop_it)

- [x] [Medium](https://medium.com/@rchain_it)

- [x] [Youtube channel](https://www.youtube.com/channel/UCLW_uxNsXBsJE0BBlXLAX3w)

## Statistics from 2018/04/19

- [x] [Website](https://drive.google.com/open?id=1iqzEedL23o2wufOaiKOj9FtAHqDWHo-Q)

- [x] [Facebook](https://drive.google.com/open?id=1I9o2W_Cue2oLKsOLtXaVN2p-7jMR9t6V)

- [x] [Twitter](https://drive.google.com/open?id=1sJkgPwKZOoSJGIZ90zHqHXLzX9L_crrN)

- [x] [Telegram](https://drive.google.com/open?id=1x0QRkEbzNpBgdNC7IIHqOyISi_ixDF8O)

- [x] [Youtube channel](https://drive.google.com/open?id=1IQVpnfHU107diFXYmuEB6YLRp3nOGJKp)

- [x] [Medium](https://drive.google.com/open?id=19fXVtubo3gDrKpCqKBnE2jYEpZvd1jHy)

- [x] [Forum](https://drive.google.com/open?id=1KkaCB2X-yrUGupXMyAwhv-psI0pH8x37)

## Promotion 2018/04/19

- [x] post at [Bitcointalk](https://bitcointalk.org/index.php?topic=3322707.0)

## Statistics on  2018/4/27

- [x] [Website](https://drive.google.com/open?id=1QBUYl_k3jBbD1C7WtWCJ69qEHi4Jd2_V)

- [x] [Twitter](https://drive.google.com/open?id=1wjkguX8gDQzDW4xKdQ95Wp7iPidZknUK)

- [x] [Telegram](https://drive.google.com/open?id=1gUaaWnzmhrMVDj98J-NaJ9f263A5vTVB)

- [x] [Youtube channel](https://drive.google.com/open?id=1PHpeL_u0y6K5lueCCIlGO2IV0WzUJS36)

- [x] [Medium](https://drive.google.com/open?id=1nP8YLmebTK4A9e10_9A0MDTGztUtCmeK)

- [x] [Facebook page](https://drive.google.com/open?id=191ydA0XbIuw8PMvvMN1HRnO-1aDfWRmB)

- [x] [Forum](https://drive.google.com/open?id=1KkaCB2X-yrUGupXMyAwhv-psI0pH8x37)

## maintenance:

 From the 1st of May:

-All RChain posts on Twitter and facebook will be translated and reposted on the corresponding italian social media. Additionally, they will be posted on the italian website, under the category [RChain news](https://rchaincoop.it/category/rchain-news/).

-All key RChain videos will get italian captions and will be reuploaded on the italian [RChain youtube channel](https://www.youtube.com/channel/UCLW_uxNsXBsJE0BBlXLAX3w)
, Facebook, Twitter as well as the [RChain Video](https://rchaincoop.it/category/rchain-video/) category of the website. 

-All new RChain blog posts will be traslated and posted on Medium, Twitter, Facebook and the [Blog](https://rchaincoop.it/category/rchain-blog/) category of the italian website.

-Promotion of the italian website on italian technology-oriented forums with the goal of increasing the visitor count of the website, and the introduction of the visitors to the italian RChain documentation, so as to bring in new members and developers from Italy to the RChain Coop.

-Management of the italian [Forum](https://rchaincoop.it/forum/) and [Telegram](https://t.me/rchaincoop_it) channel in order to promote discussion and help potential new members and developers with their questions.

**Comment by Jake-Gillberg** [comment]
A bit confused as to why the previous issue was closed and this one opened. see #569 for previous discussions and questions.

**Comment by lapin7** [comment]
Where's the link to the website?

**Comment by Staff91** [comment]
@lapin7 rchaincoop.it

**Comment by kitblake** [comment]
Hi @Staff91, nice work on the site! My Italian is limited to reading and feeling thrilled when I understand something, so I can't say anything about the content. 

The bad news is the logo you're using is not an official RChain logo. Best would be to replace it with a logo from here:
https://github.com/rchain/style_guide_and_files/tree/master/web such as:
https://github.com/rchain/style_guide_and_files/blob/master/web/Rchain_brand_scarlet.png

I realize this creates quite some work for you because you've integrated text into logo images. But the 'Member project' logo you're using will never be official. It was an exploratory exercise. 

Fyi, new branding is being developed now, expected in June, so you could also wait. But in that case we shouldn't promote your nice new site, and that would be a shame. Your call..

ps: Btw, I'm not a decision maker on this, I'm just stating the situation.

**Comment by Staff91** [comment]
@kitblake Hello. Thank you for your kind words and information. I will implement the logos that you recommended right now, since they are the official ones. I am open to any other suggestions. Thanks again!

**Comment by Staff91** [comment]
@pmoorman Hello, the scope of this issue was the creation of the italian social media platforms and website, and the subsequent maintenance of those. The creation part is complete. Please take a look at the upcoming maintenance goals, and feel free to offer any suggestion or criticism. Thank you.

**Comment by Staff91** [comment]
The creation part is complete. Closing issue and moving on to the next stage #645 .
Thank you very much @lapin7 .
