### ISSUE TITLE
Set up a web app for translations [EARLY DRAFT]

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#579]
# Issue

Create a web app for translations. The goal of setting this up is two-fold:
1. Help the translators discover which files and documents are translatable.
2. Help create better translations, since the web app is going to support a vocabulary.

## Weblate
- [Weblate](https://en.wikipedia.org/wiki/Weblate) - [Self hosted](https://weblate.org/en/hosting/)
- [Video Demo](https://youtu.be/679FoXu9BP8?t=14m32s)
- [Demo](https://demo.weblate.org/)

Used by [OpenSuse](https://l10n.opensuse.org/) and [elementary](https://l10n.elementary.io/), two multi-lingual projects (https://medium.com/elementaryos/adios-transifex-weve-gone-to-weblate-59870dea06b2)

--

## Collaborators

- @ICA3DaR5: 0%
- @thiefinshadows: 0%
- @zero-andreou: 0%

## Other Information

- **Completed:** 0%
- **Suggested Budget:** $?

**Comment by dckc** [comment]
How do the results of a translation get to their destination? How would a translation of the rholang tutorial get into the rchain/rchain repo, for example?

**Comment by Jake-Gillberg** [comment]
It seems like there are a bunch of pre-built solutions for this kind of thing. @kitblake was going to give an example of one yesterday.

**Comment by dckc** [comment]
I don't think he's actually proposing to develop an app. He showed me some existing apps a few weeks ago.

**Comment by kitblake** [comment]
On first glance I notice: 
- the languages (with the exception of Japanese) are all European. Chinese isn't there, nor Korean, Indonesian, etc.
- We certainly don't need Romansh :)

Somebody suggested a Loomio poll to decide on which languages the Co-op wants to initially target. Seems like a good idea. Shall I set it up?

**Comment by dckc** [comment]
Wait... Chinese is not in your list of languages? Please check with @llerner .

Also... don't most western Europeans (German, French, Spanish, Portugese) read English pretty well?

**Comment by dckc** [comment]
I wouldn't put much credence in the results of a Loomio poll, @kitblake. I don't think we have a critical mass of people with informed opinions who would participate. I'm not sure what alternative to suggest, though, so I suppose it's better than nothing.

**Comment by ICA3DaR5** [comment]
I will set the app first. The decision for the languages can be made until the app is ready. First goal is to decide on the app and start implementing it.

**Comment by kitblake** [comment]
This is the page/interface that I intended to show in the RAM meeting but the demo gods had other ideas: 
![bountyhive_trans](https://user-images.githubusercontent.com/912545/38378237-517abab8-38fd-11e8-8326-0fc637b653cd.png)
The "Rules & Guidelines" don't necessarily apply to our situation, but the important point is they have them and they're clearly articulated. We might consider doing something similar in a wiki page (in addition to the new issue template).

ps: I'm not suggesting we use bountyhive.io, just highlighting their guidelines as an example.

**Comment by Staff91** [comment]
@ICA3DaR5 trololo oloi

**Comment by David405** [comment]
@ICA3DaR5 I would like to get something straight, the proposed App will it do the translation itself or it will help with the organization of translation documents

**Comment by kitblake** [comment]
In order to work out guidelines for translations we need to decide what languages the Co-op should communicate in. Here's a poll where you can rank the languages that you feel are important. Would everybody please fill it out? 

You can share it too, anyone with link can participate:
https://www.loomio.org/p/yJBqS539/what-languages-should-the-co-op-communicate-in-

Thanks.

**Comment by ICA3DaR5** [comment]
@kitblake Great!

**Comment by namo927** [comment]
Since the co-op has already been set up in English, i would want to suggest it remains the same. However we have have a language change option on the home page to help non English speakers.

**Comment by dckc** [comment]
In the retrospective report (#678), the translation guides wrote:
> Perhaps a dedicated translation web app will help.

**Comment by AyAyRon-P** [comment]
@ICA3DaR5 what is the status of this translation issue? Based on what I'm reading this is no longer a valid issue and we can close this. 

cc @pavlos1851

**Comment by pavlos1851** [comment]
After contacting @ICA3DaR5, I'm closing this issue since there are no plans for the continuation of this issue and no payment has been received.
