### ISSUE TITLE
Re-create and modernize the Rchain Corporate video for the website 

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#589]
# All

https://www.rchain.coop/#home

_Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely._

Measure of Completion:  
Suggested Budget: 1500$

**Comment by Cryptovideos** [comment]
Right guys  - we can close this off, just checking if any of you see any value in this ? personally i believe the existing video to be outdated from a visual graphics point of view and i can make it look a lot more appealling....please feel free to suggest closing this...or lets move ahead and get some votes?

**Comment by lapin7** [comment]
@Cryptovideos I agree with you that the existing video is outdated and I'm looking forward to a more appealing video. :-)

**Comment by Ojimadu** [comment]
By the existing video, you mean the RChain vision video?

**Comment by lapin7** [comment]
@Ojimadu yes this one
https://youtu.be/Qftq9S34xgg

**Comment by Cryptovideos** [comment]
The Problem is that the animation looks flat, no vibrant color or action -definitely need an overhaul - would appreciate vote supports etc etc

**Comment by makys** [comment]
I like this idea. I am looking forward to an upgrade on this. I had to watch the existing video again. If we can do something really catchy, I'd love it. This will help branding and marketing.

**Comment by Cryptovideos** [comment]
Animation Planning/storeyboarding process has begun - will keep you all posted!

**Comment by Cryptovideos** [comment]
Hi Team Rchain! 

Herewith the Revamped and updated Red Hot Rchain Overview Video!!!!

Lets make 2018 our year people!!!

https://youtu.be/y7GTgdmkubc

**Comment by pmoorman** [comment]
so... where are we going to put this video, and who will approve of it?

@ian-bloom has said that updates to the website should only be rolled out in agreement with the (basically to-be-composed) marketing team. @patrick727 might be able to help, but he's also super busy.

It's little use having all kind of videos that nobody ever sees, so I would encourage everyone to think about the approval/release process before diving in creating the assets.

**Comment by Cryptovideos** [comment]
Thanks for the feedback @Pmoorman

If i may suggest…. the current video is outdated, of poor quality and is a sub standard reflection of us...

However….here are some answers to you questions...


so... where are we going to put this video

It will need to replace wherever the OLD video is loaded…. over and above this i highly suggest we upload it to our front page in the website where all our current and future visits can see who we are and what we are about? Please feel free to advise us in a better light?

, and who will approve of it?

Well… the Voters should?

Trust all can agree that… that this …. https://youtu.be/y7GTgdmkubc…...

Is a MASSIVE improvement and upgraded / reflection of our Coop than this??? : https://www.youtube.com/watch?v=Qftq9S34xgg

Kind regards



@ian-bloom<https://github.com/ian-bloom> has said that updates to the website should only be rolled out in agreement with the (basically to-be-composed) marketing team. @patrick727<https://github.com/patrick727> might be able to help, but he's also super busy.

It's little use having all kind of videos that nobody ever sees, so I would encourage everyone to think about the approval/release process before diving in creating the assets.

**Comment by pmoorman** [comment]
@Cryptovideos I applaud the idea to create improved video content, but I'm worried about the approval process.

You said: 

> ...and who will approve of it? => Well… the Voters should?

In practice, "the voters" would mean all "all verified members of the coop", but they are over 1,000 strong, and simply can't vote on every issue of this size.  Members only vote on major things like who gets elected to the board. In that sense it's similar to a typical democracy, I guess. 

I would advise to reach out to @ian-bloom or @patrick727 to figure out how to get it to replace the old video (e.g. on the homepage, and other places)

**Comment by Cryptovideos** [comment]
Thank you so much

Excellent feedback

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AyAyRon-P** [comment]
@Cryptovideos 

Please update your initial post following the NEW ISSUE template:
https://github.com/rchain/bounties/issues/new

Are there any updates to this project? Do we need to add anything or can we close this out and archive the links in the issue?

**Comment by pmoorman** [comment]
@Ojimadu @lapin7 @Cryptovideos in agreement with Patrick I've updated the video on the homepage to be this sexy-as-fuck strategic overview of RChain that just got published the other day.

I personally really like how it looks, and I know from at least a couple other people that they think the same way! I think that actually completes this project 👍 

$1500 is a bit steep for this version of the execution. In fact, it took me about 15 minutes, and I don't think a reward is warranted for something small like that.
