### ISSUE TITLE
Organize RChain speakers and representatives for upcoming Blockchain events

### ISSUE THREAD

**Issue by David405** [rchain/bounties#593]
This is a sub-issue of #583. It will be nice if proper information is passed across to coop members how RChain intends to be represented in these events. I would really appreciate if members of board, admins, comment on this issue @lapin7? @ian-bloom? and others concerned

**Comment by Valentine-Mario** [comment]
This is a very valid point raised here. To grow in the market, RChain needs to be represented in many of these events. 
And also RChain needs to host events targeted at cryptocurrency enthusiasts.

**Comment by jasoncruzzy** [comment]
Truly Rchain needs to be represented in many of these events.  Valid point raised here

**Comment by Preshcode** [comment]
I think the Executives and all members of the co-op should take this issue seriously because our vision will not turn into reality if Rchain is not properly represented at all blockchain events worldwide. The events will not only make Rchain stand out as the fastest and most scalable blockchain technology but will also boost the rate of Rhoc purchase.

**Comment by pmoorman** [comment]
@David405 can we make this issue a bit more SMART? Most importantly: what are we actually trying to achieve with this issue? When is it completed?

you could update the description to reflect this

**Comment by David405** [comment]
@pmoorman what we hope to achieve on this issue is to organize persons(volunteers or sent by the Coop) who will represent RChain at very strategic and important events around the globe. It is doesnt have a deadline as these events have different dates.

**Comment by Ojimadu** [comment]
How do you intend to do that?

**Comment by Murphy6** [comment]
That is a wonderful idea to help motivate and reach out to those that don't understand or believe in this great community.

**Comment by nonnykul** [comment]
@David405, @pmoorman,@ojimadu. I suggest using the 'Discord channel meet up' to organize RChain speakers and representives for Blockchain events

**Comment by Ojimadu** [comment]
Am closing off this issue. Feel free to reopen if you're willing to work on it.
