### ISSUE TITLE
Introduce RChain to Russian community

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#596]
### Benefit to RChain

Creating a telegram group for Russian community, vk.com [group](https://vk.com/rchain_ru), post about RChain at russian medium blog [RChain_RU](https://medium.com/@rchain_ru)

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[1000]**
_Estimated Timeline Required to Complete the Task:_ **[Done]**
_How will we measure completion?_ **[With links merged here]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by qelentium** [comment]
It is just the first ideas of what and how is going to happen. Feel free to suggest and participate

**Comment by Barkov-F** [comment]
Let's translate the rspace
<https://github.com/rchain/rchain/blob/master/rspace/docs/Tutorial.md#using-multiple-channels>
tutorial and go from there. If we post on habrahabr.ru and other
russian-speaking developers forums, we can generate some feedback for #594

**Comment by qelentium** [comment]
@Barkov-F when you will have time please answer at Discord

**Comment by qelentium** [comment]
We created page at vk.com, posted about RSpace at (habrhabr)[https://github.com/rchain/bounties/issues/608]

**Comment by pmoorman** [comment]
@Ojimadu @Mervyn853 as organisers of the social channels, I think you should be aware of this issue!

For @qelentium: can we make this issue more SMART?  I see that a Russian Telegram group has been created, but I can't find it searching for "RChain russia".

Here's to phrasing issues in a way that it's clear what our budgets are exactly being spent on!

_(btw, other than that great work here ;-)_

**Comment by azazime** [comment]
I suggest we work more on social media in other to achieve this.

Firstly we have to understand how things like this operate in Russia then we can do a targeted AD which has to be very intensional

**Comment by qelentium** [comment]
@pmoorman We are posting in vk.com posts about RChain, about architecture, and the history of RChain.We are translating them and posting them direct there.

**Comment by AyAyRon-P** [comment]
Please update your initial post following the NEW ISSUE template:
https://github.com/rchain/bounties/issues/new

Can we close this out and archive the links in the issue?
