### ISSUE TITLE
Nairaland Engagement

### ISSUE THREAD

**Issue by Preshcode** [rchain/bounties#601]
Nairaland is an online community targeted at Nigerians. Nairaland currently has over 1,943,105 registered accounts (January 2018), and is ranked as the 10th most visited site in Nigeria (and the most visited indigenous site) according to Alexa.com. Nairaland reportedly has over 55 million Internet users, corresponding to 32.9% of the entire population. With Nairaland having a considerable but unconfirmed number of users based in diaspora. This makes Nairaland a useful blog in getting the people of Nigeria acquainted with Rchain platform. Please visit the <a href="http://www.nairaland.com/4452510/rchain community/">link<a/> and join in the discussion.

**Comment by jasoncruzzy** [comment]
@Preshcode i studied the issue via the link, its elaborate and comprehensive. Promoting #Rchain on nairaland is a very good platform for developing our community

**Comment by Pionelle** [comment]
@Preshcode and @Valentine-Mario I will join this process by using my Nairaland anonymously. And contributing to the link on www.nairaland.com
Nairaland has made social discourse amongst the Nigerian population very seamless. Even please note that a great number of people from other countries use Nairaland for commerce and social activity.

**Comment by Pionelle** [comment]
Excitedly, I was able to add to the previous information in the thread on Nairaland. The thread has about47 views about the time I was present . 

![screenshot-www nairaland com-2018 04 15-00-44-15](https://user-images.githubusercontent.com/36760393/38773512-2c14bc24-4046-11e8-8638-6fdccac2cb9b.png)

**Comment by Valentine-Mario** [comment]
The thread on nairaland hopes to be like a series explaining RChain extensively.

**Comment by Valentine-Mario** [comment]
This issue is in response to #591 about penetrating the African market and strategically on boarding African users.

**Comment by Pionelle** [comment]
@Valentine-Mario  does this require us to constantly check in and make contributions from time to time?

**Comment by Kencode7** [comment]
Wow! Nairaland is an exciting platform to bring the Rchain community closer to Africa.
they have a lot of enthusiastic programmers that would appreciate the architecture that makes the Rchain design scalable.

Would like to be part of these process @Preshcode @Valentine-Mario @benmorrow @jasoncruzzy 
we can find a good number of seasoned programmers on the webmaster section too. since we already at on the programming section.

**Comment by Valentine-Mario** [comment]
@Pionelle that's the idea. To continually grow the thread and attract more readers and developers from Africa

**Comment by Pionelle** [comment]
@Valentine-Mario  Please consider this done. We should all keep the discussion going forward. Well done for inventing this wonderful idea.

**Comment by Kencode7** [comment]
Applying the SMART-objective on this issue;

1. On [nairaland.com](url) targeted ads about The Rchain platform can be placed on sections where developers/programmers often visits like the webmaster section or the programming section

2. When these posts are made (Interesting posts that will attract tech enthusiasts/ programmers), relevant page moderators can be mentioned. this enables the post to get to the front general page.

3. From there on, We can continually grow the thread.

**Comment by azazime** [comment]
Nice move,,,
