### ISSUE TITLE
2nd Video installment: Rnode 0.2.1 release and much more!!

### ISSUE THREAD

**Issue by lover33** [rchain/bounties#602]
# All

DESCRP: Here is the 2nd video I have released to my online audience, covering a brief overview of the Rchain project and its recent updates. I will continue to produce quality videos moving forward as I am more comfortable with my trust and relation to this platform. I feel it is my duty to learn as much as I can about any new company in the crypto space that I resonate with, then share with the world. I seek mass adoption, so my goals are simple; learn and share everything in a simple manner to gain the trust of the masses.

Measure of Completion:  Posted within a reasonable time of NEWS...etc
Suggested Budget: $275 - 100% for video

_See CONTRIBUTING.md for details on budget and reward process._

**Comment by lover33** [comment]
My 2nd public review: I will post my reviews and updates for Rchain!

https://youtu.be/vxJLwvFizw0

I will also be a point person on social media for milestone releases and updates whenever Rchain announces!

**Comment by pmoorman** [comment]
I'm going through the issue list to keep things organised.  In this case, I would suggest we remove the "events" and "branding" label, since this work doesn't fall into these categories.

Cheers,

**Comment by pmoorman** [comment]
Btw, would you mind sharing the stats from the 1st video? So people can see the reach you've been able to generate? 

@lapin7 is starting an effort to be a bit more data-driven in our decisionmaking, and I think this is a good idea. Maybe you could always publish the stats after 2 weeks, or after a month, or whatever.

**Comment by lover33** [comment]
Ok sounds like a plan. I will post the stats on each issue

**Comment by lover33** [comment]
![screen shot 2018-04-30 at 9 25 28 am](https://user-images.githubusercontent.com/32472864/39438568-6907dade-4c59-11e8-9c56-994968cef35a.png)
![screen shot 2018-04-30 at 9 25 35 am](https://user-images.githubusercontent.com/32472864/39438569-69255802-4c59-11e8-81a2-fb69e8743e66.png)

**Comment by lover33** [comment]
![screen shot 2018-04-30 at 9 26 24 am](https://user-images.githubusercontent.com/32472864/39438584-72d1b35a-4c59-11e8-8380-f6302b2a2929.png)
![screen shot 2018-04-30 at 9 26 33 am](https://user-images.githubusercontent.com/32472864/39438585-72ec232a-4c59-11e8-909d-8cf8fb627395.png)

**Comment by lover33** [comment]
Here are the stats. Looks like numbers will increase each month. 
I can act as a monthly media update source for announcement to do with Rchain.
Let's make this position more focused than what I currently do!
