### ISSUE TITLE
Comprehensive Summary Post for Developer Conference Sessions

### ISSUE THREAD

**Issue by PatrickM727** [rchain/bounties#604]
Let's create something similar to Ojimadu's summary post of a debrief here
https://docs.google.com/document/d/1Ftu4Uw0gCJ4g63fdpmApDrv2YMWO5vR5w52mwoE-hcE/edit#heading=h.rduez1xidvbd

for the RChain developer conference videos

[Day 1 Session 1](https://www.youtube.com/watch?v=P8-P6YgFnas)
[Day 1 Session 2](https://www.youtube.com/watch?v=O9IA1G1IV9Y)
[Day 1 Session 3](https://www.youtube.com/watch?v=KVkZv-itwFk)

[Day 2 Session 1](https://www.youtube.com/watch?v=lUs1k8iY8XA)
Cont...

Thank you!

**Comment by PatrickM727** [comment]
btw locked out of my old account @patrick727 

i can verify identity with whomever

**Comment by David405** [comment]
Hi @PatrickM727, can we talk more about this, I would like to see how far you have gone or have you started at all?

**Comment by David405** [comment]
Hi @PatrickM727, can we talk more about this, I would like to see how far you have gone or have you started at all?

**Comment by Pionelle** [comment]
Can this document then be distributed to a specific mailing list. I understand that not all were live during the events.
This is a perfect way to educate the public.

**Comment by jasoncruzzy** [comment]
@PatrickM727 dis seem nice buh i'm yet to understand the function of this. Please throw more light on this.....Thanks

**Comment by PatrickM727** [comment]
@jasoncruzzy The function is simple. Take all of the presentations from the dev conference and create blog posts out of them. 

It's repurposing content. 

@David405 I have not started at all as my intentions was for community members to pick up on it. 

specifically I wish that @Ojimadu would because he did a great job with the debrief summary post that i used as an example. but anyone can try. 

@Pionelle this will not be 1 document but a series of blog posts.

**Comment by dckc** [comment]
> btw locked out of my old account @patrick727

Please contact github support and get that fixed, @PatrickM727 . Otherwise you're going to lose a bunch of reputation. The bounty app is likely to get confused... but maybe it'll be smart enough if you have both github accounts connected to the same discord id.

**Comment by Ojimadu** [comment]
Anyone willing to take on this?

**Comment by Ojimadu** [comment]
Closing this out for now. If any one6is willing to take on it then feel free to reopen.
