### ISSUE TITLE
Manage Telegram growth and focus for April 2018

### ISSUE THREAD

**Issue by kitblake** [rchain/bounties#606]
*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*

The organic growth of the Telegram groups continues. The main group should hit 2000 members in April. The groups seem to have stabilized in terms of spammer/scammer activity. Admins are keeping the conversation focused on the tech as opposed to the market.

These are the current groups:
https://t.me/rchain_coop
https://t.me/rchain_official (announcement channel)
https://t.me/rchain_africa (see #592)
https://t.me/rchain_cn
https://t.me/rchain_fr
https://t.me/rchain_nl
https://t.me/rchain_ru (new, see #596)

This is the April activity for the main group:
https://combot.org/chat/-1001123521235?start=01%2F04%2F2018&end=30%2F04%2F2018

*Estimated Budget of Task:* $2400
*Estimated Timeline Required to Complete the Task:* the month of April
*Measure of Completion:* See Combot statistics for the larger groups.

The suggested budget is less this month, following a recommendation during the issue review: when there is extra infrastructural work such as adding/upgrading bots, creating new groups, training new admins, etc. then Admins should report the activity in this issue and add budget.

--
***Legal***
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by kitblake** [comment]
For the record, here's an example of astute 'adminning': 

RC, [01.04.18 19:49]
What is the plan for RChain to convince developers and corporates to build their systems on Rchain?

Ojimadu, [01.04.18 20:01]
[In reply to RC]
There are organizations (Reflective ventures and Pithia)  working to bring companies on board and add value to the RChain ecosystem. Reflective ventures in the last community updates has about 6 companies to be funded in about two week time. 12+ companies under due diligence. Working on some deal signing in San Francisco.
Pithia too has signed up LifeID.
The cooperative is working to build out Crypto/Hacker space and incubator for start ups. All these plus more are aimed towards adding value and building out a rich RChain ecosystem.

RC, [01.04.18 20:16]
[In reply to Ojimadu]
Well, that was a much better elaborated answer than expected 😄

**Comment by David405** [comment]
@kitblake, very nice stats you have there but the combot stats seems to be only available for the main group

**Comment by kitblake** [comment]
@David405 Some of the country groups have Combots too but there's not a lot of activity to note.

**Comment by David405** [comment]
I believe the target of 2000 members on the telegram group has been met!

**Comment by lapin7** [comment]
Let's convert those members to RAM's :-)

**Comment by BelovedAquila** [comment]
Coming as a suggestion, I think in managing the growth of the telegram groups, it's needful to see that groups are not just springing out and decentralized country wise but continentally, to prevent excesses and mismanagement. I believe that way the coops group tends to be in more union and qualitative effect than several ineffective disintegration.

**Comment by azazime** [comment]
If the telegram groups are properly and well managed in the aspect of PR, it tends to increase the number of RAMs. This could be achieved via strategic publicity and comprehensive explanations in our telegram groups

**Comment by kitblake** [comment]
RChain Africa: http://combot.org/chat/-1001196019499

The other groups are small and don't merit a combot.
