### ISSUE TITLE
RChain On Quora: A Definitive Blog 

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#607]
RChain has attained a significant level of visibility on Quora. I honestly would give all the commendation to the numerous interested Quorans, who have found an avenue for demanding information pertaining to the workings around RChain.
 Engagement, as constant as could be, remains one involving - **an individual** representing an entity (As **RChain**). And so to limit the very significant absence of an Official page on Quora, It has become necessary to create an information hub, one that could aid the reach out to Quorans become more organized. 
About 1,560 **Quorans** have read answers  the Blockchain/Startups/RChain is mentioned, in this past week.
**SMART OBJECTIVE**
Reach out to a dedicated community of Blockchain interested individuals.
**Budget: This is in progress.**
**Process: Constantly update Page with content.**
Utilize model question/answers to determine major area of interest for participants. Collate and emulate other known brands actively engaging consumers/public on Quora.

**Comment by ResonanceXX** [comment]
https://rchainupdate.quora.com/

This seems like a domain name which would fit. Uploaded the very first content, as a welcome to message.
Please visit and drop your comments. Cheers.

**Comment by ResonanceXX** [comment]
The one important aspect of Quora, which writers find helpful, is the community based approach to both article writing and information gathering.
The opportunity to respond almost informally to very important issues is key for Quorans.
Also many users think Medium is biased towards long article writers. But I have grown to admire the fonts, UX and ease on the eyes.

**Comment by ResonanceXX** [comment]
This article wears a different look when moved to Quora.

https://rchainupdate.quora.com/PITHIA-AND-RCHAIN-TRANSMITTING-BLOCKCHAIN-ORACLES

Looking to possibly calm the yearnings for information around Quora.

**Comment by Valentine-Mario** [comment]
This is a nice initiative @ResonanceXX.

**Comment by ResonanceXX** [comment]
I ran into the little problem of having my quora profile being updated due to traffic. A not so nice moderator requested that I hence forth use a better/longer name. And so ResonanceXX will operate under the banners of Chris Ken. Only for now. haha.

**Comment by ResonanceXX** [comment]
The hitch is slightly solved. 

I am currently scouring through previous articles on Medium. That are needed on Quora.

**Comment by ResonanceXX** [comment]
@Valentine-Mario good to see activity around the post. Cheers.

**Comment by ResonanceXX** [comment]
@Jake-Gillberg has the wonderful article content.

https://medium.com/rchain-cooperative/rchain-developer-retreat-roundup-day-1-759091f53795
This is a valuable document. Working towards requesting @Jake-Gillberg's permission to use this on Quora. Cheers.

**Comment by pmoorman** [comment]
Hey guys, can we split this issue into something with a clearer SMART deliverable?

Right now -- the way the issue is worded -- it's impossible to tell whether anything is created/completed, and where the money is spent on.

**Comment by ResonanceXX** [comment]
http://qr.ae/TUTtFz

**Comment by ResonanceXX** [comment]
http://qr.ae/TUTtHP

**Comment by ResonanceXX** [comment]
http://qr.ae/TUTrXg

**Comment by ResonanceXX** [comment]
In reacting to a smart objective

**Specificity** - Targeted to a community of Quorans who would frequent the Blockchain/cryptocurrency segment. 
**Measurability** - Putting up an article periodically, and some of them would be drawn from Medium.
**Achievability** - Currently has a cummulative 100+ views on about 4 separate articles. Especially since with minimal link sharing/marketing.
**Relevance** - Information is key. Quora and Medium are considered contrasting services in the article publishing space. Both have their differences and the features that stand them out.
**Time Limitability** - Looking at having this around, for as long as the readership continues to avail themselves.

Note - It is my personal belief that since these articles even with minimal exposure have been read by some curious Quorans. Then the premise is this, that the urgency for more information is real. And that it is unforgiving to have a space like Quora, and fail to reach out to the niche.

**Comment by Pionelle** [comment]
Well said! 

    On Monday, May 7, 2018 4:28 PM, Chris Ken <notifications@github.com> wrote:
 

 In reacting to a smart objectiveSpecificity - Targeted to a community of Quorans who would frequent the Blockchain/cryptocurrency segment.
Measurability - Putting up an article periodically, and some of them would be drawn from Medium.
Achievability - Currently has a cummulative 100+ views on about 4 separate articles. Especially since with minimal link sharing/marketing.
Relevance - Information is key. Quora and Medium are considered contrasting services in the article publishing space. Both have their differences and the features that stand them out.
Time Limitability - Looking at having this around, for as long as the readership continues to avail themselves.Note - It is my personal belief that since these articles even with minimal exposure have been read by some curious Quorans. Then the premise is this, that the urgency for more information is real. And that it is unforgiving to have a space like Quora, and fail to reach out to the niche.—

**Comment by ResonanceXX** [comment]
https://rchainupdate.quora.com/PITHIA-AND-RCHAIN-TRANSMITTING-BLOCKCHAIN-ORACLES

Statistically, this has been the most read content on the Blog. So maybe readers can/should go through this for more information.
Looking also to include links to Telegram and/or the discord channel. Since specificity has been included as the predicated parameter for Marketing. (Engagement)

**Comment by pmoorman** [comment]
@ResonanceXX maybe some ideas on how we could improve on this issue, to make it more effective in aligning with what the coop needs:

- I can see we've gotten 42 views on the article. I wonder if we could use Bitly (or similarly tracked) links in the future, so we can see approx. how much traffic the blog is driving.

- If 42 views is the highest performer, I wonder if this approach is **worthwhile relative to the budget** we spend on it. What are your thoughts on this?

- Finally, in the SMART objectives I would say we're still somewhat missing the point. For instance in `measurable` we use the word "periodically" which is impossible to measure. If we'd instead say "monhtly" or "weekly" or whatever, _that_ would be measurable.

**Comment by pmoorman** [comment]
oke, in that case I would suggest that we treat this as an experiment to see what we can do with Quora, and conclude that it's not a channel to pursue for now.

**Based on your response** I'll close off this issue, and I'd suggest we stop our efforts on Quora until we have a better strategy in place that warrants pushing more budget into it.

**Comment by ResonanceXX** [comment]
http://qr.ae/TUTuqH
