### ISSUE TITLE
Rchain Weekly Updates (Debrief 71 & 72), April 4th&11th,2018.

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#613]
Rchain weekly update: 
[Debrief 71](https://docs.google.com/document/d/134mhbMMZ8YpeB0vdqfL7c7ga-QgChhRInUAkpC49GtI/edit#heading=h.iu3radrink15)

- [x] Watch the [video ](https://youtu.be/Gi1pauUw3Ls)of the Debrief 71

- [x] Write a textual run down

- [ ]  Publish on Rchain [medium](https://medium.com/rchain-cooperative)

Suggested Budget: $500

[Debrief 72
](https://docs.google.com/document/d/1cc-Y5t-QihNiqM91_886GKiy-kGmV2GFAYelMz-zK2w/edit#heading=h.gwrym7qo5q2z)

- [x] Watch the [video ](https://youtu.be/Aqojt6f4HhA)of the Debrief 72.
- [x] Write a textual run down

- [ ] Publish on Rchain [Medium](https://medium.com/rchain-cooperative)

Suggested Budget: $500

**Comment by TrenchFloat** [comment]
(See my comment on #618.) My fault for not staying current on all the Github issues, we might save time to split the workload though.
