### ISSUE TITLE
Rchain Weekly Update (Debrief 73) 20180418

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#618]
Rchain Weekly Update 
[Debrief 73](https://drive.google.com/drive/folders/1-qfqIUWSQ7WAwvE2MXduVmPtHjXEF10S)

- [x] Watch [video](https://youtu.be/tH6xoSBLReY) of the Debrief
- [x] Write textual run down
- [ ] Upload to RChain  medium

Suggested Budget: $500

**Comment by lapin7** [comment]
@Viraculous please move "Debrief 73" to this folder:
https://drive.google.com/drive/folders/1-qfqIUWSQ7WAwvE2MXduVmPtHjXEF10S

**Comment by TrenchFloat** [comment]
Oops, looks like we've been doing the same job - I've been writing notes and timestamps for the weekly debriefs and putting them up in [the wiki](https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index) and [this google doc](https://docs.google.com/document/d/1Va_u-I_IWCvpWVgQXNKsFuhpaH-enouhPotJMTGoiRM/edit). I'm not very familiar with Medium though. Would it save you any time to take my notes from the wiki for your uploads to the RChain Medium? I have them written and on the wiki within 24 hours of the debrief each week.

**Comment by Viraculous** [comment]
Great @TrenchFloat, its welcomed. so, what do you think? How do we go about it?

**Comment by TrenchFloat** [comment]
@Viraculous The easiest path I think would be for me to keep doing the timestamps for the debriefs like I have been, then you take them from the wiki and include them in your Medium posts/write about each section. I post in the discord lobby as soon as I have them done each week.

On the other hand, if you have any other ideas for working together, I could help out more with your end. Anything you don't like doing?
