### ISSUE TITLE
Code Segments in Rholang tutorial should copy without line numbers

### ISSUE THREAD

**Issue by rolandkofler** [rchain/bounties#620]
*Currently line numbers are hard coded into the code segments of the tutorial, apply CSS to automate line numbering and to exclude them automatically when copying code for trials* 

See https://developer.rchain.coop/tutorial#

To fix it, for example use the following snippet in your CSS.
https://stackoverflow.com/a/41309213/345913

* Estimated Budget of Task: **$100** 
* Estimated Timeline Required to Complete the Task: **1 hour**  
* Measure of Completion: **Hard coded numbers are removed and lines are numbered through CSS on the above URL**

**Comment by tschoffelen** [comment]
This one has been effectively resolved by me rebuilding the entire tutorial, see #622 for details.
