### ISSUE TITLE
D> Make Rholang Tutorial code examples interactive

### ISSUE THREAD

**Issue by tschoffelen** [rchain/bounties#622]
Update [Rholang Tutorial](https://developer.rchain.coop/tutorial) page by changing code snippets to embedded versions of [Rchain.cloud](http://rchain.cloud), allowing readers to immediately execute those snippets and see the output of the compiler. Also changed the layout, added edit button (linking to Github), and some other tweaks.

*Estimated Budget of Task:* **$1000**  \
*Estimated Timeline Required to Complete the Task:* **5 days**  \
*Measure of Completion:* **Github PR to the developer website**  \
*Status* **[PR merged](https://github.com/rchain/rchain/pull/683), live on [website](https://developer.rchain.coop/tutorial/)**

**Comment by Ojimadu** [comment]
Would it be possible to also have these tutorials on rchain.cloud

**Comment by tschoffelen** [comment]
I started working on this repo: https://github.com/tschoffelen/rholang-tutorial

Far from finished, but I think this is going into the right direction. Would love some feedback.

**Comment by dckc** [comment]
[sharable URLs for rchain.cloud](https://github.com/th3build/rchain.cloud/issues/5) would help with this sort of thing. That's what I had in mind when I chatted with you about this, @TrenchFloat

**Comment by tschoffelen** [comment]
I finished a version of the tutorial that downloads the original markdown file, processes it, and adds runnable code samples: http://rholang-tutorial.surge.sh/

Repo is in my previous comment.

**Comment by tschoffelen** [comment]
@MParlikar may I rope you in here to see what would need to happen to get a version of this live on the developer site?

**Comment by dckc** [comment]
@KellyatPyrofex is also very much involved in documentation.

But... if the core dev team were to take it on, we'd be right back to having them take responsibility for securing the service: [RHOL-78](https://rchain.atlassian.net/browse/RHOL-78). The core team just accepted my [PR 659](https://github.com/rchain/rchain/pull/659) that removes **rholangweb** from the core source tree altogether in favor of rchain.cloud.

**Comment by dckc** [comment]
Oh... maybe not... maybe developer.rchain.coop could just point to rchain.cloud for running the examples.

**Comment by KellyatPyrofex** [comment]
Wow, @tschoffelen! your version of the Rholang tutorial is amazing and similar to an idea the dev team talked about a few weeks ago. We can absolutely feature it on developer.rchain.coop. In fact, I would love to do this quickly to coincide with this week's release of RNode-0.3.

There is a new version of the Rholang tutorial coming out with the release. Would you be able to update your tool to pull from a new file before the end of the week? Here's the trick... I'm waiting on the dev team to do the last merge before release. Please contact me via Discord (KellyFoster#5307) to discuss.

**Comment by KellyatPyrofex** [comment]
@dckc starting last week developer.rchain.coop does feature rchain.cloud as a tool for running examples

**Comment by tschoffelen** [comment]
Status update: as requested by @KellyatPyrofex, submitted a [PR](https://github.com/rchain/rchain/pull/683) into the core RChain repo.

**Comment by PatrickM727** [comment]
This is great!

**Comment by PatrickM727** [comment]
@tschoffelen are you interested in more technical writing work? dm me on discord too @patrick727 and let's sync with pyrofex.

**Comment by azazime** [comment]
Nice one, such tutorial when completed should also be made available on various social media platforms

**Comment by decentralizebanksy** [comment]
Roger that. It's done. I included it in this week's schedule. Great idea @azazime! For future messages, we can also breakdown each code snippet example into individual posts/tweets with unique links to the tutorial and rchain.cloud example. The static rholang tutorial has been shared across our social media channels often.

**Comment by dckc** [comment]
> Would anyone mind voting for this ...

done.

> I screwed up by placing a budget vote too early ..., any way to fix that?

You already did it: placed a vote in the 201805 pay period.

The dangling vote in 201804 is just business-as-usual.

**Comment by tschoffelen** [comment]
Can I bother someone to add one more vote on [rewards.rchain.coop](https://rewards.rchain.coop/index.php?-table=issue&-search=tutorial&-action=list&-submit=Search+Issue#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-table%3Dissue%26-search%3Dtutorial%26-action%3Dbrowse%26-submit%3DSearch%2BIssue%26-sort%3Dnum%2Bdesc%26-cursor%3D1%26-skip%3D0%26-limit%3D30%26-mode%3Dlist%26-recordid%3Dissue%253Fnum%253D622%26-ui-root%3Dmain-content)?

**Comment by dckc** [comment]
@TrenchFloat go ahead and vote based on comments above by @KellyatPyrofex ?
