### ISSUE TITLE
Translate the Medium blog posts to Chinese Part 2

### ISSUE THREAD

**Issue by linsheng9731** [rchain/bounties#625]
Tasks:

- [x] Copy the posts to text files.
- [ ] Translate the content.
- [ ] Check the spelling.
- [ ] Review each other's work.
- [ ] Have them reviewed by others with knowledge of English and Chinese.
- [ ] Post them to the Chinese [Medium]() or equivalent 

# Translators

Thanks for your interest in telling the story of RChain in another language.

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #242 #246 ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

i will translate those documents into chinese with @RowlandZhou @yyh1102 .

I will translate this one
a-visualization-for-the-future-of-blockchain-consensus[1408 words]

This article is assigned to @yyh1102
annual-meeting-summary[919 words]

The two articles are assigned to @RowlandZhou
the-first-membership-meeting-will-be-held-on-october [518 words]
vlad-zamfir-joins-the-rchain-cooperative [379 words]

Suggested Budget: $700 (for 3224 English words)

**Comment by linsheng9731** [comment]
This issue is related to #541

**Comment by BelovedAquila** [comment]
@linsheng9731 you are right, so why the duplicate please ?

**Comment by yyh1102** [comment]
Have done the translation work and upload it to [google doc](https://docs.google.com/document/d/1eluC3q8BljOVyXN0aRBIqzEg_1ZOZOA7D5T4qY4wrEo/edit)

**Comment by RowlandZhou** [comment]
I have done the translation of [the-first-membership-meeting-will-be-held-on-october [518 words]](https://docs.google.com/document/d/1lqYKhFd1i9CazpDEgtIos6pVgEZgOxfPolB7H-MoN70/edit?usp=sharing) and vlad-zamfir-joins-the-rchain-cooperative [379 [words]](https://docs.google.com/document/d/1idqpJKK1u3WWEb3L5lNdDIA3sERKMmNu4f9k_t777mY/edit?usp=sharing)，

**Comment by ICA3DaR5** [comment]
Please post the content to a blog service like [Medium](https://medium.com/). Also you state "Italian" in the content and "Chinese" in the title.

**Comment by ICA3DaR5** [comment]
Any updates on this issue?

**Comment by zsluedem** [comment]
@linsheng9731 You can post it in http://www.rchain.site/

**Comment by linsheng9731** [comment]
I post them to google doc, you can check them [here](https://docs.google.com/document/d/1PtkzlQruW3CswAOce1XhgHdmyE1dxVUrl4Q6zCDAxeI/edit)

**Comment by yuhuanmocmoc** [comment]
we have posted some of them to [Medium](https://medium.com/rchain-cooperative-china)
