### ISSUE TITLE
Convert Non RAM's  RChain Telegram Members To RAM's 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/bounties#626]
*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

In cognizance to the development and growth of the RChain Telegram groups  and the intended  management of the Telegram groups #606, there is an irreversible need for the conversion of Non-RAM's  from the RTG  to RAM's, by bringing the RTMs who are not yet RAM's into becoming bona-fide RAM's 

Estimated Budget of Task:$1500
Estimated Timeline Required to Complete the Task:  Monthly 
Measure of Completion: in Process... 

The suggested budget is for the time being, as we will be scanning through the current groups 
These are the current groups:
https://t.me/rchain_coop
https://t.me/rchain_official (announcement channel)
https://t.me/rchain_africa (see #592)
https://t.me/rchain_cn
https://t.me/rchain_fr
https://t.me/rchain_nl
https://t.me/rchain_ru (new, see #596)

Subsequent groups might influence the estimated budget 

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by David405** [comment]
@BelovedAquila @lapin7 I created a <a href="https://docs.google.com/spreadsheets/d/1Z-o19S7lhkfsBYkSmXH4OMquoNXrwee-rZVKccPmmCA/edit#gid=0">database</a> which can help us keep track of RAM and non RAM members in all telegram groups, that way we can know what percentage of telegram group members are RAM members and also we can track our rate of converting RTM to RAMs

**Comment by David405** [comment]
Each of the telegram groups in the spreadsheet has different colours for ease of identification. I have also started filled in the RAMs in RChain Africa group.

**Comment by lapin7** [comment]
I've moved the spreadsheet here:
[Folder SocialMedia](https://drive.google.com/drive/folders/1tcaoqSJXtfclWWJTNqIG0FW2wssUKHzs)
[File](https://docs.google.com/spreadsheets/d/1Z-o19S7lhkfsBYkSmXH4OMquoNXrwee-rZVKccPmmCA/edit#gid=0)

**Comment by David405** [comment]
Nice work @lapin7, can I get a list of all RAMs and their country of origin so they could be filled in appropriately

**Comment by BelovedAquila** [comment]
@David405 that's a good one with the database, but there are some vital columns or cells  that needs to be added, am on it.
@lapin7 well done

**Comment by BelovedAquila** [comment]
Yes this is actually intended to be monthly because we have to be updated as the groups keeps enlarging, @David405

**Comment by Murphy6** [comment]
That is a wonderful idea and this link can be shared on various watsapp groups for members that aren't on telegram platform
