### ISSUE TITLE
Article of incorporation link broken 

### ISSUE THREAD

**Issue by BelovedAquila** [rchain/bounties#627]
*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

I was trying to undertake some task and came across the Article of incorporation [link](https://github.com/rchain/board/blob/master/2017/01-10/RChain%20Cooperative%20-%20Articles%20of%20Incorporation%20with%20Ra) under the  [RChain Reference](https://github.com/rchain/board)  which doesn't respond but rather redirects to a 404 error signal. @ian-bloom can you please  look into this? 

Estimated Budget of Task: **$[200]**  

***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by Jake-Gillberg** [comment]
LOL @ $200 to fix a broken link. [Pull request submitted to fix the link](https://github.com/rchain/board/pull/2). Content found [here](https://github.com/rchain/board/blob/master/2017/01-10/RChain%20Cooperative%20-%20Articles%20of%20Incorporation%20with%20RA.pdf).
