### ISSUE TITLE
Post on habr.ru front page on rholang

### ISSUE THREAD

**Issue by Barkov-F** [rchain/bounties#628]
### Posted on rholang on habr.ru

This post was briefly on the frond page of the site and it's getting hundreds of [views](https://habr.com/post/354398/). Hope it will draw some interest from russian speaking developers community. The post covers the basics of the rholang.

*Estimated Budget of Task:* **$500**  \
*Estimated Timeline Required to Complete the Task:* **Done**  \
*Measure of Completion:* [**post published**](https://habr.com/post/354398/)

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by Barkov-F** [comment]
@lapin7 @qelentium Can you vote on the budget?

**Comment by Barkov-F** [comment]
@Ojimadu you've seen the link to the post on the tg channel, did you like it? Can you vote on the budget? The post has about 700 views and generated some pulls on docker container

**Comment by pmoorman** [comment]
@Barkov-F good work here.

I'm responsible for tidying up the issue list with "marketing" labels, and I think this issue is completed/done, right?

If so, you can close the issue so it doesn't stick around here forever!
