### ISSUE TITLE
Newsletter - Apr 4th, 2018

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/bounties#630]
I'm too late to suggest any edits on this one, but anyone who had a part in this newsletter can say so here. Here is the [google doc](https://docs.google.com/document/d/1Va_u-I_IWCvpWVgQXNKsFuhpaH-enouhPotJMTGoiRM/edit) with the notes for all the hangouts and the [Weekly Debrief Index](https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index).

**Comment by BelovedAquila** [comment]
Doing some reviews on the doc @TrenchFloat

**Comment by kitblake** [comment]
Thanks for creating this @TrenchFloat.
I put in a bit of time on this and @plantether put in lots.
https://docs.google.com/document/d/176Ml0ewMXCBjWXhODktMWjPIuLCy7lKtXhofBbIm10g/edit

**Comment by kitblake** [comment]
What system is sending the newsletter now? There's an out-of-date link going to:
http://archive.sendpulse.com/shc4c/Ade65e732/
in https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index

**Comment by Viraculous** [comment]
Hello @Trenchfloat and @kitblake, I could still review the docs. They are awesome.

**Comment by Viraculous** [comment]
Awesome @Kitblake

**Comment by pmoorman** [comment]
can we close this off @TrenchFloat ?
