### ISSUE TITLE
M> Wechat official account for 201804/05

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#632]
### For all issues
[Keep italic labels, replace brackets with answer]

Same as #258 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

**In the past month, me and my teammates post more than 10 articles to the Wechat official account to spread Rchain's Idea.
Most of the articles are the rchain medium post translation. Besides, we also upload RChain team latest progress, rchain core videos and other resources.**

*Estimated Budget of Task:* **$3000**  \
*Estimated Timeline Required to Complete the Task:* **4weeks**  \
*Measure of Completion:* **12 new articles has been post**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by linsheng9731** [comment]
Good job 👍

**Comment by rjl493456442** [comment]
Update: 
In the past month(201805), me and my teammates post 12 articles to the Wechat official account to spread Rchain's Idea.
Most of the articles are the rchain medium post translation. Besides, we also upload RChain team latest progress

**Please follow our account by scanning the QRCode below. You can check all posts uploaded by us in the past several months**

![image](https://user-images.githubusercontent.com/5959481/40888080-b10ce018-6784-11e8-8c0f-e8048ca0350a.png)

**Comment by rjl493456442** [comment]
Besides, the budget for may including the translation reward for 12 community update articles(about 600 dollar).
