### ISSUE TITLE
Translating Rchain to Nigerian Pidgin English and other languages

### ISSUE THREAD

**Issue by iamcoderisk** [rchain/bounties#634]
Since Africa is the next target market for crypto, and Nigeria is one of the target region to start with, there's therefore a need for language translation I.e having an option in the home page to switch from one language to another ("Yoruba","Housa" and "Igbo").
The reason is because since we are trying to buy the mind of the people in Nigeria, most of the business men from these three ethnic groups do not really understand much English, they'd be a need for Translating English to *Nigerian pidgin*, *Yoruba*, *Housa* and *Igbo*. I can assist with the implementation of the stated suggestion.
Look up for http://pidgin.com.ng/app
This is just an example of a working English to Pidgin translator that a friend of mine created, its very much feasible and achievable.

**Comment by Ojimadu** [comment]
Hi, @iamcoderisk,  I don't think this is a good target for translation as a good number of Nigerians are able to speak English, Nigerian pidgin is a vernacular of English language, people that only speak pidgin can't read nor write. I don't think translating to pidgin is necessary.

**Comment by pmoorman** [comment]
I'll close this issue, since it seems the consensus to not pursue this (I agree). Feel free to re-open if it's relevant in any way.
