### ISSUE TITLE
A need for a proper explanation of Rholang keywords and usage.

### ISSUE THREAD

**Issue by iamcoderisk** [rchain/bounties#635]
Hi guys, 
They'd be a need for a proper explanation of the various components of the Rholang because the current documentation isn't friendly at all. 
Take a look at this
```
new myApp in {
 contract myApp(args)={
display("Hello\t",args, "!\n")
} |
myApp(" Prince Darlington")
}
```
The real interpretation of the above snippet is this:
There's a class called ##myApp
and has a constructor called ##myApp, where the constructor only accepts one argument string. In the constrictor, the display method is called to simply output the "Hello" string alongside with my name; and immediately after the closing of the constructor parenthesis, there's a bar separating the constructor and the instance of the class ##myApp. The simply means "do two things", execute the class constructor and instantiate the class immediately. I believe my explanation is quite easy and straight forward as they'd be a need for a proper explanation of the keywords and their usage. Nevertheless, I can assist with the tutorials development so that African developers and other developers who are willing to join the development team cab catch up easily with Rholang.

**Comment by iamcoderisk** [comment]
Oh I see, thanks anyway

**Comment by plantether** [comment]
@iamcoderisk @lapin7 @patrick727 @kitblake This sounds like a good idea to me, if nothing like this exists or is in progress.

**Comment by azazime** [comment]
We need more of such ideas to expand our brand

**Comment by kitblake** [comment]
@iamcoderisk It looks like your "Rholang keywords and usage" is referring to a code level. Fyi, there was a project to build an RChain Dictionary, operating on a somewhat higher level, but it stalled waiting on developer input that never materialized: 
https://github.com/rchain/bounties/blob/master/projects/dictionary.md

**Comment by zsluedem** [comment]
@kitblake any open issue about the dictionary?
@David405 I agree with u about the advancing the more general explanation Rholang to a standard tutorial.

**Comment by allancto** [comment]
@iamcoderisk I think it's an excellent idea. Please look at the link that @kitblake provided. That dictionary is a bit technical, were you talking about translating those concepts into everyday terms, or expanding on the dictionary as it is? In either case could you give some examples of how this might turn out? I think I would vote for a reward on this project if it turns out something useful. 

cc @allancto

**Comment by allancto** [comment]
@kitblake what is this about, at the bottom of the md? What is VPG? 

Project Double Linking
This document is being referenced and curated by the VPG. Your help and suggestions are most appreciated. Join us at Mattermost for the Social Ledger experment.
