### ISSUE TITLE
Financial report to inform board

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#637]
# *Financial report to inform the board* 
RAM's and board need financial data in order to manage the Coop. Oversight is important for self-management. Not only the board needs to be informed about Key Performance Indicators (KPI) but RAM's as well. Like that we can better manage budgets and be more result focused. Also project management can not do without KPI's. 

But instead of creating committees that make decisions and managers that command things to be done, RAM's can do that themselves in small teams that are focussed on solving an issue in the SMARTest way.

Let's create [KPI-dashboards](https://www.klipfolio.com/resources/dashboard-examples).

This is a first setup. Please re-edit this first comment in order that it can function as contents table.

- [ ] amount of RHOC in Treasure
- [ ] amount of RHOC in market
- [ ] market cap, volume, moving average as RHOC traded on markets
- [ ] RHOC spend on SoW, Employees, Bounty, Deals
- [ ] Cash Flow position: USD, BTC, ETH, RHOC, AMP
- [ ] Balance
- [ ] Tax to pay
- [ ] ......

*Estimated Budget of Task:* **[$ 1000]**   
*Estimated Timeline Required to Complete the initial Task:* **[2 weeks]**  \
*Estimated Timeline Required to provide report monthly:* **[1 day]**  \
*Measure of Completion:* **[Published reports]**
*KPI dashboards:* **[[Document](https://docs.google.com/document/d/1PPfKGk3hxKiVYdbAWpXQAD-BJlzT7PCjnVSoR2JD4sI/edit)]**
--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by jasoncruzzy** [comment]
Great @lapin7, I think will be very helpful to the development of our community

**Comment by jasoncruzzy** [comment]
@lapin7  I think the first comment will be best suited as "financial index window"

**Comment by lapin7** [comment]
@jasoncruzzy 
First comment as "Financial index window"
Let's create: *KPI dashboards:* **[[Document](https://docs.google.com/document/d/1PPfKGk3hxKiVYdbAWpXQAD-BJlzT7PCjnVSoR2JD4sI/edit)]**

**Comment by pmoorman** [comment]
@lapin7 great idea to try bring some data into the decision-making process. I don't know if these suggestions are in-scope with what you're thinking, but I would suggest a few 'softer' things would be really valuable for RAMs to have. 

For instance:

- Highest priority/**goals for the coop / bounty system**... so we know what we're collectively trying to achieve  (I would suggest: "get Rholang DApps created on RChain come Mercury launch")

- In line with that, maybe something like **"epics" or "focus areas"** or something of the sort. So people know what kind of action is most valuable towards achieving the above top-level goal.

- **Estimated value** of (for instance) bringing onboard a functional Haskell developer, or other kind of 'buckets'.... so we can make better autonomous decisions about spending _(For instance: if we pay $1500 for tactic X which we expect will bring 2 new Haskell developers into the coop. Is that a good deal, or not?)_

- **Funnel metrics** such as "visits to website", "new members last 30 days", and "SDK downloads last 30 days" and so on.... so we know how we're doing, and which things are working or could be better

- **Targets for all of the above.** Even if the bounty program can't actually impact all targets, it's a good start to at least _know_ what the target is. That makes it easier to think along in a constructive way.

----

**Next action:** @lapin7 let me know if this aligns with what you're thinking, before I try merge it into your write-up. Maybe this is not in line with what you had in mind.

If you need specific KPIs for any of my ideas, I can make suggestions of course.

**Comment by pmoorman** [comment]
oh, random idea.... 

**We could compile the KPI dashboard once per month, and turn it into a good-looking infographic of sorts?**

- That way we can turn it into a piece of content for marketing. 
- It also ties nicely into the idea of radical transparency, and showing people what's going on while we're hard at work...

**Comment by barneycinnamon** [comment]
Is the report to inform the board or to inform the members? I would like it if the board and the members saw the same stream of information. Independently, it would be valuable to the bounty system to have its own mini version of this based on the funds available to that system. That would help inject a notion of opportunity cost into the evaluation of spending Co-op (bounty system) funds on any given pursuit.

**Comment by azazime** [comment]
Amount of RHOC in market should come before the amount of RHOC in treasure, then Tax to pay comes ahead of Balance which should be last on the table.

**Comment by barneycinnamon** [comment]
I am going to close Issue #494, which I think will be covered by this issue.

**Comment by lapin7** [comment]
Here's a spreadsheet to play with.
https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=592953635

It has all data of Budgets and Bounties from August 2017 to April 2018

It's the base for a nice financial report.

**Comment by jimscarver** [comment]
This issue is on the task approval overdue list. Do you want to budget this?
