### ISSUE TITLE
Marketing and Branding Discord Discussion Consolidation

### ISSUE THREAD

**Issue by AyAyRon-P** [rchain/bounties#638]
"...Provide documention to consolidate all internal thinking about Branding and Taglines discussed to loop in a carefully chosen Branding Firm to help us explain this wonderfully pluripotent project to an attention-deficited world." - Jonathanks

In reference to #471 - Principles and Values WG

*Estimated Budget of Task:* $40/hr - 15hrs est
*Estimated Timeline Required to Complete the Task:* 1 week
- [x] *Measure of Completion:* Send Gdoc  to @jonathanks
https://docs.google.com/document/d/1y-rd8rin8QnHavSCC5__tSloa0j_8NCtM32zbjfuxZM/edit?usp=sharing

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by philipandri002** [comment]
Awesome.. But please try and use more common and simple terms in explaining this issue..I.e a clearer elaborations

**Comment by AyAyRon-P** [comment]
More common and simple terms of what? @philipandri002

**Comment by AyAyRon-P** [comment]
Again, terms of what? Elaborate on what you’re asking for. 

This project simply consolidated all communications from discord regarding the tagline and logo process. 

It seemed straightforward to me in the first 3 lines. The remainder of the quote just happened to be part of the full sentence.

**Comment by philipandri002** [comment]
AyAYRon-P sorry I ididnt quite understand it at first.

Nice one
