### ISSUE TITLE
Expand on events list with "non-blockchain" centric events. Let's try for 30 this week. 

### ISSUE THREAD

**Issue by PatrickM727** [rchain/bounties#639]
### For all issues
The people in issue #583 did a great job finding a bunch of blockchain oriented events. 

I'd like to create this issue to find other conferences that may not blockchain centric but RChain could attend because of our unique organization. 

Examples of topics to search are. 
- decentralization
- functional programming
- social coordination
- innovative activism
- open-source software
- tokenization
- platform cooperatives
- futurism
- etc. 

*Estimated Budget of Task:* **[$200]*  \
*Estimated Timeline Required to Complete the Task:* **[1 Week]**  \
*Measure of Completion:* **30 New Events in the linked list that are non blockchain centric**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by jasoncruzzy** [comment]
Nice one @PatrickM727 i think this is a great idea.....I'm in on this

**Comment by Viraculous** [comment]
I created a Google sheet for the this issue [HERE](https://docs.google.com/spreadsheets/d/1X840EVeJsT4-rYdbPQap4ey8QtG3YCg8-yRTKR3dyIE/edit?usp=sharing). Do you mind reducing the scope of the event list to 10 or 15 for faster implementation.

**Comment by dckc** [comment]
@patrick727 and @PatrickM727 are awfully similar... anyone care to explain?

**Comment by dckc** [comment]
ah... "locked out..." https://github.com/rchain/bounties/issues/604#issuecomment-381646934

**Comment by Viraculous** [comment]
@PatrickM727 , I have added about 9 conferences to the Gsheet. Still getting much more events anyway but I guess we need a guide to this conferences as well to define the imperative ones that meet the community's need.

**Comment by Ojimadu** [comment]
@Viraculous, Patrick said he asked you to drive this issue and issue #583, I would like to see that's both these issues are merged to a new issue for a monthly list of events with a time gap of one month before the actual event takes place.

**Comment by Viraculous** [comment]
@Ojimadu thanks. Merging it is better than having two seperate events-to-attend issues. I will create a seperate google sheet ranging from blockchain to non-blockchain events as it meets the scope that @PatrickM727 listed above and sort out events a month ahead based on certain criteria. It would be wonderful to set a yardstick an event must reach before it can be deemed fit for the community to attend. For me, it should be in the order of locality within RChains mobility, the number of attendance and the opportunity it provide the community to build its team and get in touch with influencers and thought leadership. Am also persuaded to raise and issue on the metrics for RChain being part of an events.

**Comment by Ojimadu** [comment]
Closing this issue in favour of #743
