### ISSUE TITLE
upload videos to Chinese website on April

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#643]
upload the videos from Youtube to Chinese video website
I have inform the QQ group about the videos.

1.[Rchain Developer Boulder Conference Opening Announcement](https://www.bilibili.com/video/av22165199)
2.[Rchain Boulder Developer Conference Day One Session 1](https://www.bilibili.com/video/av22174982)
3.[Rchain Boulder Conference Day 1 Session 2](https://www.bilibili.com/video/av22167392)
4.[Rchain Boulder Conference Day 1 Session 3](https://www.bilibili.com/video/av22176664)
5.[Rchain Boulder Developer Conference Day 2 Session 1](https://www.bilibili.com/video/av22204884)
6.[Rchain Boulder Developer Conference Day 2 Session 2](https://www.bilibili.com/video/av22207579)
7.[Rchain Boulder Developer Conference Day 2 Session 3](https://www.bilibili.com/video/av22211783)
8.[Rchain Boulder Developer Conference Day 3 Session 1](https://www.bilibili.com/video/av22262761)
9.[Rchain Boulder Developer Conference Day 4 Session I](https://www.bilibili.com/video/av22323865)

Measure of Completion: completed already
Suggested Budget: 200$

**Comment by philipandri002** [comment]
Is the video in Chinese or in English

**Comment by zsluedem** [comment]
English @philipandri002
