### ISSUE TITLE
Management of the italian website and social media

### ISSUE THREAD

**Issue by ghost** [rchain/bounties#645]
## Collaborators:

- @akhs13 
- @Chris-Arv 
------------------------------------------------------------------------------------------------------------------

Hi to all. We have completed the creation of the italian social media platforms and website (#573), where all the translated documents*1  are available, which means that we now have all the means we need in order to make RChain more accessible to new developers and members from Italy. We are open to any suggestions and criticism and we invite anyone willing to help with the betterment of this project. @lapin7 

## Goals

- [ ] Post about the italian website on the italian altcoin subforum at [Bitcointalk](https://bitcointalk.org/index.php?board=132.0) and bump of said post in order to keep it on the front page.
- [ ] Promotion of the italian website on other italian technology-oriented forums.*2
- [ ] Management of the italian Forum and Telegram channel in order to promote discussion and help potential new developers and members with their questions.*3
- [ ] All RChain posts on Twitter and Facebook will be translated and reposted on the  italian [Twitter](https://twitter.com/rchain_it) and [Facebook](https://www.facebook.com/rchaincoop.it/) within one day. Any post which is news will be posted on the italian website, under the category [RChain news](https://rchaincoop.it/category/rchain-news/).
- [x] All italian Medium posts will be promoted on Facebook and Twitter and reposted on the italian website under the category [Blog](https://rchaincoop.it/category/rchain-blog/)
- [ ] All key RChain videos will get italian captions from the translations and will be reuploaded on the [italian RChain youtube channel](https://www.youtube.com/channel/UCLW_uxNsXBsJE0BBlXLAX3w), and then posted on Facebook, Twitter as well as the [RChain Video](https://rchaincoop.it/category/rchain-video/) category of the italian website.
- [ ] Update the italian website with any newly translated or updated document.
- [x] Maintenance of the italian website. *4
- [ ] Anything else that the community deems necessary.
-------------------------------------------------------------------------------------------------------------------
*1 `IMPORTANT`  The option for italian is not available as of yet on the [RChain Platform Architecture](https://rchain-architecture.readthedocs.io/en/latest/index.html) page (as indicated in #368 ) Should we wait for it to be built or should we upload the italian architecture docs on the italian website? @AbnerZheng @dckc  
*2 Links to all the posts on italian forums will be posted here in real time.
*3 All statistics from the italian forum and telegram page will be posted here at the end of the month.
*4 All webstite statistics will be posted here at the end of the month.

**Comment by Staff91** [comment]
@jasoncruzzy  Do you mean @Chris-Arv @akhs13 ? My collaborators? Yes, they are aware.

**Comment by Staff91** [comment]
Due to my busy schedule,  @akhs13 will be in charge of the management of the italian Website and social media.

**Comment by Staff91** [comment]
As soon as the payment for May has been made I will leave the bounty and the translations due to personal reasons.I want to thank for everything my associates @akhs13 and @Chris-Arv the whole Rchain team and especially @lapin7.

**Comment by AyAyRon-P** [comment]
@kitblake @pmoorman 

Do either of you have visibility into this?

**Comment by pmoorman** [comment]
I'm closing this out due to (what looks like) inactivity. If anyone actively wants to pursue this task, feel free to reopen and recommit to it!
