### ISSUE TITLE
The Ultimate Rchain Mega Review Mashup Video 

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#649]
### For all issues

I will source, download and cut /take the best parts / highlights of the Rchain Coop, as described by the various existing reviews currently on YouTube, re-edit and create a high impact reel that will leave a solid positive impression on the market -  creating an dynamic intro and some added special effects and vibrant background music to suit. 
[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

*Estimated Budget of Task:* **$3000**  \
*Estimated Timeline Required to Complete the Task:* **2-3 weeks**  \

Goals 

- [x] Source and download Various Reviews about Rchain

- [x] Filter the videos individually, edit and extract the highlights

- [x] Arrange the sections into the project editing timeline and start the editing process

- [x] Create a unique Intro and Outro for the Showreel

- [x] Record,Edit and include the Voice Over 

- [x] Add the Special effects, Audio and Titles and bake

- [x] Get the video Uploaded to the Rchain Youtube channel

**Comment by Cryptovideos** [comment]
Sorry guys - accidentally closed the issue earlier - please consider opened for now

**Comment by Cryptovideos** [comment]
@pmoorman need you advice :  would it not be a good idea to suggest that we add a "Video" tab to our Rchain website ....whereby we could then pull all the video links straight from the Rchain Youtube Channel so visitors could watch them there?  This is in fact also great for Organic Seo on the website as well... as Google owns Youtube and Videos are a great pull factor for website ranking.

**Comment by iamcoderisk** [comment]
Hi, i am thinking of providing a solution to what you just suggested, but I want wanted o get something clear. Do you mean whoever can handle the editing should check on some other reviews about rchain just to have idea of what's happening, am I right?

**Comment by Cryptovideos** [comment]
@iamcoderisk - thank you for connecting - i am going to be handling the entire video  - sourcing the reviews, editing them, adding the special effects, intro music - the whole thing. This is what i do full time so no assistance needed from anything video realted standpoint. but thank you

**Comment by jasoncruzzy** [comment]
@Cryptovideos I have some video links of RChain i can assist you with and I will advice your re-editing(video) be kind of brief and also some should be comprehensive. The brief/short videos can the more about Rchain introductions. Overall its a fantastic idea and i want to be part of this

**Comment by Cryptovideos** [comment]
Thank you Jason, i have a particular vision for this style of video so regards the advice,i will condsider it and feel free to send me your suggestions.please email all relevant links to : evanbasson@hotmail.com

**Comment by jasoncruzzy** [comment]
@cryptovideo I just sent one to you via the e-mail you sent to me....i'm
still working on getting some more if i can

**Comment by Cryptovideos** [comment]
Tks jasoncruzzy@gmail.com  Omeka - please dont send millions of single emails- rather send one email containing many links etc etc... tks bro - i have those links now - appreciate the help.

all is well should i need further assistance ill reach out to ya brother

**Comment by jasoncruzzy** [comment]
Sorry that was an error

**Comment by Cryptovideos** [comment]
No sweat dude - thanks for the good vibes - I will be in touch should i need any more links etc.

**Comment by dckc** [comment]
@Cryptovideos writes:
> i am going to be handling the entire video ... so no assistance needed ...

I wonder if that style is appropriate. Please be more open to collaboration.

> ... regards the advice,i will condsider it and feel free to send me your suggestions.please email all relevant links to ...

There's a time and a place for private discussion, but please minimize it. In general, please keep the discussion open.

**Comment by makys** [comment]
Just to chime in here, IMO the culture of the coop is heavy on collaboration and transparency. We believe in the Collective Intelligence as re-iterated so many times as far as I can recall.

When I saw @dckc comment, I was forced to go through the entire thread. 

@Cryptovideos I appreciate the skills that you bring and the awesome videos you have made. However, it would be preferred if this engagement is collaborated on with members willing to support in ways they can. I understand that you do this sort of task professionally and maybe have your fixed routine; I would appreciate inclusiveness on this and related task.

**Comment by jasoncruzzy** [comment]
@makys thanks for the observations here is one of the video i have sent to  @Cryptovideos https://youtu.be/_QvmCQm2OD0

**Comment by jasoncruzzy** [comment]
@Cryptovideos @dckc @makys here is another video that should be helpful to this issue https://ci4.googleusercontent.com/proxy/7PV1I8SNqivkBlGC5Ba8Jw_FhaZ7mIQG8bMDnRV995zBgdmL5f_l4qw_pYGVjZUxmrnEcZryq9QOI5Vv3mdtnyc_2yhG5gJmufUxssMLAE6ClyqKUkyXgQ=s0-d-e1-ft#https://ssl.gstatic.com/docs/doclist/images/icon_11_video_list.png

**Comment by Cryptovideos** [comment]
@dckc  - points noted tks 👍 Still getting the hang of this way......

@makys  - Points noted here as well 👍 ......thank you for that

@jasoncruzzy  - I feel That Tutorial video is not within the scope of this project "  Rchain personal invoice tutoria.mp4 " 

The other links you have sent are defiantaly within the scope as they acrtually do reviews about Rchain....they are great to work with, iv checked em out and there are indeed sections to use - cheers

**Comment by jasoncruzzy** [comment]
@Cryptovideos I found another video which might be helpful to this issue. Here is the link https://youtu.be/2SiEBpSI6Uo check it out.

**Comment by philipandri002** [comment]
Great job @cryptovideos and @jasoncruzzy..

@cryptovideos can I ask you to also after you finish editing send some of us the video to proof study and cross check to see if there be any mistake or need for improvement like the saying goes two good heads are better than one.

Thanks

**Comment by philipandri002** [comment]
Great job @cryptovideos and @jasoncruzzy..

@cryptovideos can I ask you to also after you finish editing send some of us the video to proof study and cross check to see if there be any mistake or need for improvement like the saying goes two good heads are better than one.

Thanks

**Comment by Murphy6** [comment]
@jasoncruzzy nice work on the videos.. Really would love to have most of the videos so as to upload on our Instagram handle

**Comment by Cryptovideos** [comment]
@Murphy6 i can send you the videos directly? or however you propose? im editing the feature at the moment and should have the first draft ready for viewing early next week sometime!

**Comment by Cryptovideos** [comment]
BOOM!!! here we go -  https://youtu.be/C_L-yGY2CYc

**Comment by lapin7** [comment]
It's a pity that the CEO @leithaus is not on.

**Comment by Cryptovideos** [comment]
is there any videos of him? id be happy to include it into the edit?

On 07 Jun 2018, at 19:45, HJ Hilbolling <notifications@github.com<mailto:notifications@github.com>> wrote:


It's a pity that the CEO @leithaus<https://github.com/leithaus> is not on.

**Comment by lapin7** [comment]
Maybe interesting parts of the Wednesday Debriefs where Greg is talking.

**Comment by Cryptovideos** [comment]
Agreed - and if anyone else could direct me to extra videos i can include this is most welcome too - and thanks to those who suggested the previous Youtube Links as well.

**Comment by lapin7** [comment]
My Discord went down. Sorry

**Comment by lapin7** [comment]
The [Amsterdam meetup of BlockchainTalks.io ](https://www.youtube.com/watch?v=RAyzSSpaeVA)on Streamed live on May 23, 2018 

![image](https://user-images.githubusercontent.com/1913335/41140927-5ce89f62-6af0-11e8-8a09-321ba565a0c2.png)

Probably I will go through that video to submit the most interesting parts, because it's a 3+ hour video.

**Comment by Cryptovideos** [comment]
@pmoorman @lapin7 awesome input!

@lapin7 please send me info regards the parts you want me to cut out The Amsterdam meetup of BlockchainTalks.io  video to include into my master edit - tks chief

**Comment by Cryptovideos** [comment]
@makys @pmoorman @Murphy6 @jasoncruzzy @dckc Would appreciate some support... please Vote for me in the rewards/budgets app. Thanks all

**Comment by entropee** [comment]
Very nice work, @Cryptovideos . I gave you a thumbs up on youtube. I'll ask for guidance about voting for the budget after just watching, but I have some thoughts. 
1. We need more shots and clips of Greg and other devs, maybe while some of the other commentators are mentioning them. 
2. Lawrence's content was great but his audio quality was BAD. Is there any way to cool it off a bit. Maybe get him to redub? Should the coop buy him a good mic?
3. I'm no prude but the sharding/sharting reference at 13:00 doesn't match the tone or overall good taste and professionalism of the rest of the audio. 
4. I love the music but the _pacing_ seemed a bit fast for the clips chosen. How about something slower with a bit of gravitas.

**Comment by jasoncruzzy** [comment]
@pmoorman the video work is awesome and fantastic. Should be considered....@Cryptovideos send me a direct message

**Comment by pmoorman** [comment]
@Cryptovideos @entropee @lapin7 I want to vote a budget here, but I see you all have voted $3.000 already.

What is this $3.000 budget based on?

**Comment by Cryptovideos** [comment]
@jasoncruzzy thanks man -

**Comment by Cryptovideos** [comment]
@pmoorman budget/rewards covers time - time to source, download and scour the clips individually, then cut each one down separately and extract selected pieces, then add and mix these pieces into a master edit, then amend all the sound levels on each piece individually as best as poss...based on exisitng Audio, then creating the intro separately in animation software, then incorporating that into the timeline, thereafter adding and dubbing the backing track and raising, lowering levels to match audio clips, all time basically -then theres the next pahse, re-editing according to the various suggestions already made.. and improving the master project in my timeline, many factors justify it.

**Comment by pmoorman** [comment]
Closing this, because the work is completed (hurray!)
