### ISSUE TITLE
Translate blockchain interviews Lawrence lerner ceo of pithia in French

### ISSUE THREAD

**Issue by truffard** [rchain/bounties#654]
issue 

# **Original (English) Content with subtitles in French**
https://www.youtube.com/watch?v=G4fSrC-43GE

## Collaborators
- @truffard 

*Estimated Budget of Task:1000 $
*Estimated Timeline Required to Complete the Task: 3 days
*Measure of Completion 

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #653  ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by philipandri002** [comment]
Hello...
Can be assigned to carry out this task.

I think it is something I can really do

**Comment by truffard** [comment]
@philipandri002 si tu veux, tu peux traduire une vidéo d'environ 10 minutes aussi sur youtube et je te mettrais dans l'issue

**Comment by philipandri002** [comment]
(if you want, you can translate a video of about 10 minutes also on youtube and I will put you in the show)

Merci.(Thanks)

**Comment by philipandri002** [comment]
@truffard s'il vous plaît avez-vous une vidéo spécifique que vous voulez que je traduise ou le lien de la vidéo youtube

**Comment by truffard** [comment]
@philipandri002 https://www.youtube.com/watch?v=lL8XtF2l-_o&t=203s

**Comment by lapin7** [comment]
It's OLD

**Comment by truffard** [comment]
@lapin7 laquelle est vieille? La vidéo que j'ai traduite a une semaine sur youtube

**Comment by lapin7** [comment]
Sorry, it's not old.

**Comment by truffard** [comment]
@philipandri002 tu t'en sors?

**Comment by philipandri002** [comment]
oui, mais s'il vous plaît donnez-moi une semaine

**Comment by truffard** [comment]
@philipandri002 oui aucun souci à lundi....ça te dirait de prendre part à un plus gros projet de trad pour rchain?

**Comment by philipandri002** [comment]
Pls I just translate the video into French both in letters not on the video, I couldn't get a good video editor..

Maybe some one can just pick up the write up and do a video editing

Thanks

**Comment by philipandri002** [comment]
RChain Interview par Ashiton Addison avec le PDG Pithia INC Mr Lawrence Lerner.

Mr Ashiton: J'adore en savoir un peu plus sur Pithia Inc?

Mr Lawrence: Pithia est une société financée par un prêt de la coopérative RChain. La coopération de construction de la troisième génération blockchain base sur le calcul de processus mobile hautement évolutive à 40 mille transaction et il utilise mimspace pour essentiellement blockchain que vous pouvez faire une transaction en même temps.


Mr Ashton: très intéressant! Donc, je sais qu'il y a des problèmes de monde de crypto-monnaie avec l'évolutivité de blockchain comme BTC et etherum, ainsi la coopérative RChain résout-elle la solution dans l'environnement d'entreprise?

M. Lawrence: Absolument. Eh bien, la plate-forme a été construite très largement pour construire et favoriser un écosystème qui vous permettra de faire des transactions hautement évolutives, sécurisées et être en mesure de fournir concurremment par conception dans la règle et le langage qui a été tout de la terre.

Pithia, en tant que branche d'investissement, est à la recherche d'entreprises et d'entreprises à la recherche de solutions hautement évolutives. nous travaillons plutôt comme une société de capital-risque traditionnelle, mais dans l'espace blockchain, nous sommes très flexibles sur la façon dont nous faisons certaines transactions

M. Ashton: Donc, en tant qu'entreprise qui cherche à adopter la technologie blockchain, pourquoi devrais-je aller aux pithias et utiliser la RChain plutôt qu'une autre blockchain?


Mr Lawrence: RChain nous avons un écosystème phénoménal de développeurs et d'autres partenaires. Une des choses que nous avons fait est et vous savez que mon expérience a été dans le monde des logiciels d'entreprise et aider à lancer des plateformes sur Internet, je fais du développement internet depuis les années 80 et j'ai aussi lancé des sociétés de conseil. dans les années 90 et je pense que certaines leçons apprises sont vos choses fondamentales, votre dépendance que vous devez faire. La première chose que nous examinons est le portefeuille, les échanges, les solutions d'identité. Les choses que vous allez faire des millions de fois par heure, si vous allez réussir avec n'importe quel type de scalable

**Comment by philipandri002** [comment]
If this us approve I will post the last section of the interview@truffard

**Comment by truffard** [comment]
@philipandri002 tu te trompes de vidéo;j'ai déja traduit celle la. Il faut que tu télécharges la video et que tu la upload sur ta chaine youtube, et de la tu pourras ajouter des sous titres...ce n'est pas difficile

**Comment by truffard** [comment]
@philipandri002 voila la video à traduire https://www.youtube.com/watch?v=lL8XtF2l-_o&t=203s

**Comment by Pionelle** [comment]
Voir l'étiquette de notre belle langue. 

I add it now to this issue

**Comment by philipandri002** [comment]
salut! Est-il possible pour moi de faire une traduction ou une conversion vocale de l'anglais vers le français?

s'il vous plaît ne pas offenser, juste demander?

**Comment by ICA3DaR5** [comment]
@Jake-Gillberg @ian-bloom @dckc @michaelizer @zero-andreou @lapin7 

Okay guys, what's the general sense on translating subtitles?

**Comment by dckc** [comment]
I'm confused... the issue description says It's important to translate because it's an RChain blog item. But looking at the RChain blog, I don't see it. Help?!

**Comment by ICA3DaR5** [comment]
@truffard You have posted that this is a RChain blog post. Since it's not I am closing this issue.

**Comment by truffard** [comment]
@ICA3DaR5 fine with me
