### ISSUE TITLE
Weekly "Vision of the Ecosystem" talks

### ISSUE THREAD

**Issue by allancto** [rchain/bounties#658]
**Purpose** 
One of the valuable resources we have is our weekly Community Debrief. The debrief lets everyone know what the new happenings with development groups, partners, and so on, and often visions of what may happen in the future. 

A weekly “Vision of the Ecosystem” series will serve a somewhat similar function. Each week we’ll invite representatives of new projects forming or contemplated, bound by the common thread of working in the RChain ecosystem. Many of these project may be ones that Pithia or Reflective have an active investment interest in, but any project would be eligible, limited only by time available. 

The format will be four short (10 minute) presentations followed by questions from the audience (5 minutes)- similar to an academic or “meetup” type format. The only background knowledge assumed will be knowledge of the RChain platform itself. We’d expect many of the talks to come from projects that Pithia and Reflective are investing in or reviewing, but that’s not a requirement. We’ll need some way of maintaining a list of potential presenters, and selecting 4 each week based on criteria such as: 
1. Clarity of presentation 
2. Importance to the ecosystem
3. Novelty of vision

These talks will stimulate the community to think about what’s possible, understand some of the details that explain what is the work to bring projects to fruition. The talks may serve to stimulate discussion within the ecosystem and provide onlookers with a view of what is happening now and what is likely to happen in the future. 

**Team** 
We will need sources to recommend possible presenters, @Lawrence, @kdvalentine and others in the community have volunteered to share their network of project contacts. We'll also have a "suggestion box" that anyone may use. We'll need help from both operations and marketing, @patrick727 can give us advice here. 

The core team will be 2-5 members of the community who will work cooperatively to sift through the suggestion box and curate. Because we want to reach a wide audience, these community members should be ordinary, "average" members of the community- well, no one is *really* average or ordinary, but hopefully we'll have broad involvement. Curators will have the responsibility to view submissions and select 4 each week for presentation (as well as coordinate schedules and so on). 

**Suggested Reward**
$200 for each presenter, $50 per week for each community member curator, total of ~$1050 per week. Curators are expected to view all presentations submitted and participate with summary, comments/ analysis, and prioritization (time commitment ~5 hours/ week). Patrick and other members with staff roles in the community should support the effort but not be rewarded separately (to the extent that this is already part of their roles). 

**Time Frame**
Aim for first Vision of the Ecosystem session by late May (3 weeks from now). 

**Contact**
Members please contact me (here on github or @allanc on discord) if you are interested in participating. 

**Submissions and Curation**
Simple, initial submission process, currently just a [suggestion box](https://docs.google.com/document/d/1-v1KvCKxXKWmYTcZNudwuTYLiY9n2NBVPZq0KwE0R6c/edit?usp=sharing) with comment access.

--  \
***Disclaimer*** \
All work and rewards are subject to member review and budgetary oversight. Participation is NOT a guarantee of reward. 

***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by jasoncruzzy** [comment]
@allancto Beautiful idea but I want to know how this can work effectively without multi translation concerns. We have members(RAM) from various countries and divers languages,  how do we integrate every interested member representing new projects(forming or contemplated) into the 'eco-system'. If you have any provision on that please brief me(us)

**Comment by dckc** [comment]
@TrenchFloat "Dream team would be Patrick" suggests he's looking for help from a **Marketing** guide more than operations. (btw... referring to him as @patrick727 should cause github to notify him.)

And this blurs between Meeting and Event... I think perhaps it's more of a proposal for Events.

**Comment by dckc** [comment]
@allancto please [avoid "click here" links](https://www.w3.org/QA/Tips/noClickHere).

**Comment by allancto** [comment]
@jasoncruzzy I think @kitblake is looking at the translation issue, please contact him and let me know the result. Thanks! -Allan

**Comment by jasoncruzzy** [comment]
Ok i will do that

**Comment by allancto** [comment]
Thanks @jasoncruzzy !

**Comment by pmoorman** [comment]
@allancto sounds like a great idea to me. I'd love to see what kind of things people are building on RChain, or even hear 10-min pitches of _ideas_ that could be built on RChain.

What are the next action items here?

Maybe you could create a "pilot" like with television series, and see if this is the next GoT in the making?

**Comment by Ojimadu** [comment]
Any update on this?

**Comment by kitblake** [comment]
This looks like an event in need of organizers. But they're all busy with other things. 
Shall we close it? For now..

**Comment by AyAyRon-P** [comment]
@allancto 

Are there any updates to this project? Do we need to add anything or can we close this out and archive the links in the issue?

**Comment by Ojimadu** [comment]
Am inclined to close this issue for now because it looks stalled. Anyone willing to work on it feel free to reopen.

**Comment by allancto** [comment]
Thanks all for commenting. I've dropped the ball here but will consider reopening in the future. Anyone with ideas and a desire to participate please contact me!! Thanks! -@allancto
