### ISSUE TITLE
HashNode - Engagement: Developer Community. 

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#665]
### For all issues
[Keep italic labels, replace brackets with answer]

*Basically looking at attracting more attention to RChain with slight bias towards  RChain's language and node testing sections. HashNode is a friendly and inclusive developer community. People ask questions, write articles, discover and share links. Don't miss out, join the network.* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

*Estimated Budget of Task:* **$[]**  \
*Estimated Timeline Required to Complete the Task:* **[50%]**  \
*Measure of Completion:* **1 - 5 weeks**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by dckc** [comment]
I don't understand what you mean by "forseeable" as a Measure of Completion. The Measure of Completion should be an objective way to measure whether this task is complete; for example:

 - [ ] Engage 10 members of  the HashNode community in RChain node testing.

Likewise "ongoing" is insufficient. When do you expect to achieve your goals? Make some estimate, please.

**Comment by azazime** [comment]
@ResonanceXX this a brilliant issue to bring up but you have to be more precise in your setup. Thanks

**Comment by ResonanceXX** [comment]
@dckc I actually could not state that the profile is ready. And like every other thing @resonanceXX does, i tend to work through the motions. I will be posting questions and articles unto the HashNode page, from the responses generated, then the traffic could then be estimated. There isnt any sure-fire way of reaching out to X amount of people, with out first setting out.
The time frame - forseeable, unlike #197 here I have @kencode doing this also. Since two individuals cannot work in similar ways, I like not put words in his mouth as regards completion. 
On my part however, i have made 

- Series of non-technical questions to shade  a bit of light

- Have the profile set up @HashNode

- Created this issue on Github

- Only just woke up this morning. Haha. Cheers.

**Comment by ResonanceXX** [comment]
![screenshot-2018-5-7 why should i code - inbox - yahoo mail](https://user-images.githubusercontent.com/34219332/39701890-ccbbfb72-51fa-11e8-9bdc-daacedadc277.png)

**Comment by ResonanceXX** [comment]
An example of the sort of content on Hashnode.

**Comment by ResonanceXX** [comment]
https://hashnode.com/post/who-has-a-good-review-of-rchain-and-their-rho-lang-language-cjgwbz4tw00dpj4s133xmam4m

**Comment by dckc** [comment]
@ResonanceXX writes:
> ... i tend to work through the motions ...

Working out the objective incrementally makes sense... and "1 to 5 weeks" is useful. But I wouldn't expect to see a budget number until the objective ("how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain") is more clear. I don't support a $1500 budget based on what I see so far.

**Comment by ResonanceXX** [comment]
I personally think that equating the work done, to the stated budget - both (so far) is hasty. Because all of the work is done in the future. And the budget is set out for the future. 
And that the implementation of this work is not dependent on the budget, most times budget placing is a formality. 
Additionally, the potential for this to grow is a reality. (Reference Quora a bit)

@kencode brings with him plenty of enthusiasm.

**Comment by Kencode7** [comment]
Building & implementation process of this task;

1. Discussing Rchain on Hashnode predisposes the developers community to the beauty of Rchain blockchain
2. New developers show up asking for the best language to start with especially on the Blockchain community, we can introduce them to Rholang, & Rnode testing by posting articles from the Rchain developers forum.
3. We plan to have a Rchain Community on Hashnode (this process has already kicked off, the link posted already by @ResonanceXX )

With these we tend to bring Rchain community to a wider developer community
We welcome more suggestions from members.
thank you! @dckc

**Comment by Kencode7** [comment]
S.M.A.R.T Engagement on Hashnode
[Here](https://hashnode.com/post/who-has-a-good-review-of-rchain-and-their-rho-lang-language-cjgwbz4tw00dpj4s133xmam4m#cjgxlu8t3001hijs2adjaytjq)

**Comment by dckc** [comment]
I don't see how that link is relevant to the S.M.A.R.T. criteria:

Specific – target a specific area for improvement.
Measurable – quantify or at least suggest an indicator of progress.
Assignable – specify who will do it.
Realistic – state what results can realistically be achieved, given available resources.
Time-related – specify when the result(s) can be achieved.

**Comment by Viraculous** [comment]
@ResonanceXX, You have a great idea but I think this issue isn't smart enough or perhaps I don't get you well. 
Whats the targetted intent of the issue or what is the issue meant to actualize?
whats the roadmap to reaching this target or say measures to be employed in getting to the desired goal?
Who and who do you deem competent to meet the expected target?
what is the measure of success to the target?
What is the time frame?

How about getting in touch with the developers and having them on-boarded on the RChain platform while we Keep the trend on the RChain community ongoing upon the Hashnode's community?

**Comment by ResonanceXX** [comment]
Okay fine. Allow me to get the work done. Complaints aside that is. I am submitting to all criticisms.

**Comment by ResonanceXX** [comment]
https://hashnode.com/post/who-shares-the-same-experience-using-rchans-test-node-rnode-v031-are-the-improvements-currently-visible-and-applicable-cjh8bps0s000ifos12smoo0vu


Lets all jump on this maybe?

**Comment by ResonanceXX** [comment]
So this about expressing the progress made, using Nash Foster's excellent delivery on the RNode release. Medium is a fine venue for readers. Hashnode going by the discussions there, seems like a very fine niche for developers. So yeah, looking at pulling a dozen, hopefully.

**Comment by ResonanceXX** [comment]
@Kencode7 How has this gone so far?

**Comment by mmaksimovic** [comment]
Hi @Kencode7 @ResonanceXX @dckc @Viraculous @azazime  

My name is Milica and I am the Hashnode Community Manager. What you're discussing here goes directly against our policy and we're going to take the following steps:

-  Delist all posts that mention RChain,
-  Ban all the fake registered profiles that were involved in this process.


You're free to engage with the rest of Hashnode community as long as you follow our rules. Our platform was always free for use and we won't allow anyone to profit from promoting any services.

I'm here if you have any questions.

Regards,
Milica Maksimovic

**Comment by pmoorman** [comment]
@mmaksimovic it's good to see you here, and welcome onboard the RChain community. (btw, how did you find out about us?)

I don't know if anyone has responded to you so far, but given the silence here let me write something. I think -- as a community -- we weren't quite aware that the actions of a member were against the rules of the HashNode platform, and our apologies for that.

We hold a call every month or so to discuss issues as they arise building out the bounty program, and I'll add this topic to the call for this Friday, so at least we can discuss it internally. I hope we'll be able to work out a way to avoid such behaviour in the future.

cc @dckc @deannald

**Comment by mmaksimovic** [comment]
@pmoorman thank you for writing back to me. Please refer to https://github.com/rchain/bounties/issues/887 , as it is directly connected with this issue. 

We have an anti-spam policy set in place and we do allow people to promote what they're working on as long as they provide value and don't spam our users. 

One of your promoters spammed our platform and continued doing so after we've warned him. (I guess because he could earn money). He even made fake profiles and con.

Due to this fact, we've banned him from mentioning RChain and are considering setting up a ban for RChain completely.

Please get back to me when you're finished with discussing this internally.
