### ISSUE TITLE
Blog post: Interview summary.

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#668]
[Blockchain Interview](https://www.youtube.com/watch?v=PJYEI2rIC_c) with Lawrence Lerner Ceo of [Pithia](http://pithia.com/)
- [x]   Write textual run down. [HERE](https://docs.google.com/document/d/1cCx1V4MXaljmOQZMvj1nxIp8t8SjjMklPe4B-1mZjQc/edit?usp=sharingurl)
- [ ]   Upload to RChain medium
Suggested Budget: $200

**Comment by philipandri002** [comment]
Viraculous@ I had to support your write up so as to give the audience a clearer view for people with different understanding background.

Thanks

**Comment by jasoncruzzy** [comment]
@Viraculous It is necessary this part of the interview be included; POSSIBLE IMPACT OF RCHAIN ON A DECENTRALIZED APPLICATION(Dapp) i sent it to you via the 'suggestions' icon
