### ISSUE TITLE
Translate video "Crypto Talks" on Rize: Kenny Rowe (COO of RChain)" into french

### ISSUE THREAD

**Issue by truffard** [rchain/bounties#671]
### For all issues
# original english content with french subtitles, as requested by @lapin7 on telegram
https://www.youtube.com/watch?v=cjHooZc0JNM

## collaborators
@truffard
@niwaa 
@lapin7 

Me and @niwaa are both french and have lived and worked extensively in the US, we can deliver a quality product in a timely fashion.
*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

*Estimated Budget of Task: $3000 
*Estimated Timeline Required to Complete the Task:10 days
*Measure of Completion:* **[measure]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Pionelle** [comment]
@Truffard 
Tout va bien. Bonsoir

**Comment by Pionelle** [comment]
Je ferai bien dans la relecture de ce travail 

Well done guys

**Comment by truffard** [comment]
@Pionelle finis tes documents s'il te plait dans les issues précédentes, c'est loin d'etre parfait!!

**Comment by Pionelle** [comment]
La relecture vient après.

Vous vous trompez. Je peux les travailler avec votre aide. Et soyez ici pour vous aider aussi. c'est un droit **coopératif?**

But I understand. Maybe I get too excited.

**Comment by philipandri002** [comment]
@truffard S'il vous plaît monsieur, pouvez-vous ajouter un collaborateur avec une tâche d'écriture des mots, puis laissez-moi juste modifier la vidéo

merci, je serai vraiment reconnaissant si vous pouvez me considérer ..

**Comment by niwaa** [comment]
@philipandri002 Sorry but I can tell you are not a French native, by reading your comment.

**Comment by philipandri002** [comment]
@niwaa but that doesn't limit me.. 

When we go for business trip we do not go with native interpreters but one with a highly level of usage and understanding of the languages been required.. 

So please I can still participate my quota..

Thanks

**Comment by lapin7** [comment]
Only native French speakers are allowed to translate.

**Comment by Staff91** [comment]
Hello @lapin7 ! Should we translate this video to Italian?

**Comment by lapin7** [comment]
Please ask @ICA3DaR5, @zero-andreou

**Comment by Staff91** [comment]
@lapin7 Thank you! 
@zero-andreou What do you think about it?

**Comment by zero-andreou** [comment]
@staff91 I will consult with @ica3dar5 and get back to you. We created some subtitles 2 months ago and they still haven't been uploaded, so we're trying to figure it out.

**Comment by Staff91** [comment]
@zero-andreou We already know that the translated subtitles haven't been uploaded @ICA3DaR5 and that's why we created an italian youtube channel so that we can upload the subtitles there.If there are already english subtitles for any important video like that above, we can translate them to italian with a budget around 1200$.What's your opinion about it?

**Comment by ICA3DaR5** [comment]
@truffard How's this a Medium blog item?

@Staff91 Open a new issue.

**Comment by truffard** [comment]
@ICA3DaR5 i thought it was as this translation was requested by @lapin7 .Me and @niwaa will deliver in about 2 or 3 days

**Comment by ICA3DaR5** [comment]
@truffard What's the status of this?

**Comment by niwaa** [comment]
This has been completed. Translation is done and was uploaded to the French Rchain youtube channel.

**Comment by Pionelle** [comment]
Can you post a link to the youtube video here?

**Comment by ICA3DaR5** [comment]
Is [this](https://www.youtube.com/watch?v=4GxheRH7Ql8) the one?

**Comment by truffard** [comment]
@ICA3DaR5 yes it is

**Comment by ICA3DaR5** [comment]
Closing this since it seems to have been completed.

**Comment by truffard** [comment]
@lapin7 its all set me and @niwaa already voted...
