### ISSUE TITLE
Find 3 guides / "peers" for each functional area of the bounty system

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#672]
One of the conclusions from the implementation of guides for the bounty system, is that we need some redundancy in the system. Ideally, each functional area (development, marketing, etc.) have 1 guide to act as the "designated driver", and two other peers to assist and help vote for issues.

**The goal of this issue** is to identify at least a 2nd and ideally also a 3rd guide for each functional area.

**Measure of completion:** 
3 guides for the following areas, synced with [Labels](https://github.com/rchain/bounties/labels):
- [ ] branding (lead: @pmoorman, @AyAyRon-P)
- [ ] development (@dckc, @Jake-Gillberg )
- [ ] education (lead: @TrenchFloat, @Viraculous)
- [x] greeter (lead: @makys, @pmoorman, @Ojimadu)
- [x] marketing (lead: @pmoorman, @kitblake, @AyAyRon-P)
   - [ ] China (lead: ???)
   - [x] Africa (lead: @David405, @keaycee @JUANITA-MAYBEL @Valentine-Mario )
   - [x] Social media (lead:  @@Keaycee ,@Viraculous @Valentine-Mario) 
   - [ ] Events (lead: @Ojimadu )
   - [ ] Russia (lead: ???)
- [x] member-site (lead: @ian-bloom, @kitblake, @dckc, @Andrekuipers )
- [x] translation (lead: @AyAyRon-P, @pavlos1851, @zsluedem )
- [x] voting (lead: @Jake-Gillberg, @jimscarver, @allancto)
- [ ] governance (lead: @jimscarver, @barneycinnamon)
- [x] operations (lead: @lapin7, @TrenchFloat, @jimscarver )

Plus:
 - [ ] guides are effectively reviewing new issues (Task Identification Forms)
 - [ ] guides have sufficient trust metric weight to influence budgets and rewards

Budget:  ???

***Legal***
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by pmoorman** [comment]
To start off with some suggestions:

1. Branding should probably have Jonathan & Patrick as 2nd and 3rd guides (since the 3 of us make up the branding WG, which has the best view on all branding-related efforts)

2. @kitblake for the member website seems obvious. (and maybe @Andrekuipers since he's the actual developer on it, so it's helpful for prioritization)

3. @ian-bloom and myself could second for the "greeter". Maybe also @kitblake if he wants to.

---

Oh, and maybe I'm missing labels like "operations" and such...?

**Comment by ResonanceXX** [comment]
@pmoorman. 

Marketing. If there is a slot available. I will to give that a shot. Cheers.

**Comment by dckc** [comment]
I'd be happy to see Jonathan and Patrick pitch in, but I'd like to think you could farm out more of the routine work to people with less key roles in the organization. As I'm typing this, @ResonanceXX chimes in; I suggest a 20 minute call or two to sync expectations could get things going for the next little while.

Likewise, I'm not sure I want to ask Kuipers to do project managment. Ian actually asked me to help with member-site project management, and I agreed. So put me down there along with Kit.

By the way... the list belongs in https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ; if we're going to keep a list here, they need to point back and forth.

**Comment by dckc** [comment]
This is not a change to the bounty contract.

**Comment by dckc** [comment]
Oh... I guess the [Labels][] page is another source of this info... ugh.

[Labels]: https://github.com/rchain/bounties/labels

**Comment by dckc** [comment]
Sorting Labels by most issues, some observations:
  - **Marketing** has 84. Merits some combination of a small army of guides, a regular meeting for review, or subdivision into sub-areas. (e.g. social media promotion)
    - Since we have a guide for **Events** (@Ojimadu) , we could take Marketing off the 3 that have both labels (much like I did in the case of Translation some time ago)
  - **China** has 23 open issues but, as far as I know, no guide. @llerner ?

**Comment by barneycinnamon** [comment]
Chuckling, because this issue is tagged Governance and Operations, but lists neither one as areas that need guides. I'll edit the initial comment to add those.

**Comment by pmoorman** [comment]
thanks all for chiming in!

- Good point to not tie up Jonathan, Patrick and other key players if it can be avoided. For branding I would suggest @AyAyRon-P might be interested?

- How about @TrenchFloat to complete the triplet on "operations"?

- @barneycinnamon how about "governance"? Wouldn't you want to play a role there?

- I'll add myself to greeter.

I'll think about how we can maybe break marketing into subsets to make it more managable.


**P.S.** If anyone is reading this and thinks _"darn, I would like to do something but not sure which..."_ then please comment here or write me a note on Discord.  I didn't think of @ResonanceXX for marketing for instance, but happy if he can help!

**Comment by kitblake** [comment]
You can put me on branding as well.

**Comment by David405** [comment]
@pmoorman I would love to help out in marketing

**Comment by David405** [comment]
@pmoorman @dckc I feel marketing be divided into sub-categories which should be based on media, region, platform. It would be make tasks surrounding marketing a little more organized.

**Comment by David405** [comment]
Just in case the marketing position isn't available, I wouldn't mind helping out in education or governance

**Comment by ICA3DaR5** [comment]
For translations I may suggest: @zero-andreou, @michaelizer,  ? Are you up for it guys?

**Comment by TrenchFloat** [comment]
I'll definitely work on Operations. Putting my name in the initial comment - @pmoorman  If I'm the third, who is the second?

@David405 Nothing says you can't be a guide for more than one area. Shall I put you down for education?

**Comment by AyAyRon-P** [comment]
Hey @pmoorman you can add me to Marketing and Branding segments

**Comment by kitblake** [comment]
@TrenchFloat I was thinking of it but now I'm in 3 and that's enough. And 3.

**Comment by zero-andreou** [comment]
@ica3dar5  i'm in!!

**Comment by barneycinnamon** [comment]
Added myself to Governance and AyAyRon-P  to Marketing and Branding segments

**Comment by TrenchFloat** [comment]
@kitblake I'm not sure I understand your comment. Are you opting out of guiding the Ops issues?

**Comment by ICA3DaR5** [comment]
@michaelizer Great!

**Comment by kitblake** [comment]
@TrenchFloat Yes, I'd prefer to take on branding instead. Sorry if that was cryptic.

**Comment by dckc** [comment]
It's great to see everybody pitching in. Something I think bears repeating:

> Bounty task guides ... are here to **align contributions with goals of the RChain cooperative**

For example, the budgets for Marketing issues should align with the recently approved marketing plan. I talked about this (along with Events) with @pmoorman and @PatrickM727 in 1-1 conversations, but I don't think we shared it explicitly with everybody else.

I make an effort to talk with Medha and others about how which development tasks should be high priority.

For Education, I'm encouraging @TrenchFloat to sync up with @KellyAtPyrofex, who is involved in a lot of documentation stuff.

@barneycinnamon and I lamented that it's challenging to figure out where to go for Governance priorities for the coop as a whole. We're brainstorming on how to interface with the board of directors. (I suppose I'm on the executive committee ...)

For Operations, @lapin7 is right here; likewise, **member-site** and **greeter** have large overlap with the bounty program already.

**Comment by casanwugo** [comment]
Great job guys,,, this looks very interesting. Would love to contribute. Thanks

**Comment by David405** [comment]
@pmoorman I edited your initial comment to include marketing subcategories based on region, media and platform, more can be including though.

@TrenchFloat @pmoorman since there is no longer a slot in marketing, I volunteer to be a guide in Africa issues and also a second or third guide in education.

**Comment by Andrekuipers** [comment]
@pmoorman I'm in for the member site.

**Comment by pmoorman** [comment]
Guys, I've added people based on the comments above.

- There are 4 guides now in "member website", but since @Andrekuipers is keen (and he's actually building the site), I think he should definitely be in there. Also makes it easier for Ian, for instance.

- @casanwugo please be a bit more specific. What expertise do you have? Where would you like to help?

---

@dckc said: 

> Something I think bears repeating:
> 
> > Bounty task guides ... are here to align contributions with goals of the RChain cooperative ... -- Bounty Task Guides
> 
> For example, the budgets for Marketing issues should align with the recently approved marketing plan. I talked about this (along with Events) with @pmoorman and @PatrickM727 in 1-1 conversations, but I don't think we shared it explicitly with everybody else.

I plan to make a separate issue to "translate" the big marketing plan into actual deliverables for the bounty system. That way we'll have that connection you're talking about.

I think also it might be worth to create an issue to set "tenets" for each functional area on what kind of contributions we're most looking for. I plan to create both those issues when I have a bit more time & focus.

**Comment by jasoncruzzy** [comment]
@pmoorman  If the slot for 'social media' is still available, I will love to help out in that aspect of 'marketing'...Great Job Man

**Comment by entropee** [comment]
I want to join the part of the social media team that helps with discord, telegram, mattermost, etc. I see that as broader than just marketing, however.

**Comment by philipandri002** [comment]
@pmoorman since I am a social media online strategist and marketer, I would love to be assigned to carry out such responsibility.. 

My  idea is to get broadcast RChain on social media thereby creating the much needed attention and understanding that will make RChain a recognised block chain..

Waiting for a quicker response..the link is a proof of of one of the publishing RChain on social media and this has gotten several people reaching out to me for clarity.

**Comment by casanwugo** [comment]
@pmoorman,,, thanks for the response! I am available to assist in the African guide, as well as education.

**Comment by casanwugo** [comment]
I'd like to assist @David405 in the Africa lead,,, and also @Ojimadu in Events. Thanks

**Comment by JUANITA-MAYBEL** [comment]
@TrenchFloat I would love to help out in Education.
@pmoorman I would also love to assist in the Lead for Africa

**Comment by Keaycee** [comment]
@pmoorman It's a very nice idea. I can take on the **social media** and also assist in leading the African communities. I already created some [Facebook](https://web.facebook.com/rchaincooperativeafrica/) and [Twitter](https://twitter.com/RChain_Africa) channel for the up coming RChain web forum. see issue #662

**Comment by kaka56** [comment]
@pmoorman  I can assist in education and social media.

**Comment by Viraculous** [comment]
@pmoorman, I would be glad to be among the leads on Social Media platform and Education. I have already strategized on the techniques to publicize RChain platform to the audience, reach out to influencers of technologies and get them on-boarded.

**Comment by dckc** [comment]
Based on discussion here and in #616 and #644, I turned the trust metric on, provisionally, for **201805**.

**Comment by zsluedem** [comment]
@pmoorman Since there is on one else in China involved with the lead of marketing in China., I'd love to do a favor with that. I am not a really marketing guy.(I am more into the development), but try to do my best of it.
Do we still have to have 3 leads in the marketing area zone?

**Comment by dckc** [comment]
I notice that at least a few of the people who have volunteered to serve as guides are not among the [people certified by the trust metric][1]. If you're not certified, you won't be able influence budgets and rewards if/when we use the trust metric (#375).

Two suggestions:
  1. Edit your github profile to tell us about yourself; use the URL to point to a site with your resume or the like (e.g. linkedin).
  1. Go back and edit the comment where you volunteered and add pointers to work you have done that qualifies you for the role.


[1]: https://rewards.rchain.coop/index.php?-table=authorities&-action=list&-cursor=0&-skip=0&-limit=30&-mode=list&-sort=rating+desc

**Comment by David405** [comment]
@dckc I have added a URL to my LinkedIn on my github profile

**Comment by David405** [comment]
@dckc I have added a URL to my LinkedIn on my github profile

**Comment by jasoncruzzy** [comment]
@dckc I have added a URL to my LinkedIn on my github profile as requested.

**Comment by Valentine-Mario** [comment]
@pmoorman  I would like to be involved in development and social media

**Comment by allancto** [comment]
@Jake-Gillberg @pmoorman  I would like to be added to voting

**Comment by allancto** [comment]
Anyone working as a lead guide or even as a guide: I will personally vote to slash the budget for this issue #672 if we don't get support on #678. It needs to be a duty of the lead guide for each label to responsibly articulate to our membership and our board- supported with data- the contribution each label is making to the RChain Cooperative and the RChain Community. 
/cc @pmoorman @dckc @TrenchFloat @makys @ian-bloom @Jake-Gillberg @jimscarver @lapin7 @PatrickM727

**Comment by casanwugo** [comment]
@dckc I have added a URL to my github profile. Thanks

**Comment by pmoorman** [comment]
Hey all, I stated as the goal of this issue:

> The goal of this issue is to **identify at least a 2nd** and ideally also a 3rd **guide for each functional area.**

Seems like we've successfully done that! Some sub-labels of marketing still require guides, and some functional areas lack a 3rd guide, but I think it's good enough for now to start looking for next steps.

For now I'll leave this issue open for another week or so, and after that it can be closed.

**Comment by dckc** [comment]
I added a few more goals:

### Guides are effectively reviewing new issues

I added a [Task Approval Overdue](https://rewards.rchain.coop/index.php?-table=task_approval_overdue) tab to rewards.rchain.coop. The idea is to find Task Identification Forms with insufficient feedback after five days. It currently shows **68 overdue issues**.

By filtering on labels (much like searching for issues by number), I find 7 [overdue Development issues](https://rewards.rchain.coop/index.php?-table=task_approval_overdue&-limit=30&issue_num=&title=&state=&days_old=&weeks_old=&labels=Development&createdAt=&updatedAt=) (after I cleaned up a few :). Each guide can do likewise for their area. Just 9 in **Marketing**. Good job pruning, @pmoorman !

The exact logic is issues without any budget votes where...
```
  where i.updatedAt < date_sub(current_timestamp, interval 36 hour) -- issues discussed in the last day or so are excused
  and ((i.state = 'OPEN' and i.labels not like '%"needs-SMART-objective"%')
       or 
       (datediff(current_timestamp, i.updatedAt) < 60  -- closed / updated in the last pay period or two
        and i.labels not like '%"invalid"%'
        and i.labels not like '%"wontfix"%'
	and i.labels not like '%"duplicate"%'))
```

### Guides have sufficient trust rating to influence budgets and rewards

As noted above, guides without trust ratings can't directly affect budgets and rewards, so I added a goal about this.

### Sync with Labels

The list of guides ultimately belongs in the Label descriptions so that they are shown as people are selecting labels for an issue, so I clarified that our list should be sync'd there.

**Comment by ICA3DaR5** [comment]
Added @michaelizer as a translation guide, since he has already been assigned as a guide on the "Translation" label.

**Comment by dckc** [comment]
@Jake-Gillberg , @lapin7 , would you please review [@zero-andreou's contributions][1] and certify him if you think it's appropriate? I'm not much of an expert in translation, but his work looks pretty good, and he's helping @ICA3DaR5 with guiding Translation, so for now, I certified him as **journeyer**.

[1]: https://github.com/rchain/bounties/issues?utf8=%E2%9C%93&q=is%3Aissue+assignee%3Azero-andreou+

**Comment by TrenchFloat** [comment]
For budgeting/rewarding: I took the [minutes](https://docs.google.com/document/d/1NbEku_ye40H0WTBA3-7YibtjYuSFvbq_BDxk4e-900E/edit?ts=5b005aa4#) and participated in the 5/25 "guiding guides" meeting, as well as maintaining Education issues. We're still looking for someone with the bandwidth to guide Ops issues fully.

**Comment by barneycinnamon** [comment]
Just wanted to shout out to the folks who put together the Rhobot.glitch.me tool. It is a tremendous crutch for me as I attempt to be a halfway decent label guide.

**Comment by dckc** [comment]
@barneycinnamon to support rhobot.glitch.me, vote for rewards on #609 .

**Comment by dckc** [comment]
@TrenchFloat you said you're struggling to keep up with **Operations** and that @jimscarver nominated @entropee , but you haven't managed to contact him. @jimscarver suggested the next peer learning meeting, Monday Jun 4 at 4pm ET (5pm CT) might be a good place to catch him.

**Comment by kitblake** [comment]
I did some label cleanup including slight rename conventioning of the labels: 
- Functional areas (Development, Marketing, etc., which have guides) are capitalized.
- Other labels (e.g. meeting, french, wontfix, etc.) are lowercase.

**Comment by ICA3DaR5** [comment]
I am removing myself as a lead guide. I am proposing @zero-andreou and @michaelizer to continue the work.

**Comment by kitblake** [comment]
@ICA3DaR5 Donald, sorry to see go. Are you feeling a bit burned? 
Bad joke, I know. But guide burnout is a problem we've anticipated, and haven't found an answer yet.

**Comment by ICA3DaR5** [comment]
@kitblake No, I am not burned, I am taking a break for personal reasons. @zero-andreou and @michaelizer are very capable people and I trust them 100% to do great work. I might get back on the task once I feel like it.

**Comment by ICA3DaR5** [comment]
Okay, so me, @zero-andreou and @michaelizer had a conversation on the translation guides.

We decided that @michaelizer is the best choice for a Lead Guide, and myself and @zero-andreou will follow along as guides. Is that okay?

**Comment by dckc** [comment]
Regardless of your role going forward, @ICA3DaR5 , thanks for your contributions so far!

**Comment by pmoorman** [comment]
@allancto let's spin the comment above (about the need for translation/localisation/regionalisation) into it's own issue. 

I have my thoughts on that, as do many others, but I don't think this is the right place to discuss it!

**Comment by zsluedem** [comment]
@allancto agree with low priority for translations.Start another issue to discuss it. I remember it seems there was some discussion before.Let me check.

**Comment by allancto** [comment]
@pmoorman @zsluedem @Viraculous @David405 yes, I agree with what you all have been saying. As we ourselves become more knowledgeable and experienced, we should be "upping our game". We should be not rest on our laurels, we should be able to add new kinds of value to the work we've been doing. How can we make what we do always more productive? Better tools for doing it? New initiatives? Research into what our Cooperative requirements are? Continuously improving our own skills?

**Comment by BelovedAquila** [comment]
@pmoorman I have an interest to assist in guiding Education,Meeting and Africa

**Comment by ICA3DaR5** [comment]
I am stepping down on the Translation label as a guide. I think it would benefit the co-op for the guides to rotate. I hope my work here as a guide helped both the co-op and the community. I am pretty sure other people can do the work, especially now that the heavy workload has already been done.

**Comment by zero-andreou** [comment]
I will also be following on @ica3dar5's steps. I will have focus on other work, therefore I won't have the time to properly work as a guide.

**Comment by pavlos1851** [comment]
I am interested in becoming a guide in the translation label . I am familiar with the workflow of the the translation guides and I am up for it.

**Comment by qelentium** [comment]
Im interested in becoming translation guide too, if its still on

**Comment by ICA3DaR5** [comment]
After chatting with @zero-andreou and @pavlos1851 I think he has the technical knowledge of being a guide on the Translation label.

**Comment by dckc** [comment]
@qelentium you (and everybody else) are more than welcome to do some guiding at any time. You would need a trust rating to affect budgets and rewards though. Recall last time you asked me about that, I asked how your work reviewing the arch doc (#580) is going :)

I see @AyAyRon-P is listed in the label description. @ICA3DaR5 did you put that there? Has he agreed to guide translation? If not, please add "nominated" or some such.

p.s. I wonder if it's better to discuss Translation guide rotation in #483.

**Comment by ICA3DaR5** [comment]
@dckc Yes, after chatting with him he did agree. He is very trustworthy IMO.

**Comment by AyAyRon-P** [comment]
There was an opportunity to talk through the needs and expectaitons with @ICA3DaR5 of the translation label guides when reviewing some marketing material and I'm glad to now be part of the translation label guides. I think it's better to keep the translation issues with translation #483 as @dckc suggested.

**Comment by zero-andreou** [comment]
I removed @michaelizer from the Translation label as a guide as per his request.

**Comment by AyAyRon-P** [comment]
Thank you @zero-andreou 

@pavlos1851 I've added you on discord to create our Translation Label Guide Chat - is this you? 
pavlos1851#6292
