### ISSUE TITLE
Blog Post: RChain Cooperative on Hashnode

### ISSUE THREAD

**Issue by JUANITA-MAYBEL** [rchain/bounties#675]
Hashnode is a community and a home for programmers and developers where discussion of programming languages and other development are discussed. On Hashnode, there are lots of programmers and developers, who are yet to know about the new emergent blockchain development platform( RChain Blockchain ). RChain community has been growing steadily but slow across the world, there is need to create more awareness to developers and also steps on how they can get onboard on the RChain Community. I also think developers has more ability to create more awareness about RChain.

**Here is the [blogpost](https://hashnode.com/post/rchain-cooperative-and-how-to-join-cjgwyi73l0010r3s1qtzi7a1e)** 
 

*Estimated Budget of Task:* **$[800]**  \
*Estimated Timeline Required to Complete the Task:* **[[Completed]](https://hashnode.com/post/rchain-cooperative-and-how-to-join-cjgwyi73l0010r3s1qtzi7a1e)**  \
*Measure of Completion:* **[[Completed]](https://hashnode.com/post/rchain-cooperative-and-how-to-join-cjgwyi73l0010r3s1qtzi7a1e)**

**Comment by azazime** [comment]
I'll suggest a link be generated for RChain and posted on hashnode

**Comment by Keaycee** [comment]
It's a good job putting up the RChain Cooperative on hashnode with some briefing to enlighten some developers about the RChain Blockchain  and also how they can be on boarded. Good one @JUANITA-MAYBEL .  There is already a link @azazime

**Comment by TrenchFloat** [comment]
@JUANITA-MAYBEL can you elaborate on the $800 budget for both this issue and your Quora issue, which both look like copies of the www.rchain.coop site?

**Comment by JUANITA-MAYBEL** [comment]
The hashnode is a community for developers and it's part of the marketing plan to educate and onboard more developers to the community, The blog post is not only meant for the awareness of our new emergent blockchain development platform (RChain Blockchain), but also avenue for further questions from developers and non developers. The blog post has 76 views from developers and i think that is a good direction for awareness and education. In regards to the contents, i see it fit to let the public know more about the Bio of the executive members of  the new emergent blockchain development platform. I would also like to add more info on some of the Executive members.  The budget is an estimate, but i think it's worth it in future as i would be managing the blogpost and further questions arising from it. We can also work together as i'm concern in  educating and also marketing.

**Comment by TrenchFloat** [comment]
You're right that posts like these are great for awareness. I'm glad you're making them. As for the budget, the task you detailed in the initial comment was making the blog post. So we should create a budget for that, and if you spend a significant amount of time _maintaining_ the post/answering questions, you can reopen this issue and campaign to be compensated for that work afterwards - not up front.

I don't see much of a precedence in budgets for blog posts, so I'll propose $80 for 2 hours at $40/hr for this and #680. What do you think, @JUANITA-MAYBEL?
