### ISSUE TITLE
Retrospective Bounty Progress Report

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/bounties#678]
Compose a report of progress the bounty system has made to address the board's concerns on the benefits of the bounty system:

 -  [201804 Bounty Progress Report](https://docs.google.com/document/d/18TfJWqAREEyr0wQdGb_UOxrFVk4KOigdFgpf7bV2ZL8/edit?usp=sharing)

This particular report should cover everything from 201704 to 201804, but from now on perhaps quarterly or monthly reports will be composed in separate GitHub issues. See discussion in 20180509 [RAM Meeting]( https://www.youtube.com/watch?v=0zLdQxjZWQk) (beginning to ~22min)

The board is asking how valuable the bounty system is. They are also irritated by the repeated gaming for RHOCs, to the point of considering abolishing the bounty system. Regular reports have been suggested by many to show the board the value of the system.

The suggestion came up in the RAM meeting above to divide the reports into categories that reflect issue labels like marketing, development, etc. and to have the [guides for each issue label](https://github.com/rchain/bounties/issues/672) write about progress in their respective areas.

This report will pair with #637 in that the progress described will attempt to justify the expenses described in the financial data included.

--

*Estimated Budget of Task:* **$1650**
Development, Governance, Marketing, Translation, Operations: $150 each
Branding, Events, Greeter, Education: $100 each
Financial Data: $300 to @dckc for working with @lapin7 on creating an accurate accounting spreadsheet
Coordination: $200 to @TrenchFloat for directing efforts from label guides

*Estimated Timeline Required to Complete the Task:* **THIRD EDIT: June 8th**
June board meeting has been [postponed to the 14th](https://discordapp.com/channels/375365542359465989/396078336620888065), and TrenchFloat goes out of town on the 9th

*Measure of Completion:* **Report includes all categories mentioned in budget proposal, accounting data, and a conclusion, and is submitted to the board.**

 - [x] Operations section written @TrenchFloat
 - [x] Marketing section written @AyAyRon-P 
 - [ ] Formatting @TrenchFloat
 - [ ] Submit to the Board and Publish

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by allancto** [comment]
@TrenchFloat , great proposal. 
1. The suggested budget is described as 9*$150 + $450. Can you give some color as to what this represents? Why is the marketing portion 3 times the others, or in reverse, why are all the others all the same as each other? 

2. Is it likely that the rewards for this issue will be voted on by the same people who are assigned to it, would that represent a conflict of interest, and if not why not? 

3. Would it make sense to explicitly add some sort of simple financial reporting here? For instance the monthly report might contain total spent this month, with some color around the largest expenditures, and "guesstimated" future expenditures? 

4. Might we BEGIN with a Retrospective Report in exactly the same format as the monthly report but reporting on 12 months past data? This serves two important functions, 
- Orient the assignees regarding how the bounty program has functioned in the past
- Provide our membership with an understanding of the overall magnitude of the program, and the value it has provided to our cooperative. 

The budget for the Retrospective Report may be something like 2.5x=$4200 the budget for monthly reports, since it will involve looking at up to 12x the amount of data. The Retrospective Report may seem expensive at first blush, but it's only a small fraction of the expenditures of the bounty program overall and it will give us valuable insight into our past, and a preview of future reporting, for only 21% of the projected cost of reporting over the coming 12 months.

**Comment by dckc** [comment]
I see a significant overlap with #637; I hope we can combine efforts.

**Comment by allancto** [comment]
Dan, i think 637 is much more financial data oriented and this iiuc is about what value the coop receives and how projects are guided in the bounty system. I agree with @trenchfloat that this is an important part of bounty system governance.

**Comment by dckc** [comment]
@Jake-Gillberg I jotted down some notes on Dev work funded by the bounty program.

**Comment by allancto** [comment]
Y'all below are listed as the lead guides in defined label areas. At last week's RAM meeting I promised to summarize the "state of the bounties" so I'd like to get a preview of what's going on in your guided areas. I'm happy to do that one on one in discord dm or in a shared google document. @dckc you've already jotted down some notes for the dev label, are those available? 

Thanks for responding! 
/cc @pmoorman @dckc @TrenchFloat @makys @ian-bloom @Jake-Gillberg @jimscarver @lapin7

**Comment by dckc** [comment]
Yes, I put my notes in the doc as requested above. Please try harder to find stuff before asking me.

**Comment by allancto** [comment]
@TrenchFloat I agree with you on almost all of this. Imo $80 represents two hours of highly skilled work and is very appropriate to a monthly report as you said initially and again above, The exact amount of budget is, to me, secondary-- the reporting and engaging our membership is primary. 

As to the timing of our first retrospective report, I agree that July 15 may be appropriate for that. But monthly reporting must begin NOW. Members are questioning the value as well as resistance to gaming-  and we owe them transparency. 

The function of the report is to report progress, costs, and value to our Cooperative membership. It is our membership who are the sponsors and beneficiaries of the Bounty program, we deserve some kind of transparency as to why we are spending, how much we are spending, and what value is being created. Literally every formalized cooperative I know of has this kind of reporting: 

1. Financial summary (perhaps, spent this month, projected future, etc)
2. Breakdown into major subprojects 
3. Tracking summary of work product, viewpoint as to why the project is worthwhile, and so on

I'd like to be able to present these summaries monthly at the community debriefs. I'd like to follow Medha's format and introduce individual contributors, our guides, and so on. The bounty program is central to our notion of cooperative governance, and our Cooperative membership are the people we're working for. 

I agree with you that it should be the lead guides for each label. Lead guides should be compensated for this work, as you suggest. Success stories and progress may be presented every week, summaries every month. I suggest we change the title to "Monthly reporting by the Bounty Program to the Members of our Cooperative". 

The financial reporting requested by @lapin7 in #637 is not to be confused with the bounty system reporting we are obligating ourselves to here. #637 is about aggregate financial reporting within our whole cooperative.  This issue, #678, is about transparency within the bounty system. 

Lead guides, what do you think? Is @TrenchFloat 's issue a good way to provide budgetary and value transparency to our membership? Lead guides: @pmoorman @dckc @TrenchFloat @makys @ian-bloom @Jake-Gillberg @jimscarver @lapin7

**Comment by dckc** [comment]
@allancto how about you start the ball rolling on whatever form of reporting you find appropriate? That's the way collaboration works, right? Before you ask others to do something, you make some effort at it yourself.

**Comment by allancto** [comment]
Dan, good idea. I'm self assigned as the third guide on the "voting" label. My label happens to have only 6 issues, so it should be relatively easy to handle. How do i find out which ones have been rewarded, what the reward was and which pay period? Once i find that out, I'll read through each of the six issues and write my own summary and probably try to chat with one of the main people on the issue to see how it benefited or will benefit the cooperative. I think I can already speak for one or two of the issues. As far as I can tell they are all interesting issues and have benefited our Cooperative in ways that I know of (and none of them seem even to have required any budget!). @Jake-Gillberg , is it ok with you as lead guide if I prepare the coming report?

**Comment by allancto** [comment]
@pmoorman suggests another approach to the same problem, in #693 : "align effort/compensation with the goals of the RChain cooperative", starting from the "requirements" side.

**Comment by lapin7** [comment]
@allancto @dckc 
Here's a spreadsheet to play with.
https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=592953635

It has all data of Budgets and Bounties from August 2017 to April 2018

It's the base for a nice financial report.

1 mln RHOC was allocated for this program by @leithaus.

Total USD | Total RHOC
-- | --
$ 319,575.69 | ⍴ 862,209.14

**Comment by allancto** [comment]
@lapin7 , @dckc thanks for this spreadsheet, it's exactly what we need. Noticing expenditures in rhoc through April and the initial allocation, may also help explain a bit why this issue has been raised within our board at this particular time, the intent may be to enable the program to continue along with fresh allocation.

**Comment by Ojimadu** [comment]
I added a [report link](https://docs.google.com/document/d/1-khashTui6oJBdBD68lo2_MZUwFUianowgsz1JJ-mHc/edit) to the sheet above.

**Comment by dckc** [comment]
@Ojimadu that report has plenty of useful information, but it's much more detail than I would expect in this report. I'd appreciate if you would
  - [ ] move the detailed info to the respective issues
  - [ ] edit your contribution to this report down to less than half a screenful

**Comment by TrenchFloat** [comment]
@allancto 
> As to the timing of our first retrospective report, I agree that July 15 may be appropriate for that. But monthly reporting must begin NOW.

> Might we BEGIN with a Retrospective Report in exactly the same...

Could you clarify which report you think is more important to complete first?

Since I think writing the 12-month report first would be of more use to the board and the coop, I proposed the 12-month report by May 28th and the first *quarterly* report by July 15th. I'm going to start writing a 12-month report, and I would suggest everyone else do the same.


I will make a section in this doc for HJ's financial data.

**Comment by allancto** [comment]
@TrenchFloat that sounds exactly right. Apologies- I misunderstood you the first time. 12 month (or august to april since that's where our data is) May 28th is awesome, quarterlies or monthlies beginning July 15 perfect. Thanks for catching this @TrenchFloat !

**Comment by dckc** [comment]
@jimscarver mentioned

 - Problems encountered
 - Planned solution

in the context of this report. I think it's a good idea. Here's hoping we manage to include some of that as well.

**Comment by dckc** [comment]
@lapin7 How did you make that RAMb&b spreadsheet? I think I found a bug.

I merged that spreadsheet with Label info and it seemed to show substantial rewards on invalid issues, which looked odd.  But on investigation, I find the spreadsheet says @pmoorman was rewarded $1283 on 280 "Translate 20180131 Rchain Weekly Community Debrief 62 into Portugese" but rewards.rchain.coop has it as 522 "Website patch #1"

**Comment by lapin7** [comment]
> I find the spreadsheet says @pmoorman was rewarded $1283 on 280 "Translate 20180131 Rchain Weekly Community Debrief 62 into Portugese" but rewards.rchain.coop has it as 522 "Website patch #1"

I will look into that.

**Comment by lapin7** [comment]
I've exported issues from the rewards.app
Maybe something went wrong with sorting
Will export it again and see if it gives different results.

**Comment by lapin7** [comment]
I exported issues and rewards again from the rewards app. For the month March April.
And added it to the data from the spreadsheet Bounty. That contained data from Aug 2017 to Feb 2018.
[RAMb&r](https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=592953635) is updated now.

**Comment by dckc** [comment]
RAMb&r still doesn't look right to me. It has a March reward for the following but rewards.rchain.coop does not:

 - 334 O>Implement w3c verifiable claims api on RChain and their usecases worked out.

In fact, in RAMb&r pay periods 201803 and newer, there are 529 mis-matches (and only 21 matches with rewards.rchain.com data (based on pay_period, issue_num, and worker).

```sql
select count(*)
from ramb_b pay
left join reward r on date(r.pay_period) = date(pay.pay_period) and r.issue_num = pay.issue_num and r.worker = pay.worker
where pay.pay_period >= '2018-03-01'
and r.worker is null
```

**Comment by lapin7** [comment]
Thx for your analyses.

Please try again
[All Data](https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=1333494031&range=A1:E4)
[All Calc](https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=921691599&range=A1:E4)
[March April Data](https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=242222634&range=A1:E4)
[March April Calc](https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=1612998254&range=A1:C4)

**Comment by Barkov-F** [comment]
> (and only 21 matches with rewards.rchain.com data
@dckc Can you share the list of the lucky ones?

**Comment by TrenchFloat** [comment]
Looks like this won't be complete by Monday, so I'm postponing to June 2nd, three days before the board meeting on the 5th. Once the last few sections are written up, I will start working on making the info into a cohesive and argumentative report with a main message. I'm working with HJ on this and the coordination of the financial data.

Much of the discussion in the #bounties discord channel is relevant to this issue.

**Comment by dckc** [comment]
Yes, now all 555 reward records for March and April match between that spreadsheet and the rewards.rchain.coop database, @lapin7 .

**Comment by lapin7** [comment]
I've updated the spreadsheet RAMb&r
https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=1333494031&range=B4:E5

**Comment by dckc** [comment]
@lapin7 This update looks good from all the angles I have checked.

@TrenchFloat I think I'm done with [the Development section][1]. @Jake-Gillberg maybe you could take a look?

[1]: https://docs.google.com/document/d/18TfJWqAREEyr0wQdGb_UOxrFVk4KOigdFgpf7bV2ZL8/edit#heading=h.53k4w9k4o6yv

**Comment by lapin7** [comment]
OK,
Then I set the access for the spreadsheet [RAMb&r](https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=1333494031&range=B4:E5) for RAM's to edit again

**Comment by dckc** [comment]
recall from [May 25 meeting][1]:

 - @lapin7  will contact Kitblake to get Telegram metrics into the report.
 - @TrenchFloat will start an issue collecting metrics/analytics on youtube videos that reflect bounty program efforts.

[1]: https://docs.google.com/document/d/1NbEku_ye40H0WTBA3-7YibtjYuSFvbq_BDxk4e-900E/edit#

**Comment by TrenchFloat** [comment]
I revised my budget proposal and postponed the completion date (again) to June 8th, since the board meeting is now in the 14th (see discord Board2Coop channel, linked above).

@allancto, @jimscarver, we talked about leaving this unfinished in favor of making better reports in the future, but [I see people pushing](https://github.com/rchain/bounties/issues/616#issuecomment-392341466) for a report by the next board meeting, and the new June 14th date is close enough to our planned date for the second bounty report (June 15th) that we can finish this one in time. We're pretty close, too.

**Comment by dckc** [comment]
@lapin7 perhaps some version of the https://github.com/rchain/bounties/issues/261#issuecomment-361633354 story belongs in the report?

**Comment by lapin7** [comment]
@dckc yes. Let's add a summary to the report

**Comment by jimscarver** [comment]
I did a little editing and added stuff on education and governance.

**Comment by TrenchFloat** [comment]
Almost done! Meanwhile, @lapin7 has said he will send the report out to the board in advance of the June 14th board meeting.

**Comment by TrenchFloat** [comment]
I just wrote the Operations section and copied the marketing section from the separate doc that @AyAyRon-P was working in. Now all we need is the finishing touches from the Translation guides to resolve @dckc's comments (to come in the next few days), and formatting/editing for the whole document. I'm about to leave on vacation (until the 16th) and am looking for someone to do the latter...

**Comment by justinc667** [comment]
I rearranged the draft to make major sections more distinct through formatting and subheadings under them less eye-catching to help the contrast. I also posted comments I had about incomplete or hard to understand portions of the document so that there are opportunities to shore them up before the presentation of the report.

**Comment by lapin7** [comment]
Where's the final version to be send to the board today?

Is it this one?
https://docs.google.com/document/d/18TfJWqAREEyr0wQdGb_UOxrFVk4KOigdFgpf7bV2ZL8/edit#heading=h.xpbjkupkceyd

It still has DRAFT on it

**Comment by dckc** [comment]
Yes, @TrenchFloat confirms that's the one.

I suggest you dispose of the outstanding comments as you see fit and remove
DRAFT.

**Comment by dckc** [comment]
Um... Today? The meeting isn't June 14?

**Comment by AyAyRon-P** [comment]
@trenchfloat 

Did you get what you needed? I messaged you a copy to your discord. Let me know if you need anything else.

**Comment by lapin7** [comment]
> Um... Today? The meeting isn't June 14?

They need some reading time.

**Comment by jimscarver** [comment]
Is it time to close this issue?  I think we did a pretty good job and HJ's letter to the board was near perfect but lament I did not do more.  I got caught up with rhoc2rev and failed to add to the report a justification for the reward system addressing issues like in nature and culture of the coop, how member engagement augments hiring of employees in a positive manner and support the cooperative principle of economic participation, how the process can scale, and how it facilitates the emergence of collective intelligence.

We want to avoid our aspirations being lower than our leadership and give assurance that our decentralized governance avoids the chaos and polarization that destroys most attemps at decentralization, and will employ what have been shown to be effective patterns for decentralized organizations.
![decentralizationpatterns](https://user-images.githubusercontent.com/3037201/41509195-6df961b2-721e-11e8-8f18-ef4bb7f1c629.png)

**Comment by dckc** [comment]
@lapin7 can you get us a pointer to the minutes of the board meeting? Or would you like to summarize it?

@jimscarver writes:
> HJ's letter to the board was near perfect

What letter is that? Pointer?

> Is it time to close this issue?

Are all the follow-up items discovered in preparing and delivering the report captured in other open issues? For development, they are. I just reviewed the other areas and updated a few issues to match.

I'm inclined to keep this open until we have the outcomes from the board meeting captured.

**Comment by lapin7** [comment]
The board meeting of Friday, June 15, 2018.
The [201804 and 201805 Bounty Progress Report](https://docs.google.com/document/d/18TfJWqAREEyr0wQdGb_UOxrFVk4KOigdFgpf7bV2ZL8/edit#heading=h.94qzgjy9eyk0) was received, but the objectives and evaluation criteria were missing. Greg @leithaus  will formulate the objectives and evaluation criteria of the bounty program and in the month of June we need to implement the Task Force and create a system of metrics.

The payments of May will be executed. And the payments of June depend on the implementation of a successful system of metrics.

**Comment by Ojimadu** [comment]
@lapin7 By "task force" you mean the Task approval committee?  We're 2/3 into June already.

**Comment by lapin7** [comment]
@Ojimadu The train is rolling. So in the mean time the executive committee appointed a Task Committee. Members are: @dckc @deannald @PatrickM727 
Ask Them Anything!!!

**Comment by jimscarver** [comment]
@dckc the letter from HJ accompanning the report is [here](https://youtu.be/ofi9FeoW75Q).
H J
5:16 PM Jun 14
The report has been sent on Jun 14, 23:15 CET to the board with this message:

I 'm sending you the management report of the Bounty System that covers the history from the beginning to April 2018.

May is the first month that the trust metric takes effect. The result is "slashing" a lot of proposed budgets and rewards and like that we've managed to stay below the allocated budget. We've been developing transparency with increased reporting and visibility, we've been developing voting systems to prioritize butdgeting, and we will now develop valuation metrics that will allow us to contribute in alignment with our Cooperative needs. 

I hope you've some time to read it. This is the first management report, the next one will be better. I'm looking forward to your feedback.
