### ISSUE TITLE
Blog Post: RChain Cooperative & How to join the community on Quora

### ISSUE THREAD

**Issue by JUANITA-MAYBEL** [rchain/bounties#680]
Quora is a question and answer community, where questions are asked on every aspect of life, answered, edited and organized by members of the community. From statistics, it has above 100 million users monthly. The post will enlighten members on the new emergent blockchain platform and RChain beginners guide on how to join the community.

READ BLOG [HERE](https://rchaincooperative.quora.com/RCHAIN-COOPERATIVE-HOW-TO-JOIN-THE-COMMUNITY)

![screenshot 119](https://user-images.githubusercontent.com/37958082/39836613-4601aff6-53d4-11e8-9236-7966c00d8a4e.png)
![screenshot 120](https://user-images.githubusercontent.com/37958082/39836620-4e589174-53d4-11e8-968f-16091e04b118.png)

_Estimated Budget of Task:_ **$[800]**  \
_Estimated Timeline Required to Complete the Task:_ **[[Completed](https://rchaincooperative.quora.com/RCHAIN-COOPERATIVE-HOW-TO-JOIN-THE-COMMUNITY)]**  \
_Measure of Completion:_ **[[Completed](https://rchaincooperative.quora.com/RCHAIN-COOPERATIVE-HOW-TO-JOIN-THE-COMMUNITY)]**

**Comment by nonnykul** [comment]
A good concept you have there,will definitly want to be a part of it

**Comment by JUANITA-MAYBEL** [comment]
It's parts of the goals to sell out RChain Cooperative to people out there, to create more awareness about the new emergent blockchain technology and their executive members by creating awareness. As a member of the RChain community, I see prospect in RChain Cooperative and i'm willing to create more awareness.

**Comment by TrenchFloat** [comment]
See my comment on #675.
