### ISSUE TITLE
disallow votes on issues created after the current pay period

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#682]
#653 was created May 2, but some budget and rewards are scheduled to apply in the April pay period, since votes thru May 8 apply to the April pay period. I suspect it was a mistake. In any case, it's causing problems for the participants to work out the budget and rewards together.

Let's tweak the app to prevent this unfortunate case from happening again.

I'm inclined to apply this retroactively, but reviewing the affected issues shows some where the work was clearly done in April...

   -  #648 | Retroactive Branding WG work Pieter
   -  #649 | The Ultimate Rchain Mega Review Mashup Video
   -  #653 | Translate rholang-spec-0.2.pdf to French
   -  #657 | April Core Development Bounties: Virtual Machine, Rholang Interpreter and Node
   -  #661 | Video Tutorial for Personal Invoice Preparation
   -  #662 | Construction and Maintenance of web forum for RChain Africa Community
   -  #663 | Translation: RCHAIN: AVEC CONCURRENCE ET DIVERSITÉ.
   -  #664 | Bug: Failure Notice For An Email
   -  #667 | RChain Weekly Update (Debrief 75) 20180502
   -  #668 | Blog post: Interview summary.

```
select issue_num, title from (
  select distinct issue_num from budget_vote
  where issue_num >= 644 and pay_period < '2018-05-01'
  union all
  select distinct issue_num from reward_vote
  where issue_num >= 644 and pay_period < '2018-05-01'
) oops join issue on issue.num = oops.issue_num;
```

## Benefit to RChain Membership:

Clarify budget and reward negotiations and make sure there is plenty of time.

suggested budget: $300 (including coordinating with those affected)

cc @kitblake @lapin7

**Comment by Valentine-Mario** [comment]
I had the same conflict sometime ago. It would be good if it is verified so that in future times, issues created for a particular month only get reward for that month.

**Comment by dckc** [comment]
An idea from a brainstorming session today with @barneycinnamon , @ICA3DaR5 , @allancto  was to use trust metric weight to decide which votes to postpone for review. So for each of the 10 issues in question, the weight of the reward voters along with the currently scheduled reward follows. In a separate comment, I'll make a suggestion based on these data:

<TABLE>
<TR>
	<TH>
		pay_period
	</TH>
	<TH>
		issue_num
	</TH>
	<TH>
		reward_usd
	</TH>
	<TH>
		voters
	</TH>
	<TH>
		weight
	</TH>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#648
	</TD>
	<TD>
		1750
	</TD>
	<TD>
		ottermagically:m*7, PatrickM727:, pmoorman:m*7
	</TD>
	<TD>
		14
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#649
	</TD>
	<TD>
		0
	</TD>
	<TD>
		Cryptovideos:j*3, lapin7:m*7
	</TD>
	<TD>
		10
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#653
	</TD>
	<TD>
		3000
	</TD>
	<TD>
		Pionelle:, Valentine-Mario:, BelovedAquila:
	</TD>
	<TD>
		0
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#657
	</TD>
	<TD>
		3430
	</TD>
	<TD>
		AbnerZheng:j*3, notbdu?, dckc:m*7, MParlikar:m*7
	</TD>
	<TD>
		17
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#661
	</TD>
	<TD>
		1100
	</TD>
	<TD>
		kaka56:, BelovedAquila:, dckc:m*7
	</TD>
	<TD>
		7
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#662
	</TD>
	<TD>
		1986
	</TD>
	<TD>
		Valentine-Mario:, Ojimadu:a*1, David405:, Preshcode:, Keaycee:
	</TD>
	<TD>
		1
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#663
	</TD>
	<TD>
		695
	</TD>
	<TD>
		Pionelle:, Kencode7:, ResonanceXX:, lapin7:m*7, Valentine-Mario:
	</TD>
	<TD>
		7
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#664
	</TD>
	<TD>
		85
	</TD>
	<TD>
		Pionelle:, ResonanceXX:, Valentine-Mario:
	</TD>
	<TD>
		0
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#667
	</TD>
	<TD>
		0
	</TD>
	<TD>
		Viraculous:
	</TD>
	<TD>
		0
	</TD>
</TR>
<TR>
	<TD>
		2018-04-01
	</TD>
	<TD>
		#668
	</TD>
	<TD>
		250
	</TD>
	<TD>
		Viraculous:, BelovedAquila:, Ojimadu:a*1
	</TD>
	<TD>
		1
	</TD>
</TR>
</TABLE>

### Query

```sql
select iv.pay_period
     , concat('#', iv.issue_num) issue_num
     , coalesce(rtot.reward_usd, 0) reward_usd
     , tv.voters, tv.weight
from (
  select distinct pay_period, issue_num from (
    select pay_period, issue_num from budget_vote
    where issue_num >= 644 and pay_period < '2018-05-01'
    union
    select pay_period, issue_num from reward_vote
    where issue_num >= 644 and pay_period < '2018-05-01'
  ) av
) iv
left join (
  select pay_period, issue_num, sum(reward_usd) reward_usd
  from reward
  group by pay_period, issue_num
) rtot on rtot.pay_period = iv.pay_period and rtot.issue_num = iv.issue_num
left join (
  select pay_period, issue_num
       , group_concat(sig separator ', ') voters
       , coalesce(sum(weight), 0) weight
  from (
    select distinct pay_period, issue_num, sig, weight
    from reward_vote rv
    left join user_flair uf on uf.login = rv.voter
  ) rvwt
  group by pay_period, issue_num
) tv on tv.pay_period = iv.pay_period and tv.issue_num = iv.issue_num

order by issue_num
;
```

**Comment by dckc** [comment]
I moved all but #648 and #657, which had >10 weight each.

```
drop trigger current_edit_bv_update;
drop trigger current_edit_rv_update;

update reward_vote set pay_period = '2018-05-01'
where pay_period = '2018-04-01'
and issue_num  in (
 -- #648 
  649 
, 653 
-- #657 
, 661 
, 662 
, 663 
, 664 
, 667 
, 668);

update budget_vote set pay_period = '2018-05-01'
where pay_period = '2018-04-01'
and issue_num  in (
 -- #648 
  649 
, 653 
-- #657 
, 661 
, 662 
, 663 
, 664 
, 667 
, 668);
```
Then I turned those two triggers back on (see https://github.com/dckc/rchain-dbr/blob/master/dbr_triggers.sql ).

**Comment by barneycinnamon** [comment]
@lapin7 When reviewing invoices, you can check to confirm that the people listed below didn't accidentally include in their April invoice rewards associated with the issues beside their usernames in the table here. I believe the query that generated these was based on issue votes, so it is possible some of these people voted on rewards for associated issues but didn't receive rewards themselves (no problem) and possible that some people received rewards for these affected issues but did not vote on them (problem).

Username | Issues
-- | --
Pionelle | #653, #663, #664
Valentine-Mario | #653, #662, #664
BelovedAquila | #653, #661, #668
kaka56 | #661
dckc | #661
Ojimadu | #662, #668
David405 | #662
Preshcode | #662
Keaycee | #662

**Comment by Cryptovideos** [comment]
@dckc Howzt Dan - sorry to worry you but does this mean i must not do #649? im still not up to speed on this technical stuff - apologies

**Comment by dckc** [comment]
No, it just means votes for #649 belong in the May pay period, not April.

**Comment by Cryptovideos** [comment]
Tsk Dan all good!

On 13 May 2018, at 15:45, Dan Connolly <notifications@github.com<mailto:notifications@github.com>> wrote:


No, it just means votes for #649<https://github.com/rchain/bounties/issues/649> belong in the May pay period, not April.

**Comment by lapin7** [comment]
#661
#663
#668
Have been moved to May Work Period

**Comment by Valentine-Mario** [comment]
@lapin7  does that mean #662 would be in April invoice?

**Comment by lapin7** [comment]
@Valentine-Mario 
Yes they have been moved to May invoice.

**Comment by dckc** [comment]
Database triggers enforce this constraint now.

fixed in https://github.com/dckc/rchain-dbr/commit/cac617327ec747881593f36ff9d5368ff6aa4da9

**Comment by barneycinnamon** [comment]
@lapin7 @jimscarver @TrenchFloat One vote shy for budget and one vote shy for rewards. If any of the guides want to jump in and nudge it over, that would be nice.

**Comment by kitblake** [comment]
@barneycinnamon Done, this issue is now 'provisioned'. 

That's a term the Marketing guides use, meaning the budget and rewards are not provisional anymore. So @lapin7 @jimscarver @TrenchFloat don't need to take action.
