### ISSUE TITLE
reboot Marketing bounty budgets

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#692]
### Context
See [this comment](https://github.com/rchain/bounties/issues/672#issuecomment-387727941) in issue #616.

The budgets & bounties for marketing should align with the [recently approved marketing plan][1], and we should make sure that...

1. We don't spend a lot of marketing bounty budget on stuff that's outside the scope of the bigger plan (this means guides need to say "hey guys, we don't need this task right now"), but also...

2. We (= 'the guides for marketing') should translate the things that _are_ needed under the marketing plan into actual issues and task that the bounty program can execute on.

### Goal of this issue 
**To create at least 5 well-spec'd marketing issues that align with the [Big Marketing Plan][1]...** 

... and in the process figure out how guides can act as liaisons between 'big plans' and 'bounty execution' to increase the bounty system effectiveness.

cc @kitblake @AyAyRon-P

[1]: https://github.com/rchain/board/blob/master/2018/04-06/Exhibit_C_-_RChain_Maketing_Plan.docx.pdf

---

Since @patrick727 (or is it @PatrickM727 ??) acts as an interface to the marketing team, we'll obviously sync with him as much as possible, to avoid overlap.

***Legal***
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
by "recently approved marketing plan" I suppose you mean https://github.com/rchain/board/blob/master/2018/04-06/Exhibit_C_-_RChain_Maketing_Plan.docx.pdf

**Comment by David405** [comment]
@stallion00 seems you re new, please use the links below to acquaint yourself and contribute to the community

  
- [ ] Watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
 

- [ ] Join rchain@googlegroups.com to get access to documents of RChain 

- [ ] https://groups.google.com/forum/#!forum/rchain/join

- [ ] Join github/rchain/bounties in order to contribute https://github.com/rchain/bounties/invitations
  

- [ ] Fill out the RAM registration form https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform
  

- [ ] Collaboratein all kind of issues https://github.com/rchain/bounties/issues
  

- [ ] Collaborate in development https://rchain.atlassian.net/browse/OPS-31?jql=labels%20%3D%20bounty
 

- [ ] Fool around with our Bounty App https://rewards.rchain.coop/

- [ ] Read about collaborating https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
 

- [ ] Read about our decentralized bounty system. https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App
  

- [ ] Join RChain Coop by signing up for membership http://member.rchain.coop/
 

- [ ]  Claim your reward: https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
 

- [ ] fill out a W8 https://www.irs.gov/pub/irs-pdf/fw8ben.pdf
 

- [ ] read W8 instructions https://docs.google.com/document/d/1LdxfZEjM37ub_qFizM_otrp2X1YxiJh7VDpfqeYDfu8/edit?usp=sharing
  or fill out a W9 https://www.irs.gov/pub/irs-pdf/fw9.pdf
  

- [ ] W9 instructions https://docs.google.com/document/d/1hg83LDU__6VYV_fkZTeZrErCPKs8PsHGasRVAvQG_uY/edit

**Comment by David405** [comment]
@stallion00 The marketing plan is in the link @dckc shared

**Comment by David405** [comment]
@dckc I believe Education and Development teams can work together to develop coursetracks for beginner, intermediate and advanced RChain developers

**Comment by Viraculous** [comment]
yea, @pmoorman. GregM already will be will be hosting lectures on the course "**INTRODUCTION TO THE DESIGN OF COMPUTATIONAL CALCULI**  " which will be commencing on the 28th of may and definitely we will try integrating that into the RChain's educational resource.

**Comment by nonnykul** [comment]
@David405,a coursetrack will help in promoting an education content.@pmoorman on #681,will make the 'educational idea' a reality by getting enthusiastic students in Rholang developerment.

**Comment by barneycinnamon** [comment]
Does it make sense for this issue to live inside the bounty system as opposed to living inside the proposed new marketing organization? It seems like somebody inside the marketing organization should be managing the interface between that effort and specific issues that could be completed within the bounty system. I guess I just don't understand why "the crowd" would decompose the plan into bounty-able action items as opposed to the people actually running the marketing org choosing how that happens.

**Comment by jimscarver** [comment]
this issue needs a smart objective.

I do not think the bounty system should confine itself to activities already being pursued by the coop marketing plan. I think we should cast a wider net and fund anything we think may provide us good exposure.  Everything is an experiment and we need to have some metrix if success.

**Comment by pmoorman** [comment]
@jimscarver in my description I stated the goal of the issue as:

> To create at least 5 well-spec'd marketing issues that align with the Big Marketing Plan...

What is not SMART about that? Maybe the "timebound" is missing, but other than that it's about as SMART as I can get it. Can you suggest improvements?

**Comment by pmoorman** [comment]
Hey all,

I owe everyone an update here. While the 201805 pay period closes, it's clear that there is a lot of energy in marketing, but we sometimes struggle to channel that energy into productive means.

Meanwhile, Patrick has been working very hard together with Ankur and others to build out an autonomous marketing organisation to support RChain. They oversee much of the strategic marketing work that comes out of the Big Marketing Plan, but Patrick told me they're too busy right now to have enough time to properly communicate with the bounty system.

That means that -- for now -- there is very little in terms of strategic directions to work with apart from the marketing plan itself. 

There are a few areas where Patrick and I belief the bounty system can certainly add value:

- **Competitive Intelligence**  :: we're currently setting up a small informal working group to lead competitive intelligence, but the bounty system can help in doing the research and maintaining that knowledge base.

- **Help spread content**  ::  core content creation will probably fall mainly under the control of the marketing org, but the bounty system can help amplify the reach of that content.

- **Branding asset creation**  ::  while the Branding WG together with Girvin leads a strategic branding overhaul, we'll need assets to be created based on that strategic work. This work isn't available immediately, but will be from ~August onwards

- **Onboarding**  ::  onboarding developers to learn Rholang and explore the technology is something the bounty system can do.

On top of that, (as @jimscarver has also suggested) the bounty system should be able to pursue marketing tasks that the core marketing org won't get to, or suggest other tasks that are in alignment.

For now... it will take more work than I thought to provide a steady flow of marketing tasks (especially while the marketing org is getting itself organised), but we're working on it.

Feel free to ping @kitblake, @AyAyRon-P or myself you have suggestions, or want to discuss ideas.

**Comment by pmoorman** [comment]
### Short update

Today I created:

1. An issue on creating a "meetup-in-a-box" => https://github.com/rchain/bounties/issues/779
2. An issue on creating website information architecture, with more tasks to come concerning website => https://github.com/rchain/bounties/issues/780

I spoke with Dan yesterday about this topic, today will speak with @makys about what we can do regarding onboarding, and tomorrow will meet with Kit and Patrick to discuss how to improve the flow from marketing org strategy to bounty system execution.

My hope is that we can create those 5 good issues within the next couple days, and move to a more steady stream of issues being posted in the (near) future.

**Issues that I hope to publish in the next couple days:**

- Cardano research
- RChain librarian project
- RChain use cases research
- Rholang concepts for non-devs
- Gathering testimonials for website
- Website mock-ups
- Website design agency engagement
- Onboarding tasks (details to be determined, hopefully tonight)

_[To be continued...]_

**Comment by pmoorman** [comment]
## Update

Here's another update on what's happening with this. 

- First of all: the competitive intelligence WG is getting ready to work more publicly, and could use the help from more hands. Read more about it here https://github.com/rchain/bounties/issues/776#issuecomment-401279401

- The marketing org has produced an excellent promotional video, which the bounty system community can help spread. See #807. This is an excellent case of how marketing org + bounty system can work together

- The website now has a lead by the marketing org, and we'll see in the next ~2 weeks how RAMs can assist with this effort. This looks like another great case where marketing org and bounty program can work together. For an update on this, see https://github.com/rchain/bounties/issues/776#issuecomment-401279401

- A week ago we have had a call with @kitblake @patrick727 @jplepel and @decentralizebanksy and myself to discuss how marketing could sync better with the bounty program. The energy & commitment on the call were great, and there's a lot of optimism that we can actually make this "decentralised marketing" work. We wrote notes on the call, but we haven't agreed to publish them. Instead I'll write this update.

- @kitblake and myself now have much better transparency into what's going on in the marketing organisation, which already helps easy the communications.

- We'll strive to co-lead projects with 1 lead from marketing org, 1 from bounty system (e.g. competitive intelligence, or website). @kitblake and myself will look for opportunities there.

- @kitblake will produce a sort of "organisational chart" of the marketing organisation, so at least people from the outside can find out who they should reach about a given topic. 

- The marketing organisation is looking to migrate to JIRA for issue tracking, which will make it more transparent. Again @kitblake is instrumental here in helping getting this set up.

- @kitblake and myself will act as more of a liaison between the marketing org and the bounty system. Especially 

- We want to experiment with pre-assigning certain bounty tasks to certified people in the bounty system. This compromises openness of admission somewhat, but at the gain of dependability that we can offer the marketing team. For instance, we have within the community Maarten who has proved to be a good WordPress developer. We could say: _"hey, here's a bounty project that Maarten could do to help set up the marketing blog"_.  I plan to open up a new issue to make room for discussing this topic specifically. 

- @phil (on Discord) has suggested that maybe there should be open marketing calls that people can listen to. Sounds like a good idea, and something we'll have to work on in the (near) future

## Conclusion

My hope is —of course— that with this update, y'all can see that we're working very hard behind the scenes to make this synchronisation between marketing org and bounty program happen.

It's turned out to be much harder than I initially thought, but we're certainly moving in the right direction. 

_**P.S.** Specially shout-out to especially @kitblake and @PatrickM727 for putting in a lot of effort behind the scenes to make all of this happen. They're the ones trying especially hard to make this decentralised effort work!_

**Comment by pmoorman** [comment]
I'm tempted to close this issue, because explicit goal as laid out in the description has been achieved. 

However... I think we (marketing guides) are still doing a bad job passing work from the marketing org to the bounty system. As such, I'll keep this issue open with the aspiration to widen the scope in the next month(s), and improve on this area.

**Comment by barneycinnamon** [comment]
@pmoorman Based on your last comment you were just about ready to close the issue. Do you still have follow up items you want to address within the scope of this issue?

**Comment by pmoorman** [comment]
@barneycinnamon (and tagging @kitblake @AyAyRon-P as well, for good measure) I'm a bit torn about it. I feel we (marketing guides) have only done a so-so job of translating marketing work to bounty tasks. 

It's certainly turned out to be harder than I thought, and it's probably an ongoing effort. I guess you're right we should close this off for now, since there's no SPECIFIC action that I plan on taking on this at the very moment. If that changes, I'll open it up again.

Conclusion: closing this issue for now, will possibly re-open when specific tasks pop up again.

**Comment by dckc** [comment]
discussion with @PatrickM727 , @deannald , @ddayan , @JoshOrndorff ...

@PatrickM727 has an org chart in the works; the pillars are:
 1. developer education (Joshy)
 2. product marketing (Kevin)
 3. digital marketing (Amir)
 4. community development (Patrick (@planteater ?))
    - meetups

split **Development** into core-dev and ...
pivot / rename **RChain Technical Literacy** toward developer education?

for Weds debriefs: feed bounty / community building info to to Patrick on Tuesday, as well as perhaps having TAC/guide meetings Thursdays... 10am Seattle. @dckc to contact @allancto ; PM to contact LGM.

**Comment by David405** [comment]
@dckc @PatrickM727 are these new labels a subset of marketing? or the only labels we are going to have now?
Also, I would love to work with Joshy in guiding developer education issues. @JoshOrndorff what's your take on this?

**Comment by dckc** [comment]
It's as I said in #783 :

> I would expect to see some sponsorship from Marketing for anything like these labels: **Branding**, **Community Building**, **Events**, **Marketing** (duh), **Social media**, **Translation**.

No, there's no discussion of limiting bounties to only these marketing-related things.

**Comment by dckc** [comment]
@pmoorman made a [marketing labels sketch](https://docs.google.com/document/d/1TufZLFrBM4_z2Z7zdcqPdOyKVJ78imn3VeROcPvS6ps/edit#) that turned into meeting notes for #995 . @PatrickM727 and others have the ball to follow up on a few things, but not an overall Marketing label. So I think that about wraps it up for this issue.
