### ISSUE TITLE
Establish "tenets" for marketing issues (and integrate into bounty onboarding experience)

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#693]
### Context
This issue is in line with a series of issues to make the bounty system work smoother and align effort/compensation with the goals of the RChain cooperative. I would like to make it easier for (new) contributors to see what kind of contributions we're most seeking out.

Tenets could be (for example (!!)):

- **Focus to increase engagement in Asia**  =>  which means that Asia-focused efforts are more highly rewarded than the same Latin America-focused areas 

- **Less sharecropping. Publish on cooperative-controlled domains**  =>  which means that the same Youtube video or blog post is more valuable if it's on the official RChain Youtube channel than if it's on your own channel

- **We need Rholang developers, first and foremost**  =>  which means that marketing that gets us in front of functional developers is much more valuable than marketing that gets us in front of 'interested people' that aren't developers and aren't very likely to write Rholang code in the near future

- etc.

These are just _examples (!!)_, but I think we can work together to establish tenets for marketing work (and probably similarly for other functional areas). This will make it easier for everyone to judge whether their ideas match with what fits with the "big picture" strategy. 

### Goal
**Establish tenets for marketing issues within the bounty system....**

... so that it'll be transparent for everyone with ideas for new bounty issues how their ideas match (or mismatch) against the bigger picture marketing strategy of the cooperative.

Suggested budget: $1.000
Completion: tenets defined and integrated into the wiki or CONTRIBUTING.md or similar places where everyone can easily find them.

---

***Legal***
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by David405** [comment]
@pmoorman, according to the coop marketing plan, onboarding software developers is paramount and so any work done towards this should be more rewarded than others. I believe this should be one of the marketing tenets

**Comment by pmoorman** [comment]
@David405 great first addition. Alignment with the marketing plan and those first focus areas is a great idea. Keep it coming!

**Comment by philipandri002** [comment]
@ pmoorman I also think that it should also be highly rewarded when a marketer or influencer as the name may suit reaches out to more strategic marketer to join forces in creating the much needed awareness that at the long run increase the chances of getting better software developers and investors..

What do you think Sir.

**Comment by azazime** [comment]
Tenets should be less complicated with simple and precise headlines so as not to confuse the (new) contributors which would defeat the aim of such effort. And I would also advice the admins at various levels incorporate such tenants at their various quarters, e.g @David405 who is part of the admin in the Africa telegram group who ensure the tenants are part of the pinned messages there.

**Comment by casanwugo** [comment]
I'll collaborate on this by adding that "marketing” meant having a capabilities brochure, corporate presentation, web site and little else. There is much that marketing can do to promote RChain's value proposition, brand, image, reputation and market visibility all contributing to lead generation, which is the lifeblood for growth in the community.  Marketing’s job is to develop a market presence i.e. ecology around business development and operations so that newbies can establish mindshare. Tenets should include but not be limited to the following; 

- Finding a niche that would enable us standout from competitors.

- Get found online. 

- Become a destination.

- Be part of the community. If you want your community to support you, support it. Be visible in your community.
 
Hope you find this insightful,,, @pmoorman Great job!

**Comment by pmoorman** [comment]
Hey all,

after discussing with the 2 other marketing guides @AyAyRon-P and @kitblake here's a first suggestion for marketing "best practices".

I'll change the title from "tenets" (which is almost like a religious belief) to "best practices" because really that's more what it's about.
**[
Here's the document](https://docs.google.com/document/d/1wMj8VGYTLc1PTRjgVtwVxEv8Byzvsb5L3fIV6Z-XENI/edit?usp=sharing)**

There are 7 best practices:

1. Our target audience is Rholang developers & Dapp decision makers
2. No sharecropping
3. Aim for the center
4. Consider the approval & release process
5. Does it have an ROI?
6. Try to measure it

Our aim is to provide these best practices to help everyone submit marketing bounty issues that are more likely to be accepted and funded.

### Next steps:

- [ ] Collect feedback from everyone, as well as additional suggestions
- [ ] Incorporate feedback & additional tenets (as needed)
- [ ] Publish the marketing tenets on the Wiki page, so we can point people to it

I would also encourage other functional area guides to consider if something similar can be done for their respective labels, too.

**Comment by David405** [comment]
@pmoorman I believe these _"best practices"_ should move beyond marketing issues to every other label issues. It should act as a general guideline for all issues.

Also, I think a standard metric should be developed to help RAMs measure progress on participating issues.

**Comment by pmoorman** [comment]
if people find them useful outside the context of marketing, then by all means let's use them more broadly.

I didn't really think about how this would interface with governance or greeter or any other label. Maybe these guides could have a look at them, and see what they can copy?

**Comment by nonnykul** [comment]
This best practices could be applied to other issues,to create a standard

**Comment by ResonanceXX** [comment]
**Marketing is the embassy of the whole operation.** Consistent with @pmoorman's view, best practices do, and should, be applied in the context of how Marketing issues are executed.

Maybe there is a proliferation of Marketers and I understand the subsequent need to have organization. Willing to conform to this, and work towards attaining the set marks. Cheers all.

**Comment by barneycinnamon** [comment]
I removed the Governance label, because I think the scope of this issue is Marketing.

**Comment by pmoorman** [comment]
This has been open for review for a little over a month now. Since it's been well-received, I've proceeded to roll this into the wiki.

**[See the wiki page here »](https://github.com/rchain/bounties/wiki/Marketing-best-practices)**

I'm closing out this issue now, but I can imagine we make further improvements on it in the next couple months, to further fine-tune it.
