### ISSUE TITLE
Website upgrade  ::  add a 'research' page to display information regarding research grants and related matters

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#694]
Eitan Chatav and Joseph Denman reached out (via Patrick) to add a research section to the website. Their idea is to show off research papers related to RChain and maybe videos of talks, etc. 

For comparison see [IOHK's research page](https://iohk.io/research/).

This seems like a great idea, so let's add a research section to the website.

**Measure of completion:** research page up on the rchain.coop website
**Budget:** $600

---

***Legal***
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Valentine-Mario** [comment]
I can also help in contributing by talking of human behavior in relation to Rchain cryptocurrency

**Comment by nonnykul** [comment]
Gud concept, like to contribute to d research section on the website

**Comment by azazime** [comment]
There are a lot of documents on this, I suggest we think of integrating them

**Comment by Murphy6** [comment]
Nice contribution social media platforms is one of the highest promoting platforms.. We all should kindly follow the rchain Instagram account https://www.instagram.com/rchainafrica

**Comment by nonnykul** [comment]
@pmooman,working on issues#696.The videos that will be uploaded will be Research works done on RChain,it will be beneficial to the research section on rchain.coop
