### ISSUE TITLE
RChain Africa channel on Youtube

### ISSUE THREAD

**Issue by nonnykul** [rchain/bounties#696]
*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

YouTube, the google owned video network,boasts over a billion users and everyday people watch hundreds of millions of hours on YouTube and generate millions of views.
Why aren't businesses investing in YouTube as part of their social media strategy?
In reality,though,video is becoming more cheaper and easier to create.This means there is a huge opportunity for RChain on YouTube.

Task to be done

- [x] Create the YouTube channel - https://www.youtube.com/channel/UC-jgVqhIJ4cVopRQTNn8WtQ

- [x] Manage the YouTube channel

- [ ] Use videos to promote RChain in Africa

- [ ] Generate content for the channel

 

_Estimated Budget of Task:_ **$[500]**  \
_Estimated Timeline Required to Complete the Task:_ **[4weeks]**  \
_Measure of Completion:_ **[completion of tasks]**

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by nonnykul** [comment]
Working on a creative,detailed video that will market RChain to the world.

**Comment by Keaycee** [comment]
@David405 @nonnykul. All RChain videos would be update on the RChain Official youtube handle. There won't be a need to create another youtube Handle. Videos of any events anywhere in the world would be reviewed by the executives members before reflecting on the Youtube handle.

**CC**  @pmoorman

**Comment by David405** [comment]
This is required right now and so I am closing it.
