### ISSUE TITLE
Cobudget tool for the bounties system

### ISSUE THREAD

**Issue by Barkov-F** [rchain/bounties#697]
### Cobudget tool adoption for the bounties system

https://cobudget.co

*Current budgeting process has several drawbacks, including limited reporting and accountability. I suggest testing the cobudget platform developed by the [greaterthan](https://www.greaterthan.finance/) coop for marketing and translation tasks in June.* 

The Cobudget is being used by several coops around the globe with great results. See the [case studies](https://greaterthan.gitbooks.io/greaterthan-s-guide-to-collaborative-finance/content/case-studies.html).

The basic idea behind the tool is simple: group members receive funds in their cobudget account. They can propose projects and activities and allocate their own funds to support the proposals of others in the group. See the [3 min video](https://www.youtube.com/watch?time_continue=1&v=8d1zrxNgFS8).
 
_Estimated Timeline Required to Complete the Task:_ **8 weeks**  \
**2 weeks** - get access to the platform, inform the RAMs about the experiment and onboard them to cobudget
**5 weeks** - run the first budget cycle with marketing and translation tasks
**1 week** - evaluate the results, prepare a test-report, share the findings with the board and the community

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Barkov-F** [comment]
I started a loomio thread about the proposal. https://www.loomio.org/p/40XMOcNP/let-s-try-cobudget-for-bounties

Please, share your views and opinions

**Comment by dckc** [comment]
Is this intended as a means to carry out the Apr 6 TOS decision (#616)? If so, how does the Task Approval Committee work? If not, is this a separate bounty system?

How would we sync coop membership with cobudget accounts? (a la #413)

In any case, how would the money get into the cobudget accounts to start?

Does cobudget support payment in dollar-equivalent RHOC?

I tried to use the thing but ran into an "apply for early access" thing.

I tried to read the case studies, but I'm struggling to find them. https://greaterthan.gitbooks.io/greaterthan-s-guide-to-collaborative-finance/content/case-studies.html redirects to https://guide.greaterthan.finance/

**Comment by Barkov-F** [comment]
Hmm... Strange. How about this [link](https://guide.greaterthan.finance/collaborative-finance-tools/cobudgeting/cobudget-use-cases)? The page with the use cases outlines several ways how the tool can be used in different organizations: [BlackwoodSeven](https://guide.greaterthan.finance/collaborative-finance-tools/cobudgeting/case-studies/agile-team-in-blackwoodseven), [ELI](https://stories.greaterthan.finance/cobudgeting-for-member-engagement-bd1c54ed434) and [Outlandish](https://stories.greaterthan.finance/investing-surplus-for-impact-cobudgeting-at-outlandish-efa9890d0d4f)

I think than Task Approval Committee job will be easier if we set cobudget group parameters and policies and stick to them. See [the template](https://docs.google.com/document/d/1yK8A3HoT8Yd7ElYKfuccRibgCXb_yEj5Pu8WFMPAUts/edit#)

So far I see the dollar-equivalent RHOC payment requirement as the biggest hurdle for adoption.

**Comment by lapin7** [comment]
# Hold on!!

We've about >150 RAM's that actually do things.
We're still within budget. About 150.000 RHOC left from the 1 mln RHOC that was allocated by @leithaus 
We've a great innovative budget and bounty system. The Trust metric is able to provide governance.
We've a great collaboration tool. Github works just fine.
It's a large scale social experiment that is about to take off to the moon.

Whereas the TOS is invented by a few persons and without consult of the RAM's.
The TOS is only words at the moment and RChain doesn't have an implementation plan.

**Comment by lapin7** [comment]
Here's a spreadsheet to play with.
https://docs.google.com/spreadsheets/d/1UfRgtSaTcZvuVW7GOonivA3Qgs2xVgT-0SVwpuDxHzM/edit#gid=592953635

It has all data of Budgets and Bounties from August 2017 to April 2018

It's the base for a nice financial report.

**Comment by pmoorman** [comment]
sounds about right to first work out the ToS stuff (see #616 and related issues) before we dive into this. 

Although it's not perfect the app built by @dckc seems like a good approximation of what we need. I would lean towards improving that, rather than switching things around entirely.

**Comment by Murphy6** [comment]
Nice contribution social media platforms is one of the highest promoting platforms.. We all should kindly follow the rchain Instagram account https://www.instagram.com/rchainafrica

**Comment by jimscarver** [comment]
cobuget is good when you have a fixed amount of money to play with. We hope to spend as much as possible for good work so I go not think cobudget is the right tool for us.

**Comment by Barkov-F** [comment]
Ok. I guess I get excited too much when I see a shiny new betas. But still I think that the Coop should approach someone, if not Cobudget, then someone else to help us with the organisational patterns and compensation and rewards practicies:

**Disco**

This US-based company, started in 2015, uses artificial intelligence to scan employees’ messages to one another. If a bot spots an employee being congratulated for good work, it will automatically award a star. Clients include Adobe and Spotify.

**Bonusly**

Founded in 2012. Just over 1,000 companies use the service, including Hulu, Oracle and Chobani. The Boulder, Colorado-based company has investment from FirstMark Capital and Bloomberg Beta.

**Globoforce**

The elder statesman of employee social recognition. The company was started in Ireland in 1999, and encourages employees and managers to mark service milestones as well as life events. Customers include Hershey and Cisco

**Comment by Barkov-F** [comment]
@pmoorman  We can try their tools for [free ](https://fluxicon.com/disco/download.php?dist=win)
