### ISSUE TITLE
Promoting RChain Africa on Instagram 

### ISSUE THREAD

**Issue by Murphy6** [rchain/bounties#699]
Promoting RChain on Instagram basically and mostly with photos for benefits of those that wouldn't have the time to wait for some minutes online and read a post, most times strategic photos are used on Instagram and social media platforms to put people on hold/ read and advert . Africans on Instagram are running in Millions and it is a platform that is growing day after day with each day recording hundreds of new members over other social media.

Have created an account for RChain Africa in a way it will be easy for " a lame man " with illustration and explanation of what the community is all about basically with photos and writeups. 

With this every African member can follow each other and allso have a direct link to ask questions.

This also includes uploading one minute videos of what RChain stands for.

The two weeks duration is for coming up with the videos and picture illustrations which is already in progress and getting Members of this great community to follow back and help share the link.

In order for members to be aware of this great development will keep commenting the link for every issue for people to follow.

This handle is almost ready but after the given period it will be fully ready where by people can understand with rchain is all about. In addition the handle will keep running (renewing it monthly) I will make sure I keep it up online for the growth of our community.

Tasks to be done

 Create the Instagram  handle ☑️100%
 Manage the handle ☑️ 100%
 Promote RChain in Africa☑️ 60%
 Generate content for the page☑️ 40%
Getting members to follow back ☑️ 30%

Members on Instagram can share the link 
And also follow @ RchainAfrica https://www.instagram.com/rchainafrica

_Estimated Budget of Task:_ **$[300-400]**  \
Duration **2 weeks***
_Measure of Completion:_ ** completed **

**Comment by David405** [comment]
@Murphy6 nice work but the 2 weeks duration is for what if I may ask?

**Comment by Valentine-Mario** [comment]
But we have to consider how much information a picture can pass across unless you wish to use an info graph, then I can supply you with some content.

**Comment by Murphy6** [comment]
@valentine-Mario thanks so much for your contribution. The community is for everyone aiming to keep promoting the community to make sure more Africans gets to know and understand it. Illustrations through photos can really help consider when an art teacher tells you about history just through photos. Your content will really be of a great use if you can come up with any before the completion date.

**Comment by Murphy6** [comment]
@david405 really appreciate for your time and question.. The two weeks duration is for coming up with the videos and picture illustrations which is already in progress and getting members of this great community to kindly follow back.

**Comment by Murphy6** [comment]
@pmoorman thanks for your time .. But this issue is basically set to grow African on Instagram and educate them about the community. This platform can also be used as a medium to share other people's issues from the platform.

**Comment by David405** [comment]
@Murphy6 can you kindly give an update on this?

**Comment by Murphy6** [comment]
@david405 thanks for your comment at this point the page has over 104 followers and it is still growing it has a lot of content and people are really getting all information they need from the page.

**Comment by Murphy6** [comment]
@david405 @AyAyRon-P @kitblake @pmoorman please am kindly asking for support the page has over 104 Africans following and with great content on it.

**Comment by AyAyRon-P** [comment]
I don’t see much if any value of having an Instagram for RChain. We have discussed this before and there are other social media platforms that will be far more beneficial to RChain if you are truly trying to build a community in this region. @ojimadu @philipandri002 what’re your thoughts?

**Comment by Murphy6** [comment]
@AyAyRon-P thanks so much for your time and comment. Since over two months I open that Instagram handle (RchainAfrica) over 50 people have sent a direct message asking what is all about and how they can be part of it . To caught the long story short 39 of them have registered and are full members of the community.. And more are still following the page . We shouldn't in anyway understand estimate the importance of Instagram in the lifes of over millions of African youths

**Comment by Murphy6** [comment]
@AyAyRon-P thanks so much for your time and comment. Since over two months I open that Instagram handle (RchainAfrica) over 50 people have sent a direct message asking what is all about and how they can be part of it . To caught the long story short 39 of them have registered and are full members of the community.. And more are still following the page . We shouldn't in anyway underestimate the importance of Instagram in the lifes of over millions of African youths.

**Comment by kitblake** [comment]
@Murphy6 Instagram is not one of the services that the Cooperative is using. That could possibly change in the future but until it does there's no ROI on an rchainafrica Instagram.

**Comment by pmoorman** [comment]
I'm closing this issue, because I don't believe marketing further wants to pursue this line of work (see comments from Kit and Aaron above)
