### ISSUE TITLE
Medium post: RCHAIN; THE FUTURE OF DECENTRALIZED INTERNET

### ISSUE THREAD

**Issue by Kencode7** [rchain/bounties#700]
*Most developers are recently interested in smart contracts and blockchain technology because it is the future of internet. This medium post is to expose and enlighten developers, tech communities & tech enthusiasts on the scalable Rchain application with keen interest in Rho-lang so they can experience a concurrent and correct by construction language* 

[POST](https://medium.com/@kencode007/rchain-the-future-of-decentralized-internet-8342446b0445)

_Estimated Budget of Task:_ **$[500]**  \
_Estimated Timeline Required to Complete the Task:_ **[completed]**  \
_Measure of Completion:_ **[members attracted to the developers forum and review of the post]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Murphy6** [comment]
Nice contribution social media platforms is one of the highest promoting platforms.. We all should kindly follow the rchain Instagram account https://www.instagram.com/rchainafrica

**Comment by pmoorman** [comment]
@Murphy6 please stop posting your "promotion" on all Github channels. I consider it SPAM, and I'd appreciate if you could remove all those comments.

_Your posting actively hurts collaboration by others._

**Comment by Murphy6** [comment]
@pmoorman with due respect the link am posting is basically for same goal why we all are here is a link for rchain Africa on Instagram .. but will surely take it out thanks

**Comment by Pionelle** [comment]
Bonjour @kencode
Votre écriture est très directe et excellente. Il devrait être lu par un plus grand public ne pensez-vous pas, j'ai demandé la permission de traduire et de publier sur Medium_FR

**Comment by TrenchFloat** [comment]
Could you tell me why you proposed a $500 budget? I'm not sure this post is fit to represent the RChain community until it is proofread and edited for errors.

**Comment by Kencode7** [comment]
The post was merely to excite young developers to try out rholang...

**Comment by TrenchFloat** [comment]
In that case, I propose a budget of $80, for 2 hours of work at $40/hr. With some editing, I would think to expand the budget.

**Comment by kitblake** [comment]
I see a Marketing label so I read the post. Hopefully it will excite some young developers. 

Adding links from where you collected the content helps them dig in deeper. The post has 28 claps, and I added some. I'm also following @TrenchFloat's lead and adding a budget. 
@pmoorman @AyAyRon-P
