### ISSUE TITLE
Rchain Africa Twitter handle 

### ISSUE THREAD

**Issue by Valentine-Mario** [rchain/bounties#701]
A Twitter handle for RChain is helpful as it provides tailored discussions and topics that both promotes RChain in Africa markets and provides basic, less complex and very complex documentation that accomodates the needs of both newbies and established members..

I acknowledge the fact that RChain already has a Twitter handle and chat mediums for discussions but a Twitter handle that is tailored for Africa is still needful in an effort to penetrate the African market.

Tasks to be done
- [x] Create the Twitter handle
- [x] Manage the Twitter handle
- [ ] Promote RChain in Africa 
- [x] Generate content for the page

Time required : ???
Budget :???

**Comment by Valentine-Mario** [comment]
The Twitter handle has been created and can be followed @ rchainafrica

**Comment by nonnykul** [comment]
good concept,will like to contribute to achieve the desired task

**Comment by Murphy6** [comment]
Nice contribution social media platforms is one of the highest promoting platforms.. We all should kindly follow the rchain Instagram account https://www.instagram.com/rchainafrica

**Comment by pmoorman** [comment]
@Valentine-Mario to me it's not obvious why it would be benefitial to have region-specific Twitter handles. To me the costs/downsides of having many handles are obvious, but the upsides are not. 

**Could you better explain why this constitutes value to the RChain coop?** 

Why can't African people just use the main twitter handle?

Also: since this would then be an RChain property / asset to manage, who has access to this twitter handle? Is it now something that we're sharecropping with you, or how does that work?

_I'm fairly skeptical that this regional approach is needed and that budgets are justified._

**Comment by Valentine-Mario** [comment]
The timing for RChain Africa handle might not be optimal, but it's a long term goal because as RChain grows, it would have to be region specific. This would also go a long way in reducing the burden at the center. moreover, it is in response to #591 on penetrating the African market.

**Comment by Keaycee** [comment]
@Valentine-Mario @pmoorman @David405 . There won't be need to create another twitter handle because one already existed Check issue #662 . Do not create any other handles as it already created and is in use already.

**Comment by Valentine-Mario** [comment]
I was involved in developing that forum. It's not a Twitter handle. It is a forum for Rchain Africa. Rchain Africa has no Twitter handle till now.

**Comment by Keaycee** [comment]
@Valentine-Mario @David405 please see this. [Click](https://github.com/rchain/bounties/issues/662#issuecomment-387516149)

**Comment by Valentine-Mario** [comment]
Thanks for the clarification @Keaycee I have edited the link to the original twitter handle created. I shall also help manage and promote it. The older twitter handle would be deleted.

**Comment by Valentine-Mario** [comment]
I can see that the Twitter handle does not have many followers and content. We could work together to generate daily content(s) and gather more followers.

**Comment by David405** [comment]
This is already in place in #662
