### ISSUE TITLE
Expanding RChain Africa community using Twitter as a tool :#promoteRChainAfrica 

### ISSUE THREAD

**Issue by awesome000** [rchain/bounties#702]
Social media has been the best promoting tool in Africa and the Twitter community tops the poll. Every main issue that circulates eminates from Twitter community to the rest of the world. To put RChain Africa to the rest of the world, we must take advantage of this ever growing community. 
Hence the urgent need for RChain Africa to be on that platform for strategic marketing which will in turn increase the awearness of RChain in Africa 

create the Twitter handle ☑️
Manage the handle ☑️
Generating content for the page ◽️
Getting member to follow back ◽️
Members can go follow the Twitter handle for RChain Africa and also share the link. 
https://mobile.twitter.com/ChainafricaR

Estimated budget $[300-400]
Duration 2 weeks 
Measure of completion 70%

**Comment by Valentine-Mario** [comment]
An issue has already been created on this topic. And RChain Africa already has a twitter handle. Follow @ rchainafrica
