### ISSUE TITLE
Translation: Medium post:  RCHAIN: L'AVENIR D'UN INTERNET DECENTRALISE

### ISSUE THREAD

**Issue by Pionelle** [rchain/bounties#705]
### For all issues
[Keep _italic_ labels, replace brackets with answer]

*Makeing the document availablee to Francophone and adopted French speakers:* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

_Estimated Budget of Task:_ **$[500]**  \
_Estimated Timeline Required to Complete the Task:_ **[terminé/to review before post]**  \
_Measure of Completion:_ **[2 jours]**

https://docs.google.com/document/d/16cwdJvCe7fx78NhdxlpdfgCc5h5YQN4slFZmstIj7ak/edit?usp=drivesdk&ouid=112243679794038364949

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
     @BelovedAquila  Myself
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by ICA3DaR5** [comment]
Please fill the "For Translators" section and make the Google Docs document public, otherwise there is no point in posting it.

**Comment by Pionelle** [comment]
https://docs.google.com/document/d/16cwdJvCe7fx78NhdxlpdfgCc5h5YQN4slFZmstIj7ak/edit?usp=drivesdk

Check this now

**Comment by Pionelle** [comment]
ce lien est ouvert aux gens
https://docs.google.com/document/d/16cwdJvCe7fx78NhdxlpdfgCc5h5YQN4slFZmstIj7ak/edit?usp=drivesdk

**Comment by ICA3DaR5** [comment]
@Pionelle You haven't filled the "For Translators" section on your issue.

**Comment by Pionelle** [comment]
Okay sure will do

**Comment by Pionelle** [comment]
https://medium.com/@rchainfrench/rchain-lavenir-de-l-internet-décentralisé-30de66829556

**Comment by Pionelle** [comment]
To proof read more

**Comment by Pionelle** [comment]
Published now, @ica3dar5 I try checking the boxes but it doesnt change.

**Comment by ICA3DaR5** [comment]
@Pionelle Okay you can edit the document and put x in the little box. Also if you could make your posts in English that would be very helpful.

**Comment by ICA3DaR5** [comment]
Okay, so you should fill the "For Translators" section on your issue post. I've asked you once before and I didn't get an answer to that.

**Comment by Pionelle** [comment]
of course I have now done that.

**Comment by ICA3DaR5** [comment]
Okay so it seems that this is not for translation. It's not an RChain Medium item, nor is it endorsed by @Jake-Gillberg, @MParlikar for translation.
