### ISSUE TITLE
D> Update RChain.cloud with 0.3.1 support

### ISSUE THREAD

**Issue by tschoffelen** [rchain/bounties#707]
Currently, [rchain.cloud](http://rchain.cloud/) only supports Rholang/RNode 0.2.1. This issue tracks the progress in adding support for 0.3 and future versions, which uses a different structure for executing Rholang contracts. See details in the [PR here](https://github.com/th3build/rchain.cloud/pull/9).

_Estimated Budget of Task:_ **$300**  \
_Estimated Timeline Required to Complete the Task:_ **3 days**  \
_Measure of Completion:_ **[Getting the PR completed and merged](https://github.com/th3build/rchain.cloud/pull/9)**

**Comment by dckc** [comment]
Looks like you didn't vote on any rewards for yourself, @tschoffelen . Is that on purpose?

Also... is this deployed? Didn't https://rchain.cloud/ used to have a thing where you could pick which version to use? I don't see any version info now.

**Comment by dckc** [comment]
Oh... and getting a PR merged is less of an accomplishment when it's your own repo. :)

But seriously ... is anybody reviewing these changes?

**Comment by tschoffelen** [comment]
Since 0.3+ architecture is so much different from the previous versions, we temporarily removed the version selector in the process of adding 0.3.1 support. This has been completed, see link to PR in the description of the issue.

Sorry, thought I had voted already, will do ASAP!

**Comment by dckc** [comment]
You voted on the budget but not on who gets rewards.

**Comment by tschoffelen** [comment]
Agreed on the simplicity of submitting a PR to our own repo :)

I'm very much open for transferring the rchain.cloud repo to the rchain org, but would prefer to keep it separate from the main rchain repo in that case, to make sure we can deploy quickly.

Added my vote now. Mind voting on the issue as well? Would appreciate it!

**Comment by dckc** [comment]
I don't mind which repo it's in, but I'd feel better if it were clear that code changes are getting reviewed.
