### ISSUE TITLE
May Core Development: Scala version of Rosette, RNode enhancements

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#708]
### Benefit to RChain coop / community

Build the Scala version of Rosette.
RNode enhancements in May

core development. cc @MParlikar 

_Estimated Budget of Task:_ $3,400.00
_Estimated Timeline Required to Complete the Task:_ 1 month: May
_How will we measure completion?_ Pull Requests are Merged. Measure of effort is story points. We pay $150.00 per story point in RHOC. The CoOp and board set the price of RHOC.

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
@MParlikar @KentShikama my work on CORE-410, https://github.com/rchain/rchain/pull/658 , was merged, but I'm struggling to understand whether it covers the whole scope. If it does, please close CORE-410 and support [budget and reward votes on this issue][1].

[1]: https://rewards.rchain.coop/index.php?-table=issue&-sort=num%20desc&-limit=30&num=708&title=&updatedAt=&state=&createdAt=&labels=#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-table%3Dissue%26-sort%3Dnum%2Bdesc%26-limit%3D30%26num%3D708%26title%3D%26updatedAt%3D%26state%3D%26createdAt%3D%26labels%3D%26-action%3Drelated_records_list%26-cursor%3D0%26-skip%3D0%26-mode%3Dlist%26-recordid%3Dissue%253Fnum%253D708%26-ui-root%3Dmain-content%26-relationship%3DRewards

**Comment by AbnerZheng** [comment]
@MParlikar I will complete issues ROS-330, ROS-234, CORE-524, summed up to 2400$ as issue#766 says.

**Comment by dckc** [comment]
Since @KentShikama and @tschoffelen voted for me based on just the rnode enhancements, our individual votes may look a little weird. But they're getting pretty close to the target: $2400 for @AbnerZheng and $1000 for me:

Title | Worker | Reward usd | Percent avg | Budget usd | Voter qty | Voters | Reward provisional | Budget provisional | Pay period | Labels
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
May Core Development Bounties: python node client,...... | AbnerZheng | 2657 | 77.91 | 3410 | 3 | AbnerZheng:j*3, dckc:m*7, yuhuanmocmoc:a*1 | 2657 | 3410 | 201805 | ["Development"]
May Core Development Bounties: python node client,...... | dckc | 1005 | 29.48 | 3410 | 5 | AbnerZheng:j*3, dckc:m*7, KentShikama:m*7, tschoff...... | 1005 | 3410 | 201805 | ["Development"]
