### ISSUE TITLE
RChain coop in Europe, Berlin

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#709]
## Brainstorm 

about the setup of RChain Cooperative in Europe, Berlin.
Edit [RChain Berlin Coop Info](https://docs.google.com/document/d/1QkdFbUaX-39BPDeJ0DaTggUpjiObohotyYIWWknzH-c/edit?ts=5aec629d#heading=h.mjd70wy8699q) in suggest mode.

_Estimated Budget of Task:_ **$[500]**  \
_Estimated Timeline Required to Complete the Task:_ **[4 weeks]**  \
_Measure of Completion:_ **[finalized document for coop suggestions]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by azazime** [comment]
While we're at it, its also important for us to include social media into the strategy,,it(social media influence on the global society) cannot be over emphasized. We can initiate a targeted AD system to penetrate Europe, Berlin.

**Comment by pmoorman** [comment]
@azazime social media for Europe should totally play into it, but I believe it deserves it's own issue. Let's keep this one on Governance. _If you feel inspired about social media strategy in Europe, open a separate issue for it!_

@lapin7 could you provide some more details about what exactly you're looking for in terms of contributions? What help are you seeking exactly? Which areas need research / attention?

I'll slap on the `needs-SMART-objectives` label for now.

**Comment by le-dawg** [comment]
I concur - Social Media requires continuous work and a strategy as well. I do not believe in a self-propelled social media campaign - that's a full time job (for now)

**Comment by lapin7** [comment]
I think [RChain Berlin Coop Info](https://docs.google.com/document/d/1QkdFbUaX-39BPDeJ0DaTggUpjiObohotyYIWWknzH-c/edit?ts=5aec629d#heading=h.mjd70wy8699q) is a dead document. The owner doesn't confirm changes.

**Comment by barneycinnamon** [comment]
Is this issue connected in any way to

**Comment by barneycinnamon** [comment]
Events obviously moved past this issue. I will close it now.
