### ISSUE TITLE
Translate 5 Medium blog posts to French

### ISSUE THREAD

**Issue by casanwugo** [rchain/bounties#711]
### For all issues
[Keep _italic_ labels, replace brackets with answer]

Original (English) Content
- <a href="https://medium.com/rchain-cooperative/welcome-kenny-rowe-c120ac55b404">Welcome Kenny Rowe!</a>
- <a href="https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6?source=---------3">Resonate and lifeID collaborate</a>
- <a href="https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82?source=---------2">RNode v0.3.1 introduces the RChain concensus protocol</a>
- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7?source=---------1">RChain Weekly Update (Debrief 75) — 02 May</a>
- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd?source=---------0">RChain Weekly Debrief / 9th, May 2018</a>     

 Translated (French) Content

- <a href="https://medium.com/p/78fe872b739e?source=user_profile---------7-------------------">Bienvenue Kenny Rowe</a>
- <a href="https://medium.com/p/48aad3d9c5aa?source=user_profile---------8-------------------">Resonate et lifeID collaborent</a>
- <a href="https://medium.com/p/d615b7be6e03?source=user_profile---------3-------------------">RNode v0.3.1introduit le protocole de concensus</a>
- <a href="https://medium.com/p/568fa26c1fc8?source=user_profile---------4-------------------">Mise à jour hebdomadaire de RChain (compte rendu 75) - 02 mai</a>
- <a href="https://medium.com/p/6e69fa359bf4?source=user_profile---------2-------------------">RChain weekly debrief - 9 mai 2018</a>

   Tasks

  ✔Copy the original (English) content to Medium blog as well as https://t.me/Rchain_Africa
  ✔Translate the content.
  ✔Check the spelling.
  ✔Review each other's work.
  ✔Have them reviewed by others with knowledge of English and French.
  ✔Post the translated (French) content to Medium blog, and also https://t.me/Rchain_Africa 

  Collaborators :
 - @casanwugo 70%
 - @philipandri002 30%
 
 

_Estimated Budget of Task:_ **$[1500]**  \
_Estimated Timeline Required to Complete the Task:_ **[12days]**  \
_Measure of Completion:_ **[100%]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyatPyrofex
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] significant reputation (e.g. a diploma) at stake; source: Diploma
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:

**Comment by casanwugo** [comment]
@truffard,,, I'm a fluent speaker. @Pionelle is really good with French though. Will have her replaced... Any suggestions from your end? Please help me out help.

**Comment by truffard** [comment]
@casanwugo .... I can help you out by reminding you the basic rules: @lapin7 said specifically that one must be a native speaker in order to take part in a translation issue. My recent experiences have shown that there are many valid reasons to this requirement: the technical knowledge involved for this type of document and the responsibilities attached to that can not be taken lightly, @Pionelle didn't pass the grade I'm sorry. The translated documents were incomprehensible. Also, you wouldn't be able to edit and review the work of a native speaker? @ICA3DaR5 @dckc why is it that we have to remind the same rules over and over again?

**Comment by casanwugo** [comment]
@truffard the idea is to reach out to mainly new members who joined through or are getting to know about RChain through the RChain Telegram Africa group  which has been very difficult for most to grasp because most articles are done in English whereas there are French speaking native of Africa descent.

**Comment by casanwugo** [comment]
@dckc... Thanks for that helpful reference packed with useful comments and information. Good to know!

**Comment by philipandri002** [comment]
@dckc #483 was truly educating....@truffard I think Casanwugo was only trying to proffer a solution to a little challenge that many are scared to attribute as a problem.

One unique challenge with Africa is the multi linguistic nature which happens to be their native and official language rather than English.
For example there are native French speakers in African and also Arabic..

However I think the RChain African Telegram must be able to make information not only accessible to Anglo phonic speaker  but Franco phonic speakers especially to the members who are just getting to know about RChain through the RChain Telegram group.

**Comment by ICA3DaR5** [comment]
@casanwugo Hello I am a guide here for translators, could you please answer my previous question?

**Comment by jasoncruzzy** [comment]
@casanwugo great work

**Comment by casanwugo** [comment]
@jasoncruzzy. Thank you.

**Comment by ICA3DaR5** [comment]
@casanwugo I don't think that would work. The blog posts should be posted on a blogging service, such us [Medium](https://medium.com/).

**Comment by casanwugo** [comment]
<a href="https://docs.google.com/document/d/1yiT3JUO-0aidXaxHzCD8eRBQJZJ3aTm_PY8h-GCEGTQ/edit?usp=drivesdk&ouid=115916130157516756180 ">Bienvenue Kenny Rowe</a>

**Comment by casanwugo** [comment]
@ ICA3DaR5... Here are the translated works done via google docs. Please kindly reassign reviewers so that contents can be posted to my personal medium page, and the links posted on the Telegram Africa group as well. Thanks!

<a href=https://docs.google.com/document/d/1yiT3JUO-0aidXaxHzCD8eRBQJZJ3aTm_PY8h-GCEGTQ/edit?usp=drivesdk&ouid=115916130157516756180>Bienvenue Kenny Rowe</a>
<a href=https://docs.google.com/document/d/1m-PEvDf9lYyvu4lzRoVNUnnruogQm4Ev1Pe80dquxO8/edit?usp=drivesdk&ouid=115916130157516756180>Resonate et lifeID collaborent</a>
<a href=https://docs.google.com/document/d/1xf87agTWZHi24nX5778go97C5SboQnZPOVvwzqIDIWk/edit?usp=drivesdk&ouid=115916130157516756180>RNode v0.3.1introduit le protocole de concensus</a>
<a href=https://docs.google.com/document/d/1OvVkd4yHYpCEafvVaMtbEt6hseS8MU2OwnTVDwftRQY/edit?usp=drivesdk&ouid=115916130157516756180>Mise à jour hebdomadaire de RChain (compte rendu 75) - 02 mai</a>
<a href=https://docs.google.com/document/d/17Zj8e0jeuOX8DWNoRmQaaqM_jq9AtiZxF_MTvkvCfiE/edit?usp=drivesdk&ouid=115916130157516756180>RChain weekly debrief - 9 mai 2018</a>

**Comment by casanwugo** [comment]
<a href= https://docs.google.com/document/d/1yiT3JUO-0aidXaxHzCD8eRBQJZJ3aTm_PY8h-GCEGTQ/edit?usp=drivesdk&ouid=115916130157516756180 >Bienvenue Kenny Rowe</a>

**Comment by casanwugo** [comment]
<a href="https://docs.google.com/document/d/1yiT3JUO-0aidXaxHzCD8eRBQJZJ3aTm_PY8h-GCEGTQ/edit?usp=drivesdk&ouid=115916130157516756180">Bienvenue Kenny Rowe</a>

**Comment by casanwugo** [comment]
@ ICA3DaR5... Here are the translated works done via google docs. Please kindly reassign reviewers so that contents can be posted to my personal medium page, and the links posted on the Telegram Africa group as well. Thanks!

 <a href="https://docs.google.com/document/d/1yiT3JUO-0aidXaxHzCD8eRBQJZJ3aTm_PY8h-GCEGTQ/edit?usp=drivesdk&ouid=115916130157516756180">Bienvenue Kenny Rowe
 <a href="https://docs.google.com/document/d/1m-PEvDf9lYyvu4lzRoVNUnnruogQm4Ev1Pe80dquxO8/edit?usp=drivesdk&ouid=115916130157516756180">Resonate et lifeID collaborent
 <a href="https://docs.google.com/document/d/1xf87agTWZHi24nX5778go97C5SboQnZPOVvwzqIDIWk/edit?usp=drivesdk&ouid=115916130157516756180">RNode v0.3.1introduit le protocole de concensus
 <a href="https://docs.google.com/document/d/1OvVkd4yHYpCEafvVaMtbEt6hseS8MU2OwnTVDwftRQY/edit?usp=drivesdk&ouid=115916130157516756180">Mise à jour hebdomadaire de RChain (compte rendu 75) - 02 mai
 <a href="https://docs.google.com/document/d/17Zj8e0jeuOX8DWNoRmQaaqM_jq9AtiZxF_MTvkvCfiE/edit?usp=drivesdk&ouid=115916130157516756180">RChain weekly debrief - 9 mai 2018

**Comment by casanwugo** [comment]
@ICA3DaR5 ,,, in reference to the last comment you made, i was able to create a personal medium page where the contents would first be posted to. But specifically making sure that the links gets to the targeted audience through Telegram Africa group and other social media. Please let me know if that would work?

**Comment by ICA3DaR5** [comment]
@casanwugo If you need a reviewer unfortunately you need to find him/her yourself. Asking on Discord would be a good start.

A new Medium account specifically for this purpose would be awesome!

**Comment by casanwugo** [comment]
- <"https://medium.com/rchain-cooperative/welcome-kenny-rowe-c120ac55b404">Welcome Kenny Rowe!</a>
- <a href="https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6?source=---------3">Resonate and lifeID collaborate</a>
- <a href="https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82?source=---------2">RNode v0.3.1 introduces the RChain concensus protocol</a>
- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7?source=---------1">RChain Weekly Update (Debrief 75) — 02 May</a>
- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd?source=---------0">RChain Weekly Debrief / 9th, May 2018</a>

**Comment by casanwugo** [comment]
- <a href="https://medium.com/rchain-cooperative/welcome-kenny-rowe-c120ac55b404">Welcome Kenny Rowe!</a>
- <a href="https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6?source=---------3">Resonate and lifeID collaborate</a>
- <a href="https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82?source=---------2">RNode v0.3.1 introduces the RChain concensus protocol</a>
- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7?source=---------1">RChain Weekly Update (Debrief 75) — 02 May</a>
- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd?source=---------0">RChain Weekly Debrief / 9th, May 2018</a>

**Comment by casanwugo** [comment]
@ICA3DaR5,, Thanks alot! You've been of great assistance.

**Comment by casanwugo** [comment]
@truffard, please review the translated documents in the comment section, so that they can be posted to Medium.Thank you.

**Comment by casanwugo** [comment]
- <a href="https://medium.com/p/78fe872b739e?source=user_profile---------7-------------------">Bienvenue Kenny Rowe
- <a href="https://medium.com/p/48aad3d9c5aa?source=user_profile---------8-------------------">Resonate et lifeID collaborent
- <a href="https://medium.com/p/d615b7be6e03?source=user_profile---------3-------------------">RNode v0.3.1introduit le protocole de concensus
- <a href="https://medium.com/p/568fa26c1fc8?source=user_profile---------4-------------------">Mise à jour hebdomadaire de RChain (compte rendu 75) - 02 mai
- <a href="https://medium.com/p/6e69fa359bf4?source=user_profile---------2-------------------">RChain weekly debrief - 9 mai 2018

**Comment by ICA3DaR5** [comment]
This one seems complete and reviewed. So it's complete!

**Comment by truffard** [comment]
@ICA3DaR5 At the risk of being deemed as a party pooper ,I guess Id better not make any comments on that translation work
