### ISSUE TITLE
Collaborating with Michiel Mulders

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#712]
**Introduction**: This effort was facilitated by a promptu request by @eedsilva on discord to get in touch with Michiel Mulders the author of "Comparism of Smart Contract platform" to do a technical walk through of RChain and to include RChain in his subsequent articles.
**About Michiel Mulders**: Michiel Mulder is a blockchain developer at The Ledger and technical writer for blockchain platforms; BigchainDB, Hyperledger fabric, Stella and Ethereum. 
**My effort** : I got in touch with him on LinkedIn and below is the outcome of our conversation..

> Thank very much Michiel, it's my pleasure to connect with you to get across to you the intentions of Rchain cooperative regarding your post on hackernoon " Comparison of Smart Contract Platform"https://hackernoon.com/comparison-of-smart-contract-platforms-2796e34673b7 . Am a member of RChain and as well a writer on its medium channel but not on technical issues. It would please the RChain community to see if you could do a technical walkthrough of the RChain cooperative platform and include us as well in your coming articles. I hope to get a reply soon about your thought on this, perhaps, there are conditions attached. you could let me know. Thanks https://developer.rchain.coop/ You can get in touch with our community using this links.
rchain.coop
Home
rchain.coop

Michiel Mulders reply:

> Hi Victor (Viraculous)
The article is doing very well and is ranking first on several keywords like smart contract comparison as well in Medium on certain blockchain technologies. 
So yes, I'm thinking about writing an extension or a new article where I feature some other platforms. But, indeed, I'm looking for funds to write it. 
I can as well do an independent article about RChain. Something like: problem description, solutions, RChain solution, how does it work / what makes it special and get into technical details.
I will need some info from your side. I'll prepare a couple of questions after reading the whitepaper.
For such an intensive article (technical analysis), I ask in BTC, ETH, any other major cryptocurrency or PayPal. I do not accept platform specific tokens.
The article will again be published on Hackernoon and my personal Medium. I take care of promotion on Reddit, Bitcointalk, and publish it on my LinkedIn (7k connections).
View Michiel’s profile Michiel Mulders
Generally I get 15 - 45k views and usually. I will continue to grow the next couple of months.

**Statistical Feedback**: The article is gaining momentum. So far for the month of June, It has ;
About 4k+1.8k(social view) views being read by about 1.6k. More marketing will be done around it.

**Targets**:
- [x] Get an established contractual agreement with Michiel Mulder.

- [x] Sort out relevant facts about RChain that will should be represented in the article.

- [x] A documented technical analyses of RChain. [HERE](https://docs.google.com/document/d/1ied52HFWY6894HhwVcIe61lj1CNWF7LIAMnZoy05Pcs/edit?usp=sharing)

- [x] Have the article published on all RChain channels and mediums.

**Article Title**: RChain — Multi-Threading Blockchain — Visa alike Scalability

**Measure of Completion**: The article about RChain published on various social medium.
**Suggested Budget**: $1240
https://medium.com/@michielmulders/rchain-multi-threading-blockchain-visa-alike-scalability-26107d7c920b
https://hackernoon.com/rchain-multi-threading-blockchain-visa-alike-scalability-26107d7c920b
https://medium.com/@vimirimious34/rchain-multi-threading-blockchain-visa-alike-scalability-ff865d0b8eb6
https://www.linkedin.com/feed/update/urn:li:activity:6408329536878055424
https://www.reddit.com/r/BlockChain/comments/8ofmep/rchain_multithreaded_blockchain_claims_to_handle/
https://www.linkedin.com/feed/update/urn:li:activity:6409312478047670272

**Comment by philipandri002** [comment]
@Viraculous great Job done. However how and were do we present our fact on RChain that we requested on the Task sections or do we present them here on the comment sections.

Thanks

**Comment by Viraculous** [comment]
@philipandri002 thanks. You can present them here and their links if possible. Although I have been able to sort some major facts.

**Comment by jasoncruzzy** [comment]
@Viraculous Good work

**Comment by kitblake** [comment]
@Viraculous Good networking. You wrote: 

>  "Suggested Budget: I personally would not like to suggest any budget now untill there is a measure of progress."

All Targets are checked. Do we have a measure now?

**Comment by Viraculous** [comment]
Yes @kitblake but I will like to keep the issue open till the decond half of this month so that I can upload the statistics of the audience it has attracted. I will also prefer the to claim my reward with the work done this month.

**Comment by Viraculous** [comment]
@kitblake, @pmoorman, @dckc, @Ojimadu @PatrickM727 @jimscarver and all who care about this fruitful effort, please  I would like to have your votes and budget support on this issue. Thanks

**Comment by Viraculous** [comment]
I added the video " What is RChain all about?" as a marketing effort forward.

**Comment by jimscarver** [comment]
It appears you effort @Viraculous was quite fruitful. Good job!

**Comment by Viraculous** [comment]
Yeah, thanks @jimscarver.
