### ISSUE TITLE
Maximum relative entropy (MRE) for quantifying and mitigating multifactor risk

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#713]
@jimscarver and I were discussing Trust Ratings and he brought up some experience at [Proven Security](http://www.provsec.com/), applying [maximum entropy](https://arxiv.org/abs/1603.00068) to trust.

I hope to learn more

## Benefit to RChain Membership or the RChain blockchain:

possible utility in smart contracts, including the RChain bounty system

_IOU more of a SMART objective_

Budget: TBD

*See [CONTRIBUTING.md](https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md) for details on budget and reward process.*

**Comment by jimscarver** [comment]
Our MRE repositors at https://github.com/ProvenSecureSolutionsLLC should be made public soon.  It is cool in that it integrates the powerful R statistical language as an interface but fails to use maxent stepwise during bayesian learning in the solution.

**Comment by jimscarver** [comment]
Iris diagram avatar of pseudo anonymous trust/risk factors relative to webs of trust quantified by MRE.
![irispaul](https://user-images.githubusercontent.com/3037201/40271268-e70e7618-5b68-11e8-8323-f1655550e201.png)

**Comment by billscarver** [comment]
We have code for this in the ProvenSecure Solutions private GitHub repository. Anyone interested in accessing the project should contact me at billw@provensecure.com...

**Comment by jimscarver** [comment]
@billscarver we only use open source code here. Make the repo public or have me made an admin. The development was funded under a public DARPA program and we are obligated to make it available on request as far as I know.

**Comment by dckc** [comment]
Well, perhaps I still _hope_ to pursue this, but open issues should represent things one _plans_ to pursue, and I would have to say that this is so far down on my TODO list that I don't see a plan.

Feel free to re-open it, @jimscarver .
