### ISSUE TITLE
EOS vs RChain Comparison 

### ISSUE THREAD

**Issue by jeremybeal11** [rchain/bounties#720]
@PatrickM727 brought me onto the project to write up usecases for competitors and comparing them to RChain. 

Here is the one i did with EOS: (EOS)[https://docs.google.com/document/d/1qoio4TrrzLzRpzcUv8cR1Q49BS3G2r0xUzHnTknZ6b8] 

This was my first case study that we were going to use with the bounty program. 
Hours spent: 13
Rate proposed: $40hr
Proposed bounty: $520.00

### For all issues
[Keep _italic_ labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

_Estimated Budget of Task:_ **$[000]**  \
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**  \
_Measure of Completion:_ **[measure]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in (the target language)
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by PatrickM727** [comment]
Good job, 

I am closing this because this leg of the work has been complete. 

if we would like to expand on it as a community, please open up another issue or refer to an existing one.
