### ISSUE TITLE
Translation Guides' Label Report (Jan - May 2018)

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#721]
Within the RChain Bounty Rewards contribution system, issues (aka tasks or small projects) are divided into 10 different “labels”. Label Guides help contributors align their contributions with the needs of our Cooperative by making suggestions about quality and value to our Cooperative. The Lead Guide within each label is responsible for a monthly overview report, including a high level financial summary and an overview of what issues generally are being addressed.

**Benefits to the RChain Community** 
Transparency, budgeting. 
 
**Format** 
Our current iteration is: [Translation Guides' Label Report (May 2018)](https://docs.google.com/document/d/1yv4NhhRYD8lPKR4ZWd5chEXC1ELEWrNrIRkfyXz9zhs/edit?usp=sharing)
PDF, as of 05/28/2018: [Translation Guides' Label Report (May 2018) - PDF](https://drive.google.com/open?id=1wP-Ohz4DiEHu_eiBr_RfwWHzwDILSerh)
Data source spreadsheet: [Translation Issues by Id, May 2018](https://docs.google.com/spreadsheets/d/1qiRJB399ypR-G6dG9i72hfQuhaWZuuh4ajI5R7_ks9A/edit#gid=0)
 
**Time Frame and Measure of Completion**
May 9-23. Completion requires full listing of issues reviewed, and financial summary. 
 
**Team and Suggested Reward**
@ICA3DaR5 (35%), @michaelizer (20%), @zero-andreou (35%), @allancto (10%) 
Valuation model: we are beginners in this domain of reporting and learned as we went along. We feel that $15/hour is a reasonable reward for the time that we spent. We spent 180 hours total. 
180 hrs * $15/hr = $2700 suggested reward
 
**Related issues, Demo’s and References**
https://github.com/rchain/bounties/issues/678
https://github.com/rchain/bounties/issues/672
https://github.com/rchain/bounties/issues/483

_Estimated Budget of Task:_ **2700**  \
_Measure of Completion:_ **Complete**

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by allancto** [comment]
We are going to say this is complete as of right now, with the following IOU: 
1. report issues from April and March
2. double check for any factual errors.

**Comment by allancto** [comment]
I'm also cross referencing zoom meeting "guiding guides" Friday 8am PDT 2018-05-25, agenda: 
https://docs.google.com/document/d/1NbEku_ye40H0WTBA3-7YibtjYuSFvbq_BDxk4e-900E/edit?ts=5b005aa4

**Comment by ICA3DaR5** [comment]
Issues from April and March are now reported at [Translation Guides' Label Report (May 2018)](https://docs.google.com/document/d/1yv4NhhRYD8lPKR4ZWd5chEXC1ELEWrNrIRkfyXz9zhs/edit?usp=sharing)

**Comment by ICA3DaR5** [comment]
Double check is completed!

We sub-categorized the **Under Investigation** section and revisited the issues for a possible resolve.

**Comment by dckc** [comment]
As discussed with @michaelizer and others, I'd like us to keep working on this until we have a summary at the top and until we have some conclusions or next steps on the "under investigation" items.

**Comment by AyAyRon-P** [comment]
Hi @ICA3DaR5

What is the status of this issue? Is there any update to the work? Please advise what items remain or close this issue out if no action items remain

cc @pavlos1851

**Comment by ICA3DaR5** [comment]
Hi @AyAyRon-P 

There is no update. I don't know how to proceed with this.

See [@dckc 's comment above](https://github.com/rchain/bounties/issues/721#issuecomment-395812550).

**Comment by dckc** [comment]
Since #678 is done, I'm content for you to close this.

**Comment by pavlos1851** [comment]
Closing this issue.
