### ISSUE TITLE
Translate the Medium blog posts to Chinese Part 3

### ISSUE THREAD

**Issue by yuhuanmocmoc** [rchain/bounties#730]
I will translate these Medium documents into Chinese with @rjl493456442.
1.[RChain Weekly Update (Debrief 77) -16 May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-77-16-may-2018-5ecfa806933f) [1476 words]
2.[RChain Weekly Debrief | 9th, May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd) [2601 words]
3.[RChain Weekly Update (Debrief 75) — 02 May](https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7) [1722 words]
4.[RNode v0.3.1 introduces the RChain consensus protocol](https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82) [766 words]
5.[RChain Weekly Update(Debrief 78) — 23, May](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-78-23-may-c919bf19a8ed) [1838 words]

_Estimated Budget of Task:_ **$[1850]**  \
_Estimated Timeline Required to Complete the Task:_ **[7 days]**  \
_How will you measure completion?_ **[upload to google doc and post to Wechat official account of China and Medium]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in (the target language)
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [x] a track record of quality work on rchain bounties: #242, #246, ...
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:xx

**Comment by Preshcode** [comment]
A wonderful idea for the Chinese speaking users of the platform. Thumbs up.

**Comment by yuhuanmocmoc** [comment]
all the translation Medium blogs have been uploaded to [Google doc](https://drive.google.com/open?id=1SoO3bcXzJt3rO1me-Kr9a-P_Kb7iD_6A)

**Comment by yuhuanmocmoc** [comment]
we will post them to the public Wechat official account for a few days.

**Comment by rjl493456442** [comment]
@pmoorman Hey, can you help us to allocate a budget in the bounty system? Thanks!

**Comment by ICA3DaR5** [comment]
Voted for the 5 blog posts posted. A budget of $1850. I'll leave this issue open, in case you decide to finish the work and add a budget for the month of June.

**Comment by yuhuanmocmoc** [comment]
@ICA3DaR5 ok

**Comment by AyAyRon-P** [comment]
Hi @yuhuanmocmoc 

What is the status of this issue? Is there any update to the work? Please advise what items remain or close this issue out if no action items remain

cc @pavlos1851

**Comment by zsluedem** [comment]
@AyAyRon-P This issue has been finished in June and the team has already received the rewards. All the articles has been already released in their Wechat account. I am going to close it now. Feel free to comment.
