### ISSUE TITLE
RChain Weekly Update (Debrief summary) maintenance 

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#742]
This is for work done for the month of June. As instructed by @PatrickM727, I write the textual rundown/ summary of the RChain Weekly Debrief blog post which is being uploaded on medium every Monday on agreed terms of $250 per debrief. 
So far for the month of June, There are four debriefs:
[Debrief 80](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-80-june-6-2018-19927f88a3c5)
[Debrief 81](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-81-13-june-2018-415b4318b02b)
[Debrief 82](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-82-20-june-2018-6064dba8769f)
[Debrief 83](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500)
Budget: $250*4 = $1000

**Comment by David405** [comment]
This seems to me like a mistake

**Comment by PatrickM727** [comment]
Where is the mistake?
