### ISSUE TITLE
Curating event list for RChain

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#743]
As requested by @PatrickM727, I will be curating the list of events for both blockchain and non-blockchain events on a monthly interval to ensure proper planning and preparations for the events.

Target:

- [x] Create [Gsheet ](https://docs.google.com/spreadsheets/d/1qh0daH_0KeFTQC9I6xE5RbRBsCx8XIAzZlP1cl4wGCQ/edit?usp=drivesdk&ouid=117345271212327655578   )for the events

Get the list of veritable events for RChain (10 Events monthly) for;

- [x] July
- [x] August
- [x] September
- [x] October
- [x] November
- [x] December

_Estimated Budget of Task:_ **$[200]**
@Viraculous 10% @kaka56. 90%

**Comment by David405** [comment]
And this too

**Comment by Valentine-Mario** [comment]
The list is still empty. It should be publicly accessible to get a variety of events updated. Eg the upcoming Rchain Africa meet up hasn't been added to the list

**Comment by kaka56** [comment]
@Viraculous @PatrickM727 The Gsheet now contains curated event list for Rchain. I will like you to check it out.

**Comment by Viraculous** [comment]
@kaka56 you did a good work.  Amongst the conferences in the month of **July** I recommend:

[Blockchain World Conference](http://bwcevent.com/) July 11-13
[Blockbeats: Blockchain conference](https://block-beats.com/) July 19-20
[Open:2018](https://2018.open.coop/) July 26-27

Parametre for recommendation:
Expected attendance
Sponsors
partners
Locality

**Comment by Ojimadu** [comment]
@Viraculous @kaka56 I think it would be better to split the sheet into two on the same file, one for blockchain-centric events and the other for non-blockchain centric event

**Comment by Viraculous** [comment]
ok @Ojimadu

**Comment by Viraculous** [comment]
Recommended event to attend for the month of August
**[Blockchain Summit](http://blockchainsummitsingapore.com/)** 
Date: 28th, August.
Place: Singapore Asia
Audience: 700+
