### ISSUE TITLE
upload videos to Chinese website on May

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#745]
Below is the videos I uploaded to Chinese video website.

1. ['Modeling Decentralized Organizations' w_ Rich and Nati from TheHum.org](https://www.bilibili.com/video/av23336213)
2. [Patterns for Decentralized Organization](https://www.bilibili.com/video/av23339238)
3. [Rchain Community Debrief 77](https://www.bilibili.com/video/av23627345)
4. [Rchain Community Debrief 76](https://www.bilibili.com/video/av23767106)
5. [革命性的计算机理论实践 - RChain技术浅析](https://www.bilibili.com/video/av23767359)
6. [Rchain Community Debrief 78](https://www.bilibili.com/video/av23851650)
7. [Reflective Ventures & Blockchain at Berkley presents Rchain](https://www.bilibili.com/video/av23101507)
8. [Day 1 - Opening Remarks - Introduction](https://www.bilibili.com/video/av24092743)
9. [Day 2 - Breakout Session Planning - Medha Parlikar](https://www.bilibili.com/video/av24093014)
10. [Day 2 - Consensus - By Mike Stay Prepared by Michael Birch](https://www.bilibili.com/video/av24095380)
11. [Day 2 - Namespaces - Mike Stay & Kyle Butt](https://www.bilibili.com/video/av24097349)
12. [Day 2 - Payment Semantics - Greg Meredith and Joe Denman](https://www.bilibili.com/video/av24099130)
13. [Day 2 - Breakout - Sugar Loafa](https://www.bilibili.com/video/av24104282)
14. [Day 2 - Rchain State - Kyle Butt](https://www.bilibili.com/video/av24129072)
15. [Day 4 - Rholang Language Syntax and Semantics - Kyle Butt](https://www.bilibili.com/video/av24131180)
16. [Day 2 Breakout - Canyon Rooms](https://www.bilibili.com/video/av24132953)
17. [Day 4 - RChain Rev Rhoc Swap - Nash Foster](https://www.bilibili.com/video/av24133963)
18. [Day 3 - Breakout Session Planning - Medha Parlikar](https://www.bilibili.com/video/av24136728)
19. [Day 2 Breakout Recap - Medha Parlikar](https://www.bilibili.com/video/av24135633)
20. [Day 3 - Communications - Pawel Szulc & Nash Foste](https://www.bilibili.com/video/av24137710)
21. [Day 3 - Reflective Ventures](https://www.bilibili.com/video/av24139126)
22. [Day 3 - Scala Dialect - Pawel Szulc](https://www.bilibili.com/video/av24142416)
23. [Day 4 - RChain VM - Greg Meredith & VM Developer Team](https://www.bilibili.com/video/av24143409)
24. [Day 4 - Understanding Protocol States in Casper - Vlad Zamfir](https://www.bilibili.com/video/av24147338)
25. [Day 4 - State of the Rchain Project - Nash Foster & Mike Stay](https://www.bilibili.com/video/av24159135)
26. [Day 5 - RChain Roadmap - Medha Parlikar](https://www.bilibili.com/video/av24159640)
27. [Day 5 - Tokenomics - Jon West](https://www.bilibili.com/video/av24166857)
28. [Day 3 - Storage Layer - Henry Till](https://www.bilibili.com/video/av24174618)
29. [Rchain Communiy Debrief 79](https://www.bilibili.com/video/av24176771)
30. [Day 3 - Virtual Machine - Timm Schäuble & Keith McQueen](https://www.bilibili.com/video/av24178220)
31. [Day 5 - Web Applications on RChain - When Will Relevant Features Be Available](https://www.bilibili.com/video/av24180499)
32. [Day 5 - The RChain Blockchain Structure - Michael Birch & Kent Shikama](https://www.bilibili.com/video/av24187981)
33. [Day 4 - Business Strategy and Perspective](https://www.bilibili.com/video/av24188927)
34. [Day 4 - The Web is Under Threat Can RChain Answer - Dan Connolly](https://www.bilibili.com/video/av24191250)
35. [Introduction to the design of computational calculi 01](https://www.bilibili.com/video/av24198018)
36. [Day 5 - Communications - Pawel Szulc & Nash Foster](https://www.bilibili.com/video/av24199335/)
37. [Day 4 - Namespaces - Mike Stay & Kyle Butt](https://www.bilibili.com/video/av24200135/)
38. [Day 5 - Payment Semantics - Mike Stay & Joe De](https://www.bilibili.com/video/av24202126/)
39. [ Day 4 - RChain Storage Layer - Medha Parlikar &](https://www.bilibili.com/video/av24203122/)
### For all issues
[Keep _italic_ labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

_Estimated Budget of Task:_ **20*39$[780]**  \
_Estimated Timeline Required to Complete the Task:_ **completed already**  \
_How will you measure completion?_ **[completed already]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by zsluedem** [comment]
The budget may change a little bit later. A more detailed metrics about the video management in #736 may come out.

**Comment by pmoorman** [comment]
@zsluedem would you elaborate how you come to the $780 budget?

What actual actions/tasks were performed under this issue? Is it just a matter of uploading those videos, or did you do any other work on the videos, too? 

For instance: who made the subtitles to all these videos?

$780 seems pretty steep for just uploading a bunch of videos, but maybe I'm missing something! 

Let me know, and I'll cast a vote on the work, too. For now I've put in $200, but maybe I'm missing things that justify the $780!

**Comment by zsluedem** [comment]
@pmoorman Yeah~! I'd love to explain it about that.
I would tell you the process of uploading one video to Chinese website.First, I have download the video from Youtube and also download the subtitle. Because the Chinese video website is not convenient as Youtube. You can not just upload the subtitle to the video and display it. It is not gonna work in these video website. So I have to use some kind of software(`Arctime` is what I am using) to bake these subtitles into the videos which takes most of the time and the computer resources .Once the videos are done , I upload them to the websites.

From all the processes above, using the to remake the video takes a lot of time and computer resource. For a half-hour video ,it takes me about half an hour to do it . So for 40$ an hour reward metrics, I take about 20$ for one video(almost every video is 30-minute long but not all.Some  are longer and some are shorter).

And also I'd love to discuss the metrics for this kind of work. Feel free to discuss it.

**Comment by pmoorman** [comment]
Oke, I see what you mean. Glad that you elaborated. In that case, let me update my votes
