### ISSUE TITLE
M> Wechat official account for 201806

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#748]
### Benefit to RChain

The same as #258

In China, WeChat Official Account is content publishing platform similar to Medium. WeChat users in China receive all relevant content push by subscribing to the Official Account.

Taking into account that in China, WeChat is by far the most active social software, with more than 900 million users. Therefore, the promotion of RChain through WeChat Official Account will play a very good effect.

In the past month, me and my teammates post 12 articles to the Wechat official account to spread Rchain's Idea.
**Most of the articles are the rchain medium post translation. Besides, we also upload RChain team latest progress** 

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[3000]**
_Estimated Timeline Required to Complete the Task:_ **[4weeks]**
_How will we measure completion?_ 

**Please follow our account by scanning the QRCode below. You can check all posts uploaded by us in the past several months;**

![image](https://user-images.githubusercontent.com/5959481/40884149-466c961a-6741-11e8-85a1-b4570098935b.png)

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #258
       - [x] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by linsheng9731** [comment]
Thank you very much for your work!

**Comment by rjl493456442** [comment]
@pmoorman Hey, can you help us to allocate a budget in the bounty system? Thanks!

**Comment by rjl493456442** [comment]
Attention, since the budget for 201805 can not be allocated for the time being, so i allocate the budget at the #632 .
