### ISSUE TITLE
Translate rholangtut-0.3.md to Chinese

### ISSUE THREAD

**Issue by yuhuanmocmoc** [rchain/bounties#749]
## Original (English) Content
[A Rholang tutorial](https://github.com/rchain/rchain/blob/master/docs/rholang/rholangtut-0.3.md)

## Collaborators
@rjl493456442 @linsheng9731 @yyh1102 @RowlandZhou 

_Estimated Budget of Task:_ **$[1200]**
_Estimated Timeline Required to Complete the Task:_ **[7 days]**
_How will we measure completion?_ **[100%]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: ____
       - [x] a track record of quality work on rchain bounties: #242, #246, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by rjl493456442** [comment]
@pmoorman Hey, can you help us to allocate a budget in the bounty system? Thanks!

**Comment by yuhuanmocmoc** [comment]
the translation have been uploaded to [Google doc](https://drive.google.com/file/d/1RcWtbdQEtZMkHIq4oCUCXPGu4azImvSw/view?usp=sharing) and we have posted it to Wechat official account of RChain.

**Comment by ICA3DaR5** [comment]
@yuhuanmocmoc 

1. As far as I know rholangtut-0.3 is obsolete, it seems to have been removed from the repository.
2. In the future you need to create a Pull Request for the respective repository.

**Comment by dckc** [comment]
@ICA3DaR5 please add a budget vote to clarify whether you agree with the suggestion of $1200.

@Mervyn853 perhaps you have an opinion on the impact of this translation?

**Comment by ICA3DaR5** [comment]
@dckc #802 will be updated today, with votes, including this issue.

**Comment by ICA3DaR5** [comment]
Since the file is obsolete and there was no Pull Request submitted, the translation guides are going to vote a budget of $200.
