### ISSUE TITLE
Promote Rchain to Chinese universities

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#750]
### Benefit to RChain

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:
As far as I know, there are already US study groups and Africa study groups(#681) for Rchain. China also has many universities. I think getting the students in China involved with Rchain would make a great influence to Rchain.Maybe we can find some potential dapp developers for Rchain.

*Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ) to align your contribution with goals of the RChain cooperative.*
@pmoorman might want to have a look at this.
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*
1. [X] find some people who have resources in China to help promote Rchain
2. [] get a students study group

_Estimated Budget of Task:_ **$[1000]**(not sure about this)
_Estimated Timeline Required to Complete the Task:_ **[4weeks]**(it might be long way work)
_How will we measure completion?_ **[not clear now]**

**Comment by zsluedem** [comment]
I have already get in touch with some people in China.

1.I have talk to one man who have conntact with some publishers. These publisher all have cooperations with about 600 universities.

2.There is another man who knows a lot people in University like [University of Science and technology of China](http://en.ustc.edu.cn/) and [Peking University](http://english.pku.edu.cn/) .etc. He has a really good friend  who is Director of Information Security department in University of Science and technology of China.

It seem they don't have any github accounts.Try to ping them later.

**Comment by nonnykul** [comment]
This work should be geared towards adding RChain to various Research work in the respective universities.

**Comment by zsluedem** [comment]
I have talked to Mr. Shang today. And he has connection with the  stream room in the Tsinghua University, one of the best universities in China. He said we could make a live stream to talk about Rchain which would broadcast to about 400-700 people online and the live stream can also be reviewed by their Wechat public account which has about 200000 subscribers.  He wants to charge for this about 3000 dollors.And I don't know if it is a good deal.

**Comment by azazime** [comment]
Not just getting students involved on this,  I believe or suggest you target IT inclined students who will easily understand what rchain stands for and it's importance. So approaching more of the students in the IT departments of such universities gives your work direction. @ pmoorman

**Comment by lapin7** [comment]
@azazime what's your email?

**Comment by azazime** [comment]
andrewasamonye@yahoo.com

**Comment by zsluedem** [comment]
@azazime Yes . I am trying to do that~!

Now report the work I have done these days. 
I have reached out one of my best friend who is from Beijing University of Posts and Telecommunications which lead to build the GFW in China :). It is a very strong university on the IT area in China. I have asked him to post a introduction about Rchain in the bbs forum of his university. Looking forward to get some feedback there.

**Comment by nonnykul** [comment]
@zsluedem,nice updates on your work, onboarding IT university students is a progressive work that requires time and more research.

**Comment by zsluedem** [comment]
@feichashao was one of the students in  University of Science and technology of China who is now working in [Redhat](https://www.redhat.com/en). He helped me with the bbs posting. Although the bbs posting has been already 4 days ago, not really too many feedbacks. Trying to explore other ways.

**Comment by azazime** [comment]
@zsluedem what's your personal email so we can discuss on collaborating

**Comment by zsluedem** [comment]
@azazime Do you have a discord? Find me on will#8671

**Comment by zsluedem** [comment]
I have talked with @rjl493456442 today. He is doing his master degree on [Zhejiang University](http://www.zju.edu.cn/english/). He is maintaining one of the Wechat official account with some other students in Zhejiang University.

He told me that there is Blockchain club in Zhejiang University. And now we are discussing some promotion plans about Rchain. Maybe more details would come up soon.

**Comment by zsluedem** [comment]
Recent update for this issue, I have talked to @AbnerZheng and @cenyuhai if they have time to be a representer for a meetup or something. But they are both really busy these days.

I talked with @rjl493456442 and @yyh1102 who is the head of the Blockchain club in Zhejiang University. @yyh1102 has told me athat it is ok to borrow a class room or something in Zhejiang University for a meetup. But the summer vocation is coming and most of the students are not in the university so we haven't decided about the time for the meetup.

**Comment by allancto** [comment]
@zsluedem are any of these people interested in working on #788 Smart contracts for medical data sharing
or #789 User driven RChain bounty system dashboard development, or #755 Design of Computational Calculi?

**Comment by pmoorman** [comment]
@zsluedem this looks like great work overall. Can you propose a budget that seems reasonable to you for this month's work here?

**Comment by zsluedem** [comment]
@pmoorman I suggest 400$ budget for this month. For this month, we just made some discussion work and made some connection with some university and find some potential cooperators in School.

**Comment by zsluedem** [comment]
Not really working on this one in July.

**Comment by pmoorman** [comment]
@zsluedem can you post an update here on the progress for July? 

Again: I would appreciate someone more initiated on these matters to suggest what they think is an appropriate budget allocation here.

**Comment by zsluedem** [comment]
@pmoorman No reward this month is appropriate. 

I have reached to a student in Shenzhen University in July. But we don't talk so much . I have been busy with some other things. I am busy with the Rchain Asia this month . I will spend more time on this one in August.

**Comment by AyAyRon-P** [comment]
Hi @zsluedem 

Is this still ongoing? Are there any updates? Do we need to vote on this for the month of August?

**Comment by zsluedem** [comment]
Ok. Recent update for this one~!

Ciwei Invest might offer help on this one in the future. They have already been in touch with some universities in China. But it is still ongoing with the things. I don't know if I should be rewarded on this one in August because there are no results right now.
