### ISSUE TITLE
8 Concurrent Workgroups following Designing Computational Calculi 1-4

### ISSUE THREAD

**Issue by allancto** [rchain/bounties#755]
### Purpose
A workgroup is a group of members who follow the Computational Calculii workshop each week AND do all of the exercises and compilation AND provide a translation of the videos into a language other than the original OR provide a written guide in English that is usable by secondary school students. 

1. Repo with code following the videos

2. Translation or Tutorial

3. Feedback (how understandable are the videos, how might they be improved? Questions and answers to help viewers? discussion of resources or background materials referred to in the videos, and what additional resources might be helpful?)

Suggested Guides: @ICA3DaR5, @leithaus, @kennyrowe, @michaelbirch, @Jake-Gillberg, @jimscarver, (and all attendees of the workshop). 

Resources: 
https://groups.google.com/forum/#!forum/rchain-collaborative-learning/join 
https://github.com/RChain-Collaborative-Learning/Welcome 
https://github.com/RChain-Collaborative-Learning/Introduction-to-the-Design-of-Computational-Calculi 
*Help wanted* these annotated transcripts are only partially done, if any team wants to take this over please let me know:
https://drive.google.com/open?id=1x_9mFtsQqck358U9-PsHUMcdB7LBI7lP
https://www.youtube.com/watch?v=50z-TP0_HEA&index=7&list=PL4WLgebOMwp04qr4mLKmKv90c9gLsDa21
*Help wanted* if anyone wants to write a google docs style elucidation or opinion please feel free to add to the folder DoCC Elaborations, Essays and Viewpoints:
https://drive.google.com/open?id=1x_9mFtsQqck358U9-PsHUMcdB7LBI7lP

### Benefit to RChain
Cultural literacy around our fundamental computational and scientific models. 

### Budget and Objective
_Estimated Budget of Task:_ **<= $24000**
Suggested Budget: up to $3k/ workgroup
_Team 1: @zsluedem (guide) @Whisker17 
_Team 2: @David405, @nonnykul, @valentine-mario (guides) @ibesoft11 
_Team 3: @golovach-ivan (guide) @qelentium 
_Team 4?: 

_Estimated Timeline Required to Complete the Task:_ **4 weeks**

_How will we measure completion?_ 
**1. Translation or Tutorial for videos 1-4, posted**
**2. Repo with workshop's code, discussion, questions, link posted**
**3. Feedback and Suggestions posted (how understandable are the videos, suggested improvement)**
**4. Workshop Homework:**
https://github.com/RChain-Collaborative-Learning/Introduction-to-the-Design-of-Computational-Calculi/issues/1

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by tcezi** [comment]
Can explain how u arrived at dis budget

**Comment by allancto** [comment]
@tcezi sure, $3000 is my estimate of what it would align the interests of a small group to spend 1 month working on 4 videos to produce something of $3000 value to our Cooperative. 

Are you interested in forming a group and working on it?

**Comment by kennyrowe** [comment]
I do not consider video translation a good use of resources at this time.

**Comment by golovach-ivan** [comment]
@allancto, hi
I want to participate in this task. I can translate video in two languages (native speaker): Russian and Ukrainian.
---
Questions:
1) Do I have to create a team or can I do everything alone (i personally have enough expience)?
2) If we do this work for two languages, then we will have two translations of the video, but only one comments on the video and one code in repo. On what budget can we expect in this case?
3) In what form is it necessary to translate the video (the same video but mounted with russian voices OR only add russian subtitles OR something else)?
4) I was late connected, after two lectures had already passed. I looked them up in the record, but I did it offline (did not attend online). Does it affect something?

**Comment by zsluedem** [comment]
@allancto Because you have suggest a really big amount of budget of this issue. I think you should provide a more details about your goals.(What we call YOU-NEED-SMART-OBJECTIVE)
I suggest you should divide this issue into smaller issues which we can do it step by step which would make goals more clear.

**Comment by jimscarver** [comment]
@kennyrowe  Do you consider video translation to be a good use of resources at some later point of time? If so how does it serve us to just keep the rhoc in the treasury when it could have been used for useful purpose?

Is it an issue that not many students of math don't speak english well? If not, why not engage them sooner rather than later? We will spend the rhocs sooner or later.

**Comment by allancto** [comment]
@tcezi @kennyrowe this is not a translation project, it's to form local workgroups to follow and understand the first four talks in Introroduction to the Design of Computational Calculi. 

@kennyrowe, thanks for your comment. One of the central roles of Guides in our bounty system is to provide exactly this feedback: what is the likely value of this project to our Cooperative? Do you feel it's likely to be rewarded or not? This question is critical to potential contributors, because we look to you to assess exactly this, whether the value to our Cooperative is in line with the time and effort required to participate. Potential contributors need to decide whether to engage and contribute to this project and whether they feel their participation is likely to be rewarded, and use your assessments here to make their personal choices of how to spend their time and effort. 

Why I think it's worthwhile is simple. Cultural literacy, which is exemplified by the Design of computational calculi workshop, is of enormous value to our Cooperative. A good indicator of the potential value is the simple fact that yourself, @leithaus @michaelbirch, and other attendees of the main workshop are devoting their time and energy to it. The goal of this project is to develop workgroups concurrent to the main one. @kennyrowe does the clarification (not a translation project) and explanation (why it's worthwhile) make this project and proposed budget seem to you to be properly aligned with value that might be provided to our Cooperative? 

@zsluedem, you also ask a good question, what are the SMART objectives that might apply here? I've already tried to do this in describing components 1,2,3. I invite you and others to suggest and add objectives which may be more specific, measurable, actionable and so on. 

@tcezi , you suggest that the budget of $3000 for building a workgroup and following these talks for a month is high, I can certainly accept that as a possiblity although I'd guess others might suggest it's low! These lectures seem to me quite "advanced" and will require a great deal of time, effort, organization, programming, googling references, and learning how to articulatie the concepts involved. If anything, I would say $3000 is a low budget, offset by the fact that a participant who really is able to learn this material will acquire important knowledge and marketable skills. 

@golovach-ivan this is definitely to be a workgroup project and not an individual one, just as the main workshop is designed to foster cooperative study, communication, and working together in teams.

**Comment by JoshOrndorff** [comment]
I'd love to get involved here. I don't know any languages well enough to translate, but I do have lots of highschool CS teaching experience and would love to help contribute to tutorial, lesson plans, more detailed explanations etc.

This could actually also benefit Greg and his audience as well if instead of detouring to cover topics like outer product, he could say he'll defer that to us.

Regarding bounty, I agree with @allancto that $3k per group is about right assuming groups of 3 to 4 people for four weeks work. If the total $24k seems high, perhaps we could adjust the number of work groups?

**Comment by Jake-Gillberg** [comment]
I have been trying to organize an effort here: https://github.com/RChain-Collaborative-Learning/Welcome , and am willing to accept contributions with the agreement of a price to be payed, most likely and immediately by the bounty system, but by other methods of revenue generation as well: https://github.com/glenbraun/CollaborativeLicense/ . It would be great if these efforts are combined.

**Comment by JoshOrndorff** [comment]
RChain-Collaborative-Learning is a wonderful project. I've contributed a little, and learned a lot. It really would be nice to see the efforts merged.

**Comment by allancto** [comment]
@Jake-Gillberg @JoshOrndorff this is awesome, I posted the links above under "resources", @zsluedem @David405 @golovach-ivan @tcezi please check them out. WAIT-- @golovach-ivan has ALREADY been checking them out and POSTING questions in the Collaborative Learning forum 👍 
https://groups.google.com/forum/#!forum/rchain-collaborative-learning/join

**Comment by David405** [comment]
@allancto I have checked it out and joined the group

**Comment by Valentine-Mario** [comment]
Currently I and @david405 are working on a Google document to introduce newbies to Rspace and rholang. How can we add our contributions to this main document??? Because our guide is mainly targeted at African developers.

**Comment by allancto** [comment]
@Valentine-Mario perhaps create a gdocs folder for this and other documents or a github repo and share the link the folder or repo?

**Comment by Valentine-Mario** [comment]
Okay that would be a good idea.

**Comment by Valentine-Mario** [comment]
The project ought to last for about 2-3 weeks. When the course work is ready, we would share it to the community.

**Comment by qelentium** [comment]
I want to be in group #3 with @golovach-ivan

**Comment by ibesoft11** [comment]
@allancto hi, I am also helping @Valentine-Mario and @David405  on the document guide to introduce newbies to Rholang and RSpace. I have experience developing tutorial guides for African developers. I want to be in group #2. 
cc @Valentine-Mario @David405 @nonnykul

**Comment by nonnykul** [comment]
Hey guys, check out [A brief Introduction to the design of computational calculus](https://docs.google.com/document/d/1ic7yCa37Jjx9l6UBpoFJf8o6CZzmEwtRBvfUj81lLvw/edit)  

cc: @allancto @jimscarver @Jake-Gillberg

**Comment by qelentium** [comment]
Good job @nonnykul!

**Comment by golovach-ivan** [comment]
I create a [little internal Scala DSL](https://github.com/golovach-ivan/Computational-Calculi/tree/master/src/main/scala/net/golovach/dcc) for building stream of all correct terms in any BNF-gramma.

Example:
* import some utils
```scala
  import net.golovach.dcc.LangLib._
  import net.golovach.dcc.StreamLib._
```

* define types (Process, Channel) and productions (∅, Par, Lift, Input, Drop, Quote) for RHO-Calculi
```scala
  sealed trait Process
  case object ∅ extends Process
  final case class Par(p: Process, q: Process) extends Process
  final case class Lift(x: Channel, p: Process) extends Process
  final case class Input(c0: Channel, c1: Channel, p: Process) extends Process
  final case class Drop(c: Channel) extends Process
  sealed trait Channel
  final case class Quote(p: Process) extends Channel
```

* define BNF-like generators
```scala
  def P: Stream[Process] =
    ∅ #:: ((Par ⊲ (P, P)) ⊕ (Lift ⊲ (C, P)) ⊕ (Input ⊲ (C, C, P)) ⊕ (Drop ⊲ C))
  def C: Stream[Channel] =
    Quote ⊲ P
```
**Thats all!**

If you want check you work
* define mapping (Process | Channel) => String
```scala
  def show(pc: Any): String = pc match {
    case `∅` => "∅"
    case Par(p, q) => s"(${show(p)}|${show(q)})"
    case Lift(c: Channel, p: Process) => s"${show(c)}!(${show(p)})"
    case Input(c0: Channel, c1: Channel, p: Process) => s"(${show(c0)})?(${show(c1)}.${show(p)})"
    case Drop(c: Channel) => s"*(${show(c)})"
    case Quote(p: Process) => p match {
      case `∅` => "@∅"
      case _ => s"@(${show(p)})"
    }
  }
```

* Run it
```scala
P take 100 foreach(p => println(show(p)))
```
```
> ∅
> (∅|∅)
> *(@∅)
> (@∅)?(@∅.∅)
> *(@((∅|∅)))
> @∅!(∅)
> ...
> *(@((@∅)?(@∅.(@∅)?(@∅.∅))))
> ((@∅)?(@∅.∅)|(∅|∅))
> *(@(*(@((@((∅|∅)))?(@((∅|∅)).∅)))))
> (@((∅|∅)))?(@∅.*(@((∅|∅))))
```

Feel free to use it, ask questions or make proposals.

**Comment by allancto** [comment]
All: your work is awesome! Thanks @nonnykul , and @golovach-ivan !!! I found one typo in @nonnykul 's work and no bugs in @golovach-ivan , has anyone read more carefully than me? 

Workgroups: @ibesoft11 I'm assigning you to that group now, if any of the other team members have opinions about that please speak up. Please begin by reading @nonnykul 's document. Also @qelentium I'm assigning you to the @golovach-ivan group, it would be great if you can find other Slavic speakers as well (or ANY speakers, it really doesn't matter, the real point is workgroups who are comfortable with each other). @JoshOrndorff can you speak with one of the existing 3 groups and figure out which you would most like to join- any of the groups will be happy to have you! 

I created a google docs for additional team discussions we might want to have, particularly comments and help on each other's work. 
https://docs.google.com/document/d/1zBsaKEGfq6SXgaqC_qbUL4FeYlVYAgQ0EAkO9nt58YM

Cheers! -Allan

**Comment by Pionelle** [comment]
@allancto Hi, I worked on some issues in the translation label for the coop. I also could  be a part of a group working on documents,I can also do translations

**Comment by allancto** [comment]
@Pionelle that sounds awesome. Please contact @nonnykul or @David405 . I saw the work you started on DoCC1, have you watched the video? I'll make some notes about what's still missing from those videos, hopefully those may be of use to others. Thanks!! -Allan

**Comment by Pionelle** [comment]
@allancto Yes I did watch the video, its a very long one, but I am hopeful to get it done. @nonnykul and @David405 I sent some messages to you too.

**Comment by allancto** [comment]
@golovach-ivan are you available for the RAM meeting today? You've done a lot of work on this issue which I'd like to highlight but i don't know your discord handle. I'm @allanc on discord if you need a link to RAM. Thanks! -@allancto

**Comment by allancto** [comment]
@nonnykul can you make this document "Comment" instead of "view only"? 
https://docs.google.com/document/d/1ic7yCa37Jjx9l6UBpoFJf8o6CZzmEwtRBvfUj81lLvw

**Comment by nonnykul** [comment]
@allanc, I have made the document accessible for 'comment'.

**Comment by lapin7** [comment]
@golovach-ivan
Please read [CONTRIBUTING.MD](https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md)

**Comment by kovmargo** [comment]
Hi! Could you please add me to a workgroup 3 to @golovach-Ivan?

**Comment by Valentine-Mario** [comment]
This <a href="https://docs.google.com/document/d/1BxVgqE8fAsg_bNDSJyrZMfI_9hZj6jhKrBdQA30dKpg/edit#">here</a> is the unfinished documentation team 2 are working on. Hopefully it would be ready in about a week

**Comment by lapin7** [comment]
Does an installation for Mac also make sense?

**Comment by Jake-Gillberg** [comment]
@Valentine-Mario What does that document have to do with the Introduction to the Design of Computational Calculi? Seems way off topic.

**Comment by Valentine-Mario** [comment]
@nonykul who is also a member of our team is working on intro to computational calculi. This document is focused on intro to Rholang and Rspace

**Comment by zsluedem** [comment]
Sorry for the late outcome. I was busy with an exam last few weeks and only watched the video and @Whisker17 was busy with an interview. We have made a [slide about the rho calculus](https://docs.google.com/presentation/d/1Z21jWW45mlhJ8do-hzlES41jl_XSfy8fOJ3jr-RFc0A/edit?usp=sharing) this week. It hasn't been finished yet. It is a temporarily outcome. We will try to make the slides catch up with the rho calculus lessons later.

BTW, sincerely thank @Jake-Gillberg for the guides to me :) .

**Comment by kovmargo** [comment]
According to this task should our team create tutorial on English OR on native language (Russian)? Can we add more examples to tutorial from ourselves OR info in tutorial should be strictly on video? Tnx

**Comment by Pionelle** [comment]
@kovmargo You should direct some of these questions to @allancto But If you feel confident on your Native language, then you should do that, then you would do a better job.

**Comment by allancto** [comment]
@kovmargo  please coordinate with @golovach-ivan and @qelentium if you're working in the Russian language. Please post whatever work you do, including tutorials and any materials you produce in English and/or Russian, in the DoCC folder. Thanks! Also @Pionelle thanks also, and please coordinate with Team 3. 

Here is the folder. Also in this folder you'll find a Monthly Review doc by team, each team should please contribute to that as well so we can submit June work for voting. Thanks! -@allancto
https://drive.google.com/open?id=1x_9mFtsQqck358U9-PsHUMcdB7LBI7lP.

**Comment by allancto** [comment]
We had a team meeting and recommend voting a $1000 reward for progress in June by each of the three teams (total $3000). We have laid a foundation and made some progress but haven't yet produced the quality and quantity of work we are aiming to achieve in this project. 

@Jake-Gillberg and others with an interest in this issue, please vote for the June budget. Thanks!

**Comment by nonnykul** [comment]
@Jake-Gillberg @allancto check out [Introduction to the design of Computational Calculi 02](https://docs.google.com/document/d/173eOPdg4e9rfnqYr-vDDh8O8pMJesoeRE7S_1y8mOLk/edit).

Comments are highly appreciated

**Comment by zsluedem** [comment]
Hello @allancto . @Whisker17  have already made an update of our  [slides](https://docs.google.com/presentation/d/1Z21jWW45mlhJ8do-hzlES41jl_XSfy8fOJ3jr-RFc0A/edit#slide=id.p7).

**Comment by Valentine-Mario** [comment]
@allancto I and @ibesoft11 have made modifications to our pdf. It can be viewed <a href="https://docs.google.com/document/d/1kBuBQ71MNMKhXqqko5sUOqEBvKV8sohGpfP-HwPguR4/edit?usp=sharing">here</a>

**Comment by nonnykul** [comment]
[Introduction to the design of computational calculi 03](https://docs.google.com/document/d/18A1GKLHsHEK2i14BAdXawWmwmA6fC6aJYdr89RN4Aew/edit).
comments and further input are highly appreciated

**cc**: **Jake-Gillberg**, **allancto**

**Comment by nonnykul** [comment]
[Introduction to the design of computational calculi 04](https://docs.google.com/document/d/1JmuvqMi7EZ7XvwACLnA0PYBfenfE3mxZ6CvN14BBqlQ/edit?usp=sharing)

**cc**: **Jake-Gillberg**, **allancto**

**Comment by allancto** [comment]
@nonnykul please link @Jake-Gillberg , @JoshOrndorff who have been leaders in the Collaborative Learning version of this issue, as well as @glenbraun, @jbassiri, @leithaus , @kennyrowe @jimscarver. Hopefully that will generate an autoemail to them (or perhaps ping them on discord as well!). I'm eager to get outside feedback for how our workgroups are doing so that we can get some external validation (or disputation!) of our efforts. 

Thanks! -@allancto

**Comment by kayvank** [comment]
@nonnykul , thank you for putting this doc together. I'd like to contribute to this doc once I get back.

**Comment by qelentium** [comment]
[Introduction to the design of computational calculi 03-04](https://docs.google.com/document/d/1_h1qcOzbq_24U_EdxD1bdnm6hjSPl1dGwe51RwMz_l0/edit?usp=sharing)

**Comment by JoshOrndorff** [comment]
I'm trying to look over this work so far and I want to be sure I'm looking at the right things. It seems like https://drive.google.com/drive/folders/1x_9mFtsQqck358U9-PsHUMcdB7LBI7lP is the canonical source of the work?

The stated value to RChain was, "Cultural literacy around our fundamental computational and scientific models.", and I believe we have begun to accomplish that. On the other hand, It seems like the biggest tangible result was lecture notes from the course. I have made comments on a few of those notes in google docs.

I believe one thing that is missing from the course is examples and exercises. It would be a huge help to learners to practice with concrete examples of what the definitions mean and how the concepts are used. For an example see: https://rchain-collaborative-learning.github.io/Introduction-to-the-Design-of-Computational-Calculi/discussion6.html#/true-or-false-1 (and hit the down arrow a few times)

@allancto General questions about this  bounty
1. Where do expect these resources to ultimately live?
2. Plans to do a similar project for subsequent lessons?

**Comment by David405** [comment]
@JoshOrndorff I am excited to have your input here, _(I know you want an answer directly from @allancto )_ but allow me to share my idea of the concurrent working groups. The purpose of this work is to produce simpler and more concise notes on Greg's lecture and Jake's workstudy and provide a collection of these materials to be accessible at any point by anyone. We got an offer from RChain's director of communication (Patrick Maguire) stating that the materials can be posted on RChain blog when complete. Also, I do want to organize them into a course work with a structured curriculum. Concerning examples, we would improve on that but if you can provide us with really good and simple illustrations, we will be happy to include them.

The effort is a continuous one, as long as the RChain Educational series continues, this work will continue and even if RChain Educational series stops, we will continue to improve on the existing documents

By the way, are you the anonymous commenter on some of the documents?

**Comment by David405** [comment]
@allancto I believe the measure of completion has to updated beyond lecture 1-4

**Comment by JoshOrndorff** [comment]
@David405 your answer is perfect for me! I'm glad to hear that this effort will continue for the entire course. Is the proposed budget of $3,000 / group for the entire course or the first four weeks?

Jake's RCL repos have a few good exercises such as [Am I a process](https://rchain-collaborative-learning.github.io/PiCalc-to-Rholang/lesson1.html#/am-i-a-process), "Am I Observable", and the [bisimulation questions](https://rchain-collaborative-learning.github.io/Introduction-to-the-Design-of-Computational-Calculi/discussion6.html#/true-or-false-1) that I mentioned previously. (press down arrow to navigate).

But I also think something as simple as reduction problems in lambda, pi, rho calculus would be very helpful. (and maybe others like ambient, ski, blue?) For example how about a few problems like these.

```
Reduce this pi calculus expression.
x!(0).0 | x(y).y!(0).0

Or we can explore interesting but tricky comparisons like how many valid reductions does this process have?
x!(P).0 | x(y).0 | x!(Q)

How many reductions does this similar process have?
(vx) { x!(P).0 | x(y).0 } | x!(Q)

How are the two previous cases different?
```

The key to writing good educational materials is guiding the learner through the difficult parts and making sure they have enough experience navigating things like reductions, contexts, observability, equivalence, etc. Summaries are great starts, but it isn't enough to show the end result, we have to show them the route to get there.

**Comment by David405** [comment]
Thanks Josh for the feedback, the exercises and assignments will be implemented as soon as possible.

The budget is not fixed but merely a suggestion, the actual budget is decided at the end of the month depending on the value created by each of the groups. For example, in June, each group was rewarded with $1000 which was based on the value created.

**Comment by Valentine-Mario** [comment]
I and @ibesoft11 worked on operational semantics for this month. the document can be found <a href="https://docs.google.com/document/d/1Vt3xRNoakeYb4q-GOjLII24g7KaZq-RiFeZBYxkqJA4/edit?usp=sharing">here</a>

**Comment by dckc** [comment]
rewarded in 201808
