### ISSUE TITLE
review of 201805 pay period rewards by guides

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#759]
## Objective

 - [x] get confirmation from a guide in each area that we're all set to close 201805 on June 8. Sorting by most issues:
   - [x] Marketing
   - [ ] Operations
   - [x] Translation
   - [x] Development
   - [x] Governance
   - [x] member-site
   - [x] Education
   - [x] Greeter
   - [x] Events
   - [ ] Africa
   - [x] Branding
   - [x] Voting
 - [ ] produce [May 2018 Bounty System Report][1]

[1]: https://docs.google.com/document/d/10Zw9wIbxirDVAWTCu57F4ue1lZvx1rDQ3YtNP2ugdXY/edit

A handy view of the data is:

 - [201805 Rewards for Development](https://rewards.rchain.coop/index.php?-table=reward&-limit=30&pay_period=05%2F01%2F2018&labels=Development&-action=list&-cursor=0&-skip=0&-mode=list&-sort=reward_usd+asc)  (Change the **Labels** filter as appropriate.)

As of a couple days ago, Translation had an issue where @michaelizer wasn't certified. @michaelizer let us know when Translation is ready (or assign to somebody else).

@jimscarver un-assign yourself when Governance is done.

I think Development is done, but I'll double-check.

@pmoorman confirm for Marketing or pass the ball (re-assign).

@TrenchFloat help me figure out who else should be in the critical path.

## Benefit to RChain

Align bounty system contributions with goals of RChain in Development, Marketing, and other areas.

### Budget and Objective

_Estimated Budget of Task:_ **$1600**
_Estimated Timeline Required to Complete the Task:_ 10 guides * 4hrs
_How will we measure completion?_ see objective above

**Comment by pmoorman** [comment]
As for marketing: we're working on it as fast as we can. To be honest, it's an enormous amount of work (much more than I anticipated), and @kitblake @AyAyRon-P and myself are working through it.

I don't think there's anyone to pass the ball to. 

When we're done I'll open a few issues to address a couple of the things that went wrong now that we could improve in the next month to make the bounty system stronger & better for everyone.

**Comment by dckc** [comment]
A handy view of the data is:

 - [201805 Rewards for Development](https://rewards.rchain.coop/index.php?-table=reward&-limit=30&pay_period=05%2F01%2F2018&labels=Development&-action=list&-cursor=0&-skip=0&-mode=list&-sort=reward_usd+asc)  (Change the **Labels** filter as appropriate.)

That shows the status of every Development issue / worker combo where anyone has cast a vote (whether certified or not). It's sorted by ascending amount. So toward the top, look for things that should get a reward but aren't, and at the bottom, look for overly large rewards.

In the case of Development, @KentShakima voted for my core work in #708, but his coop membership isn't connected to his github account, so the 3 vote threshold isn't met. The obvious person to chase that one down is me.

On the other end the budget for integrating labels into rewards.rchain.coop (#673) looks high. @jimscarver @aviationhacker given the clarification in scope between that one and #609, maybe you should reduce your budget votes on #673?

**Comment by dckc** [comment]
@Ojimadu I took a quick look at Events; I don't see any critical path issues. If you do, let us know and assign yourself to this issue, please.

For Governance, the translation guide's report #721 is included, but the overall retrospective report #678  is rather in Operations. Wherever the line is, surely both belong on the same side. Otherwise, I don't see any Governance issues. And this one isn't critical. (I'm keeping @jimscarver assigned to review budget on #673).

@kitblake I supported the member-site work in #615. Thanks for the reminder.

Operations... wow... 59. 14 of them are below the 3 vote threshold, though; perhaps that's as expected. I can't tell at a glance whether those are all set, @lapin7 @TrenchFloat @jimscarver .

Voting: no rewards scheduled (one claimed, below threshold). That's OK as far as I know. @Jake-Gillberg does that look right to you?

**Comment by Ojimadu** [comment]
No pending issue on the events label.

**Comment by pmoorman** [comment]
Update: I believe we're more or less "on track" for marketing. We have some complications because @AyAyRon-P is out of the country on the most critical moment, but we're dealing with it.

I think there's nothing to worry about on our label.

**Comment by michaelizer** [comment]
Greetings, for the translations category there are very few issues pending, cases that were extraordinary but we will solve it ASAP. We are finishing the transition from @ICA3DaR5 to me, give us a day or two to settle things up, and those Issues along with the category itself will be done for the May period.

**Comment by dckc** [comment]
@pmoorman and everybody,

@allancto had a question for me about the "RChain Weekly Update" blog tasks #729 , 718, 689, 667. Separate task issues for each of these blog items is clearly working against the collaborators, when it comes time to do this budget / reward voting. That's a lesson I learned a while back when doing development on rewards.rchain.coop: while I was doing the work, it was useful to have separate issues to help myself remember which parts were done and keep the design discussion separate. But for budget/reward purposes, I ended up **lumping the budget for several of them into one "deliver the thing" task issue** so that I didn't have to chase down votes for each little part.

And for these weekly blog items where there's an established pattern, one issue for the month seems easier all the way around.

I'm not discussing this directly on those issues (a) because it's advice that applies to all tasks and areas, and (b) because before I directly support that work, I would want to thoroughly review it myself. I wonder if those items are getting the level of review they deserve.

**Comment by pmoorman** [comment]
@dckc @allancto thanks for bringing it to my (our) attention. 

- I think it makes sense to lump together such issues, much like Dan suggests.

- In my vote, I've done exactly that, and voted only a budget on #729 with the understanding that this accounts for all 4 issues.

- Another problem that I see -- that this set of issues raised in particular -- is that it's hard to find closed-but-relevant issues in Github right now. I wonder which other issues I missed or forgot about.

**Comment by Viraculous** [comment]
@dckc Thanks for expressing your concern about the Weekly Updates blog post. I am also working side-by-side with @PatrickM727 and @plantether. Immediately I am done, @plantether gets to do the review and from my little knowledge, she studied English. @PatrickM727 also gets a copy of the document and is in charge of uploading the documents to the RChain medium. I hope this satisfies your question?

**Comment by dckc** [comment]
The remaining Development tweaks (#708 and #673) are all done.

**Comment by ICA3DaR5** [comment]
I talked with @michaelizer and he agrees we're done for the Translation label for 201805.

**Comment by TrenchFloat** [comment]
Education issues are all reviewed.

Until we get @entropee (and ideally someone else) up to speed on being an Operations guide, that label is a large pile of work that @lapin7, @jimscarver, and I don't have the bandwidth to go through. For now, Ops is at risk.

**Comment by pmoorman** [comment]
> Until we get @entropee (and ideally someone else) up to speed on being an Operations guide, that label is a large pile of work that @lapin7, @jimscarver, and I don't have the bandwidth to go through. For now, Ops is at risk.

I think that it's fair to say that — in general — being a guide is _much more work_ than any of us anticipated. @kitblake and I are drawing the same conclusion. 

Something to talk about in June!

**Comment by dckc** [comment]
p.s. we had a bit of a snafu where Medha created #766 to reward Abner's May core dev work, but we decided to disallow votes on issues created after the current pay period in #682. We had to put in some funky votes in #708 to make it work out right.

Next time I hope to coordinate better with Medha.

**Comment by kitblake** [comment]
_Posted this in Discord where it surely got lost:_

For label guides: bounty hunters are driving the guides crazy with PMs. Contributors should make their case in public in the Github issue. Don't discuss bounty budgets/rewards in private.

**Comment by dckc** [comment]
pay period is now: **201806**. May votes are frozen.

Next step: produce the [May report][1].

@Jake-Gillberg I'm out of the office this week; would you take a stab at the Development section?

[1]: https://docs.google.com/document/d/10Zw9wIbxirDVAWTCu57F4ue1lZvx1rDQ3YtNP2ugdXY/edit

**Comment by dckc** [comment]
This issue is showing up on the Task Approval Overdue list, believe it or not.

Based on a wild guess of 10 guides * 4hrs each, on average, I suggest a $1600 budget. I updated the issue description and submitted a [budget vote on this issue][1]. If you did work on this issue, please add a reward vote and I'll consider matching it.

Do we want / need a report for May? The title of the report we already submitted was expanded to include May, though for at least Development, I only reported thru April.

[1]: https://rewards.rchain.coop/index.php?-table=issue&-sort=num%20desc&-limit=30&num=759&title=&updatedAt=&state=&createdAt=&labels=#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-table%3Dissue%26-sort%3Dnum%2Bdesc%26-limit%3D30%26num%3D759%26title%3D%26updatedAt%3D%26state%3D%26createdAt%3D%26labels%3D%26-action%3Drelated_records_list%26-cursor%3D0%26-skip%3D0%26-mode%3Dlist%26-recordid%3Dissue%253Fnum%253D759%26-ui-root%3Dmain-content%26-relationship%3DBudgetVotes

**Comment by pmoorman** [comment]
Can't speak for other labels, but in marketing we needed _much more_ time to do all the guiding work, and all the back-and-forth with people that wanted more rewards, etc. etc.

It's probably on the conservative end to say that @kitblake and I spent about **2 full days each.** 

Does it make sense to break up these tasks per label (I have an idea between Kit and Aaron and me how to suggest a rewards split, but not really in relation to other labels)? Or maybe just pull marketing out of it, if we're much bigger than the others?

Also: maybe we should next time create an issue that we then reward in the same month, right? So we'd make an issue now that says "June guiding work" and solve it in June, so that all the June-related stuff stays in the June pay period, etc. etc.

**Comment by dckc** [comment]
> Does it make sense to break up these tasks per label?

quite possibly, especially for Marketing.

Another possibility is: reward yourselves in the issue(s) that you're guiding. But getting 3 votes for each such reward could be more trouble than it's worth.

> ... make an issue now that says "June guiding work" and solve it in June ... ?

make the issue now yes (did I already? hmm...) but given that the work goes right up thru July 8 and possibly a few days after for rewarding, I think it make more sense to have its rewards in July.

**Comment by kitblake** [comment]
Having it in one issue means all guides have to proportion the budget between all guides.

**Comment by zsluedem** [comment]
I have made a [China community report](https://docs.google.com/document/d/14e7o5EkGdxzZx9cEvOi2n_YsTdZDOsdUSohifMvPKzE/edit?ts=5b3aef6d#) and see if this report help you all. But the report is about June not May.

BTW, are you still making May report instead of June report?

**Comment by Ojimadu** [comment]
@dckc @jimscarver I voted on this issue based on work done for 06/2018 based on misunderstanding [this comment](https://github.com/rchain/bounties/issues/759#issuecomment-400116315) but your votes look like it was done based on 05/2018. I guess I suppose to vote on #809? so am changing my votes here.

**Comment by dckc** [comment]
p.s. May rewards didn't stay frozen after June 9 due to #799 .

I restored them today from a combination of invoices and other records.

See also: https://gist.github.com/dckc/af5e9ec63342adaf033c389a84c2f0db#file-reward_201805-csv
