### ISSUE TITLE
Translate to Russian + Explain + Publish translation ("Policy as Types" paper)

### ISSUE THREAD

**Issue by golovach-ivan** [rchain/bounties#764]
Translate Lucius G Meredith, Mike Stay, Sophia Drossopoulou, Jul 2013 v2 [Policy as Types](https://arxiv.org/abs/1307.7766) with explanation/dictionary of math terms to software developers: 
- capability, 
- OCap, 
- policy,
- deniability, 
- Labeled Transition System,
- trace equality,
- bisimilarity,
- barbed bisimilarity,
- calculus of communicating systems (CCS),
- п-calculus,
- RHO-calculus,
- Hennessy-Milner Logic, 
- modal logics,
- spatial logics, 
- separation operator, 
- adjoint to separation operator,
- namespace logic,
- Curry-Howard Iso

### Benefit to RChain

*The post will create a point of reference for the basic concepts concerning &#961;-calculus in Russian and attract attention of practicing programmers to RChain and rspace and other Coop projects. *

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[2000]**
_Estimated Timeline Required to Complete the Task:_ **[2 weeks]**
_How will we measure completion?_ **[Published to most popular russian-speaking IT-community habrahabr.ru with 5.000+ views]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because A) this document one of the core scientific basis of RChain B) this document has an important educational value (he explains exactly how to do a formal verification for smart contracts in Rho-lang)
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in _the target language_
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Barkov-F** [comment]
@golovach-ivan Can you add the link to the original document to the issue description? I mean the document you'll base the habr post on?

**Comment by golovach-ivan** [comment]
@Barkov-F 
> Can you add the link to the original document to the issue description? I mean the document you'll base the habr post on?

+ done
+ add terms list to explain

**Comment by allancto** [comment]
Thanks @golovach-ivan and @Barkov-F . The choice of material is awesome. When you say "Explain" may I assume you are adding your own commentary/ explanations/ discussion and glossary to the original paper? That would be exactly the sort of "value add" we need. Also, PLEASE publish your additions in both the source language (English) as well as in Russian. If you like you might even host a discussion group or google-doc with comments turned on so that developers in every language can participate and benefit. 

Thanks for helping us establish a culture of continuously adding value to RChain materials as you internalize and discuss them, by showing how they may be used, applied, conceptualized. 

Also, there isn't a suggested budget. Does $2000 sound reasonable? More? Less? I'd invite everyone to comment early on what kind of "quality" you'd like to see out of this project, and what kind of reward is appropriate to motivate that degree of quality. Beginning this discussion early will help the alignment between contributors and perceived value to our Cooperative, and create expectations that will be finalized when the project is ready for review and voting rewards. 

Again, thanks for highlighting this particular paper and beginning an insightful discussion about it.

**Comment by golovach-ivan** [comment]
@AyAyRon-P 
> Does this mean that you will not claim the bounty until the translation has 5.000+ views? 

yes

> Has there been any progress made with this project?

yes, i decided to divide work in 3 parts
1) i'll publish russian version of explanation/dictionary on habhabahb.ru until 27 Juny (without paper translation, only link to en version)
2) i'll publish on habrahabr translation of paper until 4 July
3) i'll show to RChain community explanation/dictionary for paper until 6 July
i decided to divide work in 2 posts on habrahabr because big hard tech paper - not the best post for this site (in my opinion sole explanation is better post).

P.S. 
1) http://habrahabr.ru has no analogs in en-speaking community, it is Top-1 (and top-2 and top-3) tech-site with authors articles + translations. It has crazy popularity in russian tech community, if you write really good meterial - you will have a lot of views in first 3-5 days, long tail (up to 5 years) - thankx to search engines and a lot of reposts on other tech sites.
2) i had expirience in creating Java/Scala community based on habranabr.ru
* [1000k views](https://habr.com/company/golovachcourses/blog/215275/)
* [240k views](https://habr.com/company/golovachcourses/blog/223821/)
* [160k views](https://habr.com/company/golovachcourses/blog/225585/)
* [140k views](https://habr.com/company/golovachcourses/blog/218841/)
* [90k views - translation](https://habr.com/company/golovachcourses/blog/221133/)
* [60k views](https://habr.com/company/golovachcourses/blog/217595/)
* [50k views](https://habr.com/company/golovachcourses/blog/256883/)
* [45k views](https://habr.com/company/golovachcourses/blog/217051/)
* [45k views](https://habr.com/company/golovachcourses/blog/228603/)
* [40k views - translation](https://habr.com/company/golovachcourses/blog/222679/)
* [40k views](https://habr.com/company/golovachcourses/blog/251239/)
* [40k - translation](https://habr.com/company/golovachcourses/blog/222679/)
* [30k views](https://habr.com/company/golovachcourses/blog/231755/)
* ... etc
3) i can create local community (i live in Ukraine/Kharkov, it is big tech/outsourcing city in Eastern Europe - 1.5M people, city has big crypto-community, for example here lives my friend co-author of [Ouroboros concensus protocol](https://eprint.iacr.org/2016/889.pdf) Roman Oliynykov). Kharkov occupied the 4-5 place among the industrial regions of USSR - so lots and lots of engineers live here.
4) i had expirience in creating local community - here is my [Youtube Channel](https://www.youtube.com/user/KharkovITCourses) - 25k subscribers.

**Comment by ICA3DaR5** [comment]
@golovach-ivan Please fill the **Translation Checklist** section.

At the moment  the following items are up for translation:

- [RChain blog](https://medium.com/rchain-cooperative)
- Document(s) on https://developer.rchain.coop/ that have been endorsed for translation by @Jake-Gillberg, @MParlikar, or @KellyatPyrofex

**Comment by pmoorman** [comment]
I'm removing the marketing label here, since this seems more like `translations`. 

Where will this piece be published? Where will it be distributed? What are aims in terms of reach & exposure?

**Comment by deannald** [comment]
For future translation work, I'm going to defer to @patrick727 and the marketing team to prioritize which documents RChain Cooperative is looking for translation (that's not to say you can't propose others, of course). The Task Approval Committee and RChain Cooperative are trying to ensure that high valued articles, blog posts and other materials are given top priority and, further, are distributed in a manner that has great reach.

I'd like to get weigh in from @patrick727 on value of this particular issue so that budget allotted/voted is commensurate with value (higher priority translations = higher budget).

@dckc @ian-bloom

**Comment by allancto** [comment]
@golovach-ivan please correct me if I'm wrong: although part of this work is to publish a Russian translation, the work itself is to understand a significant paper and provide the entire RChain community with analysis and context for that paper. I'd suggest that a good place to communicate this would be in our Collaborative Learning repo (where you have already published excellent work). 

If that's indeed the case I will recommend a high budget for this work. Although translation and marketing may be an indirect consequence of the work, to me its real purpose is helping the RChain community as a whole with technical literacy, and also building local community (and therefore building the RChain worldwide community). You'll explain in the source language (English) the dictionary and analysis you've provided. If you and your group participate in #755 I would consider that additional evidence your work is significant. 

@deannald @dckc @patrick727 @ian-bloom @Jake-Gillberg  I would also invite you to evaluate this work by @golovach-ivan as not translation but as significant contribution to the RChain community technical literacy and to RChain community building. 

Thanks!
@allncto

**Comment by deannald** [comment]
@allancto I believe you are making assumptions as to what this body of work entails which, as I understand it, is the translation of the original work by Greg M. et al. with push out to his large community reach. I'm not seeing additional analysis and output being included in this bid.

**Comment by golovach-ivan** [comment]
Status
1) In 6 weeks did research on Formal verification.
2) Write and send article to habr.com, now i'm steel waiting for the moderation of the article.
3) As a result of the research I also hold a meetup #821 ("Smart Contract Formal Verification: Process Calculi and Modal Logics") 
4) As a result of the research I also hold a meetup #822 ("Smart Contract Formal Verification: Process Calculi and Modal Logics")

P.S. Two meetups in two biggest Ukrainian cities (1.5M + 3M population) with a lot of devs/math.

**Comment by deannald** [comment]
Thanks @golovach-ivan for the breakdown and clarification.

**Comment by ICA3DaR5** [comment]
@golovach-ivan Why haven't you answered my previous [comment](https://github.com/rchain/bounties/issues/764#issuecomment-400766642)

**Comment by golovach-ivan** [comment]
The article was rejected as too big and too technical for this site (so i think about rewriting it for IT geeks not math people). So task will not be finished in June.

**Comment by golovach-ivan** [comment]
@ICA3DaR5 
Sorry, i missed comment. 

1) The article refers to one of the 5 most important topics that should be reported to the tech/math community - RChain concensus protocol, unique calculi, uniqie lang, unique logic, correct-by-construction contracts.

2) This article is not on the translation list. I think to take risks and, if I manage to attract much attention to the article (5,000+ views), then I propose to vote for it.

3) I do not think that on popular sites (such as habr.com) it is prudent to publish translations of documents about the operational activities of RChain. This is unlikely to attract much attention from the community.

**Comment by michaelizer** [comment]
Hello @golovach-ivan! since you haven't finished this issue yet, the guides are voting zero for the budget. We will leave this issue open for next month.

**Comment by allancto** [comment]
@michaelizer @ICA3DaR5 no voting is necessary for June. The work is not yet complete and will be completed and voted in July. Thanks! -@allancto

**Comment by allancto** [comment]
@ICA3DaR5 @michaelizer it appeared that @golovach-ivan did a significant amount of work during this period on two meetups, #821 and #822, but these did not get posted early enough for June voting. Therefore I propose we vote the first half of this budget ($1000) now and the rest on completion. 

Thanks! -allancto

**Comment by ICA3DaR5** [comment]
@allancto Okay.
