### ISSUE TITLE
Translate Medium Article - RChain: Progression And  Cooperation to French

### ISSUE THREAD

**Issue by Pionelle** [rchain/bounties#765]
### Benefit to RChain

*I  created a copy of this article for the French speaking audience. Publishing the article is done.*
**
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[400]**
_Estimated Timeline Required to Complete the Task:_ **[4 days]**
_How will we measure completion?_ **[Translated and published]**

[Medium Page with Article](https://medium.com/@rchainfrench/rchain-le-progrès-et-la-coopération-a3e89a467b3b)

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Pionelle** [comment]
offline, I ran this along my Native french mate and online here ill still open the work to more scrutiny. @niwaa @truffard @ICA3DaR5

**Comment by ICA3DaR5** [comment]
@Pionelle please correctly fill the **Translation Checklist** section.

At the moment  the following items are up for translation:

- [RChain blog](https://medium.com/rchain-cooperative)
- Document(s) on https://developer.rchain.coop/ that have been endorsed for translation by @Jake-Gillberg, @MParlikar, or @KellyatPyrofex

Also, added value is needed, check @allancto [comment](https://github.com/rchain/bounties/issues/746#issuecomment-395944639).

**Comment by michaelizer** [comment]
Hello @Pionelle! We are still waiting for you to reply @ICA3DaR5's comment, also you haven't filled the checklist yet. We are voting zero for the budget and slashing you until you prove us wrong, please answer this as soon as you read it.

**Comment by Ojimadu** [comment]
Is slashing necessary here?

**Comment by AdinaGitHub** [comment]
Hello,

I am not sure what is going on here, but I am not @Pionelle.

Would somebody please clarify?

Thanks!
Adina

Adina Suciu
206-234-8014

**Comment by ICA3DaR5** [comment]
@Ojimadu She can still reply and prove us wrong.

@AdinaGitHub What do you need clarification for? Elaborate.

**Comment by AdinaGitHub** [comment]
Please clarity why am I part of this thread. Thanks.

Adina Suciu
206-234-8014

**Comment by ICA3DaR5** [comment]
@AdinaGitHub Someone probably mentioned you in the past and removed his mention.
