### ISSUE TITLE
Core Development work for May

### ISSUE THREAD

**Issue by MParlikar** [rchain/bounties#766]
### Benefit to RChain

Build the Scala version of Rosette.  
RNode enhancements in May
Issue covering May bounty work.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ $2,400.00
_Estimated Timeline Required to Complete the Task:_ 1 month: May
_How will we measure completion?_  Pull Requests are Merged.  Measure of effort is story points.  We pay $150.00 per story point in RHOC.  The CoOp and board set the price of RHOC.

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by MParlikar** [comment]
Completed issues ROS-330, ROS-234, CORE-524

**Comment by dckc** [comment]
This looks like a dup of #708 , which I already got votes for.

**Comment by dckc** [comment]
We decided to **disallow votes on issues created after the current pay period** in #682. So we'll have to use #708.
