### ISSUE TITLE
Core Development work for June

### ISSUE THREAD

**Issue by MParlikar** [rchain/bounties#767]
### Benefit to RChain
June Core development work on the Platform.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ $10,000.00
_Estimated Timeline Required to Complete the Task:_  1 month- June
_How will we measure completion?_ Pull Requests are merged. Measure of effort is in story points.  Each story point is paid out at a rate of $150.00 in RHOC.  Price of RHOC set by board and CoOp.

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by David405** [comment]
@dckc @MParliker, how does one find the development work?

**Comment by dckc** [comment]
There's a link form developer.rchain.coop

**Comment by MParlikar** [comment]
Following tickets were paid as part of this bounty issue: ROS-438, ROS-435, ROS-433, ROS-426, ROS-424, ROS-423, ROS-422, ROS-420, ROS-419, CORE-496 - Voted for Abner - 40 story points in total.
