### ISSUE TITLE
Post core scientific papers of RChain founders on the developer.rchain.coop

### ISSUE THREAD

**Issue by golovach-ivan** [rchain/bounties#768]
Place core scientific papers related to RChain on developer.rchain.coop/documentation:
+ Meredith, Radestock, 2005, [A Reflective Higher-order Calculus](http://tech.labs.oliverwyman.com/downloads/ex_nihilo_finco.pdf)
+ Meredith, Stay, 2015, [Higher category models of the pi-calculus](https://arxiv.org/pdf/1504.04311.pdf)
+ Meredith, Bjorn, 2003, [Contracts and Types](http://bbs.w3china.org/dragonstar/papers/Meredith%2BCACM46-10.pdf)
+ Meredith, Stay, 2016, [Logic as a Distributive Law](https://arxiv.org/pdf/1610.02247.pdf)
+ Meredith, 2015, [Linear Types Can Change the Blockchain](https://arxiv.org/pdf/1506.01001.pdf)
+ Meredith, Stay, 2017, [Representing operational semantics with enriched Lawvere theories](https://pdfs.semanticscholar.org/04b9/e0db0feb1b0cb6c46021a7fa166d9663af95.pdf)
+ Meredith, Stay, 2017, [Name-free combinators for concurrency](https://arxiv.org/pdf/1703.07054.pdf)
+ Brown, Laneve, Meredith, 2005, [PiDuce. A Process Calculus with Native XML Datatypes](http://www.cs.unibo.it/PiDuce/ws-fm05.pdf) - its about how encode types of channels and pattern matching in pi-calculi

### Benefit to RChain

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*  

### Budget and Objective
_Estimated Budget of Task:_ **$[TBD]**
_Estimated Timeline Required to Complete the Task:_ **[TBD]**
_How will we measure completion?_ **[example: pull request merged]**
- What about maintenance? (choose one)
  - [x] the source document is stable; further translation work is not expected

**Comment by allancto** [comment]
@golovach-ivan can this be combined with #764 ? There's been an explosion of issue numbers and combining related issues will help everyone assess value and quality using less time and allowing more focus. 

Also please continue your pattern of adding value. Summaries, discussions, and even small introductions like you did above "its about how encode types of channels and pattern matching in pi-calculi" are valuable to all of us who care about the material but may be not yet familiar with it. Thanks!

**Comment by allancto** [comment]
This issue has been merged.
