### ISSUE TITLE
Question: What's a Rholang developer worth?

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#775]
As marketing guides, we ran repeatedly into the issue of how to value certain (marketing) work without any top-level directions on what constitutes "value" to the RChain coop.

I think that we can all agree that the goal of marketing is —ultimately— to get Rholang developers on board, and to get DApps built on the RChain infrastructure.

### Goal

Guesstimate the worth (as expressed in $$$) of the following actions:

- [ ] Bringing onboard 1 Rholang developer
- [ ] Bringing onboard 1 developer
- [ ] Bringing onboard 1 RChain Coop member (dev and non-dev)
- [ ] Bringing onboard 1 organization that can develop DApps on RChain
- [ ] .... insert more

### Notes

I understand that this question is somewhat akin to _"how long is a piece of string?"_, but I'm implicitly guesstimating a value anyway, so we might as well make it explicit.

Maybe we can express the worth as a range. For instance:

- 1 Rholang developer is probably worth _at least_ $1,000 to the RChain Coop, and but probably not more than $5,000

- Bringing onboard 1 junior developer (straight out of university) with no real experience but a Computer Science background, is probably worth....  [fill in here]

Having rough numbers on those values would help the bounty system move towards a more value-based pricing. **Without value on the marketing KPIs, it's impossible to allocate budgets sensibly.**

cc @kitblake @AyAyRon-P @PatrickM727 @ian-bloom @dckc @allancto @jimscarver @barneycinnamon @jbassiri

**Comment by dckc** [comment]
Please give examples of tasks where this is a problem.("repeatedly")

**Comment by pmoorman** [comment]
Almost every marketing task suffers from this. 

If issue X brings us 10 new Rholang developers but I don't know what a Rholang developer is worth.... then how can I judge the value that the Coop has received due to the work (and thus the worth of the issue)?

Examples could be (for instance):

- #197 
- #750 
- #739 
- #669 
- and honestly almost every issue with the goal to "tell people about RChain".

What is it worth if I tell someone about RChain? What is it worth if they come onboard? What is it worth if they write a Rholang contract / run a node / become active in the community / etc.?

**Comment by dckc** [comment]
The marketing plan has KPIs and costs by section, yes?

**Comment by dckc** [comment]
Yes... Section 4 goals lists several and refers to an appendix for a full list.

**Comment by ibesoft11** [comment]
@pmoorman, I agree with you. For example I am a .Net/JavaScript software developer that joined the RChain community but I am yet to understand what I stand to get by becoming a Rholang developer on the platform. I think it will be helpful if people like me are given lighting talks on the merits of becoming Rholang devs. Thank you
cc @Valentine-Mario @ian-bloom

**Comment by Valentine-Mario** [comment]
@pmoorman, there should also be a way to measure such input either through the on boarding video interview or through words of mouth. 
@ibesoft11, rholang is the official language of the RChain community community and it is open source which means anybody can contribute. The bounty program (which many believe to be the worth of being a rholang developer) is actually just an experimental process to see how much it could foster the spread of the technology. The real worth/motivation is actually being able to build something spectacular and new with this amazing technology and teaching others to do same.

**Comment by pmoorman** [comment]
@dckc yes the marketing plan has (rough) numbers on what to spend on certain groups of tasks, but — as a marketing guide — I'm looking for much more low-level numbers.

Imagine the following: someone comes to us (= marketing guides) and says _"hey, I told my friend about RChain, and he happens to be an Elixer/Haskell (functional) developer, and he's now writing his first Rholang contract."_  

What's that kind of action worth?

If I write a blog post and publish it in some obscure university newsletter than nobody has heard of, and I can prove that 3 Computer Science students got super excited and are now writing Rholang contracts.... what's that worth?

Such numbers (even if they're just ballparks) would help with I) better executing our marketing guides roles, but also II) make it more transparent for everyone what _"value to the RChain Coop"_ actually means in practice.

Does that make sense, or am I just going on a path here that leads nowhere?

--- 

@philipandri002 agree with you. Once we have a rough ballpark of value, we can work on measurements/tracking to have a way to attribute which value comes from which campaigns / efforts!

---

@ibesoft11 interesting feedback. I think we should work on better articulating that. Let me know if you want to think along on how to execute that!  (it's out-of-scope for this issue, but something important to address, regardless)

**Comment by jasoncruzzy** [comment]
@pmoorman I agree with you on the need to add some ways to place value on any marketing issues to increase transparency and fairness. 
 I think there should be no specifics(level) on boarding developers as that might stagnate the 'marketing'
 I suggest all categories of developers should be placed on same value.
 But we can work out other modalities to add value like;
1) How many developer's on boarding 
2) The coverage for any marketing issue towards on boarding DEVELOPERS 
3) The mode of marketing e.g RAM meet up's, social media, networking e. t.c should all have specific range of value and tasks.
  We should also put into considerations that some good marketing strategy might not on board developers immediately but should create the necessary awareness for amongst developers

**Comment by dckc** [comment]
> yes the marketing plan has (rough) numbers on what to spend on certain groups of tasks, but — as a marketing guide — I'm looking for much more low-level numbers.

Really? I see **Social media and ads ($500K, 10K engaged followers, 1M+ reached)** in [the big plan][1]. So the haskell-to-rholang person is certainly reached ($0.50) and more likely an engaged follower ($50).

Seems to me the Marketing WG owes us an answer to this one. I guess you somewhat agree, since you assigned yourself.

[1]: https://docs.google.com/document/d/1tfoZMB7tedcsqZG6enGsCN4qR6l6AZSCUNrdMUs_0c4/edit

By the way... as far as I know, this issue is hypothetical. I try to keep track of the RChain developer community, and as far as I know, Quora Engagement (#197) isn't a source of any RChain developers. Some come from Chinese universities; I don't recall just now how they heard of us, but they pre-date #750, so that can't be it. It's possible that some came via medium articles, but the one in #739 seems unlikely (not much technical meat). (No one who answered the survey from #222 with the "How did you discover RChain?" question mentioned medium).  It's quite possible that some joined via the habr.ru post on Casper (#669) without my noticing.

**Comment by dckc** [comment]
Perhaps this section of the retrospective report (#678) is the genesis of this issue?

> It’s difficult to measure ROI for Marketing and translation. Ideally we’ll work out metrics based on number of reads/clicks/views, new members gained from connections, developers garnered to build in RhoLang, etc. These measures will be included in Marketing issues going forward.

If so, in the future, please note that sort of context when opening the issue.

**Comment by ibesoft11** [comment]
@pmoorman I am interested, I have a lot of developers here I can help onboard to the community.
Chat me up on discord.

**Comment by jasoncruzzy** [comment]
@pmoorman you should be very careful with this,, as this might lead to gross abuse in the nearest future and some RAM members taking advantage of this. Have you considered some of the challenges with what you are proposing?
1)  How do u intend to verify the authenticity(category) of  each new developer on boarded
2)  Do you intend to 'interview' new RAM?, if yes then its more like employing developers which puts the idea of decentralized RChain into question.
3) Are we going to introduce 'Referrals links'  so we can know those on boarding new developers??
    In my opinion this is a one strategy marketing(networking).

    I still go by my opinion(suggestions)
    1) How many developer's on boarding
    2) The coverage for any marketing issue towards on boarding DEVELOPERS
    3) The mode of marketing e.g RAM meet up's, social media, networking e. t.c should all have specific r 
       range of value and tasks.

**Comment by pmoorman** [comment]
@jasoncruzzy thanks for thinking along!

In short:

1. I don't know exactly how we can verify them. That's a next problem to sort out. I agree with you that this is important to think about next!

2. I think we should assume that each RAM falls roughly in the $50 category, _unless we can prove otherwise_. For instance: if someone has 10+ years experience in governance... that's probably worth something, right?

3. I think the idea of better attribution tracking is the way to go. Right now our funnels are so broken that I doubt it will work, but it the future that's where we should go.  Right now our best option might be to just ask people _"how did you find out about us?"_ when they come on board.

In general: I think all these numbers should be understood as _guidelines and approximations_, rather than anything else. But it'll help everyone understand roughly what constitutes 'value' to the coop.

_P.S. Can you better explain what you mean with the i. ii. and iii. points? I'm not sure I understand well enough what you mean with it._

**Comment by jasoncruzzy** [comment]
@pmoorman nice idea but I still think if we put value on each new RAM($50) I think🤔 it might still be abused by some members we might just have an influx of RNAM(RChain non active members) coming in just to add up value for members taking advantage of the system.
  I suggest we should only put value on budget for different categories of marketing, hence we have a good bounty system its already a good platform to convince new RAM. 
My suggestions on the Marketing Categories 
1) Social media channels...........($300-$400) with range of followers, management, generating RChain topics e. t. c should be the mode of measurement. We already have a lot of this but more should be accepted if necessary 

2) BlockChain discourse web/app.....($800-$1000) with RChain profile(web and summary), management, generating RChain topics for discourse, views e. t. c should  be the mode of measurement. for instance #778 is helping RChain create awareness of RChain amongst BlockChain developers. 

3) Adverts on BlockChain related events.....(1300-2000) with the size of event,  class of event(local/foreign) and mode of advert e. t. c should be the mode of measurement. for instance #770 should help create awareness of RChain amongst developers.
 Subject to more options
@pmoorman on boarding developers in most cases takes sometimes but awareness and steady update helps,, for instance I adopted the RChain ideologies from regular update on the Telegram group (RChain Africa)

**Comment by Pionelle** [comment]
There is not too much importance contributed to the cooperative, when we have to rely on people's pedigree to clearly quantify their value addition to the team.
More emphasis to me, could be placed on the work done, as seen and felt. The CV and or experiences of individuals are important and like @Ojimadu said above, the proven metrics on the work done and accessed should serve as important pointers to the value of any member joining the team

- Another issue, is this system does not allow person's who are likely to add more skills to their present skill set. Maybe the individual is onboarded as an ordinary member. Then learns to program and becomes a highly competent developer on the cooperative. The previous value we placed on that person and what we felt they could bring to RChain was temporary and then invalid. 


-
