### ISSUE TITLE
Medium Post: RCHAIN’s: HELLO WORLD — TO DEVELOPERS.

### ISSUE THREAD

**Issue by ResonanceXX** [rchain/bounties#777]
### Benefit to RChain

*An article document to complement the efforts at reaching a more targeted developer community:*

*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[Guides decide?]**
_Estimated Timeline Required to Complete the Task:_ **[2 days]**
_How will we measure completion?_ **[Edited. proof read, published.]**

https://medium.com/@kenechukwuoliaku/rchains-hello-world-to-developers-41bb6d47bf72

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by AyAyRon-P** [comment]
Hey @ResonanceXX 

Thank you for writing this. I did have a few questions and comments after reading this.

Who was the proofreader for the article? 
Do you have the ability to make edits? 

After reading the article, it seemed a bit vague and less developer-inclusive than anticipated since the article was addressed to developers.  The image should be at the very least show the coding for 'hello world'. For the sake of readability was there a purpose to numbering each segment? I wasn't able to come up with an answer to that 'why'.  Maybe add the history of 'hello world' and how RChain will add value to the developers language list? There are some sentences that and phrases that need clarity and wordsmithing, @pmoorman could also give it a once-over.

**Comment by ResonanceXX** [comment]
@AyAyRon-P   Thank you for your inquiry.

1. I proof read, thoroughly. (And I would appreciate specifics if you'd see any 'error')
2. On the coding for 'Hello World' I chose to make the article very - non technical, Basically, potential members are first timers sometimes. And seeing that writing code is a very intensive process, selling our own language (Especially since tech/programming is tending to be more attractive and not cumbersome)
 (I decided to even out the complicated details. I went with (an ideal attractive generic coding window) As you saw?
3. Yeah its a writing style, to not bore people. Since its more of soft advertising than descriptive essay.
4. On the history and beneficial qualities of RChain to the individual - That is an inexhaustible list of things - It would be injustice and premature brevity to fit all that into an introductory article such as this.
5. Clarity and beating out - @pmoorman Is the Marketing  guide, Definitely. Yeah sure!
6. Article is very editable - I am unwilling to mislead potential RAMs.

Cheers mate.

**Comment by AyAyRon-P** [comment]
1. RCHAIN NOW

The advantage of the RChain Cooperative is modeling it's platform on a correct-by-construction software development to produce a synchronal, consistent, and linearly scalable blockchain. Based on the present pace of work, efforts have been increased towards ensuring that both the manpower and technical skills required to run a more concurrent scalable blockchain are on the ground before the mainnet launch in December 2018.

2. WHY WAS RCHAIN STARTED

Any individual curious to know the need for the release of Mercury must have a look at a few documents from the RChain architecture. Greg Meredith and the development team, between them have a rich history in Maths and development:
www.rchain.coop 
https://development.rchain.coop 
http://rchain-architecture.readthedocs.io/en/latest/

3. DEVELOPERS SHOULD BELONG

The internet was a ground breaking innovation that few in the tech world gave a chance of success until large scale adoption was embraced and its full potential unleashed for the benefit of the world. The Blockchain’s path to both recognition and earning the trust of web users is reminiscent of that same struggle. The timeless battle between efficiency and resourcefulness. And as it stands, the Blockchain seems to have attained a good position in the tech world, both as a functional and dependable means of solving critical problems in today’s world.

Any individual aspiring to join a team, working towards a realizable objective of improving a fast evolving technology: come along now. The team continues to grow, with more hands, better ideas are generated.

4. HOSTING A NODE

Running RChain’s node servers on your computer system is a step towards accepting the challenge — which we at RChain have — to make the Blockchain, an even more improved solution, that can neither be limited by scale nor methods. Nodes are the basis for the RChain network. The development team has made versions of the node available for users to explore. The basic information/requirements for hosting RChain’s node are:

* An operating system — This could be Debian, Ubuntu or Windows 8/10

** Free hard disk space of roughly about -1GB. This was from my estimation of the files as seen/received. And this figure may vary according to OS specifications. (I ran on Windows 10 Home)

*** Users must at least try to read the introduction documents at the RChain wiki page for step by step directions of installation and deployment.

RChain’s Wiki page for crucial information.

5. THE INCENTIVES

Nodes act as validators, and pending a consensus meeting where modalities are to be agreed. They could be entitled to rewards for accurately contributing to the smooth running of RChain’s Blockchain. (Proof of Stake protocol)

But first thing is first, running a new technology will always involve the unattractively painstaking process of looking out for bugs and/or improvements which will improve the experience going forward.

6. THE MEET UP POINTS

The Discord Channel — The team has a chat space — RChain — on discord. The Development discussions are found in a separate room. However, users looking to join the Discord server may have to pay a membership fee on the Membership page.

On Github — RChain Repository — The repository is filled with helpful discussions from more grounded members of the RChain team. Users can create issues for questions or observations and be assured of prompt and beneficial responses. Also, the opportunity to be part of a Working Group and earn rewards remains a useful reason to give this a try.

Welcome on board!

**Comment by ResonanceXX** [comment]
@AyAyRon-P Is this an edit? Did you make any changes which should reflect in the published article? For days, you should have maybe - @ me on this. I've been getting treatment.

**Comment by ddayan** [comment]
Hello world examples are basic, having a hello world post that that has nothing to do with writing "hello world" example is a red flag. Developers that will search for rholang hello world might find this and it will make them question the project and turn away to other projects. Non-developers will think the project is a scam.

I think this issue should be closed.

**Comment by ResonanceXX** [comment]
@ddayan How? Why? Where? Why are you suggesting it be closed?

**Comment by ResonanceXX** [comment]
Non-developers will think its a scam? Do you think this project is a scam? Because if you have sentiments like this emerge from within you, then its a reflection of the state of mind you project for people that you obviously are not.

I'm trying to understand why, how, you @ddayan think the RChain project is a scam. That is a most unhelpful and deeply discouraging thought I have seen from a ''cooperative member''

**Comment by ResonanceXX** [comment]
@pmoorman And this too, I wrote this. And I promote this also.

**Comment by pmoorman** [comment]
As noted above, the marketing guides missed out on these issues last month. I've now voted a budget for this issue for July, and encouraged the other 2 guides to do the same.

I'm voting a budget significantly lower than what's being asked for, for the following reasons:

- The quality of content isn't great (also see comment of @ddayan above)
- As far as I can tell, the article has very limited reach
- Because the article isn't on a Coop-owned property (like our own blog), it doesn't represent a significant content asset to the Coop.

As guides, we try to allocate budget in proportion to the value being created for the Coop. In the case of external articles like these, value is in the reach and engagement, both of which seem to be low.

A similar reasoning (and vote) hold for issue #784, which is alike in nature.

**Comment by pmoorman** [comment]
With the above discussion, I think this issue can be closed.
