### ISSUE TITLE
Develop website information architecture

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#780]
The marketing organisation has decided that — following the strategic branding work done with Girvin — the website needs a redesign and restructuring.

@PatrickM727 asked me to create an information architecture for the new website.

The (DRAFT) document can be found here:  https://docs.google.com/document/d/1dPMLkoXWnHZVZQ41eGNxlOF17g56eVRHaa1x1xlULyE/edit?usp=sharing

Once we have agreement on the information architecture, the next steps will be:

- Engaging a professional designer / small design firm
- Producing wireframes
- Creating copy & content for the website (informed by the messaging work done by Girvin & marketing org)
- Executing the design (informed by Girvin visual identity work)
- Implementation on https://rchain.coop

I will create new issues for these tasks once we get there. For now, the most significant thing is information architecture.

**Timeline:** I aim for sign-off by marketing org by the end of this week
**Budget:**  $xxxx

**Comment by jasoncruzzy** [comment]
Very nice idea, the web actually needs a review. Some features needs to added like @pmoorman mentioned

**Comment by lopezi** [comment]
would be glad to help on the frontend implementation

**Comment by Ojimadu** [comment]
@pmoorman writes

> For a first release of the website things can be simplified (e.g. one page for “product”, etc.) and later things can be fleshed out more deeply. 

This should be the focus for now. A one-pager would be easier to navigate and flesh out later espescially on the homepage. Made some more comments in the doc.

**Comment by lopezi** [comment]
I think we are getting to a point where simplification is not the right adjective. Let's do what's need to be done. With the proximity of some main deliveries there's no need to be shy... We'll do it right, or I don't do it at all. Looking forward to see what the branding agency comes up with

**Comment by Ojimadu** [comment]
Yes, let's do what needs to be done but what needs to be done has to start from somewhere. The one pager would be like an  MVP from there things can move up.

**Comment by azazime** [comment]
@pmoorman I would appreciate if the methods of payment are looked into, possibly adding Debit-card payment and others...

**Comment by Valentine-Mario** [comment]
I think I can also help in the front end

**Comment by casanwugo** [comment]
Interesting. 

@pmoorman,, I would love to help out on "Creating copy & content for the website" if possible.

**Comment by pmoorman** [comment]
Y'all deserve a little update here on progress:

- The marketing organisation (run by Patrick & Ankur et al.) is aware of the above work, and looking to engage with people to help build out the website.

- The timeline is roughly to deliver this together with the main branding updates. That means deployment probably before Sept 1st, in time for the RCon in Berlin.

- The marketing organisation is still deciding who should be in charge of this project. This is currently blocking progress.

- For all the people that would like to help, could you send me (personally, or publicly here) some info on your background? I have some from @lopezi already, but would appreciate from others that can help. The reason I'm asking, is because this is a mission-critical element for RChain marketing, so quality of work is really important. 

- Unfortunately, I don't currently have a timeline when the marketing organisation will make a decision on who to put in charge of the website project. Obviously I'll update here once we have news.

**Comment by pmoorman** [comment]
@azazime regarding payment method: this is out-of-scope for this topic, since this is the marketing website. People that want to become members need to make a payment. There is a separate issue for this, here: https://github.com/rchain/bounties/issues/511

**Comment by pmoorman** [comment]
## Update

- The marketing organisation has now decided on a lead for the project. This will be Kevin W. (@K_Wattage on Discord). He will lead the website project.

- I haven't spoken with Kevin yet, but I'll have to work with him to figure out how the bounty community can best assist in getting this website project together. 

- I will be out-of-office next week, so probably expect another update on that in ~10 days or so.

**Comment by azazime** [comment]
$2700 is quite interesting, am sure @pmoorman has prepared a one pager document to explain the budget.

I'll always reference this budget, nice one.

**Comment by pmoorman** [comment]
The budget reflects the work done towards creating the website information architecture as requested by the marketing org (Patrick, specifically), and the discussions around it to get the website workstream started.

$2700 specifically reflects that fact that I) doing the proper research and work to create such an architecture is quite involved, II) that it's non-trivial work, and requires more extensive knowledge in the marketing domain, and finally III) that there's just a lot of overhead in the communications around such work!

**Since we're on the topic anyway, let me also post some progress for this month:**

- We have formed a small group of people that will take responsibility of the website redesign workstream. 

- The group is headed by Kevin W. of the marketing org (and also Product Marketing lead for Dropbox during daytime), and furthermore composed of @AyAyRon-P, myself and Alexandra (who is a NYC-based designer that the marketing org engaged for the task)

- The website project has hit some significant delays, because the messaging work—on which we depend—turned out to need a lot more work. I have worked on that quite extensively with Jonathan and Dror. Moving forward it looks like Kevin and myself will take ownership of this. (more info to follow, in a separate issue, that I still have to create)

- The workstream is now split into a "content" part (Kevin and me), and a "design" part (Kevin, Aaron, Alexandra). Aaron has volunteered to take the lead in community engagement regarding the website project moving forward. We'll try do this primarily through Discord I imagine.

- The information architecture that I provided was generally accepted by the group. Per Kevin's request I've further updated the document to reflect our delays, and provided for a "simplified plan" that's safer looking at the early September deadline. We're now proceeding based on this piece of work, to flesh out the content. I hope that Kevin and I can provide updates on that by the end of this week.

That's it, for now!

---

_**P.S.** I think it's a good idea that the community helps question budgets wherever it's unclear how the money was spent (and I think this definitely might have been such case). Together, we help move the bounty system forward._

**Comment by azazime** [comment]
Its still not clear @pmoorman, can you please give a mathematical breakdown of how you arrived at 2700$ for reference purposes, thanks

**Comment by pmoorman** [comment]
@azazime there is no mathematical breakdown here, rather a judgement of effort invested and tentative value to the RChain coop. Producing a high-quality website redesign is both important and complex work, and costs a lot of time.

On top of that, there is (unfortunately) a tremendous amount of communications overhead, because so many people have a say in the effort.

**Comment by pmoorman** [comment]
I will close this issue for now, since the scope has been set for what we want to produce on the v1 website, prior to RCon3.

I might re-open this again after that v1 scope, to track for iterative website updates.

**Comment by azazime** [comment]
Hurrayyyy!!!
