### ISSUE TITLE
Community Involvement In Governance

### ISSUE THREAD

**Issue by barneycinnamon** [rchain/bounties#786]
### Benefit to RChain

*We need to connect the top (Board, Officers) and the bottom (interested Coop members).*
*But how those two poles connect and what contribution is desired from each part hasn't always been clear.*
*Before there can be an effective Governance working group or committee, there needs to be some minimal shared understanding of the objectives for that group.*

Posting this stub to serve as a placeholder for collecting some thoughts on Governance generally.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[000]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by qelentium** [comment]
I think the best way to communicate is just to speak with users in their daily work. Know what people needs, which are the problems inside of coop, improvements. For example meetings in zoom with agenda of people who wants to speak to the board or officers/board who wants to speak with RAM's

**Comment by dckc** [comment]
@kennyrowe does just that on Thursdays, @qelentium . See the #boardtocoop channel.

**Comment by jimscarver** [comment]
Kenny's office hour seems like a good time to connect community engagement to related coop activities.

**Comment by lapin7** [comment]
kennyrowe office hour
Thursday, June 28
22:00 – 23:00
Weekly on Thursday
Join Zoom Meeting
https://zoom.us/j/7911989023
Description:https://zoom.us/j/7911989023
Organizer: RChain Calendar
RChain Calendar
Creator: Created by: Jim WhitescarverCreated by: Jim Whitescarver

**Comment by allancto** [comment]
@jimscarver i agree that @kennyrowe 's office hours address this issue and are the logical place to start. 

@barneycinnamon , we found it very effective at the RAM meetings to have a posted agenda where participants may list all their questions in advance. In addition to that we have a weekly scribe who converts the agenda into minutes "real-time"  as those items get addressed. @Tonyprisca13  has been super helpful in setting this up week in and week out and making sure that there's meetings are always well prepared. I won't speak for @kennyrowe and how he may like things set up (there are many paths to achieve similar ends) but i will vouch for @Tonyprisca13 , he's helped the process work reliably and well in our context. RAM discussion minutes and recordings are always available here: 
https://docs.google.com/document/d/1jvUn8AKLmvnibNk2KT-tqJdWDV5FoYZfVPIF8czxy64

If these @kennyrowe office hour discussions become interesting I'd venture that other board members will likely show up as well, and this forum will become the go-to place for discussions between our board and our membership. 

@barneycinnamon, @kennyrowe these office hours and regular contact are awesome, please just ask if there's anything myself or any of the other members are able to help with. Thanks!

**Comment by dckc** [comment]
I just realized... this issue seems awfully similar to #564. If this isn't a duplicate, somebody explain to me how it's different?

**Comment by barneycinnamon** [comment]
I am surprised by all the action. What I posted was really a placeholder just to remind me to come back the issue when I had some time to articulate what @jimscarver and I had discussed on a Governance WG call. This has some aspects in common with #564, @dckc, but this issue is about establishing some coop governance goals, in conjunction with the board, with clarity about which ones will be the responsibility of coop employees and which the board would like to see tackled by active members.

**Comment by barneycinnamon** [comment]
I see the reason for the confusion.

When I wrote...

> Posting this stub to serve as a placeholder for collecting some thoughts on Governance generally.

I meant collecting some of _my_ thoughts on Governance. :)

**Comment by barneycinnamon** [comment]
Copying some thoughts over from Discord. I will try to create a proposal for the annual meeting with some reasonable thresholds for decisions that should be treated in this way. That will at least cover member involvement. To the extent that the discourse between board and members generates ideas for additional scaffolding that deserve their own attention, maybe this will lead to a healthier governance infrastructure linking the members and the board and officers.

At the most basic, I would think you could just announce a problem you want to solve. Explain it in whatever way you can based on how well you understand its contours at the time you announce it. Put it in a dedicated Discord channel. Let people discuss. Periodically synthesize and restate was people in the channel have said. Rewrite the problem statement to incorporate the key considerations that have been posted in the channel or voiced in office hours. Be clear about your timing concerns and make it clear that the ultimate decision might not make everyone happy, but make sure everyone agrees that their concerns have been recognized and acknowledged vis a vis pros and cons of the available choices. Then have the Board vote or the membership vote depending on the urgency and importance of the decision.
I understand there is a risk of trolling or of leakage of information if you operate in such a transparent way, but that's the nature of a strategy: it has strengths and weaknesses inherent to it. If we want to truly be a cooperative and live by our core values of transparency and collective intelligence, I don't see why we wouldn't test out this type of approach. If the Coop is going to run the RChain platform, we need a testnet for our governance just as much as we need a testnet for the software.
