### ISSUE TITLE
create short instruction videos about operational processes

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#787]
### Benefit to RChain

- less how to person to person explanations
- better impression of RChain
- faster user experience

Let's contact @kennyrowe and @deannald 

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[250]**
_Estimated Timeline Required to Complete the Task:_ **[2 day]**
_How will we measure completion?_ **[video on YouTube]**
_See [Functional Spec of Member work and Rewards](https://docs.google.com/document/d/1k4xxTmfeCChCmz5aWXE3A9B_Rb1wa-5MDlpyjkoWZ4c/edit#heading=h.d1pc12swn6uz)_

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Valentine-Mario** [comment]
This is a short video I made. Hope it helps <a href="https://drive.google.com/open?id=1gUMGeXRsmQOiXR_jPDz5YHi2klBffMLa">here</a>

**Comment by Valentine-Mario** [comment]
Thanks for the feedback. I would do just that.

**Comment by Cryptovideos** [comment]
Great initiative and idea @Valentine-Mario  - is it in English? the audio is an major issue , and yes, needs a major upgrade in look and the duration a bit long -thats my 5cents...

**Comment by lapin7** [comment]
Final instruction video Invoicing.
https://youtu.be/wGAOizRcFIE

**Comment by lapin7** [comment]
I see a lot of attempts to instruct people about operational processes. A short instruction video of max 2.5 minutes with a SMART title could help out. Like the attempt of @Valentine-Mario with the explanation of becoming a member. See: https://drive.google.com/file/d/1gUMGeXRsmQOiXR_jPDz5YHi2klBffMLa/view
A more professional example is Invoicing, see: https://youtu.be/wGAOizRcFIE

There's a lot of steps to take in order to become a RAM. Let's take e.g. [CONTRIBUTING.md](https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md) as a source of inspiration.

@jimscarver suggests the following videos:

- [ ] becoming a becoming a member through KYC
- [ ] joining github through adding/joining an issue
- [ ] voting

Other time consuming onboarding tasks include:
- [ ] using wallets
- [ ] google docs
- [ ] github etc. 
- [ ] identify existing videos
- [ ] places to show our stuff

For each video describe the user story with an ordered screen flow.

Quoted email of @deannald:

> I think this is a great use of the Bounty System. What I'd like to see is: 
>
> 1. a curated list of the top questions you guys are fielding over and over again (much like the list that Jim mentioned as time consuming onboarding tasks)
> 2. a prioritization of that list (starting with most commonly asked + time consuming)
> What we are trying to ensure happens with these videos is that:
>
> - [ ] high value needs are identified
> - [ ] the videos look professional (like the ones done by Cryptvideos)
> - [ ] the videos are accurate (they are vetted by others before posting)
> - [ ] the videos are maintained / updated as needed
> - [ ] the videos are put in an easy to find area - like a folder of instructional videos for the Bounty System on YouTube
>
> I'd also like to see bounties on instructional videos outside of working within the Bounty System. This would be something to coordinate with the Marketing team (I know they are looking at a list of work items to push out to the Bounty System), but videos regarding more co-op member information. Such as, how to sign up for membership, how to do the KYC for full membership in Discord, etc.
>
> I'm looking forward to seeing how this progresses. Let me know if you have any questions!

Have also a look at [#806 Upload and submit your invoice](https://github.com/rchain/bounties/issues/806)

**Comment by TrenchFloat** [comment]
@lapin7 I checked off "voting" in your comment since I already made a [video on the b&r app](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App) as well as a slashing video.

Could you clear up some ambiguity and tell us exactly which topics you'd like videos for?

**Comment by TrenchFloat** [comment]
The norm seems to be to create separate issues for each tutorial video.
