### ISSUE TITLE
Translate "RNode v0.3.1 introduces the RChain consensus protocol" - "RChain Weekly Update (Debrief 83) 27th June, 2018" Medium blog posts to Spanish

### ISSUE THREAD

**Issue by michaelizer** [rchain/bounties#795]
### Benefit to RChain

It will help the slowly growing Spanish community (With some extra efforts from Marketing) to develop. Another step to reach the level of a Multilingual and Multicultural community.
These translations will be made satisfying the guidelines suggested [here](https://docs.google.com/document/d/1wh-GYj_MxquhUL-VyE0BkeuoskHHeq5KVdd8tL77AKQ/edit).

### Budget and Objective

_Estimated Budget of Task:_ **$[4300]**
_Estimated Timeline Required to Complete the Task:_ **[7 days]**
_How will we measure completion?_ **[Post "RNode v0.3.1 introduces the RChain consensus protocol" - "RChain Weekly Update (Debrief 83) 27th June, 2018" Medium blog posts translations to the [RChain Community Forum](https://rchaincommunity.xyz/c/Spanish-Espa%C3%B1ol/Blog)]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

  - Why translate this document?
    - It's important to translate because translation of the RChain Medium blog posts to other languages means good global marketing.
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in Spanish
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate: Proficiency in English from institution:
       - [x] a track record of quality work on rchain bounties: #597, #650, #652 
       - [x] another body of work readily available for community review:
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:

**Comment by deannald** [comment]
Hola @michaelizer!

The link you provided above for hosting translation work is broken or, at least, I'm getting a DNS error (the RChain Community Forum).

For future translation work, I'm going to defer to @patrick727 and the marketing team to prioritize which documents RChain Cooperative is looking for translation (that's not to say you can't propose others, of course). The Task Approval Committee and RChain Cooperative are trying to ensure that high valued articles, blog posts and other materials are given top priority and, further, are distributed in a manner that has great reach.

I'd like to get weigh in from @patrick727 on value of this particular issue so that budget allotted/voted is commensurate with value (higher priority translations = higher budget).

@dckc @ian-bloom

**Comment by deannald** [comment]
Gracias, @michaelizer! Mucho bueno.

Estoy deseando ver las publicaciones del blog cuando estén completas. En este momento no estoy viendo ninguno de los blogs de "RNode v0.3.1" a "RChain Weekly Update 82".

Además, no hay muchos puntos de vista en las publicaciones actuales. ¿Cuál es el número actual de lectores de este canal?

**Comment by michaelizer** [comment]
Sure @deannald! they will be there in a day or two, thanks. 

The forum is a work in progress, the main idea is to create a space for the community to discuss the blogs, know each other, also have the translated documents in one place so any future intention of marketing (e.g. for a Spanish community) will have all the required material ready and organized.

I had a chat with @allancto about a community of devs and open source contributors named [Utopian](https://join.utopian.io/), they can be a great help if we're looking for developers and "influencers" to promote the cooperative. You can check their web and ask me whatever you want, I think they could be a great help to give a little boost to the coop.
