### ISSUE TITLE
An elaborate guide to setting up RNode, Rholang and RSpace

### ISSUE THREAD

**Issue by David405** [rchain/bounties#797]
**Benefit to RChain**

Despite this [guide](https://rchain.atlassian.net/wiki/spaces/CORE/pages/428376065/User+guide+for+running+RNode) which is good for running RNode, a lot of persons still encounter issues while trying to set up Rnode on their local machine. One of the major problems not addressed by this guide is that the user **must create a var/lib/rnode directory** and this is fundamental to running nodes. This and other important steps and problems encountered where documented in this new guide. It also explains from scratch how a windows or linux user can set up and run RNode.

Part of the inspiration for writing this document was Noob school last night, we had a node testing session, not so many persons could set up node and I couldn't assist so much since my network was terrible last night.

_Estimated Budget of Task:_ **$[400]**
_Estimated Timeline Required to Complete the Task:_ **[completed]**
_How will we measure completion?_ [**[document]**](https://docs.google.com/document/d/1BxVgqE8fAsg_bNDSJyrZMfI_9hZj6jhKrBdQA30dKpg/edit?ts=5b1f7351)

cc: @jimscarver @aviationhacker @entropee and others

**NB: This was also motivated by #298 and is a progress of the issue**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by ddayan** [comment]
The marketing team is working on a simple guide to onboard validators and non-tech users.

**Comment by tschoffelen** [comment]
Would love to help with this indeed. I was thinking of some kind of slightly interactive guide, where the user can select their OS etc. to give them really specific instructions. Not yet sure though how that would look or where it would be placed exactly.

**Comment by David405** [comment]
@tschoffelen I know the concern,  if you participate in the node testing session on Tuesdays or the Colab testing session,  a lot of persons usually have OS specific problems.

I sent you a message in the #node-runners channel in the Colab server,  reply the message,  we could start from there

**Comment by deannald** [comment]
@tschoffelen and @David405 - Definitely, please coordinate with marketing to ensure that we aren't doing duplicate efforts, but combined ones. I'd love to see an updated guide for getting a node up and running that explains, based on the user's OS, different configurations, etc. I'm assuming the dev team will continue moving forward with Docker (which would eliminate some of the issues of different pulls or compiles). However, we also want to be sensitive to the fact that this is a moving target and should target documentation for post Node 5 release on July 12. Again, this is great, but please coordinate with marketing.

**Comment by David405** [comment]
@deannald I wasn't aware of the guide the marketing team was working on until @ddayan commented on this issue. One of the major motivation for putting this up like I said in my initial comment was the challenge of setting up and testing nodes we encountered during @jimscarver led noob school last Tuesday.

 I think the official marketing team not just in this issue but throughout the whole bounty program should try to always communicate their plans to enable collaborators to work better with them. I know they are doing a good job but we need to be adequately informed to avoid duplicates and unnecessary tasks.

**Comment by ddayan** [comment]
Hi @David405, I commented on the same day you posted the issue.

**Comment by deannald** [comment]
It is my understanding that @ddayan has already made considerable progress via the Marketing group on developing the content that this issue addresses. As he mentioned, he commented the same day you posted and I commented 2 days ago with the same messaging. It is true that he could have been more explicit on what exactly marketing was doing and how other bountyists could (or not) assist. 

I also agree that Marketing should move toward better outreach to the Bounty System, however, please acknowledge that they are still getting their footing on how to work within this system, how issues will get paid out, etc. That will come with time. In the meantime, my only advice would be to reach out to marketing if someone comments that there's crossover happening on an issue you would like to work on.

**Comment by David405** [comment]
Oh, @ddayan @deannald I think I get your message now, but you guys got something wrong, the document in this issue was completed even before the issue was created. Nonetheless, this shouldn't be a problem. I will be anticipating the official document from the coop, I hope it will provide elaborate information <code>bond.txt</code> file, <code>validators</code>, <code>--deploy</code>, RNode metrics GUI and other important aspects of RNode.

**Comment by tschoffelen** [comment]
Yes, and if the marketing team needs any help with actually publishing that document in a compelling format, let me know. I also created the interface for the new Rholang tutorial, so would love to help with formatting the RNode documentation in a similar way.

**Comment by ddayan** [comment]
@tschoffelen great job with the Rholang on cloud I really like it. While we are waiting for a new rchain coop website the guides will be posted as blog posts on the new rchain blog that is coming up.

I'm going to close this issue for now.

**Comment by dckc** [comment]
Please turn on comments so we can collaborate.

Meanwhile, please add a link to [the official documentation][1] from your guide. Also, add information about [who wrote it and when](https://www.w3.org/Provider/Style/SignIt.html), and what its [status](https://www.w3.org/Provider/Style/DateIt.html) is.

[1]: https://rchain.atlassian.net/wiki/spaces/CORE/pages/428376065/User+guide+for+running+RNode

**Comment by David405** [comment]
@dckc I have added the comment access and also a link to the official documentation.
