### ISSUE TITLE
Translate last 6 Medium blog posts to Ukrainian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#798]
### Benefit to RChain

Translation of the RChain Medium blog posts to other languages means good global marketing.

### Posts

- RChain Weekly Update (Debrief 77) -16 May 2018
- RChain Weekly Update(Debrief 78) — 23, May
- RNode v0.4.1 introduces sending Rholang smart contracts across the network
- RChain Weekly Update (Debrief 80) June 6–2018
- RChain Weekly Update (Debrief 81) — 13 June, 2018
- RChain Weekly Update (Debrief 82) — 20 June, 2018

### Budget and Objective

_Estimated Budget of Task:_ **$[2200]**
_Estimated Timeline Required to Complete the Task:_ **[6 days]**
_How will we measure completion?_ **["RChain Weekly Update (Debrief 77) -16 May 2018 " - "RChain Weekly Update(Debrief 78) — 23, May" - " RNode v0.4.1 introduces sending Rholang smart contracts across the network" -RChain Weekly Update (Debrief 80) June 6–2018"- " RChain Weekly Update (Debrief 81) — 13 June, 2018" Medium blog posts to Ukrainian Medium blog posts translations to the [RChain Cooperative (Ukraine) Medium](https://medium.com/@rchain_ukraine)]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because translation of the RChain Medium blog posts to other languages means good global marketing.
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in Ukrainian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate:
       - [x] a track record of quality work on rchain bounties: #710 #599 #532 #530 #531 
       - [ ] another body of work readily available for community review:
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:

**Comment by deannald** [comment]
For future translation work, I'm going to defer to @patrick727 and the marketing team to prioritize which documents RChain Cooperative is looking for translation (that's not to say you can't propose others, of course). The Task Approval Committee and RChain Cooperative are trying to ensure that high valued articles, blog posts and other materials are given top priority and, further, are distributed in a manner that has great reach.

I'd like to get weigh in from @patrick727 on value of this particular issue so that budget allotted/voted is commensurate with value (higher priority translations = higher budget).

@dckc @ian-bloom
