### ISSUE TITLE
rewards don't freeze due to trust metric interactions

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#799]
The budget votes and reward votes freeze, but the trust metric certifications don't, so they can have retrospective effects.

@lapin7 reports Wed, Jun 27, 2018 at 3:04 AM:

Output of invoice_summary_results_2018_06_11_16_36_25.csv

pay_period | worker | issues | USD
-- | -- | -- | --
5/1/18 | azazime | 662, 659, 693 | 160.00

Output of invoice_summary_results_2018_06_21_17_00_35.csv

pay_period | worker | issues | USD
-- | -- | -- | --
5/1/18 | azazime | 659, 693 | 125.00

### Benefit to RChain

robust accounting

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$125** (for code review; my work is covered by my SOW)
_Estimated Timeline Required to Complete the Task:_ **8 hrs** (4 for coding, 4 for testing / review) over two weeks
_How will we measure completion?_ **test cases**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by azazime** [comment]
I don't understand what this means?

**Comment by lapin7** [comment]
@dckc it's not an urgent problem. Only a nuisance. ;-)

**Comment by dckc** [comment]
For 201806, note that I downloaded the total of rewards per person ("invoice summary") as of a week or so ago:
https://gist.github.com/dckc/4982f0b1704c394018f4b29860b1d2b6

**Comment by dckc** [comment]
I have a fix in mind, which is to copy the weight of a voter into the reward vote, and to update all of the weights in the reward votes in the current pay period when the trust metric is updated. So on the 8th of the month, we update the trust metric and then switch the current pay period, and now the rewards are fixed.

**Comment by allancto** [comment]
@dckc @lapin7 @deannald @patrick727 this is a critical bug which affects all accounting records. The last frozen record available to accounting was made several days ago, how can we tell whether the rewards are correct? They seemed to be stable, until today there were no errors reported in invoices etc. 

What do we need to do to ensure that "Invoice Summary" produces the correct data for all periods? If we need to take snapshots that can be done, but having differing records of historical rewards isn't. If rewards.rchain.coop is NOT the definitive source for "Invoice Summary" that needs a workaround.

**Comment by dckc** [comment]
I'm not sure what's going on here... I  added a way to freeze weights for `reward_vote`, but using the July 22 frozen ratings doesn't cause the Invoice summary to match the July 22 snapshot.

## Detail:

I uploaded the July 22 ratings in a `auth_0722` table and put them into a new `reward_vote.weight` field for June votes:

```
update
reward_vote rv
left join auth_0722 r on r.login=rv.voter
set rv.weight = elt(field(r.rating, 'apprentice', 'journeyer',  'master'), 1, 3, 7)
where rv.pay_period = '2018-06-01'
;
```

And I changed `reward_wt` to use  `coalesce(rv.weight, uf.weight)`:

  - 2b6d579 rewards: use reward_vote.weight where available
https://github.com/dckc/rchain-dbr/blame/prod/dbr_views.sql#L115-L130

but in the snapshot, we find @David405	755, 800, 752, 773, 796, 758, 809, 779, 789, 735, 681
vs. in the live result:

06/01/18 | David405 | 758, 789, 735
-- | -- | --

**Comment by dckc** [comment]
Oh... tee hee... prolly should do likewise with budget votes...

**Comment by dckc** [comment]
With this fix, I _think_ June is right now:

  - `d62bad1` budget, reward: don't retrospectively drop votes
    Don't require current uf.weight > 0 when the "locked" weight > 0

At least in the case of @David405, the list of issues (755, 800, 752, 773, 796, 758, 809, 779, 789, 735, 681) and the total amount matches.

**Comment by dckc** [comment]
I hope this is close enough for June.

In this new code (d62bad1), the total of June invoices is $86,304 vs. $86,164 in the snapshot. The biggest difference is @qelentium, who comes out ahead by $124. The invoice amounts for @irynapopova61  @jplepel        @kitblake       @Mervyn853      @Ojimadu        @thiefinshadows differ by $11 or less.

Details: https://gist.github.com/dckc/887c297eee81abd4b727af46173a73a1


```
select cur.*, snap.issues, snap.usd
from invoice_summary cur
join inv_snap22 snap on snap.pay_period = cur.pay_period and snap.worker=cur.worker
where cur.USD != snap.USD;
```

**Comment by David405** [comment]
@dckc it seems the changes works quite well for 201806 pay period( with a few errors) but it generated a bug for voting for 201807 pay period, my votes counts but carries no weight

**Comment by dckc** [comment]
I can't reproduce that problem.

The system seems to be neither counting your votes nor giving them weight, which is consistent with no trust rating for you. (see also #785 )

**Comment by dckc** [comment]
I just deployed:

  - `3934d169c813`    Hide weight field when entering votes

cc @pmoorman

**Comment by ICA3DaR5** [comment]
Clicking **Update Trust Ratings** at https://rewards.rchain.coop/aux/user returns:

`Oops!
An error has been logged.

Please report the problem to #bounties in RChain-pub discord.`

Also, I just voted for July. The Weight column is empty both on **BudgetVotes** and **RewardVotes**

**Comment by allancto** [comment]
@dckc Kudos!! rewards app seems back and humming along with accurate voting records from the past. I also noticed there is a verified_coop which I was not aware of previously. This could serve as a primary key for RAM databases and help us deal with the issue of @michaelizer updating now to @michaelizer1 . Question, where does verified_coop come from, and is it available for all members (in rewards.coop it seems to be non-null for about half of the login's). 

Thanks @dckc! 
-@allancto

**Comment by dckc** [comment]
> ...  accurate voting records from the past.

I am yet to freeze the weights for May. I think I have to re-play the history of the trust_cert table to find it status as of June 9. Ugh. I hope this explains the Bug that @Ojimadu recently found: https://github.com/rchain/bounties/issues/850#issuecomment-410549994

> where does verified_coop come from, and is it available for all members

See #413 
https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App#connect-your-coop-membership

**Comment by allancto** [comment]
@dckc thanks, i believe i understand verified_coop from that, and would indicate that the field is filled only after a contributor has logged in to vote rewards at least once.

**Comment by dckc** [comment]
@lapin7 for the Q2 report (#850 ) I need help reconstructing May rewards due to this bug. Do you have a backup of the invoice summary page from around June 8 or 9? Well, some equivalent of it? I see I didn't add that page until June 18.

**Comment by lapin7** [comment]
I have given you access to reporting

**Comment by dckc** [comment]
In #847 I recommended follow-up discussion here, but on second thought, **please use #785 instead.**

**Comment by dckc** [comment]
### reward: use dynamic rewards only for current pay period

This change (c0be568) means that rewards no longer retroactively change. When a pay period closes, the process is to freeze all the rewards in the `reward_fixed` table.

### 201805 Rewards Recovered

I'm now reasonably confident about the [invoice summaries for May][inv05]. In particular, azazime's is 125, which matches that invoice (though not the amount paid, oddly).

<TABLE>
<TR>
	<TH>
		count(*)
	</TH>
	<TH>
		count(distinct issue_num)
	</TH>
	<TH>
		count(distinct worker)
	</TH>
	<TH>
		sum(reward_usd)
	</TH>
</TR>
<TR>
	<TD>
		174
	</TD>
	<TD>
		60
	</TD>
	<TD>
		55
	</TD>
	<TD>
		60677
	</TD>
</TR>
</TABLE>

```sql
select count(*), count(distinct issue_num), count(distinct worker), sum(reward_usd)
from reward_fixed
where pay_period = date '2018-05-01'
and reward_usd > 0;
```

It was pretty involved. I hope to explain in detail in due course, but I've got to go just now.

https://github.com/dckc/rchain-dbr/blob/q2_rpt/q2_adj.py cfe3fe3

https://gist.github.com/dckc/af5e9ec63342adaf033c389a84c2f0db

[inv05]: https://rewards.rchain.coop/index.php?-table=invoice_summary&-limit=30&pay_period=05%2F01%2F2018&worker=&issues=&USD=&RHOC=

**Comment by dckc** [comment]
Recovering the history turns out to be very messy. But at least we have a way to freeze rewards at the end of the month now.

For follow-up, see #850 and #785 .
