### ISSUE TITLE
Translate "RNode v0.4.1 introduces sending Rholang smart contracts across the network" - " RChain Weekly Update (Debrief 81) — 13 June, 2018" Medium blog posts to German

### ISSUE THREAD

**Issue by gsofianidis** [rchain/bounties#801]
### Benefit to RChain

Translation of the RChain Medium blog posts to other languages means good global marketing.

### Budget and Objective

Estimated Budget of Task: $[1600]
Estimated Timeline Required to Complete the Task: [7 days]
How will we measure completion? [Post "RNode v0.4.1 introduces sending Rholang smart contracts across the network" - " RChain Weekly Update (Debrief 81) — 13 June, 2018 Medium blog posts translations to the [RChain Cooperative (Germany) Medium](https://medium.com/@rchain_de)]

### Legal

Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

### Translation Checklist

for non translation issues, delete this section

  - Why translate this document?
    - It's important to translate because translation of the RChain Medium blog posts to other languages means good global marketing.
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative
) item
    - [ ] It's a document on https://developer.rchain.coop/
 that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved
    - [x] at least two of them have high proficiency in German
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate:
       - [x] a track record of quality work on rchain bounties: #737 #633 #732 #741 
       - [ ] another body of work readily available for community review:
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is:

**Comment by dckc** [comment]
Note we have dedicated guides for Translation; @PatrickM727 and @kitblake work with and delegate to @michaelizer @zero-andreou @ICA3DaR5 .

**Comment by deannald** [comment]
@dckc Thanks, that wasn't clear.

**Comment by dckc** [comment]
Hm... I wonder how to clarify. Note that if you hover over the label above, it shows who the guides are.

**Comment by deannald** [comment]
Yeah, sorry to everyone for the bombardment of clarification on translation efforts as we work through this. Has it been widely disseminated via the guides for Translation work that there will be a prioritization of what translation work is desired? I wasn't getting the impression that message was obvious in the Bounty System... I just want to avoid having people commencing on translation work if we'd prefer they translate something else that's a higher target and something that would get a higher budget vote. @michaelizer @zero-andreou @ICA3DaR5

**Comment by dckc** [comment]
> Has it been widely disseminated via the guides for Translation work that there will be a prioritization of what translation work is desired?

No, I think the Translation guides are still struggling to figure out priorities. I suggest continuing this discussion in #483 .

**Comment by deannald** [comment]
Ok, I'll stop playing whac-a-mole on translation issues and concentrate my discussion in 483. Thanks for the navigational help!
