### ISSUE TITLE
Translation Guides' Label Report (June 2018)

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#802]
### Benefit to RChain

Transparency of the work made from the Translation label guides.

**Markdown**: https://drive.google.com/open?id=1rbw-TRwMTT-80QNIM6xLa_5hgyWFK3ej
**PDF**: https://drive.google.com/open?id=1LAUfjBl_9nmeKQ-K2DgbKxQWQoohYBWj

### Budget and Objective

_Estimated Budget of Task:_ **$[600]**
_Estimated Timeline Required to Complete the Task:_ **[10 days]**
_How will we measure completion?_ **[Issue close]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Tonyprisca13** [comment]
I think the budget for each translation show be included it will give the community an idea on what is been spent on translation.

**Comment by ICA3DaR5** [comment]
@Tonyprisca13 You mean the suggested budget, right? Because there are no votes yet.

**Comment by deannald** [comment]
I'm not sure I understand the purpose of the report - isn't this just another view of already accessible information?

**Comment by ICA3DaR5** [comment]
@deannald Guides on each of the labels create a report on actions they took for that month.

Based on that a bigger report is created for the coop. This started last month with the retrospective report of the Translation label including May. https://github.com/rchain/bounties/issues/721

**Comment by deannald** [comment]
I guess perhaps I'm a little confused. Is the budget for this issue going to be set for creating the report for the month? (which appears to be an output list from rewards.rchain.coop and/or links to github issues related to translation). Or, is the budget to be set for the work actually being done as a translation guide? I'm having a hard time seeing where the 180 hours came from for generating the report for May (as the example referenced).

**Comment by ICA3DaR5** [comment]
@deannald The budget is going to be set based on the work done by the translation guides.

May was the first time this happened. In the May report we also did a retrospective check on all translation issues from January to May (more than 150 issues). [These](https://docs.google.com/document/d/1yv4NhhRYD8lPKR4ZWd5chEXC1ELEWrNrIRkfyXz9zhs/edit) are the actions we took as guides. it took as 180 hours to do the check both on integrity of the translations and on the budgets that were set. As you can see in the report we found several issues that need investigation. We investigated a lot of them and got a resolve.

**Comment by deannald** [comment]
If that's the case, then the title of this issue and the description needs to be changed to reflect that.

**Comment by ICA3DaR5** [comment]
@deannald It clearly states that is a report of the guides of the Translation label for the month of June.

**Comment by ICA3DaR5** [comment]
@Tonyprisca13 Will do tomorrow.

**Comment by ICA3DaR5** [comment]
Updated as of today, including now suggested budgets.

**Comment by ICA3DaR5** [comment]
Updated as of today including voted budgets.

**Comment by ICA3DaR5** [comment]
This has been completed. Closing.
