### ISSUE TITLE
RNode user guide for French developers.

### ISSUE THREAD

**Issue by casanwugo** [rchain/bounties#805]
Benefit to RChain

Translation of the RChain Medium blog posts to other languages means good global marketing.

ENGLISH:

- <a href="https://docs.google.com/document/d/1BxVgqE8fAsg_bNDSJyrZMfI_9hZj6jhKrBdQA30dKpg/edit?ts=5b1f735">GUIDE FOR RUNNING RNODE</a>

FRENCH:

- <a href="https://docs.google.com/document/d/1E_Idet_v4yxORL2s8EJoOnYQcEmJoCQrVfiNbqkhZMo/edit?usp=drivesdk&ouid=112097556415500676842">GUIDE DE FONCTIONNEMENT DES RNODES</a>

 Budget and Objective

_Estimated Budget of Task:_ **$[800]**
_Estimated Timeline Required to Complete the Task:_ **[ DONE ]**
_How will we measure completion?_ Translated document has been posted to <a href="https://medium.com/@annchidinma5">Medium blog</a> and <a href="https://t.me/Rchain_Africa">RChain_Africa Telegram</a> in order to reach out to the french audience. **[example: pull request merged]**

  COLLABORATORS : 

- @casanwugo  65%
- @philipandri002  35%

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #711
       - [x] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by deannald** [comment]
Help me out on the trail here... where does the English language version of this document originate from (link?)? Also, where does it show endorsement for translation from the people referenced above (link?)? Thanks!

**Comment by casanwugo** [comment]
Hi @deannald, please see issue #797. Thank you.

**Comment by casanwugo** [comment]
Ok, i will do that. Thank you.

**Comment by ICA3DaR5** [comment]
@casanwugo Hi, in our private chat you asked from me to vote you, @deannald prompted you to ask the translation guides to point you to the most recent documents. You didn't do that. Why is that?

**Comment by casanwugo** [comment]
@ICA3DAR5 Hello, sorry about the mix up... But i think you should go through our earlier chats because i think you misunderstood me. 

The document was already sent out for translation before @deannald prompted me to liaise with the guides. Hence i told you in our conversation to see "her comments" once the translated doc was ready to know if it was ok to go ahead and post... And you gave me a go ahead. I did as she requested of me.  Please, do go through our chats again.

**Comment by ICA3DaR5** [comment]
@casanwugo Again, you haven't answered why you are translating this? Since it's not up for translation.

you have stated that it's an [RChain blog](https://medium.com/rchain-cooperative) item, which is not.

Therefore the translation guides are going to slash you.

**Comment by Ojimadu** [comment]
Is slashing necessary?

**Comment by casanwugo** [comment]
@ICA3DaR5,, I answered you earlier, and have been waiting for your response on what i should do next since the work had already been posted. It wont be fair to slash me, because you gave me the go ahead to post, though it was a mistake. I have deleted from Medium and Telegram. Please kindly withdraw slash. Thanks.

**Comment by ICA3DaR5** [comment]
@Ojimadu @casanwugo is being dishonest by stating that what she is translating is an RChain blog item, which is not.

@casanwugo You never asked me to point you to the most recent documents for translation, you just asked me to vote for you. I'll chat with the other guides and see if we made a mistake. Why have you deleted from Medium?

**Comment by casanwugo** [comment]
@ICA3DaR5... I did tell you to see @deannald's comments before continuing with this issue. But like i said earlier, sorry about the mix up if you misundertood me on the chat.

I had to delete the post from Medium, because you have now pointed to me that it isnt an RChain blog item, and i cannot go contrary.

Thanks.

**Comment by ICA3DaR5** [comment]
@casanwugo It is mentioned on the [ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md).

> It's important to translate because ____
>  - It's an RChain blog item
>  - It's a document on https://developer.rchain.coop/ that has been endorsed
>    for translation by @Jake-Gillberg, @MParlikar, or @KellyatPyrofex

I just pointed out that you have chosen the first option, without it being true.

**Comment by philipandri002** [comment]
I guess this is a case of mistake, not intentionally trying to defraud the system.. I think if @casanwugo reached out to @ICA3DaR5 before even going ahead to publish then she was not intending to do wrong.. 

@ICA3DaR5 you should have taken out time to look at the issue the moment she reached out to you in the first place and that would have prevented a lot of this unfortunate situation...

Imo the slash is unnecessary.. Let other admin look into it..

I for sure know that @casanwugo is still very new and doesn't know much around this things.
