### ISSUE TITLE
video: Submit your invoice

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#806]
### Benefit to RChain

- less how to person to person explanations
- better impression of RChain
- faster user experience

Let's contact @kennyrowe and @deannald 

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[250]**
_Estimated Timeline Required to Complete the Task:_ **[2 day]**
_How will we measure completion?_ **[video on YouTube, integrated in docs]**
_See [Functional Spec of Member work and Rewards](https://docs.google.com/document/d/1k4xxTmfeCChCmz5aWXE3A9B_Rb1wa-5MDlpyjkoWZ4c/edit#heading=h.d1pc12swn6uz)_

*See CONTRIBUTING.md for details on budget and reward process.*

Upload and submit your invoice
video-example: https://youtu.be/-yDROU93upU
- [x] show downloaded invoice_pdf
- [x] click on link Personal folder
- [x] show how to upload invoice_pdf to personal folder Invoices (drag and drop?)
- [x] show how to create shareable link >> CTRL-click on the selected file and tick "Get shareable link". Don't forget to tick also the green button to set the access to "Link sharing off"
- [x] pay attention to file access changes
- [x] show how to navigate to folder Members/Finance / file [Declarations](https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform)
- [x] explain difference between edit and view
- [x] fill out: email, github name, total in USD, month
- [x] paste the shareable link
If you haven't submitted your Tax-form for 2018, then you do the same action with this PDF for the field "TaxURL" 
- [x] go to personal folder tax 
- [x] create shareable link
- [x] go back to form declaration
- [x] paste the shareable link
- [x] submit
- [x] show email response about submission

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by TrenchFloat** [comment]
Is your video-example the finished product?

**Comment by TrenchFloat** [comment]
Found [cryptovids's video](https://www.youtube.com/watch?v=wGAOizRcFIE&t=28s). In #787, HJ [called this](https://github.com/rchain/bounties/issues/787#issuecomment-401118132) a "more professional example," which sounds like completion to me.
