### ISSUE TITLE
Help marketing promote "What is RChain all about?" Youtube video

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#807]
The marketing organisation has just delivered this excellent, high-quality Youtube video covering all the coolest aspects of RChain and it's technology:

https://youtu.be/f1D4vowiMiI

The marketing team needs as much help as possible from all of us to help spread the video as widely as possible. 

**Things that can help:**

- Posting on Facebook, Twitter, etc. 
- Promoting in groups that you're part of, or communities you frequent
- Promoting on Reddit
- Writing a "value add" to go with it, and publish it in appropriate channels
- .... and a million more options I maybe haven't thought of yet!

**Bounty:** $2.000
**Timeline:** next 10 days

---

cc @traviagio @zsluedem @PatrickM727 @qelentium @David405, @Ojimadu @Mervyn853 and many, many others :D

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by PatrickM727** [comment]
Make sure to post whatever it is that you do here so that we can value add to your work as well and also keep each other honest. 

For example if you post it as an answer on quora we can upvote it(if its quality).

If you write a reaction post, then share it here, etc etc

**Comment by decentralizebanksy** [comment]
Posts from the RChain social media channels: 

Twitter - [](https://twitter.com/rchain_coop/status/1012363216557658112)
Reddit - [](https://www.reddit.com/r/RChain/comments/8ukgb5/what_is_rchain_all_about_by_futurism/)
Facebook - [](https://www.facebook.com/rchaincooperative/posts/411083825965989)
Linkedin - [](https://www.linkedin.com/feed/update/urn:li:activity:6418133963570708480)

Like, Comment, Share, Heart, Retweet, Reply, Upvote, etc

**Comment by qelentium** [comment]
Thanks for assigning. Will post it on facebook and vk.com,  plus at some russian blockchain channel. Every post gonna merge here ✌️

**Comment by azazime** [comment]
I'm interested @pmoorman

**Comment by Cryptovideos** [comment]
Lovely stuff

**Comment by casanwugo** [comment]
@pmoorman,, Great stuff! I have posted on the following media;

- <a href="https://medium.com/@annchidinma5/are-you-interested-in-blockchain-ever-heard-of-rhocs-wanna-learn-something-new-86f667cb2282">Medium blog</a> 

- <a href="https://m.facebook.com/story.php?story_fbid=1993264794064967&id=100001443976348">Facebook</a> 

- <a href="https://www.linkedin.com/feed/update/urn:li:activity:6418181456585195520">LinkedIn</a>

**Comment by azazime** [comment]
![screenshot_20180628-215814](https://user-images.githubusercontent.com/38160042/42060528-0a3f5f00-7b1f-11e8-9f18-fff1594d1f79.png)
![screenshot_20180628-215659](https://user-images.githubusercontent.com/38160042/42060609-504f4b22-7b1f-11e8-930d-ddb1bab1ac6e.png)
Screenshots of video link posted on a (closed group)  of over 20,000 members with hundreds of programmers on facebook.

**Comment by Pionelle** [comment]
Hello @pmoorman Posted this on my **telegram crypto communities** with about 150,00 members. ;) 

Still have more to reach!

**Comment by Pionelle** [comment]
![capture](https://user-images.githubusercontent.com/36760393/42072613-53a6d396-7b59-11e8-962d-cc4b2c7d5075.PNG)
![capture1](https://user-images.githubusercontent.com/36760393/42072614-53e5c5d8-7b59-11e8-9b7f-2c186876b025.PNG)

**Comment by Pionelle** [comment]
![capture2](https://user-images.githubusercontent.com/36760393/42072701-d8154266-7b59-11e8-87a8-89cdb64ff501.PNG)

**Comment by nonnykul** [comment]
@pmoorman, I have posted the video on [nairaland](http://www.nairaland.com/4588596/what-rchain-all). with 34views and still counting...

**Comment by zsluedem** [comment]
##  publish the videos in china website
The video has translated into Chinese already~!
video address: 
1. https://www.bilibili.com/video/av25802369/  
2.https://v.qq.com/x/page/c0706527sbu.html

## published in the Wechat Official Account:
https://mp.weixin.qq.com/s/mrFMOKwo2IqerA3OhZMfTg

## spread this video in the Wechat group and qq group
![image](https://user-images.githubusercontent.com/13496262/42081228-7b2b6f4a-7bb7-11e8-8fbe-f1ac6a5e0561.png)

![image](https://user-images.githubusercontent.com/13496262/42081247-884243f2-7bb7-11e8-98e3-d6b90ba27b24.png)

**Comment by BelovedAquila** [comment]
This video really has to go places, would be posting at various strategic positions that comes to mind and as am able to access, various social medias,  would be sending  feedbacks

**Comment by BelovedAquila** [comment]
Twitter 
![img_20180629_102123_099](https://user-images.githubusercontent.com/34511117/42086250-75023a5e-7b8a-11e8-98ab-bbe422bbb85c.JPG)

**Comment by kaka56** [comment]
Awesome video it is. Posted It on
[ Facebook Group ](https://www.facebook.com/groups/1547982022154996/)
[Linkedln](https://www.linkedin.com/feed/)
[Nairaland ](http://www.nairaland.com/720565/programmers-what-project-working-now/7#68927351)

**Comment by BelovedAquila** [comment]
Facebook 
![img_20180629_111851_995](https://user-images.githubusercontent.com/34511117/42087513-50176fc6-7b8e-11e8-92a3-022bd23095a3.JPG)

**Comment by jasoncruzzy** [comment]
POSTED THE ISSUE ON

BOUNTY-ONE BLOCKCHAIN FORUM~See link here https://talk.bountyone.io/t/rchain-rholang-scalable-independent-performs-better/267?u=rchain_coop


Also posted it on
Reddit(RChain_Africa)~https://www.reddit.com/user/RChain_Africa/comments/8umjb0/rchainrholangscalable_independent_performs_better/?utm_source=reddit-android

**Comment by PatrickM727** [comment]
@everyone this is great!
lets keep the momentum going with this post

https://futurism.com/scalable-blockchain-technology-rchain/

this is the follow up to cause virality!

**Comment by azazime** [comment]
Link of video posted on medium👇

https://medium.com/@andrewasamonye/rchain-coop-a1479a95cbb6

**Comment by azazime** [comment]
Link of video posted on instagram 👇

https://www.instagram.com/p/BknQ-XCl1sE/?utm_source=ig_share_sheet&igshid=1pq1l2on3noe5

**Comment by qelentium** [comment]
[Post in Facebook](https://www.facebook.com/qelentium/posts/921135521406903)

**Comment by dckc** [comment]
The video is great in a lot of ways, but I'm actually still reluctant to share it with, for example, a good friend with an investment background. There are some critical edits where it's too geeky or something.

IOU some more details, @PatrickM727 . Do you have anything scheduled to gather "second circle" feedback on this video? Meanwhile, I'll use this issue to track my plans to provide further feedback...

**Comment by David405** [comment]
@pmoorman,  kindly clarify your input on this issue and explain why you assigned 60% of the rewards to yourself.

**Comment by jasoncruzzy** [comment]
@PatrickM727 please clarify the need for this comment, or was it said just to get us in?? "make sure to post whatever it is that you do here so that we can value add to your work as well and also keep each other honest.For example if you post it as an answer on quora we can upvote it(if its quality).If you write a reaction post, then share it here, etc etc"

**Comment by pmoorman** [comment]
@David405 good call. It looks like I've voted rewards here that were supposed to go to #776 instead (for Dror and for myself).

I've now removed those votes, and moved them over to #776 where they belong!

@dckc how can I remove a vote? I know how to edit one to (so I've now edited both votes to 0%), but it would be cleaner to just remove my vote.

**Comment by dckc** [comment]
The help video shows how to delete votes.

(I'm on mobile.)

**Comment by philipandri002** [comment]
@pmoorman @AyAyRon-P @kitblake. IMO I think most of us who collaborated on this issue didn't get the right idea of what this was suppose be. From what I'm seeing here most persons do not understand that RChain is not for every audience. You may have 8million follower's on Facebook, twitter or other social handle yet it doesn't make that the right RChain audience. 
I would have expected that we search out a designated block chain groups/crypto enthusiasts platform to promote the video.

I also think the intention of this issue was not to post the video at random but to create insightful content about RChain to be backed up with the video on specific block chain channels or groups.

Kudos to @jasoncruzzy I think he did a great job..

I would suggest to the guides that we get team member who specialises in content creation before the marketing team would be ask to promote on designated platform relevant to the RChain/Blockchain technology.

Thanks

**Comment by azazime** [comment]
@pmoorman I would really like to understand why this budget has not been shared and allocated accordingly yet???

Or is there a mistake on it? Please kindly clarify guider @pmoorman, thanks

**Comment by pmoorman** [comment]
@azazime good question. 

Because the issue was created only on the 28th of June, we decided that it would be better to allocate the rewards in the month of July rather than June. As such (even though we had already voted a budget), we decided to let it expire in June, and re-vote it in July.

I've just gone in and voted the suggested budget for this month ($2,000), and will vote for rewards a bit later, when I have more time to look into the relative contributions of everyone.

Hope that clarifies it!

**Comment by jasoncruzzy** [comment]
@pmoorman What's our input on this, I think the objective of this issue has long been accomplished!

**Comment by pmoorman** [comment]
@jasoncruzzy yes I agree! In fact, I think you're right that the issue can be closed, because the work has more or less concluded.

I have voted everyone who's made a contribution an equal part of the reward. That's what @kitblake suggested, and mostly for practical reasons. **If anyone feels treated unfair about that, then let us know.**
