### ISSUE TITLE
Translate "RNode v0.4.1 introduces sending Rholang smart contracts across the network" Medium blog post to French. 

### ISSUE THREAD

**Issue by casanwugo** [rchain/bounties#808]
Benefit to RChain 

Translation of the RChain Medium blog posts to other languages means good global marketing.

ENGLISH:

- <a href="https://medium.com/rchain-cooperative/rnode-v0-4-1-introduces-sending-rholang-smart-contracts-across-the-network-e076d0961b3e">RNode v0.4.1 introduces sending Rholang smart contracts across the network</a>

FRENCH:

- <a href="https://medium.com/@annchidinma5/rnode-v0-4-1-introduit-lenvoi-de-contrats-intelligents-rholang-%C3%A0-travers-le-r%C3%A9seau-32fa2a3c3914">RNode v0.4.1 introduit l'envoi de contrats intelligents Rholang à travers le réseau</a>

 Budget and Objective

_Estimated Budget of Task:_ **$[ 800 ]**
_Estimated Timeline Required to Complete the Task:_ **[ Completed ]**
_How will we measure completion?_ Posted on <a href="https://medium.com/@annchidinma5">Medium blog</a> and <a href="https://t.me/Rchain_Africa">RChain_Africa Telegram</a> **[example: pull request merged]**

COLLABORATORS :

- @casanwugo  70%
- @philipandri002  30%

*See CONTRIBUTING.md for details on budget and reward process.*

  Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

  Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #711
       - [x] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by michaelizer** [comment]
Hello @casanwugo, please fill the slots in the template. Also, translations per se are not a cooperative's priority right now, please check [Allan's comment](https://github.com/rchain/bounties/issues/790#issuecomment-400029403) about that.

**Comment by deannald** [comment]
For future translation work, I'm going to defer to @patrick727 and the marketing team to prioritize which documents RChain Cooperative is looking for translation (that's not to say you can't propose others, of course). The Task Approval Committee and RChain Cooperative are trying to ensure that high valued articles, blog posts and other materials are given top priority and, further, are distributed in a manner that has great reach.

I'd like to get weigh in from @patrick727 on value of this particular issue so that budget allotted/voted is commensurate with value (higher priority translations = higher budget).

@dckc @ian-bloom

**Comment by casanwugo** [comment]
@michaelizer,, i will do that. Thank you.

**Comment by ICA3DaR5** [comment]
@casanwugo Could you please justify the $800 suggested budget for a single blog post?

Counting the words and looking at other translators prices this should be a ~$200 budget.

**Comment by casanwugo** [comment]
@ICA3DaR5... The reason for the budget is because of the manual imput, time, and other expenses involved in getting the translation work done.

**Comment by ICA3DaR5** [comment]
@casanwugo I am translator myself as well as the other translation label guides (@michaelizer, @zero-andreou). We know how much effort the translation process takes. An $800 budget for a single blog post (850 words) is exaggerated. We are voting $200 for this.
