### ISSUE TITLE
review of 201806 pay period rewards by guides

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#809]
Much like #759 last time. Guides: let us know when you're done for this pay period.

   - [x] Marketing - cf. #817
   - [ ] Operations
   - [x] Translation
   - [ ] Development
   - [ ] Governance
   - [ ] member-site
   - [x] Education
   - [ ] Greeter
   - [x] Events
   - [x] Africa
   - [ ] Branding
   - [x] Voting

As to reporting: @deannald and I lean toward quarterly reporting.

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by allancto** [comment]
@dckc , @deannald d it's my opinion that quarterly reporting may be fine for traditional centralized organizations, but as we move forward at "lightspeed" i think you'll find monthly reporting useful. 

The more important question, imo, is why will we continue to have label guides at all? The TAC by definition has the role of communicating to our contributor teams what are the goals are of our Cooperative, and equally of reporting to our Cooperative what the accomplishments of our bounty contributors have been. 

The TAC is functioning as designed. Please don't add a layer of indirection where none is necessary: it's the role of TAC to do these things and TAC is already doing them well. 

cc @dckc @deannald @patrick727 @lapin7 
cc @jimscarver @kitblake @TrenchFloat @Ojimadu @Jake-Gillberg @AyAyRon-P most of you are already involved in actual projects, imo that's where the big contributions are to be made. @jimscarver is imo exemplary, he's working, guiding, and providing information back to our Cooperative. @Jake-Gillberg in the Collaborative Learning he's contributing, guiding, and providing information.

**Comment by dckc** [comment]
As to why we continue to have label guides:

> The Task Approval Committee delegates to Bounty Task Guides and others via a community trust metric. -- [Task Approval](https://github.com/rchain/bounties/wiki/Task-Approval)

The three members of the TAC are not performing the roles you note without help from the guides. The guides are necessary.

**Comment by zsluedem** [comment]
In #803 , I have made a [China community report in June](https://docs.google.com/document/d/14e7o5EkGdxzZx9cEvOi2n_YsTdZDOsdUSohifMvPKzE/edit#) . I think this will help the core community know the China community.

**Comment by dckc** [comment]
@deannald @Jake-Gillberg I'm headed out for the holiday soon; I'd like your help with https://github.com/rchain/bounties/issues/789#issuecomment-402510454

**Comment by dckc** [comment]
I asked @allancto to help @deannald and @PatrickM727 get in touch with the guides to wrap this up.

**Comment by dckc** [comment]
@deannald would you please certify the guides that you have formed effective working relationships with? [The list of people you have certified][1] is empty.

@PatrickM727 the certifications you made as @patrick727 have no effect. Please re-do them as @PatrickM727 . (Well, I'd rather you went back to your @patrick727 account, but I can imagine that's infeasible.)

[1]: https://rewards.rchain.coop/index.php?-table=github_users&-search=deannald&-action=list&-submit=Search+Users#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-table%3Dgithub_users%26-search%3Ddeannald%26-action%3Drelated_records_list%26-submit%3DSearch%2BUsers%26-cursor%3D0%26-skip%3D0%26-limit%3D30%26-mode%3Dlist%26-recordid%3Dgithub_users%253Flogin%253Ddeannald%26-ui-root%3Dmain-content%26-relationship%3DCertified

**Comment by David405** [comment]
@dckc I guess the [Community report in Africa for June 2018](https://docs.google.com/document/d/1zRWt43P7UXFs99FGJD_TQnVNeebJ2dlG2Fv06BF_E_Q/edit#heading=h.o9133o7w4qhx) can serve the purpose of a review, what's your take on it?

**Comment by dckc** [comment]
I imagine the report is fine.

My only question here is: are the [Africa rewards for 201806][1] all set? If so, please check the box above. If not, what is left to do?

[1]: https://rewards.rchain.coop/index.php?-table=reward&-limit=30&pay_period=06%2F01%2F2018&labels=Africa&-action=list&-cursor=0&-skip=0&-mode=list&-sort=budget_usd+desc

**Comment by dckc** [comment]
@David405 says there's outstanding voting to fix for a meetup issue.

**Comment by BelovedAquila** [comment]
please I observed the budget and rewards for most  meetings related issues as at 201806 hasn't been set, like issue #782 #773 #757 #800 please can that be looked into?

**Comment by philipandri002** [comment]
Also issue #781 is yet to be addressed by either of the marketing, education and discussion guides save event guide@ojimadu. please I think the guides need to visit with urgency and sort it out.

Thanks...Frank Nnalue

**Comment by Ojimadu** [comment]
The events label is done for 201806. I voted a budget of $1600 being that marketing and translation guide has created an issue for those labels. I think this should be do. I claimed a reward based on an estimated 5 hour work. I and @trenchfloat needs help completing the rewards.

**Comment by David405** [comment]
Rewards for Africa issues is set

**Comment by Tonyprisca13** [comment]
Need help with reward and budget vote for this issues 773 782 800. Thanks

**Comment by dckc** [comment]
At the request of @lapin7 , I rolled over to July:
> current: **201807** -- https://rewards.rchain.coop/

**Comment by dckc** [comment]
In our July 4 meeting (#823) @allancto took the ball to get the TAC in touch with the label guides. We got just 3 of 12 area labels checked off. Any idea where things broke down, @allancto ?

**Comment by allancto** [comment]
@dckc TAC is in touch with the label guides using the Label guide discord server, to which you have been invited. 

Voting for June is complete. There is a blank report and a list of issues that were budgeted in June in the folder below. Label guides should look at the spreadsheet first, fill in ColumnE for issues you guided, and help complete the overall report. Thanks! -@allancto
Folder: Bounty System Monthly Reports
https://drive.google.com/drive/folders/1JgtKUIb12RUcDazhZHZHp9guUH2Oq-xP

**Comment by dckc** [comment]
Well, voting for June is over in that the due date is passed. But is it complete in that guides from each label area have confirmed that the votes in their area are appropriate? The empty check-boxes above suggest otherwise.

Again, from the July 4 notes:
>  if the new discord server gets us there, fine, but the target is the check-marks that represent, for example, closure on [Africa rewards for 201806][1]

[1]: https://rewards.rchain.coop/index.php?-table=reward&-limit=30&pay_period=06%2F01%2F2018&labels=Africa&-action=list&-cursor=0&-skip=0&-mode=list&-sort=budget_usd+desc

**Comment by allancto** [comment]
@dckc so your purpose in this issue is for someone (the lead guide in each label?) to check that they've reviewed the votes in their label?

ColumnE is there to determine which label is responsible for reporting on an issue (where multiple labels exist). IMO that should be in the issue template. Or are you saying that bit of information is simply irrelevant? 

Thanks! -@allancto

**Comment by dckc** [comment]
> your purpose in this issue is for someone (the lead guide in each label?) to check that they've reviewed the votes in their label?

Yes; that is: a guide from each label. (As we discussed, I have no use for the notion of "lead guide".)

> ColumnE is there to determine which label is responsible for reporting on an issue (where multiple labels exist). IMO that should be in the issue template. Or are you saying that bit of information is simply irrelevant?

I'm saying it's redundant make-work. If an issue has multiple labels, then guides for all those labels are responsible for it. If something is labelled Development and I don't want to be responsible for it, then I just remove  the Development label.

This went quite smoothly in May (#759). My attempt to delegate this time evidently didn't work out. @deannald has wisely reserved some time for TAC / guide meetings, which should smooth things out for next month.

**Comment by TrenchFloat** [comment]
I'm seeing a pull towards quarterly reports as opposed to monthly, although it is hard to tell if the discussion is over. Is there a final answer?

And if it is quarterly reports, does that mean we're holding off until July is over? That would be 3 months from April.

cc @dckc @allancto

**Comment by allancto** [comment]
@TrenchFloat thanks for your question. Both @dckc and @deannald of TAC have requested quarterly reports. The title June was changed to Q2, TAC please let us know how you'd like this handled: should a report still be prepared for Q2 (we have already the May retrospective) or we should wait until Q3 (and make that report Sep 30 leaving June hanging, or Aug 31). 

Request to Label guides: please indicate by check mark in the issue statement above that you have reviewed voting within your label for June (will post this request as well in the discord Label Guides server). 

Thanks! -@allancto

**Comment by TrenchFloat** [comment]
@allancto May was not included in the retrospective report. So May, June, July would make 3 months, unless I'm mistaken.

**Comment by dckc** [comment]
Some stuff about May got added to the retrospective report. I found it somewhat confusing.

May, June, and July would be a quarter, but sort of a skewed one. Q2 is traditionally Apr, May, June. So we could get back on a traditional schedule if we covered June plus whatever seems useful from April and May in our Q2 report.

**Comment by TrenchFloat** [comment]
I'm making an issue for a Q2 report: April, May, June.

**Comment by dckc** [comment]
Thanks.
