### ISSUE TITLE
Translation of 2 medium blog's about RNode v0.4.1 and Weekly debrief

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#810]
### Benefit to RChain

Will translate [RNode v0.4.1 introduces sending Rholang smart contracts across the network](https://medium.com/rchain-cooperative/rnode-v0-4-1-introduces-sending-rholang-smart-contracts-across-the-network-e076d0961b3e) and [RChain Weekly Update (Debrief 81) — 13 June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-81-13-june-2018-415b4318b02b) it will bring quality for people to understand more about RChain.Will add my comments and understanding to article as said in [this](https://docs.google.com/document/d/1wh-GYj_MxquhUL-VyE0BkeuoskHHeq5KVdd8tL77AKQ/edit) document about value

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[2000]**
_Estimated Timeline Required to Complete the Task:_ **[7 days]**
_How will we measure completion?_ **[Will post at [RChain_RU](https://medium.com/@rchain_ru)]**
[RNode v0.4.1 вводит отправку смарт-контрактов Rholang по сети](https://medium.com/@rchain_ru/rnode-v0-4-1-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B8%D1%82-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D1%83-%D1%81%D0%BC%D0%B0%D1%80%D1%82-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BE%D0%B2-rholang-%D0%BF%D0%BE-%D1%81%D0%B5%D1%82%D0%B8-b8e742ad7202)
[Еженедельное обновление RChain (Дебриф 81) — 13 июня 2018 года](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%84-81-13-%D0%B8%D1%8E%D0%BD%D1%8F-2018-%D0%B3%D0%BE%D0%B4%D0%B0-6eb8e7c0421d)
*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because of RNode new update and history of community (debrief)
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved 
    - [x] at least two of them have high proficiency in Russian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] native speakers
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [x] our plan to keep the translation up to date is: 7 of July

**Comment by deannald** [comment]
For future translation work, I'm going to defer to @patrick727 and the marketing team to prioritize which documents RChain Cooperative is looking for translation (that's not to say you can't propose others, of course). The Task Approval Committee and RChain Cooperative are trying to ensure that high valued articles, blog posts and other materials are given top priority and, further, are distributed in a manner that has great reach.

I'd like to get weigh in from @patrick727 on value of this particular issue so that budget allotted/voted is commensurate with value (higher priority translations = higher budget).

@dckc @ian-bloom

**Comment by dckc** [comment]
@deannald note that @PatrickM727 is the account he uses these days.

He no longer has control of @patrick727 . I encouraged him to contact github support to restore access to that original account rather than splitting his reputation, but I can imagine other priorities don't leave time for such administrivia.

**Comment by michaelizer** [comment]
Hello @qelentium! could you please justify the estimated budget for this task?

**Comment by allancto** [comment]
@qelentium this belongs in Community Building. The purpose of the Smart Contracts video is to get a community of smart contract developers. If you need to translate "organically" as part of that, you may certainly post links to the translation (for instance in the Russian Language Speakers Monthly Report). As far as the *effectiveness* of your community building work, I'd look to see repositories and servers actively running rholang smart contracts, rholang nodes and so on. 
https://docs.google.com/document/d/1uwfmGX-G0UrmCZfNAJl2Zot5irUYUOvIcQVfP65BtxY/edit?usp=sharing

Thanks! -@allancto

**Comment by qelentium** [comment]
@michaelizer yes, its going to be not only translation but comments and explanations included.its gonna help to grow up russian community and understand better what is RChain,

**Comment by qelentium** [comment]
Translation done.Checked.Reviewed.Added commentary and explanations

**Comment by allancto** [comment]
@qelentium where are the comments and explanations in the source language (English)? Are there specific instances of community building- code, workgroups and so on- that you built with this? I don't see any contributions to "RChain Russian Language Community Worldwide Report Jun 2018".

**Comment by qelentium** [comment]
Its translation. @allancto its not about our works in workgroups

**Comment by allancto** [comment]
@qelentium I see that the Translation guides have voted $620 on this issue. I will reclose this issue and leave it at that.
