### ISSUE TITLE
Translate Rchain Whitepaper.pdf to Croatian- Reopened

### ISSUE THREAD

**Issue by InternautNeven** [rchain/bounties#811]
## Translate Rchain Whitepaper.pdf to Croatian- Reopened

My team and I have worked together on several issues (#125 #382 #544 #546) and it was a great cooperation 
not only between members of the team but also with community or Cooperation.
There is just one issue on which we have worked on that we need to reopen in order to get reward for it. 
It is an issue that was opened and finished in February. The problem was with bounty system at that time 
and it is open again. Voting went at $ 2399.99  from the 5 voters but the votes have dispersed 
in February and March so the votes weren´t considered and we couldn´t get any reward for the issue although
 we have asked at the Discord/Bounty couple of times for it and on the GitHub (#477).  
We just could do nothing but to open it again like this. In the meantime, we used it and distributed it
 at the Meetups and we will put it at the Blog probably next month.
 From here text is copied from previous issue:

---

### Original (English) Content
- [RChainWhitepaper](https://github.com/rchain/reference/blob/master/docs/RChainWhitepaper.pdf)

### Translated (Croatian) Content
- [RChainWhitepaper_HR](https://drive.google.com/open?id=1Pr1OAuhp36qKL-JpLxccwXQrJOkiIGH1)

To attract people from different cultures and with different languages. This is easiest when the English version is translated into local spoken languages. Whitepaper is basic guide that informs readers concisely about a Rchain project and present the matter. 
We will translate it in a 30 days.
Why: interest in telling the story of RChain in another language.
 
Collaborators:
* @InternautNeven
* @MarioPolo 

 Reviewers:
* @tgrospic 
* @Howsoonisnow 

Tasks:

- [x] Translate the content
- [x] Check the spelling
- [x]  Review each other's work
- [x]  Have it reviewed by others with knowledge of English and Croatian
- [x]  Create the .pdf file

* @InternautNeven: 50 %
* @MarioPolo : 20%
* @Howsoonisnow 25%
* @tgrospic 5%

### Other Information

Completed: 100%

Suggested Budget: $ 2399.99

Why this/these document(s)? (mark all that apply)

- [x]  It's one/some of the /rchain/reference document(s).
- [x] I know a person or audience who would benefit from it: The Croatian developers community.
-  [x] Several reviewers are involved. (assign the ticket to them)
-  [x] At least two of them have high proficiency in English.
-  [x] At least two of them have high proficiency in Croatian.
-  [x] At least two of them have either:
-  [x] Significant reputation Diploma
-  [x] A track record of quality work on rchain bounties: #382, #125 

What about maintenance? (choose one)

*  [ ]  The source document(s) is/are stable; further translation work is not expected.
*  [x] Our plan to keep the translation up to date is: Translate all the future updated documents.

**Comment by ICA3DaR5** [comment]
@InternautNeven Please use the new [ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)

Also the [RChainWhitepaper](https://github.com/rchain/reference/blob/master/docs/RChainWhitepaper.pdf) file is obsolete and doesn't comply with the [ISSUE_TEMPLATE](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md)

**Comment by InternautNeven** [comment]
It is not problem with template and i can use new template, but if you read Issue- it is done issue in February of this year #449- and then it was not obsolate. It was finished in time, and only reason why i opening it is - error in bounty system. And this is only way to re-open it and vote again.

**Comment by ICA3DaR5** [comment]
@InternautNeven Okay, please take this issue and post it on Discord up for discussion so we can have a consensus.

**Comment by InternautNeven** [comment]
Sure, i put it on Discord/Bounties.

**Comment by dckc** [comment]
It's not too late to vote on budgets and rewards for #449. This is a duplicate; please don't vote on this issue.
