### ISSUE TITLE
ONGOING: Weekly Debrief Index Maintenance

### ISSUE THREAD

**Issue by TrenchFloat** [rchain/bounties#812]
I maintain the [Weekly Debrief Index](https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index) by writing up timestamps for Greg's streamed hangouts each week. The timestamps help people find the updates they need without watching the hour-long updates.

Estimated Budget of Task: $100/week 
Patrick M gave me the task and we decided together each week's timestamps were worth $100.
$400 for June.

Estimated Timeline Required to Complete the Task: **The Thursday after the Debrief, by 11:00 AM PST**
How will you measure completion? **Timestamps are published to the Weekly Debrief Index on time**

-- 
Legal 
Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

**Comment by kitblake** [comment]
@TrenchFloat I added 'Ongoing' to the title. This is something the Marketing guides are doing to earmark issues that recur or continue. If you prefer to make one every month, then go ahead and delete it. 
Caveat is

**Comment by TrenchFloat** [comment]
@dckc Will do from now on.

**Comment by dckc** [comment]
@TrenchFloat Would you please look into putting the index info in youtube as well?
for example: https://www.youtube.com/watch?v=kOr7dLpXoS4&feature=youtu.be

Another option would be a pointer from each video back to the index in the wiki.

Or both, even.

**Comment by AyAyRon-P** [comment]
Hi @TrenchFloat 

Is this still ongoing? Are there any updates? Do we need to vote on this for the month of August?

**Comment by TrenchFloat** [comment]
(oops. Just got to this after the pay period ended)

This issue still deserves a budget and got one for August. There were 4 debriefs in August, for $400.

**Comment by TrenchFloat** [comment]
Over discord DM, @PatrickM727 says moving forward, the coop will stop funding the Weekly Debrief Index in favor of @Viraculous's debrief summaries on the RChain blog. As for 201809, Patrick agrees to fund the 9/5 and 9/12 timestamps as the last two items, making this month's budget $200.

After this pay period (201809) we can close this issue.
