### ISSUE TITLE
upload videos to Chinese website in June

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#813]
### Benefit to RChain

Below is the videos I uploaded to Chinese video website in June.
1. [【区块链】革命性的计算机理论实践 - RChain技术浅析[中文字幕]](https://www.bilibili.com/video/av24301182)
2. [Rchain Community Debrief 80](https://www.bilibili.com/video/av24497029)
3. [Demo - Node v0.4 API + Repurposed insight block explorer](https://www.bilibili.com/video/av24505362)
4. [The Rchain Blockchain Structure and Consensus](https://www.bilibili.com/video/av24505280)
5. [Introduction to the design of computational calculi 02](https://www.bilibili.com/video/av24737798)
6. [Meetup Presentation - Govurn and Rchain](https://www.bilibili.com/video/av24740861)
7. [Demo - Sending a block full o' Rholang](https://www.bilibili.com/video/av24742506)
8. [Demo - RChain TCP TLS transport layer _ JVM metrics](https://www.bilibili.com/video/av24746661)
9. [Introduction to the design of computational calculi 03](https://www.bilibili.com/video/av24796590)
10. [Getting Involved in the RChain Bounty by Dan Connolly](https://www.bilibili.com/video/av24801073)
11. [Hosting Your Own Secure Computer Infrastructure From Home by Jeremy Busk](https://www.bilibili.com/video/av24812006)
12. [How Reflective Ventures Invest in DApp Companies by Greg Heuss](https://www.bilibili.com/video/av24814348)
13. [Get Started with Rholang Smart Contracts by Mike Stay and Kent Shikama](https://www.bilibili.com/video/av24872157)
14. [Rchain Community Debrief 81](https://www.bilibili.com/video/av24928453)
15. [Digital Identity Solutions on RChain by Ed Eykholt](https://www.bilibili.com/video/av24932826)
16. [LADL From the Group Up by Mike Stay and Greg Meredith](https://www.bilibili.com/video/av24948945)
17. [Games and Governance by Greg Meredith](https://www.bilibili.com/video/av24952976)
18. [Panel - Legal Issues Related toToken Sales](https://www.bilibili.com/video/av24966894)
19. [Introduction to the design of computational calculi 04](https://www.bilibili.com/video/av25261901)
20. [Rchain Community Debrief 82](https://www.bilibili.com/video/av25261901)
21. [Introduction to the design of computational calculi 05](https://www.bilibili.com/video/av25620856)
22. [Rchain Community Debrief 83](https://www.bilibili.com/video/av25733306)
23. [《Rchain改变世界》 RChain 2018年官方宣传片](https://www.bilibili.com/video/av25802369)

### In order to help promote Rchain in China Wechat Official Account, I have also uploaded those videos above in the Tencent Video Website.You can find them all in http://v.qq.com/vplus/a585dd8b5010159aced49e3d6d74a98f

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*
*Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ) to align your contribution with goals of the RChain cooperative.*
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[23*20=460]**[how does the budget come from](https://github.com/rchain/bounties/issues/745#issuecomment-395065061)
_Estimated Timeline Required to Complete the Task:_ **[Finished]**
_How will we measure completion?_ **[Videos uploaded]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by AyAyRon-P** [comment]
@zsluedem 

Is bilibili.com similar to YOUTUBE? What are you video views expectations?

**Comment by zsluedem** [comment]
> Is bilibili.com similar to YOUTUBE?
Yes. But there are a lot of video website in china which are all similar to YOUTUBE.

right now . There are about 100 views per video in bilibili.com and tencent video. Some special videos(like "what about Rchain all about") would raise to about 1000views.
