### ISSUE TITLE
Post three technical articles in china media channel

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#814]
### Benefit to RChain
@wangjia184 has wrote 2 technical articles about Rchain and post them in some china media website.

1. [the estimator function of Casper](https://zhuanlan.zhihu.com/p/38418242)
2. [the block structure and DAG](https://zhuanlan.zhihu.com/p/38062592)
3. [Rchain namespace](https://zhuanlan.zhihu.com/p/36345734)

I know you guys don't know Chinese.

Most of the content is something discussed in dev forum and asked by @wangjia184 (`jerry` in dev forum)
* https://forum.rchain.coop/developer/casper-cbc/multiple-parents-block/
* https://forum.rchain.coop/developer/casper-cbc/block-in-ghost/

I think they are all really good articles and should be rewarded for that.And I have discussed a lot of technical question about Rchain with @wangjia184 . He has more than 20 years development experience and a really good developers.

@dckc I am not sure if I am right to put this issue `development` label. Could you give some opinions about the budget here?

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[900]**(may adjust)
_Estimated Timeline Required to Complete the Task:_ **[finished]**
_How will we measure completion?_ **[finished]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
I agree that those posts from developer.rchain.com are worth promoting via articles such as this.

p.s. I'm tweaking the labels. I prefer to limit the scope of the **Development** task to software development. This is developer marketing, but my understanding is that the whole $7M marketing plan is largely a developer marketing effort.

I'm prepared to support this budget after a marketing guide does. @kitblake do you know much about the audience in China?

**Comment by zsluedem** [comment]
@kitblake @pmoorman Is there some metrics of bounties for  original development article? I think original development article should be rewarded higher than translation and we should encourage this.

**Comment by zsluedem** [comment]
I add one more article which I missed.

**Comment by zsluedem** [comment]
@kitblake @pmoorman Do you want to vote for this issue? Or do you understand enough about these three articles? I need your comments and opinions about this.

**Comment by pmoorman** [comment]
This is now voted for, and fully provisioned. Good work here. Excellent example of good marketing work being produced under the bounty program!

**Comment by deannald** [comment]
@zsluedem - Can you tell us a little more about the website, zhuanlan.zhihu.com? It appears to be similar to medium.com? What kind of traffic/readership is there? Would it be beneficial to cross-post these articles to other Chinese websites?

I read through the translated posts and they look like they are of good value to RChain interested developers/investors. I agree, this is not just translation to Chinese, but original articles (as far as I can tell).

**Comment by allancto** [comment]
@zsluedem please consider also cross posting all these articles and references or important comments in [RChain Worldwide Community Forum](https://rchaincommunity.xyz/). Thanks! -@allancto

**Comment by zsluedem** [comment]
@deannald Yeah. zhihu.com is more like quora. People ask questions there and many people give their thoughts and opinions. And zhuanglan.zhihu.com is like a blog(or medium.com). You can write a series topics about one thing. Zhihu.com and zhuanlan.zhihu.com share the audience. And there are a lot of developers and experts from various fields（including investors）in zhihu.com.

>Would it be beneficial to cross-post these articles to other Chinese websites?
Yes. Most of the articles have already been published in the Wechat official account and the fansite.

>I agree, this is not just translation to Chinese, but original articles
Yes. They are all really valuable  original articles and not just plain translation. There are many details and examples about the Rchain casper and namespace which you can not find in most of the articles in  Jira and any other mediums.
