### ISSUE TITLE
Create a theme for the RChain Blog

### ISSUE THREAD

**Issue by kitblake** [rchain/bounties#815]
### Budget and Objective

RChain is moving its blog activity to a Wordpress instance that'll be hosted under an RChain domain. Marketing would like to have it online asap, during the month of June or soon thereafter. They need a theme that has an RChain look & feel. As new branding is in the pipeline the design should simply follow existing house style, as used in rchain.coop and member.rchain.coop, and not get too creative.

This issue is a request from Marketing and they would like @Andrekuipers to do the work. Their blog authors will collaborate on the design development. A couple of iterations will be needed depending on review responses. 

For efficiency, and also possible future consolidation, it would be good to use the same WP setup as the Member Site. Responsive layout for mobile is required. Once the site goes live speed optimization will be needed. 

_Estimated Budget of Task:_ **$1400** (depends on iterations)
_Estimated Timeline Required to Complete the Task:_ **2 weeks**
_Measure of Completion:_ **The theme is done, approved, and ready to go live.**

--
***Legal***
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

**Comment by dckc** [comment]
I wonder how this relates to #539.

**Comment by Murphy6** [comment]
It is a great idea will love to be part of it

**Comment by kitblake** [comment]
@dckc Is there such a disease as MVP-itis? Because we – collectively – haven't forgotten about #539 but first we want to get an MVP online.

**Comment by deannald** [comment]
@kitblake Yes, I've seen many articles about it in JAMA. MVPs are great - just as long as there's a roadmap and future releases planned :)

**Comment by pmoorman** [comment]
@kitblake I take it this can be closed, right? Work has been completed, and bounty has been paid last month.
