### ISSUE TITLE
Translate remaining blog posts to Polish

### ISSUE THREAD

**Issue by pavlos1851** [rchain/bounties#818]
### Benefit to RChain

Translation of the RChain Medium blog posts to other languages means good global marketing.

### Budget and Objective

The following posts will be traslated to polish:

[Introducing RSpace](https://medium.com/rchain-cooperative/introducing-rspace-ea12897daef2)
[Resonate and lifeID collaborate](https://medium.com/rchain-cooperative/resonate-and-lifeid-collaborate-da2d22e43df6)
[RNode v0.3.1 introduces the RChain consensus protocol](https://medium.com/rchain-cooperative/rnode-v0-3-1-introduces-the-rchain-consensus-protocol-23e67666ba82)
[RChain Weekly Update (Debrief 75) — 02 May](https://medium.com/rchain-cooperative/rchain-weekly-update-b3b9fbd480f7)
[RChain Weekly Debrief | 9th, May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-9th-may-2018-687bd7c80ebd)
[RChain Weekly Update (Debrief 77) -16 May 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-77-16-may-2018-5ecfa806933f)
[RChain Weekly Update(Debrief 78) — 23, May](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-78-23-may-c919bf19a8ed)
[RNode v0.4.1 introduces sending Rholang smart contracts across the network](https://medium.com/rchain-cooperative/rnode-v0-4-1-introduces-sending-rholang-smart-contracts-across-the-network-e076d0961b3e)
[RChain Weekly Update (Debrief 80) June 6–2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-80-june-6-2018-19927f88a3c5)
[RChain Weekly Update (Debrief 81) — 13 June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-81-13-june-2018-415b4318b02b)
[RChain Weekly Update (Debrief 82) — 20 June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-82-20-june-2018-6064dba8769f)
[The Future of Blockchain Event — with Greg Meredith and Greg Heuss](https://medium.com/rchain-cooperative/the-future-of-blockchain-event-interviews-with-greg-meredith-and-greg-heuss-9efac6082225)

There will be added value to the translations in the form of summaries of the key elements of each post and comments about them.

_Estimated Budget of Task:_ **$[4000]**
_Estimated Timeline Required to Complete the Task:_ **[1 week]**
_How will we measure completion?_ **[The blog posts will be posted at the [RChain Cooperative (Polish)](https://medium.com/@rchain_pl) medium page]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because translating the blog posts provides insight and updates about the achievements of the RChain Cooperative.
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in polish.
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #517, #527, #612
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by deannald** [comment]
Dzień dobry, @pavlos1851! For future translation work, we'll be looking for value added work either based on marketing priorities, reach of post (number of views) or additional value that otherwise can't be delivered beyond Google translate on the blog posts cited. Please coordinate value added work with the Translation Guides @ICA3DaR5 @michaelizer @zero-andreou

**Comment by ICA3DaR5** [comment]
@deannald I have chatted with @pavlos1851 and he told me he will add value by adding comments, suggestions, ideas and critique. Also he will move his blog posts from Medium to https://rchaincommunity.xyz/ which will boost views IMO.

A good side-effect of this is the conversion from Medium to Markdown, which is a format that can be easily archived and easily converted to other formats (such as PDF's etc.).

**Comment by deannald** [comment]
My concern with https://rchaincommunity.xyz/ is that is is little traffic traffic to that URL with few views of the posts that are there. What is the plan to drive traffic to this particular site in order to get people to even see the blog posts? Medium at least has a huge number of readers, some of which may stumble upon the articles there, but unless we have some marketing push to drive readers to https://rchaincommunity.xyz/, I don't see much benefit in hosting content there.

**Comment by ICA3DaR5** [comment]
@deannald rchaincommunity.xyz is a Work In Progress, see https://github.com/rchain/bounties/issues/588

The purpose of it is a community driven forum, where we can share ideas, ask questions, get to know each other and more...

**Comment by pavlos1851** [comment]
Posts made public. Closing issue.
