### ISSUE TITLE
July Core Development Work

### ISSUE THREAD

**Issue by MParlikar** [rchain/bounties#819]
### Benefit to RChain

July Core development work on the Platform. ref [core bounties](https://rchain.atlassian.net/wiki/spaces/CORE/pages/105938971/Bounties+for+Development+work)

### Budget and Objective
Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.

* Estimated Budget of Task: $4,350 (29 story points @ $150 ea)
* Estimated Timeline Required to Complete the Task: 1 month- July
* How will we measure completion? Pull Requests are merged. Measure of effort is in story points. * Each story point is paid out at a rate of $150.00 in RHOC. Price of RHOC set by board and CoOp.

See CONTRIBUTING.md for details on budget and reward process.

### Legal
Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

**Comment by dckc** [comment]
@MParlikar I see no July bounty work. Is that correct?

cc @AbnerZheng

**Comment by dckc** [comment]
@MParlikar has got some rewards for @AbnerZheng after all.

**Comment by dckc** [comment]
@MParlikar , @AbnerZheng please add a budget vote and a reward vote like mine **by August 8**.

I just talked with @MParlikar . She tells me @AbnerZheng completed 29 story points in July. At $150 ea, that comes to $4,350.

In [votes for this issue][v819], I just voted accordingly.

[v819]: https://rewards.rchain.coop/index.php?-action=related_records_list&num=%3D819&-relationship=Budget&-table=issue&-ui-root=main-content&-sort=num+desc&-cursor=0&-skip=0&-limit=30&-mode=list
