### ISSUE TITLE
Meetup "Smart Contract Formal Verification", Europe/Ukraine/Kyiv, 5 July

### ISSUE THREAD

**Issue by golovach-ivan** [rchain/bounties#822]
Holding tech/math meetup in Europe/Ukraine/Kyiv, July 5.
Topic: "Smart Contract formal verification: Process Calculus and Modal Logics".

### Event Program
1. Tell about the RChain Coop.
2. Tell about bounty program.
3. Tell about "Designing Computational Calculi" course.

4. Big topic: Chemical Abstract Machine, LTS and CSS.
5. Big topic: Propositional Logic, Predicate Logic and Hennessy-Milner Logic.

6. Intro into Pi-calculi + Caires/Cardelli logic.
7. Intro into RHO-calculi + Namespace logic.

### Benefit to RChain
1. Set up local dev/math commulity (<a href="https://en.wikipedia.org/wiki/Kiev">Kyiv, 2.9M population, engineering city</a>, 40k-50k IT people).
2. Involving developers and mathematicians to RChain Coop (#775).
3. Develop a "meetup in a box" (#779) slides + practical tasks for Formal Verification meetups/techtalks.
4. Publishing video on <a href="https://www.youtube.com/user/KharkovITCourses">youtube channel for 25.000 developers</a>.

#### Involved
golovach.ivan - 75%
kovmargo - 25%

#### Expenses
Publicity, Banners, Digital graphics $250
Hall renting $350
Camera and associated gadgets renting $80
Logistics $300 (golovach.ivan + kovmargo live in another city, in Kharkiv)

_Estimated Budget of Task:_ **$[2500]**
_Estimated Timeline Required to Complete the Task:_ **[3 days]**
_How will we measure completion?_ 
    - meetup video - published on youtube channel
    - slides - published into RChain google.docs

**Comment by allancto** [comment]
@golovach-ivan thanks for posting this. Please report progress as it happens in the "Community Building Worldwide" folder. If possible it would be nice to have a June report as well. You might consolidate with @qelentium, @Barkov-F and others in the Russian language community. For reference see #803. There's a lot of cool things going on in the Russian language community- please take the time to share it so that we may all benefit. 
https://drive.google.com/drive/folders/15Uq2FRo_o_165NG-QOLHwszIj5XCZ0eq

Thanks! -allancto

**Comment by allancto** [comment]
@golovach-ivan i'd like to add one more comment. To the extent that new understanding, methods or tools come out of your work to support "Smart contract formal verification" in a significant way, please highlight that and I will vote a special budget to acknowledge the accomplishment you and your coauthors/ contributors have made. Formal verification is hugely important because it allows us to gain greater confidence that software will "do what we intend" (aka "correct by construction").

**Comment by golovach-ivan** [comment]
@allancto 
1. I feel meetups part of June report - https://docs.google.com/document/d/1uwfmGX-G0UrmCZfNAJl2Zot5irUYUOvIcQVfP65BtxY/edit
2. In my opinion i understand logic/calculi interaction (checking "p ⊨ φ" or "¬(p ⊨ φ)" on the level CCS/Hennessy-Milner-Logic) but next level π-calcili/Caires-Cardelli-Logic and next-next level RHO-calculi/namespace-Logic need more research.
3. I think we need research about connection between RHO-Calculi and RHO-Lang. Because RChain theoretical results are about RHO-Calculi. So we need to show some encoding of RHO-Lang in RHO-Calculi (Like RHO-Lang has 'int' data type but RHO-Calculi - has not).

**Comment by Ojimadu** [comment]
@golovach-ivan Did this event later hold? Any summary of how the event went?

**Comment by golovach-ivan** [comment]
Meetup was held, video will be ready in hours.
Sorry for beign late. I spent a lot of time figuring out how everything works.
June - my first month with RChain Coop. 
It is very important for me to receive bounties for June - i can work full time next monthes.

**Comment by allancto** [comment]
@golovach-ivan please complet all the paperwork necessary. @ICA3DaR5 will help you, please dm him on discord. Thanks for your contributions!

**Comment by allancto** [comment]
I have spoken with @golovach-ivan and i recommend voting the budget as proposed in the issue statement. Thanks! -@allancto

**Comment by golovach-ivan** [comment]
This is my oversight, that the task was created in July.
These meetups are the result of our work in June, is there any possibility of transferring them to June budget?

**Comment by Ojimadu** [comment]
See my comments in #823

**Comment by deannald** [comment]
@golovach-ivan For this event as well as the one cited in #821, can you please let us know a little more about them? How many attendees were at each meetup? Were the documents/slides developed for the 2 events materially different or was there reuse - hence the meetup in a box? If so, I'd like to see the events combined and/or the total costs shown (in other words, how are you getting at the budget numbers). 

Maybe the label guides for meetups can explain how we are assessing meetup costs, given that the [guidelines](https://github.com/rchain/bounties/wiki/local-meetup-program:-summary) are either out-of-date or don't fully compensate bountyists for the work done. @Ojimadu

**Comment by golovach-ivan** [comment]
Video [Smart Contract formal verification: Process Calculus and Modal Logics, on 5 July 2018](https://www.youtube.com/watch?v=TYp4bdLB11w&list=PLoij6udfBncjj9DmzsQB5PJEN6Eo6woHA&index=1) is ready and placed on [Youtube channel](https://www.youtube.com/channel/UCuIctN7x71qam9K_ZxS1W2A) in separate playlist Blockchain with second video ([4 July meetup](https://www.youtube.com/watch?v=uqyFp2kIsxw&list=PLoij6udfBncjj9DmzsQB5PJEN6Eo6woHA&index=2)).

**Comment by golovach-ivan** [comment]
@deannald 
> How many attendees were at each meetup?

15-20 people at every event. 
Of which 5-10 high-end developers or mathematicians.

>  Were the documents/slides developed for the 2 events materially different or was there reuse?

Slides was reused. Here they are (slides will be finalized in the future for next meetups. This is the first version):
- [Formalisms: Formal language, Algebra, Calculi, Logic.v1](https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/00.formalisms.v1.pdf)
- [CCS: LTS and Process Calcculi.v1](https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/10.ccs.v1.pdf)
- [Propositional Logic.v1](https://github.com/golovach-ivan/Computational-Calculi/tree/master/slides)
- [Predicate Logic.v1](https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/40.logic-predicate.v1.pdf)
- [Hennessy-Milner Logic without Recursion.v1](https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/50.logic-hml-without-rec.v1.pdf)
- [Hennessy-Milner Logic with Recursion](https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/60.logic-hml-with-rec.v1.pdf)

> hence the meetup in a box 

#779 - materials can be brought to this level (slides, brochures), but this is a very technical meetup, and the main difficulty is the preparation of a speaker.

**Comment by golovach-ivan** [comment]
The next step of research after this meet is the [Correct-by-Construction](https://github.com/rchain/bounties/issues/835) project. 
Issue #835.

**Comment by deannald** [comment]
@golovach-ivan - These are great, thanks for posting.

**Comment by zsluedem** [comment]
@golovach-ivan  I saw some "???" in some slides. Is there any problem with these slides?

I found them in https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/00.formalisms.v1.pdf, https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/10.ccs.v1.pdf.

Have anyone read these slides?It is kind of to hard for me to just read it without any explanations.

**Comment by Ojimadu** [comment]
Hello, @golovach-ivan @kovmargo It is three days before the end of voting for this period and I have not seen a response on #822. Also, I see the slides are not yet complete so I would vote $1800 for this issue pending when the slides are complete and would vote on rewards when I get a response on #822.

**Comment by golovach-ivan** [comment]
Please see [comment on issue 821](https://github.com/rchain/bounties/issues/821#issuecomment-411067969) and vote.

**Comment by Ojimadu** [comment]
After seeing the [comment](https://github.com/rchain/bounties/issues/821#issuecomment-411067969) by @golovach-ivan I think this deserves full rewards.

**Comment by dckc** [comment]
I see rewards were issued in the 201807 pay period.
