### ISSUE TITLE
RChain Africa Community Report June 2018

### ISSUE THREAD

**Issue by David405** [rchain/bounties#824]
**Benefit to RChain**
Since #591 was created in April, there have been evident progress .  Benefits of RChain investing in Africa can be seen in #716.

The report can be seen [here](https://docs.google.com/document/d/1zRWt43P7UXFs99FGJD_TQnVNeebJ2dlG2Fv06BF_E_Q/edit#)

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[200]**
_Estimated Timeline Required to Complete the Task:_ **[Completed]**
_How will we measure completion?_ [**[Monthly Report]**](https://docs.google.com/document/d/1zRWt43P7UXFs99FGJD_TQnVNeebJ2dlG2Fv06BF_E_Q/edit#)

_NB: This was inspired by @allancto comment in #796_

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Viraculous** [comment]
Awesome @David405 and @Ojimadu, Its great.

**Comment by BelovedAquila** [comment]
It has been a smart development in the RChain Africa community @ojimadu actually did an outstanding job in making this a reality and still seeing that it improves and progresses and other RChain Africa collaborators, cheers 🥂
@David405 please may I get to understand your conception of an Active Ram, if you don't mind?

**Comment by deannald** [comment]
@allancto Do we have a standard budget for community reports? My understanding is that this particular issue isn't paying for the work that was done in creating community (@David405 Well done, by the way!), but for creating this particular report. What are the guidelines for reports - is it based on length, comprehensiveness? It would be good to have some standards to set expectations on budget.

**Comment by dckc** [comment]
@kitblake any progress on your review?

You took the ball in our July 4 meeting (#823).

**Comment by kitblake** [comment]
That's a replete report. Thanks for compiling it. Here are some notes:

- The Meetup certainly did go well, especially judging from the photos that were posted on Telegram and the YouTube video. Congrats on that!
- Sorry about the work put into the local forum. 
- The University Community Engagement is an excellent initiative that could bear fruit in the short and long term. 
- The reporting about what individual people are doing is useful, for instance I've seen @nonnykul in RAM meetings but had no idea what he was doing. 

Tbh I'm not sure a monthly report is warranted, but @allancto made good arguments for it and maybe quarterly would not be frequent enough. But the budget can reflect the complexity. For instance I imagine that the report for July will be much easier, especially the people sections because they'll keep doing what they're doing. 

It's a shame the report is somewhere in a Google doc. Once the doc is final, maybe you want to use the Markdown converter at http://markitdown.medusis.com/ and post the report in the corresponding issue. That would make it much more likely that people will read it too.

**Comment by David405** [comment]
RChain Africa Community Report June 2018

  

### Meetup

The RChain community in Africa had a successful meetup on the 9th of June. Prior to the meetup, there was a lot of interactions with the university community and software companies to pitch RChain to them and invite them to the meetup.

  

The meetup included a video presentation, a lecture on Blockchain and a node testing session.

  

More on this can be seen [#796](https://github.com/rchain/bounties/issues/796)

### Forum

  
  

There was the intention of having a forum in which 

RChain and other supporting technologies can be discussed, the forum was created and engaged its first set of users but progress on it was halted since the marketing organization doesn’t support regional websites as of this time.

  

The details of the forum [#662](https://github.com/rchain/bounties/issues/662)

  
  
  
  

### University Community Engagement

One of the important work going on is the involvement of the university community, researchers, blockchain experts, professors, students and lecturers in contributing meaningful to RChain, the work started since May and is a work in progress.

  

Over the span of two months, we have had interactions with more than a 100 students and a few researchers who find the 

RChain concept interesting but still need 

further

guide in other to contribute.

  

This work is slowly migrating from a marketing task into a 

development oriented work, and more of this will be seen in July.

  

Details and the progress of this work here [#681](https://github.com/rchain/bounties/issues/681)

  

### RChain Node-testing

During the meetup, there was a session dedicated to node-testing which was a success, the video can be seen on [youtube](https://www.youtube.com/watch?v=vT3cOqfgEpk&t=1786s). As a result of the meetup [#796](https://github.com/rchain/bounties/issues/796) and engagement with the university community [#681](https://github.com/rchain/bounties/issues/681), a 

work study group has been created, which will participate in further node-testing sessions and also train other developers from the region in 

rholang development.

  

### DoCC

The work study group created have been involved in Computational Calculi collaborative learning and is currently working on a [document](https://docs.google.com/document/d/1ic7yCa37Jjx9l6UBpoFJf8o6CZzmEwtRBvfUj81lLvw/edit) to simplify Greg’s lecture. The group also attend @Jake-Gilberg’s study on Friday’s. More on this can be seen [#755](https://github.com/rchain/bounties/issues/755).

  
  

### African Community Members individual contribution to RChain June 2018

  

Telegram Group Admins - 

@ojimadu and @david405 are active as admins in [RChain Coop Official](http://t.me/rchain_coop) and [RChain Africa](http://t.me/Rchain_Africa) telegram groups respectively.

  

Noob Programming Peer Learning -

@David405 and @valentine-mario are active participants in the weekly noob sessions and are also active contributors. @David405 is leading the design of the [bounty dashboard](https://rhobot.glitch.me/) and also assist peer learners in setting up node during the node testing session while @valentine-mario is working on a chatbot that will act as 

guide. [#789](https://github.com/rchain/bounties/issues/789)

  

RChain Collaborative Learning - 

@nonnykul is an active participant of the design of computational calculi study on 

fridays, @nonnykul is also the main contributor to  [INTRODUCTION TO THE DESIGN OF COMPUTATIONAL CALCULI ](https://docs.google.com/document/d/1ic7yCa37Jjx9l6UBpoFJf8o6CZzmEwtRBvfUj81lLvw/edit) document, He has also been active in engaging the university community [#681](https://github.com/rchain/bounties/issues/681)

  

 Operations and Meeting -

@Tonyprisca13 has been helpful in organizing the RAM weekly meeting.

  
  

Bounty-One and Reddit Engagement - 

@jasoncruzzy has been doing a great job in promoting RChain on [Bounty-One](https://talk.bountyone.io/u/rchain_coop/activity) and 

[Reddit](https://www.reddit.com/user/RChain_Africa?utm_source=reddit-android) progress report on each can be seen in [#778](https://github.com/rchain/bounties/issues/778) and [#704](https://github.com/rchain/bounties/issues/704) respectively.

  

### CHALLENGES AND LIMITATIONS

Aside the success and progress that was recorded by the 

RChain African community, we also have challenges, the disturbing ones have been Electricity supply and Internet connectivity.

- A lot more times that not, the team uses 

alternative supply of power ( the most prominent being AC generator) which can be quite expensive to maintain in terms of fueling and general maintenance. 
- Low bandwidth has also been a major 

challenges especially during meetings and other network intensive activities, it sorts of limits how much contribution can be made. A solution to this can be getting a dedicated network provider 

as against using general network providers. 
  

### ACTIVE RAMs FROM AFRICA

- @David405 
- @ojimadu 
- @nonnykul 
- @valentine-mario 
- @viraculous 
- @Tonyprisca13 
- @kaka56 
- @Preshcode 
- @ResonanceXXX 
- @jasoncruzzy 
- @azazime 
- @casanwugo 
- @philipandri 
- @keaycee 
- @Pionelle 
- @kencode 
- @ibesoft11 
- @BelovedAquila

**Comment by kitblake** [comment]
@David405 That Markdown conversion worked nicely, thanks for posting the report.

I'm going to close this issue.

**Comment by David405** [comment]
@kitblake you only voted for budget, kindly vote on rewards for this issue.

@allancto @trenchfloat please complete the vote for this report
