### ISSUE TITLE
Translate medium post to chinese

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#828]
### Benefit to RChain

- [x] [rchain-weekly-update-debrief-83-27th-june-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500) 1322words

- [x] [rchain-weekly-update-debrief-84-4th-july-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0) 866words

- [x] [the-future-of-blockchain-event-with-greg-meredith-and-greg-heuss](https://rchaincommunity.xyz/t/the-future-of-blockchain-event-with-greg-meredith-and-greg-heuss/125) 1227words

- [x] [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a) 1720words

- [x] [RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5) 900words

- [x] [rchain-update-debrief-86-july-18th](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427) 3229words

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*
*Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ) to align your contribution with goals of the RChain cooperative.*
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[1845]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #761 
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by allancto** [comment]
@rjl493456442 @yuhuanmocmoc @zsluedem I have made a PR #826 to eliminate the Translation template above. Please consider writing an article in the RChain Worldwide Community Forum instead (#588, https://rchaincommunity.xyz/). Also please consider contributing to #829 (or recommending friends with outstanding web development skills) to develop automated tools so that instead of translating word for word you can focus on commenting and analyzing RChain documents so that the entire rchain worldwide community may benefit from your insights. @AbnerZheng you've also been involved closely with RChain, please consider posting your experience in the Worldwide Community Forum (and recommend to your friends with web development experience to contribute to #829). 

Thanks! -@allancto

**Comment by rjl493456442** [comment]
@allancto will use your translation template once it get merged! 
And for the forum, yes we definitely will post our idea on the forum and appreciate for the awesome forum!  
And for the automated translation, tbh the translation quality is a big problem. If we only use the automated translation for forum, i say yes, it doesn't require high translation quality and will definitely improve the communication quality.
But for the documentation translation, i say no. We can use google translation or other tool to translate, but we can never ensure the quality and the correctness. That why we need manual work.

So what about your opinion? ::)

**Comment by allancto** [comment]
@rjl493456442 also #755, DSL's are imo awesomely valuable for us, if you can get more team members or teams on that I'd be happy to support the translation or hardware or anything else you need in order to get the quality of contribution we need in order to move dApp development forward. Thanks! -@allancto

**Comment by yuhuanmocmoc** [comment]
@allancto We will find more people to join us next time,  thanks for your warning.

**Comment by AyAyRon-P** [comment]
This looks like a good issue. 

@rjl493456442 how did you determine the budget (for my own curiosity)?

**Comment by ICA3DaR5** [comment]
@Hi @rjl493456442 

From this month forward the Translation guides are going to use [this tool](https://customer.stepes.com/instant-translation-quote/#) for word counting and pricing using the **Best - Human Translation** option.

**Comment by rjl493456442** [comment]
@ICA3DaR5 The 0.2$/Word is decided by the community right? When does it changed to 0.1$/word?

**Comment by rjl493456442** [comment]
> From this month and forward translations will be valued mostly by the added value to the community

What do you mean "added value to community"? You mean most documents will translated by the tool instead of human? So i just want to know which documents are good target for human translation.

**Comment by ICA3DaR5** [comment]
@rjl493456442 No, I don't mean that. By added value I mean adding **something extra** on top of the translation work. Probably something that helps community building or the goals of the coop.

**Comment by yuhuanmocmoc** [comment]
I have translated the [RChain Weekly Update (Debrief 83) 27th June, 2018](https://drive.google.com/file/d/1yASJX8o2ohmuE2dg22B8mdCLOsi53u-S/view?usp=sharing) and posted it to [Medium](https://medium.com/rchain-cooperative-china/rchain%E6%AF%8F%E5%91%A8%E6%9B%B4%E6%96%B0-%E7%AE%80%E6%8A%A583-2018-6-27-8195027bbd0f) and [Wechat official account of China](url).

**Comment by rjl493456442** [comment]
Debrief84 translation has been uploaded [here](https://medium.com/rchain-cooperative-china/rchain%E6%AF%8F%E5%91%A8%E6%9B%B4%E6%96%B0-%E7%AE%80%E6%8A%A584-2018%E5%B9%B47%E6%9C%884%E6%97%A5-cec42b530d31)

**Comment by AyAyRon-P** [comment]
Hi @rjl493456442  Please review my findings below and update your budget accordingly. 

- [ ] [rchain-weekly-update-debrief-83-27th-june-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500) 1322words / 1179 - **143 word discrepancy** 

- [ ] [rchain-weekly-update-debrief-84-4th-july-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0) 866words / 773 - **93 word discrepancy** 

- [ ] [the-future-of-blockchain-event-with-greg-meredith-and-greg-heuss](https://rchaincommunity.xyz/t/the-future-of-blockchain-event-with-greg-meredith-and-greg-heuss/125) 1227words / 1142 - **85 word discrepancy** 

- [ ] [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a) 1720words / 1664 - **56 word discrepancy** 

- [ ] [RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5) 900words/893 - **7 word discrepancy** 

- [ ] [https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427) 3221Words / 2895 - **326 word discrepancy** 

![2](https://user-images.githubusercontent.com/35570702/43415964-9ffb373a-93fc-11e8-869d-8d9034ca2c7a.PNG)

cc @pavlos1851

**Comment by rjl493456442** [comment]
@AyAyRon-P I use typora MD editor to count the word. Which tool do you use for counting?

**Comment by yuhuanmocmoc** [comment]
“the-future-of-blockchain-event-with-greg-meredith-and-greg-heuss” translation has been uploaded here [here](https://medium.com/rchain-cooperative-china/%E5%8C%BA%E5%9D%97%E9%93%BE%E7%9A%84%E6%9C%AA%E6%9D%A5-%E6%B4%BB%E5%8A%A8-greg-meredith-and-greg-heuss-7633dd0d140f)

**Comment by AyAyRon-P** [comment]
@rjl493456442 I use microsoft word. 

I have never seen anywhere a rate of .2 per word, @ICA3DaR5 I've seen you also make this comment, correct? Regardless, we are now using this tool moving forward. 

cc @pavlos1851

**Comment by ICA3DaR5** [comment]
@AyAyRon-P Correct.

**Comment by yuhuanmocmoc** [comment]
“ rchain-update-debrief-86-july-18th” translation has been uploaded to[medium]https://medium.com/rchain-cooperative-china/rchain%E7%A4%BE%E5%8C%BA%E7%AE%80%E6%8A%A586-2018%E5%B9%B47%E6%9C%8818%E6%97%A5-39ae1dbad5f4) and Wechat official account of China.

**Comment by rjl493456442** [comment]
@AyAyRon-P Summary:

- [x] [rchain-weekly-update-debrief-83-27th-june-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500) [**Translation Link**](https://medium.com/rchain-cooperative-china/rchain%E6%AF%8F%E5%91%A8%E6%9B%B4%E6%96%B0-%E7%AE%80%E6%8A%A583-2018-6-27-8195027bbd0f)

- [x] [rchain-weekly-update-debrief-84-4th-july-2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0) [**Translation Link**](https://medium.com/rchain-cooperative-china/rchain%E6%AF%8F%E5%91%A8%E6%9B%B4%E6%96%B0-%E7%AE%80%E6%8A%A584-2018%E5%B9%B47%E6%9C%884%E6%97%A5-cec42b530d31)

- [x] [the-future-of-blockchain-event-with-greg-meredith-and-greg-heuss](https://rchaincommunity.xyz/t/the-future-of-blockchain-event-with-greg-meredith-and-greg-heuss/125) [**Translation Link**](https://medium.com/rchain-cooperative-china/%E5%8C%BA%E5%9D%97%E9%93%BE%E7%9A%84%E6%9C%AA%E6%9D%A5-%E6%B4%BB%E5%8A%A8-greg-meredith-and-greg-heuss-7633dd0d140f)

- [x] [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a) [**Translation**](https://medium.com/rchain-cooperative-china/rchain-weekly-update-debrief-85-11th-july-2018-fdd04f0cb981)

- [x] [RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5) 
[**Translation**](https://medium.com/rchain-cooperative-china/rnode-v0-5-1-%E4%B8%BAdapp%E5%BC%80%E5%8F%91%E8%80%85%E6%8F%90%E4%BE%9B%E4%BA%86%E7%BC%96%E5%86%99%E5%92%8C%E5%8F%91%E9%80%81%E6%99%BA%E8%83%BD%E5%90%88%E7%BA%A6%E4%BA%A4%E6%98%93%E7%9A%84%E6%89%80%E6%9C%89%E7%89%B9%E6%80%A7-756c77f0669)
- [x] [rchain-update-debrief-86-july-18th](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427) [**Translation**](https://medium.com/rchain-cooperative-china/rchain%E7%A4%BE%E5%8C%BA%E7%AE%80%E6%8A%A586-2018%E5%B9%B47%E6%9C%8818%E6%97%A5-39ae1dbad5f4)

**Comment by dckc** [comment]
rewarded in 201807
