### ISSUE TITLE
Forum Improvement Proposal: Add Automated Translation

### ISSUE THREAD

**Issue by allancto** [rchain/bounties#829]
### Proposal and Benefit to RChain

The RChain Worldwide Forum https://rchaincommunity.xyz/ (#588 by @ICA3DaR5) supports discussion groups in many languages, and we wish to improve communication between our various language groups. Manual translation documents has in the past been a primary way of reaching out to speakers of other languages. Manual translation more suitable for many purposes than automatic translation with existing tools, but in our context automatic translation may be more desirable:  

- Automatic translation goes in both directions. People from different language groups can share ideas, comments, and views of the same document. 
- Automatic translation is fast, translation is available almost immediately. 
- Automatic translation is cost effective: we can expect to translate every document and every response almost instantly and at very low cost.
- Automated translation can improve our mutual understanding. We will all be able to learn a little of each other’s words and typography, views and values, perspectives and wisdom. 

From a software design perspective there will be several issues to consider. 

1. UX and layout. How can we minimize the number of clicks, can readers set default preferences yet easily override the defaults when they want to? 
2. Performance. Should documents be translated automatically and stored for rapid viewing? 
3. The goal is to utilize existing services such as google translate and google captioning to do the actual translation. There should be no need at this time us to develop translation software, only to apply the existing services. Perfect translation is not the goal, ability to communicate with each other by incorporating existing tools is the goal. 

Potential added features: 
1. Indexing. How can we make it easy to point “into” a translated document? (by paragraph, special word, manually generated pointer?)
2. Video. Can automated video transcription be handled within this project? A big benefit would be to use words to “index” into RChain videos, which would enable or at least facilitate queries like “show me the video clip starting at the time where Mike asks about validators”. A related possibility would be to automatically or semi-automatically include speaker identification within videos. (@coininterview)
3. Search. Related to indexing, it would be awesome to have google-class search tools (indeed potentially based on google api’s) to look for relevant RChain documents within all of our repositories. (@eknir)

I’m attaching the Help Wanted label here, we do not have a team yet. We are seeking contributors in full stack web development, backend development and UX to accomplish these goals. 

### Objectives, Timeline and Budget
_How will we measure completion?_ **[coded, merged and tested in the Forum]**
_Estimated Timeline Required to Complete the Task:_ **[target 4-8 weeks]**
_Estimated Budget of Task:_ **[$8000-$13000 depending on features]**
_Suggested Budget Valuation Model: [TBD]_ 
_Retrospective remarks: [fill in AFTER completion of task and BEFORE final voting]_

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by zsluedem** [comment]
@allancto Automated translation?Do you mean something like google translations?

**Comment by allancto** [comment]
@zsluedem yes exactly, i explicitly mean google translate or equivalent. The translation and transcription "engines" already exist, not perfect but quite usable, we just need to apply them to make cross language communication easier.

**Comment by Viraculous** [comment]
@allancto said > Perfect translation is not the goal, ability to communicate with each other by incorporating existing tools is the goal.

**Comment by allancto** [comment]
@Viraculous that link was broken and now fixed, thank you! -@allancto
https://rchaincommunity.xyz/

**Comment by allancto** [comment]
@all here is a link provided by @ICA3DaR5 which gives some samples around working within the Discourse framework: https://github.com/search?q=topic%3Adiscourse-plugin+org%3Adiscourse&type=Repositories

**Comment by David405** [comment]
@allancto I am concerned about the quality of automated translations......I think one of the major calls for concern of translated works over time has been the use of services such as google translate.

**Comment by deannald** [comment]
Perhaps I'm missing the point of this issue, but doesn't your browser already take care of this automated translation? I can reference any one of the pages produced and Google automatically translates the page (based on my preferences). Why are we reinventing the wheel here? What additional functionality are you proposing? If I wander into https://rchaincommunity.xyz/c/Italian-Italiano and click on any one of the articles posted there, I get automatic translation to English (or I right click "Translate to English"). Scaling this out to have storage (in how many languages?) and indexing/search just doesn't appear worth the benefit - better to add tags to articles.

This issue seems superfluous - I'd rather see development work happening on things where we get a lot more use of out it.

**Comment by dckc** [comment]
I see this has a **Web Development** label and no other issue does. Labels are for grouping issues. Until there's a pattern, a new label isn't worth the cost.

**Comment by ICA3DaR5** [comment]
@deannald 

> Perhaps I'm missing the point of this issue, but doesn't your browser already take care of this automated translation? I can reference any one of the pages produced and Google automatically translates the page (based on my preferences). Why are we reinventing the wheel here? What additional functionality are you proposing?

For issue #588 I am going to use https://github.com/discourse/discourse-translator for convenience  and user-friendliness, the budget for this won't be **$8000-$13000**, that would be crazy. @allancto probably has other things in mind on top of this which we need to discuss.

At the moment the Discourse Translator plugin uses [Microsoft Translator](https://www.microsoft.com/en-us/translator/default.aspx) with plans to include Google Translate soon.

**Comment by AyAyRon-P** [comment]
Are there any updates to this automated translation @allancto @ICA3DaR5 ?

**Comment by ICA3DaR5** [comment]
@AyAyRon-P As of now I am trying to resolve an issue with the [Microsoft Translator Text API](https://www.microsoft.com/en-us/translator), once resolved I'll post about it on issue #588

**Comment by allancto** [comment]
added WontFix because no devs stepped up and also wait to see outcome of @ICA3DaR5 investigation into existing plugin. 

I will still support this issue if and when a great web developer steps in wanting to work on it. -@allancto

**Comment by AyAyRon-P** [comment]
Hi @allancto @ICA3DaR5 

Are there any updates to this automated translation or can we close this?
