### ISSUE TITLE
Animated Rchain Facebook Banner Video - Mainnet Release 

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#832]
Create a 3d animated Facebook Video Banner for the Rchain Facebook page - Call to action / Announcement promo

- Communicate the requirement from marketing 
- Create the Animation
- Present the concept and get approval from marketing 
- Pull across into the editing main production suite
- incorporate particular details/date/info
- add sound design, color grading and post production for final export and delivery

Estimated Budget of Task: $[500]
Estimated Timeline Required to Complete the Task: [1 week]
How will we measure completion? [final product delivered] uploaded to the Facebook Paltform

**Comment by pmoorman** [comment]
Any updates here, @Cryptovideos ?

**Comment by pmoorman** [comment]
I think this is done, right? I'll close it under that assumption

**Comment by Cryptovideos** [comment]
Hi yes- apologies pls close



________________________________
