### ISSUE TITLE
Promote RChain to Chinese Investment Community

### ISSUE THREAD

**Issue by cchx0000** [rchain/bounties#839]
### Benefit to RChain

I have been publishing a popular series of investment research reports on various blockchain tech areas through Wechat channels, in collaboration with Node Capital, a top blockchain VC fund in China (http://www.nodecap.com/). These reports have been well circulated among the blockchain investment community in China. Previous topics included DAG, sharding, privacy computing, blockchain governance, and state channels. I would like to dedicate a special issue to RChain. The report will quickly reach all of the top blockchain VC funds in China and be carefully purveyed by investment managers. 

This will significantly increase awareness of the RChain ecosystem among the Chinese investment community. It will also increase future opportunities for collaboration with blockchain media, exchanges, wallets and hackathons, since the VC funds invested heavily in them and have strong connections. 

### Budget and Objective

_Estimated Budget of Task:_ **$[1000]**
_Estimated Timeline Required to Complete the Task:_ **3 weeks**
_How will we measure completion?_ **Published report on wechat**

*See CONTRIBUTING.md for details on budget and reward process.*

**Comment by zsluedem** [comment]
@cchx0000 I am so glad to start contributing to Rchain already. But you have to be a collaborator first.

And you have to be  a member of Rchain, too. [Become a member](https://member.rchain.coop/)

**Comment by kdvalentine** [comment]
@cchx0000 truly appreciate the effort to evangelize what we all are working
to build. From the perspective of complying with US securities regulations,
promotion of RChain as an investment is a risk to the Cooperative. Members
promoting RChain as an investment poses a risk that I don't think is worth
the potential exposure.

If you are still interested in producing educational content that
highlights the features of the platform, I'm sure you will find support
from the membership towards that effort.

Regardless, please join as a member.

**Comment by cchx0000** [comment]
Hi thank you for the feedback. These reports focuses on providing general and technical knowledge about different projects and technology and do not include any investment advice or recommendations, as it is considered illegal to advertise crypto offerings in China.  

I already joined as a member. Looking forward to contributing.

**Comment by zsluedem** [comment]
Closing it now because of the policy of Rchain . @cchx0000 hope you don't feel frustrated . Keep on

**Comment by zsluedem** [comment]
@pmoorman Roger that~!
