### ISSUE TITLE
Translate 9 blog posts to Italian

### ISSUE THREAD

**Issue by akhs13** [rchain/bounties#841]
### Benefit to RChain

Translation of the RChain Medium blog posts to other languages means good global marketing.

### Budget and Objective

_Estimated Budget of Task:_ **$[1740]**
_Estimated Timeline Required to Complete the Task:_ **[12 days]**
_How will we measure completion?_ **RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform" - "RChain Weekly Update (Debrief 85) 11th July, 2018" - "RChain Weekly Update (Debrief 84) 4th July, 2018"- "RChain update (Debrief 86), July 18th, 2018" - "Introduction to rho calculus" - "Building a New Blockchain Without Reinventing the Wheel: Part 1" - "RChain Cooperative Presents RCon3" - "Running RNode(v 0.5.1) with Docker" - "RChain update (Debrief 87), July 25th, 2018" blog posts translations to the [RChain Cooperative (Italian)](https://medium.com/@rchain_it)**

_Conversion of medium blog posts to markdown format and post to https://rchaincommunity.xyz/

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

   - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: CELI 5 from institution of Perugia
       - [x] a track record of quality work on rchain bounties: #790  #645 #722 #717 #691 #687 #684 #683 #670 #590 #587 #580 # #577 #576 #574 #537 #502 #489 #488 #480 #369 #368 #367
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

### Original (English) Content
- [RChain Weekly Update (Debrief 84) 4th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0?source=---------2) (786 words)
- [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a?source=---------1) (1666 words)
- [RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5?source=---------0) (892 words)
- [RChain update (Debrief 86), July 18th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427) (2913 words)
- [Introduction to rho calculus](https://blog.rchain.coop/intro-to-rho-calc/) (1124 words)
- [Building a New Blockchain Without Reinventing the Wheel: Part 1](https://blog.rchain.coop/building-a-new-blockchain-without-reinventing-the-wheel-part-1/) (832 words)
- [RChain Cooperative Presents RCon3](https://blog.rchain.coop/rchain-cooperative-rcon3/) (362 words)
- [Running RNode(v 0.5.1) with Docker](https://blog.rchain.coop/running-rnodev-0-5-1-with-docker/) (529 words)
- [RChain update (Debrief 87), July 25th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-87-july-25th-2018-f5d7e8f3a53a) (1609 words)
### Translated (Italian) Content
- [Aggiornamento Settimanale di Rchain (Debrief 84) 4 Luglio, 2018](https://rchaincommunity.xyz/t/aggiornamento-settimanale-di-rchain-debrief-84-4-luglio-2018/210)
- [Aggiornamento Settimanale di Rchain (Debrief 85) 11 Luglio, 2018](https://rchaincommunity.xyz/t/aggiornamento-settimanale-di-rchain-debrief-85-11-luglio-2018/212)
- [Rilasciata la versione RNode v0.5.1](https://rchaincommunity.xyz/t/rilasciata-la-versione-rnode-v0-5-1/213)
- [Introduzione al Calcolo Rho](https://rchaincommunity.xyz/t/introduzione-al-calcolo-rho/216)
- [Costruire una nuova Blockchain senza reinventare la ruota: Parte 1](https://rchaincommunity.xyz/t/costruire-una-nuova-blockchain-senza-reinventare-la-ruota-parte-1/217)
- [Aggiornamento di RChain (Debrief 86), Luglio 18, 2018](https://rchaincommunity.xyz/t/aggiornamento-di-rchain-debrief-86-luglio-18-2018/218)
- [RChain Cooperativa presenta RCon3](https://rchaincommunity.xyz/t/rchain-cooperativa-presenta-rcon3/219)
- [Esecuzione di RNode (v 0.5.1) con Docker](https://rchaincommunity.xyz/t/esecuzione-di-rnode-v-0-5-1-con-docker/248)
- [Aggiornamento di RChain (Debrief 87), 25 Luglio 2018](https://rchaincommunity.xyz/t/aggiornamento-di-rchain-debrief-87-25-luglio-2018/249)
- [Aggiornamento Settimanale di Rchain (Debrief 84) 4 Luglio, 2018](https://medium.com/@rchain_it/aggiornamento-settimanale-di-rchain-debrief-84-4-luglio-2018-5d2f72108bca)
- [Aggiornamento Settimanale di Rchain (Debrief 85) 11 Luglio, 2018](https://medium.com/@rchain_it/aggiornamento-settimanale-di-rchain-debrief-85-11-luglio-2018-48bace5a675c)
- [Rilasciata la versione RNode v0.5.1](https://medium.com/@rchain_it/rnode-v0-5-1-ce073b5f4e7)
- [Introduzione al Calcolo Rho](https://medium.com/@rchain_it/introduzione-al-calcolo-rho-a5fdc97e78de)
- [Costruire una nuova Blockchain senza reinventare la ruota: Parte 1](https://medium.com/@rchain_it/costruire-una-nuova-blockchain-senza-reinventare-la-ruota-parte-1-c99822206402)
- [Aggiornamento di RChain (Debrief 86), Luglio 18, 2018](https://medium.com/@rchain_it/aggiornamento-di-rchain-debrief-86-luglio-18-2018-cbfd1a6a290c)
- [RChain Cooperativa presenta RCon3](https://medium.com/@rchain_it/rchain-cooperativa-presenta-rcon3-b209c68a1ca7)
- [Esecuzione di RNode (v 0.5.1) con Docker](https://medium.com/@rchain_it/esecuzione-di-rnode-v-0-5-1-con-docker-15ac3dbb06b2)
- [Aggiornamento di RChain (Debrief 87), 25 Luglio 2018](https://medium.com/@rchain_it/aggiornamento-di-rchain-debrief-87-25-luglio-2018-f8d24813aecb)

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by deannald** [comment]
@AyAyRon-P @michaelizer - What's the status on translations these days? Are we still accepting them or are they being incorporated into the Community Building label as not straight up translation tasks? @michaelizer - when are you officially not a Translation guide (or has that already happened)?

**Comment by michaelizer** [comment]
Hello @deannald! and yes, that has already taken place. Now @AyAyRon-P guides the label, transition between the Translation label and Community Building is still under discussion <https://github.com/rchain/bounties/issues/483#issuecomment-407191341>

**Comment by akhs13** [comment]
Hello @AyAyRon-P  .
Regarding the added value,we are going to convert these articles to markdown format and post them on Medium and on rchaincommunity.xyz
We are currently searching for blogs and forums that will give publicity and resonance to these articles. If we find something remarkable, we will let you know.
I provided the word count. You can check above.

**Comment by Tonyprisca13** [comment]
can you post  the link to this translation on medium and rchain community xyz here

**Comment by akhs13** [comment]
The links to both sites are posted above, in the issue description. @Tonyprisca13

**Comment by akhs13** [comment]
We have already posted the blog posts on several social media sites such as Facebook,Twitter and Reddit so that they will acquire the publicity that we seek.We will continue to search for tech-forums that will attract as many viewers as possible.You can check the links below:
- https://www.reddit.com/r/oknotizie/comments/943dbr/qui_puoi_trovare_tutte_le_notizie_importanti_su/
- https://www.facebook.com/rchaincoop.it/
- https://twitter.com/rchain_coop_it/status/1025126877273509889

@AyAyRon-P
