### ISSUE TITLE
Translate a total of 9 blog posts to Greek

### ISSUE THREAD

**Issue by ICA3DaR5** [rchain/bounties#842]
### Benefit to RChain

Reach a larger audience and help expand the community building.

Translations will be posted both on the [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο)](https://rchaincommunity.xyz/c/Greek-%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC/Blog-%CE%99%CF%83%CF%84%CE%BF%CE%BB%CF%8C%CE%B3%CE%B9%CE%BF), the [RChain Cooperative (Greek)](https://medium.com/@rchain_el/latest) Medium account, Facebook and Reddit.

### Budget and Objective

_Estimated Budget of Task:_ **9224 words = $1408.29 + ($1408.29 * 10% -> $140.83 for the Markdown conversion) = $[1549.12]**
_Estimated Timeline Required to Complete the Task:_ **[13 days]**
_How will we measure completion?_ **[Fill the _Translated (Greek) Content_ section below.]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@ICA3DaR5), Proficiency (@zero-andreou), Lower (@zero-andreou) from institution: [University of Michigan](https://www.umich.edu/) (@ICA3DaR5), [Edexcel](https://qualifications.pearson.com/en/home.html) (@zero-andreou), [Cambridge University](https://www.cam.ac.uk/) (@zero-andreou)
       - [x] a track record of quality work on rchain bounties: https://github.com/rchain/bounties/issues?q=is%3Aissue+author%3AICA3DaR5+is%3Aclosed
       - [x] another body of work readily available for community review: [decred/dcrdocs](https://github.com/decred/dcrdocs/tree/master/src/i18n/el)
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

### Original (English) Content

- [RChain Weekly Update (Debrief 84) 4th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0?source=---------2) (786 words, $102.18)
- [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a?source=---------1) (1666 words, $216.58)
- [RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5?source=---------0) (892 words, $115.96)
- [Introduction to rho calculus](https://blog.rchain.coop/intro-to-rho-calc/) (1124 words, $146.12)
- [Building a New Blockchain Without Reinventing the Wheel: Part 1](https://blog.rchain.coop/building-a-new-blockchain-without-reinventing-the-wheel-part-1/) (884 words, $114.92)
- [RChain update (Debrief 86), July 18th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427?source=collection_home---6------0----------------) (2913 words, $378.69)
- [RChain Cooperative Presents RCon3](https://blog.rchain.coop/rchain-cooperative-rcon3/) (430 words, $55.90)
- [Running RNode(v 0.5.1) with Docker](https://blog.rchain.coop/running-rnodev-0-5-1-with-docker/) (529 words, $68.77)
- [RChain update (Debrief 87), July 25th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-87-july-25th-2018-f5d7e8f3a53a) (1609 words, $209.17)

### Translated (Greek) Content

- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Εβδομαδιαία Ενημέρωση του RChain (Debrief 84) -- 04 Ιουλίου, 2018](https://rchaincommunity.xyz/t/rchain-debrief-84-04-2018/205)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Εβδομαδιαία Ενημέρωση του RChain (Debrief 85) -- 11 Ιουλίου, 2018](https://rchaincommunity.xyz/t/rchain-debrief-85-11-2018/206)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Κυκλοφόρησε η έκδοση RNode v0.5.1](https://rchaincommunity.xyz/t/rnode-v0-5-1/207/2)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Εισαγωγή στον Λογισμό Rho](https://rchaincommunity.xyz/t/rho/208)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Οικοδομώντας ένα Νέο Blockchain Χωρίς να Ανακαλύψουμε Ξανά τον Τροχό: Μέρος 1](https://rchaincommunity.xyz/t/blockchain-1/209)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Εβδομαδιαία Ενημέρωση του RChain (Debrief 86) -- 18 Ιουλίου, 2018](https://rchaincommunity.xyz/t/rchain-debrief-86-18-2018/214/2)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Η Κοοπερατίβα RChain Παρουσιάζει το RCon3](https://rchaincommunity.xyz/t/rchain-rcon3/215)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Εκτέλεση του RNode (v0.5.1) Χρησιμοποιώντας το Docker](https://rchaincommunity.xyz/t/rnode-v0-5-1-docker/244/2)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Εβδομαδιαία Ενημέρωση του RChain (Debrief 87) -- 25 Ιουλίου, 2018](https://rchaincommunity.xyz/t/rchain-debrief-87-25-2018/276/2)
- [Εβδομαδιαία Ενημέρωση του RChain (Debrief 84) -- 04 Ιουλίου, 2018](https://medium.com/p/f84178e39f7a?source=user_profile---------8------------------)
- [Εβδομαδιαία Ενημέρωση του RChain (Debrief 85) -- 11 Ιουλίου, 2018](https://medium.com/p/3e262bc30b18?source=user_profile---------7------------------)
- [Κυκλοφόρησε η έκδοση RNode v0.5.1](https://medium.com/p/8dfe715ba4c0?source=user_profile---------6------------------)
- [Εισαγωγή στον Λογισμό Rho](https://medium.com/p/aca6700d13b8?source=user_profile---------5------------------)
- [Οικοδομώντας ένα Νέο Blockchain Χωρίς να Ανακαλύψουμε Ξανά τον Τροχό: Μέρος 1](https://medium.com/p/c0c18ac5ec2a?source=user_profile---------4------------------)
- [Εβδομαδιαία Ενημέρωση του RChain (Debrief 86) -- 18 Ιουλίου, 2018](https://medium.com/p/63e43ed7732e?source=user_profile---------3------------------)
- [Η Κοοπερατίβα RChain Παρουσιάζει το RCon3](https://medium.com/p/b3b8dbd4daf1?source=user_profile---------2------------------)
- [Εκτέλεση του RNode (v0.5.1) Χρησιμοποιώντας το Docker](https://medium.com/p/e484d421ee3b?source=user_profile---------2------------------)
- [Εβδομαδιαία Ενημέρωση του RChain (Debrief 87) -- 25 Ιουλίου, 2018](https://medium.com/@rchain_el/%CE%B5%CE%B2%CE%B4%CE%BF%CE%BC%CE%B1%CE%B4%CE%B9%CE%B1%CE%AF%CE%B1-%CE%B5%CE%BD%CE%B7%CE%BC%CE%AD%CF%81%CF%89%CF%83%CE%B7-%CF%84%CE%BF%CF%85-rchain-debrief-87-25-%CE%B9%CE%BF%CF%85%CE%BB%CE%AF%CE%BF%CF%85-2018-85ed81fe9df7)

**Comment by AyAyRon-P** [comment]
- Will these be posted in Greek somewhere else or only the RChain Forum? What other value added content will you be posting along with these debriefs, medium posts, RChain blog posts? 

Thoughts on translation at this time are that the metrics to this completion should be the number of views/likes/etc not simply completing the translation. We need to make sure that the right audience is reading these, because if no one reads these then there is no purpose to translation. 

@ICA3DaR5 please provide the word count for each debrief

cc @pavlos1851

**Comment by ICA3DaR5** [comment]
@AyAyRon-P These will also be posted on [Medium](Η έκδοση RChain Node 0.1.3 κυκλοφόρησε).

We are in a process of thinking of other ways for more people to view these.

How can we measure views and likes? These can only be measured in retrospect. IMO posting them to the RChain forum is an added value for community building. These articles are going to **also be read in the future**, not just now.

I will provide word counting.

**Comment by ICA3DaR5** [comment]
@AyAyRon-P 

The last item of the list is ready for posting. I am doing this in a while and I'll close the issue!

- [RChain update (Debrief 87), July 25th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-87-july-25th-2018-f5d7e8f3a53a)
