### ISSUE TITLE
Translate remaining blog posts

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#844]
### Benefit to RChain

Reach larger audience and help to build the community 
Translation will be posted at [RChain Worldwide Community Forum](https://rchaincommunity.xyz/) and at [Medium RChain_RU](https://medium.com/@rchain_ru)

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[1307.02]**
_Estimated Timeline Required to Complete the Task:_ **[10 days]**
_How will we measure completion?_ **[When filled the "Translated (Russian) Content" section below]**

*See CONTRIBUTING.md for details on budget and reward process.*
@qelentium : 90%
@kovmargo : 10%

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: diploma from  Russian Embassy School in Athens (Native speaker)
       - [x] a track record of quality work on rchain bounties: #714  #751 #810   ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

### Original (English) Content
- [RChain Weekly update (Debrief 77) - 16 may 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-77-16-may-2018-5ecfa806933f)
- [RChain Weekly Update (Debrief 80) June 6–2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-80-june-6-2018-19927f88a3c5)
- [RChain Weekly Update (Debrief 82) — 20 June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-82-20-june-2018-6064dba8769f)
- [RChain Weekly Update (Debrief 83) 27th June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500)
- [RChain Weekly Update (Debrief 84) 4th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0)
- [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a)
- [RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5)
### Translated (Russian) Content
- [Еженедельное обновление RChain (Дебриф 77) -16 мая 2018 года](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%BF%D0%BE%D0%B4%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2-77-16-%D0%BC%D0%B0%D1%8F-2018-%D0%B3%D0%BE%D0%B4%D0%B0-ba8a29bf218)
- [Еженедельное обновление RChain (Дебриф 80) 6 июня-2018 года](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%BF%D0%BE%D0%B4%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2-80-6-%D0%B8%D1%8E%D0%BD%D1%8F-414cd6830e2d)
- [Еженедельное обновление RChain (Дебриф 82) — 20 июня 2018 года](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%8B-82-20-%D0%B8%D1%8E%D0%BD%D1%8F-2018-%D0%B3%D0%BE%D0%B4%D0%B0-c0d266556fcc)
- [Еженедельное обновление RChain (Дебриф 83) 27 июня 2018 года](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%84-83-27-%D0%B8%D1%8E%D0%BD%D1%8F-2018-%D0%B3%D0%BE%D0%B4%D0%B0-afb953d4ab99)
- [Еженедельное обновление RChain (Дебриф 84) 4 июля 2018 года](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%84-84-4-%D0%B8%D1%8E%D0%BB%D1%8F-2018-%D0%B3%D0%BE%D0%B4%D0%B0-eb200db616d1)
- [Еженедельное обновление RChain (Дебриф 85) 11 июля 2018 года](https://medium.com/@rchain_ru/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%84-85-11-%D0%B8%D1%8E%D0%BB%D1%8F-2018-%D0%B3%D0%BE%D0%B4%D0%B0-824d1dcec93a)
- [RNode v0.5.1 предлагает все функции, необходимые разработчикам dApp для написания и транзакции смарт-контрактов на платформе](https://medium.com/@rchain_ru/rnode-v0-5-1-cef0fba39da)
_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by qelentium** [comment]
Contacted with admins of [RChain Worldwide Community Forum](rchaincommunity.xyz).Its still pending to create russian section there, so all translations gonna be uploaded only at medium for a moment.After section will be created they gonna be uploaded there 2

**Comment by AyAyRon-P** [comment]
@ICA3DaR5 What is the timeline for adding Russian to the community blog? 

- Will these be posted in Russian somewhere else or only the RChain Forum? What other value added content will you be posting along with these debriefs, medium posts, RChain blog posts? 

Other thoughts:
- Is there an audience to support the need for this to be translated? 
- What is the value to RChain having these translated? 

The metrics to this completion should be the number of views/likes/etc not simply completing the translation. We need to make sure that the right audience is reading these, because if no one reads these then there is no purpose to translation. 

@qelentium please provide the word count for each debrief

cc @pavlos1851

**Comment by qelentium** [comment]
@AyAyRon-P it will be posted at Medium [RChain_ru](https://medium.com/@rchain_ru). I think its good to know when and what updates were plugged, its like history of RChain.When Russian blog will be created, i will post all debriefs and blogs there.Via [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#) it will be [RChain Weekly update (Debrief 77) - 16 may 2018] (https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-77-16-may-2018-5ecfa806933f) 1,364 Words, [RChain Weekly Update (Debrief 80) June 6–2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-80-june-6-2018-19927f88a3c5)1,589 Words, [RChain Weekly Update (Debrief 82) — 20 June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-82-20-june-2018-6064dba8769f) 2,570 Words, [RChain Weekly Update (Debrief 83) 27th June, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500) 1,187 Words, [RChain Weekly Update (Debrief 84) 4th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0)  786 Words, [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a) 1,666 Words, [RNode v0.5.1 offers all features needed for dApp developers to write and transact smart contracts on the platform](https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5)  892 Words

**Comment by qelentium** [comment]
@kovmargo is reviewer cant add her as assigner

**Comment by pavlos1851** [comment]
@qelentium The word count and budget are correct, however I can't find @kovmargo anywhere in the user database. If she is not a verified member then she can't collaborate with you and thus, you can't complete the bounty since you don't meet the minimum requirement of two assignees. Please post an update about @kovmargo's membership status so that we know how to proceed.

**Comment by kovmargo** [comment]
Hi, guys!

I can't understand what's going on. I passed verification process with
ysgjay (nick from discord) on 07/06/2018, I paid fee. You can see my
comments at the task #821 <https://github.com/rchain/bounties/issues/821>.

Maybe, I miss something else? Who can help me? Nobody is answering on
discord and I can't find the person who is responsible of the process


Thx in advance!


Best regards,
Margaryta.

**Comment by Ojimadu** [comment]
@kovmargo This is probably because you're not a collaborator on this repository. Have you requested access?

**Comment by kovmargo** [comment]
Seems yes... And I found the problem - my name on Git and  on Rewards
systems are different... Don't know bow this happens to be honest...You can
find me as 'Margaryta'

**Comment by pavlos1851** [comment]
@kovmargo Great, I can find you now in rewards.rchain.coop by searching for kovmargo as well, so that's resolved.

**Comment by qelentium** [comment]
All translated and reviewed.Posted at [Medium](https://medium.com/@rchain_ru). @qelentium 90% @kovmargo 10%.

**Comment by ICA3DaR5** [comment]
@AyAyRon-P 

I need someone to translate the following words to Russian (and/or other languages) in order to create the relevant categories:

- Forum Feedback
- Blog
- Introductions
- Questions
- Ideas
- Governance
- Meetups
- Off-Topic
