### ISSUE TITLE
Translate 11 Blog Posts to French.

### ISSUE THREAD

**Issue by casanwugo** [rchain/bounties#846]
### Benefit to RChain

Translation of the RChain Medium blog posts to other languages means good global marketing.

Translated contents will be posted both on the <a href="https://rchaincommunity.xyz/">RChain Worldwide Community Forum > French (Français) > Blog</a>, and <a href="https://medium.com/@annchidinma5">Medium Blog</a>.

  Original (English) Content :

- <a href="https://medium.com/p/5ecfa806933f?source=user_profile---------14-------------------">RChain Weekly Update (Debrief 77) - 16 May, 2018</a> (1492)

- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-80-june-6-2018-19927f88a3c5">RChain Weekly Update (Debrief 80) June 6, 2018</a> (1883)

- <a href="https://medium.com/p/415b4318b02b?source=user_profile---------11-------------------">RChain Weekly Update (Debrief 81) - 13 June, 2018</a> (1960)

- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-82-20-june-2018-6064dba8769f">RChain Weekly Update (Debrief 82) 20 June, 2018</a> (2783)

- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-83-27th-june-2018-67f309a9500">RChain Weekly Update (Debrief 83) 27th June, 2018</a> (1459)

- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0">RChain Weekly Update (Debrief 84) 4th July, 2018</a> (786)

- <a href="https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a">RChain Weekly Update (Debrief 85) 11th July, 2018</a> (1666)

-  <a href="https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427?source=collection_home---6------0----------------">RChain update (Debrief 86), July 18th, 2018</a> (2913)

- <a href="https://medium.com/rchain-cooperative/rnode-v0-5-1-82c7841940f5?source=---------0">RNode v0.5.1 offers all features needed for dApp developers to write and transact small contracts on the platform</a> (892)

- <a href="https://blog.rchain.coop/building-a-new-blockchain-without-reinventing-the-wheel-part-1/">Building a New Blockchain Without Reinventing the Wheel: Part 1</a> (884)

- <a href="https://blog.rchain.coop/intro-to-rho-calc/">Introduction to rho calculus</a> (1124)

Translated (French) Content :

- <a href="https://medium.com/@annchidinma5/mise-%C3%A0-jour-hebdomadaire-de-rchain-compte-rendu-77-16-mai-2018-d239ae6abc5e">Mise à jour hebdomadaire de RChain (compte rendu 77) -16 Mai 2018</a>

- <a href="https://medium.com/@annchidinma5/mise-%C3%A0-jour-hebdomadaire-de-rchain-le-80e-compte-rendu-de-6-%C3%A0-18-juin-e840af4b5c02">Mise à jour hebdomadaire de RChain (le 80e compte rendu) de 6 à 18 juin</a>

- <a href="https://medium.com/@annchidinma5/mise-%C3%A0-jour-hebdomadaire-de-rchain-compte-rendu-81-le-13-juin-2018-276bff3d5da">Mise à jour hebdomadaire de RChain (compte rendu 81) – le 13 Juin 2018</a>

- <a href="https://medium.com/@annchidinma5/rchain-weekly-update-d%C3%A9brief-82-20-juin-2018-f240cac3dda3">Mise à jour hebdomadaire de RChain (Débrief 82) - 20 juin 2018</a>

- <a href="https://medium.com/@annchidinma5/la-mise-%C3%A0-jour-hebdomadaire-de-rchain-le-83e-compte-rendu-83-le-27-juin-2018-4e35a032462f">La mise à jour hebdomadaire de RChain (le 83e compte rendu 83) le 27 juin, 2018</a>

- <a href="https://medium.com/@annchidinma5/mise-%C3%A0-jour-hebdomadaire-de-rchain-le-84e-compte-rendu-le-4-juillet-2018-987248edd6da">Mise à jour hebdomadaire de RChain (le 84e compte rendu) le 4 juillet 2018</a>

- <a href="https://medium.com/@annchidinma5/la-mise-%C3%A0-jour-hebdomadaire-de-rchain-le-85e-compte-rendu-le-11-juillet-2018-de513505475d">La mise à jour hebdomadaire de RChain (le 85e compte rendu) le 11 juillet, 2018</a>

- <a href="https://medium.com/@annchidinma5/mise-%C3%A0-jour-de-rchain-le-86e-compte-rendu-le-18-juillet-2018-7de1d66b0f2">Mise à jour de RChain (le 86e Compte Rendu), le 18 juillet 2018</a>

- <a href="https://medium.com/@annchidinma5/la-version-0-5-1-58e240f04dcf">La version 0.5.1 de RNode offre toutes les fonctionnalités nécessaires afin que les développeurs de dapper écrivent et traitent des contrats intelligents sur la plateforme</a>

- <a href="https://medium.com/@annchidinma5/construire-une-nouvelle-blockchain-sans-r%C3%A9inventer-la-roue-la-premi%C3%A8re-partie-caed86526ee3">Construire une nouvelle Blockchain sans réinventer la roue: La Première Partie</a>

- <a href="https://medium.com/@annchidinma5/apprendre-5f18e65e16d2">Introduction au rho calcul</a>

Collaborators : 

@casanwugo ;   70%

@philipandri002; 30%

### Budget and Objective

_Estimated Budget of Task:_ **$[ 2480 + 248 (10% for Markdown Conversion) = 2728  ]**
_Estimated Timeline Required to Complete the Task:_ **[ Completed ]**
_How will we measure completion?_ **[ "Translated (French) Contents" has been posted to Medium and RChain Community Forum ]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #711, #808, ... 
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by AyAyRon-P** [comment]
@casanwugo 

- Where are these being posted in French? 
- Is there an audience to support the need for this to be translated? 
- What is the value to RChain having these translated? 
- What other value added content will you be posting along with these debriefs, medium posts, RChain blog posts? 

The metrics to this completion should be the number of views/clicks/upvotes/likes/etc not simply completing the translation. We need to make sure that the right audience is reading these, because if no one reads these then there is no purpose to translation. 

cc @pavlos1851

**Comment by casanwugo** [comment]
@AyAyRon-P,,  The French section on the RChain forum is already being worked on by @ICA3DaR5 as i have already communicated the details to him. Thank you.

**Comment by AyAyRon-P** [comment]
@casanwugo, @ICA3DaR5 is no longer a translation guide, this is the reason I'm asking for this information. Please answer my other questions above with the exception to the one I directed to @ICA3DaR5

**Comment by David405** [comment]
@AyAyRon-P I do support the idea that translation requires an audience to be of any practical value _(which I believe @casanwugo has shown over time, I may be wrong)_. 

I also think it is necessary to have important articles such as the weekly debriefs, rnode/rholang updates in other widely spoken languages like French, Chinese etc and finally I DO NOT support the idea that metrics such as likes, views should be introduced not just to translation but even general marketing, this almost always leads to spamming which is counterproductive for RChain.

**Comment by casanwugo** [comment]
@AyAyRon-P... Translations will be posted on my <a href="https://medium.com/@annchidinma5">Medium Blog</a> which has a constantly growing following with the French audience in between. Also when the French section is created on the RChain Community Forum, i will have the contents posted there as well.

I believe that these Translations are beneficial to the RChain coop, in that, they are archived for readers to access both now and in the future, anytime, anyday. This in its own sense is value added on Translation.

**Comment by pavlos1851** [comment]
@casanwugo How did you come up with the budget? The [tool](https://www.stepes.com/) is giving a quote of $2,481.00.

**Comment by casanwugo** [comment]
@pavlos 1851... I only estimated. Didnt make use of the tool initially. But now that you've pointed it out,,, i'll have it corrected immediately. Thank you.

**Comment by pavlos1851** [comment]
@casanwugo @philipandri002 Could you please go through the "Verify Coop Membership" procedure? [Instructions](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App).

**Comment by casanwugo** [comment]
@pavlos 1851 oops... I thought i had completed all process. Will do that today.

**Comment by AyAyRon-P** [comment]
@casanwugo please provide word counts for each of the documents that you've translated as requested on  June 26th. 

Also, what is the status on your final translation? 

cc @pavlos1851

**Comment by ICA3DaR5** [comment]
@AyAyRon-P 

```
 @ICA3DaR5 Is this something we will be adding?
```

It has already been added!

**Comment by casanwugo** [comment]
@AyAyRon-P  Completed!

**Comment by pavlos1851** [comment]
@philipandri002 I see that you still haven't completed the Coop verification process. Could you please do so? 
Also, closing issue, since it's complete.

**Comment by philipandri002** [comment]
@pavlos1851 pls tell me what to do

**Comment by Ojimadu** [comment]
@philipandri002 Have you been KYC'ed by the coop?

**Comment by philipandri002** [comment]
No sir

**Comment by philipandri002** [comment]
Can u help me out@Ojimadu

**Comment by Ojimadu** [comment]
What problems are you facing? You can PM me on discord.
