### ISSUE TITLE
review of July pay period (201807) rewards by TAC + guides

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#847]
[Guides from each area](https://github.com/rchain/bounties/labels?sort=count-desc), please check the box when you're done with budgets and rewards for 201807:

 - [x] Operations: @TrenchFloat, @jimscarver
 - [x] Marketing: @pmoorman @AyAyRon-P @kitblake
   - separate budget: #817
 - [x] Translation: @AyAyRon-P, @pavlos1851
   - separate budget: #869
 - [x] Governance: @jimscarver, @barneycinnamon, @rayzor
 - [x] Development: @dckc, @Jake-Gillberg 
 - [x] member-site: @PatrickM727 @andrekuipers @kitblake @ian-bloom
 - [x] Community Building: @PatrickM727, @allancto
 - [x] RChain Technical Literacy: @JoshOrndorff @David405
 - [x] China: @zsluedem
 - [x] Education: @TrenchFloat
 - [x] Greeter: @makys @ian-bloom
 - [x] Events: @Ojimadu
 - [x] Voting: @Jake-Gillberg @jimscarver @allancto
 - [x] Branding: @pmoorman @AyAyRon-P @kitblake
 - [x] Africa: @David405 
 - [x] Social media: @azazime @jasoncruzzy

Thursday, July 26th at 2:00 PM PDT, the Task Approval Committee hosted the opportunity for Label Guides to bring up any problems and/or discuss specific issues that have gone really well in the month of July. The Zoom for this meeting is https://zoom.us/j/318506349.

meeting notes: [RChain Task Approval Committee (TAC) + Guides 27 July 2018][1]

[1]: https://docs.google.com/document/d/1wZ9dm8BDOuxpeqE69hVYrxohp_PWdVvuy17VQZSj-KY/edit#heading=h.ssm21fe0e94i

### Benefit to RChain

align bounty rewards with coop goals

### Budget and Objective

_IOU_

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ $1600? $2400? (see discussion below)
_Estimated Timeline Required to Complete the Task:_ 60hrs? (10 persons * 6hrs)
_How will we measure completion?_ a guide in each area has signaled that budgets and rewards from their area are in order for the month.

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by pmoorman** [comment]
I have created an agenda for the meeting, to make sure we can progress quickly and efficiently.

https://docs.google.com/document/d/1wZ9dm8BDOuxpeqE69hVYrxohp_PWdVvuy17VQZSj-KY/edit?usp=sharing

Everyone has comment-rights to suggest things, and @deannald has edit rights (so she can finalise the agenda effectively)

We should probably add a topic about 2 Guides for Translations stepping down, and how to fill the void (see #672).

**Comment by nonnykul** [comment]
Sorry, I made a mistake closing the issue, I was on mobile.

**Comment by dckc** [comment]
You are not alone. "About 36,300 results" for +accidentally +closed +github +issue

grumble.

**Comment by TrenchFloat** [comment]
I'm having trouble finding the quote, but I remember @pmoorman saying something like "One thing none of us saw coming is that being a guide takes a LOT more time than anticipated." I agree. While we're moving towards rewarding value, not time spent, the value of this endeavor goes up if we're all dedicating enough time to it. So I propose a $2400 budget for this month, instead of $1600, what we agreed on for June.

**Comment by dckc** [comment]
Looking at [rewards for the July pay period][r7] with less than a week before the pay period closes, I see just 10 rewards scheduled to go out to 7 persons on 8 issues -- all in Marketing or related areas (Translation, Community Building).

[r7]: https://rewards.rchain.coop/index.php?-table=reward&-limit=30&issue_num=&title=&worker=&reward_usd=&percent_avg=&budget_usd=&voter_qty=&voters=&reward_provisional=&budget_provisional=&pay_period=07%2F01%2F2018&labels=&-action=list&-cursor=0&-skip=0&-mode=list&-sort=reward_usd+desc

**Comment by David405** [comment]
I believe this is due to the fact that a lot of persons have been unable to access rewards.rchain.coop for a while now

**Comment by TrenchFloat** [comment]
@dckc Previous months have consisted of watching B&R votes regularly. July (for Education) has entailed more sustained conversations with RAMs over budgets, as we raise standards for value creation. There has been more communication among guides, the TAC meeting, and lots of issues to keep up with in general. I estimate I spent 6 hours guiding this month, and with 10 guides (right?) at $40 an hour, I got to $2400.

**Comment by AyAyRon-P** [comment]
@pavlos1851 and I have spent a collective total in excess of 40 hours this month researching, testing and implementing new processes for translations: the translation [tool](https://customer.stepes.com/instant-translation-quote/#), devising a method for quality control with online English Proficiency [testing](https://www.kaplaninternational.com/english-level-test/form), responding to DMs, and guiding the translation issues that have developed over the month and pre-existing issues as well. 

It's for these reasons that he and I have moved our work to issue #869 

Also a noteworthy mention that we've recruited @zsluedem to join us in the Translation Label Guides team. We know he will be an invaluable asset helping us with the Chinese community.

**Comment by pavlos1851** [comment]
@TrenchFloat  Also, by having a separate issue we can create a discrete, more verbose report of our actions there, and later move the key parts to the quarterly reports. My suggestion is to keep #869 alive.

**Comment by dckc** [comment]
@TrenchFloat writes:
> ... with 10 guides (right?) ...

Let's see how many guides check the "My area is finished with budgets and rewards for this month" boxes I just added to the description of this issue. I noted the separately budgeted issues for Marketing and Translation, but I would still like those boxes checked.

Everybody is also encouraged to note estimated time spent along with where the time went: were there any particularly time-consuming aspects? Any particularly stressful aspects? These might be worth discussion in a future TAC + Guides meeting.

In particular, @AyAyRon-P writes:
> spent ... hours ... responding to DMs ...

Don't do it! As @pmoorman and others have argued, with very rare exceptions, the only response to DMs should be "let's discuss this in public."

**Comment by dckc** [comment]
I only see two guides (leaving Marketing and Translation aside) claiming a reward on this issue. There's only one day left to do so.

**Comment by dckc** [comment]
I'd like to lead by example, but I'm struggling to coordinate rewards for core work (#819) again :-/ .

**Comment by dckc** [comment]
Noone is claiming a reward on any issues in the following areas, so I'm checking them off: Governance, Greeter, Voting, Social media.

**Comment by barneycinnamon** [comment]
Thank you for checking the Governance box. There was no work on Governance issues through the bounty system in the month of July. Since there were no issues to guide, there was no work for the Governance guides in the sense of this issue.

**Comment by dckc** [comment]
@zsluedem perhaps the fact that you're done with the July China report (#867) means that you're done reviewing budgets and rewards as well? From a brief scan of the report, it doesn't look that way.

Please consider adding to your report an audit of budgets and rewards for the month.

**Comment by zsluedem** [comment]
@dckc It is my first time to do the guide here .Actually I am kind of confused of what you said. 
I have to add more details about the budget and reward for the month in the report.Can you address more about what `doesn't look that way`?

**Comment by dckc** [comment]
You could do your part of #850 in your monthly reports. No, you don't have to.

In this issue, I just need you to say "I am done with budgets and rewards for China issues for 201807. They are in order."

**Comment by pavlos1851** [comment]
@dckc @zsluedem  I am in the middle of finalizing this report right now.

**Comment by zsluedem** [comment]
@dckc Yes.I am done with budgets and rewards for China issues for 201807

and @pavlos1851 told me that I don't have to work on #850 to avoid some duplicate work here.

**Comment by dckc** [comment]
I see checks in all the area boxes but two, and @AyAyRon-P acknowledged having the ball for Translation just a couple days ago in  #869 and I see in notes from a meeting today (#880) that @David405 took the ball for Tech Literacy.

Good work, everybody!

**Comment by dckc** [comment]
### Unintended change in "at least 3 votes"

@deannald @PatrickM727 @lapin7 @allancto 

On July 27, an interim fix for #799 ( d62bad1 ) changed the way "at least 3 votes" works. In May, all 3 had to have trust ratings. But now votes from any 3 coop members make for "at least 3". Only votes from users with trust ratings figure into the amounts still. I'm not sure if invoices for 201806 were computed before or after the July 27 change. As @Ojimadu pointed out, I'm having trouble reproducing the May rewards for the Q2 report because of this.

Since guides have endorsed the current rewards, I suppose the thing to do is to use the rewards as they are now (https://rewards.rchain.coop/bak/2018-08-09%2014:02:46.sql.gz https://gist.github.com/dckc/0273a67080764424fe942c29c20bf1d7) for 201807. In the future, once a pay period is closed, the code will have to use stored rewards rather than dynamically computed rewards, since the dynamic computation is different for May and July.

As to how we compute rewards going forward, let's please use #799 to discuss that.

**Comment by allancto** [comment]
@dckc this unintended change gave all participants (even with weight 0) the ability to produce a quorum though not influence the amount. Perhaps that's a reasonable amount of trust to extend. (more conservative might be to require >=3 voters && a minimum total trust rating), following in the spirit of opinions expressed by @David405  and @jimscarver .

**Comment by dckc** [comment]
Again: as to how we compute rewards going forward, **let's please use #799 to discuss that** so that we can close this one, which is about July.

**Comment by dckc** [comment]
Actually, #785 is probably a better place for the follow-up discussion.

**Comment by dckc** [comment]
Thanks again for the good work, everybody. I think we're done here.

At about 9am today, I switched the current pay period:

```
insert into pay_period values (date '2018-08-01', date '2018-08-31', 1, null);
update admin_settings set current_pay_period = date '2018-08-01';
```
"current: 201808" -- https://rewards.rchain.coop/

**Comment by allancto** [comment]
@dckc thanks for this issue, for me it was quite helpful in making sure all of the issues i was on a label for got voted. 

Going forward I'd like to suggest that this issue be expanded for next month, to reference a small doc for each label with two sections, "issue guide" explaining what was accomplished in the issue and what in the view of the guide was important about it, and a "voting guide" where the author briefly suggests how they are going to vote the issue and why. 

For me, building an internal voting guide was the most time consuming part of the voting process and i feel like it would be useful to write that down and share with others who are interested in the issue (or the evaluation that goes into the voting process overall).

The issue summary obviously coordinates with the voting guide, and it will also give us a sense of where we stand as a community, knowing what we've accomplished voting period by voting period (and make compiling quarterly reports ever so much easier). I'd also prefer to put the time in when the issues are fresh, rather than months later, when a retrospective mood will be useful but not as valuable as when the voting is happening. 

I'd also like to target the last day of the month as an appropriate time to build these documents, not the 8th of the following months. Of course, some issues may slip, some guides may change their votes up till the close of voting, but it seems reasonable to me for guides to have the responsibility to get out front and be "guiding" this process, not checking boxes furiously at the last moment. 

How do all the other label guides feel about this? -@allancto

Example:  Here are my notes on the process we used in issue #755, which involved the large number of team members and discussions in the DoCC discord server and 1-1 dm's and zooms. 
https://docs.google.com/document/d/1bJ54OVKlWsrpGRAknjt9DpuFcVsj8ZOOp3Kqf1EpqP4/edit?usp=sharing

**Comment by dckc** [comment]
> ... how they are going to vote the issue and why

All that sort of discussion belongs in the issue.

> what was accomplished in the issue and what in the view of the guide was important about it

That too - as it becomes more clear what the issue is about, the Objective and Benefit to RChain sections are often refined.

Quarterly reports seem cost-effective for accounting purposes and for summary and reflection. But the detail about each issue belongs in the issue.

> ... target the last day of the month ...

Even that is quite late. Per the [Task Approval](https://github.com/rchain/bounties/wiki/Task-Approval) process, we owe feedback (actually, a decision) with five days of when the issue is raised.

> 1-1 dm's

Once again, guides should not be expected to discuss budgets and rewards privately. If you make an exception, (a) make clear that it is an exception and that other guides should not be expected to do likewise, and (2) make sure the substance of the voting discussion is re-played in public, that is: in comments on the issue.
