### ISSUE TITLE
Rchain Asia Debrief 20180724

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#849]
### Benefit to RChain

Following by #834 , here are the agenda for the Rchain Asia Debrief.

The first meeting will hold at 04:00 UTC 20180717
Sydney +11, Beijing +8, Greece +3, Amsterdam +2, Lagos +1,
New York -4, Seattle -7

The zoom link is https://zoom.us/j/2522161381.

- [x] Prepare [agenda](https://docs.google.com/document/d/1gVFuc-Zm28xYXMDv5gquWrf0OCkU29KMSKslNdpaJQI/edit).
- [] invite people to attend to the meeting
### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[000]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

**Comment by zsluedem** [comment]
No budget on this issue. See [my comment](https://github.com/rchain/bounties/issues/834#issuecomment-410531449).

**Comment by dckc** [comment]
@zsluedem I'm using **duplicate** as a signal to the audit tools that the budget for this work is elsewhere.
