### ISSUE TITLE
RChain developers meetup Nigeria

### ISSUE THREAD

**Issue by David405** [rchain/bounties#852]
**Overview of the Meetup**

Last week Saturday, a meetup was held mainly for developers who are willing to build DApps on the RChain platform. The meetup was partly motivated by the encouraging response and follow up from developers who were present for the First meetup held in June #796. The meetup introduced the development kits ( Rholang, RNode, RHO-calculus) to the developers who were present and also the prospects and future of the RChain platform were discussed with a lot of positivity. 

**Programme of Event**

- Welcome speech

- Video Presentation: Scalability of the RChain platform

- Talk 1: A decentralized Future - Why decentralize?

- Practical Session: Writing Smart Contracts in RHolang

- Break

- Discussion: The design of RHO calculus

- RNode testing session

- Fireside Chat: How can we contribute as a group to the RChain project?

- Brainstorm Session

- Refreshment

**Benefit to RChain**

- Onboarding software developers with different language proficiencies that can contribute to the project.

- Further engagement with the University and Software community in Nigeria

- Formation of a rholang dev team

Attendance: 21 persons ( All developers with different skillsets and language proficiencies)

Estimated Budget of Task: $**[2570]**
Estimated Timeline Required to Complete the Task: **[completed]**
How will we measure completion? **[completed]**

See CONTRIBUTING.md for details on budget and reward process.

Legal
Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

**Comment by David405** [comment]
@zsluedem here are my [slides](https://docs.google.com/presentation/d/1uiKntDxXs8m3V-cbwerURBq2YJ7DJAnGfdrNMSeJTBc/edit#slide=id.p) from the meetup, you can add them to the materials we are gathering to update the current meetup wiki, @ibesoft11 kindly post your slides/notes on grammar here.

**Comment by BelovedAquila** [comment]
Interesting @David405 and @Ibesoft. 
How often are meet ups to be organized? Does it have a limit, duration or frame? Annually or something? @kitblake

**Comment by Kencode7** [comment]
Engaging Meetup!

**Comment by casanwugo** [comment]
Kudos! @David and team.

**Comment by David405** [comment]
@allancto I kindly request your input in completing the vote for this task.
