### ISSUE TITLE
Email Marketing

### ISSUE THREAD

**Issue by iamcoderisk** [rchain/bounties#853]
### Benefit of Email Marketing to RChain

*After researching for closely two months, I realize if Rchain really wishes to stretch beyond the category of people that knows about her existence, other than sensing weekly news letter to people who already subscribed to the platform, I think sending of bulk mails to different regions would be extremely awesome and something we can leverage on.*
*There are great tools out there for getting emails based on location/regions and I got them. I got upto 180K email plus and I got all of this from the tool I use. In conclusion, what I intend doing is to extract as many emails as possible, send message across stating why they should join Rchain  and sort of.*

**Comment by pmoorman** [comment]
@iamcoderisk this is an issue that has already been discussed previously, before you probably joined RChain.

You can read more about it in issue #219. I'll close this issue now, because it directly overlaps with that issue (and the decisions taken under it).
