### ISSUE TITLE
M> Wechat official account for 201807

### ISSUE THREAD

**Issue by rjl493456442** [rchain/bounties#855]
### Benefit to RChain

The same as #258

In China, WeChat Official Account is content publishing platform similar to Medium. WeChat users in China receive all relevant content push by subscribing to the Official Account.

Taking into account that in China, WeChat is by far the most active social software, with more than 900 million users. Therefore, the promotion of RChain through WeChat Official Account will play a very good effect.

In the past month, me and my teammates post 12 articles to the Wechat official account to spread Rchain's Idea.
**Most of the articles are the rchain medium post translation. Besides, we also upload RChain team latest progress** 

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[1500]**
_Estimated Timeline Required to Complete the Task:_ **[4weeks]**
_How will we measure completion?_ 

**Please follow our account by scanning the QRCode below. You can check all posts uploaded by us in the past several months;**

![image](https://user-images.githubusercontent.com/5959481/40884149-466c961a-6741-11e8-85a1-b4570098935b.png)

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #258
       - [x] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by pavlos1851** [comment]
@rjl493456442 Please use the updated [issue template](https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md). Also, could you justify the budget? From a quick glance at the wechat account all I can see are reposts of the debriefs posted on medium, the rholang tutorials, as well as a couple of videos. What do you intend to post to warrant a budget of 3600 USD?

**Comment by AyAyRon-P** [comment]
@rjl493456442 please provide links and to the articles you translated/posted and give a word count for each. Also, please provide the date translated/posted for reference. Then as @pavlos1851 stated update the objectives using the new issue template and populate the template with more precise objectives. 

I have a few other questions: 

- Are you migrating content from your already existing public channel into this "official" channel? 
- What makes this channel "official"? 
- 900 Million users is a great community, but how many of them have been attracted to RChain? 
- Has this official channel generated new members or developers? 
- What are the articles analytics in terms of views/likes?
- Is this budget you're proposing a monthly management bounty or is this a bounty for management since you last update the channel in March  #258? 

Hello @Mervyn853 @zsluedem @AbnerZheng @sportshark 
Do any of you have concerns with this? Can you validate the content and quality of what is being posted on WeChat? Is this content duplicate to what is on the public channel? Thank you for your help with this since I unfortunately cannot read the content. 


cc @pmoorman @kitblake

**Comment by v56700** [comment]
I see a serious overlap between the content and rchain.site.
Each article has a reading of less than 40.
It's worth noting that I noticed that you applied for a budget for each article posted on WeChat.
What is included in the current budget?
I want to reiterate that WeChat is a public platform with no maintenance costs.
Should your budget be reduced to $1000?

**Comment by rjl493456442** [comment]
@v56700 Hey, for some explanation here. We posted all articles which translated by me and my teammates, so we have no idea the content on the rchain.site.
And for the wechat official account maintaining, typesetting and content translation is the most important work, it still needs some people to spend hours on it.
And for the viewing time of articles, yes it is not too much, we will try to promote the official account as far as possible, but it is the truth that there are not too many developers for rchian in China.
Regarding the budget, yes we can negotiate here. Since we have 7 people in our team, we maintain the Wechat official account in turn, so the budget is not all for me. But 1000$ is too less, do you think 1500$ is reasonable?

**Comment by v56700** [comment]
If you need 7 people to typeset articles, this is really reasonable.

**Comment by v56700** [comment]
https://github.com/rchain/bounties/issues/828
The cooperative paid a translation fee of $1,848 and the reprint fee was $1,500. If your budget is reasonable, I am willing to complete this work, my budget is $500.

**Comment by rjl493456442** [comment]
@v56700 Definitely you can setup the wechat official account by yourself and apply for the budget. There are already 2 accounts in China, if you think there is a necessary to do this.

**Comment by rjl493456442** [comment]
@v56700 The most important thing for Wechat official account is promoting the RChain in China. We already have more than 700 people as the subscribers. Yes it is definitely a small group and we need to work continually, but we all know that there are a few people know **What is rchain**. And it is our goal and mission to make more people know the quintessence of RChain.

If you want to do the same thing, welcome and we have a group which aim for the promotion.

**Comment by rjl493456442** [comment]
@v56700 And for your personal information, please show me you have the ability to understand what is blockchain. All my teammates are blockchain developers and graduate from Zhejiang University, we have the confidence to do this thing professionally.
So please post more your personal information and we definitely welcome professional people join the promotion group

**Comment by v56700** [comment]
We seem to be discussing whether reimbursement and translation fees should be paid separately. So what do you do through WeChat as a developer? Any Rholang teaching? Or any article that helps others understand Rchain? These jobs are included in the budget? Please explain separately.

**Comment by AyAyRon-P** [comment]
Hi @rjl493456442 

Is this still ongoing? Are there any updates? Do we need to vote on this for the month of August? 

@zsluedem @Mervyn853 can you validate the work done here?

**Comment by rjl493456442** [comment]
@AyAyRon-P I prefer to leave this issue open and allocate budget for August based on this issue.
