### ISSUE TITLE
Translate 5 Top Post on Russian

### ISSUE THREAD

**Issue by kovmargo** [rchain/bounties#863]
Translation of the RChain hot topics to other languages means good global marketing: reach a larger audience and help expand the community building.

### Budget and Objective
**Collaborators Work:**
@kovmargo: 90%
@qelentium: 10%

**Estimated Budget of Task: $ 498**

Estimated Timeline Required to Complete the Task: **7** 
How will we measure completion? **Fill the Translated Content section below. Also, translations will be posted on the RChain Worldwide Community Forum (Russian), the RChain Cooperative Medium account(Russian), Facebook.**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 

  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language (Russian)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@kovmargo) from institution: [European University](https://e-u.in.ua/ua/) (international diploma)
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [] our plan to keep the translation up to date is:

Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)

**Original (English) Content:**
- [Running RNode(v 0.5.1) with Docker](https://blog.rchain.coop/running-rnodev-0-5-1-with-docker/) 585 Words $76.05
- [RChain Cooperative Presents RCon3](https://blog.rchain.coop/rchain-cooperative-rcon3/) 430 Words $55.90
- [Building a New Blockchain Without Reinventing the Wheel: Part 1](https://blog.rchain.coop/building-a-new-blockchain-without-reinventing-the-wheel-part-1/) 885 Words $115.05
- [Introduction to rho calculus](https://blog.rchain.coop/intro-to-rho-calc/) 1,124 Words $146.12
- [Runway Interview: The Future of Blockchain](https://blog.rchain.coop/the-future-of-blockchain-event/) $105.04

**Translated (Russian) Content.**
- [Запуск RNode (v 0.5.1) с помощью Docker](https://medium.com/@rchain_ru/%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-rnode-v-0-5-1-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-docker-f6de66207f1b)
- [RChain представляет: блокчейн ​​RCon3 конференция в Берлине](https://medium.com/@rchain_ru/rchain-%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82-%D0%B1%D0%BB%D0%BE%D0%BA%D1%87%D0%B5%D0%B9%D0%BD-rcon3-%D0%BA%D0%BE%D0%BD%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%86%D0%B8%D1%8F-%D0%B2-%D0%B1%D0%B5%D1%80%D0%BB%D0%B8%D0%BD%D0%B5-7d4bd2772896)
- [Создание нового блокчейна без изобретения колеса: Часть 1](https://medium.com/@rchain_ru/%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%B1%D0%BB%D0%BE%D0%BA%D1%87%D0%B5%D0%B9%D0%BD%D0%B0-%D0%B1%D0%B5%D0%B7-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B5%D1%82%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BA%D0%BE%D0%BB%D0%B5%D1%81%D0%B0-%D1%87%D0%B0%D1%81%D1%82%D1%8C-1-f5078cfd646e)
- [Введение в rho-исчисления](https://medium.com/@rchain_ru/%D0%B2%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-rho-%D0%B8%D1%81%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-a64c2426a817)
- [Интервью: будущее Blockchain](https://medium.com/@rchain_ru/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B2%D1%8C%D1%8E-%D0%B1%D1%83%D0%B4%D1%83%D1%89%D0%B5%D0%B5-blockchain-685aafcbe808)

**Comment by AyAyRon-P** [comment]
@kovmargo 

- There isn't currently a Russian section of the RChain forum that is being worked on by @ICA3DaR5 
- If you're posting on the RChain Medium account - I'm assuming then  you will place these in markdown text? 
- What facebook pages are you posting these on? 
- What other value added content will you be posting along with these debriefs, medium posts, RChain blog posts? 

Other thoughts:
- What is the value to RChain having these translated? Please provide 3 objectives in your proposal. 

The metrics to this completion should be the number of views/likes/etc not simply completing the translation. We need to make sure that the right audience is reading these, because if no one reads these then there is no purpose to translation. 

Please also provide the word count for each debrief and use this [tool ](https://customer.stepes.com/instant-translation-quote/#)for budget estimation. 

cc @pavlos1851

**Comment by pavlos1851** [comment]
@kovmargo So is this for russian only now? Because the budget doesn't reflect that, and all 5 of these blog posts are included in #865

**Comment by ICA3DaR5** [comment]
@AyAyRon-P @kovmargo 

I need someone to translate the following words to Russian (and/or other languages) in order to create the relevant categories:

- Forum Feedback
- Blog
- Introductions
- Questions
- Ideas
- Governance
- Meetups
- Off-Topic

**Comment by kovmargo** [comment]
@ICA3DaR5 

Forum Feedback - Обратная Связь (Форум)
Blog - Блог
Introductions - it's depend on context - 'Представление' (if you mean to tell someone about RChain, statement with a proposal for something) OR 'Введение' (Introductory, initial part)
Questions - Вопросы
Ideas - Идеи
Governance - 'Руководство' (If you are going to tell about Board of Directors) OR 'Управление' (if you want talking about process of how RChain coop works) 
Meetups - Встречи
Off-Topic - Не по теме

**Comment by pavlos1851** [comment]
@kovmargo See [#865](https://github.com/rchain/bounties/issues/865#issuecomment-409898879)

**Comment by kovmargo** [comment]
@pavlos1851 sorry for delay with answering - my child was ill(
<<So is this for russian only now? Because the budget doesn't reflect that, and all 5 of these blog posts are also included in #865.

This articles in the separate issue because translating will be doing on the different languages - #863 will be translated on Russian and #865 will be translated on Ukrainian. It's two different languages.

If trust MIS the 66% of Ukrainian people speak Ukrainian -> thats around 30 millions. 
After the events on the world stage with Russia, Ukraine is extremely concerned about the popularization of the Ukrainian language. This is felt, more young people are switching to Ukrainian. 
If we take the Russian-speaking world (post-Soviet countries), the Russian speaking population is even more. Translation into Russian and Ukrainian languages ​​will allow RChain to gain a large audience

**Comment by kovmargo** [comment]
@pavlos1851 @AyAyRon-P I've updated the budget. The reason is described at the #865

**Comment by kovmargo** [comment]
@AyAyRon-P  @panos1980 The translations will be posting on the RChain Medium account (Russian) in markdown text; I'm going to create Facebook account with the aim to popularize RChain and involve people/developers to the coop. I think, I will post some of this articles or all (now discussion about it at the #862 issue). I thinks, it will be better to add short summary to each article or explanation in short form to get better traffic (one of the value)

<<What is the value to RChain having these translated? Please provide 3 objectives in your proposal.

1. As I tell above, it will be good base for Facebook.
2. It's a way to development: translation makes articles and ideas more accessible;
number of views can be analyzed and you can trace the people's need to open new directions and new understanding.
3. Translation is a good part of Regional marketing:  because the people, who makes translation familiar with the regions and having a good knowledge of what is most effective for each region for on involving new developers. Russian-speaking people will better trust you if you are speaking Russian, this will add more insight, answers to questions. Blockchain technologies are increasingly being embraced as potential solutions for Russian/Ukrainian nations and people need to know what RСhain can do for them.

**Comment by ICA3DaR5** [comment]
@kovmargo 

> Forum Feedback - Обратная Связь (Форум)
> Blog - Блог
> Introductions - it's depend on context - 'Представление' (if you mean to tell someone about RChain, statement with a proposal for something) OR 'Введение' (Introductory, initial part)
> Questions - Вопросы
> Ideas - Идеи
> Governance - 'Руководство' (If you are going to tell about Board of Directors) OR 'Управление' (if you want talking about process of how RChain coop works)
> Meetups - Встречи
> Off-Topic - Не по теме

Can someone verify and clarify these a little bit better?

**Comment by kovmargo** [comment]
@ICA3DaR5  what words embarrass you? Maybe, it will be better if you are link us on the pages with the similar context? Then we will not guess

**Comment by ICA3DaR5** [comment]
@kovmargo I didn't say that any words embarrass me. Check:https://rchaincommunity.xyz/c/English or https://rchaincommunity.xyz/

**Comment by qelentium** [comment]
@ICA3DaR5 i verify translation of the words

**Comment by qelentium** [comment]
Work is done. Reviewed. Posted. Closing this issue

**Comment by ICA3DaR5** [comment]
I am adding them today then!

**Comment by ICA3DaR5** [comment]
@kovmargo 

> Introductions - it's depend on context - 'Представление' (if you mean to tell someone about RChain, statement with a proposal for something) OR 'Введение' (Introductory, initial part)

Introductions is about people introducing themselves. What would be the appropriate translation?

**Comment by kovmargo** [comment]
@ICA3DaR5 for Introductions will be 'Представление' and for Governance 'Управление' 

Don't know yet how voting works... Will ask you to vote for my issues: #863 (this issue) and #865

**Comment by ICA3DaR5** [comment]
@kovmargo I'll add them tomorrow. Thanks!
