### ISSUE TITLE
July report for RChain community in China

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#867]
### Benefit to RChain

Monthly report for the Rchain community in China.

**It is still under draft** I will finish it in these two days.
https://docs.google.com/document/d/1vC5MW6_iz1K88T-2DPoyF38W24GaUlTm1aEaIMMD0YM/edit#heading=h.l69nb2ivqvtw

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*
*Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ) to align your contribution with goals of the RChain cooperative.*
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[200]**
_Estimated Timeline Required to Complete the Task:_ **[2days]**
_How will we measure completion?_ **[A complete doc come out]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
Now I see "It is still under draft".

Also, @pavlos1851 writes in #847 that he's working on "this report" in a way that suggests he means this one. I'll stay tuned to see if things become clear.

**Comment by pavlos1851** [comment]
@dckc I meant that I'm finalizing the translation label report ( #850 ), not this one. Sorry for the confusion.
