### ISSUE TITLE
Start up a Rnode test QQ group in China and make Rnode test video

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#868]
### Benefit to RChain

@cool007zqw and I have start up a Rnode test QQ group in China .There are already 68 people in the group. We helped others with Rnode testing.

And @cool007zqw has made two videos on how to do the node testing thing.

1. Chinese version: https://www.bilibili.com/video/av27717965
2. English version: https://youtu.be/3w8bBBb1-nw

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*
*Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ) to align your contribution with goals of the RChain cooperative.*
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[500]**
_Estimated Timeline Required to Complete the Task:_ **[Done]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by zsluedem** [comment]
@TrenchFloat I believe there is a metrics for the video making. Am I right? I can't find it now . Are the metrics all settled down now?

**Comment by TrenchFloat** [comment]
YouTube metrics have stalled for now (#736). If that issue is something you'd like to see completed, PM me and let's work together on it.

**Comment by dckc** [comment]
Let's reserve **Development** for writing software.

**Comment by cool007zqw** [comment]
maybe we will need a node/validator label in the short future

**Comment by zsluedem** [comment]
@dckc Sorry for the bothering and I don't know there is a Rchain Technical Literacy

**Comment by dckc** [comment]
no problem.

**Comment by AyAyRon-P** [comment]
Hi @zsluedem 

Is this still ongoing? Are there any updates? Do we need to vote on this for the month of August? 

Let me know what your thoughts are on budget for the month so we can vote accordingly.

**Comment by zsluedem** [comment]
@AyAyRon-P Yes. @cool007zqw and I is maintaining the QQ group and answer questions from the node tester. @wangjia184 is also helping with the questions. And we successfully attract many developers to the Tuesday node test session. There are about 60-70 members(I am not sure about the exact numbers from China community but at least 10-20) in the node test session per week now which there was only 10-20 members before. We believed that we didi a good thing on this one. I think we should be rewarded for that.
I would suggest 800$ reward for this month. @cool007zqw 40%, @zsluedem(myself) 40%, and @wangjia184 20%.

**Comment by dckc** [comment]
I see rewards were issued in the 201808 pay period.

Good job setting this up!
