### ISSUE TITLE
ONGOING: Label Guiding for Translations - July 2018

### ISSUE THREAD

**Issue by pavlos1851** [rchain/bounties#869]
### Benefit to RChain

The report will provide transparency regarding the translation label issues and the actions performed by the guides.

This month we have also implemented the use of this [tool](https://customer.stepes.com/instant-translation-quote/#) for word counting and pricing of the translations now and moving forward. This is to ensure consistent and fair pricing and eliminate a guesstimate of translation values. 

### Budget and Objective

_Estimated Budget of Task:_ **$[1600]**
_Estimated Timeline Required to Complete the Task:_ **[1 month]**
_How will we measure completion?_ **[The task will be complete when the report of the translation label guides is finalized and posted here and in the quarterly reports.]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

| Issue #                                               | Title                                                        |  Budget  | Voted budget                                                 | Guide actions                                                | Status |
| ----------------------------------------------------- | ------------------------------------------------------------ | :------: | ------------------------------------------------------------ | ------------------------------------------------------------ | :----: |
| [#828](https://github.com/rchain/bounties/issues/828) | [Translate medium post to chinese](https://github.com/rchain/bounties/issues/828) |  1845$   | [1845$](https://rewards.rchain.coop/index.php?-limit=30&num=828&title=&updatedAt=&state=&createdAt=&labels=&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D828&-sort=num+desc&-relationship=Budget) | Commented [1](https://github.com/rchain/bounties/issues/828#issuecomment-404826806)  [2](https://github.com/rchain/bounties/issues/828#issuecomment-408964879) [3](https://github.com/rchain/bounties/issues/828#issuecomment-409285383) |  Open  |
| [#841](https://github.com/rchain/bounties/issues/841) | [Translate 9 blog posts to Italian]( https://github.com/rchain/bounties/issues/841) |  1780$   | [1780$](https://rewards.rchain.coop/index.php?-limit=30&num=841&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D841&-sort=num+desc&-relationship=Budget) | Commented [1](https://github.com/rchain/bounties/issues/841#issuecomment-408136764) | Closed |
| [#842](https://github.com/rchain/bounties/issues/842) | [Translate a total of 9 blog posts to Greek](https://github.com/rchain/bounties/issues/842) | 1549.12$ | [1550$](https://rewards.rchain.coop/index.php?-limit=30&num=842&title=&updatedAt=&state=&createdAt=&labels=&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D842&-sort=num+desc&-relationship=Budget) | Commented [1](https://github.com/rchain/bounties/issues/842#issuecomment-408135276) [2](https://github.com/rchain/bounties/issues/842#issuecomment-410453040) | Closed |
| [#844](https://github.com/rchain/bounties/issues/844) | [Translate remaining blog posts](https://github.com/rchain/bounties/issues/844) | 1307.02$ | [1300,88](https://rewards.rchain.coop/index.php?-limit=30&num=844&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D844&-sort=num+desc&-relationship=Budget) | Commented [1](https://github.com/rchain/bounties/issues/844#issuecomment-408134757) [2](https://github.com/rchain/bounties/issues/844#issuecomment-408554016) [3](https://github.com/rchain/bounties/issues/844#issuecomment-408557468) [4](https://github.com/rchain/bounties/issues/844#issuecomment-408654302) | Closed |
| [#846](https://github.com/rchain/bounties/issues/846) | [Translate 11 Blog Posts to French](https://github.com/rchain/bounties/issues/846) |  2728$   | [2706,22](https://rewards.rchain.coop/index.php?-limit=30&num=846&title=&updatedAt=&state=&createdAt=&labels=&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D846&-sort=num+desc&-relationship=Budget) | Commented [1](https://github.com/rchain/bounties/issues/846#issuecomment-408128876) [2](https://github.com/rchain/bounties/issues/846#issuecomment-408173657) [3](https://github.com/rchain/bounties/issues/846#issuecomment-408190471) [4](https://github.com/rchain/bounties/issues/846#issuecomment-408739126) [5](https://github.com/rchain/bounties/issues/846#issuecomment-408739126) [6](https://github.com/rchain/bounties/issues/846#issuecomment-410453421) [7](https://github.com/rchain/bounties/issues/846#issuecomment-411091533) | Closed |
| [#859](https://github.com/rchain/bounties/issues/859) | [Translate a total of 9 blog posts to Spanish](https://github.com/rchain/bounties/issues/859) | 1787.45$ | [1788$](https://rewards.rchain.coop/index.php?-limit=30&num=859&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D859&-sort=num+desc&-relationship=Budget) |                                                              | Closed |
| [#862](https://github.com/rchain/bounties/issues/862) | [Construction and support Facebook community on Russian, involving people](https://github.com/rchain/bounties/issues/862) |  1500$   | N/A                                                          | Commented [1](https://github.com/rchain/bounties/issues/862#issuecomment-409896456) [2](https://github.com/rchain/bounties/issues/862#issuecomment-411261822) | Closed |
| [#863](https://github.com/rchain/bounties/issues/863) | [Translate 5 Top Post on Russian](https://github.com/rchain/bounties/issues/863) |   498$   | [498$](https://rewards.rchain.coop/index.php?-limit=30&num=863&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D863&-sort=num+desc&-relationship=Budget) | Commented [1](https://github.com/rchain/bounties/issues/863#issuecomment-409262586) [2](https://github.com/rchain/bounties/issues/863#issuecomment-409297517) [3](https://github.com/rchain/bounties/issues/863#issuecomment-409900638) | Closed |
| [#865](https://github.com/rchain/bounties/issues/865) | [Translate a total 11 Top Post on Ukrainian](https://github.com/rchain/bounties/issues/865) |  1675$   | [1675$](https://rewards.rchain.coop/index.php?-limit=30&num=865&title=&updatedAt=&state=&createdAt=&labels=&-table=issue&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D865&-sort=num+desc&-relationship=Budget) | Commented [1](https://github.com/rchain/bounties/issues/865#issuecomment-409261430) [2](https://github.com/rchain/bounties/issues/865#issuecomment-409898879) | Closed |

[In PDF format](https://drive.google.com/file/d/1cMw2O2SxElBYTrIBwtgbNh4RMZBkGvL1/view?usp=sharing)

**Comment by dckc** [comment]
> How will we measure completion? [Closing of the issue]

That's circular, no? That is: we'll close the issue when the work is complete. The question is: how do you / we define complete?

I suggest: this task is complete when the Translation guides have summarized the July work in a concise report that discusses rewards paid vs. value produced as well as issues / problems / solutions.

Meanwhile... is there any particular reason to do this separately from the quarterly reports such as #850 ? I would rather see your July work go into an early draft of the Q3 bounty program report. (cc @TrenchFloat )

**Comment by TrenchFloat** [comment]
All of the guides are rewarded for their work through monthly issues like #847. In that issue and in #850, the budgets are decided by all the guides. I suggest this issue is a duplicate.

**Comment by dckc** [comment]
Separating budgets for particularly burdensome areas such as Marketing and Translation seems reasonable to me.

I would still appreciate a "Translation guides are done for this month" signal in the overall monthly review issue (#847).

**Comment by AyAyRon-P** [comment]
Hi @dckc as soon as we're finished over here I promise to check off the "done for this month" box 👍

**Comment by dckc** [comment]
This was rewarded in 201807. As discussed in #483 etc., translation work is on hold pending sponsorship.
