### ISSUE TITLE
Candy for HJ

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#871]
As almost everyone will know, HJ is in the hospital because of treatment on a brain tumor that was found earlier this month.

Even though we all work "distributed", a personal touch remains invaluable. Since I'm in Holland anyway, I am in the train right now to deliver some candy and fruit to him, as well as best wishes from all of us.

My idea is to bring a card and write this Github issue number on it, so that **everyone can write a comment below here, with his own message to HJ.** HJ has to only open the issue, and see all the wishes!

Best, (and best health to you, HJ!)

–Pieter

**Comment by David405** [comment]
@pmoorman I think this issue has been created already #860, write your comment there and add the issue number to your gift, also don't forget to send my warm regards, if you can zoom perfect!.. I am closing this issue.

**Comment by pmoorman** [comment]
oh shit, I missed that!

If you wouldn't mind, I'll re-open it (but keep the reference to that other issue), since I've just copy-pasted this issue all over the place! It probably doesn't hurt to have a double set of health wishes, anyway 👍

**Comment by David405** [comment]
I will prefer #860 is fronted since the issue was generally agreed upon from July 25 RAM meeting, @pmoorman, you don't attend the RAM meetings, do you go through the meeting notes?

**Comment by dckc** [comment]
@David405 please stop closing issues that represent work by other people. Peter has offered to personally deliver a gift and has added pointers to this issue "all over the place".

**Comment by dckc** [comment]
@pmoorman I added a note in #860.

**Comment by AyAyRon-P** [comment]
Let me know your ether address and I'll send you some RHOC :smiley: maybe you can get him so ROCK CANDY 👍

**Comment by deannald** [comment]
HJ,

I'm hoping you are having a speedy, uncomplicated and comfortable recovery. Cancer treatment can be a very daunting challenge, but I can think of few others who possess the strength and network of support to help you through.

Best wishes,
Deanna

**Comment by allancto** [comment]
Good morning HJ! We're paying attention to your wish to build awareness of who are ALL the stakeholders in the health of our planet. Kindness and fairness to our fellow humans is just the start. 

Thank you for your inspiration, HJ! 
Allan

**Comment by philipandri002** [comment]
Hi HJ! I believe in prayer and miracles, so I pray for you today that you will have a speedy supernatural recovery.. God will cause you to share this testimony to many who are fighting cancer as a message of hope and strength to them..

Love you!!

**Comment by BelovedAquila** [comment]
Hello Mr Hendrik,I actually wanted to make this look official, but I realized there isn't any need to be official and not pass my heart felt wishes, encouragement and acknowledgement to you, in the sincere and honest way it spills from my heart. Moments of your absence in the coop are of great worth and dearly missed,if it were for just our needs of your friendly, warm, calm,accommodating, understandable and diligent  nature towards the coop, we would have preferred you being as always present with us, yet priority has taught us to follow right placements, I am consoled that your presence at the hospital is paramount and not a waste of those precious moments of your influential and impact filled contributions to the coop and it's members individually. Rather, it's to the end that we might have you better and stronger with us.
 What makes men fight and win isn't in their exertion of power and strength, it's in the right exertion of knowledge through love,you possess that ability and mindset.
 The power and strength cancer as an illness seems to have, is weak as compared to your God ordained ability if exerted rightly. 
You are already conquering,keep on, soon we shall celebrate a complete victory in this fight. 

HJ I am praying for you 🙏, Also know that Jesus loves you and heals you.

**Comment by Kencode7** [comment]
HJ,
Trust you are coming out of this treatment stronger... your faith only needs to be absolute, cause you are being prayed for.
Cheers!!

**Comment by Preshcode** [comment]
Hello HJ,
I wish u a quick and full recovery, so u resume work with full energy and in your jolly good spirit. This is just a trying moment of your life but I believe it'll pass. You are one of the most experienced of us and we need you back soon for your support, advice and wise contributions. Stay strong HJ. 
Thank you for all your advice so far,
Preshcode.

**Comment by pmoorman** [comment]
Hey all,

on behalf of all of us, I went to visit @lapin7 yesterday, and checked how he's doing. 
Considering circumstances, he's doing very well!

HJ is back at home, and being very well taken care of by everyone around him. We took a selfie together, so everyone can verify that he's in good spirits: 

https://www.dropbox.com/s/0tgwr5k8sprmcgh/38462130_698596667154206_2498116922550255616_n.jpg?dl=0

**Comment by azazime** [comment]
Nice one @pmoorman,

**Comment by pmoorman** [comment]
I'll close this one off. For any more on this topic, see #860
