### ISSUE TITLE
Translate 4 last blogs to Ukrainian

### ISSUE THREAD

**Issue by thiefinshadows** [rchain/bounties#873]
### Benefit to RChain

*Translation of the RChain hot topics to other languages means good global marketing: reach a larger audience and help expand the community building.*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[414 +10%=455.6$]**
_Estimated Timeline Required to Complete the Task:_ **[29 of August]**
_How will we measure completion?_ **[Fill the _Translated (Ukrainian) Content_ section below.]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

### Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [x] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

Original (English) Content

- [https://blog.rchain.coop/rchain-spotlight-hellofriend/](https://blog.rchain.coop/rchain-spotlight-hellofriend/) 467 Words	$60.71 
- [Running RNode on Amazon AWS(EC2](https://blog.rchain.coop/running-rnode-0-5-3-on-amazon-ec2/) 601 Words	$78.13 
- [Reflective Ventures Deal Day](https://blog.rchain.coop/reflective-ventures-deal-day/) 851 Words	$110.63
- [RNode v0.6.1 supports launch of the RChain test net](https://medium.com/rchain-cooperative/rnode-v0-6-1-supports-launch-of-the-rchain-test-net-f6ddcacb4b6) 1,268 Words $164.84

Translated (Ukrainian) Content
- [День угоди з Reflective Ventures](https://medium.com/@rchain_ukraine/%D0%B4%D0%B5%D0%BD%D1%8C-%D1%83%D0%B3%D0%BE%D0%B4%D0%B8-%D0%B7-reflective-ventures-c2a6544367f0)
- [Запуск RNode на Amazon AWS (EC2)](https://medium.com/@rchain_ukraine/%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-rnode-%D0%BD%D0%B0-amazon-aws-ec2-ukr-e3a1975a3eae)
- [RChain Spotlight: Hellofriend](https://medium.com/@rchain_ukraine/rchain-spotlight-hellofriend-ukr-e84606ae5a9b)
- [Відзначені особливості та покращення в RNode v0.6.1](https://medium.com/@rchain_ukraine/%D0%B2%D1%96%D0%B4%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D1%96-%D0%BE%D1%81%D0%BE%D0%B1%D0%BB%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D1%96-%D1%82%D0%B0-%D0%BF%D0%BE%D0%BA%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%BD%D1%8F-%D0%B2-rnode-v0-6-1-cd757cce13f4)

**Comment by qelentium** [comment]
First 2 translations are already being translating in issue #865 .This issue were opened before yours.So please cancel those 2 translations

**Comment by kovmargo** [comment]
@thiefinshadows Could you please provide me with credentials for Medium RChain Ucrainian account ? I’m going to post transactions at the #865 issue. Thanks!

**Comment by kovmargo** [comment]
@thiefinshadows Please, remove 'Computational Calculi Primer Part 2: π-calculus ' article. It's being translating in issue #892 and were added before yours. Thanks!

сс @AyAyRon-P @irynapopova61
