### ISSUE TITLE
Translate 6 last blogs to Russian 

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#874]
### Benefit to RChain

Translation of the RChain hot topics to other languages means good global marketing: reach a larger audience and help expand the community building.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[1002+10%(markdown)=1102$]** 
_Estimated Timeline Required to Complete the Task:_ **[18 days ] + [6 days for new blogs]**
_How will we measure completion?_**[Fill the _Translated (Russian) Content_ section below.]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.

### Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [x] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

Original (English) Content

- [RChain update (Debrief 86), July 18th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-86-july-18th-2018-362658622427) 2,913 Words	$378.69
- [RChain update (Debrief 87), July 25th, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-87-july-25th-2018-f5d7e8f3a53a) 1,609 Words	$209.17
- [https://blog.rchain.coop/rchain-spotlight-hellofriend/](https://blog.rchain.coop/rchain-spotlight-hellofriend/) 467 Words	$60.71 
- [Running RNode on Amazon AWS(EC2](https://blog.rchain.coop/running-rnode-0-5-3-on-amazon-ec2/) 601 Words	$78.13 
- [Reflective Ventures Deal Day](https://blog.rchain.coop/reflective-ventures-deal-day/) 851 Words	$110.63
- [RNode v0.6.1 supports launch of the RChain test net](https://medium.com/rchain-cooperative/rnode-v0-6-1-supports-launch-of-the-rchain-test-net-f6ddcacb4b6) 1,268 Words $164.84

Translated (Russian) Content
- [Обновление RChain (Отчет 86), 18 июля 2018 года](https://medium.com/@Rchain.RUS/%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%BE%D1%82%D1%87%D0%B5%D1%82-86-18-%D0%B8%D1%8E%D0%BB%D1%8F-2018-%D0%B3%D0%BE%D0%B4%D0%B0-930228e95250)
- [Обновление RChain (Отчет 87), 25 июля 2018 г](https://medium.com/@Rchain.RUS/%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%BE%D1%82%D1%87%D0%B5%D1%82-87-25-%D0%B8%D1%8E%D0%BB%D1%8F-2018-%D0%B3-aa5e63e88659)
- [Запуск RNode на Amazon AWS (EC2)](https://medium.com/@Rchain.RUS/%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-rnode-%D0%BD%D0%B0-amazon-aws-ec2-7f531a8f217f)
- [День сделки с Reflective Ventures](https://medium.com/@Rchain.RUS/%D0%B4%D0%B5%D0%BD%D1%8C-%D1%81%D0%B4%D0%B5%D0%BB%D0%BA%D0%B8-%D1%81-reflective-ventures-4d1ff5d4aa28)
- [RChain Spotlight: Hellofriend](https://medium.com/@Rchain.RUS/rchain-spotlight-hellofriend-50b788ddb371)
- [RNode v0.6.1 поддерживает запуск тестовой сети RChain](https://medium.com/@Rchain.RUS/rnode-v0-6-1-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%B5%D1%82-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%B9-%D1%81%D0%B5%D1%82%D0%B8-rchain-10ec672867a)

**Comment by kovmargo** [comment]
Please, remove 'Computational Calculi Primer Part 2: π-calculus ' article. It's being translating in issue #891  and were added before yours. Thanks!
