### ISSUE TITLE
Creation of core value props document for marketing

### ISSUE THREAD

**Issue by pmoorman** [rchain/bounties#875]
The most significant work stream for marketing at the moment, is clearly defining value propositions, positioning relative to competitors, and messaging. All this work will ultimately serve all other marketing communications, but most notably the website.

After the marketing organization pushed [their core piece on messaging](https://docs.google.com/document/d/17bCHdhvQ97KgJFMWAgbxXiUYyxefseZ1-5TfvuLrmD4/edit), it was decided by Jonathan and others that further improvement was needed.

I worked intensively with Jonathan and other community members (hat tip to @ddayan and @kitblake and Kevin W. in particular) and Pyrofex developers on this matter. 

The outcome is this document: https://docs.google.com/document/d/1tMI0y9Anv41sXwC4WEphf07QQG6D3ea0Z-E9BmeWltw/edit?usp=sharing

**Product marketing epic**
For the sake of clarity: this is a continuation on the path towards a clear brand positioning and messaging for RChain. 
Other pieces include:

- Website architecture (see #780)
- Product truths documentation
- Messaging document (work-in-progress)
- Website narrative & copywriting (in progress, see #877 )
- Website design (in progress, see #876 )

All work in these matters is overseen primarily by Jonathan and Kevin W.

**A full website redesign is expected to be live before RCon3!**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by pmoorman** [comment]
This Github issue was created in August (today), but tracks a scope of work done in July. The Rewards app system won't allow to vote on a July budget for an issue that was created in August. 

While I understand why the app logic is set up that way, _I consider this to be a technicality in the rewards app,_ rather than a hard rule in the bounty system.

As such, **I have decided to track the budget & rewards for this issue in (unrelated issue)** #776. 

To be clear: this is a hack. No work done here has related to the work scope of #776, or vice versa. The reason to track under #776 is that we didn't do much for that issue this month because we used our energy to do the work under this issue. Alas.

If anyone has any questions about this weird state of affairs, I'm happy to discuss.

**Comment by dckc** [comment]
> The Rewards app system won't allow to vote on a July budget for an issue that was created in August.
>
> While I understand why the app logic is set up that way, I consider this to be a technicality in the rewards app, rather than a hard rule in the bounty system.

Hm. #682 was labelled **bounty-contract**. I thought of it as a hard rule. But I didn't make any change to CONTRIBUTING.md, and all the hard rules are supposed to be in there.

In any case, there are any number of situations where work in July might not be rewarded until August... perhaps somebody didn't drum up sufficient votes in July but got lots of support in August, for example.
