### ISSUE TITLE
Rchain Asia Weekly Debrief 20180807

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#878]
### Benefit to RChain

The first meeting will hold at 04:00 UTC 20180717
Sydney +11, Beijing +8, Greece +3, Amsterdam +2, Lagos +1,
New York -4, Seattle -7

The zoom link is https://zoom.us/j/2522161381.

The Rchain Asia Weekly Defrief note folder:https://drive.google.com/drive/folders/1PcIaVLwU4pH5wBf-mIk1zAeBMJUUjsdB

- [x] Prepare [agenda](https://docs.google.com/document/d/1E9eD94OxY8r-gaA5i8hMRLZX7ZlSEzrRG8zd0-vUSl0/edit#).
- [] invite people to attend to the meeting

cc: @kitblake @pmoorman @ddayan @AbnerZheng @lapin7 @allancto @kdvalentine @hcl3 @jiyuxuan1944 @yuhuanmocmoc @Mervyn853  @ottermagically @ian-bloom 

***Please add the items you want to discuss in the google doc!*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[500]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

**Comment by TrenchFloat** [comment]
I took the minutes for 45 minutes of the meeting, then @David405 took minutes for the rest.

**Comment by dckc** [comment]
This is on the [overdue list][1]. I suspect the budget was consolidated with another issue, so for budgeting purposes I'm marking this **duplicate**.

[1]: https://rewards.rchain.coop/index.php?-table=task_approval_overdue
