### ISSUE TITLE
August core Development work

### ISSUE THREAD

**Issue by MParlikar** [rchain/bounties#881]
### Benefit to RChain

*Build the platform

(much like May #766 June #767 July #819 )

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$5700.00**
_Estimated Timeline Required to Complete the Task:_ **4 weeks**
_How will we measure completion?_ **PR's Merged**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Ojimadu** [comment]
@Medha I suppose this should for August right?

**Comment by dckc** [comment]
Yes, since this ticket was created in August, you won't be able to reward for it in July.

**Comment by dckc** [comment]
@AbnerZheng I don't see any budget nor reward votes from you nor any notes on what work was done. Should this be closed as wontfix?

@MParlikar At close of business today (in about 3 or 4 hours) I'm out of the office for the remainder of the voting period for August, so you would need to coordinate with someone else.

@Jake-Gillberg I would appreciate if you could step in here and get the right thing(s) to happen.

**Comment by AbnerZheng** [comment]
I ask for the reward of 5700$(38 story points) for August development work. 
The tickets I have finished shows below. 

tickets 			link 									story ponint
RHOL-541  https://rchain.atlassian.net/browse/RHOL-541                     5
ROS-453  https://rchain.atlassian.net/browse/ROS-453                        1
CORE-1057  https://rchain.atlassian.net/browse/CORE-1057		 1
RHOL-329   https://rchain.atlassian.net/browse/RHOL-329			13
RHOL-648   https://rchain.atlassian.net/browse/RHOL-648		         5
RHOL-649    https://rchain.atlassian.net/browse/RHOL-649                13

**Comment by dckc** [comment]
@AbnerZheng I don't see any votes from you. Be sure to vote for yourself!

**Comment by AbnerZheng** [comment]
@dckc Done, thanks for your help.

**Comment by dckc** [comment]
@AbnerZheng , @zsluedem in [rewards for this issue][1] I see you voted for this issue again for 201809. Any reason why? It was already rewarded in 201808. For September work, see #985.

[1]: https://rewards.rchain.coop/index.php?-table=issue&-sort=num+desc&-limit=30&num=881&title=&updatedAt=&state=&createdAt=&labels=&-action=related_records_list&-cursor=0&-skip=0&-mode=list&-recordid=issue%3Fnum%3D881&-relationship=Rewards

**Comment by dckc** [comment]
@JoshOrndorff your 201809 budget vote on this issue is misplaced. #985 is the issue for Sep.

cc @allancto
