### ISSUE TITLE
Translate RChain Blogs - Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#883]
### Benefit to RChain

Reach larger audience and help to build the community 
Translation will be posted at [RChain Worldwide Community Forum](https://rchaincommunity.xyz/) and at [Medium RChain_RU](https://medium.com/@rchain_ru)

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[344.6 (313.3+10% 31.3 markdown conversion) ]**
_Estimated Timeline Required to Complete the Task:_ **[7 days]**
_How will we measure completion?_ **[Will be posted at [RChain Worldwide Community Forum](https://rchaincommunity.xyz/) and at [Medium RChain_RU](https://medium.com/@rchain_ru)]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in Russian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: Native Language speakers and diploma from Russian Embassy School in Athens
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: 

**Original (English) Content**
- [RChain update (Debrief 88), 1st August, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-88-1st-august-2018-8058f8f94527) 1,749 Words
- [Start coding in Rholang](https://blog.rchain.coop/start_coding_in_rholang/) 661 Words

**Translated (Russian) Content**
- [Обновление RChain (Дебриф 88), 1 августа 2018 года](https://medium.com/@rchain_ru/%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%84-88-1-%D0%B0%D0%B2%D0%B3%D1%83%D1%81%D1%82%D0%B0-2018-%D0%B3%D0%BE%D0%B4%D0%B0-b3e3d2275a05)
- [Начните кодирование в Rholang сегодня!](https://medium.com/@rchain_ru/%D0%BD%D0%B0%D1%87%D0%BD%D0%B8%D1%82%D0%B5-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-rholang-%D1%81%D0%B5%D0%B3%D0%BE%D0%B4%D0%BD%D1%8F-9c04587ad15a)

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by pavlos1851** [comment]
@qelentium Please change the title so that the target language is visible. Also, state the assignees/reviewers for this issue. Finally, you've clearly misunderstood the meaning and puprose of the  "What about maintenance?" section. These are blog posts and thus, they are stable. Please select the first option.

**Comment by qelentium** [comment]
@pavlos1851 @kovmargo gonna be reviewer i still can not assign her here.Thanks for helping!

**Comment by qelentium** [comment]
Reviewed by @kovmargo posted at Medium and https://rchaincommunity.xyz https://rchaincommunity.xyz/t/rchain-88-1-2018/320 and https://rchaincommunity.xyz/t/rholang/319. Closing this issue
