### ISSUE TITLE
Translate the video What is RChain All About to Chinese

### ISSUE THREAD

**Issue by cool007zqw** [rchain/bounties#884]
I just learnt video translation is suspended for now. So I will close this issue.

### Benefit to RChain

I translated the video [What is RChain All About](https://www.youtube.com/watch?v=f1D4vowiMiI) with Chinese subtitles and @zsluedem and @Whisker17 reviewed and proofread it.

This is the latest Intro video of RChain which helps people understand the core value of RChain. But to most Chinese it will be hard to understand because of the language barrier. The Chinese subtitles helps to reduce the barrier.

The video has been uploaded by @zsluedem on Tencent Video and Bilibili, two of the major video sites in China. and here are the statistics of views:
[Tencent Video](https://v.qq.com/x/page/c0706527sbu.html?spm=a2h0k.11417342.soresults.dtitle): 1467
[Bilibili](https://www.bilibili.com/video/av25802369): 187

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[250]** $200 for translation of 973 words + $50 for time editing of subtitles
_Estimated Timeline Required to Complete the Task:_ **[it took me 3.5 hours]**
_How will we measure completion?_ **[video uploaded]**

Please note besides translating, editing the time of every line of the subtitles is also a part of the work.

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [x] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in _the target language_
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [ ] a track record of quality work on rchain bounties: #465, #384, #347 
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by pmoorman** [comment]
removing the marketing label, as this is a translation (which we exclude from marketing)

**Comment by dckc** [comment]
This is on the [overdue for task approval list][1]. Given @zsluedem 's [comment][2] about a separate Asian bounty program, I'm marking this **duplicate**.

[1]: https://github.com/rchain/bounties/issues/783#issuecomment-423035301
[2]: https://github.com/rchain/bounties/issues/783#issuecomment-423035301
