### ISSUE TITLE
Orientation video in Chinese on How to join RNode weekly community test

### ISSUE THREAD

**Issue by cool007zqw** [rchain/bounties#885]
### Benefit to RChain

I have been participating 3 or 4 times in RNode weekly community test and realize some orientation on the following questions will make joining easier and smoother, especially for first-timers:
1. what to prepare
2. where to find information about the upcoming test
3. how to file a bug/issue

So I made a video for the Chinese community. It has been uploaded by me and @zsluedem on [Youku](https://v.youku.com/v_show/id_XMzc2NjY5NzAxNg==.html?spm=a2hzp.8244740.0.0), [Tencent Video](https://v.qq.com/x/page/j0748s5xzg0.html), with total 240 views for far.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[100]**
_Estimated Timeline Required to Complete the Task:_ **[2 hours]**
_How will we measure completion?_ **[video uploaded]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by zsluedem** [comment]
@David405 @JoshOrndorff @TrenchFloat 
Can you guys take a look at this one and give a reasonable budget vote and reward vote

**Comment by David405** [comment]
@cool007zqw @zsluedem Although I couldn't understand much of what was done ( _since it was done in Chinese of which I am not proficient in_ ) I believe it is a good guide for those with Chinese proficiency.

**Comment by zsluedem** [comment]
@David405 Thanks David~ :)

**Comment by dckc** [comment]
I see rewards were issued in the 201808 pay period.
