### ISSUE TITLE
RCON3 Takes Over Berlin for Blockchain Week video

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#886]
RCON3 Takes Over Berlin for Blockchain Week video - a video to excite ,promote & market the Rcon3 event. 

Estimated Budget of Task:_ $[900]
Estimated Timeline Required to Complete the Task:_ [3-5 -work in progress]
How will we measure completion?_ [Video Link submitted / original video transferred directly]

- [x] source clips ,material, audio backing track options 
- [x] import, arrange into project timeline, compose edit , color grade etc
- [x] generate title effects, transition effects and dubb/mix backing 
- [x] post production and load to Youtube 

upon completiong the first draft found here [https://www.youtube.com/watch?v=78RiV5YPsh0](https://www.youtube.com/watch?v=78RiV5YPsh0)

**Comment by Ojimadu** [comment]
Excellent video.

**Comment by nonnykul** [comment]
Good work @**cryptovideos**,
 Nice themes being put together, the concept of of the video was awesome. The flight  that took off at the early stage of the video was captivating. The message behind the video was duly informed...
** The 2018 Rcon 3 event*". I would love to help in the publicity of this promo video.

**Comment by Cryptovideos** [comment]
Excellent please discuss the marketing drive / efforts thereoff with @disruptbansky

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by decentralizebanksy** [comment]
Hey, guys let's wait on sharing this publicly until we get a round of feedback. Once that happens and the edits are made shortly after that, I'll use the RChain social media channels to share it. Then, we with out public accounts will engage with those posts and share those posts. 

Also, we'd share it in FB Groups, Linkedin Groups, Subreddits, etc.

**Comment by jasoncruzzy** [comment]
Nice work man!!

**Comment by Cryptovideos** [comment]
Hey guys tks for the positivity and good vibes...i look forward to seeing it get loads of views/drive etc

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by casanwugo** [comment]
Great! I'm in.

**Comment by Tonyprisca13** [comment]
Superb

**Comment by Cryptovideos** [comment]
Great feedback tks @Preshcode ... please wait on @decentralizebanksy tho before undertaking anything just yet, we are going to tweak it slightly and then will upload a Final version....should not be too long tho till its ready, hang in there and check with him tho in the interim...

**Comment by decentralizebanksy** [comment]
@Ojimadu @Preshcode @Tonyprisca13 @casanwugo @nonnykul @jasoncruzzy Check out this issue with online marketing instructions on promoting the final RCON3 promo code and Facebook event page https://github.com/rchain/bounties/issues/911

**Comment by casanwugo** [comment]
@decentralizebanksy, @cryptovideos... Good job!! #911

Tweeted on;

- <a href="https://medium.com/@annchidinma5/hello-blockchain-lovers-hashtag-crypto-subscribers-88b06c738e8d">@Crypto Medium Blog</a>

- <a href="https://m.facebook.com/story.php?story_fbid=2079908928733886&id=100001443976348&__tn__=%2As%2As-R">Facebook</a>

- <a href="https://www.linkedin.com/feed/update/activity:6436623658906578944">Linkedin</a>

**Comment by AyAyRon-P** [comment]
@decentralizebanksy @Cryptovideos @Ojimadu 

This project seems to be completed, can we close this out for the month? Or is it waiting for feedback? 

Please provide a status update and close if it's ready for voting.

**Comment by Cryptovideos** [comment]
Yes its closed thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
