### ISSUE TITLE
Blog Post: Post RChain documents on Hashnode and medium blog

### ISSUE THREAD

**Issue by azazime** [rchain/bounties#887]
### Benefit to RChain
Promote Rchain contents regularly on Hashnode.
Create Rholang awareness amongst developers on hashnode

Posts on hashnode/medium blog;

<a href="https://hshno.de/Hyd4qOBSm">Correct-by-construction Casper</a>

<a href="https://medium.com/@andrewasamonye/the-rchain-root-shard-85f529f5a11c">The RChain Root Shard</a>

<a href="https://medium.com/@andrewasamonye/backbone-validation-663e13a88d7e">Validation</a>

<a href="https://medium.com/@andrewasamonye/rchain-community-validation-polls-dd1e863f0f04">RChain Community Validation Polls</a>

<a href="https://medium.com/@andrewasamonye/building-a-new-blockchain-without-reinventing-the-wheel-f50a85081995">New World of Blockchain</a>

<a href="https://medium.com/@andrewasamonye/rnode-v0-5-1-released-a0e2836457c0">RNode v0.5.1 Released</a>

<a href="https://medium.com/@andrewasamonye/become-a-validator-and-acquire-rhoc-for-staking-4e81de2bd2b6">Become a Validator</a>

<a href="https://medium.com/@andrewasamonye/computational-calculi-primer-part-2-%CF%80-calculus-acb30c789ce3 ">Computational-calculi-primer-part2</a>

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[???]**

**Comment by Keaycee** [comment]
The 3, 4, & 5th post was delisted from hashnode by moderators, kindly review the post.

**Comment by azazime** [comment]
Yes @Keaycee that is due to some of their internal policy, its been sorted out..

**Comment by Keaycee** [comment]
Good Job

**Comment by mmaksimovic** [comment]
Hi @azazime @Keaycee @JUANITA-MAYBEL 

My name is Milica and I am the Hashnode Community Manager. What you're discussing here goes directly against our policy and we're going to take the following steps:

-  Delist all posts that mention RChain,
-  Ban all the fake registered profiles that were involved in this process.


You're free to engage with the rest of Hashnode community as long as you follow our rules. Our platform was always free for use and we won't allow anyone to profit from promoting any services.

I'm here if you have any questions.

Regards,
Milica Maksimovic

**Comment by mmaksimovic** [comment]
Hey @azazime ,

I've noticed that my comment was deleted, so I'm repeating things once again.

My name is Milica and I am the Hashnode Community Manager. What you're discussing here goes directly against our policy and we're going to take the following steps:

-  **Delist all posts that mention RChain,**
-  **Ban all the fake registered profiles that were involved in this process.**


You're free to engage with the rest of Hashnode community as long as you follow our rules. Our platform was always free for use and we won't allow anyone to profit from promoting any services.

**As we've already discussed, @azazime is no longer allowed to ever mention RChain on our platform, or he will be permanently banned, so please close this issue.**

I'm here if you have any questions.

Regards,
Milica Maksimovic

**Comment by azazime** [comment]
@mmaksimovic you comments here are not entirely in the best interest of Rchain hence I would like you to take it down or send it as a private message to my mail, thanks.

**Comment by pmoorman** [comment]
@mmaksimovic @fazlerocks just wanted to hopefully put you (somewhat) at ease that we're talking about this issue internally. We have a call this Friday were I expect it will be addressed. 

For the record: I'm also not an officer of RChain, but I'll try escalate it to someone appropriate. I think that would be best. For us it's certainly a learning case on how to avoid such situations in the future.

cc @dckc @deannald @kitblake

**Comment by azazime** [comment]
@mmaksimovic sorry for my actions both here and on hashnode, it was a clear misunderstanding from my path. Everything about hashnode will be removed here.
