### ISSUE TITLE
RChain Wolfram|Alpha Oracles Project Request For Comments

### ISSUE THREAD

**Issue by ottermagically** [rchain/bounties#888]
**RChain Wolfram|Alpha Oracles _Request For Comments_**

_Project Team: Jake Gilberg (@Jake-Gillberg), Jonathan Kochmer (@ottermagically), Deanna Duke (@deannald), participants from Ethereum_

**Overview**: We propose to leverage the experience of a team from Ethereum to deploy specific, strategic, and well-defined Oracle services from [Wolfram|Alpha](http://www.wolframalpha.com) for the benefit of RChain just as they have done for Ethereum.

**Status**: We are here soliciting the RChain community for ideas about highest priority Oracle service to RChain, ideally in time for Mercury launch. _This Oracle Project initiation is contingent upon perceived added value of Oracles proposed to the quality, performance and revenue enhancement to RChain. We make no guarantees at this time that any particular Oracle service will be included if project is initiated._

**Call To Action**: Suggest in comments on this issue those Oracle Services you would like for use on Rchain, especially if you are member of a technical team of an RChain Platform Partner or certain you will be developing a high-quality dApp on RChain.

_Estimated Budget of Task:_ 0 within Bounty System most likely
_Estimated Timeline Required to Complete the Task:_ 7 days to collect suggestions from community
_How will we measure completion?_ Incorporation of new high-value WolframAlpha Oracles into Proposal to be Reviewed by Board

### High Value / Low Implementation Risk Oracles

1. Random number generator - poll, parameterized (goal: to test methods of ensuring trust (how is seed generated, how do we know for sure the seed won’t leak))

> RandomInteger[{imin, imax}]

2. By Request from RChain Platform Partner: Global Clean vs Renewable energy production - update when there is new information (goal: demonstrate push on updated capability)

> Entity["Country", "World"][EntityProperty["Country", "ElectricityTotalRenewables", {"ResourceTransaction" -> "Production"}]]
> Entity["Country", "World"][EntityProperty["Country", "AllPrimaryFuels", {"ResourceTransaction" -> "Production"}]]

3. Price Data
    1. REV (RHOC) to USD - Update on a 1% change, on request, or at minimum every 6 hours, poll for price at specific historic date / time
    2. REV (RHOC) to USD thirty day moving average - Same as above, but a 30 day moving average (closing price per day determined by price at midnight)
    3. ETH to USD - Update on a 1% change, on request, or at minimum every 6 hours, poll for price at a specific historic date / time

4. Fiat Currency Exchange Rates - poll, parameterized

5. Stock prices - poll, parameterized

6. Ethereum to USD - push on time schedule?

### High Value / Medium Implementation Risk Oracles

1. Ethereum <-> RChain events
    1. End-user requests updates from a specific ethereum event (with address and block height)
    2. Reverse process, from RChain events to Ethereum

### High Value / Unknown Implementation Risk Oracles

1. Oauth
    1. Discord
    2. Github
    3. Google
5. Arbitrary Wolfram queries
6. Ethereum Name Service (ENS)
7. Carbon Market Data
8. Consumer Price Index
9. Climatological data streams

**Comment by ogini1** [comment]
The top three oracle services I would like to see implemented are:
1. Price data
2. Oauth
3. Climatological data streams

Additional: RNG

**Comment by Jake-Gillberg** [comment]
Hey @ogini1, thanks for the input. I haven't seen you around here before, care to introduce yourself?

Also, can you be more specific as to what you would like to use the [Climatological data streams](http://www.wolframalpha.com/examples/science-and-technology/weather-and-meteorology/) for / exactly what pieces of data you would find useful? This one is currently not defined well enough for implementation.

**Comment by Phistr90** [comment]
Generally sounds interesting.
Can you elaborate on why the first 6 are 'low risk' oracles services?  
Generally what do mean by risk in this context?
I would think the risk depends on the application the oracles services are used for and centralized oracles can always do a lot of harm when used improperly.

**Comment by Jake-Gillberg** [comment]
@Phistr90 "Risk" here is being used as more of a project management term and not a security term; "low risk" is referring to the fact that these oracles have no or relatively little unknowns when it comes to implementation.

> I would think the risk depends on the application the oracles services are used for and centralized oracles can always do a lot of harm when used improperly.

I wholeheartedly agree. These oracles will only be useful to those willing to trust a signed message from Wolfram|Alpha containing the requested data. There is active research being done on their end to understand how to put more trust into this data, through both decentralization and verified computation.

**Comment by dckc** [comment]
Feeds from the stock market and stuff look pretty cool.

As to OAuth: I have a good start on it, so I'd be a little jealous: https://github.com/dckc/rchain-dbr/tree/reorg_dirs/o2r 8e5a3ef
I was planning to work with the European coop folks who are building on-chain governance tools.

**Comment by Jake-Gillberg** [comment]
Notably absent from this list are any oracles that leverage the high-strain computational capabilities of Wolfram|Alpha.. anyone have thoughts on a use case here?

**Comment by desaperados** [comment]
As a point of reference, we explored using Wolfram Alfa as a price oracle at Maker and decided that it was too expensive compared to our own price-feeds solution. From memory I think it was going to cost 50K/year plus transaction costs which is far more than we pay to run our own oracles.  

https://makerdao.com/feeds/

**Comment by allancto** [comment]
#dc, we (like Maker DAO) would rather build a pool of members skilled in
these areas. That's another important consideration. And btw it's my
current assessment that mkr has a much better (though special purpose)
oracle system.

I encourage everyone to follow and understand the Maker project, i imagine
that in the future we'll be cooperating with them in some areas. -@allancto

**Comment by Jake-Gillberg** [comment]
@desaperados Yeah, thanks, I talked with Kenny and Mariano about this. Our project plan is to incubate useful oracles for the duration of a pilot project then transition the financial support for the useful oracles off of the coop, hopefully captured in smart contracts and charged by usage.

**Comment by ogini1** [comment]
Hello Jake, am Ginika.I've been loosely following the community but recently signed up and still trying to find my way around here and blockchain technology.
I would like to see climate data being used for some kind of on-chain insurance for agriculture and supply chain/logistics. Data like degree days and atmospheric thermodynamics and weather forecast would be useful for such use case IMO.

**Comment by Jake-Gillberg** [comment]
@ogini1 Thanks! for both the introduction and the clarification. It looks like degree-days would certainly be an option for us.

If you know or contact anyone who is (or if you yourself are) interested in building an insurance application like the one described, please send them my way, I would love to talk in more detail.

**Comment by ottermagically** [comment]
@Jake-Gillberg it seems that despite repeated entreaties to the pithia and reflective ventures discord channels and in the weekly debrief, comments and suggestions have died down. Frankly, I'm a tad disheartened, but as they say in Old English, _sofliche_ I'll be in a RVP call in 10 minutes, maybe I can scare up a wren or a thrush.

**Comment by dckc** [comment]
@Jake-Gillberg the 7 day estimate starting Aug 9 has long past. If this is still going on, give us an updated timeframe? If not, please close this.

**Comment by Jake-Gillberg** [comment]
This project is currently blocked waiting for funding on the coop end. @JoshOrndorff may have picked up a lead for another potential partner to provide these services.

I suppose this issue has served it's purpose though, informing the bounty community and getting feedback on the oracles. closing.
