### ISSUE TITLE
Translate last RChain Asia, Spotlight, C. Calculi 2, 3, Become Validator, RASPBERRY Pi + Debrief 89 to Russian

### ISSUE THREAD

**Issue by kovmargo** [rchain/bounties#891]
Translation of the RChain hot topics to other languages means good global marketing: reach a larger audience and help expand the community building.

### Budget and Objective
**Collaborators Work:**
@kovmargo: 90%
@golovach-ivan: 10%

**Estimated Budget of Task: $1613 ($1466.69 + $146.7(10% for the Markdown conversion))**

Estimated Timeline Required to Complete the Task: **7** 
How will we measure completion? **Fill the Translated Content section below. Also, translations will be posted on the RChain Worldwide Community Forum (Russian), the RChain Cooperative Medium account(Russian), Facebook.**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 

  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language (Russian)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@kovmargo) from institution: [European University](https://e-u.in.ua/ua/) (international diploma)
       - [x] a track record of quality work on rchain bounties: #863, #865  
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [] our plan to keep the translation up to date is:

Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)

**Original (English) Content:**
[COMPUTATIONAL CALCULUS PRIMER PART 3: Ρ-CALCULUS](https://blog.rchain.coop/calculus-primer-%CF%81-calculus/) (2,581 words, $387.15)
[RCHAIN AND RASPBERRY PI: COIN FAUCET](https://blog.rchain.coop/rchain-and-raspberry/)  (937 words, $140.55)
[Become a validator and acquire RHOC for staking](https://blog.rchain.coop/become-a-validator-and-acquire-rhoc-for-staking/) (921 Words, $119.73)
[Computational Calculi Primer Part 2: π-calculus](https://blog.rchain.coop/calculus-primer-%CF%80-calculus/) (2,033 Words, $264.29)
[RChain Asia: China](https://blog.rchain.coop/rchain_asia_china/) (1,967 Words, $255.71)
[RChain Spotlight : Translo](https://blog.rchain.coop/rchain-spotlight-translo/)    (736 Words, $95.68)
[RChain update (Debrief 89), 8th August 2018](https://medium.com/@vimirimious34/rchain-update-debrief-89-8th-august-2018-a61d2273b114) (1566 Words, $203.58)

**Translation**
[ВЫЧИСЛИТЕЛЬНЫЕ ИСЧИСЛЕНИЯ ЧАСТЬ 3: RHO-ИСЧИСЛЕНИЯ](https://medium.com/@rchainhomeru/%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B8%D1%81%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D1%8C-3-rho-%D0%B8%D1%81%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-153e13e587aa)
[RCHAIN И RASPBERRY PI: СБОРЩИК МОНЕТ](https://medium.com/@rchainhomeru/rchain-%D0%B8-raspberry-pi-%D1%81%D0%B1%D0%BE%D1%80%D1%89%D0%B8%D0%BA-%D0%BC%D0%BE%D0%BD%D0%B5%D1%82-3cf1dc11bcaf)
[Станьте валидатором и приобретайте RHOC, чтобы иметь возможность сделать ставку](https://medium.com/@rchainhomeru/%D1%81%D1%82%D0%B0%D0%BD%D1%8C%D1%82%D0%B5-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%BC-%D0%B8-%D0%BF%D1%80%D0%B8%D0%BE%D0%B1%D1%80%D0%B5%D1%82%D0%B0%D0%B9%D1%82%D0%B5-rhoc-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D0%B8%D0%BC%D0%B5%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D1%83-fda701f78a28)
[ВЫЧИСЛИТЕЛЬНЫЕ ИСЧИСЛЕНИЯ ЧАСТЬ 2: π-исчисления](https://medium.com/@rchainhomeru/%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B8%D1%81%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D1%8C-2-%CF%80-%D0%B8%D1%81%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-b3f97af0ae9c)
[RChain Азия: Китай](https://medium.com/@rchainhomeru/rchain-asia-%D0%BA%D0%B8%D1%82%D0%B0%D0%B9-4c35fde62b6d)
[Прожектор RChain: Translo]( https://medium.com/@rchainhomeru/прожектор-rchain-translo-477f404e684)
[Обновление RChain (Отчет 89), 8 августа 2018 года](https://medium.com/@rchainhomeru/%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-rchain-%D0%BE%D1%82%D1%87%D0%B5%D1%82-89-8-%D0%B0%D0%B2%D0%B3%D1%83%D1%81%D1%82%D0%B0-2018-%D0%B3%D0%BE%D0%B4%D0%B0-6517ea9a66ba)

**Comment by pavlos1851** [comment]
[RChain Blockchain multithreading mechanism](https://thecryptosyndicate.com/rchain-multi-threading-blockchain/) is not a [medium](https://medium.com/rchain-cooperative) or [blog.rchain.coop](https://blog.rchain.coop/) item. Why did you include this post?

**Comment by kovmargo** [comment]
@pavlos1851 because I'm going to post translation on the Medium account. But it's seems I need to create separate issue for "RChain Blockchain multithreading mechanism" article and check  "It's a document on https://developer.rchain.coop/" option .

**Comment by pavlos1851** [comment]
You posting a translation on medium does not make it an official RChain Medium blog item. 
Also, it's not a document from [developer.rchain.coop](https://developer.rchain.coop/) either.
This is an article written by a third party completely unrelated to the Coop.
I cannot understand the reasoning behind including this here and in #892.

**Comment by kovmargo** [comment]
The reason is to explain the blockchain multithreading mechanism to Russian people, aim at attach more people who are interested in RChain. If it's not suit I'll delete this article.

**Comment by kovmargo** [comment]
Reviewed. Closed
