### ISSUE TITLE
Translate last Medium post: RASPBERRY Pi, Calculus Part 3  + Debriefs 88, 89, 90 to Ukrainian

### ISSUE THREAD

**Issue by kovmargo** [rchain/bounties#892]
Translation of the RChain topics to other languages means good global marketing: reach a larger audience and help expand the community building. Translation of Blockchain multithreading mechanism will help Ukrainian-speaking people to understand the blockchain technology and add more value to the process.

### Budget and Objective
**Collaborators Work:**
@kovmargo: 80%
@golovach-ivan: 10%
@qelentium: 10%

**Estimated Budget of Task: $2304 ($2094.81 +  $209,5(10% for the Markdown conversion))**

Estimated Timeline Required to Complete the Task: **7** 
How will we measure completion? **Fill the Translated Content section below. Also, translations will be posted on the RChain Worldwide Community Forum (Russian), the RChain Cooperative Medium account(Russian), Facebook.**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 

  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language (Russian)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@kovmargo) from institution: [European University](https://e-u.in.ua/ua/) (international diploma)
       - [x] a track record of quality work on rchain bounties: #863 
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [] our plan to keep the translation up to date is:

Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)

**Original (English) Content:**
[COMPUTATIONAL CALCULUS PRIMER PART 3: Ρ-CALCULUS](https://blog.rchain.coop/calculus-primer-%CF%81-calculus/) (2,581 words, $387.15)
[RCHAIN AND RASPBERRY PI: COIN FAUCET](https://blog.rchain.coop/rchain-and-raspberry/)  (937 Words, $140.55)
[Become a validator and acquire RHOC for staking](https://blog.rchain.coop/become-a-validator-and-acquire-rhoc-for-staking/) (921 Words, $119.73)
[Computational Calculi Primer Part 2: π-calculus](https://blog.rchain.coop/calculus-primer-%CF%80-calculus/) (2,033 Words, $264.29)
[RChain Debrief 90: RCON3 program released](https://blog.rchain.coop/rchain-debrief-90/) (1,414 Words, $183.82)
[RChain update (Debrief 89), 8th August 2018](https://medium.com/@vimirimious34/rchain-update-debrief-89-8th-august-2018-a61d2273b114) (1566 Words, $203.58)
[RChain update (Debrief 88), 1st August, 2018](https://medium.com/rchain-cooperative/rchain-update-debrief-88-1st-august-2018-8058f8f94527) (1,749 Words, $227)
[RChain Asia: China](https://blog.rchain.coop/rchain_asia_china/) (1,967 Words, $255.71)
[Computational Calculi Primer](https://blog.rchain.coop/computational-calculi-primer/) (1520 Words, $217.3)
[RChain Spotlight : Translo](https://blog.rchain.coop/rchain-spotlight-translo/)    (736 Words, $95.68)

**Translation**
[ОБЧИСЛЮВАЛЬНІ ОБЧИСЛЕННЯ ЧАСТИНА 3: RHO-ОБЧИСЛЕННЯ](https://medium.com/@rchainhomeukr/%D0%BE%D0%B1%D1%87%D0%B8%D1%81%D0%BB%D1%8E%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D1%96-%D0%BE%D0%B1%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-3-rho-%D0%BE%D0%B1%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-169cb353bc89)
[RCHAIN ТА RASPBERRY PI: СБОРЩИК МОНЕТ](https://medium.com/@rchainhomeukr/rchain-%D1%82%D0%B0-raspberry-pi-%D1%81%D0%B1%D0%BE%D1%80%D1%89%D0%B8%D0%BA-%D0%BC%D0%BE%D0%BD%D0%B5%D1%82-10628b1b76cf)
[Станьте валідатором і придбайте RHOC щоб зробити ставку](https://medium.com/@rchainhomeukr/%D1%81%D1%82%D0%B0%D0%BD%D1%8C%D1%82%D0%B5-%D0%B2%D0%B0%D0%BB%D1%96%D0%B4%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%BC-%D1%96-%D0%BF%D1%80%D0%B8%D0%B4%D0%B1%D0%B0%D0%B9%D1%82%D0%B5-rhoc-%D1%89%D0%BE%D0%B1-%D0%B7%D1%80%D0%BE%D0%B1%D0%B8%D1%82%D0%B8-%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D1%83-e0889931ad3)
[ОБЧИСЛЮВАЛЬНІ ОБЧИСЛЕННЯ ЧАСТИНА 2: π-числення](https://medium.com/@rchainhomeukr/%D0%BE%D0%B1%D1%87%D0%B8%D1%81%D0%BB%D1%8E%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D1%96-%D0%BE%D0%B1%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-2-%CF%80-%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-2bf803592df0)
[RChain Дебріф 90: випуск програми RCON3](https://medium.com/@rchainhomeukr/rchain-%D0%B4%D0%B5%D0%B1%D1%80%D1%96%D1%84-90-%D0%B2%D0%B8%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8-rcon3-7fc307cb52b4)
[Оновлення RChain (Звіт 89), 8 серпня 2018 року](https://medium.com/@rchainhomeukr/%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-rchain-%D0%B7%D0%B2%D1%96%D1%82-89-8-%D1%81%D0%B5%D1%80%D0%BF%D0%BD%D1%8F-2018-%D1%80%D0%BE%D0%BA%D1%83-9e301bcbb72c)
[Оновлення RChain (Звіт 88), 1 серпня 2018 року](https://medium.com/@rchainhomeukr/%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-rchain-%D0%B7%D0%B2%D1%96%D1%82-88-1-%D1%81%D0%B5%D1%80%D0%BF%D0%BD%D1%8F-2018-%D1%80%D0%BE%D0%BA%D1%83-2d2833419da8)
[RChain Азія: Китай](https://medium.com/@rchainhomeukr/rchain-%D0%B0%D0%B7%D1%96%D1%8F-%D0%BA%D0%B8%D1%82%D0%B0%D0%B9-f3712c9d9113)
[Обчислювальні числення. Частина 1: Лямда-числення і BNF](https://medium.com/@rchainhomeukr/%D0%BE%D0%B1%D1%87%D0%B8%D1%81%D0%BB%D1%8E%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D1%96-%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-1-%D0%BB%D1%8F%D0%BC%D0%B4%D0%B0-%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-%D1%96-bnf-d112aa78dadf)
[Прожектор RChain: Translo](https://medium.com/@rchainhomeukr/%D0%BF%D1%80%D0%BE%D0%B6%D0%B5%D0%BA%D1%82%D0%BE%D1%80-rchain-translo-94370f56f8e6)

**Comment by Ojimadu** [comment]
Is there a need translating same documents to Russian and Ukrainian? Am opined that these languages bear remarkable similarities as they are both Slavic languages. I believe anyone that's able to comprehend Russian would do so reasonably well for Ukrainian as well.

**Comment by pavlos1851** [comment]
[RChain Blockchain multithreading mechanism](https://thecryptosyndicate.com/rchain-multi-threading-blockchain/) is not a [medium](https://medium.com/rchain-cooperative) or [blog.rchain.coop](https://blog.rchain.coop/) item. Why did you include this post?

**Comment by kovmargo** [comment]
Issue reviewed. Closed.
