### ISSUE TITLE
Rchain Asia Weekly Debrief 20180814

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#894]
### Benefit to RChain

The first meeting will hold at 04:00 UTC 20180814
Sydney +11, Beijing +8, Greece +3, Amsterdam +2, Lagos +1,
New York -4, Seattle -7

The zoom link is https://zoom.us/j/2522161381.

The Rchain Asia Weekly Defrief note folder:https://drive.google.com/drive/folders/1PcIaVLwU4pH5wBf-mIk1zAeBMJUUjsdB

- [x] Prepare [agenda](https://docs.google.com/document/d/1SWYVHF4XBnpJgqocogYaWAfXurnAtS7qCDxWcpDb_bk/edit?usp=sharing
).
- [] invite people to attend to the meeting

cc: @kitblake @pmoorman @ddayan @AbnerZheng @lapin7 @allancto @kdvalentine @hcl3 @jiyuxuan1944 @yuhuanmocmoc @Mervyn853  @ottermagically @ian-bloom 

***Please add the items you want to discuss in the google doc!*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[500]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

**Comment by dckc** [comment]
I don't see any budget votes, so I suppose this is more of a discussion than a task proposal.
