### ISSUE TITLE
ONGOING: RChain update on blog and Medium

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#896]
Check every Thursday at [RChain blog](https://blog.rchain.coop/category/community/) to get updates from the community. 
**August**

- [x] [Debrief 88](https://medium.com/rchain-cooperative/rchain-update-debrief-88-1st-august-2018-8058f8f94527)
- [x] [Debrief 89](https://medium.com/@vimirimious34/rchain-update-debrief-89-8th-august-2018-a61d2273b114)
- [x] [Debrief 90](https://medium.com/rchain-cooperative/rchain-update-debrief-90-15th-august-2018-f2ab4b7bb8af)
- [x] [Debrief 91](https://blog.rchain.coop/rchain-debrief-91-rnode-v0-6-1-released/)
- [x] [Debrief 92](https://blog.rchain.coop/rchain-debrief-92-rcon3-week/)

**September**
- [x] [Debrief 93](https://blog.rchain.coop/rchain-debrief-93-rcon3/)
- [x] [Debrief 94](https://blog.rchain.coop/rchain-update-94-feedback-from-rcon3/)
- [x] [Debrief 95](https://blog.rchain.coop/rchain-update-95/)
- [x] [Debrief 96](https://blog.rchain.coop/rchain-debrief-96-try-rsong-immersive-audio-on-android-or-iphone/)

**October**
- [x] [Debrief 97](https://www.rchain.coop/blog/rchain-debrief-97/)
- [x] [Debrief 98](https://www.rchain.coop/blog/rchain-debrief-98/)
- [x] [Debrief 99](https://www.rchain.coop/blog/rchain-debrief-99-items-of-business/)
- [x] [Debrief 100](https://www.rchain.coop/blog/rchain-debrief-100-the-market-signal/)
- [x] [Debrief 101](https://www.rchain.coop/blog/rchain-debrief-101-main-net-security-and-performance-tradeoffs/)

**November**
- [x] [Debrief 102](https://www.rchain.coop/blog/rchain-debrief-102-officers-items-of-business-updates-and-transactions-discussion/)
- [x] [Debrief 103](https://www.rchain.coop/blog/rchain-debrief-103-rchain-on-spot-for-korean-blockchain-facility-support/)
- [ ] Debrief 104
- [ ] Debrief 105
- [ ] Debrief 106

**Comment by dckc** [comment]
The RChain blog is https://blog.rchain.coop/ now, right? It's no longer on medium, is it?

**Comment by dckc** [comment]
Please use a more novel headline. This stuff is too interesting and valuable to go under a headline that only communicates "A week has passed and I have put more bits on the internet". For example, the headline for update 88 could be:

 - RChain 88: RumbleMonkey wins 50K RHOC at Reflective Deal Day, 18 nodes connect, RCon in Berlin and more


See also:
  - [my recent comment on the weekly index to the same effect](https://github.com/rchain/bounties/issues/812#issuecomment-406634657)
 - [Nielsen on headlines and other microcontent](https://www.nngroup.com/articles/microcontent-how-to-write-headlines-page-titles-and-subject-lines/)

**Comment by Viraculous** [comment]
Thanks @dckc. We will be having the full version of the debriefs on the blog and a shorter one on Medium.

**Comment by kitblake** [comment]
@Viraculous Does this issue require votes?

**Comment by Viraculous** [comment]
@kitblake for now I am indecisive about this particular issue with regards to vote but will be needing vote for last month's. Moreover,  this issue is meant to keep track some sort of the debrief. See reply in issue.

**Comment by dckc** [comment]
This work (along with #812) on text summaries of the weekly debrief is important. The blog items are getting better and better. If we had a [category just for them](https://github.com/rchain/marketing/issues/17), we might be able to retire the [Weekly Debrief Index](https://github.com/rchain/bounties/wiki/Weekly-Debrief-Index) wiki topic.

Meanwhile, @TrenchFloat @Viraculous @PatrickM727 @plantether  (and @kitblake ? @pmoorman ? @AyAyRon-P ? ) I gather you have an agreement in principal about how this work is conducted and rewarded. Please write it down for the purposes of the reboot (#783). I suggest a narrow **weekly-debrief** or **debrief-editorial** label, since the wider **Marketing** area seems challenging to map out in general.

**Comment by dckc** [comment]
I wonder how this relates to what [Derek Beres](https://blog.rchain.coop/author/derek-beres/) wrote in [#members](https://discordapp.com/channels/375365542359465989/406191011564617748) yesterday:

> 1. the blog is going through a revamp; some pieces are in place, but we are planning on producing daily content in the coming weeks, which will integrate nicely with
> 2. a weekly newsletter I'll be spearheading. This is for subscribers that will go out every Thursday. It will be a round-up of Wednesday's community call, new blog content, event information, and so forth. It's one of the main projects I've been envisioning since coming on board, and we're almost there.

**Comment by JoshOrndorff** [comment]
We do have such a label. Leah created it at your asking, @dckc . You can navigate there by hovering the community menu at the top. 

https://blog.rchain.coop/category/community/community-debriefs/

![image](https://user-images.githubusercontent.com/2915325/45847178-32809900-bcf8-11e8-9a94-ccf0924414fd.png)
