### ISSUE TITLE
Quora: Post RChain documents on Quora blog

### ISSUE THREAD

**Issue by JUANITA-MAYBEL** [rchain/bounties#906]
### Benefit to RChain
Quora is one of the popular quest for knowledge platform / community (a place to gain & share knowledge. From statistics, it has above 100 million users monthly. The post will enlighten members on the new emergent Blockchain platform, Rholang and RChain beginners guide on how to join the community.

**6 Posts on Quora blog;**

[Start coding in Rholang now](https://rchaincooperative.quora.com/Start-coding-in-Rholang-today)

[Correct-by-construction Casper
](https://rchaincooperative.quora.com/Correct-by-construction-Casper)
[Building a new blockchain without reinventing the wheel
](https://rchaincooperative.quora.com/Building-a-new-Blockchain-Without-Reinventing-the-Wheel-Part-1)
[RNode v0.4.1 Introduces sending smart contracts across the network
](https://rchaincooperative.quora.com/RNode-v0-4-1-introduces-sending-Rholang-smart-contracts-across-the-network-1)
[The release RNode (v0.5.1)
](https://rchaincooperative.quora.com/The-Realease-of-RNode-v0-5-1)
[Running RNode (0.5.1) with Docker
](https://rchaincooperative.quora.com/Running-RNode-v-0-5-1-with-Docker)
### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[300]**

**Comment by owans** [comment]
This is quite extensive,and would serve as a   motivation to learn rholang. Good one

**Comment by PatrickM727** [comment]
It any be more beneficial for SEO and for our organizations goals to simply direct traffic to the actual blog post

maybe put a blurb on quora with a call to action for "full post here"

we dont want to take traffic away from the blog we want to drive traffic to the blog

thank you

**Comment by JUANITA-MAYBEL** [comment]
Thank you very much, I understand very clearly. I will review each post and create a blurb.

**Comment by pmoorman** [comment]
@JUANITA-MAYBEL in line with the comments from @patrickM727 above, could you please give clearer credit to the tasks here. It's simple X-posting of content from the blog to Quora, which might or might not turn out beneficial. 

As per Patrick's request, it would be good to either create blurbs that link back to us, or at least clearly say that the article is an X-post, and refer back to the canonical source on the RChain Blog!

**Due to this nature, I wouldn't want to vote budget for this issue now.**  Please fix the above, and let us know when that's done.

**Comment by AyAyRon-P** [comment]
@JUANITA-MAYBEL are there any updates to this? So looking at this and following @pmoorman on this issue, all that I can see you've done is post pre-existing articles from the RChain Blog. Please create commentary on the article or some type of value-added statement. In it's current state I don't see $300 value in posting someone else's work. Something like this would be worth 1-hour of time: $40.
