### ISSUE TITLE
Rcon3 Social Media Pack

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#908]
RCON3 Takes Over Berlin for Blockchain Week Social Media Pack - a series of animated videos to excite ,promote & market the Rcon3 event across the various platforms etc

Estimated Budget of Task:_ $[800]
Estimated Timeline Required to Complete the Task:_ [5-8 -work in progress]
How will we measure completion?_ [Video Link submitted / original video transferred directly]

    

- [x] create graphic elements ,material, audio backing track options
 - [x] import,arrange into project timeline, compose edit , color grade etc
 - [x] generate title effects, transition effects and dubb/mix backing
- [x] post production and direct handover to marketing dep.

**Comment by owans** [comment]
Can't wait to see this! Good one @cryptovideos

**Comment by decentralizebanksy** [comment]
The drafts look AMAZING!

**Comment by casanwugo** [comment]
@cryptovideos & @decentralizebanksy. Awesome!

**Comment by pmoorman** [comment]
@Cryptovideos if you want us (bounty org) to vote budgets for this, could you post the videos here? 
That way, it would be easier to justify voting the budgets! 😄 

Also, since it looks like this work is done, can you close the issue?

**Comment by Cryptovideos** [comment]
Thank you yes will do

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Cryptovideos** [comment]
https://youtu.be/4s6OKc0tZrM
https://youtu.be/2ynclnDPjMk
https://youtu.be/3px8MqcrNUY
https://youtu.be/K7fJMiQsyg4
https://youtu.be/HlDKrE1Lw_A
https://youtu.be/3NRCDrkWlAw
https://youtu.be/bUwbndyFpVM
