### ISSUE TITLE
Promote RCON3 Promo Video and FB Event Page

### ISSUE THREAD

**Issue by decentralizebanksy** [rchain/bounties#911]
**Engage with RChain Posts (ie Like, Comment, Share, Heart, Reply, Retweet, Upvote, etc)**

- Use the hashtags #RCON3, #BlockchainWeekBerlin, & #RChain
- Tweet with youtube video and fb event 
https://twitter.com/rchain_coop/status/1030521267932332032 
https://twitter.com/rchain_coop/status/1030522053693190144
- Facebook Post with video & fb event (_INVITE YOUR BLOCKCHAIN COLLEAGUES AND FRIENDS_)
FB event http://bit.ly/RCON3_FBevent
FB post https://www.facebook.com/rchaincooperative/posts/455641991510172
- Linkedin Post with video & fb event
https://www.linkedin.com/feed/update/urn:li:activity:6436298946372464640
- Reddit with video and fb event
https://www.reddit.com/r/RChain/comments/983pf4/rcon3_video_rchain_testnet_launch_in_berlin/  
https://www.reddit.com/r/RChain/comments/983qhg/rsvp_to_the_rcon3_fb_event_page/ 

**Shared Generator Links**

- Click the prefilled tweet links available below, the after you completed the tweet reply to your own tweet with 
“RSVP to the #RCON3 - #RChain #Developer’s Conference FB event and invite all your #blockchain friends http://bit.ly/RCON3_FBevent_TWTR”

- Tweets

I’m going to #RCON3! http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #Berlin #BlockchainWeekBerlin #FightToMercury

Pre-filled Tweet → https://twitter.com/home?status=I%E2%80%99m%20going%20to%20%23RCON3!%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%0A%0A%23BlockchainWeek%20%23Berlin%20%23BlockchainWeekBerlin%20%23FightToMercury 

I’m going to #RCON3 in #Berlin! http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #BlockchainWeekBerlin #FightToMercury

Prefilled Tweet →  https://twitter.com/home?status=I%E2%80%99m%20going%20to%20%23RCON3%20in%20%23Berlin!%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23BlockchainWeekBerlin%20%23FightToMercury 

I’m going to #RCON3 in #Berlin, #Germany! http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #BlockchainWeekBerlin #FightToMercury

Prefilled Tweet → https://twitter.com/home?status=I%E2%80%99m%20going%20to%20%23RCON3%20in%20%23Berlin,%20%23Germany!%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23BlockchainWeekBerlin%20%23FightToMercury 

I am pumped to go to #RCON3! http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #BlockchainWeekBerlin #FightToMercury

Prefilled Tweet → https://twitter.com/home?status=I%20am%20pumped%20to%20go%20to%20%23RCON3!%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23BlockchainWeekBerlin%20%23FightToMercury 

Join me at #RCON3 during #BlockchainWeekBerlin  http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #Berlin #FightToMercury

Prefilled Tweet → https://twitter.com/home?status=Join%20me%20at%20%23RCON3%20during%20%23BlockchainWeekBerlin%20%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23Berlin%20%23FightToMercury 

Will you be at #BlockchainWeekBerlin? Come to #RCON3!  http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #FightToMercury #RChain

Prefilled Tweet → https://twitter.com/home?status=Will%20you%20be%20at%20%23BlockchainWeekBerlin?%20Come%20to%20%23RCON3!%20%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23FightToMercury%20%23RChain 

Where will you be during #BlockchainWeekBerlin? I’ll be at #RCON3! http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #FightToMercury #RChain #Berlin

Prefilled Tweet → https://twitter.com/home?status=Where%20will%20you%20be%20during%20%23BlockchainWeekBerlin?%20I%E2%80%99ll%20be%20at%20%23RCON3!%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23FightToMercury%20%23RChain%20%23Berlin 

I have #RChain fever and the only remedy is #RCON3 http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #FightToMercury #BlockchainWeekBerlin #Berlin

Prefilled Tweet → https://twitter.com/home?status=I%20have%20%23RChain%20fever%20and%20the%20only%20remedy%20is%20%23RCON3%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23FightToMercury%20%23BlockchainWeekBerlin%20%23Berlin 

Let’s start our #BlockchainWeekBerlin journey together at #RCON3! http://bit.ly/RCON3_Video_TWTR #BlockchainWeek #FightToMercury #RChain

Prefilled Tweet → https://twitter.com/home?status=Let%E2%80%99s%20start%20our%20%23BlockchainWeekBerlin%20journey%20together%20at%20%23RCON3!%20%0A%0Ahttp%3A//bit.ly/RCON3_Video_TWTR%20%0A%0A%23BlockchainWeek%20%23FightToMercury%20%23RChain 

**Share on other platforms using the links in the section below. You have the option of drafting your own message or simply sharing the platform dependent posts in the engagement section above**

- Subbreddits
- Facebook Groups
- Linkedin Groups
- Forums

**UTM Tagged Short Links**

Facebook Event

- Facebook http://bit.ly/RCON3_FBevent 
- Twitter http://bit.ly/RCON3_FBevent_TWTR 
- LinkedIn http://bit.ly/RCON3_FBevent_LI 
- Reddit https://www.facebook.com/events/223749521610549/?utm_source=Reddit&utm_medium=Social&utm_campaign=RCON3_FBevent 

YouTube Video 
- Facebook http://bit.ly/RCON3_PromoVideo_FB 
- Twitter http://bit.ly/RCON3_Video_TWTR 
- LinkedIn http://bit.ly/RCON3_PromoVideo_LI 
- Reddit https://www.youtube.com/watch?v=VddnHD6LbFA&utm_source=Reddit&utm_medium=Social&utm_campaign=RCON3_Video 

RCON3 Conference Page
- Facebook http://bit.ly/RCON3_FB 
- Twitter http://bit.ly/RCON3_TWTR 
- LinkedIn http://bit.ly/RCON3_LI 
- Reddit https://developer.rchain.coop/conference?utm_source=Reddit&utm_medium=Social&utm_campaign=RCON3

**Comment by kaka56** [comment]
This is a nice video am doing publishing right away

**Comment by Keaycee** [comment]
Good job. I'm gonna create the awareness on all my links.

**Comment by nonnykul** [comment]
Good, The publicity for Rcon3 Conference his here.
Are you ready? 
[Twitter](
https://twitter.com/Nonso16800881/status/1030665441788743680?s=08)
[Fb event](https://m.facebook.com/story.php?story_fbid=1827564597279879&id=100000790690705&_rdr)
[Fb post](https://m.facebook.com/story.php?story_fbid=1827604787275860&id=100000790690705&refid=52&__tn__=C-R)
[LinkedIn] (https://www.linkedin.com/in/nonso-nwosu-a21715164/recent-activity/)
[Reddit](https://www.reddit.com/r/RChain/comments/983pf4/rcon3_video_rchain_testnet_launch_in_berlin/) video
[Reddit](https://www.reddit.com/user/nonnykul/comments/9864oo/rcon3_conference/?utm_source=reddit-android) Fb page

**Comment by kaka56** [comment]
[Linkedln](https://www.linkedin.com/feed/update/urn:li:activity:6436335861192884224) video
[Linkedln](https://www.linkedin.com/feed/update/urn:li:activity:6436337603913621504)Fb page
[Fb post](https://www.linkedin.com/feed/update/urn:li:activity:6436335861192884224)
[Twitter](https://twitter.com/kgo4life/status/1030571739275780098)

**Comment by BelovedAquila** [comment]
Publishing on my networks : LinkedIn, Twitter and Facebook

**Comment by kitblake** [comment]
Thanks for posting this engage request @decentralizebanksy. In order to be proper we need to create SMART issues with a budget and objective. You did make it SMART (Specific, Measurable, Achievable, Realistic, Timely) but we need the following:

_Estimated Budget of Task:_ **$400**
_Estimated Timeline Required to Complete the Task:_ **1 day / half an hour per person**
_How will we measure completion?_ **Post reference links when done**

I've filled in some values, feel free to adjust.

**Comment by cindyfunzi** [comment]
nice one @Cryptovideos

**Comment by ogini1** [comment]
Awesome, promoting RCon3 conference now on
Twitter 
LinkedIn 
Facebook

**Comment by ogini1** [comment]
Psyched, promoting it on my network 
[Twitter](https://twitter.com/AttitudeOgini/status/1033263392587427840?s=08)
[facebook](https://m.facebook.com/story.php?story_fbid=2042288916010595&id=100006885190401)
[LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6436298946372464640)

**Comment by AyAyRon-P** [comment]
Hi @decentralizebanksy 

Right now I see a total of 7 participants who would receive .5hr rate equivalent to $20 for posting to their pages based on @kitblake 's recommendation. 

Is this issue completed since promoting now is past it's effective date?

**Comment by dckc** [comment]
rewarded in 201808
