### ISSUE TITLE
How to use RNode (video)

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#913]
how to use RNode - in this video, We'll discuss how to do the following : 
1. Running rholang code
2. Connecting to other network nodes
3. Becoming a validator

The video is broken into 6 sections 

Estimated Budget of Task:_ [$1100]
Estimated Timeline Required to Complete the Task:_ [5-8 -work in progress]
How will we measure completion?_ [Video Link submitted / original video transferred directly]
WORKLOAD:
Create the intro and outro for the mini series : Retrieve the and edit in the HD screen capture supplied as is, cut,edit and fine tune the sections into a project timeline, integrate new voice-over and audio backing track, hand over for inspection before official upload after approval

**Comment by Cryptovideos** [comment]
@JoshOrndorff https://youtu.be/8AMXNzAPi9I

**Comment by dckc** [comment]
rewarded in 201808
