### ISSUE TITLE
20180831 Label Guides Meeting

### ISSUE THREAD

**Issue by David405** [rchain/bounties#921]
**Label Guides Meeting for August pay period**

Meeting Agenda https://docs.google.com/document/d/1gvv5bVeZjxjXmEuF4HOl1AT4C9kmkDzZwd--Qpa8yZI/edit#

**All label guides and other collaborators are free to edit and add agenda to the document**

_Estimated Budget of Task:_ **$[000]**
_Estimated Timeline Required to Complete the Task:_ **[One week]**
_How will we measure completion?_ **[Agenda prepared, minutes are taken and the meeting is done]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by TrenchFloat** [comment]
What issue started the interest in this meeting? A blank agenda and a note that says "please add agenda items" makes me wonder if it's worth attending.

**Comment by David405** [comment]
@TrenchFloat I am sure you were aware of the Label Guides meeting arrangement from 20180815 and 20180822 RAM meeting, you took the minutes notes. I am certain the agenda items will be full before 20180831, I only created this early so people can add to the agenda what they feel should be discussed. Also, it is not mandatory for you to attend.

**Comment by TrenchFloat** [comment]
The purpose of this meeting was unclear even during those RAM meetings - anyways, shouldn't the main purpose be here or at least in the agenda?

**Comment by dckc** [comment]
dup of #925
