### ISSUE TITLE
review of August pay period (201808) rewards by TAC + guides

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#925]
Let's have another TAC + Guides meeting. _much like  #847, #809, #759_

 - when: Fri, Aug 31 11am Seattle time ([corresponding times elsewhere](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20180831T1800))
 - where: Zoom Room https://zoom.us/j/318506349.
 - what: review of August rewards; input to the agenda is welcome
   - cite this issue from another issue to put that issue on the agenda, and/or
   - add an issue to the [meeting notes](https://docs.google.com/document/d/1gvv5bVeZjxjXmEuF4HOl1AT4C9kmkDzZwd--Qpa8yZI/edit#)
 - who: TAC, label guides, any other interested parties

[Guides from each area](https://github.com/rchain/bounties/labels?sort=count-desc), please check the box when you're done with budgets and rewards for 201808:

 - [x] Operations: @TrenchFloat, @jimscarver
 - [x] Marketing: @pmoorman @AyAyRon-P @kitblake
   - separate budget: #817
 - [x] Translation: @AyAyRon-P, @pavlos1851
   - separate budget: #869
 - [x] Governance: @jimscarver, @barneycinnamon, @rayzor
 - [x] Development: @dckc, @Jake-Gillberg 
 - [ ] member-site: @PatrickM727 @andrekuipers @kitblake @ian-bloom
 - [x] Community Building: @PatrickM727, @allancto, @Ojimadu 
 - [ ] RChain Technical Literacy: @JoshOrndorff @David405
 - [x] China: @zsluedem
 - [ ] Education: @TrenchFloat
 - [ ] Greeter: @makys @ian-bloom
 - [ ] Events: @Ojimadu
 - [ ] Voting: @Jake-Gillberg @jimscarver @allancto
 - [x] Branding: @pmoorman @AyAyRon-P @kitblake
 - [x] Africa: @David405 
 - [x] Social media: @azazime @jasoncruzzy @Ojimadu 

_Bonus points to anybody who checks the list above to see if it's consistent with the label descriptions and fixes any discrepancies they find._

### Benefit to RChain

align bounty rewards with coop goals

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$2000**
_Estimated Timeline Required to Complete the Task:_ 60hrs? (10 persons * 6hrs)
_How will we measure completion?_  a guide in each area has signaled that budgets and rewards from their area are in order for the month.

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by jasoncruzzy** [comment]
@dckc  I included @Ojimadu to community building and social media label, that should be an update on the guides list.

**Comment by Tonyprisca13** [comment]
@dckc i can help with operation and education if it's ok

**Comment by dckc** [comment]
The normal way I expect people to become guides is:
  1. Do exemplary work in the area
      - earn trust metric certifications
  2. Start doing the work of a guide, in collaboration with anyone already guiding in that area.
      - Build relationships with relevant people in the RChain organization (e.g. @lapin7 for Operations; for Education, I'm not sure... ask @TrenchFloat ).
      - Help align bounty system work with their goals.
  3. Formalize your role as guide by adding yourself to the list of guides in the label description.

@Tonyprisca13 does that make sense? If you mean to say you're ready for step 3, perhaps edit your comment to mention who you are working with and what you have done so far?

@jasoncruzzy did you add @Ojimadu at his request? I'm not sure I understand what's going on. Also, somebody please get @PatrickM727 to confirm that @Ojimadu should be a guide for Community Building (or point me to where he has already done so). As noted in https://github.com/rchain/bounties/issues/914#issuecomment-416683431 , I would really appreciate clarification from @PatrickM727 on how Marketing and Community Building relate.

**Comment by jasoncruzzy** [comment]
@dckc I checked the labels and found @Ojimadu as guide in those label but couldn't see him on same labels in this issue 

> anybody who checks the list above to see if it's consistent with the label descriptions and fixes any discrepancies they find.

**Comment by Tonyprisca13** [comment]
@ viggo need vote for [917 ](https://github.com/rchain/bounties/issues/917)

**Comment by pmoorman** [comment]
@Tonyprisca13 please request such votes in the issue itself, rather than here. Thanks! Btw, it helps to @mention the people that you want/expect to vote on it!

**Comment by Tonyprisca13** [comment]
@pmoorman this issue meant to review payment for this month so i believe anyone with issue regarding vote can also post it here to enable the guide look it and render necessary help or guide needed. @vkhansen is the only one to be rewarded in the issue. Thanks!

**Comment by dckc** [comment]
@Tonyprisca13 if you're saying that issue #917 puts finishing the guide work at-risk for August, then commenting here is in order. But I see that Events guide @Ojimadu and Tech Lit guide @allancto are involved #917 and seem to be having a productive discussion of budget and rewards, so I don't see reason to discuss it here.

**Comment by dckc** [comment]
**Development** looks done, except that @AbnerZheng needs to vote for himself on #881 .

It's starting to look like I should find more back-up on guiding Development work. I don't think I got any help while I was away.

**Comment by dckc** [comment]
## Current pay period is now September

```
insert into pay_period values ('2018-09-01', '2018-09-30', 1, null);
commit;

insert into reward_fixed
(select * from reward where pay_period = '2018-08-01' and reward_usd > 0);

update admin_settings set current_pay_period = '2018-09-01';
commit;
```

This was scheduled to happen before all of the votes today (Sep 9) but I was away due to a family emergency, and we don't yet have anyone else authorized and able to do it (#872).

## Remaining label areas???

If you finished your review, go ahead and check the box in the description of this issue.

If not, what went wrong?

**Comment by pmoorman** [comment]
For `marketing` and `branding` labels all went well this period. Just forgot to check the boxes, but have done that now!

**Comment by dckc** [comment]
I have been standing by for info from guides along the lines of the 20180912 RAM meeting notes:
> Kyle (@TrenchFloat )  will propose the guides post how much/when they communicated with outside sources correlated to their label in #925

You're still more than welcome to share that sort of info here, but I guess we're actually done figuring out the rewards for 201808 so I'm closing this.

**Comment by pmoorman** [comment]
I have been standing by for info from guides along the lines of the 20180912 RAM meeting notes:

@dckc as far as marketing goes: I have been out-of-office for the past 10 days, and @kitblake is out-of-office at the moment till the 30th (damn those Europeans with their holidays!). I haven't spoken with @PatrickM727 or anyone in the marketing org regarding sponsoring.

So that's not much of an update, but maybe better than silence. 

--

A few areas of marketing where I expect we can make progress:

- **Website work** => should be paid out of the marketing budget
- **Onboarding & activation** => I have scheduled a call with @ysgjay about it, and expect to talk with @ian-bloom and @deannald in the future to discuss how to get that funded
- **Asian marketing efforts** => should be running through the yet-to-be-formed RChain Asia efforts (led by the always untaggable Mr. Otter)

I believe those 3 areas to be the most significant pieces of work moving forward. Other areas worth mentioning (where I haven't got good solutions either):

- The excellent work @kitblake has been doing for the marketing org should --surprise, surprise-- probably be funded through the marketing org
- Meetups like the Munich meetup by @rolandkofler and @Jake-Gillberg should be paid out of marketing budget, since there's already a label for that in the marketing plan.

I've just been introduced to Derek Beres, who is the new Director of Content (if I'm not mistaken), and maybe I can talk with him about how content efforts could be funded.
