### ISSUE TITLE
RChain on Bounty-one Forum Report(August) 201808

### ISSUE THREAD

**Issue by jasoncruzzy** [rchain/bounties#931]
BENEFITS TO RCHAIN

RChain on Bountyone Discourse web #778 report for August

2018 I created RChain account on Bounty-one Forum which was approved by the COMMUNITY BUILDING and SOCIAL MEDIA labels to act as a representative(developer) for RChain, sell the RChain ideologies, create RChain awareness amongst developers and possibly on board newdevelopers for RChain.

  STATS FOR AUGUST

1. Contents Generated for RChain on Bounty-one 

* Setting up a local docker network~ [https://talk.bountyone.io/t/setting-up-a-local-docker-network/585?u=rchain_coop](https://talk.bountyone.io/t/setting-up-a-local-docker-network/585?u=rchain_coop)

* Learn Rholang by Example (1)~ [https://talk.bountyone.io/t/learn-rholang-by-example-1/615?u=rchain_coop](https://talk.bountyone.io/t/learn-rholang-by-example-1/615?u=rchain_coop)

* Learn Rholang by Example (2)~[https://talk.bountyone.io/t/learning-rholang-by-example-2/635?u=rchain_coop](https://talk.bountyone.io/t/learning-rholang-by-example-2/635?u=rchain_coop)  

* Notable Enhancements of RNode v0.5.1~[https://talk.bountyone.io/t/notable-enhancements-of-rnode-v0-5-1/650?u=rchain_coop](https://talk.bountyone.io/t/notable-enhancements-of-rnode-v0-5-1/650?u=rchain_coop)

* Running RNode on Amazon AWS (EC2)~[https://talk.bountyone.io/t/running-rnode-on-amazon-aws-ec2/669?u=rchain_coop](https://talk.bountyone.io/t/running-rnode-on-amazon-aws-ec2/669?u=rchain_coop)

* Learn Rholang By Example (3)~[https://talk.bountyone.io/t/learn-rholang-by-example-3/691?u=rchain_coop](https://talk.bountyone.io/t/learn-rholang-by-example-3/691?u=rchain_coop)

*Mainnet! (Scalability and speed)~[https://talk.bountyone.io/t/mainnet-scalability-and-speed/675/3?u=rchain_coop](https://talk.bountyone.io/t/mainnet-scalability-and-speed/675/3?u=rchain_coop)

* Learn Rholang by Example (4)~[https://talk.bountyone.io/t/learn-rholang-by-example-4/738?u=rchain_coop](https://talk.bountyone.io/t/learn-rholang-by-example-4/738?u=rchain_coop)

* RCon3 Testnet Conference (RNode)~[https://talk.bountyone.io/t/rcon3-testnet-rnode/716?u=rchain_coop](https://talk.bountyone.io/t/rcon3-testnet-rnode/716?u=rchain_coop)

*New RNode v0.6.1 supports launch of the RChain Test Net~[https://talk.bountyone.io/t/new-rnode-v0-6-1-supports-launch-of-the-rchain-test-net/759?u=rchain_coop](https://talk.bountyone.io/t/new-rnode-v0-6-1-supports-launch-of-the-rchain-test-net/759?u=rchain_coop)

2. How Many People Read the Topics? 

We had a total number of 564 Developers reading(VIEWS) our topics in the month of August, a significant increase from the months of June and July.

3. Have any of the developers joined RChain?

A member(developer) of the bountyone forum ‘@jackstin’ already joined the official RChain telegram group he introduced himself already and he also join the RChain Community forum. He showed interest in the RChain Cooperative by our topic on bountyone “Mainnet! (Scalability and Speed) see here [https://talk.bountyone.io/t/mainnet-scalability-and-speed/675/2?u=rchain_coop](https://talk.bountyone.io/t/mainnet-scalability-and-speed/675/2?u=rchain_coop)

4. The contents(topic) used are sourced from RChain Approved Documents hence I'm acting as a representative of the RChain Cooperative. The interesting and educating topics besides views have also garned good number of comments from the bountyone forum.

 The RCON 3 Test Net Conference was also promoted in the bountyone forum as one of our topics.

5. What is the goal of topics addressed? 

* The goal of the topics created gives an insight about the RChain Ideologies(Rholang, RNode, RSpace) and to help showcase what the RChain can offer to Blockchain Technology.

6. How have these topics helped built RChain Interest? 

The Bounty-one Forum has helped build the RChain interest because with its platform we have constantly created awareness and provided informations about the RChain. With over 550 developers reading(Views) and learning about RChain ideas(contents), firstly it is a strategic point to enlighten developers about RChain and secondly with consistency we will onboard developers for RChain. 

7. Time spent?

  A total of 4 hours daily in the month of August is dedicated on bountyone reading topics, sourcing contents, replying comments or direct messages.

 Estimated Budget of Task:_ **$[1300]**
 Timeframe: Month of August
 Measure of completion: Statistics

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
> approved by the COMMUNITY BUILDING and SOCIAL MEDIA labels
help us find that approval?

**Comment by jasoncruzzy** [comment]
Great @dckc, I responded to that in #778 

> @dckc I spoke with PatrickM727 about the name and logo, clearly stating the position of RChain on bounty-one forum and also requested to retain the name and logo which he did ACCEPT and commended the job done. He approved of it hence the contents generated are sourced from Approved RChain document on our website or other RChain official channels.

**Comment by pmoorman** [comment]
This issue was hotly debated in the TAC call, where we were lucky enough to have all relevant parties present.

The conclusion from discussion was that in issue like these (where a lot of time is invested, and a retrospective budget is requested), that it is expected for label guides to vote in accordance with "value created for the RChain Coop" rather than in accordance with the work invested by the contractor. 

I see that others have already voted a $1300 budget on this issue for the month, but I have voted $50 in accordance with conclusions from the TAC discussion. $50 because of the exposure created and the 1 Telegram subscriber.

I thought I'll write a comment here to clarify, as it might be unexpected to some (and so this can serve as a signal / clarification to other similar situations, too)

**Comment by jasoncruzzy** [comment]
@pmoorman fI was able to respond to all questions on this issue at TAC meeting and also respond to @dckc on consulting guides for this issue, and they thought it was ok. I was also at the meeting and there was no mention of #50 for over 100hrs of time spent in a month, sourcing contents and including bring in someone via Bountyone, your #50 is totally unjustified as such was not the resolution in the meeting, the least not #50. What's the value of #50 after conversation?, that invariably reflects a no value.

**Comment by jasoncruzzy** [comment]
Thanks @pmoorman 👍👍

**Comment by allancto** [comment]
@jasoncruzzy , @Cryptovideos , @David405 , @casanwugo can you describe why you voted a $1300 budget on this issue? I don't see any guidance on this number. 

Thanks! -@allancto

**Comment by Cryptovideos** [comment]
@allancto ...Iv made a mistake and actually agree with Pmoorman on his logic here on this particular issue. By no means do i mean to under-value / not appreciate / all the work done , however my understanding on this issue is somewhat limited and thus i do not wish to be directly involved.

**Comment by Viraculous** [comment]
@jasoncruzzy, @pmoorman, @allancto, what's the progress or hitch on this issue?

**Comment by dckc** [comment]
@Viraculous thanks for keeping things moving, but note that closing an issue indicates that it's done, unless it's labelled **wontfix** or **invalid** or **needs-SMART-objective**.

**Comment by Viraculous** [comment]
@dckc thanks, I think, I am obliged as a coop member to help push things forward not necessarily as a guide.
