### ISSUE TITLE
ONGOING:August Report for RChain community in China

### ISSUE THREAD

**Issue by zsluedem** [rchain/bounties#934]
### Benefit to RChain

Monthly report for the Rchain community in China.

**Finished** I will finish it in these days.

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*
*Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ) to align your contribution with goals of the RChain cooperative.*
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[TBD]**
_Estimated Timeline Required to Complete the Task:_ **[5days]**
_How will we measure completion?_ **[A complete doc come out]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
@zsluedem @ottermagically any suggestion on rebooting **China** bounties? Are you developing some process that subsumes them? Shall we close them as duplicates? Or shall we arrange a budget structure and sponsorship?

**Comment by dckc** [comment]
In #783, @zsluedem writes:
> @ottermagically and Jocellin are drafting a business plan which includes an bounty program separated from this bounty program.

I see pretty much the same thing In [RChain Asia Weekly Debrief 20180928][1].

Meanwhile, just in case, I certified @ottermagically and @zsluedem to handle any **China** bounties.

[1]: https://docs.google.com/document/d/1ac2-f4JhJoIGyEwordWcVPqWxOCXJ_TmibKfB2uEWNs/edit?ts=5baae596#heading=h.hgmtg3aeilo7

**Comment by dckc** [comment]
I certified @pmoorman too; we made a new **Asia** label and I retired **zz-China**.

**Comment by pmoorman** [comment]
In turn, I also certified @cool007zqw (Enzo)
