### ISSUE TITLE
Translate four debriefs to German (82-85)

### ISSUE THREAD

**Issue by gsofianidis** [rchain/bounties#935]
### Benefit to RChain

Reach a larger audience and help expand the community building.

Translations will be posted both on the [RChain Worldwide Community Forum > German(Deutsch) > Blog (https://rchaincommunity.xyz/c/German-Deutsch/Blog-Blog), the [RChain Cooperative (German)](https://medium.com/@rchain_de) Medium account.

### Budget and Objective

_Estimated Budget of Task:

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@gsofianidis), Proficiency (@amaliasof ), from institution: [University of Michigan](https://www.umich.edu/) (@gsofianidis), , from institution: [University of Michigan](https://www.umich.edu/) (@amaliasof)
       - [x] a track record of quality work on rchain bounties: #737 
       - [ ] another body of work readily available for community review
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

### Original (English) Content

- [RChain Weekly Update (Debrief 84) 4th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-84-4th-july-2018-9768f046b3d0?source=---------2) (786 words, $102.18)
- [RChain Weekly Update (Debrief 85) 11th July, 2018](https://medium.com/rchain-cooperative/rchain-weekly-update-debrief-85-11th-july-2018-57b1e6ab6b9a?source=---------1) (1666 words, $216.58)
- [

**Comment by ddayan** [comment]
I don't think there's a need to translate these to German.

**Comment by dckc** [comment]
It's reasonably clear that we're lacking a critical mass of support for this work. See also https://github.com/rchain/bounties/issues/483#issuecomment-423215054
