### ISSUE TITLE
Translate RChain latest Blog Posts to German

### ISSUE THREAD

**Issue by cindyfunzi** [rchain/bounties#936]
### Benefit to RChain

Reach a larger audience and help expand the community building.

Translated contents will be posted on <a href="https://rchaincommunity.xyz/c/German-Deutsch">RChain Community.xyz-German-Deutsch</a> and Medium blog.

### Budget and Objective

_Estimated Budget of Task:_ **$[ 2390.4 + 239 (10% for markdown conversion) [2629.4] ]**
_Estimated Timeline Required to Complete the Task:_ **[ 3 weeks]**
_How will we measure completion?_ **[Fill the Translated German Section below]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [X] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [X] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [X] several reviewers are involved (_assign the ticket to them_)
    - [X] at least two of them have high proficiency in _the target language_
    - [X] at least two of them have high proficiency in English
    - [X] at least two of them have either
       - [X] formal training: degree / certificate: ___ from institution: _____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [X] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

ENGLISH Content

- [Computational Calculi Primer (Part 1)](https://blog.rchain.coop/computational-calculi-primer/) (1,580 words)

- <a href="http://blog.rchain.coop/computational-calculus-primer-%cf%80-calculus">Computational Calculus Primer: π-calculus (Part 2)</a> (1880 words)

- [Computational Calculus Primer Part 3: ρ-calculus ](https://blog.rchain.coop/calculus-primer-ρ-calculus/) (2648 words)

- <a href="https://blog.rchain.coop/start_coding_in_rholang/">Start coding in Rholang today!</a> (715 words)

- <a href="https://medium.com/rchain-cooperative/rnode-v0-6-1-supports-launch-of-the-rchain-test-net-f6ddcacb4b6">RNode v0.6.1 supports launch of the RChain test net</a> (1308 words)

- <a href="http://blog.rchain.coop/become-a-validator-and-acquire-rhoc-for-staking/">Become a validator and acquire RHOC for staking</a> (911 words)

- <a href="http://blog.rchain.coop/rchain-debrief-90/ ">RChain Debrief 90: RCON3 program released</a> (1381 words)

- [RChain Update (Debrief 91), 24th August 2018](https://blog.rchain.coop/rchain-debrief-91-rnode-v0-6-1-released/) (1091 words)

- <a href="http://blog.rchain.coop/rchain-debrief-92-rcon3-week/">RCHAIN DEBRIEF 92: VALIDATOR ECONOMICS</a> (874 words)

- <a href="https://blog.rchain.coop/intro-to-design-of-computational-calculi-1/">Intro to design of computational calculi 1</a> (1833 words)

- <a href="https://blog.rchain.coop/rsong-the-future-of-music/">RSONG: THE FUTURE OF MUSIC</a> (718 words)

(  A total of 14940 words )

Translated (GERMAN) Contents :
 
- 
- 
- 
- 
- 
- 
- 
- 
- 
- 

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by ddayan** [comment]
I don't think there's a need to translate these to German.

**Comment by azazime** [comment]
@ddayan what are your reasons?

**Comment by ddayan** [comment]
There's no need to translate debriefs, if we start doing that for every language you will end up spending over a million dollars a year just on debrief translations. Also I'm not convinced there's a need to translate technical stuff to German as most educated germans can read English.

@azazime if RChain was your private business would you spend money to make these German translations?

**Comment by azazime** [comment]
@ddayan I think you're missing the point here, firstly Rchain cannot be over publicized regardless of the number of languages and there are a lot of Germans who prefer reading in their native language.
We need more people to see Rchain articles and documents to increase our popularity and that would include translating to German and other languages @ddayan I believe you should study the essence of the  cooperative

**Comment by ddayan** [comment]
Do you have any data that theseGerman translations are needed?
@azazime Do you know what kind of cooperative Rchain is?

**Comment by jasoncruzzy** [comment]
@kdvalentine RChain is a global brand and not an 'English speaking' brand, every part of the world is vital and should be penetrated, any which way to reach out to the world is ok, Translation is very vital, the country hosting the RCon3 test net is Germany and having to translate vital RChain documents to Deutsche is strategic and important 👍👍

**Comment by ddayan** [comment]
@jasoncruzzy  No one stops you from translating. People translate Wikipedia pages without a bounty system all the time.

**Comment by jasoncruzzy** [comment]
@ddayan  I'm not the one translating here, just responding to @kdvalentine comments 👍👍

**Comment by dckc** [comment]
@jasoncruzzy I don't see any support for your claim that translating these documents to German will "Reach a larger audience".

"Translation is very vital" is argument by assertion.

The fact that https://developer.rchain.coop/conference is not available in German shows that the RCon3 organizers disagree that "the country hosting the RCon3 test net is Germany and having to translate vital RChain documents to Deutsche is strategic and important".

Finally, if you're not doing the translating, why did you assign yourself to this ticket?

**Comment by jasoncruzzy** [comment]
@dckc I was only stating my views of translation to @ddayan and I will re-state translating to Germany(deutche) is as important as translating to every other languages already translated in the RChain Bounties.
On this

> Finally, if you're not doing the translating, why did you assign yourself to this ticket?

@cindyfunzi is new to the system and @cindyfunzi  was introduced to the system by me via some of the documents @cindyfunzi read and picked interest in the RChain Cooperative. Assigning myself to this issue is to follow up on @cindyfunzi work and provide support where needed, I also helped her put up the translation label as @cindyfunzi.

**Comment by ddayan** [comment]
"... as important as translating to every other languages already translated..." A great number of former translations were unnecessary as well.

**Comment by cindyfunzi** [comment]
@AyAyAron P... Thanks for the welcome message. I'm a fluent German speaker, currently taking Language courses in the University of Nigeria, Nsukka. I recently joined RChain and really wanted to participate in translations. I had earlier opened a medium account "https://medium.com/@zibbyme" where the translations would be posted. It has a number of German following, and i intend to do more work and grow it much more... There is also a strong notion that German/English natives would prefer to read in German language...and i am sure the likes of @gsofianidis and others here attests to this claim, hence the need for continued German translations...
(@gsofianidis,, Thumbs up to your previous great works on German translations by the way).

I am reviewer of this project along side 2 others offline. 
@jasoncruzzy is collaborator. Would also love  to collaborate with @gsofianidis, but cannot currently assign anyone, as i work toward getting that fixed.

**Comment by cindyfunzi** [comment]
@All... Sorry I mistakenly closed this...

**Comment by ddayan** [comment]
Oh "There is also a strong notion that German/English natives would prefer to read in German language" I didn't think about that. In that case we should start translating as much as we can.

"There are roughly 6,500 spoken languages in the world today. However, about 2,000 of those languages have fewer than 1,000 speakers."

4500 x 3400 = 15300000

To save mass issue clutter could you make this a general translation issue and change the budget to $15,300,000?

**Comment by cindyfunzi** [comment]
Hello,@AyAyRonP thanks for your guidance I have listed off old articles and added some new ones,I would also add my personal commentary or brief summary at the end of each translations as you have advice,thanks

**Comment by luigidemeo** [comment]
has this been cancelled?
