### ISSUE TITLE
Meetup "Formal Verification for Real-World Business", Europe/Ukraine

### ISSUE THREAD

**Issue by golovach-ivan** [rchain/bounties#944]
Hold a meeting "Formal Verification for Real-World Business" for business developers (insurance).

### Benefit to RChain
- grow Russian-speaking community
- develop slides for "meetup in a box" project (#779) 
- publishing video on [youtube channel for 25.000+ developers](https://www.youtube.com/watch?v=TYp4bdLB11w&list=PLoij6udfBncjj9DmzsQB5PJEN6Eo6woHA)

#### Involved
golovach.ivan - 85%
kovmargo - 15%

#### Expenses
Publicity, Banners, Digital graphics $100
Hall renting $100
Camera and associated gadgets renting + video processing $150
Logistics $50
Slides development - golovach.ivan time
Speech/Info preparing - golovach.ivan time
Video processing consultancy,  organization - kov.margo time

_Estimated Budget of Task:_ **$[2000]**
_Estimated Timeline Required to Complete the Task:_ **[1week]**
_How will we measure completion?_ **[processed video uploaded to [Youtube channel](https://www.youtube.com/watch?v=TYp4bdLB11w&list=PLoij6udfBncjj9DmzsQB5PJEN6Eo6woHA) + slides uploaded to #779 ("meetup in the box" issue) google directory**

**Comment by Ojimadu** [comment]
@golovach-ivan Please see the local meet up guide in the wiki and acquaint yourself with it.

**Comment by golovach-ivan** [comment]
Yes, meetup was held in software development company with insuarance specialisation ([Fortifier](https://4tifier.com/)) for management and developers.
- [Video on Youtube Channel with 25k+ IT-subscribers](https://www.youtube.com/watch?v=TIcIZQYAv9g&list=PLoij6udfBncjj9DmzsQB5PJEN6Eo6woHA&index=3).
- [Slides](https://github.com/golovach-ivan/Computational-Calculi/blob/master/slides/Formal_Verification_for_Reallife_Business.pdf).
Please vote for it.

**Comment by AyAyRon-P** [comment]
@golovach-ivan @kovmargo 

Would you all please post these in the LOCAL MEETUP SERVER under the  https://discord.gg/mn4JwMW Europe channel?

**Comment by dckc** [comment]
I see rewards were issued in the 201808 pay period.

**Comment by Ojimadu** [comment]
@golovach-ivan Please on subsequent issues create the issue like a week prior to the event and not after the event has been held. Also have a look the [local meet up program](https://github.com/rchain/bounties/wiki/local-meetup-program:-summary) and acquaint yourself with it.
