### ISSUE TITLE
Rchain Bounty App Tutorial Video

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#947]
in the last video (#854 ) we gave an overview of the Membership Signup procedure and walk-through. In this next video we introduce how you to navigate and make use of the new and improved Bounty App

    Develop the Script for the Voice Over,
    Grab screenshots for steps in script
    Record and edit the Voice over in studio
    add special effects and highlight areas
    Import all elements, audio and compositions into the timeline for main editing & post production
    Handover of final video and loading to Youtube for link sharing etc etc

Estimated Budget : 1900$.... "this is not a fixed rate" 
Estimated Timeline Required to Complete the Task: Work in Progress to be delivered end of month.
improvements will be delivered continuously, budget estimate is for july work. A project backup will be executed for future tweaks and updates the the main working project file.

**Comment by nonnykul** [comment]
I am psyched about this video, it would go a long way to help newbies.

**Comment by buka4chocksy** [comment]
Great video to simplify the bounty app user process

**Comment by owans** [comment]
Great work, simplifies the process for beginners.

**Comment by Tonyprisca13** [comment]
Good work! Very useful.

**Comment by Cryptovideos** [comment]
Apologies....issue already is open in #854...closing this

**Comment by Cryptovideos** [comment]
Guys - sorry about the confusion here - this is in fact a new video NOT lasy months 854 RChain Membership Signup Explainer Video wisch was completed, uploaded and closed thereafter.

**Comment by pmoorman** [comment]
For the sake of clarity on labels, I'll remove the label `marketing` from this issue, as it's not related to marketing (= getting DApps and developers onboard the RChain platform), but rather something like `operations` (which I'll apply instead)

**Comment by Cryptovideos** [comment]
Yes i see thank you for that

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dckc** [comment]
It's not clear to me why this was closed. My best guess is that you decided not to do it after all.

In any case, I don't think we have support for promoting the bounty system:

> The board doesn't want to promote the Bounty System until improvements are implemented. -- @kitblake Aug 21 https://github.com/rchain/bounties/issues/595#issuecomment-414626360

**Comment by Cryptovideos** [comment]
Hey Dan appreciate you commenting here...in all honesty i was discouraged after creating this issue...got some negative feedback and decided against it..all good...thank you again Dan


Sent from my Samsung Galaxy smartphone.


-------- Original message --------
