### ISSUE TITLE
Translate Debrief 92, 93 and Intro to design of computational calculi -1 and RSong: the Future of Music - Russian

### ISSUE THREAD

**Issue by qelentium** [rchain/bounties#948]
### Benefit to RChain

Reach larger audience and help to build the community 
Translation will be posted at [RChain Worldwide Community Forum](https://rchaincommunity.xyz/) and at [Medium RChain_RU](https://medium.com/@rchain_ru)

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[503.63 (457.93+10% $45.7 for Markdown conversion) ]**
_Estimated Timeline Required to Complete the Task:_ **[10 days]**
_How will we measure completion?_ **[Will be posted at [RChain Worldwide Community Forum](https://rchaincommunity.xyz/) and at [Medium RChain_RU](https://medium.com/@rchain_ru)]**

*See CONTRIBUTING.md for details on budget and reward process.*
@qelentium : 
@kovmargo : 

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in Russian
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: Native Language speakers and diploma from Russian Embassy School in Athens
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: 

**Original (English) Content**
- [RCHAIN DEBRIEF 92: VALIDATOR ECONOMICS](https://blog.rchain.coop/rchain-debrief-92-rcon3-week/)  870 Words

- [INTRO TO DESIGN OF COMPUTATIONAL CALCULI 1](https://blog.rchain.coop/intro-to-design-of-computational-calculi-1/)  1,756 Words

- [RSONG: THE FUTURE OF MUSIC](https://blog.rchain.coop/rsong-the-future-of-music/) 716 Words $93.08

- [RCHAIN DEBRIEF 93: RCON3](https://blog.rchain.coop/rchain-debrief-93-rcon3/) 175 Words

**Translated (Russian) Content**
- [RCHAIN ​​ДЕБРИФ 92: ЭКОНОМИКА ВАЛИДАТОРА](https://medium.com/@rchain_ru/rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%84-92-%D1%8D%D0%BA%D0%BE%D0%BD%D0%BE%D0%BC%D0%B8%D0%BA%D0%B0-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D1%80%D0%B0-35056bce3841)
- [ВСТУПЛЕНИЕ К ПРОЕКТИРОВАНИЮ ВЫЧИСЛИТЕЛЬНОГО ИСЧИСЛЕНИЯ 1](https://medium.com/@rchain_ru/%D0%B2%D1%81%D1%82%D1%83%D0%BF%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8E-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B8%D1%81%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-1-5c48989fab56)
- [RSONG:БУДУЩЕЕ МУЗЫКИ](https://medium.com/@rchain_ru/rsong-%D0%B1%D1%83%D0%B4%D1%83%D1%89%D0%B5%D0%B5-%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B8-9142e8e64b86)
- [RCHAIN ДЕБРИФ 93: RCON3](https://medium.com/@rchain_ru/rchain-%D0%B4%D0%B5%D0%B1%D1%80%D0%B8%D1%84-93-rcon3-1dc4f4fdb6f4)

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by qelentium** [comment]
Translated.Posted.Reviewed.Closing this issue.

**Comment by AyAyRon-P** [comment]
Please let myself or one of the two guides close this out so we can be sure to vote on it at the end of the month. We had missed a few that had closed without voting on them or being able to give feedback. Thanks @qelentium!

**Comment by qelentium** [comment]
@AyAyRon-P Of couse! 👍

**Comment by dckc** [comment]
We're re-evaluating return on investment in the bounty system; in particular, regarding Translation, see https://github.com/rchain/bounties/issues/483#issuecomment-423215054

@qelentium what are the major Russian language outlets for cryptocurrency and decentralized systems news?

**Comment by qelentium** [comment]
@dckc habr.com vk.com t.me bits.media

**Comment by dckc** [comment]
Have you ever posted on those sites? Can you reach those audiences?

**Comment by qelentium** [comment]
Yes we tried with the team to post on habr and vk.com (this is still in process).For some reason, users do not want to joint t.me group for discussion

**Comment by dckc** [comment]
Good to know reaching the habr and vk.com audiences is in progress.

I'm not sure who "the team" refers to. Care to clarify?

Likewise t.me... that's telegram, right? How is that relevant?

**Comment by qelentium** [comment]
@dckc by saying the term "team" i mean people, whose knows russian language and with whose we are contacting with. Some of the posts did @Barkov-F  other's were done by @golovach-ivan . And about telegram, we made a russian speaking group there, i was trying to reach people to join that chat for months and only few joined.
