### ISSUE TITLE
Translate RChain Debrief 92, 93, Rsong (music), Testnet, Update 94, Rholang to Ukrainian

### ISSUE THREAD

**Issue by kovmargo** [rchain/bounties#950]
Translation of the RChain hot topics to other languages means good global marketing: reach a larger audience and help expand the community building.

### Budget and Objective
**Collaborators Work:**
@kovmargo: 90%
@golovach-ivan: 10%

**Estimated Budget of Task: **

Estimated Timeline Required to Complete the Task: **20** 
How will we measure completion? **Fill the Translated Content section below. Also, translations will be posted on the RChain Worldwide Community Forum (Russian), the RChain Cooperative Medium account(Russian), Facebook.**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 

  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language (Russian)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@kovmargo) from institution: [European University](https://e-u.in.ua/ua/) (international diploma)
       - [x] a track record of quality work on rchain bounties: #863 
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [] our plan to keep the translation up to date is:

Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)

**Original (English) Content:**
[RHOLANG VS. THE DINING PHILOSOPHERS](https://blog.rchain.coop/rholang-vs-the-dining-philosophers/)
[RCHAIN UPDATE 94: FEEDBACK FROM RCON3](https://blog.rchain.coop/rchain-update-94-feedback-from-rcon3/)
[RCHAIN TEST NET GENESIS CEREMONY](https://blog.rchain.coop/rchain-testnet-genesis-ceremony/)
[RCHAIN DEBRIEF 93: RCON3 ](https://blog.rchain.coop/rchain-debrief-93-rcon3/)
[RSONG: THE FUTURE OF MUSIC](https://blog.rchain.coop/rsong-the-future-of-music/)
[INTRO TO DESIGN OF COMPUTATIONAL CALCULI 1](https://blog.rchain.coop/intro-to-design-of-computational-calculi-1/)
[RCHAIN DEBRIEF 92: VALIDATOR ECONOMICS](https://blog.rchain.coop/rchain-debrief-92-rcon3-week/)

**Comment by jplepel** [comment]
Is there a market for Ukrainian translations? Where are these translations posted after completion?

**Comment by allancto** [comment]
@jasoncruzzy you talked about doing something with SEO/ google analytics. Do you think that might be useful helping @kovmargo and @jplepel figure out whether this article will have an impact or whether previous translations like this have? I think @ICA3DaR5 has some experience with setting seo tags and such, and google analytics as well, at least in the context of RUB.

**Comment by luigidemeo** [comment]
Don't think there is a market for this

**Comment by Viraculous** [comment]
Secondly, I see no upfront budget for the issue.

**Comment by Viraculous** [comment]
@kovmargo you have not responded to any of the comment. Please see my comment in #960. There is no audience for translations in Ukraine and no marketing efforts around it. I suggest you suspend the translation and see the concerns around it on the issue i mentioned myself.
