### ISSUE TITLE
Translate 5 blog posts to Greek (September)

### ISSUE THREAD

**Issue by zero-andreou** [rchain/bounties#955]
### Benefit to RChain

Reach a larger audience and help expand the community building.

Translations will be posted both on the [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο)](https://rchaincommunity.xyz/c/Greek-%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC/Blog-%CE%99%CF%83%CF%84%CE%BF%CE%BB%CF%8C%CE%B3%CE%B9%CE%BF), the [RChain Cooperative (Greek)](https://medium.com/@rchain_el/latest) and Medium account.

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$561.03 + ($561.03 * 10% = $56.10) = $[617.13]**
_Estimated Timeline Required to Complete the Task:_ **[24 days]**
_How will we measure completion?_ **[Translations will be posted on the [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο)](https://rchaincommunity.xyz/c/Greek-%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC/Blog-%CE%99%CF%83%CF%84%CE%BF%CE%BB%CF%8C%CE%B3%CE%B9%CE%BF) and the [RChain Cooperative (Greek)](https://medium.com/@rchain_el/latest) Medium account.]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in Greek
    - [x] at least two of them have high proficiency in English
   - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@ICA3DaR5), Proficiency (@zero-andreou), Lower (@zero-andreou) from institution: [University of Michigan](https://www.umich.edu/) (@ICA3DaR5), [Edexcel](https://qualifications.pearson.com/en/home.html) (@zero-andreou), [Cambridge University](https://www.cam.ac.uk/) (@zero-andreou)
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #497, #540, #585, #586, #597, #621, #650, #652, #686, #688, #715, #719, #721, #738, #757, #842, #859, #905, #923 
       - [x] another body of work readily available for community review: [decred/dcrdocs](https://github.com/decred/dcrdocs/tree/master/src/i18n/el)
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

### Original (English) Content

- [RCHAIN DEBRIEF 92: VALIDATOR ECONOMICS](https://blog.rchain.coop/rchain-debrief-92-rcon3-week/) (860 words, $111.80)
- [INTRO TO DESIGN OF COMPUTATIONAL CALCULI 1](https://blog.rchain.coop/intro-to-design-of-computational-calculi-1/) (1,760 words, $228.80)
- [RSONG: THE FUTURE OF MUSIC](https://blog.rchain.coop/rsong-the-future-of-music/) (716 words, $93.08)
- [RChain Debrief 93: RCon3](https://blog.rchain.coop/rchain-debrief-93-rcon3/) (187 words, $24.31)
- [RChain test net genesis ceremony](https://blog.rchain.coop/rchain-testnet-genesis-ceremony/) (644 words, $103.04)

### Translated (Greek) Content
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > RChain Debrief 92: Οικονομικά Επικυρωτών](https://rchaincommunity.xyz/t/rchain-debrief-92/493)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Εισαγωγή στο σχεδιασμό υπολογιστικών λογισμών 1](https://rchaincommunity.xyz/t/topic/502)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > RSong: Το Μέλλον της Μουσικής](https://rchaincommunity.xyz/t/rsong/503)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > RChain Debrief 93: RCon3](https://rchaincommunity.xyz/t/rchain-debrief-93-rcon3/504)
- [RChain Worldwide Community Forum > Greek (Ελληνικά) > Blog (Ιστολόγιο) > Τελετή γένεσης δοκιμαστικού δικτύου του RChain](https://rchaincommunity.xyz/t/rchain/517)

- [RChain Debrief 92: Οικονομικά Επικυρωτών](https://medium.com/@rchain_el/rchain-debrief-92-%CE%BF%CE%B9%CE%BA%CE%BF%CE%BD%CE%BF%CE%BC%CE%B9%CE%BA%CE%AC-%CE%B5%CF%80%CE%B9%CE%BA%CF%85%CF%81%CF%89%CF%84%CF%8E%CE%BD-3d56d24f2b9f)
- [Εισαγωγή στο σχεδιασμό υπολογιστικών λογισμών 1](https://medium.com/@rchain_el/%CE%B5%CE%B9%CF%83%CE%B1%CE%B3%CF%89%CE%B3%CE%AE-%CF%83%CF%84%CE%BF-%CF%83%CF%87%CE%B5%CE%B4%CE%B9%CE%B1%CF%83%CE%BC%CF%8C-%CF%85%CF%80%CE%BF%CE%BB%CE%BF%CE%B3%CE%B9%CF%83%CF%84%CE%B9%CE%BA%CF%8E%CE%BD-%CE%BB%CE%BF%CE%B3%CE%B9%CF%83%CE%BC%CF%8E%CE%BD-1-c45bafd52193)
- [RSong: Το Μέλλον της Μουσικής](https://medium.com/@rchain_el/rsong-%CF%84%CE%BF-%CE%BC%CE%AD%CE%BB%CE%BB%CE%BF%CE%BD-%CF%84%CE%B7%CF%82-%CE%BC%CE%BF%CF%85%CF%83%CE%B9%CE%BA%CE%AE%CF%82-1fbc5abbdc24)
- [RChain Debrief 93: RCon3](https://medium.com/@rchain_el/rchain-debrief-93-rcon3-226ffa7bc68a)
- [Τελετή γένεσης δοκιμαστικού δικτύου του RChain](https://medium.com/@rchain_el/%CF%84%CE%B5%CE%BB%CE%B5%CF%84%CE%AE-%CE%B3%CE%AD%CE%BD%CE%B5%CF%83%CE%B7%CF%82-%CE%B4%CE%BF%CE%BA%CE%B9%CE%BC%CE%B1%CF%83%CF%84%CE%B9%CE%BA%CE%BF%CF%8D-%CE%B4%CE%B9%CE%BA%CF%84%CF%8D%CE%BF%CF%85-%CF%84%CE%BF%CF%85-rchain-ed798bfc2c5b)

**Comment by jplepel** [comment]
Is there a market for Greek translations? Where are these translations posted after completion?

**Comment by jplepel** [comment]
@zero-andreou Can you provide metrics on your past translations?

**Comment by zero-andreou** [comment]
@jplepel We will provide the metrics for the translations and the forum by the end of the month.

**Comment by jplepel** [comment]
@zero-andreou I'd like to see metrics on prior translations for the month of august. There needs to be a proven market and demand for greek translations. In the loomio poll 5months ago, greek finished 9th. 

In 2012, 51% of people in Greece can speak English. While that number is not very high, I'm assuming the % of people that are tech literate know English well. I am open to be proven wrong.

**Comment by zero-andreou** [comment]
@jplepel The country had an economic crisis for the past several years which led to  English illiteracy in the young population. You are right about the current metrics but don't forget that RChain is fairly new and hasn't released its main net yet. In my opinion the translations have a timeless value and they are going to be read in the future more than they are read now, especially when RChain releases its main net abd forward.

**Comment by jplepel** [comment]
https://translate.google.com/translate?sl=auto&tl=el&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fblog.rchain.coop%2Frchain-debrief-93-rcon3%2F&edit-text=&act=url

Using google translate is sufficient for blog posts.

**Comment by ysgjay** [comment]
Why was this reopened?
