### ISSUE TITLE
Translate 'RChain test net genesis ceremony; Update 94', Rholang  to Russian

### ISSUE THREAD

**Issue by kovmargo** [rchain/bounties#959]
Translation of the RChain hot topics to other languages means good global marketing: reach a larger audience and help expand the community building.

### Budget and Objective
**Collaborators Work:**
@kovmargo: 90%
@golovach-ivan: 10%
@qelentium: 10%

**Estimated Budget of Task: **

Estimated Timeline Required to Complete the Task: **7** 
How will we measure completion? **Fill the Translated Content section below. Also, translations will be posted on the RChain Worldwide Community Forum (Russian), the RChain Cooperative Medium account(Russian), Facebook.**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

Translation Checklist

  - Why translate this document?
    - It's important to translate because ____
    - [x] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 

  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language (Russian)
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@kovmargo) from institution: [European University](https://e-u.in.ua/ua/) (international diploma)
       - [x] a track record of quality work on rchain bounties: #863 
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [] our plan to keep the translation up to date is:

Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)

**Original (English) Content:**
[RHOLANG VS. THE DINING PHILOSOPHERS](https://blog.rchain.coop/rholang-vs-the-dining-philosophers/)
[RCHAIN UPDATE 94: FEEDBACK FROM RCON3](https://blog.rchain.coop/rchain-update-94-feedback-from-rcon3/)
[RCHAIN TEST NET GENESIS CEREMONY](https://blog.rchain.coop/rchain-testnet-genesis-ceremony/)

**Comment by jplepel** [comment]
I suggest putting this translation on hold before beginning work. The members are discussing weather these types of translations are a good use of the co-ops budget.

**Comment by AyAyRon-P** [comment]
Translations are suspended indefinitely please see #783 

cc @pavlos1851 @zsluedem @Viraculous

**Comment by kovmargo** [comment]
Sorry guys for delay with responce, was out of town...  From the #960 I fully understand the necessity of suspending translation issues. 

BUT, now we (I and @golovach-ivan) are going to create the Russian-speaking RChain community in Ukraine in the way like Chinese did.  

Every month we already are holding an 1-2 mettups that include SMART TOPICS such us #821, #822, #944 (number of views more than 2000 - publishing video [on youtube channel](https://www.youtube.com/watch?v=TYp4bdLB11w&list=PLoij6udfBncjj9DmzsQB5PJEN6Eo6woHA) for 25.000+ developers), not only telling about RChain coop and bounty programm. We had  8 people on 1st meetup and around 30 on the last mettup locally,  and we are going to increase this amount by promotions.  The futher translation will help us to involve developers and mathematicians to RChain Coop via [Habr](https://habr.com/), [DOU](https://dou.ua/) - the biggest Russian-speaking channels. We also plans to create own channel on Discord (now we communicate through Skype)

I would like to ask you @Viraculous @AyAyRon-P @ysgjay @pmoorman @pavlos1851 @zsluedem   to support us in Translation for Russian-speaking community because we really can add value to RChain.

**Comment by kovmargo** [comment]
@luigidemeo what do you mean by 'sponsor' ?

**Comment by luigidemeo** [comment]
A department of Rchain (i.e. marketing) will need to sponsor this work. Essentially you need to find somebody willing to pay for it.
