### ISSUE TITLE
Translation: Metrics and Value system

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#960]
**Target:** The aim of this issue is to prioritize the essence of translation, get an established metrics and value system for translation. 

**Purpose:** Translation has been one the uprising concerns amongst others in the bounty system with serious contentions on the value and metrics. More of the concerns are centered on spending on translations without any significant market for the locality that is being translated for. 

Information from the Budget and reward sheet shows that an estimate of **$170,000** has been spent from March to August(6months) on translation. Particularly, **$22,000** was spent for translations in the month of August with little or no audience for the translation. The budget on this does not match the result.

Translations are currently being posted on two main channels; Medium and RChain Worldwide community forum. Each translation seems to have a separate medium account.

**Here is a list of the media channels and followers**

[RChain Greek](https://medium.com/@rchain_ru) 0 follower
[RChain German](https://medium.com/@rchain_ru) 2 followers
[RChain Polish](https://medium.com/@rchain_ru) 0 followers
[RChain Ukraine](https://medium.com/@rchain_ukraine) 1 follower
[RChain Russia](https://medium.com/@Rchain.RUS) 0 follower
[French(@casanwugo's personal medium](https://medium.com/@annchidinma5)) 271 followers
[RChain Spanish](https://medium.com/@rchain_es) 0 follower
[RChain  Italian](https://medium.com/@rchain_it) 4 followers
RChain Chinese( I see no channel where Chinese translations are being posted)
[RChain worldwide community XYZ 
](https://rchaincommunity.xyz/) has only about 43 registered users.

**Recommendation:** 
- Replace human translation with automated translation; The essence of translation is communication, understanding, and interaction with non-English speakers. The automated translation may not be perfect but I think meets that requirement 70-80% especially for the non-technical document. (Except for technical documents)
- Translation of technical documents will be at the approval of the dev-team and the marketing team.
- languages to be translated to should be determined by the marketing team. Otherwise, send a request to the marketing team stating valid reasons why the doc(Technical) should support other languages.
- Amongst others, viewership(not just from anybody but from the locality of the translation) should be the ultimate metric for translating a document. 

**CTA**
- Get in touch with the TAC and Marketing team to get this effected starting fully from October.

**Budget:**  ???

**Comment by luigidemeo** [comment]
is there a suggested budget for this task. In general i agree with the approach.

**Comment by Viraculous** [comment]
@luigidemeo for now the budget is quite tentative.

**Comment by dckc** [comment]
See also my proposal to reboot all labels: https://github.com/rchain/bounties/issues/783#issuecomment-420802890

**Comment by AyAyRon-P** [comment]
@Viraculous @luigidemeo there is currently no budget in place for translations. Each time there was a translation issue presented, the question was always asked "is there an audience?" to which someone would reply with some long winded copy+paste from wiki/google about "how XXmillion people speak the language", "how it's a technology advanced country", and "how we need to be a global community and not only English speaking" etc, etc, etc 💩 

None of those answers are good enough and quite frankly I'm glad that we're shutting down the translations label because it's a massive waste of resources. The only translation I see of value right now is Chinese because we have a sizable following and member base in China.

**Comment by Viraculous** [comment]
@AyAyRon-P  thank you very much. I have no issue at all with translations but mainly concerned about the audience and a statistical reason why documents should be translated into their language. You said 
>. The only translation I see of value right now is Chinese because we have a sizable following and member base in China.
>
There are basically 3 reasons why I also think the Chinese translation of value.

1. People proficient in English in China is [less than 10%](https://en.m.wikipedia.org/wiki/List_of_countries_by_English-speaking_population) of [1.2 billion](https://www.internetworldstats.com/stats8.htm) of their population which is very low.
2. China technologically improved having a good knowledge of blockchain.
3. China has a great deal of audience around RChain(Though the entire population is a factor because they are the highest most populated country in the world).
For me, any country that meets these criteria is good for translation.
Secondly, even for Chinese, I think google translate would serve for non-technical document except for the critical ones. But on second thought, I think if a translation work meets the value above, it would increase member participation and as well employment of skill to use for members to take up the task provided it is within the budget scope. 
Thirdly, this issue as you can see was raised to streamline translation issues until there is a clear metric for it. With your comments above, I am persuaded to close this issue but will be leaving this questions.
Seeing that money has been spent on translation, what then will happen to the translation document up on medium without an audience? Do we leave them there to lie valueless or get them across to channels where they can be read and valued while it has been suspended? I still believe value could be gotten from those  translations, it's all about taking the the right channels and socials where they can be valued and spread the good news about RChain.

**Comment by dckc** [comment]
This has a large overlap with #483. Let's use that one if there's any more discussion on this.

**Comment by kaka56** [comment]
@dckc how do we continue with the discussion when both issues are closed with no conclusion ?
At least one should be left open.

**Comment by dckc** [comment]
Issues can be reopened by anyone who intends to do more work on them.

Is there actually more work to do here? Doesn't the comment in #483 noting the reboot address the issue raised here?

**Comment by kaka56** [comment]
Alright cleared
