### ISSUE TITLE
Translation of 5 blog posts into Spanish

### ISSUE THREAD

**Issue by michaelizer1** [rchain/bounties#963]
### Benefit to RChain

The translated material will server the Cooperative to reach a larger audience and help the expansion of the community building. 

Translations will be posted both on the [RChain Worldwide Community Forum > Spanish (Español) > Blog (Blog)](https://rchaincommunity.xyz/c/Spanish-Espa%C3%B1ol/Blog-Blog), and the [RChain Cooperative (Spanish) Medium account](https://medium.com/@rchain_es).

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$622.8 + ($622.8 * 10% = $62.28) = $[685.08]**
_Estimated Timeline Required to Complete the Task:_ **[10 days]**
_How will we measure completion?_ **Translations will be posted both on the [RChain Worldwide Community Forum > Spanish (Español) > Blog (Blog)](https://rchaincommunity.xyz/c/Spanish-Espa%C3%B1ol/Blog-Blog), and the [RChain Cooperative (Spanish) Medium account](https://medium.com/@rchain_es).**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [x] at least two of them have either
       - [x] formal training: degree / certificate: Proficiency (@ICA3DaR5), Proficiency (@zero-andreou), Lower (@zero-andreou) from institution: [University of Michigan](https://www.umich.edu/) (@ICA3DaR5), [Edexcel](https://qualifications.pearson.com/en/home.html) (@zero-andreou), [Cambridge University](https://www.cam.ac.uk/) (@zero-andreou)
       - [x] a track record of quality work on rchain bounties: #244, #265, #286, #287, #288, #292, #299, #345, #363, #390, #447, #475, #497, #540, #585, #586, #597, #621, #650, #652, #686, #688, #715, #719, #721, #738, #757, #842, #859, #905, #909, #923
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

### Original (English) Content

- [RCHAIN DEBRIEF 92: VALIDATOR ECONOMICS](https://blog.rchain.coop/rchain-debrief-92-rcon3-week/) (860 words, $129.60)
- [INTRO TO DESIGN OF COMPUTATIONAL CALCULI 1](https://blog.rchain.coop/intro-to-design-of-computational-calculi-1/) (1,760 words, $264.00)
- [RSONG: THE FUTURE OF MUSIC](https://blog.rchain.coop/rsong-the-future-of-music/) (697 words, $104.55)
- [RChain Debrief 93: RCon3](https://blog.rchain.coop/rchain-debrief-93-rcon3/) (187 words, $28.05)
- [RChain test net genesis ceremony](https://blog.rchain.coop/rchain-testnet-genesis-ceremony/) (644 words, $96.60)

### Translated (Spanish) Content

-
-
-
-
-

**Comment by Viraculous** [comment]
@michaelizer1 see my comment on issue #961and also my thought on issue #960. Is there a Spanish audience yet for this translation? Translating without question has benefit to RChain but the question is, what is the value(What is it worth if there are no audience for it). For now am attaching the "Suspend work" label until there is a clear metrics(veiwers within the locality) around this issue

**Comment by dckc** [comment]
Lacking response to questions about audience, let's close this.
