### ISSUE TITLE
Decentralized organizations & Cooperation at Scale Animated Explainer video

### ISSUE THREAD

**Issue by Cryptovideos** [rchain/bounties#964]
Benefit to RChain
An explainer video on Decentralized organizations & Cooperation at scale , How we as Rchain operate.

- [x] Script dev & creation
- [x] Voice over production and editing
- [x] Animation and Video editing / special effects
- [x] Audio mixing and backing track

Estimated Budget of Task: $[1800]
Estimated Timeline Required to Complete the Task: [1 week]
How will we measure completion? [https://youtu.be/VWgLiv8DpjM]

**Comment by Cryptovideos** [comment]
Going forward it shall be as suggested

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Cryptovideos** [comment]
**Manifested by our community members**
 : 
    Be a self-starter :: because there is no boss, nobody is going to tell you what to do. Being a RAM is much more like being an entrepreneur than it is like being a employee.
        todo: advice on finding a mentor; cf. onboarding #253
    Think for yourself :: The coop works together like a swarm of insects does... but we need to avoid herd-thinking. We rely on independent thinking, and speaking up when you think we’re going the wrong direction. Independent thought makes the coop stronger.
    Get things Done :: We value the guy that steps up and executes. Having opinions is easy, but doing the work is hard.
    Morals matter :: The crypto space is a wild-west landscape, where it’s our own job to figure out our moral standards, and stick to them. We believe in transparency, openness, and fairness. But it’s ultimately up to our members to create and guard those values.
    Be nice to each other :: Most of our work happens online, distributed, remote. Be nice to each other, and easy to forgive. Even if you disagree, remember that we’re all working towards the same goal.

**Comment by Cryptovideos** [comment]
https://github.com/rchain/bounties/wiki/Welcome-to-the-Bounty-Program

**Comment by jplepel** [comment]
Being a self starter is encouraged. Entrepreneurs are often asked for a business plan and identifying target markets. Doing work behind closed does and then suggesting a bounty is counter productive. Think of the bounty system as investors in your startup. If that was the case, this issue essentially took investor money before they even saw the business plan.

**Comment by jplepel** [comment]
Morals do matter... And this issue was created with poor moral standards. We live and we learn. Could we also get a detailed cost analysis on the suggested budget? I am not familiar with cost of script, voice and animations.

**Comment by Cryptovideos** [comment]
your opinion on morals is incorrect and i dont agree sorry

**Comment by Cryptovideos** [comment]
then start familiarizing yourself
i try stick to the 'Lower side" of the scale all the time ;)
https://www.videobrewery.com/blog/how-much-does-an-explainer-video-cost/ 
http://tubularinsights.com/animated-explainer-video-cost/
https://hingemarketing.com/blog/story/what-is-the-cost-of-video-production-for-the-web

**Comment by Cryptovideos** [comment]
> Being a self starter is encouraged. Entrepreneurs are often asked for a business plan and identifying target markets. Doing work behind closed does and then suggesting a bounty is counter productive. Think of the bounty system as investors in your startup. If that was the case, this issue essentially took investor money before they even saw the business plan.

but you obviously didn't listen to me then did you now? i told you already this has been planned and discussed with @allancto and even chages were made to the original draft video ... so NO very the plan was set in place...i just failed to raise the issue early on... but as you said...you live and you learn.....

**Comment by jplepel** [comment]
> Morals matter :: The crypto space is a wild-west landscape, where it’s our own job to figure out our moral standards, and stick to them. We believe in transparency, openness, and fairness. But it’s ultimately up to our members to create and guard those values 

> 

What about this bounty was transparent, open, and fair? 2-3 people made the executive decision to make this video without consulting Marketing. The work was completed before the bounty was made. If membership votes this issue down, the work done prior to opening the issue is wasted.

**Comment by Cryptovideos** [comment]
thats a really good point @jplepel but i am yet to have negative feedback on ANY of my work - it seems its only you thus far? and when i discuss ideas with people i respect and look to for advice etc and they tend to agree on the task at hand i execute it - out of all the issues / jobs iv done - this is the forst and ONLY time iv missed the mark by creating and issue late after work etc... and i cant keep going around in circles with you - iv already apologized for that

**Comment by jplepel** [comment]
No problem. I'm taking a close look at this week's new issues submitted, this is one of them. I am not questioning the quality of your work. I am questioning the community if this work is within scope and the best use of the co-ops funds, as well as the process in which issues are created.

**Comment by Cryptovideos** [comment]
understood and i hear you on all you are saying -

**Comment by Viraculous** [comment]
@Cryptovideos I truly cherish your idea of being a self-starter and working independently. You said 
>We rely on independent thinking and speaking up when you think we’re going the wrong direction. Independent thought makes the coop stronger. 
> 
For surety independent thought can make the coop stronger but certainly not a non-directional thought. Soliciting from the marketing team for a scope doesn't make you lose your autonomy but rather narrows the though in line with the organizational need. One thing I find out with the bounty system is, we've got lots of talent but very few have been able to identify what the community actually needs to move forward and cooperate. We do things with benefits without actually creating a value for the community and that's why the feelings, thoughts and concerns reflects the bounty system as a wasteful commitment by the coop.

**Comment by owans** [comment]
I admire your idea generation @cryptovideos,the value this issue produces is quite obvious,in as much as we're looking to 'align' the coop bounty system values,let's also take time to appreciate effort.

**Comment by Viraculous** [comment]
@Cryptovideos I see this issue is completed and video uploaded on youtube. Can you make the link on the issue click-able?

**Comment by dckc** [comment]
I see @PatrickM727 budgeted $1800 for this; I just backed that vote with my own.
