### ISSUE TITLE
Translate Debriefs and some latest blog to Chinese

### ISSUE THREAD

**Issue by yyh1102** [rchain/bounties#966]
### Benefit to RChain

- [x] [WHAT’S YOUR MUST? DISPATCH FROM RCON3](https://blog.rchain.coop/whats-your-must-dispatch-from-rcon3/) 196 word
- [x] [RCHAIN TEST NET GENESIS CEREMONY](https://blog.rchain.coop/rchain-testnet-genesis-ceremony/) 676 words
- [x] [RCHAIN DEBRIEF 93: RCON3](https://blog.rchain.coop/rchain-debrief-93-rcon3/) 208 words
- [x] [RSong](https://blog.rchain.coop/rsong-the-future-of-music/) 715 words

Tip1: I think the post [RSong](https://blog.rchain.coop/rsong-the-future-of-music/) is very important and worth to be translated because it may be a model of application built in RChain, and will attract more developers and investor from China.

Tip2: We use Typora to count the words

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[359]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [x] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [x] at least two of them have high proficiency in _the target language_
    - [x] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [x] a track record of quality work on rchain bounties: #882 , #899 , #924  ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [x] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by zsluedem** [comment]
@yuhuanmocmoc The whole bounty program is rebooting. The Asia bounty program is still drafting. And the budget of this issue is possibly not rewarded in the future. Just want to let you know that.

BTW, the translation of your content are partly google translating. 

```
Standard Apple headphones are not known for warmth; the bass response is commendable for earbuds, but the delicacy required of a nuanced performance is lacking. Plugging the phones into my ears and hitting play, I was immediately captured by the spatial segmentation of each instrument. The separation of elements was apparent, no small feat given the medium. For the first time, I felt like I was listening to what the artists envisioned, the swelling of guitars and violin, the soft vocal harmonies, a swirling of gorgeous forces.
```
in the [Rsong](https://blog.rchain.coop/rsong-the-future-of-music/)

to 
```
标准的Apple耳机并不以温暖的音质出名，其低音的音质对于耳塞来说是不错的，但依然缺乏精致的音质细节。将手机插入我的耳朵并进行播放，我会立即被各个乐器的空间分段捕获。元素的分离是显而易见的，鉴于媒介，这是不小的成就。这是我第一次感觉到我正在聆听艺术家的音乐，吉他和小提琴的膨胀，柔和的声调和声，以及华丽力量的旋转。
```

which is not really good translation.

**Comment by rjl493456442** [comment]
> The whole bounty program is rebooting. The Asia bounty program is still drafting. And the budget of this issue is possibly not rewarded in the future.

So it means the blog translation may not be encouraged by cooperative in the future right?

**Comment by yuhuanmocmoc** [comment]
@zsluedem We will fix the bug, and heighten  our review work in the future, but if the bounty rules of blog translation are still in consultation, i think all of us should stop translating!

**Comment by dckc** [comment]
@zsluedem writes:
> @yuhuanmocmoc The whole bounty program is rebooting.

For details, refer to https://github.com/rchain/bounties/issues/783#issuecomment-423171144
