### ISSUE TITLE
Translate blog post ,RCHAIN UPDATE 94: FEEDBACK FROM RCON3 to Russian and Ukranian

### ISSUE THREAD

**Issue by irynapopova61** [rchain/bounties#967]
### Benefit to RChain

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:*
*Get in touch with a guide (https://github.com/rchain/bounties/wiki/Bounty-Task-Guides ) to align your contribution with goals of the RChain cooperative.*
*Replace these 3 lines with your answer*

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[000]**
_Estimated Timeline Required to Complete the Task:_ **[days/weeks]**
_How will we measure completion?_ **[example: pull request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

### Translation Checklist

*for non translation issues, delete this section*

  - Why translate this document?
    - It's important to translate because ____
    - [ ] It's an RChain blog item on [Medium](https://medium.com/rchain-cooperative)
    - [ ] It's an RChain blog item on https://blog.rchain.coop/
    - [ ] It's a document on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in _the target language_
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] formal training: degree / certificate: ___ from institution: _____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
       - [ ] another body of work readily available for community review: _____
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

_**Word counting and pricing for translations will be done with [The World's Fastest Human Translation Service](https://customer.stepes.com/instant-translation-quote/#)**_

**Comment by kovmargo** [comment]
@irynapopova61  Please, close issue - the artice is already being translate at issues #950 and #959 

Please, use search option inside of issues before you are going to add new issue. Thanks!

**Comment by dckc** [comment]
"Benefit to RChain" section is not filled out.
