### ISSUE TITLE
RContributors: Rebrand the “Bounty System"

### ISSUE THREAD

**Issue by allancto** [rchain/bounties#968]
### Benefit to RChain

Recent discussions have exposed an important problem we have communicating who we believe we are. The problem stems from a name which is out of sync with what we actually do and how we accomplish it. Communicating clearly that we are RContributors and not "bounty hunters" will go a long way towards properly aligning ourselves with the RChain community at large. 

### Description

What we strive to do every day is to contributing along with our fellow members for the betterment of our Cooperative. 

#### Are we “workers”? 
RContributors are NOT workers. the term “bounty” suggests that people are working for a specific reward. In a few cases that may be  true: there is a very specific requirement that’s been laid out and can be measured with a relatively clear metric such as story points. But the bulk of our projects are self initiated: people with ideas want an opportunity to implement and prove our ideas valuable. To not be a worker, to be an entrepreneur. It’s not charity and it’s not performance to specification. We aspire to contribute and be voted cooperative tokens of reward for our contribution. 

#### Are we hodlers? 
RContributors SHOULD hold rhoc. This is truly important. By its nature rhoc is designed as an asset of our Cooperative, the ledger of contributions by members of time, capital, skill, reputation, opportunities. Being all in the same “lifeboat” together, with our aspirations tied to the long term value of rhoc, aligns our interests. I want to post a separate issue with proposing that Contributors be required to have a holding period or “lockup” for a significant portion of the rewards they are voted. My preliminary discussions indicate that most RContributors are in favor of this. Many of us do it already for exactly the same reason that other members do: we believe in each other and in the future market price for rhoc. Please save comments directed specifically at the question of lockups for that issue. The important point here is I want to state unequivocally my personal wish that all Contributors, and probably all members of our Cooperative, be long term holders of rhoc. 

#### Are we useful? 
RContributors suggests we are: we contribute. I feel i can speak on behalf or almost all contributors: we want to be, we hope to be, we do our best to be. Of course people have a wide array of perspectives on what is indeed useful. Particularly in a project like this, where outcomes may not be evident for weeks, months, years, even lifetimes. So many of our discussions of utility reflect personal opinion. We attempt to value our contribution through a voting system designed to reflect trust, reputation, and competence to assess contributions in particular areas. Our voting systems are clearly primitive but they are getting better. Our voting systems are our best effort to adapt free market economics towards budgeting. 

The words of @lapin7 accurately describe our aspirations and our actual practice. 

>Some important things that new RAMs should be aware of:
* Be a self-starter :: because there is no boss, nobody is going to tell you what to do. Being a RAM is much more like being an entrepreneur than it is like being a employee.
* Think for yourself :: RAMs work together like a swarm of insects does... but we need to avoid herd-thinking. We rely on independent thinking, and speaking up when you think we're going the wrong direction. Independent thought makes the coop stronger.
* Get things Done :: We value the guy that steps up and executes. Having opinions is easy, but doing the work is hard.
* Morals matter :: The crypto space is a wild-west landscape, where it's our own job to figure out our moral standards, and stick to them. We believe in transparency, openness, and fairness. But it’s ultimately up to our members to create and guard those values.
* Be nice to each other :: Most of our work happens online, distributed, remote. Be nice to each other, and easy to forgive. Even if you disagree, remember that we're all working towards the same goal.

Naming ourselves RContributors communicates our true relationship with our Cooperative. We are here to contribute. We are not contractors. We are not employees. We are individuals and entrepreneurs, contributing to the betterment of our Cooperative to the best of our abilities. We are not volunteers or charity workers. We expect to be properly and fairly rewarded for our contributions, through an open system of discussion, consensus and voting by our fellow members. We recognize the contributions of others and we work side by side with all members of the RChain Cooperative. 

### Budget and Objective
[TBD]

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by Viraculous** [comment]
@allancto I am glad to see your thought on this. @lapin7 said 

>Morals matter:: The crypto space is a wild-west landscape, where it's our own job to figure out our moral standards and stick to them. We believe in transparency, openness, and fairness. But it’s ultimately up to our members to create and guard those values
>
The moral standard is a cultural attribute of the cooperative. Robert Owen, the father of cooperative have always emphasized on the role of moral values amongst workers of the cooperative in getting the task accomplished and building a fairer worker environment.

The role of moral standard in the bounty system cannot be overemphasized. I and @jimscarver and a few others had discussed on the need of implementing the 5th principle of cooperative into the bounty system. "Education, training and information", Educating the members, training the officials and informing the general public. This will lead us into more transparent, open and fair contributions against selfish and greedy contributions. With these values being predominant in the system, cooperation at scale becomes more difficult.
Perhaps we need to go back and review the seven principles of cooperatives and align it with the bounty system. 
Here

- Voluntary, Open Ownership. Open to all without gender, social, racial, political, or religious discrimination. ...
-Democratic Owner Control. One Owner, one vote. ...
-Member-owner Economic Participation. ...
-Autonomy And Independence. ...
-Education, Training And Information. ...
-Cooperation Among Cooperatives. ...
-Concern For The Community.

**Comment by luigidemeo** [comment]
I am not sure this is about re-branding. For me, until there are budgets with each RChain "department" and they feel every RHOC spent on their behalf, they system will not work. Changing the name does not do much, its the actual work being done that is more troubling.

**Comment by allancto** [comment]
@luigidemeo , @ddayan , @Viraculous , @ysgjay ABSOLUTELY, we need to BE relevant, not just SAY relevant. Will you help? 

Let's start with "department", here's a brief doc speaking to what these might be (in our github system we've been overloading "Label" to represent "department"). Do you think the set of labels suggested in this doc accurately represent Cooperative imperatives? 
https://docs.google.com/document/d/1Amk--A2fNMllAVSDFmtkY0j_L_7u8-Clt9hpIghJ_8U/edit#heading=h.ffq5ze16vda9

Now about projects representing value "for every rhoc spent". You've already been constructive in providing support for #956, #919, #913. Can you help to demonstrate consensus with others that these issues are indeed providing value? 

Here are a couple of issues you might weigh in on the value of. They have no suggested budget and require better issue statements, but you might consider helping to shape them 

* As RContributors we should be proactive in aligning ourselves with all rhoc holders within the community: #969. 

* As RContributors we can support and leverage Cryptofex IDE: #970. 

Thanks @luigidemeo , @ddayan , @Viraculous , @ysgjay!

**Comment by dckc** [comment]
> @allancto I am glad to see your thought on this. @lapin7 said
> 
> > Morals matter:: ...

I wonder where anybody got the impression that @lapin7 said that.

It comes from @pmoorman Feb 14; see https://github.com/rchain/bounties/issues/370#issuecomment-365823292 (oops; I neglected to acknowledge him in https://github.com/rchain/bounties/commit/4d3f62d688bbe2ef4549950bc516b8eca5ef7dfa)

**Comment by dckc** [comment]
I wonder if there's anything new here since last time we picked a name: #267

**Comment by dckc** [comment]
@allancto writes:
> We are not contractors.

Well, that's what we're called in the filing system. The registration form linked from CONTRIBUTING says _You also have a personal folder. Access is for you and some internal RChain folks. RChain/Contracts/Contractors_.

> RContributors are NOT workers.

The process from the Apr 6 board decision (quoted in https://github.com/rchain/bounties/wiki/Task-Approval ) says "... Project Submitter may begin work on the Project ..."

**Comment by pmoorman** [comment]
Thanks @dckc for providing a bit of a background / history on this. I indeed wrote the piece that was attributed above to @lapin7 although obviously I was just capturing in words the approach that people like HJ, Dan and others had already established.

I think the link to #267 is also very relevant, and it'd be wise for everyone to read up on it, lest we'll just go around in circles!

Maybe I can contribute a little here by just pointing out what comes to mind when I see this issue:

1. Certainly @luigidemeo is right that naming isn't the foremost issue. That said, the naming can still be confusing of course.

2. In the issue description, I don't relate to the HODLer section. As far as I can tell, that's for everyone themselves to decide. While some choose to HODL, others choose to use it to pay the rent (!!). Both uses are fine, as far as I can tell. To me, it's more about the value you contributed that got you the RHOC, rather than what you do with it afterwards. That section confuses/mixes matters, in my opinion.

3. Reading through the values that I jotted down back then, I think most still hold true. The main thing that's troubling me is that in some circumstances the ecosystem makes it very hard for people to actually "be a self-starter", so that's maybe the most promising thing we could actually work on.

4. I would suggest we treat this as a `discussion` as per Dan's suggestion. @allancto maybe you could clarify specific actions / changes we're aiming for here? 

5. I'm undecided whether I like "RContributers" more than "RAM". RAM isn't great, but many people will hopefully contribute to RChain without being "RContributors", thus making that name confusing, too. For now, I would probably stick with RAM just because it's simpler. (again, see #267)

**Comment by dckc** [comment]
After a week of discussion, the only positive feedback I have seen is about material that is already in our [README][r], i.e. material that is already part of our branding.

In the interest of keeping the open issues list focussed, I think it's time to close this as **wontfix**.

[r]: https://github.com/rchain/bounties/blob/master/README.md
