### ISSUE TITLE
Regular Marketing Zoom meeting to educate and inspire

### ISSUE THREAD

**Issue by philipandri002** [rchain/bounties#976]
### Benefit to RChain:
1.Improve the marketing department 
2.Motivate members for effectiveness and commitment
3. Boost the marketing department for increases productivity
4. It encourage creativity 

### Description 
The Role and function of an aggressive marketing department cannot be overemphasized. It is the brainbox for sustainability and the continuity for any organization. Whether the ideology, vision, product or service will get to the people who may need to use it rests on the shoulders of an aggressive marketing department. 

Marketing is said to be the bridge between the producers and the users. No matter how great a product is, there has to be a proper awareness of the product, that can boost peoples confidence to at least give the product a trial before they can become convinced afterwards. 

This is the reason I took my time to share some knowledge as my little way of contributing in building a more aggressive, productive robust and scalable marketing department in RChain. To inspire result oriented team workforce and effectiveness. I hope this inspires and add some sort of value to the coop especially the marketing department.

To have a viable and effective marketing department, I believe Education as agreed by myself, @Jasoncruzzy @Jimscarver, and others cannot be overemphasized. I pointed that repetition is the law of deep and lasting impression. There has to be purpose driven educational or learning sections for the marketing department as  this will help to educate members or the marketing team on the core values of  the RChain ideology, label goals & purpose, results expectations.

Below, I have shared some Marketing ideology:

To have a great marketing department we have to take  cognizance of the fact that;

1. Marketing bridges the gap between a products/service and its users. Its is the job of the marketers to convert a products from a state of production to consumption. Like it is said that production is not complete until it gets to it final consumers/users.

2. Creating the necessary awareness, noise and publicity of the product to gain users attention also known as (Hype). 

3. Engaging the Market: this role is a special one which aims at building people's confidence on a particular product. Sometimes it goes as far as telling the people why they need the product and what value it will be to them.

4.Feedback: effective marketing cannot displace the role of data collection and feedback reporting. It is from feedbacks gotten from the market that enables organisations to plan, forecast and strategize.

 Marketers listen to what are users perception about the products/service, response to the product, what are the product  market advantage or disadvantage and report ( data collated)  to the organisation for planning, improvement or adjustment.

These are but a few guides necessary for training and building a viable and aggressive Marketing department. Like I stated above my intention is to help our marketing team unleash full potentials and become productive.
 
There is a need to put the marketing house together so that individually and collectively we can achieve our goals and objective for the Coop. To harness a department with so much potentials and responsibilities, it has to have a structure, a well planned strategic approach must be put in place as it cannot depend on luck.

There are few things we must emphasize

1. Our Goals And Objectives: what are our goals and objectives, i.e what do we aim to achieve at a certain period of time, whether they are short terms goals or long term. We have to clearly define our purpose and explain it in the simplest of terms for everyone to have a complete understanding of what we are here for. Sometimes it's misleading to think that everyone knows, when they don't even know, some of us may even think we know but it may not actually be what we thought it is. 

2. Communication: relationship works best when there are no communication gap whether in a family or in an  organization. A bridge in communication can lead to abuse and misplaced priority.( which has been the case here). Communication plays a major part for the success of any organization. Therefore we must priotise and increase avenues that will prompt easy communication and access between everyone one of us.

 3.Team work: there is a saying that" two good heads are better than one" When people come together with one mind and heart to give their best collectively it increase productivity and efficiency more than individuals efforts. It is team spirit that makes a football club outstanding. Team spirit means; " the interests of the team supersedes our individual interests " yet when the interests of the team is met, all of our individual interests also is met.

4. Motivation: members needs to be continually inspired to give out their best shot. Motivation is a force, its like fuel that drives an engine. We cannot get people's ultima participation when they are frustrated and unhappy. Therefore we must look out for ways to get team members motivated to give us their full committment. Incentives and acknowledging people's effort is one way to inspire and motivate people.

5. Happy work Environment: people perform better when they feel comfortable and happy in doing their job. An environment surrounded with love and appreciation is not too much to ask, if that is what it takes to achieve our set goals. We shouldn't give room for anger, bitterness or selfish unhealthy competition/ intimidation. People should be able and allowed to express themselves, ideas and contributions without fear or inferiority. We are friends and we are family and we must promote that at all times. This will boost people's confidence in themselves which will lead to effectiveness. When a member makes mistake or you do not agree with their opinion, you can be kind in expressing your views, disagreement and opinion and even when making corrections. We don't have to hurt one another to express our opinions.

6.Result Oriented: Finally, above everything is to get it done what we have set out to achieve. Everything we do must be result driven. The idea is not to meet our individual interest but that of the coop which in return will meet our interest. We must be ready to sacrifice our selves so that we can make the RChain coop a force to reckon with.

Our passion should be on achieving results that aligns with the RChain mandate... To achieve result, it has to be base on the S.M.A.R.T agenda or principles (Specific, Measurable, Achievable, Realistic, Timely) principle.. 

### MY RECOMMENDATIONS/ PROPOSAL

To Marketing Guides/RAM

 @pmoorman @AyAyRon-P @Kitblake @pavlos @dckc @jimscarver @allancto @ddayan @Viraculous @Patrick727, @casanwugo and others ( we need all the marketers to see this and give their opinion) you can add to the list names of persons you think are necessary to contribute.

### Marketing Zoom meeting:
I am suggesting that we take out time to educate and inspire ourselves on a regular bases. 

### Benefit of such meetings:

1.A meeting section of such maybe twice in every month, gives us the opportunity to discuss within ourselves and also educate ourselves, share ideas, talk about some challenges and brainstorm for solution.

2. In meetings like this, emphasis are made on the goals and visions and what strategy we must apply to achieve results. 

3. Feedbacks.. We return feedbacks (market analysis) from the field and that will help us to strategies and position or make necessary adjustments if need be.

4. Ideas and testimony can be shared. People should tell us about challenges they faced, how they managed it, and made it work.

5. Training sections : This will serve also as training and learning section to keep improving / sharpening our members marketing skills and ideologies.. (Education)

6. Fun : a meeting like this will be fun as it will help to unite and brings us together. 
 
I will also recommend a sort of bounty to be set aside as an incentive to motivate a greater participation and committed members.

Thanks and I hope we find this valuable.

Please feel free to contribute, and make corrections and recommendations as you deem fit.

Thanks! 
Philipandri002.

### Budget and Objective
Estimated Budget of task[TBD]

**Comment by pmoorman** [comment]
hey @philipandri002 since we're in the middle of a "reset" of the bounty system (which certainly impacts marketing, too), I'd rather hold off a bit on more meetings.  We should first get clarity there, before we move forward with such ideas.

If marketers want to come together and share insights / ideas / etc. that's of course welcome. I'm not sure I myself want to commit to more meetings, but I can only speak for myself.

Maybe not the best response, but the best I can do for now. If you're feeling like putting such a meeting together already then by all means go for it. And let's hear what others think of this idea, too.

**Small tip:** 
For readability maybe create a 1-line summary of your idea in the top of the description? Or better yet rephrase the headline to something more descriptive? (e.g. "regular marketing meetings to discuss XYZ" or something like that)

**Comment by Viraculous** [comment]
@philipandri002, point 1 and 3 to me are quite the same points about improvement but I did like the area of education. Can you integrate your comments to a simpler form with CTAs for a clearer angle of perception?

**Comment by AyAyRon-P** [comment]
This is thoroughly thought out and I appreciate you crafting this proposal @philipandri002. 

My concern for more meetings from the COOP and building this "marketing department" are the issues we would be discussing are only speculative in nature and bottom-up in terms of processing and need. This is exactly what has been happening slowly over the past few months and has caused the misalignment of bounty system marketing vs official RChain marketing needs. What we need at this time, through the reset and beyond, is to get our objectives from the top-down before proceeding with anything if we are to ever truly be a functional bounty system for the benefit of RChain.

**Comment by dckc** [comment]
My first thought (once I figured out what's proposed here... more on that below) ws: oh no, not another meeting.

But there's kind of a lot of... um... chaos in the relationship between the bounty system and marketing. So maybe getting together to talk regularly would help things gel. Developing an effective meeting series looks quite challenging, but I'm going to reserve judgement for a bit before deciding whether it's worth a try.

p.s. Don't bury the lede! That is: don't make me wade through a page of text before I get to "I am suggesting that we ..." I tweaked the title to clarify.

**Comment by Viraculous** [comment]
@dckc nice one. The tweak was helpful.

**Comment by dckc** [comment]
@philipandri002 I recommend you perform the experiment. Start negotiating a meeting time; that is: propose a specific time as well as two or three alternatives; [doodle](https://doodle.com/) works well for this, in my experience. And start preparing an agenda. See how many confirmed attendees you can get.

Aim to conclude the meeting time negotation and call the meeting _a week in advance_.

**Comment by dckc** [comment]
The **Benefit to RChain** here needs work. "Improve the marketing department" isn't objective. [How long is a piece of string?](https://en.wiktionary.org/wiki/how_long_is_a_piece_of_string) Most things can always be improved. Improve it how much? In what way?

**Comment by Viraculous** [comment]
Yea @allancto, Patrick and the marketing team are working to check marketing issues on the bounty.

**Comment by philipandri002** [comment]
@allancto awesome.

**Comment by philipandri002** [comment]
@Viraculous great to know. I hope everyone willing to commit to this are carried along. Please can elaborate more on the team stuff I need to know who exactly are involved, seem you know

**Comment by philipandri002** [comment]
>  @philipandri002 @pmoorman @Viraculous @AyAyRon-P at today's debrief a weekly marketing "office hours" zoom was announced, not specifically addressed at bounty, and also Patrick did indicate he's working now to identify marketing bounty projects.Marketing Office Hours Tuesdays 9am – 10am, https://zoom.us/j/866980752.                            



@allancto I'm sure you busy but I need to know if the meeting held and how did it go. I wasn't available at the scheduled time of the meeting @patrick727 @pmoorman @Viraculous @AyAyRon-P

**Comment by AyAyRon-P** [comment]
@philipandri002 the meeting went well and ran for approximately 1 hour. A large portion of the office hour was spent discussing developer progress, bug bounty and the new channels used for that, and lastly the topic of the bounty system. Currently there is a great deal to be budgeted for specifically breaking down certain tasks and passing those onto the bounty system being part of that. It was a good first meeting but incredibly broad in scope and how we(RAM Bounty System) can align itself with RChain Marketing Org.

**Comment by philipandri002** [comment]
@i sure missed alot @AyAyRon-P thanks for the info. Is there a way I can get the details, like is there a video link or something and when is the next meeting holding.

**Comment by philipandri002** [comment]
@dckc do think it's appropriate to ask for a vote of budget for this issue?

**Comment by dckc** [comment]
This is a discussion, not a complete task proposal. The only bounty budget norms established since the reboot are for core-dev and developer education. The work of organizing and running a meeting was done by staff.

No, I don't see support for a budget for this issue.

**Comment by dckc** [comment]
This looks like it's taken care of by the Tuesday office hours.

Anyone who wants this to remain open, please clarify what other important work there is to do.
