### ISSUE TITLE
Cloud dApp Deployment Tools

### ISSUE THREAD

**Issue by allancto** [rchain/bounties#977]
### Benefit to RChain

Better development tools will help dApp developers deploy sooner. 

This issue if properly formulated would be sponsored by the dApp development community (@kvalentine, @nedrobinson). 

For reference an existing project in the ethereum space is Infura: 
>"[YOUR ACCESS TO THE ETHEREUM NETWORK](https://infura.io/)"
Our easy to use API and developer tools provide secure, reliable, and scalable access to Ethereum and IPFS. We provide the infrastructure for your decentralized applications so you can focus on the features.

Help_Wanted: detailed proposal for one or more projects in this area. 

### Budget and Objective

_Estimated Budget of Task:_ **$[TBD]**
_Estimated Timeline Required to Complete the Task:_ **[TBD]**
_How will we measure completion?_ **[TBD]**

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
Are we confusing Infura (a service) with Truffle (a development tool) here? I'm a little fuzzy...

**Comment by dckc** [comment]
I'm tidying up the list of Development issues. It seems that noone is even available to clarify what's desired here.
