### ISSUE TITLE
Old logo being used

### ISSUE THREAD

**Issue by plantether** [rchain/bounties#980]
@AyAyRon-P Are you in charge of branding issues?

This group is using the wrong logo:
https://sfblockchainweek.io/sponsors

cc @JoshOrndorff

**Comment by AyAyRon-P** [comment]
I can reach out to them and provide them an updated logo.

**Comment by dckc** [comment]
I don't mind your using an issue like this to reach @AyAyRon-P too much, but this isn't actually a task proposal, is it?

**Comment by plantether** [comment]
@dckc No. Sorry. I should have put this under Marketing. Or is there a better place for requests like this?
