### ISSUE TITLE
RSong Demo Highlight Reel

### ISSUE THREAD

**Issue by decentralizebanksy** [rchain/bounties#983]
### Benefit to RChain

- Consolidate the RSong Demo livestream recording into a highlight reel
- Content to create social media buzz and drive traffic to the rchain.coop website
- Increase downloads of RSong app

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*

_Estimated Budget of Task:_ **$[1500]**
_Estimated Timeline Required to Complete the Task:_ **[1 to 2 Weeks]**
_How will we measure completion?_ **[Issue Closed After Uploading to YouTube and Sharing Link in the Comment Section Below]**

https://youtu.be/ooMNSZir6IM

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by luigidemeo** [comment]
is this going to be paid by marketing?

**Comment by allancto** [comment]
@luigidemeo you ask an excellent question, and not limited to the context of this particular issue. In issue #979 i discuss a proposal in which i argue that the bounty system should be expanded and should be funded directly by vote of our membership on October 24. 

Historically, over the past 12 months, ALL bounty funding has come from the Marketing budget. While expedient, I believe it's led to many of the problems we're now addressing with our "reboot". In my opinion Bounty should exist #1 as our testnet for budgetary governance, #2 to support member initiatives. 

We've recently seen a lot of talk of departments and respected members of the community sponsoring, endorsing, supporting activities within the Bounty system. I wholeheartedly support that. It works the other way too: the Bounty system may and should be used to sponsor, endorse and support activities of departments and respected members of the community, the activities which our membership feels particularly useful and deserving of expansion and support. 

I urge you to support both by your own vote and by seeking support among our membership. The member proposal attached to #979 will give your a genuine opportunity to participate in voting the direction of our Cooperative. It will give you direct control (well, collaboratively with all of our members) at a significant yet appropriate tentative funding level of $3M plus ρ3M. "IOB to Expand, Redefine and Explicitly Fund the Bounty and RContributors Systems" deserves the support of yourself and all of our membership.

**Comment by decentralizebanksy** [comment]
No, this is a community lead initiative by @Cryptovideos. Just because it has a marketing label doesn't mean it comes from the marketing budget.

**Comment by luigidemeo** [comment]
@decentralizebanksy we are undergoing a reboot of the bounty program. Marketing will have to pay for the issue if they want it. Without a sponsor, it cannot be funded.

**Comment by Tonyprisca13** [comment]
Nice video.

**Comment by dckc** [comment]
> Just because it has a marketing label doesn't mean it comes from the marketing budget.

That's not the way I see it. Adding the Marketing label is a request for sponsorship by Marketing. Note that the Marketing label is still called **zz-Marketing**; i.e. it has not been rebooted. As discussed in https://github.com/rchain/bounties/issues/692#issuecomment-425528811 , it's unlikely that the Marketing label will get rebooted as a whole; rather, more narrow marketing-related processes will each get their own label along with budget norms.

Promotional videos would seem to overlap with Marketing responsibilities. Among the 4 pillars @PatrickM727  outlined, I suppose digital marketing, led by Amir, is most relevant. So please do get in touch with Amir ("make the relevant sociocratic connections"); @JoshOrndorff , perhaps you would make the introduction?

**Comment by Cryptovideos** [comment]
Thank you @Dan Connolly<mailto:dckc@madmode.com> for further clarity and direction ill be sure to reach out

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dckc** [comment]
I see @PatrickM727 budgeted $1500 for this; I just backed that vote with my own.
