### ISSUE TITLE
Core dev work for Sep 2018

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#985]
created in discussion with @MParlikar 

### Benefit to RChain

address [core dev team bounty tickets](https://rchain.atlassian.net/wiki/spaces/CORE/pages/105938971/Bounties+for+Development+work) (in Jira)

### Budget and Objective

_Estimated Budget of Task:_ **$8400**  56 (40 + 8 + 8) story points @ $150/story point (per #273)

_Estimated Timeline Required to Complete the Task:_ Sep 2018
_How will we measure completion?_ **[core PR request merged]**

*See CONTRIBUTING.md for details on budget and reward process.*

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment]
I just submitted [buget and reward votes on this issue][1] based on 57 story points per @MParlikar .

Great work, @AbnerZheng !

[1]: https://rewards.rchain.coop/index.php?-action=related_records_list&num=%3D985&-relationship=RewardVotes&-table=issue&--msg=Record+successfully+added+to+%22RewardVotes%22+relationship.

**Comment by zsluedem** [comment]
I made a [pr](https://github.com/rchain/rchain/pull/1472) for the core team in Seq and it was merged already. 8 story points.

**Comment by AbnerZheng** [comment]
@dckc Thanks for your help.  It is too much for me. Actually RHOL648 and RHOL 649 has been rewarded for August.  
The tickets for Sep show below. The sum of the stroy points is 40. @dckc would you please change the reward? Thank you!

|ticket| story points|
| ------------- | ------------- |
|RHOL-623|3|
|RHOL-169|8|
|RHOL-611|5|
|RHOL-623|3|
|RHOL-631|5|
|RHOL-802|5|
|RHOL-774|3|
|RHOL-651|8|






|

**Comment by dckc** [comment]
@zsluedem @xenophilia be sure to cast 14% reward votes for yourselves and get someone to back you (such as @AbnerZheng ). Voting for September work closes Oct 8, and note that I'm not available for RChain work Mon-Weds.

See also https://github.com/rchain/bounties/issues/785#issuecomment-427418399

The budget is $8400: $150 x (40 story points for @AbnerZheng  + 8 for @zsluedem + 8 for @xenophelia).
