### ISSUE TITLE
Review of Sep pay period (201809) rewards by TAC + Guides

### ISSUE THREAD

**Issue by dckc** [rchain/bounties#995]
similar to #925 for Aug, #847 for July, ...

I'm available to meet today at 11am Pacific time. Apologies for short notice. Venue: https://zoom.us/j/3287944287 . [meeting agenda / notes](https://docs.google.com/document/d/1TufZLFrBM4_z2Z7zdcqPdOyKVJ78imn3VeROcPvS6ps/edit#heading=h.9jy4wqbrxly2)

See also discussion in [#bounties](https://discordapp.com/channels/375365542359465989/418562733727023114).

 - [ ] core-dev
 - [ ] developer-education
 - ... others?

ref:
  - [Budgets for Sep](https://rewards.rchain.coop/index.php?-table=issue_budget&-limit=30&issue_num=&title=&budget_usd=&budget_provisional=&voter_qty=&voters=&pay_period=09%2F01%2F2018&labels=)
  - [Rewards for Sep](https://rewards.rchain.coop/index.php?-table=reward&-limit=30&issue_num=&title=&worker=&reward_usd=&percent_avg=&budget_usd=&voter_qty=&voters=&reward_provisional=&budget_provisional=&pay_period=09%2F01%2F2018&labels=)

### Budget and Objective

_This is not a task proposal._

*See CONTRIBUTING.md for details on budget and reward process.*

**Comment by dckc** [comment]
I'm leaning toward relaxing constraints on reward votes (but not budget votes). See https://github.com/rchain/bounties/issues/785#issuecomment-427418399

@David405 suggested likewise and @MParlikar agreed it's workable for **core-dev**, since everything is transparent and auditable there.

**Comment by Valentine-Mario** [comment]
Would the time for end of voting be adjusted considering the delay?

**Comment by dckc** [comment]
What delay? The delay in announcing this meeting? No, I don't plan to extend voting past Oct 8.

**Comment by Ojimadu** [comment]
I couldn't make it to this meeting because it happened too soon. Are there any notes?

**Comment by dckc** [comment]
Yes, they're linked from the issue description.

**Comment by dckc** [comment]
201810 is now current.

Summary of rewards for 201809, including @allancto 's work filling in for @lapin7 as discussed in #912 yesterday:

<TABLE>
<TR>
	<TH>
		count(*)
	</TH>
	<TH>
		count(distinct worker)
	</TH>
	<TH>
		count(distinct issue_num)
	</TH>
	<TH>
		sum(reward_usd)
	</TH>
</TR>
<TR>
	<TD>
		45
	</TD>
	<TD>
		30
	</TD>
	<TD>
		15
	</TD>
	<TD>
		30619
	</TD>
</TR>
</TABLE>

detail of rewards, trusted voters, and sql update code:
https://gist.github.com/dckc/bb5115d354c4d84506f4099a9b4f813c
